import { tags } from "typia";

import { ICommunityBbsMember } from "./ICommunityBbsMember";
import { ICommunityBbsCommunity } from "./ICommunityBbsCommunity";

/**
 * Summary of a trending post for the hot scores feed. Contains essential
 * information to display a post in a trending list without the full content.
 * Author and community information are included as summary objects to provide
 * context while minimizing payload size.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityBbsPost = {
  /**
   * Unique identifier of the post.
   *
   * @x-autobe-database-schema-property community_bbs_posts.id
   * @x-autobe-specification Direct mapping from community_bbs_posts.id column.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Title of the post as provided by the author.
   *
   * @x-autobe-database-schema-property community_bbs_posts.title
   * @x-autobe-specification Direct mapping from community_bbs_posts.title column.
   */
  title: string & tags.MinLength<1> & tags.MaxLength<200>;

  /**
   * Calculated hot score value determining post ranking in trending feed.
   * Higher scores indicate more trending content based on engagement,
   * recency, and vote count.
   *
   * @x-autobe-database-schema-property mv_community_bbs_post_hot_scores.hot_score
   * @x-autobe-specification Direct mapping from mv_community_bbs_post_hot_scores.hot_score materialized view column. Computed by: (upvotes - downvotes) * exp(-time_elapsed_in_hours / 12) + log2(current_votes).
   */
  hot_score: number & tags.Minimum<0>;

  /**
   * Timestamp when this post was created in ISO 8601 format.
   *
   * @x-autobe-database-schema-property community_bbs_posts.created_at
   * @x-autobe-specification Direct mapping from community_bbs_posts.created_at column.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Summary information of the author who created this post.
   *
   * @x-autobe-database-schema-property community_bbs_member
   * @x-autobe-specification JOIN on community_bbs_posts.author_id to community_bbs_member.id to get IBbsMember.ISummary.
   */
  author: ICommunityBbsMember.ISummary;

  /**
   * Summary information of the community where this post was published.
   *
   * @x-autobe-database-schema-property community_bbs_communities
   * @x-autobe-specification JOIN on community_bbs_posts.community_id to community_bbs_communities.id to get ICommunityBbsCommunity.ISummary.
   */
  community: ICommunityBbsCommunity.ISummary;

  /**
   * The main content body of the post, containing the text description or
   * article content for text posts.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.content column.
   * @x-autobe-database-schema-property content
   */
  content: string;

  /**
   * Unique identifier of the user who created this post. This is a reference
   * to the community_bbs_member table.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.author_id column.
   * @x-autobe-database-schema-property author_id
   */
  author_id: string;

  /**
   * Unique identifier of the community where this post was published. This is
   * a reference to the community_bbs_communities table.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.community_id column.
   * @x-autobe-database-schema-property community_id
   */
  community_id: string;

  /**
   * Type of the post content: 'text' for posts with body content, 'link' for
   * posts that link to external resources.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.post_type column, values: 'text' for text posts, 'link' for link posts.
   * @x-autobe-database-schema-property post_type
   */
  post_type: string;

  /**
   * Current status of the post, determining its visibility and accessibility.
   * Valid values: 'draft', 'published', 'archived'.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.status column, ENUM values: 'draft', 'published', 'archived'.
   * @x-autobe-database-schema-property status
   */
  status: string;

  /**
   * Timestamp when this post was last modified in ISO 8601 format.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.updated_at column.
   * @x-autobe-database-schema-property updated_at
   */
  updated_at: string;

  /**
   * Total number of upvotes received by this post.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.likes column.
   * @x-autobe-database-schema-property likes
   */
  likes: number & tags.Type<"int32">;

  /**
   * Total number of times this post has been viewed by users.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.views column.
   * @x-autobe-database-schema-property views
   */
  views: number & tags.Type<"int32">;

  /**
   * Whether this post has been manually pinned by a moderator or
   * administrator to remain visible at the top of the community feed.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.is_pinned column.
   * @x-autobe-database-schema-property is_pinned
   */
  is_pinned: boolean;

  /**
   * Total number of comments associated with this post, calculated as
   * aggregate from community_bbs_comments table.
   *
   * @x-autobe-specification Direct mapping from community_bbs_posts.comment_count column.
   * @x-autobe-database-schema-property comment_count
   */
  comment_count: number & tags.Type<"int32">;
};
export namespace ICommunityBbsPost {
  /**
   * Request DTO for updating an existing community post. Only allows
   * modification of the post's title and content. The author_id is not
   * included as it is derived from the authenticated user's JWT token. Other
   * fields such as status, likes, views, and is_pinned are system-managed and
   * cannot be changed via this API endpoint.
   */
  export type IUpdate = {
    /**
     * The new title of the post. Must be non-empty and no more than 200
     * characters.
     *
     * @x-autobe-specification Direct mapping from community_bbs_posts.title column.
     */
    title: string & tags.MinLength<1> & tags.MaxLength<200>;

    /**
     * The new content of the post. Must be non-empty.
     *
     * @x-autobe-specification Direct mapping from community_bbs_posts.content column.
     */
    content: string & tags.MinLength<1>;
  };

  /**
   * Request DTO for creating a new BBS post in a community. This schema
   * defines the required fields for publishing content: the post title and
   * content body, along with the target community identifier and content type
   * discriminator. Only authenticated members can create posts, and the
   * author information is automatically extracted from the authentication
   * token, making it unnecessary to include in this request DTO. The
   * post_type field determines whether this is a text-based post (using the
   * content field) or a link-based post (which will have a URL field defined
   * in the system).
   */
  export type ICreate = {
    /**
     * The title of the post, limited to 200 characters.
     *
     * @x-autobe-specification Direct mapping from community_bbs_posts.title column.
     */
    title: string & tags.MinLength<1> & tags.MaxLength<200>;

    /**
     * The unique identifier of the community where this post will be
     * published.
     *
     * @x-autobe-specification Direct mapping from community_bbs_posts.community_id column, references community_bbs_communities.id.
     */
    community_id: string & tags.Format<"uuid">;

    /**
     * Type of the post content: 'text' for posts with body content, 'link'
     * for posts that link to external resources.
     *
     * @x-autobe-specification Direct mapping from community_bbs_posts.post_type column, values: 'text' for text posts, 'link' for link posts.
     */
    post_type: "text" | "link";
  };

  /**
   * Lightweight summary representation of a post for display in comment
   * threads. Provides essential context for comments without including full
   * post content or metadata.
   */
  export type ISummary = {
    /**
     * Unique identifier for the post.
     *
     * @x-autobe-specification Direct mapping from community_bbs_posts.id column. Unique identifier for the post.
     */
    id: string & tags.Format<"uuid">;

    /**
     * The title of the post, providing a concise summary of the post
     * content.
     *
     * @x-autobe-specification Direct mapping from community_bbs_posts.title column. The main title of the post.
     */
    title: string & tags.MaxLength<255>;

    /**
     * Summary information about the author of this post.
     *
     * @x-autobe-specification Reference to IBbsMember.ISummary via JOIN on community_bbs_posts.author_id to community_bbs_member table. Returns summary variant with id, name, avatar.
     */
    author: ICommunityBbsMember.ISummary;
  };

  /**
   * Search and pagination parameters for posts in the communityBbs platform.
   * Use these parameters to filter and paginate posts based on keyword
   * search, community, creation date range, minimum upvote threshold, and
   * time scope. This enables comprehensive content discovery across the
   * platform.
   */
  export type IRequest = {
    /**
     * Keyword to search for in post title and content. Matches partial text
     * with case-insensitive comparison.
     *
     * @x-autobe-specification Search term applied as LIKE '%search%' pattern against post title and content columns.
     */
    search?: string | undefined;

    /**
     * Identifier of the community to filter posts by. Will match exact
     * community_id in the database. This must be a UUID string format as
     * required by the API's resource identifier standard.
     *
     * @x-autobe-specification Matches community_bbs_post.community_id field to filter posts by community.
     */
    community_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Minimum number of upvotes a post must have to be included in results.
     * Posts with fewer upvotes than this value will be filtered out.
     *
     * @x-autobe-specification Filters posts with upvote_count below this threshold. Compares against community_bbs_post_votes aggregated count field.
     */
    min_upvote_count?:
      | (number & tags.Type<"int32"> & tags.Minimum<0>)
      | undefined;

    /**
     * Starting date/time for filtering posts by creation date. Posts must
     * be created on or after this timestamp to be included in results.
     * Format: ISO 8601 date-time.
     *
     * @x-autobe-specification Filters posts created on or after this timestamp using created_at >= from_created_at comparison against community_bbs_posts.created_at.
     */
    from_created_at?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Ending date/time for filtering posts by creation date. Posts must be
     * created on or before this timestamp to be included in results.
     * Format: ISO 8601 date-time.
     *
     * @x-autobe-specification Filters posts created on or before this timestamp using created_at <= to_created_at comparison against community_bbs_posts.created_at.
     */
    to_created_at?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Time scope for top content queries. Accepts one of: "All Time" (all
     * posts), "Today" (posts from last 24 hours), "This Week" (posts from
     * last 7 days), "This Month" (posts from last 30 days), "This Year"
     * (posts from last 365 days). This parameter is used specifically for
     * the /content/top endpoint.
     *
     * @x-autobe-specification Applies time-based filtering for top content: "All Time" (no filter), "Today" (created_at >= 24 hours ago), "This Week" (created_at >= 7 days ago), "This Month" (created_at >= 30 days ago), "This Year" (created_at >= 365 days ago).
     */
    time_scope?:
      | "All Time"
      | "Today"
      | "This Week"
      | "This Month"
      | "This Year"
      | undefined;

    /**
     * Pagination cursor token from the previous response for incremental
     * navigation of results. This enables efficient cursor-based pagination
     * without offset-based performance degradation. When empty, returns
     * first page.
     *
     * @x-autobe-specification Cursor token for pagination, retrieved from previous response's next_cursor field. Used for cursor-based pagination in community_bbs_posts table.
     */
    cursor?: string | undefined;

    /**
     * Number of items to return per page. Maximum allowed value is 20.
     * Default value is 20 when not provided. Controls the size of each page
     * of results.
     *
     * @x-autobe-specification Page size for pagination. Maximum allowed value is 20 as specified in the operation specification. Used with cursor-based pagination implementation.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<20>)
      | undefined;
  };
}
