import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallCustomerSession } from "../../../../structures/IPageIShoppingMallCustomerSession";
import { IShoppingMallCustomerSession } from "../../../../structures/IShoppingMallCustomerSession";

/**
 * Retrieve a paginated list of active customer sessions in the shopping mall platform.
 *
 * This operation supports complex search criteria including filtering by customer ID, IP address, session creation, and expiration timestamps.
 *
 * Sessions represent JWT tokens issued upon customer login, including metadata such as client IP, accessed URL (href), and HTTP referrer for audit and security monitoring.
 *
 * Access is restricted to authenticated customers and administrators, ensuring protected viewing of session data.
 *
 * This list endpoint supports pagination, sorting, and filtering to efficiently manage and audit sessions.
 *
 * Related endpoints include login and logout operations which create and destroy sessions respectively.
 *
 * @param props.connection
 * @param props.body Filter criteria and pagination parameters for customer session listing.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Implement a service layer that queries both shopping_mall_customer_sessions and shopping_mall_seller_sessions tables, applying filters from the request body on fields such as shopping_mall_customer_id, seller_id, ip, created_at, and expired_at.
 *
 * Consolidate results into a unified paginated response including session ID, user type (customer or seller), user ID, IP, href, referrer, creation and expiration timestamps.
 *
 * Support pagination parameters like page number and page size, as well as sorting by created_at descending by default.
 *
 * Ensure proper authorization checks that only allow members and administrators to access this endpoint.
 *
 * Handle errors such as invalid filter parameters and return appropriate HTTP status codes.
 *
 * Implement efficient database queries using indices on user IDs and timestamps.
 *
 * Provide documentation linking to authentication endpoints and user management interfaces.
 * @path /shoppingMall/customer/sessions
 * @accessor api.functional.shoppingMall.customer.sessions.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Filter criteria and pagination parameters for customer session listing.
     */
    body: IShoppingMallCustomerSession.IRequest;
  };
  export type Body = IShoppingMallCustomerSession.IRequest;
  export type Response = IPageIShoppingMallCustomerSession.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/customer/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/sessions";
  export const random = (): IPageIShoppingMallCustomerSession.ISummary =>
    typia.random<IPageIShoppingMallCustomerSession.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information of a specific customer session by session ID.
 *
 * This operation accesses the `shopping_mall_customer_sessions` table which stores JWT session tokens for customer authentication and metadata like IP address, referer URL, href URL, and creation/expiry timestamps.
 *
 * It requires the unique `sessionId` path parameter which is a UUID string identifying the session.
 *
 * Access to this operation should be limited to authorized actors such as administrators or the owning customers.
 *
 * The response includes all key session attributes:
 * - `id`: the session UUID
 * - `shoppingMallCustomerId`: the UUID of the associated customer
 * - `ip`: IP address of the login client
 * - `href`: the URL accessed during session creation
 * - `referrer`: the HTTP referer header received
 * - `createdAt`: timestamp when the session record was created
 * - `expiredAt`: timestamp when the session expires
 *
 * No request body is required for this GET operation.
 *
 * Common use cases include auditing session activity, security monitoring, and customer session management.
 *
 *
 * @param props.connection
 * @param props.sessionId Unique identifier of the customer session (UUID)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query the shopping_mall_customer_sessions table filtering by id = :sessionId parameter.
 * Validate sessionId is a UUID string.
 * Return full session record matching the sessionId.
 * If session not found, return 404 error.
 * Restrict access to owning customer or administrators.
 * No request body needed.
 * Use path parameter for sessionId as string UUID.
 * @path /shoppingMall/customer/sessions/:sessionId
 * @accessor api.functional.shoppingMall.customer.sessions.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the customer session (UUID)
     */
    sessionId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallCustomerSession;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/sessions/:sessionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/sessions/${encodeURIComponent(props.sessionId ?? "null")}`;
  export const random = (): IShoppingMallCustomerSession =>
    typia.random<IShoppingMallCustomerSession>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("sessionId")(() => typia.assert(props.sessionId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
