export * as auth from "./auth/index";
export * as users from "./users/index";
export * as user from "./user/index";
export * as admins from "./admins/index";
export * as admin from "./admin/index";
export * as super_admins from "./super_admins/index";
export * as superAdmin from "./superAdmin/index";
export * as sections from "./sections/index";
export * as articles from "./articles/index";
