import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { ICommunityPlatformMvCommunitySubscriberCount } from "../../../../../structures/ICommunityPlatformMvCommunitySubscriberCount";

/**
 * Retrieve subscriber analytics and metrics for a specific community.
 *
 * This operation provides comprehensive subscriber data including current subscriber count, historical growth trends, subscription rates, and engagement metrics. The subscriber count is publicly visible information that helps users assess community popularity and activity levels before deciding to join.
 *
 * The metrics include real-time subscriber count from the materialized view `community_platform_mv_community_subscriber_counts`, subscription/unsubscription activity trends from `community_platform_subscription_activities`, and derived metrics like subscriber growth rate and retention patterns.
 *
 * Users can filter metrics by date ranges to analyze subscriber trends over specific periods. This supports community owners and moderators in understanding their community's growth patterns and members in evaluating community vitality.
 *
 * Authorization is not required as subscriber counts are public information accessible to all users including guests. The operation returns detailed analytics that complement the publicly displayed subscriber count shown on community pages and lists.
 *
 * Related operations include viewing community details (`GET /communities/{communityId}`) which shows basic subscriber count, and listing subscribed communities (`PATCH /members/{memberId}/subscriptions`) for personal subscription management.
 *
 * @param props.connection
 * @param props.communityId Unique identifier of the target community
 * @param props.body Metrics filtering and aggregation parameters
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query the materialized view `community_platform_mv_community_subscriber_counts` for the specified community ID to get current subscriber count.
 *
 * Calculate subscriber growth trends by analyzing `community_platform_subscription_activities` records:
 * - Filter by `community_id` = the target community
 * - Group by time periods (daily, weekly, monthly) based on request filters
 * - Count `event_type = 'subscribed'` vs `event_type = 'unsubscribed'`
 * - Compute net subscriber change per period
 *
 * For historical data, consider `created_at` timestamps in subscription activities.
 *
 * Return aggregated metrics including:
 * - Current subscriber count
 * - Subscriber growth trends over time
 * - Subscription/unsubscription rates
 * - Active subscription percentage
 *
 * Implement pagination and date range filtering via request body parameters.
 *
 * Ensure proper authorization: public endpoint accessible to all users (guests, members, admins) since subscriber counts are public information.
 *
 * Handle community not found error: return 404 if community ID doesn't exist.
 * @path /communityPlatform/admin/communities/:communityId/subscribers/metrics
 * @accessor api.functional.communityPlatform.admin.communities.subscribers.metrics
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function metrics(
  connection: IConnection,
  props: metrics.Props,
): Promise<metrics.Response> {
  return true === connection.simulate
    ? metrics.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...metrics.METADATA,
          path: metrics.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace metrics {
  export type Props = {
    /**
     * Unique identifier of the target community
     */
    communityId: string & tags.Format<"uuid">;

    /**
     * Metrics filtering and aggregation parameters
     */
    body: ICommunityPlatformMvCommunitySubscriberCount.IRequest;
  };
  export type Body = ICommunityPlatformMvCommunitySubscriberCount.IRequest;
  export type Response = ICommunityPlatformMvCommunitySubscriberCount;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/admin/communities/:communityId/subscribers/metrics",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/admin/communities/${encodeURIComponent(props.communityId ?? "null")}/subscribers/metrics`;
  export const random = (): ICommunityPlatformMvCommunitySubscriberCount =>
    typia.random<ICommunityPlatformMvCommunitySubscriberCount>();
  export const simulate = (
    connection: IConnection,
    props: metrics.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: metrics.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityId")(() => typia.assert(props.communityId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
