import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommerceOrderItem } from "../../../../../../structures/IEcommerceOrderItem";

/**
 * Force-cancels an individual order item regardless of its current status, triggering automatic refund and stock restoration.
 *
 * This operation is restricted to administrators only and bypasses normal cancellation workflow restrictions. When executed, the system processes a refund for the customer and restores the stock quantity for the associated product variant through inventory records.
 *
 * **Authorization**
 * Only administrators with appropriate privileges can execute this operation. Regular customers and sellers cannot force-cancel order items.
 *
 * **Business Logic**
 * - The order item status is updated to "cancelled"
 * - A refund is automatically processed for the customer
 * - Stock quantity is restored for the associated product variant
 * - An inventory record is created with reason "cancellation"
 * - The action is recorded in the order item snapshots for audit trail
 *
 * **Error Conditions**
 * - The operation is rejected if the order item has already been cancelled
 * - The order and order item must exist and be accessible
 * - Invalid UUIDs or non-existent resources return appropriate error responses
 *
 * @param props.connection
 * @param props.orderId UUID of the parent order containing the order item (global scope)
 * @param props.itemId UUID of the order item to force-cancel (scoped to parent order)
 * @param props.body Optional reason for the force-cancellation action, recorded for audit trail purposes.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Implement as admin-only POST endpoint with UUID path
 *   parameters for orderId and itemId.
 *
 * **Implementation Steps**
 * 1. Authenticate request as administrator with force-cancel privileges
 * 2. Validate orderId and itemId are valid UUIDs
 * 3. Query ecommerce_order_items table for the item with matching id and ecommerce_order_id
 * 4. Verify the order item exists and belongs to the specified order
 * 5. Check if order item status is NOT already "cancelled" - reject if cancelled
 * 6. Begin database transaction
 * 7. Update order item status to "cancelled"
 * 8. Update order item updated_at timestamp
 * 9. Create inventory record for the associated product variant with positive quantity change and reason "cancellation"
 * 10. Create order item snapshot capturing the state before cancellation
 * 11. Recalculate parent order status based on all order items
 * 12. Commit transaction
 * 13. Return updated order item with new status
 *
 * **Edge Cases**
 * - Order item already cancelled: Return 409 Conflict with error message
 * - Order item not found: Return 404 Not Found
 * - Order not found: Return 404 Not Found
 * - Non-administrator access: Return 403 Forbidden
 * - Invalid UUID format: Return 400 Bad Request
 *
 * **Transaction Safety**
 * All database updates must occur within a single transaction to ensure consistency between order item status, inventory records, and order status recalculation.
 * @path /ecommerce/admin/orders/:orderId/items/:itemId/force-cancel
 * @accessor api.functional.ecommerce.admin.orders.items.force_cancel.forceCancel
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function forceCancel(
  connection: IConnection,
  props: forceCancel.Props,
): Promise<forceCancel.Response> {
  return true === connection.simulate
    ? forceCancel.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...forceCancel.METADATA,
          path: forceCancel.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace forceCancel {
  export type Props = {
    /**
     * UUID of the parent order containing the order item (global scope)
     */
    orderId: string & tags.Format<"uuid">;

    /**
     * UUID of the order item to force-cancel (scoped to parent order)
     */
    itemId: string & tags.Format<"uuid">;

    /**
     * Optional reason for the force-cancellation action, recorded for audit trail purposes.
     */
    body: IEcommerceOrderItem.IForceCancel;
  };
  export type Body = IEcommerceOrderItem.IForceCancel;
  export type Response = IEcommerceOrderItem;

  export const METADATA = {
    method: "POST",
    path: "/ecommerce/admin/orders/:orderId/items/:itemId/force-cancel",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/ecommerce/admin/orders/${encodeURIComponent(props.orderId ?? "null")}/items/${encodeURIComponent(props.itemId ?? "null")}/force-cancel`;
  export const random = (): IEcommerceOrderItem =>
    typia.random<IEcommerceOrderItem>();
  export const simulate = (
    connection: IConnection,
    props: forceCancel.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: forceCancel.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.param("itemId")(() => typia.assert(props.itemId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
