import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IMallPlatformAdministratorApprovalRequest } from "../../../../api/structures/IMallPlatformAdministratorApprovalRequest";
import { IPageIMallPlatformAdministratorApprovalRequest } from "../../../../api/structures/IPageIMallPlatformAdministratorApprovalRequest";
import { AdministratorAuth } from "../../../../decorators/AdministratorAuth";
import { AdministratorPayload } from "../../../../decorators/payload/AdministratorPayload";
import { getMallPlatformAdministratorAdministratorApprovalRequestsAdministratorApprovalRequestId } from "../../../../providers/getMallPlatformAdministratorAdministratorApprovalRequestsAdministratorApprovalRequestId";
import { patchMallPlatformAdministratorAdministratorApprovalRequests } from "../../../../providers/patchMallPlatformAdministratorAdministratorApprovalRequests";
import { putMallPlatformAdministratorAdministratorApprovalRequestsAdministratorApprovalRequestId } from "../../../../providers/putMallPlatformAdministratorAdministratorApprovalRequestsAdministratorApprovalRequestId";

@Controller("/mallPlatform/administrator/administratorApprovalRequests")
export class MallplatformAdministratorAdministratorapprovalrequestsController {
  /**
   * Search administrator approval requests for governance review.
   *
   * This endpoint returns a paginated list of administrator approval requests that super administrators can use to review pending submissions and inspect completed request history. It is intended for administrative triage, not for making decisions.
   *
   * The search supports filtering by applicant, request status, and review timing, along with pagination and sorting for large result sets. The response uses summary records only; use the detail endpoint when a full record is needed.
   *
   * Requests that do not match the criteria return an empty page. Invalid pagination or filter combinations are rejected according to the platform browsing rules.
   *
   * @param connection
   * @param body Search criteria for administrator approval requests, including filters, sorting, and pagination settings.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor administrator
   * @x-autobe-specification Query mall_platform_administrator_approval_requests with pagination, filtering, and sorting.
   * Apply filters for applicant, current request status, and lifecycle timestamps as supported by the schema and business rules.
   * Return a paginated summary projection suitable for administrative list views.
   * Enforce super-administrator-only access through authorization middleware.
   * Reject invalid pagination values and malformed filters. If no records match, return an empty page rather than an error.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @AdministratorAuth()
    administrator: AdministratorPayload,
    @TypedBody()
    body: IMallPlatformAdministratorApprovalRequest.IRequest,
  ): Promise<IPageIMallPlatformAdministratorApprovalRequest.ISummary> {
    try {
      return await patchMallPlatformAdministratorAdministratorApprovalRequests({
        administrator,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a single administrator approval request for governance review.
   *
   * This endpoint returns the full administrator approval request identified by the path parameter. It is intended for super administrator oversight so the reviewer can inspect the applicant’s submitted reason, current status, and any recorded decision details associated with the request.
   *
   * The request represents a formal application from an existing customer or seller who wants administrator status. The returned record should preserve the current lifecycle state, including pending, approved, or rejected, so the platform can present an accurate and traceable approval history.
   *
   * If the identifier does not match an existing request, the service should return a not-found response. If the caller is not authorized to access administrator approval requests, the request should be rejected according to the platform’s authorization rules.
   *
   * @param connection
   * @param administratorApprovalRequestId The unique identifier of the administrator approval request to retrieve.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor administrator
   * @x-autobe-specification Load the administrator approval request directly from mall_platform_administrator_approval_requests using the UUID path parameter.
   * Return the complete entity for the matching row, including the applicant reference, submitted reason, status, reviewer decision fields, and lifecycle timestamps that exist in the table.
   * Authorize access for super administrators only; regular administrators, customers, and sellers must not be able to read this record.
   * If no matching row exists, return a not-found error.
   * Do not fabricate fields or join unrelated tables unless the implementation requires them for the entity schema.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":administratorApprovalRequestId")
  public async at(
    @AdministratorAuth()
    administrator: AdministratorPayload,
    @TypedParam("administratorApprovalRequestId")
    administratorApprovalRequestId: string & tags.Format<"uuid">,
  ): Promise<IMallPlatformAdministratorApprovalRequest> {
    try {
      return await getMallPlatformAdministratorAdministratorApprovalRequestsAdministratorApprovalRequestId(
        {
          administrator,
          administratorApprovalRequestId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Updates an administrator approval request with the reviewer’s final decision.
   *
   * Only a super administrator may perform this operation. The request must still be pending when it is reviewed; completed requests are rejected and remain unchanged. A rejection must include a reason so the review outcome is fully recorded for governance and dispute handling.
   *
   * When the decision is approved, the applicant is granted regular administrator access. When the decision is rejected, the applicant does not receive administrator privileges. The response returns the updated approval request so callers can confirm the recorded state and decision details.
   *
   * @param connection
   * @param administratorApprovalRequestId The administrator approval request identifier (UUID) for the request being reviewed.
   * @param body The final review decision for the administrator approval request, including approval or rejection and any required rejection reason.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor administrator
   * @x-autobe-specification Authenticate the caller and enforce super-administrator authorization before reading or writing any data.
   *
   * Load the administrator approval request by its UUID. Verify that the request exists and is still pending. If the request is already approved or rejected, reject the operation and do not modify any row.
   *
   * Apply the decision in a single transaction. For approval, update the request to its approved final state and promote the applicant account to a regular administrator if needed. For rejection, require a non-empty reason, persist the rejection reason, and update the request to its rejected final state. If the schema stores reviewer identity or reviewed timestamps, set them in the same transaction.
   *
   * Do not create or modify snapshot history rows here; snapshots are handled separately by the snapshot subsystem. The operation must be idempotent with respect to the final state, meaning a terminal request cannot be processed again. Return the updated approval request entity after the transaction commits successfully.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":administratorApprovalRequestId")
  public async update(
    @AdministratorAuth()
    administrator: AdministratorPayload,
    @TypedParam("administratorApprovalRequestId")
    administratorApprovalRequestId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IMallPlatformAdministratorApprovalRequest.IUpdate,
  ): Promise<IMallPlatformAdministratorApprovalRequest> {
    try {
      return await putMallPlatformAdministratorAdministratorApprovalRequestsAdministratorApprovalRequestId(
        {
          administrator,
          administratorApprovalRequestId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
