import { tags } from "typia";

/**
 * Append-only audit log entry mapped to the Prisma model
 * `discussion_board_audit_logs`. Contains canonical forensic snapshot of a
 * system or user event. The `metadata` property contains serialized JSON text
 * (string) and may be redacted for callers without unredacted-audit privileges.
 * All timestamps use ISO 8601 UTC format.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardAuditLog = {
  /** Unique identifier of the audit record (UUID). */
  id: string & tags.Format<"uuid">;

  /**
   * Canonical event type (e.g.
   * 'auth.login','moderation.action','export.request'). Use dot notation for
   * hierarchical classification.
   */
  event_type: string;

  /** Time when the audited event occurred (ISO 8601 UTC). */
  event_timestamp: string & tags.Format<"date-time">;

  /**
   * Optional resource type the event targets (e.g.,
   * 'article','comment','attachment'). Null when event is system-level with
   * no resource.
   */
  resource_type?: string | null | undefined;

  /**
   * Optional UUID of the target resource. Interpreted according to
   * resource_type; may be null for non-resource events.
   */
  resource_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Classification of the actor that performed the action. Use the canonical
   * values (member, moderator, system, guest).
   */
  actor_type: "member" | "moderator" | "system" | "guest";

  /**
   * Optional actor identifier (UUID) when applicable. Nullable for system
   * events or anonymized actors. THIS FIELD MAY BE REDACTED in responses
   * returned to callers without unredacted-audit privileges; when redacted
   * the API SHOULD return null and record the access in audit-access logs.
   */
  actor_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Observed IP address for the event when available. May be redacted for
   * callers without unredacted privileges. Consider storing in logs but
   * returning null to non-privileged API clients.
   */
  ip?: string | null | undefined;

  /**
   * User agent or client hint captured at event time. May be null or redacted
   * for non-privileged callers.
   */
  user_agent?: string | null | undefined;

  /**
   * Serialized event payload stored as JSON text (string) containing
   * event-specific details for forensic reconstruction. MAY contain PII and
   * therefore MUST BE REDACTED for callers without unredacted-audit
   * privileges. Recommended consumer guidance: attempt to parse the string as
   * JSON if present. Keep payloads reasonably sized; extremely large payloads
   * should be truncated or referenced via external forensic storage.
   */
  metadata?: string | null | undefined;

  /**
   * Record insertion timestamp (ISO 8601 UTC). For audit semantics this is
   * typically set by the application to match event_timestamp where
   * possible.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp. Audit records are append-only and updates are
   * exceptional; updates should be rare and audited. In many implementations
   * updated_at == created_at for append-only entries unless an authorized
   * correction occurred.
   */
  updated_at: string & tags.Format<"date-time">;

  /** Optional administrative soft-delete marker. Use is restricted by policy. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IDiscussionBoardAuditLog {
  /**
   * Search request for discussion_board_audit_logs. Contains optional
   * filters, full-text search over the metadata column (GIN/trigram),
   * pagination and sorting. Intended for privileged moderator usage; caller
   * identity is taken from authentication context and must not be supplied
   * here. Date range filters map to
   * discussion_board_audit_logs.event_timestamp and are inclusive.
   */
  export type IRequest = {
    /**
     * Exact-match filter for event_type (for example: 'auth.login',
     * 'moderation.action'). Server may validate against known event types.
     */
    eventType?: string | undefined;

    /**
     * Filter by actor_type (for example: 'member','moderator','system').
     * Use only known classifications. Caller must be authorized to filter
     * by actor-related fields.
     */
    actorType?: string | undefined;

    /**
     * Filter by actor_id (UUID). Maps to
     * discussion_board_audit_logs.actor_id. This filter exposes PII and
     * MUST be honored only for callers with appropriate privileges;
     * accesses should be audited.
     */
    actorId?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Filter by resource_type (for example:
     * 'article','comment','attachment').
     */
    resourceType?: string | undefined;

    /**
     * Filter by resource_id (UUID). Maps to
     * discussion_board_audit_logs.resource_id. Use only when caller is
     * authorized to query resource-level audit events.
     */
    resourceId?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Free-text search applied to the metadata column (serialized JSON)
     * using the DB GIN/trigram index. This is a privileged operation:
     * queries may be rate-limited, results may be redacted for PII, and
     * full payload access may require elevated permissions.
     */
    fullText?: string | undefined;

    /**
     * Inclusive lower bound for event_timestamp (ISO 8601 UTC). Maps to
     * discussion_board_audit_logs.event_timestamp.
     */
    dateFrom?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Inclusive upper bound for event_timestamp (ISO 8601 UTC). Maps to
     * discussion_board_audit_logs.event_timestamp.
     */
    dateTo?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Page number for pagination (1-based). Default is 1. Server enforces a
     * minimum of 1.
     */
    page?:
      | (number & tags.Type<"int32"> & tags.Default<1> & tags.Minimum<1>)
      | undefined;

    /**
     * Number of items per page. Default 20. Server MUST enforce an upper
     * bound (recommended max 100) to protect the system and avoid extremely
     * large synchronous responses.
     */
    limit?:
      | (number &
          tags.Type<"int32"> &
          tags.Default<20> &
          tags.Minimum<1> &
          tags.Maximum<100>)
      | undefined;

    /**
     * Sort expression. Typical values: 'event_timestamp' (ascending) or
     * '-event_timestamp' (descending). Server validates supported sort
     * keys.
     */
    sort?: string | undefined;
  };

  /**
   * Concise summary of an audit-log entry (discussion_board_audit_logs).
   * Intended for listing and triage. The full serialized metadata payload is
   * intentionally excluded from this summary. To retrieve full event_payload
   * callers require an elevated/detail endpoint and appropriate privileges;
   * such accesses MUST be audited.
   */
  export type ISummary = {
    /**
     * Primary key: unique identifier of the audit log entry
     * (discussion_board_audit_logs.id).
     */
    id: string & tags.Format<"uuid">;

    /**
     * Canonical event type describing the audited event (for example:
     * 'auth.login','moderation.action'). Use dot notation for hierarchical
     * classification when applicable.
     */
    event_type: string;

    /**
     * Timestamp when the audited event occurred (ISO 8601 UTC). Corresponds
     * to discussion_board_audit_logs.event_timestamp.
     */
    event_timestamp: string & tags.Format<"date-time">;

    /**
     * Optional resource type targeted by the event (for example:
     * 'article','comment','attachment'). Nullable for system-level events.
     */
    resource_type?: string | null | undefined;

    /**
     * Optional UUID of the resource targeted by the event
     * (discussion_board_audit_logs.resource_id). Nullable when no resource
     * is targeted.
     */
    resource_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Classification of the actor that performed the action (for example:
     * 'member','moderator','system'). Nullable for system events.
     */
    actor_type?: string | null | undefined;

    /**
     * Actor identifier (UUID) when applicable
     * (discussion_board_audit_logs.actor_id). May be null when actor was
     * anonymized or when event is system-generated. This field may contain
     * PII and should be redacted for callers without unredacted-audit
     * privileges; the server MUST log accesses to unredacted audit
     * responses.
     */
    actor_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Record insertion timestamp (ISO 8601 UTC). For audit semantics this
     * is typically set by the application and corresponds to
     * discussion_board_audit_logs.created_at.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Last update timestamp (ISO 8601 UTC). Audit records are append-only
     * and updates are exceptional; this field is nullable and mirrors
     * discussion_board_audit_logs.updated_at.
     */
    updated_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Administrative soft-delete timestamp (ISO 8601 UTC). Presence
     * indicates the record has been administratively marked; use is
     * restricted by policy. Mirrors
     * discussion_board_audit_logs.deleted_at.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
