import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IDiscussionBoardSection } from "../../../api/structures/IDiscussionBoardSection";
import { IPageIDiscussionBoardSection } from "../../../api/structures/IPageIDiscussionBoardSection";
import { getDiscussionBoardSectionsSectionId } from "../../../providers/getDiscussionBoardSectionsSectionId";
import { patchDiscussionBoardSections } from "../../../providers/patchDiscussionBoardSections";

@Controller("/discussionBoard/sections")
export class DiscussionboardSectionsController {
  /**
   * Retrieve a filtered and paginated list of all active discussion board sections.
   *
   * This operation provides access to the complete catalog of discussion board sections that organize articles into topic categories. Each section represents a distinct topic area such as Politics, Economy, or Current Affairs, serving as the primary organizational structure for content browsing and filtering. Sections are created and maintained by administrators through the discussion_board_admins table, with each section tracking its creator via the discussion_board_admin_id foreign key.
   *
   * All actors including guests, members, and administrators can access this endpoint to discover available sections. The response includes section summaries with essential information like name and description, optimized for list displays and navigation purposes. Sections support soft deletion through the deleted_at timestamp field, allowing administrators to remove sections while preserving historical article data.
   *
   * The operation supports comprehensive pagination with configurable page sizes and sorting options. Sections can be sorted alphabetically by name or chronologically by creation date (created_at), in either ascending or descending order. The response includes pagination metadata with current page, total pages, and total section count.
   *
   * Related operations include GET /discussionBoard/sections/{sectionId} for retrieving detailed section information and POST /discussionBoard/articles for creating articles within a specific section. Before creating an article, users should first retrieve the section list to identify the appropriate section ID.
   *
   * @param connection
   * @param body Pagination and sorting parameters for section list retrieval
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification Query discussion_board_sections table filtering out soft-deleted records (deleted_at IS NULL). Apply pagination with configurable page size and offset. Support sorting by name (alphabetical) or created_at (chronological) in ascending or descending order. Return section summaries containing id, name, description, and created_at. Implement cursor-based or offset-based pagination with total count for pagination metadata. Ensure consistent ordering across requests.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @TypedBody()
    body: IDiscussionBoardSection.IRequest,
  ): Promise<IPageIDiscussionBoardSection.ISummary> {
    try {
      return await patchDiscussionBoardSections({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve detailed information about a specific discussion board section by its unique identifier.
   *
   * This operation returns comprehensive section metadata including the section name, description, creation and modification timestamps, and references to the administrator who created the section. The section name serves as the primary identifier for topic categorization (e.g., 'Politics', 'Economy', 'Technology'), while the description provides context about the section's topic focus and content guidelines.
   *
   * All actors (guests, members, and administrators) can access this endpoint without authentication. This aligns with the business requirement that sections serve as public containers for articles, visible to all platform users regardless of their authentication status. No authorization checks are performed for this read-only operation.
   *
   * The operation queries the discussion_board_sections table using the primary key (id) with UUID format validation. Soft delete filtering is applied (deleted_at IS NULL) to ensure only active sections are returned. The response includes a join with discussion_board_admins to provide creator information including display name and email.
   *
   * Related operations: Use PATCH /discussionBoard/sections to retrieve a paginated list of all sections before navigating to a specific section. Use POST /discussionBoard/sections/{sectionId}/articles to create an article within this section after confirming section details.
   *
   * @param connection
   * @param sectionId Target section's unique identifier (UUID format)
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification Query the discussion_board_sections table by primary key (id) with UUID format validation.
   *
   * Implement soft delete filtering: WHERE id = $1 AND deleted_at IS NULL.
   *
   * Join with discussion_board_admins table to retrieve creator information (display name, email).
   *
   * Validate that the section exists and is active before returning data.
   *
   * Return 404 Not Found if section not found or deleted.
   *
   * No authorization checks required - accessible to all actors (guest, member, admin).
   *
   * Include section metadata: id, name, description, created_at, updated_at, discussion_board_admin_id, and creator details.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":sectionId")
  public async at(
    @TypedParam("sectionId")
    sectionId: string & tags.Format<"uuid">,
  ): Promise<IDiscussionBoardSection> {
    try {
      return await getDiscussionBoardSectionsSectionId({
        sectionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
