import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallLowStockAlert } from "../../../structures/IShoppingMallLowStockAlert";

/**
 * Retrieve a specific Low Stock Alert by ID from the inventory system.
 *
 * Retrieve a Low Stock Alert by its unique identifier. This operation accesses
 * the low stock alert data captured for a specific product SKU to inform
 * inventory monitoring and restocking decisions.
 *
 * The data includes the alert timestamp, whether the alert has been resolved,
 * and the resolution time if applicable.
 *
 * Security considerations allow public or minimal authenticated access
 * depending on business rules.
 *
 * This operation interfaces directly with the shopping_mall_low_stock_alerts
 * table in the database, ensuring accurate retrieval of alert records.
 *
 * Errors include handling missing or invalid UUIDs by responding with standard
 * API error formats.
 *
 * This endpoint is a critical part of inventory management workflows, enabling
 * users to query individual stock alerts to assess urgency and inventory
 * health.
 *
 * @param props.connection
 * @param props.id Unique identifier (UUID) of the target Low Stock Alert
 *   record.
 * @path /shoppingMall/lowStockAlerts/:id
 * @accessor api.functional.shoppingMall.lowStockAlerts.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier (UUID) of the target Low Stock Alert record. */
    id: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallLowStockAlert;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/lowStockAlerts/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/lowStockAlerts/${encodeURIComponent(props.id ?? "null")}`;
  export const random = (): IShoppingMallLowStockAlert =>
    typia.random<IShoppingMallLowStockAlert>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(props.id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
