import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IREdditLikeCommunityCommunityBan } from "../../../../../structures/IREdditLikeCommunityCommunityBan";

/**
 * Create a ban restricting a member from participating in a specific community.
 *
 * This endpoint allows community moderators and owners to ban members, preventing them from creating posts or comments in the targeted community. The ban takes effect immediately upon creation and remains permanent until explicitly lifted by a moderator through an unban operation.
 *
 * The requesting user must have either owner or moderator authority within the target community. The target member must have an active account (not soft-deleted). The system enforces that only one active ban exists per user per community.
 *
 * **Security**: Only authenticated users with moderator or owner roles in the community can ban users. The issuing moderator is automatically resolved from the session context and cannot be overridden via the request body.
 *
 * @param props.connection
 * @param props.communityId UUID of the community where the ban will be enforced. The requesting member must have active moderator or owner authority in this community.
 * @param props.body Ban creation details specifying which member to ban and the reason for the restriction.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification 1. Extract communityId from path parameters and
 *   memberId, reason from the request body. 2. Resolve the authenticated member
 *   from the session context. 3. Validate community existence: query
 *   reddit_like_community_communities where id = communityId. Return 404 if not
 *   found. 4. Validate target member existence: query
 *   reddit_like_community_members where id = memberId. Return 404 if not found
 *   or if deleted_at is not null (deleted account cannot be banned per Section
 *   139). 5. Validate moderator authority: query
 *   reddit_like_community_community_moderators where
 *   reddit_like_community_community_id = communityId,
 *   reddit_like_community_member_id = authenticatedMemberId, and deleted_at is
 *   null. Return 403 if no active moderator record exists. 6. Prevent duplicate
 *   bans: query reddit_like_community_community_bans where
 *   reddit_like_community_community_id = communityId, member_id = memberId, and
 *   deleted_at is null. Return 409 conflict error if an active ban already
 *   exists. 7. Retrieve the authenticated moderator's record ID from step 5 to
 *   populate as the issuing moderator reference. 8. Insert a new record into
 *   reddit_like_community_community_bans with:
 *   reddit_like_community_community_id (communityId), member_id (memberId),
 *   reddit_like_community_community_moderators_id (moderator record id from
 *   step 7), reason, and current timestamps for created_at and updated_at. Set
 *   deleted_at to null. 9. Return the created ban record.
 * @path /redditLikeCommunity/member/communities/:communityId/bans
 * @accessor api.functional.redditLikeCommunity.member.communities.bans.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * UUID of the community where the ban will be enforced. The requesting member must have active moderator or owner authority in this community.
     */
    communityId: string & tags.Format<"uuid">;

    /**
     * Ban creation details specifying which member to ban and the reason for the restriction.
     */
    body: IREdditLikeCommunityCommunityBan.ICreate;
  };
  export type Body = IREdditLikeCommunityCommunityBan.ICreate;
  export type Response = IREdditLikeCommunityCommunityBan;

  export const METADATA = {
    method: "POST",
    path: "/redditLikeCommunity/member/communities/:communityId/bans",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditLikeCommunity/member/communities/${encodeURIComponent(props.communityId ?? "null")}/bans`;
  export const random = (): IREdditLikeCommunityCommunityBan =>
    typia.random<IREdditLikeCommunityCommunityBan>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityId")(() => typia.assert(props.communityId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
