import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia from "typia";
import { patchShoppingSellerOrdersOrderCodeFulfillments } from "../../../../../providers/patchShoppingSellerOrdersOrderCodeFulfillments";
import { SellerAuth } from "../../../../../decorators/SellerAuth";
import { SellerPayload } from "../../../../../decorators/payload/SellerPayload";
import { getShoppingSellerOrdersOrderCodeFulfillmentsFulfillmentCode } from "../../../../../providers/getShoppingSellerOrdersOrderCodeFulfillmentsFulfillmentCode";

import { IPageIShoppingOrderFulfillment } from "../../../../../api/structures/IPageIShoppingOrderFulfillment";
import { IShoppingOrderFulfillment } from "../../../../../api/structures/IShoppingOrderFulfillment";

@Controller("/shopping/seller/orders/:orderCode/fulfillments")
export class ShoppingSellerOrdersFulfillmentsController {
  /**
   * Paginated retrieval of all fulfillment (shipping) records for a specific
   * order (shopping_order_fulfillments, shopping_order_lines,
   * shopping_orders).
   *
   * Fetch a paginated and filterable list of all fulfillment actions taken for
   * a specified order. Users leverage this functionality to track the shipping
   * and delivery events corresponding to each order line, including partial
   * shipments, returned items, or unfulfilled lines remaining.
   *
   * This API aggregates data from shopping_order_fulfillments referencing
   * shopping_order_lines, which must themselves belong to the specified order
   * (via order_code on shopping_orders). Security implementation ensures that
   * data visibility adheres to actor role restrictions: customers only see
   * their orders, sellers see only their fulfillments, and admins have global
   * visibility. All standard paginated retrieval behaviors apply, and optional
   * filtering parameters may be supported in the request DTO in future
   * versions.
   *
   * The operation is crucial for audit, support, and customer notification
   * workflows, as well as providing full transparency on the order's
   * post-purchase status. Error handling must protect against unauthorized data
   * access and handle cases where orders or fulfillments do not exist.
   *
   * @param connection
   * @param orderCode Globally unique order reference code (global scope)
   *   identifying the target order for which all fulfillment records are being
   *   requested. Used for business and user support flows.
   * @param body Optional filtering/pagination details for order fulfillment
   *   search. May include page, size, status, or date range in implementation.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("orderCode")
    orderCode: string,
    @TypedBody()
    body: IShoppingOrderFulfillment.IRequest,
  ): Promise<IPageIShoppingOrderFulfillment> {
    try {
      return await patchShoppingSellerOrdersOrderCodeFulfillments({
        seller,
        orderCode,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a specific fulfillment for an order using orderCode and
   * fulfillmentCode.
   *
   * This API operation enables retrieval of a single order fulfillment's data
   * by specifying both the platform-wide unique orderCode and the associated
   * fulfillmentCode in the path. The fulfillment details include shipment
   * status, fulfillment timestamp, shipping address, fulfillment notes, and
   * quantities as described in the shopping_order_fulfillments table.
   *
   * This is crucial for customers, sellers, and administrators to access
   * shipment tracking, confirm delivery events, resolve fulfillment issues, and
   * provide transparency on the order lifecycle. Security-wise, only the order
   * owner, seller, or an authorized admin should have access to the fulfillment
   * details.
   *
   * The relationship to the database is direct: the orderCode maps to the
   * parent order and the fulfillmentCode corresponds to a unique fulfillment
   * instance for that order. Validation ensures that only valid, non-deleted
   * fulfillments are retrievable, and error handling prevents unauthorized
   * access. This endpoint complements general order detail APIs and is used in
   * support, notification, and customer service flows.
   *
   * @param connection
   * @param orderCode Globally unique identifier code for the target order
   *   (human-readable, global scope).
   * @param fulfillmentCode Globally unique fulfillment code for this
   *   shipment/fulfillment (scoped to order, global scope).
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":fulfillmentCode")
  public async at(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("orderCode")
    orderCode: string,
    @TypedParam("fulfillmentCode")
    fulfillmentCode: string,
  ): Promise<IShoppingOrderFulfillment> {
    try {
      return await getShoppingSellerOrdersOrderCodeFulfillmentsFulfillmentCode({
        seller,
        orderCode,
        fulfillmentCode,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
