import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IPageIShoppingMallSalePromotion } from "../../../../api/structures/IPageIShoppingMallSalePromotion";
import { IShoppingMallSalePromotion } from "../../../../api/structures/IShoppingMallSalePromotion";
import { SellerAuth } from "../../../../decorators/SellerAuth";
import { SellerPayload } from "../../../../decorators/payload/SellerPayload";
import { deleteShoppingMallSellerSalePromotionsPromotionId } from "../../../../providers/deleteShoppingMallSellerSalePromotionsPromotionId";
import { getShoppingMallSellerSalePromotionsPromotionId } from "../../../../providers/getShoppingMallSellerSalePromotionsPromotionId";
import { patchShoppingMallSellerSalePromotions } from "../../../../providers/patchShoppingMallSellerSalePromotions";
import { postShoppingMallSellerSalePromotions } from "../../../../providers/postShoppingMallSellerSalePromotions";
import { putShoppingMallSellerSalePromotionsPromotionId } from "../../../../providers/putShoppingMallSellerSalePromotionsPromotionId";

@Controller("/shoppingMall/seller/sale-promotions")
export class ShoppingmallSellerSale_promotionsController {
  /**
   * This API operation creates a new sale promotion associated with a specific sale in the shopping mall platform. The sale_mall_sale_promotions entity records all relevant promotion details including type, discount, validity period, and activation status.
   *
   * Users can specify promotional codes, discount types (percentage or fixed amount), start and end timestamps, and descriptions. The system enforces uniqueness of promotion codes.
   *
   * The created promotion is linked to a sale identified by shoppingMallSaleId. The active flag indicates if the promotion is currently valid.
   *
   * This operation requires input validation to ensure discount values are positive and discount_type is one of the allowed types.
   *
   * Standard error handling for duplicate promotion codes and invalid references must be implemented.
   *
   * Related operations may include GET /sale-promotions to list promotions and PUT /sale-promotions/{id} to update existing promotions.
   *
   * @param connection
   * @param body Information needed to create a sale promotion record
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification The service layer must validate the existence of the referenced shopping_mall_sale_id before creation.
   *
   * Insert a new record into shopping_mall_sale_promotions with all fields from the request body.
   *
   * Ensure promotion_code uniqueness, throw an error if duplicate.
   *
   * Enforce discount_value >= 0 and discount_type must be a known type (e.g., 'percentage', 'fixed_amount').
   *
   * Timestamps start_at and end_at must be valid ISO 8601 datetime strings.
   *
   * The active field indicates whether the promotion is currently active.
   *
   * Return the newly created promotion entity including all fields and generated id.
   *
   * Handle transaction and rollback on failure.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @SellerAuth()
    seller: SellerPayload,
    @TypedBody()
    body: IShoppingMallSalePromotion.ICreate,
  ): Promise<IShoppingMallSalePromotion> {
    try {
      return await postShoppingMallSellerSalePromotions({
        seller,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a filtered and paginated list of sale promotions.
   *
   * This operation allows searching sale promotions by promotion code, promotion type, active status, and validity periods. It supports pagination and sorting.
   *
   * The sale promotions are linked to sales in the shopping_mall_sales table and include details like promotional codes, discount values (percentage or fixed), and validity date ranges.
   *
   * This operation provides essential capabilities for administrators and marketing teams to review and manage ongoing and past promotions.
   *
   * Security: Only authorized users such as administrators may access this endpoint.
   *
   * The operation supports filtering by active status and promotion type, and date-based filtering using start_at and end_at timestamps.
   *
   * This operation is critical for monitoring and managing marketing campaigns and discount applications.
   *
   * Search criteria and pagination details are included in the request body using the IShoppingMallSalePromotion.IRequest DTO.
   *
   * The response returns paginated summary data conforming to IPageIShoppingMallSalePromotion.ISummary type.
   *
   * @param connection
   * @param body Search criteria and pagination parameters for sale promotions
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Query the shopping_mall_sale_promotions table joined with shopping_mall_sales as needed.
   * Apply search filters from the request body on promotion_code, promotion_type, active status, start_at, and end_at.
   * Implement pagination with limit and offset or cursor-based paging.
   * Sort results by start_at descending as a default.
   * Return IPageIShoppingMallSalePromotion.ISummary in the response.
   * Ensure only authorized actors (e.g., administrators) can access this endpoint.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @SellerAuth()
    seller: SellerPayload,
    @TypedBody()
    body: IShoppingMallSalePromotion.IRequest,
  ): Promise<IPageIShoppingMallSalePromotion.ISummary> {
    try {
      return await patchShoppingMallSellerSalePromotions({
        seller,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve detailed information about a specific sale promotion.
   *
   * This operation fetches a single sale promotion identified by the `promotionId` path parameter.
   * It returns all attributes including promotion code, type, discount values, validity period, and status.
   *
   * Only authenticated sellers with the necessary permissions can access promotion details.
   *
   * The data is sourced from the `shopping_mall_sale_promotions` table, which stores all active and historical promotions applied to sales for marketing and pricing strategies.
   *
   * This is a read-only operation that does not modify any data.
   *
   * Related operations include creating and updating promotions, making this endpoint valuable for promotional management and display.
   *
   * @param connection
   * @param promotionId Unique identifier of the promotion (UUID).
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Query the `shopping_mall_sale_promotions` table by the `id` matching the `promotionId` path parameter.
   * Return all fields of the matched promotion.
   * Ensure the promotion is active or provide historical data with timestamps.
   * Handle not found case with appropriate error.
   * This is a read-only operation, so no request body is required.
   * Authorization checks should verify the caller's permission to view promotions.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":promotionId")
  public async at(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("promotionId")
    promotionId: string & tags.Format<"uuid">,
  ): Promise<IShoppingMallSalePromotion> {
    try {
      return await getShoppingMallSellerSalePromotionsPromotionId({
        seller,
        promotionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update a sale promotion identified by its unique ID.
   *
   * This endpoint allows administrators or authorized marketing users to modify
   * existing promotions in the shopping mall platform. Promotion details such as
   * promotion code, type, discount value/type, active status, and validity period
   * can be updated. The operation enforces data integrity and applies validation
   * constraints from the underlying database schema.
   *
   * The shopping_mall_sale_promotions table tracks all sales-related promotions,
   * linking each promotion to a sale in the `shopping_mall_sales` table.
   *
   * Users must supply the full set of updatable properties in the request body.
   *
   * On successful update, the API returns the updated promotion record with all
   * fields, including timestamps updated accordingly.
   *
   * Errors occur if the promotionId does not exist or validation rules are violated.
   *
   * No soft deletion behavior applies; updating does not affect deletion status.
   *
   * Related operations include GET /sale-promotions/{promotionId} for fetching,
   * POST /sale-promotions for creating, and DELETE /sale-promotions/{promotionId}
   * for deleting promotions.
   *
   * @param connection
   * @param promotionId The unique identifier of the sale promotion to update (UUID format).
   * @param body Update information for the sale promotion.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Validate the request parameters and body strictly.
   * Perform a database update operation on shopping_mall_sale_promotions where id = promotionId.
   * Allow updating fields: promotion_code, promotion_type, description, discount_value, discount_type, start_at, end_at, active.
   * Ensure promotion_code uniqueness is maintained.
   * Update the updated_at timestamp to the current time.
   * Return the updated promotion record including all fields.
   * Handle errors for non-existent promotionId or invalid inputs.
   * Ensure only authorized admin or marketing actors have access.
   * Use transactions to ensure atomicity.
   * Validate datetime fields with proper timezone handling using timestamptz.
   *
   * Maintain audit logs of changes outside this endpoint.
   *
   * No side-effects on related sales table outside this update.
   *
   * The operation is idempotent and fully replaces modifiable fields with provided data.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":promotionId")
  public async update(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("promotionId")
    promotionId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IShoppingMallSalePromotion.IUpdate,
  ): Promise<IShoppingMallSalePromotion> {
    try {
      return await putShoppingMallSellerSalePromotionsPromotionId({
        seller,
        promotionId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Permanently deletes the sale promotion identified by the promotionId path parameter from the shopping mall sales promotions table.
   *
   * This operation allows administrators to remove obsolete or incorrect promotional offers that are no longer valid or needed.
   *
   * Only authorized administrator actors should have access to this endpoint to prevent unauthorized data loss.
   *
   * The deletion cascades to any dependent records due to the database onDelete cascade policy defined in the shopping_mall_sale_promotions schema.
   *
   * No request body is required as the promotionId in the path uniquely specifies the target promotion.
   *
   * There is no response content upon successful deletion.
   *
   * Refer to the shopping_mall_sale_promotions database schema for detailed column definitions and relationships.
   *
   * Associated operations include GET /sale-promotions to list promotions and POST /sale-promotions to create new promotions.
   *
   * @param connection
   * @param promotionId UUID of the sale promotion to delete
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification This operation executes a cascade delete query on the shopping_mall_sale_promotions table using the promotionId path parameter as the primary key filter.
   *
   * Ensure authorization checks confirm the caller is an administrator with erase permission.
   *
   * Perform a direct delete where id = promotionId with cascade effect on dependent data as per Prisma schema.
   *
   * Handle failure scenarios such as not found or database errors with proper error responses.
   *
   * No request body is expected or required.
   *
   * Return HTTP 204 No Content status on successful deletion.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":promotionId")
  public async erase(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("promotionId")
    promotionId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteShoppingMallSellerSalePromotionsPromotionId({
        seller,
        promotionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
