import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallOrderDispute } from "../../../../../structures/IShoppingMallOrderDispute";
import { IPageIShoppingMallOrderDispute } from "../../../../../structures/IPageIShoppingMallOrderDispute";
export * as seller from "./seller/index";

/**
 * Search and list disputes for a specific order from the
 * shopping_mall_order_disputes table.
 *
 * Retrieve a filtered and paginated list of disputes associated with a specific
 * order in the shopping mall system.
 *
 * This operation targets the `shopping_mall_order_disputes` Prisma model, which
 * stores disputes raised around orders, order lines, and post-purchase
 * interactions such as claims of non-delivery, damaged products, or
 * dissatisfaction with service. While `shopping_mall_order_disputes` is the
 * primary table, related subsidiary models like
 * `shopping_mall_order_dispute_of_customers` and
 * `shopping_mall_order_dispute_of_sellers` may provide additional
 * actor-specific context, such as who opened the dispute and from which
 * session.
 *
 * The path parameter `orderId` represents the unique identifier of the parent
 * order whose disputes should be listed. It corresponds to the primary key of
 * the `shopping_mall_orders` model or an equivalent UUID field linking disputes
 * back to their order. This ensures that only disputes tied to the specified
 * order are returned. Security-wise, the endpoint is guarded by specific
 * marketplace actors (customers, sellers, or platform administrators), with
 * actual authorization rules (such as ensuring that a customer can only see
 * disputes for their own orders, or a seller only sees disputes related to
 * their segments) enforced in business logic rather than in the interface
 * specification.
 *
 * The request body uses the `IShoppingMallOrderDispute.IRequest` DTO. This DTO
 * is expected to include pagination controls (page size, page index or cursor),
 * optional search text, and structured filters such as dispute status (e.g.,
 * open, under review, resolved, rejected), dispute categories, and created-at
 * ranges. Implementations should validate these filters and apply them in a
 * safe, index-aware manner to keep queries efficient even when many disputes
 * exist for a heavily-trafficked order.
 *
 * The response body returns `IPageIShoppingMallOrderDispute.ISummary`,
 * representing a page of summary records instead of full dispute details. Each
 * summary includes key fields of `shopping_mall_order_disputes` and possibly
 * essential attributes from related entities, such as dispute type, current
 * status, opened-by actor type (customer or seller), created date, and the
 * primary subject (order vs order line). Detailed inspection of an individual
 * dispute—including full message thread, attachments, or resolution logs—is
 * provided by the `GET /orders/{orderId}/disputes/{disputeId}` operation and
 * should not be duplicated here, preserving clear separation of list versus
 * detail responsibilities.
 *
 * Error handling for this operation includes validation failures for malformed
 * pagination parameters or unsupported filter combinations, and access-related
 * failures when the authenticated user is not permitted to view disputes for
 * the given order. In such cases, the implementation should return appropriate
 * HTTP status codes (e.g., 400 for invalid filters, 403 or 404 for unauthorized
 * or non-existent orders).
 *
 * @param props.connection
 * @param props.orderId Unique identifier of the parent order whose disputes are
 *   being queried. This value corresponds to the primary key of the
 *   `shopping_mall_orders` model and scopes the dispute search to a single
 *   customer-facing order.
 * @param props.body Filter, sorting, and pagination criteria for listing
 *   disputes associated with the specified order. This includes fields for
 *   dispute status, type, date ranges, and generic pagination options.
 * @path /shoppingMall/seller/orders/:orderId/disputes
 * @accessor api.functional.shoppingMall.seller.orders.disputes.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Unique identifier of the parent order whose disputes are being
     * queried. This value corresponds to the primary key of the
     * `shopping_mall_orders` model and scopes the dispute search to a
     * single customer-facing order.
     */
    orderId: string & tags.Format<"uuid">;

    /**
     * Filter, sorting, and pagination criteria for listing disputes
     * associated with the specified order. This includes fields for dispute
     * status, type, date ranges, and generic pagination options.
     */
    body: IShoppingMallOrderDispute.IRequest;
  };
  export type Body = IShoppingMallOrderDispute.IRequest;
  export type Response = IPageIShoppingMallOrderDispute.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/orders/:orderId/disputes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/seller/orders/${encodeURIComponent(props.orderId ?? "null")}/disputes`;
  export const random = (): IPageIShoppingMallOrderDispute.ISummary =>
    typia.random<IPageIShoppingMallOrderDispute.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a single order dispute from the shopping_mall_order_disputes table
 * by order and dispute identifiers.
 *
 * Retrieve detailed information for a specific dispute belonging to a
 * particular order.
 *
 * This operation is built around the `shopping_mall_order_disputes` Prisma
 * model, which stores disputes raised against orders, order lines, or
 * after-sales processes. Each dispute record encapsulates key information such
 * as the reason category (e.g., non-delivery, damaged item, wrong item
 * received), current status (e.g., open, under review, resolved, rejected), and
 * linkages to related entities like orders, order lines, or after-sales
 * requests. Subsidiary models such as
 * `shopping_mall_order_dispute_of_customers` and
 * `shopping_mall_order_dispute_of_sellers` can be used by the service
 * implementation to enrich the DTO with which actor initiated the dispute and
 * under which session, though those implementation details do not change the
 * interface contract.
 *
 * The path requires two identifiers: `orderId`, identifying the parent order
 * from `shopping_mall_orders`, and `disputeId`, identifying the specific
 * dispute row in `shopping_mall_order_disputes`. Using both parameters ensures
 * that a dispute is always retrieved in the proper order context, preventing
 * accidental or malicious cross-order access. The system should internally
 * verify that the dispute referenced by `disputeId` is indeed associated with
 * the order referenced by `orderId`; if not, a 404 Not Found should be returned
 * to avoid leaking existence of unrelated disputes.
 *
 * The response employs the `IShoppingMallOrderDispute` DTO, which is intended
 * to expose the full dispute detail necessary for rendering a dispute detail
 * page. This includes core fields from `shopping_mall_order_disputes` such as
 * identifiers, order linkage, dispute classification, textual explanation,
 * current status, timestamps, and optionally embedded sub-structures describing
 * status history, resolution logs, or related refund and cancellation artifacts
 * depending on how the DTO is modeled against the Prisma relationships. The
 * operation is strictly read-only and does not change the dispute's state.
 *
 * Authorization is modeled with marketplace actors (customers, sellers, and
 * platform administrators), and application-layer logic must enforce more
 * granular rules, such as restricting customers to their own disputes,
 * restricting sellers to disputes tied to their seller segments, and granting
 * broader access to platform administrators. Typical errors include 404
 * responses when either the order or dispute is not found or not related, and
 * 403 responses when the current actor is not allowed to view the dispute. This
 * operation is intended to be used after listing disputes via `PATCH
 * /orders/{orderId}/disputes`, providing a full-detail follow-up for a specific
 * dispute selected from the list.
 *
 * @param props.connection
 * @param props.orderId Unique identifier of the parent order from
 *   `shopping_mall_orders` to which the dispute belongs.
 * @param props.disputeId Unique identifier of the dispute record in the
 *   `shopping_mall_order_disputes` table to retrieve in detail.
 * @path /shoppingMall/seller/orders/:orderId/disputes/:disputeId
 * @accessor api.functional.shoppingMall.seller.orders.disputes.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the parent order from `shopping_mall_orders` to
     * which the dispute belongs.
     */
    orderId: string & tags.Format<"uuid">;

    /**
     * Unique identifier of the dispute record in the
     * `shopping_mall_order_disputes` table to retrieve in detail.
     */
    disputeId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallOrderDispute;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/seller/orders/:orderId/disputes/:disputeId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/seller/orders/${encodeURIComponent(props.orderId ?? "null")}/disputes/${encodeURIComponent(props.disputeId ?? "null")}`;
  export const random = (): IShoppingMallOrderDispute =>
    typia.random<IShoppingMallOrderDispute>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.param("disputeId")(() => typia.assert(props.disputeId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
