import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { ICommunityPlatformComment } from "../../../../structures/ICommunityPlatformComment";
import { IPageICommunityPlatformComment } from "../../../../structures/IPageICommunityPlatformComment";

export * as replies from "./replies/index";
export * as scores from "./scores/index";

/**
 * Retrieve a paginated and sorted list of comments for a specific post with advanced filtering capabilities.
 *
 * This operation provides comprehensive comment retrieval for posts with support for multiple sorting algorithms: Best (confidence-based ranking balancing score and time), New (chronological order), and Controversial (comments with high engagement but neutral scores). The system supports filtering to show top-level comments only or specific comment threads based on parent comment ID.
 *
 * Comments are returned with their vote statistics including upvotes, downvotes, and total scores for display purposes. The API enforces access controls to ensure users can only view comments on accessible posts. Deleted comments are automatically filtered out from results using the is_deleted field from the community_platform_comments table.
 *
 * The pagination system supports efficient loading of large comment threads with configurable page sizes. Each comment includes metadata for threaded display including nesting depth and parent-child relationships when using the hierarchical filtering option. Pagination uses the same parameters specified in the requirements analysis files.
 *
 * This operation references the community_platform_comments table structure which includes is_deleted boolean field for soft delete management and deleted_at timestamp for audit tracking. The parent_comment_id field enables unlimited nesting depth for comment threading as specified in the requirements.
 *
 * @param props.connection
 * @param props.postId UUID of the post to retrieve comments for
 * @param props.body Search criteria for filtering, sorting, and paginating comments
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query the community_platform_comments table for comments belonging to the specified post, filtering by non-deleted status (is_deleted = false). Join with community_platform_comment_scores to get vote statistics for sorting. Support three sorting algorithms: Best (confidence algorithm based on vote score and time), New (created_at descending), and Controversial (controversial_score descending). Implement efficient pagination with cursor-based or offset-based approach. Include comment hierarchy information for threaded display. Filter by parent_comment_id for fetching specific comment threads. Validate that the post exists and is accessible before querying comments.
 * @path /communityPlatform/posts/:postId/comments
 * @accessor api.functional.communityPlatform.posts.comments.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * UUID of the post to retrieve comments for
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Search criteria for filtering, sorting, and paginating comments
     */
    body: ICommunityPlatformComment.IRequest;
  };
  export type Body = ICommunityPlatformComment.IRequest;
  export type Response = IPageICommunityPlatformComment;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/posts/:postId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/posts/${encodeURIComponent(props.postId ?? "null")}/comments`;
  export const random = (): IPageICommunityPlatformComment =>
    typia.random<IPageICommunityPlatformComment>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific comment within a post.
 *
 * This operation returns a complete comment entity including its content, author details, creation timestamps, and relationship to the parent post. The response includes the comment author's profile information (username, display name, avatar) as well as the post context (post ID and title) to provide full context for the comment.
 *
 * Comments can be part of threaded discussions with parent-child relationships supporting unlimited nesting depth. The operation validates that the requested comment belongs to the specified post to ensure data integrity and proper access control.
 *
 * Security considerations include ensuring that comment access follows the same visibility rules as the parent post, including community membership requirements and moderation status. Deleted comments are not returned through this endpoint unless the requesting user has appropriate moderation permissions.
 *
 * @param props.connection
 * @param props.postId Unique identifier of the parent post (UUID format)
 * @param props.commentId Unique identifier of the comment to retrieve (UUID format)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Retrieve a specific comment by its ID within the context of a post. Validate that the comment exists and belongs to the specified post. Return the complete comment entity with author information, post context, and all metadata fields. Handle both top-level comments and nested replies using the existing database relationship structure. Ensure proper error handling for non-existent comments or mismatched post-comment relationships.
 * @path /communityPlatform/posts/:postId/comments/:commentId
 * @accessor api.functional.communityPlatform.posts.comments.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the parent post (UUID format)
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Unique identifier of the comment to retrieve (UUID format)
     */
    commentId: string & tags.Format<"uuid">;
  };
  export type Response = ICommunityPlatformComment;

  export const METADATA = {
    method: "GET",
    path: "/communityPlatform/posts/:postId/comments/:commentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/posts/${encodeURIComponent(props.postId ?? "null")}/comments/${encodeURIComponent(props.commentId ?? "null")}`;
  export const random = (): ICommunityPlatformComment =>
    typia.random<ICommunityPlatformComment>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("commentId")(() => typia.assert(props.commentId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
