import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IDiscussionBoardAdministratorGradeChange } from "../../../../../structures/IDiscussionBoardAdministratorGradeChange";
import { IPageIDiscussionBoardAdministratorGradeChange } from "../../../../../structures/IPageIDiscussionBoardAdministratorGradeChange";

/**
 * Search and filter administrator grade change history records.
 *
 * This operation provides comprehensive search capabilities for administrator grade change records, allowing super administrators to review promotion and demotion history. The search supports text matching on reason fields, date range filtering, and pagination for efficient browsing of historical grade transitions.
 *
 * Super administrators can search for specific grade change events, track promotion patterns, and review administrative decisions. The operation returns paginated results with summary information optimized for list displays, including timestamps, grade transitions, and abbreviated reason text.
 *
 * The operation requires super administrator privileges for access control. Related operations include viewing individual grade change details through separate administrator management endpoints.
 *
 * Note: This operation performs hard queries on grade change records and does not support soft deletion functionality since the underlying schema maintains permanent grade change history.
 *
 * @param props.connection
 * @param props.administratorId Target administrator's unique identifier
 * @param props.body Search criteria and pagination parameters for grade change history
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdmin
 * @x-autobe-specification Query the discussion_board_administrator_grade_changes table filtered by administrator_id. Support text search on reason field using trigram indexing. Implement pagination with cursor-based or offset-based approach. Allow filtering by date ranges (created_at) and grade change types (old_grade/new_grade combinations). Return summary information excluding full audit details for list display.
 * @path /discussionBoard/superAdmin/administrators/:administratorId/grade-changes
 * @accessor api.functional.discussionBoard.superAdmin.administrators.grade_changes.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Target administrator's unique identifier
     */
    administratorId: string & tags.Format<"uuid">;

    /**
     * Search criteria and pagination parameters for grade change history
     */
    body: IDiscussionBoardAdministratorGradeChange.IRequest;
  };
  export type Body = IDiscussionBoardAdministratorGradeChange.IRequest;
  export type Response = IPageIDiscussionBoardAdministratorGradeChange.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/discussionBoard/superAdmin/administrators/:administratorId/grade-changes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/discussionBoard/superAdmin/administrators/${encodeURIComponent(props.administratorId ?? "null")}/grade-changes`;
  export const random =
    (): IPageIDiscussionBoardAdministratorGradeChange.ISummary =>
      typia.random<IPageIDiscussionBoardAdministratorGradeChange.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("administratorId")(() =>
        typia.assert(props.administratorId),
      );
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific grade change record for an administrator.
 *
 * This operation returns detailed information about a particular administrator grade change, including the previous and new administrator grades, the reason for the change, the administrator who performed the change, and the timestamp when the change was recorded. Grade changes represent significant transitions in administrator privileges, such as promotions from regular to super administrator or demotions from super to regular administrator.
 *
 * The operation requires both administrator ID and grade change ID parameters to ensure proper scoping and authorization. Only authorized administrators should have access to view grade change records, as they contain sensitive information about administrator privilege management within the system.
 *
 * This operation complements the broader administrator management system by providing detailed audit trail access for individual grade change events, supporting transparency and accountability in administrator hierarchy management.
 *
 * @param props.connection
 * @param props.administratorId ID of the administrator whose grade change record is being retrieved
 * @param props.gradeChangeId ID of the specific grade change record to retrieve
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdmin
 * @x-autobe-specification Query the discussion_board_administrator_grade_changes table using the gradeChangeId parameter. Verify that the grade change belongs to the specified administratorId by checking the administrator_id field. Return the complete grade change record including id, administrator_id, changed_by_administrator_id, old_grade, new_grade, reason, and created_at fields. Ensure the operation validates that both administratorId and gradeChangeId are valid UUIDs and that the grade change record exists and belongs to the specified administrator.
 * @path /discussionBoard/superAdmin/administrators/:administratorId/grade-changes/:gradeChangeId
 * @accessor api.functional.discussionBoard.superAdmin.administrators.grade_changes.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * ID of the administrator whose grade change record is being retrieved
     */
    administratorId: string & tags.Format<"uuid">;

    /**
     * ID of the specific grade change record to retrieve
     */
    gradeChangeId: string & tags.Format<"uuid">;
  };
  export type Response = IDiscussionBoardAdministratorGradeChange;

  export const METADATA = {
    method: "GET",
    path: "/discussionBoard/superAdmin/administrators/:administratorId/grade-changes/:gradeChangeId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/discussionBoard/superAdmin/administrators/${encodeURIComponent(props.administratorId ?? "null")}/grade-changes/${encodeURIComponent(props.gradeChangeId ?? "null")}`;
  export const random = (): IDiscussionBoardAdministratorGradeChange =>
    typia.random<IDiscussionBoardAdministratorGradeChange>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("administratorId")(() =>
        typia.assert(props.administratorId),
      );
      assert.param("gradeChangeId")(() => typia.assert(props.gradeChangeId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
