import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
export * as communityModeratorAssignments from "./communityModeratorAssignments/index";

/**
 * Delete a community by its unique name.
 *
 * Deletes the specified community by its unique name.
 *
 * This operation targets the reddit_community_communities table, where each
 * community is uniquely identified by its immutable name field. Deletion is a
 * hard delete, permanently removing the database record and any related
 * subsidiary data following referential integrity constraints.
 *
 * Security and permissions are enforced to restrict deletion capabilities to
 * authorized roles such as administrators or community moderators. Errors
 * related to non-existence or insufficient permissions are properly handled and
 * conveyed.
 *
 * Related operations include creating communities and managing moderator
 * assignments in the community_moderator_assignments table.
 *
 * @param props.connection
 * @param props.communityName Unique community name of the community (global
 *   scope)
 * @path /redditCommunity/admin/communities/:communityName
 * @accessor api.functional.redditCommunity.admin.communities.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique community name of the community (global scope) */
    communityName: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/redditCommunity/admin/communities/:communityName",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditCommunity/admin/communities/${encodeURIComponent(props.communityName ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityName")(() => typia.assert(props.communityName));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
