import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia from "typia";
import { patchShoppingMallShoppingMallSkuOptions } from "../../../providers/patchShoppingMallShoppingMallSkuOptions";
import { getShoppingMallShoppingMallSkuOptionsCode } from "../../../providers/getShoppingMallShoppingMallSkuOptionsCode";

import { IPageIShoppingMallSkuOption } from "../../../api/structures/IPageIShoppingMallSkuOption";
import { IShoppingMallSkuOption } from "../../../api/structures/IShoppingMallSkuOption";

@Controller("/shoppingMall/shoppingMallSkuOptions")
export class ShoppingmallShoppingmallskuoptionsController {
  /**
   * Search and retrieve a paginated list of shopping mall SKU options.
   *
   * Retrieve a filtered and paginated list of SKU options belonging to SKU
   * option groups within the shopping mall platform.
   *
   * This operation supports advanced search and filtering capabilities
   * including partial matching on the option name, exact matching on unique
   * codes, and range searches on price adjustments. Pagination and sorting
   * options are available to efficiently browse large sets of SKU options.
   *
   * The SKU options returned belong to the shopping_mall_sku_options table as
   * defined in the Prisma schema, including properties like name, code, price
   * adjustments, and timestamps indicating creation, updates, and soft deletion
   * status.
   *
   * Security: This is a public endpoint requiring no authentication, allowing
   * any user or system component to query SKU options.
   *
   * Related operations include retrieving a single SKU option by code.
   *
   * @param connection
   * @param body Search criteria and pagination parameters for filtering
   *   shopping mall SKU options
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @TypedBody()
    body: IShoppingMallSkuOption.IRequest,
  ): Promise<IPageIShoppingMallSkuOption.ISummary> {
    try {
      return await patchShoppingMallShoppingMallSkuOptions({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a specific shopping mall SKU option by unique code.
   *
   * Retrieve detailed information about a specific SKU option identified by its
   * unique code within the shopping mall platform.
   *
   * The SKU option includes all relevant details stored in the
   * shopping_mall_sku_options Prisma table such as the name, code, price
   * adjustment, creation and update timestamps, and optional soft deletion
   * timestamp.
   *
   * This endpoint uses the unique code as a path parameter to provide
   * human-readable and precise identification of SKU options.
   *
   * No authentication is required to access this endpoint.
   *
   * Related operations include listing SKU options with search filters.
   *
   * @param connection
   * @param code Unique business identifier code of the target SKU option
   *   (global scope)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":code")
  public async at(
    @TypedParam("code")
    code: string,
  ): Promise<IShoppingMallSkuOption> {
    try {
      return await getShoppingMallShoppingMallSkuOptionsCode({
        code,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
