import { Controller } from "@nestjs/common";
import { TypedRoute } from "@nestia/core";
import typia from "typia";
import { getTodoAppUserStatisticsDailyCompletions } from "../../../../../providers/getTodoAppUserStatisticsDailyCompletions";
import { UserAuth } from "../../../../../decorators/UserAuth";
import { UserPayload } from "../../../../../decorators/payload/UserPayload";

import { ITodoAppTaskCompletionsStatistics } from "../../../../../api/structures/ITodoAppTaskCompletionsStatistics";

@Controller("/todoApp/user/statistics/daily-completions")
export class TodoappUserStatisticsDaily_completionsController {
  /**
   * Retrieve daily task completion statistics for authenticated user.
   *
   * Access daily task completion statistics showing the number of tasks
   * completed each day over a specified timeframe. This operation aggregates
   * completion events from the task completion history to provide daily
   * completion counts and trend analysis.
   *
   * The statistics include completion counts per calendar day, enabling users
   * to identify productive periods, track consistency in task completion, and
   * visualize completion patterns over time. The data supports productivity
   * analysis and helps users understand their daily workflow effectiveness.
   *
   * Daily completion statistics provide insights into work patterns, identify
   * peak productivity days, and reveal trends that support better task
   * scheduling and time management strategies. Users can leverage this
   * information to optimize their daily routines and maintain consistent
   * completion rates.
   *
   * The operation queries completion records across the defined timeframe while
   * filtering by authenticated user to maintain data privacy. The aggregated
   * data supports external dashboard rendering and personal productivity
   * analysis without exposing individual task completion details or sensitive
   * information.
   *
   * @param connection
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @UserAuth()
    user: UserPayload,
  ): Promise<ITodoAppTaskCompletionsStatistics> {
    try {
      return await getTodoAppUserStatisticsDailyCompletions({
        user,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
