import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommerceMallInventoryRecord } from "../../../../../../../structures/IEcommerceMallInventoryRecord";
import { IPageIEcommerceMallInventoryRecord } from "../../../../../../../structures/IPageIEcommerceMallInventoryRecord";

/**
 * List complete inventory history for a product variant with filtering and pagination support.
 *
 * Provides sellers with a comprehensive audit trail of all stock movements for their product variants. Each record shows the timestamp, quantity change, running total, operation type, reason, and optional reference to triggering transaction. Supports filtering by date range, operation type, quantity direction, and pagination for efficient browsing of historical data.
 *
 * ### Security & Authorization
 * - Sellers can only view inventory history for product variants they own
 * - Administrators and super administrators can view inventory history for any product variant on the platform
 * - Attempting to view another seller's inventory history returns HTTP 403 Forbidden
 *
 * ### Filter Capabilities
 * - Date range: created_at from/to timestamps
 * - Operation type: RESTOCK, ADJUSTMENT, LOSS, ORDER_DEDUCTION, REFUND_RETURN, CANCELLATION_RETURN
 * - Quantity direction: POSITIVE (stock addition), NEGATIVE (stock removal), ALL
 * - Pagination: cursor-based with configurable page size
 *
 * ### Response Structure
 * Returns paginated inventory records with running stock total calculations. Each record includes the cumulative stock level after that transaction, enabling sellers to visualize stock level trends over time.
 *
 * @param props.connection
 * @param props.productId Product identifier. The variant must belong to this product.
 * @param props.variantId Product variant identifier. Must belong to the specified product.
 * @param props.body Filter and pagination criteria for inventory history list including date range, operation type, quantity direction, and cursor-based pagination parameters.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Query ecommerce_mall_inventory_records table filtered
 *   by product_variant_id derived from variantId (which belongs to the
 *   specified productId).
 *
 * Apply pagination using cursor-based pagination for efficiency with large result sets. Sort results by created_at DESC (newest first) for chronological browsing.
 *
 * Apply optional filters:
 * - date range: created_at between from and to timestamps
 * - operation_type: exact match or multiple values
 * - quantity_direction: filter by POSITIVE (>0), NEGATIVE (<0), or ALL
 *
 * Calculate running stock total for each record by SUM(quantity_change) of all preceding records (ordered by created_at ASC) for that variant.
 *
 * Verify ownership: For seller actors, check that product exists and seller_id matches the requesting seller's ID. For admin actors, skip ownership verification.
 *
 * Return paginated results with total count, cursor values for next/previous pages, and inventory records with cumulative stock calculations.
 *
 * Handle edge cases:
 * - No records found: return empty array with zero total count
 * - Soft-deleted inventory records: exclude from results (WHERE deleted_at IS NULL)
 * - Invalid variant ID: return HTTP 404 Not Found
 * - Product not owned by seller: return HTTP 403 Forbidden (for seller actors only)
 * @path /ecommerceMall/seller/products/:productId/variants/:variantId/inventory/history
 * @accessor api.functional.ecommerceMall.seller.products.variants.inventory.history.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Product identifier. The variant must belong to this product.
     */
    productId: string & tags.Format<"uuid">;

    /**
     * Product variant identifier. Must belong to the specified product.
     */
    variantId: string & tags.Format<"uuid">;

    /**
     * Filter and pagination criteria for inventory history list including date range, operation type, quantity direction, and cursor-based pagination parameters.
     */
    body: IEcommerceMallInventoryRecord.IRequest;
  };
  export type Body = IEcommerceMallInventoryRecord.IRequest;
  export type Response = IPageIEcommerceMallInventoryRecord.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/ecommerceMall/seller/products/:productId/variants/:variantId/inventory/history",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/ecommerceMall/seller/products/${encodeURIComponent(props.productId ?? "null")}/variants/${encodeURIComponent(props.variantId ?? "null")}/inventory/history`;
  export const random = (): IPageIEcommerceMallInventoryRecord.ISummary =>
    typia.random<IPageIEcommerceMallInventoryRecord.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.param("variantId")(() => typia.assert(props.variantId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
