import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallInventoryRecord } from "../../../../../structures/IPageIShoppingMallInventoryRecord";
import { IShoppingMallInventoryRecord } from "../../../../../structures/IShoppingMallInventoryRecord";

/**
 * Retrieve a paginated and filtered list of inventory change records for a specific product variant.
 *
 * This operation provides sellers with complete visibility into their product variant's stock movement history. Each record represents a single inventory change event, whether from manual restocking, adjustments, or automatic updates from orders, cancellations, and refunds.
 *
 * Supports filtering by date range and reason code, with chronological ordering by timestamp. Response includes quantity change amount, reason categorization, and creation timestamp for each record. The inventory history is read-only and immutable, forming a permanent audit trail for stock level verification and dispute resolution.
 *
 * Only accessible for variants owned by the authenticated seller. Returns 404 if the variant does not exist or belongs to a different seller.
 *
 * @param props.connection
 * @param props.variantId Product variant identifier (UUID format)
 * @param props.body Search criteria and pagination parameters for filtering inventory history
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Query shopping_mall_inventory_records table filtered by product_variant_id.
 *
 * Validate that the variant exists and belongs to the authenticated seller by joining with shopping_mall_product_variants and shopping_mall_products tables.
 *
 * Apply optional filters from request body: date range (created_at between start and end), reason code matching.
 *
 * Order results by created_at descending (newest first) for chronological display.
 *
 * Implement cursor-based or offset pagination with configurable page size.
 *
 * Return summary fields: id, quantity_change, reason, created_at.
 *
 * Handle edge cases: variant not found (404), variant not owned by seller (403), no inventory records (empty array with pagination metadata).
 * @path /shoppingMall/seller/inventory/history/:variantId
 * @accessor api.functional.shoppingMall.seller.inventory.history.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Product variant identifier (UUID format)
     */
    variantId: string & tags.Format<"uuid">;

    /**
     * Search criteria and pagination parameters for filtering inventory history
     */
    body: IShoppingMallInventoryRecord.IRequest;
  };
  export type Body = IShoppingMallInventoryRecord.IRequest;
  export type Response = IPageIShoppingMallInventoryRecord.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/inventory/history/:variantId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/seller/inventory/history/${encodeURIComponent(props.variantId ?? "null")}`;
  export const random = (): IPageIShoppingMallInventoryRecord.ISummary =>
    typia.random<IPageIShoppingMallInventoryRecord.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("variantId")(() => typia.assert(props.variantId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
