import { tags } from "typia";

import { IDiscussionBoardAdmin } from "./IDiscussionBoardAdmin";
import { IDiscussionBoardMember } from "./IDiscussionBoardMember";

/**
 * Complete ban record representing an active user access restriction. Contains the ban reason, immutable ban timestamp, and references to both the banned member and the enforcing administrator. Used for administrative transparency, audit purposes, and ban management operations.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardBan = {
  /**
   * Unique identifier for the ban record.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from discussion_board_bans.id. UUID format generated by database.
   */
  id: string & tags.Format<"uuid">;

  /**
   * The banned member's profile summary including display name and account status.
   *
   * @x-autobe-database-schema-property member
   * @x-autobe-specification Relation via member_id FK JOIN to discussion_board_members. Returns IDiscussionBoardMember.ISummary with display_name and profile info.
   */
  member: IDiscussionBoardMember.ISummary;

  /**
   * The administrator who imposed this ban, including their grade level.
   *
   * @x-autobe-database-schema-property admin
   * @x-autobe-specification Relation via admin_id FK JOIN to discussion_board_admins. Returns IDiscussionBoardAdmin.ISummary with grade level.
   */
  admin: IDiscussionBoardAdmin.ISummary;

  /**
   * Ban reason explaining why the user was banned. Required for administrative transparency and audit purposes.
   *
   * @x-autobe-database-schema-property reason
   * @x-autobe-specification Direct mapping from discussion_board_bans.reason. Required field with min/max length validation for administrative transparency.
   */
  reason: string;

  /**
   * Timestamp when the ban was imposed. Automatically recorded and cannot be modified.
   *
   * @x-autobe-database-schema-property banned_at
   * @x-autobe-specification Direct mapping from discussion_board_bans.banned_at. Auto-generated at ban creation, immutable thereafter for audit integrity.
   */
  banned_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the ban record was created in the database.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from discussion_board_bans.created_at. System-managed timestamp.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the ban record was last updated.
   *
   * @x-autobe-database-schema-property updated_at
   * @x-autobe-specification Direct mapping from discussion_board_bans.updated_at. Updated on every ban record modification.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the ban was lifted (user unbanned). Null if the ban is still active.
   *
   * @x-autobe-database-schema-property deleted_at
   * @x-autobe-specification Direct mapping from discussion_board_bans.deleted_at. Nullable: null = active ban, value = user was unbanned (ban lifted).
   */
  deleted_at: (string & tags.Format<"date-time">) | null;
};
export namespace IDiscussionBoardBan {
  /**
   * Query parameters for filtering and paginating the banned users list. Administrators can search across banned user information and ban reason text, filter by ban date ranges, and control pagination and sorting. All parameters are optional.
   */
  export type IRequest = {
    /**
     * Search term matched against user display name, email, and ban reason text.
     *
     * @x-autobe-specification Text search across discussion_board_members.display_name, discussion_board_members.email, and discussion_board_bans.reason using LIKE matching. Implemented as OR condition across all three fields.
     */
    search?: string | undefined;

    /**
     * Page number for pagination (1-indexed).
     *
     * @x-autobe-specification 1-indexed page number for offset-based pagination. Used with limit to calculate OFFSET: (page - 1) * limit. Defaults to 1 if not provided.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of items per page.
     *
     * @x-autobe-specification Number of items per page for pagination. Maximum 100 items. Used with page to calculate OFFSET and LIMIT clause. Defaults to platform standard if not provided.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Field to sort by: banned_at, display_name, email, or reason.
     *
     * @x-autobe-specification Field name to sort by. Valid values: banned_at, display_name, email, reason. Maps to ORDER BY clause. Defaults to banned_at if not provided.
     */
    sort?: string | undefined;

    /**
     * Sort direction: ascending or descending.
     *
     * @x-autobe-specification Sort direction: 'asc' for ascending, 'desc' for descending. Maps to ASC/DESC in ORDER BY clause. Defaults to desc if not provided.
     */
    direction?: "asc" | "desc" | undefined;

    /**
     * Filter bans applied on or after this timestamp.
     *
     * @x-autobe-specification ISO 8601 datetime string. Filters discussion_board_bans.banned_at >= from. Inclusive lower bound for ban timestamp range.
     */
    from?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter bans applied on or before this timestamp.
     *
     * @x-autobe-specification ISO 8601 datetime string. Filters discussion_board_bans.banned_at <= to. Inclusive upper bound for ban timestamp range.
     */
    to?: (string & tags.Format<"date-time">) | undefined;
  };

  /**
   * Request body for creating a ban record to restrict a user's access to the discussion board platform. Contains the target member's UUID and the ban reason explaining the justification for access restriction. Used by administrators when imposing a ban on a member account.
   */
  export type ICreate = {
    /**
     * Unique identifier of the member account to ban. Must be a valid UUID of an existing member who is not currently banned.
     *
     * @x-autobe-database-schema-property member_id
     * @x-autobe-specification Direct mapping from discussion_board_bans.member_id. UUID format. Validates member exists in discussion_board_members table and is not already banned (unique constraint on member_id).
     */
    member_id: string & tags.Format<"uuid">;

    /**
     * Ban reason explaining why the user was banned. Required for administrative transparency and must meet length validation requirements.
     *
     * @x-autobe-database-schema-property reason
     * @x-autobe-specification Direct mapping from discussion_board_bans.reason. String type. Validates minimum and maximum length requirements per business rules (ban reason validation).
     */
    reason: string;
  };

  /**
   * Request body for updating an existing ban record's reason. Allows administrators to modify the ban reason to provide accurate documentation, correct errors, or update justification while preserving audit integrity. The banned_at timestamp and fundamental relationships (who was banned, by whom) remain immutable.
   */
  export type IUpdate = {
    /**
     * Updated ban reason explaining why the user was banned. Required for administrative transparency and must meet validation requirements for minimum/maximum length. Allows administrators to correct errors or provide more accurate documentation.
     *
     * @x-autobe-database-schema-property reason
     * @x-autobe-specification Direct mapping from discussion_board_bans.reason. Backend validates: required field, minimum length (e.g., 10 chars), maximum length (e.g., 500 chars) per ban validation rules section 232. Content must provide clear justification for administrative transparency.
     */
    reason?: string | undefined;
  };

  /**
   * Lightweight ban record summary for administrative oversight. Displays the banned user's profile, enforcing administrator, ban reason, and when the ban was applied. Used in paginated banned users lists for platform governance.
   */
  export type ISummary = {
    /**
     * Unique identifier for this ban record.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from discussion_board_bans.id. UUID format.
     */
    id: string & tags.Format<"uuid">;

    /**
     * The banned user's profile summary including display name for identification.
     *
     * @x-autobe-database-schema-property member
     * @x-autobe-specification JOIN to discussion_board_members via member_id FK. Returns IDiscussionBoardMember.ISummary with id, display_name, bio, status, created_at, is_admin.
     */
    member: IDiscussionBoardMember.ISummary;

    /**
     * The administrator who enforced this ban, for accountability and transparency.
     *
     * @x-autobe-database-schema-property admin
     * @x-autobe-specification JOIN to discussion_board_admins via admin_id FK. Returns IDiscussionBoardAdmin.ISummary with id, grade, created_at, and nested member summary.
     */
    admin: IDiscussionBoardAdmin.ISummary;

    /**
     * The documented reason explaining why the user's access was restricted.
     *
     * @x-autobe-database-schema-property reason
     * @x-autobe-specification Direct mapping from discussion_board_bans.reason. Required field with minimum/maximum length validation per business rules.
     */
    reason: string;

    /**
     * The timestamp when the ban was imposed on the user.
     *
     * @x-autobe-database-schema-property banned_at
     * @x-autobe-specification Direct mapping from discussion_board_bans.banned_at. Automatically recorded at ban creation, immutable thereafter for audit integrity. ISO 8601 date-time format.
     */
    banned_at: string & tags.Format<"date-time">;
  };
}
