import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IDiscussionBoardModerationOverview } from "../../../../../structures/IDiscussionBoardModerationOverview";

/**
 * Moderation dashboard overview aggregating reports, actions, and audit
 * metrics.
 *
 * Compute moderation overview metrics aggregated from reports, moderation
 * actions, and moderation audit records.
 *
 * Purpose and overview: Provides consolidated dashboard metrics for moderation
 * teams: pending reports (24h/7d), counts of moderation actions by type,
 * average time-to-first-action and time-to-resolution, and a short list of
 * recent high-priority audit entries. The recent-items list MUST be sanitized
 * (id, event_type, occurred_at, short_summary) to avoid leaking full
 * event_payload in the overview context. Full payload access requires a
 * deep-link to the audit detail endpoint with stricter access controls.
 *
 * Security considerations and user permissions: Access restricted to moderator
 * or higher roles. The endpoint must enforce RBAC and implement rate limiting
 * and caching to avoid expensive repeated aggregations. Any inclusion of audit
 * detail must adhere to the event_payload redaction policy.
 *
 * Relationship to underlying database entities: Composes queries across
 * discussion_board_reports (status, created_at, processed_at),
 * discussion_board_moderation_actions (created_at, action_type), and
 * discussion_board_moderation_audit (recent high-priority events).
 * Implementations SHOULD paginate or limit the recent-items list.
 *
 * Validation rules and business logic: No path parameters. Optional query
 * parameters for windowing or priority can be added later (e.g., ?window=24h).
 * Return codes: 200 with overview DTO, 401 unauthorized, 403 forbidden, 500
 * internal error.
 *
 * @param props.connection
 * @path /discussionBoard/moderator/dashboard/moderationOverview
 * @accessor api.functional.discussionBoard.moderator.dashboard.moderationOverview.overview
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function overview(
  connection: IConnection,
): Promise<overview.Response> {
  return true === connection.simulate
    ? overview.simulate(connection)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...overview.METADATA,
          path: overview.path(),
          status: null,
        },
      );
}
export namespace overview {
  export type Response = IDiscussionBoardModerationOverview;

  export const METADATA = {
    method: "GET",
    path: "/discussionBoard/moderator/dashboard/moderationOverview",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () =>
    "/discussionBoard/moderator/dashboard/moderationOverview";
  export const random = (): IDiscussionBoardModerationOverview =>
    typia.random<IDiscussionBoardModerationOverview>();
  export const simulate = (_connection: IConnection): Response => {
    return random();
  };
}
