import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ITodoListUser } from "../../../structures/ITodoListUser";

/**
 * Register a new user in the todo_list_users table.
 *
 * This API operation enables new user registration by creating a record in the
 * `todo_list_users` table, which represents each registered end-user in the
 * Todo List application. The request must provide a unique email and a securely
 * hashed password, ensuring that only verified credentials allow access to the
 * service.
 *
 * Security considerations include enforcing uniqueness of `email`, hashing of
 * passwords using current best cryptographic standards, and immediate audit of
 * registration attempts. The table's `created_at` and `updated_at` fields
 * record the registration and any future account changes, while the
 * `deleted_at` field provides a soft-deletion mechanism, which is not triggered
 * by this endpoint.
 *
 * This endpoint ties directly to the single actor identity of the Todo List
 * application, ensuring each account is separate and cannot view or modify
 * other users' data. All business task ownership, session records, and
 * interactions track back to this primary key.
 *
 * Validation rules enforce proper email format, case-insensitive uniqueness,
 * and reject registrations that attempt to reuse deleted or existing addresses.
 * Account creation is always a public operation and requires no existing
 * authentication.
 *
 * The endpoint is critical to the authentication workflow: registration must
 * precede all login or session management, making this the foundational
 * endpoint for onboarding new users.
 *
 * @param props.connection
 * @param props.body New user registration fields, including unique email and
 *   password (plain, to be hashed server-side).
 * @setHeader token.access Authorization
 *
 * @path /auth/user/join
 * @accessor api.functional.auth.user.join
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function join(
  connection: IConnection,
  props: join.Props,
): Promise<join.Response> {
  const output: join.Response =
    true === connection.simulate
      ? join.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...join.METADATA,
            path: join.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace join {
  export type Props = {
    /**
     * New user registration fields, including unique email and password
     * (plain, to be hashed server-side).
     */
    body: ITodoListUser.IJoin;
  };
  export type Body = ITodoListUser.IJoin;
  export type Response = ITodoListUser.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/user/join",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/user/join";
  export const random = (): ITodoListUser.IAuthorized =>
    typia.random<ITodoListUser.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: join.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: join.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Authenticate user and issue JWT token (todo_list_users table).
 *
 * Authenticate a user using credentials in the `todo_list_users` table,
 * validating their unique email and password. Passwords are never stored or
 * transmitted in plain text but always processed as secure hashes. This
 * operation interacts with the `password_hash` and `email` columns for
 * verification and relies on `deleted_at` to determine if accounts are eligible
 * for login.
 *
 * Security considerations include constant-time comparison to prevent timing
 * attacks, full audit logging through session insertion in the
 * `todo_list_user_sessions` schema, and avoidance of explicit existence
 * confirmation for any user account.
 *
 * The endpoint ties every session and all business data ownership in the
 * application back to a valid, authenticated user record. Audit requirements
 * drive full contextual session logging.
 *
 * Input validation rejects malformed or non-unique emails and fails
 * authentication if the supplied credentials do not match. The endpoint is
 * fully public and does not require prior authentication.
 *
 * This operation must be used in conjunction with registration for account
 * onboarding and with token refresh for session continuity.
 *
 * @param props.connection
 * @param props.body Login credentials for authentication, including registered
 *   email and password (plain, for server-side verification).
 * @setHeader token.access Authorization
 *
 * @path /auth/user/login
 * @accessor api.functional.auth.user.login
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function login(
  connection: IConnection,
  props: login.Props,
): Promise<login.Response> {
  const output: login.Response =
    true === connection.simulate
      ? login.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...login.METADATA,
            path: login.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace login {
  export type Props = {
    /**
     * Login credentials for authentication, including registered email and
     * password (plain, for server-side verification).
     */
    body: ITodoListUser.ILogin;
  };
  export type Body = ITodoListUser.ILogin;
  export type Response = ITodoListUser.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/user/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/user/login";
  export const random = (): ITodoListUser.IAuthorized =>
    typia.random<ITodoListUser.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: login.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: login.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Refresh user JWT token using session (todo_list_user_sessions table).
 *
 * Refresh an existing user session's JWT access token using a valid refresh
 * token, with all user and session validation handled against
 * `todo_list_user_sessions` and `todo_list_users` tables. Successful refresh
 * issues a new access token and updates session timestamps and audit metadata.
 *
 * Privacy is maintained by never disclosing whether a session or user still
 * exists; errors give no additional information. The endpoint supports
 * continuous access security by limiting session lifetimes and granting users
 * flexible authentication continuity with strong integrity.
 *
 * This operation is core to supporting modern SPA and mobile session
 * lifecycles.
 *
 * Input is strictly limited to a valid refresh token, and output is a new
 * authentication payload in standard format. No user credentials are required
 * for this flow, and the endpoint is available only to clients already holding
 * a valid refresh token associated with an active session.
 *
 * @param props.connection
 * @param props.body Refresh token for current session, linked securely to
 *   user/session records.
 * @setHeader token.access Authorization
 *
 * @path /auth/user/refresh
 * @accessor api.functional.auth.user.refresh
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function refresh(
  connection: IConnection,
  props: refresh.Props,
): Promise<refresh.Response> {
  const output: refresh.Response =
    true === connection.simulate
      ? refresh.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...refresh.METADATA,
            path: refresh.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace refresh {
  export type Props = {
    /**
     * Refresh token for current session, linked securely to user/session
     * records.
     */
    body: ITodoListUser.IRefresh;
  };
  export type Body = ITodoListUser.IRefresh;
  export type Response = ITodoListUser.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/user/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/user/refresh";
  export const random = (): ITodoListUser.IAuthorized =>
    typia.random<ITodoListUser.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: refresh.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: refresh.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
