import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IRedditCloneComment } from "../../../../../../api/structures/IRedditCloneComment";
import { MemberAuth } from "../../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../../decorators/payload/MemberPayload";
import { deleteRedditCloneMemberRedditCloneCommentsCommentIdRepliesReplyId } from "../../../../../../providers/deleteRedditCloneMemberRedditCloneCommentsCommentIdRepliesReplyId";
import { postRedditCloneMemberRedditCloneCommentsCommentIdReplies } from "../../../../../../providers/postRedditCloneMemberRedditCloneCommentsCommentIdReplies";
import { putRedditCloneMemberRedditCloneCommentsCommentIdRepliesReplyId } from "../../../../../../providers/putRedditCloneMemberRedditCloneCommentsCommentIdRepliesReplyId";

@Controller("/redditClone/member/redditClone/comments/:commentId/replies")
export class RedditcloneMemberRedditcloneCommentsRepliesController {
  /**
   * Create a reply to an existing comment.
   *
   * This endpoint allows authenticated members to reply to any existing comment, creating a nested reply thread. The reply is associated with the same post as the parent comment and inherits the thread structure through the parent_comment_id reference. Replies can themselves have unlimited nesting depth - there is no restriction on how deep reply chains can go.
   *
   * The authenticated user becomes the author of the reply. Content must be non-empty and is limited to a reasonable length. Each reply starts with a vote score of zero.
   *
   * If the parent comment has been soft-deleted (deleted_at is set but record exists), new replies are still allowed. If the parent comment has been permanently deleted (record does not exist), a 404 error is returned.
   *
   * @param connection
   * @param commentId The unique identifier of the parent comment being replied to.
   * @param body The reply content for the new comment.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification 1. Retrieve the authenticated member ID from the
     *   request session. 2. Validate that the parent comment with {commentId}
     *   exists and is not permanently deleted. 3. Extract the
     *   reddit_clone_post_id from the parent comment for associating the reply.
     *   4. Validate request body: content must be non-empty string, reject
     *   empty/whitespace-only content. 5. Create new comment record with: - id:
     *   generated UUID - reddit_clone_post_id: copied from parent comment -
     *   reddit_clone_member_id: from authenticated session - parent_comment_id:
     *   {commentId} from path - content: from request body - vote_score: 0
     *   (initial) - created_at: current timestamp - updated_at: current
     *   timestamp - deleted_at: null 6. Return the created comment with
     *   computed fields.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("commentId")
    commentId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IRedditCloneComment.ICreate,
  ): Promise<IRedditCloneComment> {
    try {
      return await postRedditCloneMemberRedditCloneCommentsCommentIdReplies({
        member,
        commentId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update the content of an existing reply to a comment.
   *
   * This operation allows a member to edit the text content of their own reply. Only the content field can be modified through this endpoint. Vote scores, author attribution, and timestamps are managed automatically by the system.
   *
   * The authenticated user must be the author of the reply. Attempts to update a reply authored by another user will be rejected with a 403 Forbidden response. If the reply has been deleted, updates are not permitted.
   *
   * The parent comment and its nested structure remain intact after the update.
   *
   * @param connection
   * @param commentId Parent comment identifier (the comment being replied to)
   * @param replyId Reply comment identifier to update
   * @param body Update request containing the new content for the reply
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Update the content field of the reply comment
     *   identified by replyId.
   *
   * Implementation steps:
   * 1. Extract commentId and replyId from path parameters
   * 2. Authenticate the requesting member from session
   * 3. Verify the reply exists and is not soft-deleted (deleted_at is null)
   * 4. Verify the parent comment exists (commentId matches)
   * 5. Verify the authenticated member is the author of the reply (reddit_clone_member_id matches)
   * 6. Validate the request body content field is not empty and within length limits
   * 7. Update the content field and set updated_at to current timestamp
   * 8. Return the updated comment entity with author information
   *
   * Error handling:
   * - 404 Not Found: If reply or parent comment does not exist
   * - 403 Forbidden: If authenticated user is not the author of the reply
   * - 400 Bad Request: If content is empty or exceeds length limits
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":replyId")
  public async update(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("commentId")
    commentId: string & tags.Format<"uuid">,
    @TypedParam("replyId")
    replyId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IRedditCloneComment.IUpdate,
  ): Promise<IRedditCloneComment> {
    try {
      return await putRedditCloneMemberRedditCloneCommentsCommentIdRepliesReplyId(
        {
          member,
          commentId,
          replyId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Removes a nested reply to a comment from public view.
   *
   * This endpoint allows authenticated users to delete their own comment replies. When a reply is deleted, the system performs a soft-delete by setting the deleted_at timestamp, which preserves the comment's place in the nested reply tree while removing its content from public view.
   *
   * The authenticated user must be the author of the reply being deleted. Replies to deleted comments can still be deleted by their authors. This operation does not affect sibling replies or the parent comment.
   *
   * @param connection
   * @param commentId Unique identifier of the parent comment (must exist in reddit_clone_comments)
   * @param replyId Unique identifier of the reply to delete (must be a child of the parent comment)
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Implement soft-delete for the comment reply:
   *
   * 1. Extract commentId and replyId from path parameters
   * 2. Verify authenticated user exists (require member session)
   * 3. Query reddit_clone_comments table to find the reply by replyId
   * 4. Verify reply.parent_comment_id equals commentId (ensure reply belongs to specified parent)
   * 5. Verify reply.reddit_clone_member_id equals authenticated user's id (only author can delete)
   * 6. If reply.deleted_at is already set, return success (idempotent)
   * 7. Set reply.deleted_at to current timestamp
   * 8. Return 204 No Content on success
   *
   * Error responses:
   * - 401 Unauthorized: No valid session
   * - 403 Forbidden: User is not the author of the reply
   * - 404 Not Found: Comment or reply does not exist
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":replyId")
  public async erase(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("commentId")
    commentId: string & tags.Format<"uuid">,
    @TypedParam("replyId")
    replyId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteRedditCloneMemberRedditCloneCommentsCommentIdRepliesReplyId(
        {
          member,
          commentId,
          replyId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
