import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IRedditCommunityCommunity } from "../../../../../api/structures/IRedditCommunityCommunity";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { getRedditCommunityMemberCommunitiesCommunityIdStats } from "../../../../../providers/getRedditCommunityMemberCommunitiesCommunityIdStats";

@Controller("/redditCommunity/member/communities/:communityId/stats")
export class RedditcommunityMemberCommunitiesStatsController {
  /**
   * Retrieve comprehensive statistics for a specific community including subscriber count, post metrics, and activity data.
   *
   * This endpoint provides an aggregated view of community health and engagement metrics. It returns the community's basic information along with computed statistics such as total subscribers, post counts, and comment activity. The statistics are pre-computed and maintained in the database for fast retrieval.
   *
   * @param connection
   * @param communityId The unique identifier of the community.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query the reddit_community_communities table by
     *   UUID to fetch the community record.
   *
   * Compute and return the following metrics:
   * - subscriber_count: Count of active subscriptions for this community (status='active', deleted_at IS NULL)
   * - post_count: The post_count field from the communities_posts table (maintained incrementally)
   * - comment_count: Sum of comment_count fields from all active posts in this community
   * - vote_count: Sum of vote_score values from all posts in this community (absolute value for total engagement)
   * - created_at: Community creation timestamp
   * - name: Community name
   *
   * Apply the following validations:
   * - Verify community exists and is not soft-deleted (deleted_at IS NULL)
   * - Return 404 if community is not found or has been deleted
   * - Return only active subscriptions for subscriber count (status='active')
   *
   * Use efficient SQL with COUNT and SUM aggregate functions. Avoid N+1 queries by using JOINs or batch queries.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("communityId")
    communityId: string & tags.Format<"uuid">,
  ): Promise<IRedditCommunityCommunity.IAt> {
    try {
      return await getRedditCommunityMemberCommunitiesCommunityIdStats({
        member,
        communityId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
