import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommerceMallProductVariant } from "../../../../structures/IEcommerceMallProductVariant";

/**
 * Retrieves comprehensive details for a specific product variant nested under its parent product.
 *
 * This operation validates relational integrity by confirming the variant is a direct child of the supplied parent product ID. It verifies that the parent listing remains active and unsoft-deleted to ensure shoppers only access currently available catalog items. The response is automatically enriched by fetching all normalized attribute options from the variant option table, providing a complete variant configuration without requiring additional API calls.
 *
 * @param props.connection
 * @param props.productId The unique identifier of the parent product containing the variant.
 * @param props.variantId The unique identifier of the target product variant to retrieve.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query the ecommerce_mall_product_variants table using
 *   the variantId path parameter. Validate relational integrity by ensuring the
 *   variant belongs to the specified productId via the
 *   ecommerce_mall_product_id foreign key. Verify the parent product exists and
 *   ensure it is not soft-deleted by checking the deleted_at column on the
 *   ecommerce_mall_products table. Fetch all matching option records from the
 *   ecommerce_mall_product_variant_options table where the variant ID matches,
 *   and merge them into a structured options array within the response payload.
 *   Return a 404 Not Found if the parent product or variant does not exist.
 * @path /ecommerceMall/products/:productId/variants/:variantId
 * @accessor api.functional.ecommerceMall.products.variants.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The unique identifier of the parent product containing the variant.
     */
    productId: string & tags.Format<"uuid">;

    /**
     * The unique identifier of the target product variant to retrieve.
     */
    variantId: string & tags.Format<"uuid">;
  };
  export type Response = IEcommerceMallProductVariant;

  export const METADATA = {
    method: "GET",
    path: "/ecommerceMall/products/:productId/variants/:variantId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommerceMall/products/${encodeURIComponent(props.productId ?? "null")}/variants/${encodeURIComponent(props.variantId ?? "null")}`;
  export const random = (): IEcommerceMallProductVariant =>
    typia.random<IEcommerceMallProductVariant>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.param("variantId")(() => typia.assert(props.variantId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
