import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

export * as auth from "./auth/index";
export * as users from "./users/index";
export * as member from "./member/index";
export * as owner from "./owner/index";
export * as communities from "./communities/index";
export * as moderator from "./moderator/index";
export * as posts from "./posts/index";
export * as karmas from "./karmas/index";
export * as comments from "./comments/index";
export * as feed_configs from "./feed_configs/index";
export * as feed_views from "./feed_views/index";
export * as moderator_assignments from "./moderator_assignments/index";
export * as bans from "./bans/index";
export * as moderators from "./moderators/index";
export * as moderation_logs from "./moderation_logs/index";
export * as appeals from "./appeals/index";
export * as moderation_reports from "./moderation_reports/index";
export * as content_types from "./content_types/index";
export * as guest from "./guest/index";

/**
 * Invalid - This was not an operation generation request
 *
 * @param props.connection
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Invalid
 * @path /redditClone/invalid
 * @accessor api.functional.redditClone.invalid
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function invalid(connection: IConnection): Promise<void> {
  return true === connection.simulate
    ? invalid.simulate(connection)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...invalid.METADATA,
          path: invalid.path(),
          status: null,
        },
      );
}
export namespace invalid {
  export const METADATA = {
    method: "GET",
    path: "/redditClone/invalid",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditClone/invalid";
  export const random = (): void => typia.random<void>();
  export const simulate = (_connection: IConnection): void => {
    return random();
  };
}
