import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IEcommerceModificationInventoryRestoration } from "../../../../api/structures/IEcommerceModificationInventoryRestoration";
import { IPageIEcommerceModificationInventoryRestoration } from "../../../../api/structures/IPageIEcommerceModificationInventoryRestoration";
import { SellerAuth } from "../../../../decorators/SellerAuth";
import { SellerPayload } from "../../../../decorators/payload/SellerPayload";
import { getEcommerceSellerModificationInventoryRestorationsRestorationId } from "../../../../providers/getEcommerceSellerModificationInventoryRestorationsRestorationId";
import { patchEcommerceSellerModificationInventoryRestorations } from "../../../../providers/patchEcommerceSellerModificationInventoryRestorations";

@Controller("/ecommerce/seller/modification-inventory-restorations")
export class EcommerceSellerModification_inventory_restorationsController {
  /**
   * Retrieve a specific inventory restoration record by its unique identifier, providing detailed access to restoration records created when cancellation or refund requests are approved. Each restoration record captures the quantity of stock returned to inventory, the business reason for restoration, and links to the specific modification request that triggered it.
   *
   * This operation provides access to the `ecommerce_modification_inventory_restorations` table data, which serves as the central tracking mechanism for inventory restoration throughout the order lifecycle. The restoration process ensures that when orders are modified after payment or delivery, the corresponding inventory quantities are properly restored to available stock. Each restoration record includes the quantity restored, business reason, and references to both the triggering modification request and the underlying inventory record that was restored.
   *
   * Inventory restoration records are essential for maintaining complete stock integrity and audit trail compliance. They work in conjunction with the inventory tracking system to provide accurate stock level calculations and support dispute resolution processes. The system automatically creates these records when cancellation or refund requests are approved, capturing the exact quantity returned to inventory and linking it to the specific business event that triggered the restoration.
   *
   * Access to this operation is restricted to authorized seller users who need to review inventory restoration history for audit purposes, dispute resolution, or inventory management analysis. The response includes complete restoration details along with timestamps for creation and updates, as well as relationships to both the triggering request and the restored inventory record.
   *
   * Related operations include viewing cancellation requests that triggered restorations (GET /cancellation-requests/{requestId}) and refund requests that triggered restorations (GET /refund-requests/{requestId}), as well as accessing the underlying inventory records (GET /inventory-records/{recordId}). For comprehensive audit trail analysis, sellers should also review the related modification requests and their associated status transitions.
   *
   * @param connection
   * @param restorationId Unique identifier of the inventory restoration record to retrieve
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Query the ecommerce_modification_inventory_restorations table by the provided restorationId parameter.
   *
   * Return the complete restoration record including id, quantity_restored, restoration_reason, created_at, updated_at, and deleted_at fields.
   *
   * Include relationship data by joining with cancellation_requests and refund_requests tables to show which modification request triggered this restoration.
   *
   * Also include the inventory_record relationship to show which inventory record was restored.
   *
   * Handle cases where the restoration record does not exist by returning appropriate 404 error.
   *
   * Ensure proper authorization checks - only authorized users should be able to access restoration records.
   *
   * Return soft-deleted records if they exist, as these records are preserved for audit purposes.
   *
   * The response should provide a complete view of the inventory restoration operation for transparency and audit trail purposes.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":restorationId")
  public async at(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("restorationId")
    restorationId: string & tags.Format<"uuid">,
  ): Promise<IEcommerceModificationInventoryRestoration> {
    try {
      return await getEcommerceSellerModificationInventoryRestorationsRestorationId(
        {
          seller,
          restorationId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a filtered and paginated list of inventory restoration records.
   *
   * This operation provides comprehensive search capabilities for tracking inventory restoration events that occur when cancellation or refund requests are approved. Each restoration record represents the return of stock quantities to available inventory, maintaining accurate stock levels throughout the order lifecycle.
   *
   * Administrators can filter results by restoration reason, quantity ranges, creation dates, and associations with specific cancellation or refund requests. The operation supports advanced text search on restoration reasons using PostgreSQL's GIN index for efficient pattern matching.
   *
   * Results include summary information optimized for list displays, showing essential details about each restoration event while maintaining pagination for large datasets. This endpoint is essential for inventory auditing and tracking stock movement patterns across the platform.
   *
   * The response includes pagination metadata for efficient navigation through large result sets, with configurable page sizes and sorting options available through the request body parameters.
   *
   * This is an administrative function that provides oversight capability for tracking inventory adjustments across the entire platform. Access is restricted to authorized administrators to maintain data integrity and security.
   *
   * @param connection
   * @param body Search criteria and pagination parameters for inventory restoration records
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Query ecommerce_modification_inventory_restorations table with comprehensive filtering and pagination capabilities.
   *
   * Apply filters based on:
   * - Restoration reason (partial match using GIN index)
   * - Quantity restored range (min/max)
   * - Creation date range
   * - Association with cancellation requests (by ID)
   * - Association with refund requests (by ID)
   * - Association with inventory records (by ID)
   *
   * Join with related tables for additional context:
   * - ecommerce_cancellation_requests for cancellation details
   * - ecommerce_refund_requests for refund details
   * - ecommerce_inventory_records for inventory context
   *
   * Implement cursor-based pagination for large result sets. Sort by creation date descending by default to show most recent restorations first. Include soft-deleted records in results with appropriate filtering option.
   *
   * Validate that all referenced IDs exist in their respective tables. Ensure proper authorization checks for administrative access only.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @SellerAuth()
    seller: SellerPayload,
    @TypedBody()
    body: IEcommerceModificationInventoryRestoration.IRequest,
  ): Promise<IPageIEcommerceModificationInventoryRestoration.ISummary> {
    try {
      return await patchEcommerceSellerModificationInventoryRestorations({
        seller,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
