import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IDiscussionBoardReport } from "../../../../../structures/IDiscussionBoardReport";

/**
 * Report an article for violating community guidelines.
 *
 * Submit a new report about a published article that the member believes
 * violates community guidelines or policies. This operation creates a report
 * record that enters the moderator review queue and notifies moderators to
 * investigate the reported content.
 *
 * The operation captures why the member filed the report (using predefined
 * reason categories: offensive_language, personal_attack, spam, off_topic,
 * copyright_violation, harassment, other), includes optional detailed context
 * explaining the violation, and associates the report with both the reporting
 * member and the reported article.
 *
 * Security and Access Control: Only authenticated members can file reports,
 * preventing anonymous submissions and enabling moderator follow-up with
 * reporters if needed. Each report captures the filing member's identity for
 * audit purposes. Members can report any published article they encounter, not
 * just articles by specific users, enabling community moderation support.
 *
 * Relationships and Workflow: The created report enters pending_review status
 * and appears in the moderator queue for investigation. Reports reference both
 * the discussion_board_members table (reporter identity) and
 * discussion_board_articles table (the reported content). The report remains in
 * the system as a permanent audit record even after moderators resolve it,
 * tracking all community feedback about content quality.
 *
 * Validation and Business Rules: Reports must specify a reason from the
 * predefined category list to ensure consistent triage. The optional
 * description field (maximum 500 characters) provides context for moderators.
 * The operation initializes the report with pending_review status, null
 * moderator_notes (no investigation yet), and null resolved_at timestamp (not
 * yet resolved). Only published articles can be reported; members cannot report
 * draft or rejected articles from other users.
 *
 * @param props.connection
 * @param props.articleId Unique identifier of the article being reported for
 *   policy violations
 * @param props.body Report submission data including reason category and
 *   optional detailed explanation
 * @path /discussionBoard/member/articles/:articleId/reports
 * @accessor api.functional.discussionBoard.member.articles.reports.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /** Unique identifier of the article being reported for policy violations */
    articleId: string & tags.Format<"uuid">;

    /**
     * Report submission data including reason category and optional
     * detailed explanation
     */
    body: IDiscussionBoardReport.ICreate;
  };
  export type Body = IDiscussionBoardReport.ICreate;
  export type Response = IDiscussionBoardReport;

  export const METADATA = {
    method: "POST",
    path: "/discussionBoard/member/articles/:articleId/reports",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/discussionBoard/member/articles/${encodeURIComponent(props.articleId ?? "null")}/reports`;
  export const random = (): IDiscussionBoardReport =>
    typia.random<IDiscussionBoardReport>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("articleId")(() => typia.assert(props.articleId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
