import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IRedditPlatformFeedPreference } from "../../../../structures/IRedditPlatformFeedPreference";

export * as my from "./my/index";

/**
 * Retrieve user's feed preferences and configuration settings.
 *
 * This endpoint returns the current feed configuration for the authenticated user, including their preferred sorting method, time filters, and other feed-related settings.
 *
 * The feed preferences determine how content appears in the user's feeds (home, popular, community feeds), affecting the ordering and filtering of posts they see.
 *
 * Security Considerations:
 * - Requires authentication - only the user can access their own preferences
 * - Returns user-specific configuration only
 * - No sensitive data exposed
 *
 * Database Relationship:
 * - Direct mapping to reddit_platform_feed_preferences table
 * - One-to-one relationship with user account
 *
 * Related Operations:
 * - PATCH /preferences - Update user's feed preferences
 *
 * @param props.connection
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query reddit_platform_feed_preferences table for the authenticated user's preferences.
 * Return the preference record containing sortingMethod, timeFilter, and other configuration settings.
 * If no preference exists, return default configuration values.
 * Apply authentication to ensure only the user can access their own preferences.
 * @path /redditPlatform/member/preferences
 * @accessor api.functional.redditPlatform.member.preferences.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(connection: IConnection): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(),
          status: null,
        },
      );
}
export namespace at {
  export type Response = IRedditPlatformFeedPreference;

  export const METADATA = {
    method: "GET",
    path: "/redditPlatform/member/preferences",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditPlatform/member/preferences";
  export const random = (): IRedditPlatformFeedPreference =>
    typia.random<IRedditPlatformFeedPreference>();
  export const simulate = (_connection: IConnection): Response => {
    return random();
  };
}

/**
 * Update user-specific feed preferences and configuration settings.
 *
 * This endpoint allows authenticated members to configure their feed experience including default feed type (home, popular, community), sorting algorithms, content visibility filters, theme preferences, and interface density settings. The preferences are stored per-user and persist across sessions to provide a personalized experience.
 *
 * Security Considerations: Only the authenticated user can update their own preferences. The system validates that the requesting user matches the target user ID. All preference updates are logged for audit purposes.
 *
 * Database Schema Relationship: This operation directly corresponds to the reddit_platform_feed_preferences table which stores user-specific configuration values including default_feed_type, default_sort_order, home_feed_subscribed_only, content_karma_threshold, show_nsfw, theme, interface_density, content_language, hide_muted_communities, auto_expand_media, infinite_scroll, comment_sort_order, show_community_recommendations, show_trending_topics, and enable_recommendations flags.
 *
 * Validation Rules: The system validates that preference values are from allowed enums (feed types, sort orders, themes, interface densities, comment sort orders), ensures karma threshold is within acceptable range, and validates content language codes match supported locales. Invalid values result in 400 Bad Request responses.
 *
 * Related Operations: Users retrieve their current preferences through GET /preferences endpoint. The preferences are applied when accessing feeds through GET /feeds/home, GET /feeds/popular, and community-specific feed endpoints.
 *
 * @param props.connection
 * @param props.body Feed preferences update request with user configuration options
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Update user feed preferences in reddit_platform_feed_preferences table.
 * Validate all input against allowed enums and constraints.
 * Apply changes to authenticated user's preferences record.
 * Return updated preferences with all configuration values.
 * Handle missing preferences record by creating new one.
 * Log all preference changes for audit trail.
 * @path /redditPlatform/member/preferences
 * @accessor api.functional.redditPlatform.member.preferences.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Feed preferences update request with user configuration options
     */
    body: IRedditPlatformFeedPreference.IUpdate;
  };
  export type Body = IRedditPlatformFeedPreference.IUpdate;
  export type Response = IRedditPlatformFeedPreference;

  export const METADATA = {
    method: "PATCH",
    path: "/redditPlatform/member/preferences",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditPlatform/member/preferences";
  export const random = (): IRedditPlatformFeedPreference =>
    typia.random<IRedditPlatformFeedPreference>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
