import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IPageIDiscussionBoardArticle } from "../../../../../structures/IPageIDiscussionBoardArticle";

/**
 * Retrieve a paginated list of articles associated with a specific tag.
 *
 * This operation retrieves articles that have been tagged with the specified tag ID. It enables users to explore all articles related to a particular subject or category identified by the tag.
 *
 * The path parameter tagId is a UUID corresponding to the ID of a tag in the discussion_board_tags table.
 *
 * The response returns article summaries, which include the article title, author, section association, creation timestamp, and other relevant summary information.
 *
 * This API is publicly accessible by guests and all authenticated users. No special authorization is required.
 *
 * Related API operations include POST /articles to create articles, GET /articles/{articleId} to retrieve full article details, PATCH /articles to search articles, and GET /tags to retrieve tag details.
 *
 * The implementation involves joining the discussion_board_articles, discussion_board_article_tags, and discussion_board_tags tables, filtering articles by the given tag ID, and returning a paginated list.
 *
 * Only articles with deleted_at = null will be included, effectively filtering out soft-deleted records.
 *
 * Errors include 404 if the tag ID does not exist or 400 for invalid UUID formats.
 *
 * This operation does not modify any data and is idempotent.
 *
 * @param props.connection
 * @param props.tagId Identifier of the tag to filter articles (UUID format).
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor administrator
 * @x-autobe-specification Query discussion_board_article_tags to find all article IDs linked to the provided tagId.
 * Join with discussion_board_articles to retrieve article summaries.
 * Apply pagination and sorting based on query parameters.
 * Ensure filtering excludes soft-deleted articles.
 * Return paginated article summary data.
 * Handle errors for invalid UUID or non-existent tag.
 *
 * This API operation is publicly accessible without authentication.
 *
 * Supports pagination via query parameters such as page number and page size.
 * Sorting can be by creation date ascending or descending.
 * @path /discussionBoard/administrator/tags/:tagId/articles
 * @accessor api.functional.discussionBoard.administrator.tags.articles.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
      );
}
export namespace index {
  export type Props = {
    /**
     * Identifier of the tag to filter articles (UUID format).
     */
    tagId: string & tags.Format<"uuid">;
  };
  export type Response = IPageIDiscussionBoardArticle.ISummary;

  export const METADATA = {
    method: "GET",
    path: "/discussionBoard/administrator/tags/:tagId/articles",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/discussionBoard/administrator/tags/${encodeURIComponent(props.tagId ?? "null")}/articles`;
  export const random = (): IPageIDiscussionBoardArticle.ISummary =>
    typia.random<IPageIDiscussionBoardArticle.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("tagId")(() => typia.assert(props.tagId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
