import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IDiscussionBoardContentFlag } from "../../../../structures/IDiscussionBoardContentFlag";
import { IPageIDiscussionBoardContentFlag } from "../../../../structures/IPageIDiscussionBoardContentFlag";

/**
 * Search and filter content flags for administrator moderation workflow.
 *
 * This operation provides comprehensive search capabilities for content flags reported by users, allowing administrators to efficiently manage the moderation queue. The system supports filtering by flag status, content type, reporter information, and date ranges to help administrators prioritize and organize their moderation tasks.
 *
 * Administrators can search for flags based on specific criteria such as pending review status, particular flag types (spam, harassment, inappropriate content), or flags submitted within specific time periods. The response includes summarized flag information including reporter details, flag reason, status, and creation timestamp for efficient moderation workflow management.
 *
 * The operation integrates with the discussion_board_content_flags table which tracks user-reported content violations, providing administrators with the tools needed to maintain community standards while ensuring transparent and accountable content moderation processes.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for flag filtering
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query the discussion_board_content_flags table with filtering capabilities. Support filtering by status (pending, under_review, resolved, dismissed), flag type, content type (article vs comment), reporter user, and date ranges. Join with related tables for reporter information and flagged content details. Implement pagination with configurable page sizes and sorting options. Return summarized flag information optimized for moderation workflow.
 * @path /discussionBoard/admin/flags
 * @accessor api.functional.discussionBoard.admin.flags.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for flag filtering
     */
    body: IDiscussionBoardContentFlag.IRequest;
  };
  export type Body = IDiscussionBoardContentFlag.IRequest;
  export type Response = IPageIDiscussionBoardContentFlag.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/discussionBoard/admin/flags",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/discussionBoard/admin/flags";
  export const random = (): IPageIDiscussionBoardContentFlag.ISummary =>
    typia.random<IPageIDiscussionBoardContentFlag.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
