import { Module } from "@nestjs/common";

import { AuthGuestuserController } from "./controllers/auth/guestUser/AuthGuestuserController";
import { AuthMemberuserController } from "./controllers/auth/memberUser/AuthMemberuserController";
import { AuthCommunitymoderatorController } from "./controllers/auth/communityModerator/AuthCommunitymoderatorController";
import { AuthPlatformadminController } from "./controllers/auth/platformAdmin/AuthPlatformadminController";
import { CommunityplatformPlatformadminPlatformsettingsController } from "./controllers/communityPlatform/platformAdmin/platformSettings/CommunityplatformPlatformadminPlatformsettingsController";
import { CommunityplatformPlatformadminContentpolicycategoriesController } from "./controllers/communityPlatform/platformAdmin/contentPolicyCategories/CommunityplatformPlatformadminContentpolicycategoriesController";
import { CommunityplatformContentpolicycategoriesController } from "./controllers/communityPlatform/contentPolicyCategories/CommunityplatformContentpolicycategoriesController";
import { CommunityplatformPlatformadminReportreasoncategoriesController } from "./controllers/communityPlatform/platformAdmin/reportReasonCategories/CommunityplatformPlatformadminReportreasoncategoriesController";
import { CommunityplatformCommunityrulecategoriesController } from "./controllers/communityPlatform/communityRuleCategories/CommunityplatformCommunityrulecategoriesController";
import { CommunityplatformPlatformadminCommunityrulecategoriesController } from "./controllers/communityPlatform/platformAdmin/communityRuleCategories/CommunityplatformPlatformadminCommunityrulecategoriesController";
import { CommunityplatformPlatformadminSystemoverviewController } from "./controllers/communityPlatform/platformAdmin/systemOverview/CommunityplatformPlatformadminSystemoverviewController";
import { CommunityplatformPlatformadminGuestusersController } from "./controllers/communityPlatform/platformAdmin/guestUsers/CommunityplatformPlatformadminGuestusersController";
import { CommunityplatformPlatformadminGuestusersSessionsController } from "./controllers/communityPlatform/platformAdmin/guestUsers/sessions/CommunityplatformPlatformadminGuestusersSessionsController";
import { CommunityplatformPlatformadminMemberusersController } from "./controllers/communityPlatform/platformAdmin/memberUsers/CommunityplatformPlatformadminMemberusersController";
import { CommunityplatformMemberuserMemberusersController } from "./controllers/communityPlatform/memberUser/memberUsers/CommunityplatformMemberuserMemberusersController";
import { CommunityplatformPlatformadminMemberusersSessionsController } from "./controllers/communityPlatform/platformAdmin/memberUsers/sessions/CommunityplatformPlatformadminMemberusersSessionsController";
import { CommunityplatformMemberuserMemberusersSessionsController } from "./controllers/communityPlatform/memberUser/memberUsers/sessions/CommunityplatformMemberuserMemberusersSessionsController";
import { CommunityplatformPlatformadminCommunitymoderatorsController } from "./controllers/communityPlatform/platformAdmin/communityModerators/CommunityplatformPlatformadminCommunitymoderatorsController";
import { CommunityplatformPlatformadminCommunitymoderatorsSessionsController } from "./controllers/communityPlatform/platformAdmin/communityModerators/sessions/CommunityplatformPlatformadminCommunitymoderatorsSessionsController";
import { CommunityplatformPlatformadminPlatformadminsController } from "./controllers/communityPlatform/platformAdmin/platformAdmins/CommunityplatformPlatformadminPlatformadminsController";
import { CommunityplatformPlatformadminPlatformadminsSessionsController } from "./controllers/communityPlatform/platformAdmin/platformAdmins/sessions/CommunityplatformPlatformadminPlatformadminsSessionsController";
import { CommunityplatformPlatformadminAccountstatusesController } from "./controllers/communityPlatform/platformAdmin/accountStatuses/CommunityplatformPlatformadminAccountstatusesController";
import { CommunityplatformPlatformadminUsersecurityeventsController } from "./controllers/communityPlatform/platformAdmin/userSecurityEvents/CommunityplatformPlatformadminUsersecurityeventsController";
import { CommunityplatformGuestuserUsersecurityeventsGuestController } from "./controllers/communityPlatform/guestUser/userSecurityEvents/guest/CommunityplatformGuestuserUsersecurityeventsGuestController";
import { CommunityplatformMemberuserUsersecurityeventsMemberuserController } from "./controllers/communityPlatform/memberUser/userSecurityEvents/memberUser/CommunityplatformMemberuserUsersecurityeventsMemberuserController";
import { CommunityplatformPlatformadminUsersecurityeventsCommunitymoderatorController } from "./controllers/communityPlatform/platformAdmin/userSecurityEvents/communityModerator/CommunityplatformPlatformadminUsersecurityeventsCommunitymoderatorController";
import { CommunityplatformPlatformadminUsersecurityeventsPlatformadminController } from "./controllers/communityPlatform/platformAdmin/userSecurityEvents/platformAdmin/CommunityplatformPlatformadminUsersecurityeventsPlatformadminController";
import { CommunityplatformPlatformadminSecurityeventsAudittrailController } from "./controllers/communityPlatform/platformAdmin/securityEvents/auditTrail/CommunityplatformPlatformadminSecurityeventsAudittrailController";
import { CommunityplatformCommunitiesController } from "./controllers/communityPlatform/communities/CommunityplatformCommunitiesController";
import { CommunityplatformMemberuserCommunitiesController } from "./controllers/communityPlatform/memberUser/communities/CommunityplatformMemberuserCommunitiesController";
import { CommunityplatformCommunitymoderatorCommunitiesController } from "./controllers/communityPlatform/communityModerator/communities/CommunityplatformCommunitymoderatorCommunitiesController";
import { CommunityplatformPlatformadminCommunitiesController } from "./controllers/communityPlatform/platformAdmin/communities/CommunityplatformPlatformadminCommunitiesController";
import { CommunityplatformMemberuserCommunityvisibilitylevelsController } from "./controllers/communityPlatform/memberUser/communityVisibilityLevels/CommunityplatformMemberuserCommunityvisibilitylevelsController";
import { CommunityplatformPlatformadminCommunityvisibilitylevelsController } from "./controllers/communityPlatform/platformAdmin/communityVisibilityLevels/CommunityplatformPlatformadminCommunityvisibilitylevelsController";
import { CommunityplatformCommunitymoderatorCommunitiesMembershipsController } from "./controllers/communityPlatform/communityModerator/communities/memberships/CommunityplatformCommunitymoderatorCommunitiesMembershipsController";
import { CommunityplatformPlatformadminCommunitiesMembershipsController } from "./controllers/communityPlatform/platformAdmin/communities/memberships/CommunityplatformPlatformadminCommunitiesMembershipsController";
import { CommunityplatformMemberuserCommunitiesMembershipsController } from "./controllers/communityPlatform/memberUser/communities/memberships/CommunityplatformMemberuserCommunitiesMembershipsController";
import { CommunityplatformMemberuserMemberusersCommunitymembershipsController } from "./controllers/communityPlatform/memberUser/memberUsers/communityMemberships/CommunityplatformMemberuserMemberusersCommunitymembershipsController";
import { CommunityplatformPlatformadminMemberusersCommunitymembershipsController } from "./controllers/communityPlatform/platformAdmin/memberUsers/communityMemberships/CommunityplatformPlatformadminMemberusersCommunitymembershipsController";
import { CommunityplatformCommunitymoderatorCommunitiesMembershiprequestsController } from "./controllers/communityPlatform/communityModerator/communities/membershipRequests/CommunityplatformCommunitymoderatorCommunitiesMembershiprequestsController";
import { CommunityplatformPlatformadminCommunitiesMembershiprequestsController } from "./controllers/communityPlatform/platformAdmin/communities/membershipRequests/CommunityplatformPlatformadminCommunitiesMembershiprequestsController";
import { CommunityplatformMemberuserCommunitiesMembershiprequestsController } from "./controllers/communityPlatform/memberUser/communities/membershipRequests/CommunityplatformMemberuserCommunitiesMembershiprequestsController";
import { CommunityplatformMemberuserMemberusersCommunitymembershiprequestsController } from "./controllers/communityPlatform/memberUser/memberUsers/communityMembershipRequests/CommunityplatformMemberuserMemberusersCommunitymembershiprequestsController";
import { CommunityplatformPlatformadminMemberusersCommunitymembershiprequestsController } from "./controllers/communityPlatform/platformAdmin/memberUsers/communityMembershipRequests/CommunityplatformPlatformadminMemberusersCommunitymembershiprequestsController";
import { CommunityplatformPlatformadminCommunitiesModeratorassignmentsController } from "./controllers/communityPlatform/platformAdmin/communities/moderatorAssignments/CommunityplatformPlatformadminCommunitiesModeratorassignmentsController";
import { CommunityplatformCommunitymoderatorCommunitiesModeratorassignmentsController } from "./controllers/communityPlatform/communityModerator/communities/moderatorAssignments/CommunityplatformCommunitymoderatorCommunitiesModeratorassignmentsController";
import { CommunityplatformPlatformadminCommunitymoderatorsAssignmentsController } from "./controllers/communityPlatform/platformAdmin/communityModerators/assignments/CommunityplatformPlatformadminCommunitymoderatorsAssignmentsController";
import { CommunityplatformCommunitymoderatorCommunitiesBansController } from "./controllers/communityPlatform/communityModerator/communities/bans/CommunityplatformCommunitymoderatorCommunitiesBansController";
import { CommunityplatformPlatformadminCommunitiesBansController } from "./controllers/communityPlatform/platformAdmin/communities/bans/CommunityplatformPlatformadminCommunitiesBansController";
import { CommunityplatformCommunitymoderatorMemberusersCommunitybansController } from "./controllers/communityPlatform/communityModerator/memberUsers/communityBans/CommunityplatformCommunitymoderatorMemberusersCommunitybansController";
import { CommunityplatformPlatformadminMemberusersCommunitybansController } from "./controllers/communityPlatform/platformAdmin/memberUsers/communityBans/CommunityplatformPlatformadminMemberusersCommunitybansController";
import { CommunityplatformCommunitiesRulesController } from "./controllers/communityPlatform/communities/rules/CommunityplatformCommunitiesRulesController";
import { CommunityplatformCommunitymoderatorCommunitiesRulesController } from "./controllers/communityPlatform/communityModerator/communities/rules/CommunityplatformCommunitymoderatorCommunitiesRulesController";
import { CommunityplatformCommunitiesTagsController } from "./controllers/communityPlatform/communities/tags/CommunityplatformCommunitiesTagsController";
import { CommunityplatformCommunitymoderatorCommunitiesTagsController } from "./controllers/communityPlatform/communityModerator/communities/tags/CommunityplatformCommunitymoderatorCommunitiesTagsController";
import { CommunityplatformPlatformadminCommunitiesTagsController } from "./controllers/communityPlatform/platformAdmin/communities/tags/CommunityplatformPlatformadminCommunitiesTagsController";
import { CommunityplatformCommunitiesSearchController } from "./controllers/communityPlatform/communities/search/CommunityplatformCommunitiesSearchController";
import { CommunityplatformCommunitiesOverviewController } from "./controllers/communityPlatform/communities/overview/CommunityplatformCommunitiesOverviewController";
import { CommunityplatformCommunitiesGovernanceController } from "./controllers/communityPlatform/communities/governance/CommunityplatformCommunitiesGovernanceController";
import { CommunityplatformStatisticsCommunitiesMembershipController } from "./controllers/communityPlatform/statistics/communities/membership/CommunityplatformStatisticsCommunitiesMembershipController";
import { CommunityplatformStatisticsCommunitiesGrowthController } from "./controllers/communityPlatform/statistics/communities/growth/CommunityplatformStatisticsCommunitiesGrowthController";
import { CommunityplatformPlatformadminStatisticsCommunitiesBansController } from "./controllers/communityPlatform/platformAdmin/statistics/communities/bans/CommunityplatformPlatformadminStatisticsCommunitiesBansController";
import { CommunityplatformPlatformadminPosttypesController } from "./controllers/communityPlatform/platformAdmin/postTypes/CommunityplatformPlatformadminPosttypesController";
import { CommunityplatformPostsController } from "./controllers/communityPlatform/posts/CommunityplatformPostsController";
import { CommunityplatformMemberuserPostsController } from "./controllers/communityPlatform/memberUser/posts/CommunityplatformMemberuserPostsController";
import { CommunityplatformCommunitymoderatorPostsController } from "./controllers/communityPlatform/communityModerator/posts/CommunityplatformCommunitymoderatorPostsController";
import { CommunityplatformPlatformadminPostsController } from "./controllers/communityPlatform/platformAdmin/posts/CommunityplatformPlatformadminPostsController";
import { CommunityplatformMemberuserPostsStateController } from "./controllers/communityPlatform/memberUser/posts/state/CommunityplatformMemberuserPostsStateController";
import { CommunityplatformCommunitymoderatorPostsStateController } from "./controllers/communityPlatform/communityModerator/posts/state/CommunityplatformCommunitymoderatorPostsStateController";
import { CommunityplatformPlatformadminPostsStateController } from "./controllers/communityPlatform/platformAdmin/posts/state/CommunityplatformPlatformadminPostsStateController";
import { CommunityplatformPlatformadminPostsSnapshotsController } from "./controllers/communityPlatform/platformAdmin/posts/snapshots/CommunityplatformPlatformadminPostsSnapshotsController";
import { CommunityplatformPostsSnapshotsController } from "./controllers/communityPlatform/posts/snapshots/CommunityplatformPostsSnapshotsController";
import { CommunityplatformPostsCommentsController } from "./controllers/communityPlatform/posts/comments/CommunityplatformPostsCommentsController";
import { CommunityplatformMemberuserPostsCommentsController } from "./controllers/communityPlatform/memberUser/posts/comments/CommunityplatformMemberuserPostsCommentsController";
import { CommunityplatformCommunitymoderatorCommentsStateController } from "./controllers/communityPlatform/communityModerator/comments/state/CommunityplatformCommunitymoderatorCommentsStateController";
import { CommunityplatformMemberuserCommentsSnapshotsController } from "./controllers/communityPlatform/memberUser/comments/snapshots/CommunityplatformMemberuserCommentsSnapshotsController";
import { CommunityplatformPlatformadminPostvotesController } from "./controllers/communityPlatform/platformAdmin/postVotes/CommunityplatformPlatformadminPostvotesController";
import { CommunityplatformMemberuserPostvotesController } from "./controllers/communityPlatform/memberUser/postVotes/CommunityplatformMemberuserPostvotesController";
import { CommunityplatformCommunitymoderatorCommentvotesController } from "./controllers/communityPlatform/communityModerator/commentVotes/CommunityplatformCommunitymoderatorCommentvotesController";
import { CommunityplatformPlatformadminCommentvotesController } from "./controllers/communityPlatform/platformAdmin/commentVotes/CommunityplatformPlatformadminCommentvotesController";
import { CommunityplatformMemberuserCommentvotesController } from "./controllers/communityPlatform/memberUser/commentVotes/CommunityplatformMemberuserCommentvotesController";
import { CommunityplatformMemberusersPostkarmasController } from "./controllers/communityPlatform/memberUsers/postKarmas/CommunityplatformMemberusersPostkarmasController";
import { CommunityplatformMemberusersCommentkarmasController } from "./controllers/communityPlatform/memberUsers/commentKarmas/CommunityplatformMemberusersCommentkarmasController";
import { CommunityplatformMemberusersTotalkarmasController } from "./controllers/communityPlatform/memberUsers/totalKarmas/CommunityplatformMemberusersTotalkarmasController";
import { CommunityplatformMemberusersKarmasController } from "./controllers/communityPlatform/memberUsers/karmas/CommunityplatformMemberusersKarmasController";
import { CommunityplatformPlatformadminMemberusersVotingratelimitsController } from "./controllers/communityPlatform/platformAdmin/memberUsers/votingRateLimits/CommunityplatformPlatformadminMemberusersVotingratelimitsController";
import { CommunityplatformPlatformadminVotingkarmaStatisticsUserkarmadistributionController } from "./controllers/communityPlatform/platformAdmin/votingKarma/statistics/userKarmaDistribution/CommunityplatformPlatformadminVotingkarmaStatisticsUserkarmadistributionController";
import { CommunityplatformVotingkarmaStatisticsTopkarmausersController } from "./controllers/communityPlatform/votingKarma/statistics/topKarmaUsers/CommunityplatformVotingkarmaStatisticsTopkarmausersController";
import { CommunityplatformVotingkarmaStatisticsVotingactivitytrendsController } from "./controllers/communityPlatform/votingKarma/statistics/votingActivityTrends/CommunityplatformVotingkarmaStatisticsVotingactivitytrendsController";
import { CommunityplatformMemberuserSubscriptionsController } from "./controllers/communityPlatform/memberUser/subscriptions/CommunityplatformMemberuserSubscriptionsController";
import { CommunityplatformCommunitymoderatorSubscriptionsController } from "./controllers/communityPlatform/communityModerator/subscriptions/CommunityplatformCommunitymoderatorSubscriptionsController";
import { CommunityplatformPlatformadminSubscriptionsController } from "./controllers/communityPlatform/platformAdmin/subscriptions/CommunityplatformPlatformadminSubscriptionsController";
import { CommunityplatformMemberuserMemberusersSubscriptionsController } from "./controllers/communityPlatform/memberUser/memberUsers/subscriptions/CommunityplatformMemberuserMemberusersSubscriptionsController";
import { CommunityplatformPlatformadminCommunitiesSubscriptionsController } from "./controllers/communityPlatform/platformAdmin/communities/subscriptions/CommunityplatformPlatformadminCommunitiesSubscriptionsController";
import { CommunityplatformMemberuserCommunitiesSubscriptionsController } from "./controllers/communityPlatform/memberUser/communities/subscriptions/CommunityplatformMemberuserCommunitiesSubscriptionsController";
import { CommunityplatformMemberuserUserfeedpreferencesController } from "./controllers/communityPlatform/memberUser/userFeedPreferences/CommunityplatformMemberuserUserfeedpreferencesController";
import { CommunityplatformPlatformadminUserfeedpreferencesController } from "./controllers/communityPlatform/platformAdmin/userFeedPreferences/CommunityplatformPlatformadminUserfeedpreferencesController";
import { CommunityplatformMemberuserMemberusersFeedpreferencesController } from "./controllers/communityPlatform/memberUser/memberUsers/feedPreferences/CommunityplatformMemberuserMemberusersFeedpreferencesController";
import { CommunityplatformPlatformadminDefaultfeedsController } from "./controllers/communityPlatform/platformAdmin/defaultFeeds/CommunityplatformPlatformadminDefaultfeedsController";
import { CommunityplatformMemberuserFeedsHomeController } from "./controllers/communityPlatform/memberUser/feeds/home/CommunityplatformMemberuserFeedsHomeController";
import { CommunityplatformMemberuserFeedsCommunityController } from "./controllers/communityPlatform/memberUser/feeds/community/CommunityplatformMemberuserFeedsCommunityController";
import { CommunityplatformPlatformadminReportsController } from "./controllers/communityPlatform/platformAdmin/reports/CommunityplatformPlatformadminReportsController";
import { CommunityplatformMemberuserReportsController } from "./controllers/communityPlatform/memberUser/reports/CommunityplatformMemberuserReportsController";
import { CommunityplatformCommunitymoderatorReportsController } from "./controllers/communityPlatform/communityModerator/reports/CommunityplatformCommunitymoderatorReportsController";
import { CommunityplatformCommunitymoderatorReportsPostController } from "./controllers/communityPlatform/communityModerator/reports/post/CommunityplatformCommunitymoderatorReportsPostController";
import { CommunityplatformPlatformadminReportsPostController } from "./controllers/communityPlatform/platformAdmin/reports/post/CommunityplatformPlatformadminReportsPostController";
import { CommunityplatformPlatformadminReportsCommentController } from "./controllers/communityPlatform/platformAdmin/reports/comment/CommunityplatformPlatformadminReportsCommentController";
import { CommunityplatformCommunitymoderatorReportsCommentController } from "./controllers/communityPlatform/communityModerator/reports/comment/CommunityplatformCommunitymoderatorReportsCommentController";
import { CommunityplatformPlatformadminReportsCommunityController } from "./controllers/communityPlatform/platformAdmin/reports/community/CommunityplatformPlatformadminReportsCommunityController";
import { CommunityplatformCommunitymoderatorReportsCommunityController } from "./controllers/communityPlatform/communityModerator/reports/community/CommunityplatformCommunitymoderatorReportsCommunityController";
import { CommunityplatformCommunitymoderatorReportsUserController } from "./controllers/communityPlatform/communityModerator/reports/user/CommunityplatformCommunitymoderatorReportsUserController";
import { CommunityplatformPlatformadminReportsUserController } from "./controllers/communityPlatform/platformAdmin/reports/user/CommunityplatformPlatformadminReportsUserController";
import { CommunityplatformCommunitymoderatorReportsModerationactionsController } from "./controllers/communityPlatform/communityModerator/reports/moderationActions/CommunityplatformCommunitymoderatorReportsModerationactionsController";
import { CommunityplatformPlatformadminReportsModerationactionsController } from "./controllers/communityPlatform/platformAdmin/reports/moderationActions/CommunityplatformPlatformadminReportsModerationactionsController";
import { CommunityplatformCommunitymoderatorReportsUsersanctionsController } from "./controllers/communityPlatform/communityModerator/reports/userSanctions/CommunityplatformCommunitymoderatorReportsUsersanctionsController";
import { CommunityplatformPlatformadminReportsUsersanctionsController } from "./controllers/communityPlatform/platformAdmin/reports/userSanctions/CommunityplatformPlatformadminReportsUsersanctionsController";
import { CommunityplatformPlatformadminReportsAppealsController } from "./controllers/communityPlatform/platformAdmin/reports/appeals/CommunityplatformPlatformadminReportsAppealsController";
import { CommunityplatformMemberuserReportsAppealsController } from "./controllers/communityPlatform/memberUser/reports/appeals/CommunityplatformMemberuserReportsAppealsController";
import { CommunityplatformCommunitymoderatorReportsAppealsController } from "./controllers/communityPlatform/communityModerator/reports/appeals/CommunityplatformCommunitymoderatorReportsAppealsController";
import { CommunityplatformPlatformadminModerationactionsController } from "./controllers/communityPlatform/platformAdmin/moderationActions/CommunityplatformPlatformadminModerationactionsController";
import { CommunityplatformCommunitymoderatorModerationactionsController } from "./controllers/communityPlatform/communityModerator/moderationActions/CommunityplatformCommunitymoderatorModerationactionsController";
import { CommunityplatformPlatformadminUsersanctionsController } from "./controllers/communityPlatform/platformAdmin/userSanctions/CommunityplatformPlatformadminUsersanctionsController";
import { CommunityplatformPlatformadminAppealsController } from "./controllers/communityPlatform/platformAdmin/appeals/CommunityplatformPlatformadminAppealsController";
import { CommunityplatformCommunitymoderatorAppealsController } from "./controllers/communityPlatform/communityModerator/appeals/CommunityplatformCommunitymoderatorAppealsController";
import { CommunityplatformMemberuserAppealsController } from "./controllers/communityPlatform/memberUser/appeals/CommunityplatformMemberuserAppealsController";
import { CommunityplatformCommunitymoderatorModerationqueuesController } from "./controllers/communityPlatform/communityModerator/moderationQueues/CommunityplatformCommunitymoderatorModerationqueuesController";
import { CommunityplatformPlatformadminModerationqueuesController } from "./controllers/communityPlatform/platformAdmin/moderationQueues/CommunityplatformPlatformadminModerationqueuesController";
import { CommunityplatformPlatformadminStatisticsReportsController } from "./controllers/communityPlatform/platformAdmin/statistics/reports/CommunityplatformPlatformadminStatisticsReportsController";
import { CommunityplatformCommunitymoderatorStatisticsReportsController } from "./controllers/communityPlatform/communityModerator/statistics/reports/CommunityplatformCommunitymoderatorStatisticsReportsController";
import { CommunityplatformPlatformadminStatisticsModerationactionsController } from "./controllers/communityPlatform/platformAdmin/statistics/moderationActions/CommunityplatformPlatformadminStatisticsModerationactionsController";
import { CommunityplatformCommunitymoderatorStatisticsModerationactionsController } from "./controllers/communityPlatform/communityModerator/statistics/moderationActions/CommunityplatformCommunitymoderatorStatisticsModerationactionsController";
import { CommunityplatformPlatformadminStatisticsUsersanctionsController } from "./controllers/communityPlatform/platformAdmin/statistics/userSanctions/CommunityplatformPlatformadminStatisticsUsersanctionsController";
import { CommunityplatformPlatformadminStatisticsAppealsController } from "./controllers/communityPlatform/platformAdmin/statistics/appeals/CommunityplatformPlatformadminStatisticsAppealsController";
import { CommunityplatformCommunitymoderatorDashboardModerationoverviewController } from "./controllers/communityPlatform/communityModerator/dashboard/moderationOverview/CommunityplatformCommunitymoderatorDashboardModerationoverviewController";
import { CommunityplatformPlatformadminDashboardModerationoverviewController } from "./controllers/communityPlatform/platformAdmin/dashboard/moderationOverview/CommunityplatformPlatformadminDashboardModerationoverviewController";
import { CommunityplatformCommunitymoderatorSearchReportsController } from "./controllers/communityPlatform/communityModerator/search/reports/CommunityplatformCommunitymoderatorSearchReportsController";
import { CommunityplatformPlatformadminSearchReportsController } from "./controllers/communityPlatform/platformAdmin/search/reports/CommunityplatformPlatformadminSearchReportsController";
import { CommunityplatformPlatformadminAuditlogsController } from "./controllers/communityPlatform/platformAdmin/auditLogs/CommunityplatformPlatformadminAuditlogsController";
import { CommunityplatformPlatformadminErrorlogsController } from "./controllers/communityPlatform/platformAdmin/errorLogs/CommunityplatformPlatformadminErrorlogsController";
import { CommunityplatformPlatformadminModerationauditlogsController } from "./controllers/communityPlatform/platformAdmin/moderationAuditLogs/CommunityplatformPlatformadminModerationauditlogsController";
import { CommunityplatformPlatformadminAnalyticsAuditlogsController } from "./controllers/communityPlatform/platformAdmin/analytics/auditLogs/CommunityplatformPlatformadminAnalyticsAuditlogsController";
import { CommunityplatformPlatformadminAnalyticsErrorlogsController } from "./controllers/communityPlatform/platformAdmin/analytics/errorLogs/CommunityplatformPlatformadminAnalyticsErrorlogsController";
import { CommunityplatformPlatformadminAnalyticsModerationauditlogsController } from "./controllers/communityPlatform/platformAdmin/analytics/moderationAuditLogs/CommunityplatformPlatformadminAnalyticsModerationauditlogsController";

@Module({
  controllers: [
    AuthGuestuserController,
    AuthMemberuserController,
    AuthCommunitymoderatorController,
    AuthPlatformadminController,
    CommunityplatformPlatformadminPlatformsettingsController,
    CommunityplatformPlatformadminContentpolicycategoriesController,
    CommunityplatformContentpolicycategoriesController,
    CommunityplatformPlatformadminReportreasoncategoriesController,
    CommunityplatformCommunityrulecategoriesController,
    CommunityplatformPlatformadminCommunityrulecategoriesController,
    CommunityplatformPlatformadminSystemoverviewController,
    CommunityplatformPlatformadminGuestusersController,
    CommunityplatformPlatformadminGuestusersSessionsController,
    CommunityplatformPlatformadminMemberusersController,
    CommunityplatformMemberuserMemberusersController,
    CommunityplatformPlatformadminMemberusersSessionsController,
    CommunityplatformMemberuserMemberusersSessionsController,
    CommunityplatformPlatformadminCommunitymoderatorsController,
    CommunityplatformPlatformadminCommunitymoderatorsSessionsController,
    CommunityplatformPlatformadminPlatformadminsController,
    CommunityplatformPlatformadminPlatformadminsSessionsController,
    CommunityplatformPlatformadminAccountstatusesController,
    CommunityplatformPlatformadminUsersecurityeventsController,
    CommunityplatformGuestuserUsersecurityeventsGuestController,
    CommunityplatformMemberuserUsersecurityeventsMemberuserController,
    CommunityplatformPlatformadminUsersecurityeventsCommunitymoderatorController,
    CommunityplatformPlatformadminUsersecurityeventsPlatformadminController,
    CommunityplatformPlatformadminSecurityeventsAudittrailController,
    CommunityplatformCommunitiesController,
    CommunityplatformMemberuserCommunitiesController,
    CommunityplatformCommunitymoderatorCommunitiesController,
    CommunityplatformPlatformadminCommunitiesController,
    CommunityplatformMemberuserCommunityvisibilitylevelsController,
    CommunityplatformPlatformadminCommunityvisibilitylevelsController,
    CommunityplatformCommunitymoderatorCommunitiesMembershipsController,
    CommunityplatformPlatformadminCommunitiesMembershipsController,
    CommunityplatformMemberuserCommunitiesMembershipsController,
    CommunityplatformMemberuserMemberusersCommunitymembershipsController,
    CommunityplatformPlatformadminMemberusersCommunitymembershipsController,
    CommunityplatformCommunitymoderatorCommunitiesMembershiprequestsController,
    CommunityplatformPlatformadminCommunitiesMembershiprequestsController,
    CommunityplatformMemberuserCommunitiesMembershiprequestsController,
    CommunityplatformMemberuserMemberusersCommunitymembershiprequestsController,
    CommunityplatformPlatformadminMemberusersCommunitymembershiprequestsController,
    CommunityplatformPlatformadminCommunitiesModeratorassignmentsController,
    CommunityplatformCommunitymoderatorCommunitiesModeratorassignmentsController,
    CommunityplatformPlatformadminCommunitymoderatorsAssignmentsController,
    CommunityplatformCommunitymoderatorCommunitiesBansController,
    CommunityplatformPlatformadminCommunitiesBansController,
    CommunityplatformCommunitymoderatorMemberusersCommunitybansController,
    CommunityplatformPlatformadminMemberusersCommunitybansController,
    CommunityplatformCommunitiesRulesController,
    CommunityplatformCommunitymoderatorCommunitiesRulesController,
    CommunityplatformCommunitiesTagsController,
    CommunityplatformCommunitymoderatorCommunitiesTagsController,
    CommunityplatformPlatformadminCommunitiesTagsController,
    CommunityplatformCommunitiesSearchController,
    CommunityplatformCommunitiesOverviewController,
    CommunityplatformCommunitiesGovernanceController,
    CommunityplatformStatisticsCommunitiesMembershipController,
    CommunityplatformStatisticsCommunitiesGrowthController,
    CommunityplatformPlatformadminStatisticsCommunitiesBansController,
    CommunityplatformPlatformadminPosttypesController,
    CommunityplatformPostsController,
    CommunityplatformMemberuserPostsController,
    CommunityplatformCommunitymoderatorPostsController,
    CommunityplatformPlatformadminPostsController,
    CommunityplatformMemberuserPostsStateController,
    CommunityplatformCommunitymoderatorPostsStateController,
    CommunityplatformPlatformadminPostsStateController,
    CommunityplatformPlatformadminPostsSnapshotsController,
    CommunityplatformPostsSnapshotsController,
    CommunityplatformPostsCommentsController,
    CommunityplatformMemberuserPostsCommentsController,
    CommunityplatformCommunitymoderatorCommentsStateController,
    CommunityplatformMemberuserCommentsSnapshotsController,
    CommunityplatformPlatformadminPostvotesController,
    CommunityplatformMemberuserPostvotesController,
    CommunityplatformCommunitymoderatorCommentvotesController,
    CommunityplatformPlatformadminCommentvotesController,
    CommunityplatformMemberuserCommentvotesController,
    CommunityplatformMemberusersPostkarmasController,
    CommunityplatformMemberusersCommentkarmasController,
    CommunityplatformMemberusersTotalkarmasController,
    CommunityplatformMemberusersKarmasController,
    CommunityplatformPlatformadminMemberusersVotingratelimitsController,
    CommunityplatformPlatformadminVotingkarmaStatisticsUserkarmadistributionController,
    CommunityplatformVotingkarmaStatisticsTopkarmausersController,
    CommunityplatformVotingkarmaStatisticsVotingactivitytrendsController,
    CommunityplatformMemberuserSubscriptionsController,
    CommunityplatformCommunitymoderatorSubscriptionsController,
    CommunityplatformPlatformadminSubscriptionsController,
    CommunityplatformMemberuserMemberusersSubscriptionsController,
    CommunityplatformPlatformadminCommunitiesSubscriptionsController,
    CommunityplatformMemberuserCommunitiesSubscriptionsController,
    CommunityplatformMemberuserUserfeedpreferencesController,
    CommunityplatformPlatformadminUserfeedpreferencesController,
    CommunityplatformMemberuserMemberusersFeedpreferencesController,
    CommunityplatformPlatformadminDefaultfeedsController,
    CommunityplatformMemberuserFeedsHomeController,
    CommunityplatformMemberuserFeedsCommunityController,
    CommunityplatformPlatformadminReportsController,
    CommunityplatformMemberuserReportsController,
    CommunityplatformCommunitymoderatorReportsController,
    CommunityplatformCommunitymoderatorReportsPostController,
    CommunityplatformPlatformadminReportsPostController,
    CommunityplatformPlatformadminReportsCommentController,
    CommunityplatformCommunitymoderatorReportsCommentController,
    CommunityplatformPlatformadminReportsCommunityController,
    CommunityplatformCommunitymoderatorReportsCommunityController,
    CommunityplatformCommunitymoderatorReportsUserController,
    CommunityplatformPlatformadminReportsUserController,
    CommunityplatformCommunitymoderatorReportsModerationactionsController,
    CommunityplatformPlatformadminReportsModerationactionsController,
    CommunityplatformCommunitymoderatorReportsUsersanctionsController,
    CommunityplatformPlatformadminReportsUsersanctionsController,
    CommunityplatformPlatformadminReportsAppealsController,
    CommunityplatformMemberuserReportsAppealsController,
    CommunityplatformCommunitymoderatorReportsAppealsController,
    CommunityplatformPlatformadminModerationactionsController,
    CommunityplatformCommunitymoderatorModerationactionsController,
    CommunityplatformPlatformadminUsersanctionsController,
    CommunityplatformPlatformadminAppealsController,
    CommunityplatformCommunitymoderatorAppealsController,
    CommunityplatformMemberuserAppealsController,
    CommunityplatformCommunitymoderatorModerationqueuesController,
    CommunityplatformPlatformadminModerationqueuesController,
    CommunityplatformPlatformadminStatisticsReportsController,
    CommunityplatformCommunitymoderatorStatisticsReportsController,
    CommunityplatformPlatformadminStatisticsModerationactionsController,
    CommunityplatformCommunitymoderatorStatisticsModerationactionsController,
    CommunityplatformPlatformadminStatisticsUsersanctionsController,
    CommunityplatformPlatformadminStatisticsAppealsController,
    CommunityplatformCommunitymoderatorDashboardModerationoverviewController,
    CommunityplatformPlatformadminDashboardModerationoverviewController,
    CommunityplatformCommunitymoderatorSearchReportsController,
    CommunityplatformPlatformadminSearchReportsController,
    CommunityplatformPlatformadminAuditlogsController,
    CommunityplatformPlatformadminErrorlogsController,
    CommunityplatformPlatformadminModerationauditlogsController,
    CommunityplatformPlatformadminAnalyticsAuditlogsController,
    CommunityplatformPlatformadminAnalyticsErrorlogsController,
    CommunityplatformPlatformadminAnalyticsModerationauditlogsController,
  ],
})
export class MyModule {}
