import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallProductReview } from "../../../structures/IPageIShoppingMallProductReview";
import { IShoppingMallProductReview } from "../../../structures/IShoppingMallProductReview";

/**
 * Create a new product review associated with a purchased product variant and order item to ensure authenticity and purchase verification.
 *
 * This API allows customers to submit a star rating (1-5) and optional textual feedback for a product variant they have purchased.
 *
 * Each review is linked to the customer account, the specific order item, and the product variant reviewed. This ensures that only customers who have bought the product can submit reviews.
 *
 * Security considerations ensure only authenticated customers can create reviews. Business rules and validation maintain rating ranges and ensure valid foreign keys to other entities.
 *
 * This operation works with the shopping_mall_product_reviews table, which tracks reviews with timestamps and soft delete for handling review updates and removals.
 *
 * Related operations include GET /products/{productId}/reviews for listing reviews of a product.
 *
 * Errors will occur if foreign keys are invalid or if rating is outside the accepted range.
 *
 * The response returns the full created review entity including timestamps.
 *
 * @param props.connection
 * @param props.body Information needed to create a product review including customer reference, order item, product variant, rating (1-5 stars), and optional textual feedback.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Validate the request body for required fields: customer ID, order item ID, product variant ID, rating (1-5), and optional review body.
 * Check that the customer has purchased the specified order item and variant.
 * Insert a new record into shopping_mall_product_reviews with creation and update timestamps.
 * Handle soft delete columns properly.
 * Return the created review object.
 * Handle errors for foreign key violations or invalid rating.
 * Ensure only authenticated customers can access this endpoint.
 * @path /shoppingMall/productReviews
 * @accessor api.functional.shoppingMall.productReviews.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Information needed to create a product review including customer reference, order item, product variant, rating (1-5 stars), and optional textual feedback.
     */
    body: IShoppingMallProductReview.ICreate;
  };
  export type Body = IShoppingMallProductReview.ICreate;
  export type Response = IShoppingMallProductReview;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/productReviews",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/productReviews";
  export const random = (): IShoppingMallProductReview =>
    typia.random<IShoppingMallProductReview>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a paginated, filtered, and sorted list of product reviews submitted by customers. This operation supports flexible search criteria including filtering by customer ID, order item ID, product variant ID, rating ranges, and review creation date ranges. It enables users to browse and moderate customer feedback on purchased products.
 *
 * This operation reads data from the `shopping_mall_product_reviews` table, which stores star ratings (1 to 5) and optional textual comments linked to customers, order items, and product variants. The soft delete `deleted_at` field is used to exclude logically deleted reviews from the results.
 *
 * Access to this operation requires authenticated membership as a customer or an administrator role with appropriate permissions to view product reviews. The operation returns a paginated list of review summaries optimized for fast UI loading and response times.
 *
 * Related operations include:
 * - GET /products/{productId}/reviews to fetch reviews for a particular product
 * - POST /products/{productId}/reviews to create a new review
 * - PUT /products/{productId}/reviews/{reviewId} to update an existing review
 * - DELETE /products/{productId}/reviews/{reviewId} to delete a review
 *
 * Errors such as invalid filter criteria or pagination parameters return appropriate HTTP status codes with descriptive messages.
 *
 * This operation excludes soft-deleted reviews by filtering out entries with a non-null `deleted_at` timestamp.
 *
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for product reviews
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification This operation queries the shopping_mall_product_reviews table with flexible filtering on fields like customer ID, order item ID, product variant ID, rating range, and date range for creation timestamp.
 *
 * The query excludes soft-deleted records by filtering where deleted_at is null.
 *
 * Supports cursor-based pagination with search criteria provided through IShoppingMallProductReview.IRequest type.
 *
 * Joins with customer, order item, and product variant tables as needed to gather summary info.
 *
 * Returns paginated results with IPageIShoppingMallProductReview.ISummary type for response.
 *
 * Handle errors for invalid filter values and return HTTP 400 with details.
 *
 * Ensure secure access limiting to authenticated customers and administrators with permission to view reviews.
 * @path /shoppingMall/productReviews
 * @accessor api.functional.shoppingMall.productReviews.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for product reviews
     */
    body: IShoppingMallProductReview.IRequest;
  };
  export type Body = IShoppingMallProductReview.IRequest;
  export type Response = IPageIShoppingMallProductReview.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/productReviews",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/productReviews";
  export const random = (): IPageIShoppingMallProductReview.ISummary =>
    typia.random<IPageIShoppingMallProductReview.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a product review by its unique ID.
 *
 * This API operation allows clients to fetch a specific review written by a customer for a product variant within an order item, identified by the UUID productReviewId. It includes the rating, optional textual body, and timestamps for creation and update.
 *
 * The review is linked to the customer who authored it, the order item purchased, and the specific product variant reviewed, ensuring data integrity and purchase verification.
 *
 * Authorized users including customers and administrators can access this endpoint to view review details for transparency and dispute resolution.
 *
 * This is a read-only operation with no request body. It conforms to RESTful conventions for retrieving a resource by its primary key identifier.
 *
 * Related operations:
 * - POST /productReviews to create a new review
 * - PUT /productReviews/{productReviewId} to update an existing review
 * - DELETE /productReviews/{productReviewId} to delete a review
 *
 * This operation assumes proper authentication and authorization middleware enforce access control.
 *
 * @param props.connection
 * @param props.productReviewId Unique identifier of the product review (UUID format)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification The service layer should query the shopping_mall_product_reviews table filtering by the UUID productReviewId. It should join related customer, order item, and product variant tables to confirm data linkage if needed.
 *
 * The response should map all fields including id, shopping_mall_customer_id, shopping_mall_order_item_id, shopping_mall_product_variant_id, rating, body, created_at, updated_at, and deleted_at.
 *
 * The query should ensure that soft deleted reviews (deleted_at not null) are still retrievable for authorized users.
 *
 * No request body is required.
 *
 * Implement standard error handling for not found resources and insufficient permissions.
 * @path /shoppingMall/productReviews/:productReviewId
 * @accessor api.functional.shoppingMall.productReviews.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the product review (UUID format)
     */
    productReviewId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallProductReview;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/productReviews/:productReviewId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/productReviews/${encodeURIComponent(props.productReviewId ?? "null")}`;
  export const random = (): IShoppingMallProductReview =>
    typia.random<IShoppingMallProductReview>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productReviewId")(() =>
        typia.assert(props.productReviewId),
      );
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * This endpoint updates an existing product review identified by the path parameter `productReviewId` which must be a valid UUID.
 *
 * The operation allows an authenticated customer to update the rating, which is an integer from 1 to 5 stars, and an optional textual body of a product review. This review is linked to the customer, order item, and product variant to ensure the customer has purchased the item.
 *
 * Only the `rating` and `body` fields may be modified; other fields including IDs and timestamps (`created_at`, `updated_at`, `deleted_at`) are controlled by the system and cannot be changed by the client.
 *
 * Security enforcement ensures only the customer who created the review can perform this update, maintaining data integrity and preventing unauthorized modifications.
 *
 * Validation rules require the rating to be between 1 and 5 inclusive, and the review body is optional but constrained in length.
 *
 * This operation is related to creating new reviews, retrieving reviews for display, and deleting reviews in the system.
 *
 * @param props.connection
 * @param props.productReviewId Unique identifier of the product review to update. Must be a valid UUID.
 * @param props.body Updated rating and text body of the product review
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Validate that the productReviewId path parameter exists and is a valid UUID.
 * Retrieve the existing product review by ID.
 * Authorize the current customer to ensure ownership of the review.
 * Validate the request body rating (1-5) and optional body text length.
 * Update the product review record in the database with the new rating and body.
 * Update the updated_at timestamp automatically.
 * Return the full updated product review record.
 * Do not allow updates to IDs, created_at, deleted_at.
 * Handle errors and return appropriate HTTP status codes.
 * @path /shoppingMall/productReviews/:productReviewId
 * @accessor api.functional.shoppingMall.productReviews.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Unique identifier of the product review to update. Must be a valid UUID.
     */
    productReviewId: string & tags.Format<"uuid">;

    /**
     * Updated rating and text body of the product review
     */
    body: IShoppingMallProductReview.IUpdate;
  };
  export type Body = IShoppingMallProductReview.IUpdate;
  export type Response = IShoppingMallProductReview;

  export const METADATA = {
    method: "PUT",
    path: "/shoppingMall/productReviews/:productReviewId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/productReviews/${encodeURIComponent(props.productReviewId ?? "null")}`;
  export const random = (): IShoppingMallProductReview =>
    typia.random<IShoppingMallProductReview>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productReviewId")(() =>
        typia.assert(props.productReviewId),
      );
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Permanently delete a product review identified by the unique productReviewId from the shopping_mall_product_reviews table.
 *
 * This operation performs a hard delete, fully removing the review record from the system with no soft deletion or marking.
 *
 * Authorization is restricted to administrators or the customer who owns the review.
 *
 * No request body is required.
 *
 * No content is returned in the response upon successful deletion (HTTP 204 No Content).
 *
 * Related operations:
 * - GET /products/{productId}/reviews to list product reviews
 * - POST /products/{productId}/reviews to create a new review
 * - PUT /products/{productId}/reviews/{reviewId} to update an existing review
 *
 * This operation does not generate a snapshot as it permanently removes the data.
 *
 * @param props.connection
 * @param props.productReviewId The UUID of the product review to delete.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Implement database deletion query on shopping_mall_product_reviews where id = productReviewId.
 * Verify authorization: only admins or the customer who wrote the review can delete.
 * Enforce cascading to related entities if applicable (e.g., review votes).
 * Return HTTP 204 No Content on successful deletion.
 * Handle errors for not found or unauthorized appropriately.
 * @path /shoppingMall/productReviews/:productReviewId
 * @accessor api.functional.shoppingMall.productReviews.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * The UUID of the product review to delete.
     */
    productReviewId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/shoppingMall/productReviews/:productReviewId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/productReviews/${encodeURIComponent(props.productReviewId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productReviewId")(() =>
        typia.assert(props.productReviewId),
      );
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
