import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IHrmEmployeeInvitation } from "../../../../../api/structures/IHrmEmployeeInvitation";
import { GuestAuth } from "../../../../../decorators/GuestAuth";
import { GuestPayload } from "../../../../../decorators/payload/GuestPayload";
import { patchHrmGuestInvitationsInvitationIdAccept } from "../../../../../providers/patchHrmGuestInvitationsInvitationIdAccept";

@Controller("/hrm/guest/invitations/:invitationId/accept")
export class HrmGuestInvitationsController {
  /**
   * Accepts a pending employee invitation and creates the employee record in the target organization.
   *
   * This operation allows users to accept invitations sent to their email address, joining the inviting organization as an employee with the specified role. When accepted, the invitation status changes to 'accepted' and the member_id is populated to link the invitation to the user's account.
   *
   * The system validates the invitation token for security, ensures the invitation is still pending and not expired, and verifies the invited email matches the authenticated user. Upon successful acceptance, an employee record is created linking the user to the organization with the assigned role.
   *
   * If the invitation has already been accepted, expired, or cancelled, the operation is rejected. The invitation is consumed upon acceptance and cannot be reused.
   *
   * @param connection
   * @param invitationId UUID identifier of the invitation to accept (global scope).
   * @param body Invitation acceptance request containing the verification token sent to the invited email address.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor guest
     * @x-autobe-specification 1. Extract invitationId from path parameter and
     *   validate UUID format. 2. Fetch invitation from hrm_employee_invitations
     *   table where id = invitationId AND deleted_at IS NULL. 3. Validate
     *   invitation exists; return 404 if not found. 4. Check invitation.status
     *   equals 'pending'; return 400 if status is 'accepted', 'expired', or
     *   'cancelled'. 5. Validate invitation.expires_at is not in the past;
     *   return 400 if expired. 6. Verify request body token matches
     *   invitation.token; return 401 if mismatch. 7. Get current authenticated
     *   member from session/JWT. 8. Verify member.email matches
     *   invitation.email; return 403 if mismatch. 9. Begin database
     *   transaction. 10. Update invitation: SET status = 'accepted', member_id
     *   = member.id, updated_at = NOW() WHERE id = invitationId. 11. Check if
     *   employee record already exists for this organization_id and user_id; if
     *   not, create employee record with role_id, department_id (null),
     *   position (null), employment_type (from role or default), status =
     *   'active'. 12. Commit transaction. 13. Return 200 with updated
     *   invitation object including populated member_id. 14. Handle unique
     *   constraint violations on [organization_id, email, status] with 409
     *   Conflict. 15. Log activity for invitation acceptance.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async accept(
    @GuestAuth()
    guest: GuestPayload,
    @TypedParam("invitationId")
    invitationId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IHrmEmployeeInvitation.IAccept,
  ): Promise<IHrmEmployeeInvitation> {
    try {
      return await patchHrmGuestInvitationsInvitationIdAccept({
        guest,
        invitationId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
