import { tags } from "typia";

/**
 * Lightweight summary of a rule category from
 * `community_platform_community_rule_categories`.
 *
 * This type is used to enrich community rules with higher‑level categorization,
 * making it easier for members to understand which type of policy a rule
 * belongs to (for example, behavior vs. content guidelines). It omits internal
 * lifecycle and soft‑delete details that are not needed on governance pages.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformCommunityRuleCategorySummary = {
  /**
   * Primary key of the rule category from
   * `community_platform_community_rule_categories.id`.
   *
   * This value is referenced by community rules that choose to classify
   * themselves under this category.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Machine‑friendly code from
   * `community_platform_community_rule_categories.code`.
   *
   * This stable identifier is used by backend logic and tooling when
   * referring to the category in configuration, analytics, or automated
   * checks.
   */
  code: string;

  /**
   * Human‑readable category name from
   * `community_platform_community_rule_categories.name`.
   *
   * Displayed in configuration UIs and governance views to describe the
   * general theme of rules in this category.
   */
  name: string;

  /**
   * Detailed category description from
   * `community_platform_community_rule_categories.description`.
   *
   * Explains what types of rules belong to this category and may provide
   * examples that help moderators choose appropriate categories when
   * authoring rules.
   */
  description: string;

  /**
   * Display ordering value from
   * `community_platform_community_rule_categories.sort_order`.
   *
   * Determines how categories are sorted when presented in configuration or
   * selection UIs, with lower values appearing earlier.
   */
  sortOrder: number & tags.Type<"int32">;

  /**
   * Active flag from
   * `community_platform_community_rule_categories.is_active`.
   *
   * When true, the category is available for new rules and standard UIs. When
   * false, it is kept only for historical records and should typically be
   * hidden from authoring flows.
   */
  isActive: boolean;
};
