import { tags } from "typia";

import { IHrmPlatformActivityLog } from "./IHrmPlatformActivityLog";

/**
 * A field-level change record within an activity log entry. This represents a single attribute modification that occurred during a business action, such as an employee status change, contract edit, project update, or task status transition. Each change record captures the field name, previous value, new value, data type, and timestamp for comprehensive audit trail tracking and compliance purposes.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IHrmPlatformActivityLogChange = {
  /**
   * Unique identifier for this field-level change record.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.id. Primary key, UUID format. Immutable identifier for this change record.
   */
  id: string & tags.Format<"uuid">;

  /**
   * UUID of the parent activity log entry that contains this field-level change.
   *
   * @x-autobe-database-schema-property hrm_platform_activity_log_id
   * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.hrm_platform_activity_log_id. Foreign key reference to the parent activity log entry. Used with field_name in composite unique constraint.
   */
  hrm_platform_activity_log_id: string & tags.Format<"uuid">;

  /**
   * Name of the field that was modified in the target entity.
   *
   * @x-autobe-database-schema-property field_name
   * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.field_name. String field identifying which attribute was modified (e.g., 'status', 'title', 'assigned_to', 'end_date'). Part of composite unique constraint with hrm_platform_activity_log_id.
   */
  field_name: string;

  /**
   * Previous value of the field before the change. Null if the field was newly created.
   *
   * @x-autobe-database-schema-property old_value
   * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.old_value. Nullable string field containing the value before the change. Null for newly created fields that had no prior value. Stored as string regardless of original field type for audit trail consistency.
   */
  old_value: string | null;

  /**
   * New value of the field after the change. Null if the field value was deleted or removed.
   *
   * @x-autobe-database-schema-property new_value
   * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.new_value. Nullable string field containing the value after the change. Null for deleted fields or when a value is removed. Stored as string regardless of original field type for audit trail consistency.
   */
  new_value: string | null;

  /**
   * Data type of the changed field (e.g., string, int, datetime, boolean, uuid).
   *
   * @x-autobe-database-schema-property field_type
   * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.field_type. String field indicating the data type of the changed field (e.g., 'string', 'int', 'datetime', 'boolean', 'uuid'). Provides context for interpreting the old and new values.
   */
  field_type: string;

  /**
   * Timestamp when this field-level change was recorded.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.created_at. DateTime field with timestamptz database type. Immutable timestamp recording when this change was made. Used for audit trail chronological ordering.
   */
  created_at: string & tags.Format<"date-time">;
};
export namespace IHrmPlatformActivityLogChange {
  /**
   * Lightweight summary of a field-level change within an activity log entry. Each change record captures a single attribute modification, including the field name, previous value, new value, and data type. Used in paginated lists to show detailed audit trail information for compliance and investigation purposes.
   */
  export type ISummary = {
    /**
     * Unique identifier for this field-level change record.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.id. Primary key, UUID format, immutable.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Name of the field that was changed in the target entity.
     *
     * @x-autobe-database-schema-property field_name
     * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.field_name. String field identifying which attribute was modified (e.g., 'status', 'title', 'assigned_to').
     */
    field_name: string;

    /**
     * Previous value of the field before the change. Null for newly created fields.
     *
     * @x-autobe-database-schema-property old_value
     * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.old_value. Nullable string containing the previous value before the change. Null for newly created fields.
     */
    old_value: string | null;

    /**
     * New value of the field after the change. Null for deleted fields.
     *
     * @x-autobe-database-schema-property new_value
     * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.new_value. Nullable string containing the new value after the change. Null for deleted fields.
     */
    new_value: string | null;

    /**
     * Data type of the changed field for context when interpreting old and new values.
     *
     * @x-autobe-database-schema-property field_type
     * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.field_type. String indicating the data type of the changed field (e.g., 'string', 'int', 'datetime', 'boolean', 'uuid').
     */
    field_type: string;

    /**
     * Timestamp when this field change was recorded.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from hrm_platform_activity_log_changes.created_at. DateTime field with timestamptz, immutable for audit trail integrity.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Parent activity log entry that contains this field-level change.
     *
     * @x-autobe-database-schema-property activityLog
     * @x-autobe-specification Relation mapping from hrm_platform_activity_log_changes.activityLog. Join via hrm_platform_activity_log_id FK to hrm_platform_activity_logs.id. Returns IHrmPlatformActivityLog.ISummary with parent activity log details.
     */
    activityLog: IHrmPlatformActivityLog.ISummary;
  };

  /**
   * Request parameters for filtering and paginating activity log change records. Use these parameters to search for specific field modifications within an activity log entry. All fields are optional - omit to retrieve all changes for the activity log. Supports filtering by field name, field type, and value patterns, with configurable pagination for large result sets.
   */
  export type IRequest = {
    /**
     * Filter by the name of the field that was modified. Supports exact or partial matching to find changes to specific attributes like 'status', 'title', or 'end_date'.
     *
     * @x-autobe-specification Filter parameter that maps to hrm_platform_activity_log_changes.field_name column in database. Used for exact or partial match on the name of the field that changed (e.g., 'status', 'title', 'assigned_to'). Applied in WHERE clause with LIKE or = operator to filter activity log changes by the specific attribute that was modified.
     */
    field_name?: string | undefined;

    /**
     * Filter by the data type of the changed field. Exact match on types like 'string', 'int', 'datetime', 'boolean', or 'uuid' to narrow results by data category.
     *
     * @x-autobe-specification Filter parameter that maps to hrm_platform_activity_log_changes.field_type column in database. Used for exact match on the data type of the changed field (e.g., 'string', 'int', 'datetime', 'boolean', 'uuid'). Applied in WHERE clause with = operator to narrow results by data category.
     */
    field_type?: string | undefined;

    /**
     * Filter by the previous value of the field before the change. Supports pattern matching to find changes from specific values. May be null for newly created fields that had no prior value.
     *
     * @x-autobe-specification Filter parameter that maps to hrm_platform_activity_log_changes.old_value column in database (nullable). Used for pattern matching on the previous value before the change. Nullable field - may be null for newly created fields. Applied in WHERE clause with LIKE operator or IS NULL check to filter changes from specific values.
     */
    old_value?: string | undefined;

    /**
     * Filter by the new value of the field after the change. Supports pattern matching to find changes to specific values. May be null for deleted fields or when a value is removed.
     *
     * @x-autobe-specification Filter parameter that maps to hrm_platform_activity_log_changes.new_value column in database (nullable). Used for pattern matching on the new value after the change. Nullable field - may be null for deleted fields or removed values. Applied in WHERE clause with LIKE operator or IS NULL check to filter changes to specific values.
     */
    new_value?: string | undefined;

    /**
     * Page number for pagination (1-indexed). Specifies which page of results to retrieve. Defaults to page 1 if not provided. Each page contains up to 'limit' number of records.
     *
     * @x-autobe-specification Computed pagination parameter, not mapped to database column. 1-indexed page number for result set pagination. Default value is 1. Used to calculate OFFSET in SQL: OFFSET = (page - 1) * limit. Validates minimum value of 1.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Maximum number of records per page. Controls how many activity log changes are returned in each page. Defaults to 20 records per page, with a maximum of 100 records allowed.
     *
     * @x-autobe-specification Computed pagination parameter, not mapped to database column. Page size controlling maximum records per page. Default value is 20, maximum is 100. Used as LIMIT clause in SQL query. Validates range 1-100.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };
}
