import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IRedditPlatformChannel } from "../../../structures/IRedditPlatformChannel";
import { IPageIRedditPlatformChannel } from "../../../structures/IPageIRedditPlatformChannel";

/**
 * Retrieve a filtered and paginated list of platform-wide content channels from
 * the system. This operation queries the reddit_platform_channels database
 * model as defined in the schema, specifically using the 'name', 'description',
 * 'visibilityStatus', and 'creationDate' fields for display purposes and
 * filtering parameters.
 *
 * The operation supports comprehensive filtering based on channel name
 * (matching name field), creation date (using creationDate field), and
 * visibility status (using visibilityStatus field). Full pagination is
 * implemented with request parameters for page size, page number, and sorting
 * criteria. Channels can be sorted by creation date in ascending or descending
 * order, or by name alphabetically.
 *
 * Security considerations include that this endpoint is publicly accessible
 * without authentication, aligning with the user requirements for visible
 * community channels. The endpoint is designed for frontend applications to
 * populate channel listings and navigation menus without user authentication
 * requirements. Integration requires matching the Channel schema's structure,
 * particularly the 'name' and 'description' fields for display purposes.
 *
 * @param props.connection
 * @param props.body Filter and pagination parameters for channel search
 * @path /redditPlatform/channels
 * @accessor api.functional.redditPlatform.channels.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Filter and pagination parameters for channel search */
    body: IRedditPlatformChannel.IRequest;
  };
  export type Body = IRedditPlatformChannel.IRequest;
  export type Response = IPageIRedditPlatformChannel.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditPlatform/channels",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditPlatform/channels";
  export const random = (): IPageIRedditPlatformChannel.ISummary =>
    typia.random<IPageIRedditPlatformChannel.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a single community channel's public configuration and branding
 * details. This operation fetches the complete channel definition from the
 * Reddit Platform database schema, including channel name, description,
 * branding elements, and visibility configuration.
 *
 * The channel identification is based on the unique channelCode which is
 * globally unique across all content channels. The operation does not require
 * authentication as channel information is publicly accessible by all users of
 * the platform.
 *
 * Response includes full channel configuration suitable for displaying in
 * public channel directories and community navigation interfaces. Care has been
 * taken to exclude internal system fields like timestamps or hidden
 * configuration parameters.
 *
 * Security considerations include validation that the channelCode corresponds
 * to a live and active channel, with appropriate 404 response for non-existent
 * channels.
 *
 * @param props.connection
 * @param props.channelCode Unique business identifier code of the target
 *   channel (global scope)
 * @path /redditPlatform/channels/:channelCode
 * @accessor api.functional.redditPlatform.channels.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique business identifier code of the target channel (global scope) */
    channelCode: string;
  };
  export type Response = IRedditPlatformChannel;

  export const METADATA = {
    method: "GET",
    path: "/redditPlatform/channels/:channelCode",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditPlatform/channels/${encodeURIComponent(props.channelCode ?? "null")}`;
  export const random = (): IRedditPlatformChannel =>
    typia.random<IRedditPlatformChannel>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("channelCode")(() => typia.assert(props.channelCode));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
