import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallPlatformAdminJoin } from "../../../structures/IShoppingMallPlatformAdminJoin";
import { IShoppingMallPlatformAdmin } from "../../../structures/IShoppingMallPlatformAdmin";
import { IShoppingMallPlatformAdminLogin } from "../../../structures/IShoppingMallPlatformAdminLogin";
import { IShoppingMallPlatformAdminRefresh } from "../../../structures/IShoppingMallPlatformAdminRefresh";

/**
 * Register a new platform administrator in shopping_mall_platformadmin and
 * create bound auth credentials, returning
 * IShoppingMallPlatformAdmin.IAuthorized tokens.
 *
 * This operation registers a new platform administrator by inserting identity
 * and credential records into the `shopping_mall_platformadmin` and
 * `shopping_mall_auth_credentials` tables, then returns an authorized session
 * representation for immediate use.
 *
 * At the identity level, it creates a `shopping_mall_platformadmin` row
 * capturing administrator details such as `email`, `name`, `status`, and audit
 * timestamps `created_at` and `updated_at`. The `deleted_at` column remains
 * null for active admins but allows future lifecycle transitions that preserve
 * references for audit logs and configuration change histories, as emphasized
 * in the schema description. The `email` column is constrained by a unique
 * index so the implementation must check for existing admins with the same
 * email before insertion.
 *
 * For authentication, the handler provisions a `shopping_mall_auth_credentials`
 * record with `actor_type` set to a value like `platformAdmin`, an `email`
 * matching the admin account, and a `password_hash` derived from the submitted
 * password using a strong one-way function. It also sets the credentials
 * `status` (for example `active`), initializes `created_at` and `updated_at`,
 * and leaves `last_login_at` null until the first login event. The uniqueness
 * constraint on `(actor_type, email)` must be honored, and violations should be
 * surfaced as validation errors rather than generic failures.
 *
 * The credentials are linked to the admin identity using
 * `shopping_mall_auth_credentials_of_platformadmins`, which stores
 * `shopping_mall_auth_credentials_id`, `shopping_mall_platformadmin_id`, and
 * `created_at`. This establishes a strict one-to-one mapping between a
 * credentials row and a specific platform admin using the unique index on
 * `shopping_mall_auth_credentials_id`. The join logic must ensure both sides
 * exist and are consistent before completing the transaction.
 *
 * On successful registration, the system issues JWT access and refresh tokens
 * and returns an `IShoppingMallPlatformAdmin.IAuthorized` response that
 * encapsulates the admin profile, credential status, and tokens. It should also
 * create an entry in `shopping_mall_platformadmin_sessions` capturing the
 * `shopping_mall_platformadmin_id` along with `ip`, `href`, `referrer`,
 * `created_at`, and a null `expired_at` to represent the newly established
 * session, aligning with the standardized session schema used for admins.
 * Additionally, an optional `shopping_mall_auth_logs` entry can be recorded
 * with `event_type` such as `"login_success"`, `actor_type` =
 * `"platformAdmin"`, `actor_id` referencing the admin id, and `success` = true
 * for forensic analysis.
 *
 * Error handling must account for invalid input (e.g., weak passwords),
 * collisions on the unique `email` indexes, and any failures when writing to
 * the identity, credentials, or session tables. In any failure case, partial
 * changes should be rolled back so that there is no
 * `shopping_mall_platformadmin` without credentials or vice versa. This join
 * endpoint complements the corresponding login and refresh operations and is
 * intended to be used sparingly by bootstrap flows or existing admins
 * provisioning new operators rather than by the general public.
 *
 * @param props.connection
 * @param props.body Registration info for a new platform administrator,
 *   including profile and credential fields required to create
 *   shopping_mall_platformadmin and shopping_mall_auth_credentials records.
 * @setHeader token.access Authorization
 *
 * @path /auth/platformAdmin/join
 * @accessor api.functional.auth.platformAdmin.join
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function join(
  connection: IConnection,
  props: join.Props,
): Promise<join.Response> {
  const output: join.Response =
    true === connection.simulate
      ? join.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...join.METADATA,
            path: join.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace join {
  export type Props = {
    /**
     * Registration info for a new platform administrator, including profile
     * and credential fields required to create shopping_mall_platformadmin
     * and shopping_mall_auth_credentials records.
     */
    body: IShoppingMallPlatformAdminJoin.IRequest;
  };
  export type Body = IShoppingMallPlatformAdminJoin.IRequest;
  export type Response = IShoppingMallPlatformAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/platformAdmin/join",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/platformAdmin/join";
  export const random = (): IShoppingMallPlatformAdmin.IAuthorized =>
    typia.random<IShoppingMallPlatformAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: join.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: join.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Authenticate a platform administrator using shopping_mall_auth_credentials
 * and return an IShoppingMallPlatformAdmin.IAuthorized JWT session.
 *
 * This operation authenticates platform administrators by validating their
 * email and password against normalized credential records while updating audit
 * and session tables.
 *
 * The login handler first locates a `shopping_mall_auth_credentials` record by
 * matching the supplied `email` and `actor_type` value associated with platform
 * administrators. Using the schema’s unique index on `(actor_type, email)`, it
 * ensures at most one credentials row is considered, and checks its `status`
 * field to confirm that logins are allowed (for example, `active` versus
 * `locked` or `compromised`). The incoming plaintext password is hashed and
 * compared to `password_hash` to determine whether authentication can proceed.
 *
 * If the credentials are valid, the system updates `last_login_at` and
 * `updated_at` on `shopping_mall_auth_credentials` to reflect the new
 * successful login. It then follows the one-to-one link defined in
 * `shopping_mall_auth_credentials_of_platformadmins` to the corresponding
 * `shopping_mall_platformadmin` identity row, ensuring the admin’s `status`
 * indicates that account lifecycle permits access. The
 * `shopping_mall_platformadmin` columns `email`, `name`, `status`,
 * `created_at`, and `updated_at` are used to assemble the identity portion of
 * the response.
 *
 * A new authentication session for this admin is recorded in
 * `shopping_mall_platformadmin_sessions` with the
 * `shopping_mall_platformadmin_id` foreign key and context fields `ip`, `href`,
 * `referrer`, `created_at`, and null `expired_at`, as per the standardized
 * session schema. This allows future admin actions to be correlated to a
 * specific session row. In parallel, the operation logs a
 * `shopping_mall_auth_logs` event with `event_type` set to `"login_success"`,
 * `actor_type` to `"platformAdmin"`, `actor_id` as the admin id, `actor_email`
 * as the login email, and `success` set to true, capturing `ip`, `user_agent`,
 * and optional `correlation_id` or `metadata_json` for further analysis.
 *
 * If authentication fails due to incorrect password, missing credentials,
 * disallowed credential `status`, or incompatible
 * `shopping_mall_platformadmin.status`, the system must avoid creating sessions
 * or updating `last_login_at`. Instead, it writes a `shopping_mall_auth_logs`
 * record with `event_type` `"login_failure"`, `actor_type` `"platformAdmin"`,
 * `actor_email` set to the attempted email, `success` false, and a
 * `failure_reason` such as `"invalid_credentials"` or `"account_suspended"`.
 * The HTTP response should be a generic unauthorized error that does not leak
 * whether the account exists. On successful login, the operation issues fresh
 * JWT access and refresh tokens encoded in the
 * `IShoppingMallPlatformAdmin.IAuthorized` response body.
 *
 * @param props.connection
 * @param props.body Login credentials and context (email, password, and client
 *   metadata) for a platform administrator attempting to sign in.
 * @setHeader token.access Authorization
 *
 * @path /auth/platformAdmin/login
 * @accessor api.functional.auth.platformAdmin.login
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function login(
  connection: IConnection,
  props: login.Props,
): Promise<login.Response> {
  const output: login.Response =
    true === connection.simulate
      ? login.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...login.METADATA,
            path: login.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace login {
  export type Props = {
    /**
     * Login credentials and context (email, password, and client metadata)
     * for a platform administrator attempting to sign in.
     */
    body: IShoppingMallPlatformAdminLogin.IRequest;
  };
  export type Body = IShoppingMallPlatformAdminLogin.IRequest;
  export type Response = IShoppingMallPlatformAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/platformAdmin/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/platformAdmin/login";
  export const random = (): IShoppingMallPlatformAdmin.IAuthorized =>
    typia.random<IShoppingMallPlatformAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: login.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: login.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Refresh JWT tokens for a platform administrator using a valid refresh token
 * and return an updated IShoppingMallPlatformAdmin.IAuthorized session.
 *
 * This operation renews JWT tokens for a platform administrator using a valid
 * refresh token, ensuring that credential and risk state are still acceptable
 * while persisting audit information.
 *
 * The handler begins by validating the provided refresh token against the
 * server-side token store, confirming that it has not expired or been revoked.
 * Once the token is trusted, the implementation determines which
 * `shopping_mall_auth_credentials` row it is associated with and loads that
 * record. Using `actor_type` from the credentials schema, the flow ensures that
 * the credential indeed belongs to a `platformAdmin` and checks the `status`
 * column to verify that continued authentication is allowed.
 *
 * Next, the operation follows the one-to-one association from
 * `shopping_mall_auth_credentials_of_platformadmins` to the corresponding
 * `shopping_mall_platformadmin` identity. It inspects that admin’s `status` and
 * timestamps (`created_at`, `updated_at`, and `deleted_at` being null) to
 * ensure the account remains usable. Additional security policies can consult
 * `shopping_mall_risk_flags` entries linked via
 * `shopping_mall_auth_credentials_id`, looking at `risk_level`,
 * `reason_category`, `active`, and `cleared_at` to decide whether a high-risk
 * or active flag should block token refresh or require additional
 * verification.
 *
 * For ongoing session tracking, the refresh operation either reuses an existing
 * `shopping_mall_platformadmin_sessions` row representing the admin’s current
 * session or creates a new one, populating `shopping_mall_platformadmin_id`,
 * `ip`, `href`, `referrer`, `created_at`, and a null `expired_at` for active
 * sessions. This keeps administrator actions traceable to a concrete session
 * for future analysis and moderation. The handler then issues new JWT access
 * (and possibly refresh) tokens encoded in an
 * `IShoppingMallPlatformAdmin.IAuthorized` response that reflects the admin’s
 * identity and current credential state.
 *
 * Regardless of success or failure, an immutable `shopping_mall_auth_logs`
 * event is written. On success, an entry with `event_type` `"token_refresh"`,
 * `actor_type` `"platformAdmin"`, `actor_id` for the admin, `actor_email` from
 * the credentials, `success` true, and relevant `ip`, `user_agent`, and
 * `correlation_id` is created. On failure, the log uses `success` false and
 * sets `failure_reason` to values such as `"invalid_token"`, `"token_expired"`,
 * or `"blocked_by_risk_flag"`, while never exposing sensitive details in the
 * client-facing error. This refresh endpoint completes the core admin
 * authentication lifecycle alongside the join and login endpoints.
 *
 * @param props.connection
 * @param props.body Refresh token and client context required to renew a
 *   platform administrator's JWT session.
 * @setHeader token.access Authorization
 *
 * @path /auth/platformAdmin/refresh
 * @accessor api.functional.auth.platformAdmin.refresh
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function refresh(
  connection: IConnection,
  props: refresh.Props,
): Promise<refresh.Response> {
  const output: refresh.Response =
    true === connection.simulate
      ? refresh.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...refresh.METADATA,
            path: refresh.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace refresh {
  export type Props = {
    /**
     * Refresh token and client context required to renew a platform
     * administrator's JWT session.
     */
    body: IShoppingMallPlatformAdminRefresh.IRequest;
  };
  export type Body = IShoppingMallPlatformAdminRefresh.IRequest;
  export type Response = IShoppingMallPlatformAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/auth/platformAdmin/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/platformAdmin/refresh";
  export const random = (): IShoppingMallPlatformAdmin.IAuthorized =>
    typia.random<IShoppingMallPlatformAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: refresh.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: refresh.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
