import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IHrmTimeTrackingActivityRecord } from "../../../../../api/structures/IHrmTimeTrackingActivityRecord";
import { IPageIHrmTimeTrackingActivityRecord } from "../../../../../api/structures/IPageIHrmTimeTrackingActivityRecord";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { getHrmTimeTrackingMemberHrmTimeTrackingActivityRecordsActivityRecordId } from "../../../../../providers/getHrmTimeTrackingMemberHrmTimeTrackingActivityRecordsActivityRecordId";
import { patchHrmTimeTrackingMemberHrmTimeTrackingActivityRecords } from "../../../../../providers/patchHrmTimeTrackingMemberHrmTimeTrackingActivityRecords";

@Controller("/hrmTimeTracking/member/hrmTimeTracking/activity-records")
export class HrmtimetrackingMemberHrmtimetrackingActivity_recordsController {
  /**
   * Retrieve a paginated list of activity log entries for the currently selected organization.
   *
   * Each activity record represents a significant business action that occurred within the organization, including the time of the action, the user who performed it, the action type, the target entity, and supporting details. The log is intended for organizational review and audit visibility, so the returned records must remain anchored to the active organization context and must never include entries from any other organization.
   *
   * Access to this endpoint is limited to users who are allowed to view organization-level operational history. The response is designed for browsing and filtering historical business events, not for editing or deleting them. Consumers should treat the returned entries as immutable historical facts that help the organization understand what happened and when.
   *
   * The endpoint supports filtered and paginated retrieval so clients can narrow results by action type, actor, target entity, and date range. The system must apply organization isolation before evaluating any other filters, and any request that attempts to reach outside the current organization must be rejected. For detailed inspection of a single activity entry, a separate detail endpoint should be used if present; this operation is intentionally focused on list browsing.
   *
   * The underlying hrm_time_tracking_activity_records data model stores append-only entries for significant actions. This API should surface the fields needed for timeline rendering and operational review, while keeping the payload compact enough for fast log browsing. The activity log remains available as historical context for related workflows such as employee changes, contract updates, project actions, task status changes, and other notable organizational events.
   *
   * @param connection
   * @param body Search, filter, pagination, and sorting criteria for organization activity records.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Implement an organization-scoped activity log search on hrm_time_tracking_activity_records.
   *
   * Resolve the active organization from the authenticated request context first. Reject the request if no organization is selected or if the caller lacks organization-management visibility for activity records. All queries must be constrained to the active organization before any other filtering is applied.
   *
   * Support paginated filtering by action type, actor user, target entity type, target entity identifier, and date range. Sort newest-first by the activity timestamp by default, with optional stable secondary sorting by primary key if needed for consistent pagination. Because this is a historical log, do not allow mutation operations through this endpoint.
   *
   * Query the activity records table directly, selecting only the fields needed for summary browsing. If the schema includes a foreign key or actor reference, join or resolve it only for display purposes; do not expose any cross-organization data. Apply validation to ensure any supplied user or target entity filters belong to the current organization context when those fields are organization-scoped.
   *
   * Return a paginated page object containing summary items with timestamp, actor display reference, action type, target entity metadata, and details summary. Preserve append-only semantics: records are never edited through this endpoint. Handle empty result sets gracefully with an empty page and pagination metadata.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedBody()
    body: IHrmTimeTrackingActivityRecord.IRequest,
  ): Promise<IPageIHrmTimeTrackingActivityRecord.ISummary> {
    try {
      return await patchHrmTimeTrackingMemberHrmTimeTrackingActivityRecords({
        member,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a single organization activity record by its identifier.
   *
   * This operation returns one timestamped business action from the currently selected organization. Each activity record represents a significant operational event in the organization’s history and includes when the event occurred, who performed it, the action type, the affected target entity, and the structured details needed to understand the event in context.
   *
   * The record is read within the active organization boundary only. A member who belongs to multiple organizations must still access the log through the currently selected organization context, and the API must reject any attempt to read a record that belongs to another organization. This preserves the organization-specific history model described by the activity log requirements and ensures that records are interpreted only inside the organization that owns them.
   *
   * Access to this endpoint is intended for members with organization management visibility, because the activity log is used as a reviewable history of important business actions such as employee changes, contract updates, project lifecycle changes, task status changes, timesheet decisions, and role assignments. If the requested identifier does not exist in the current organization context, the service should respond as not found rather than exposing whether the record exists elsewhere.
   *
   * @param connection
   * @param activityRecordId The activity record identifier.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Load the activity record by primary identifier and the authenticated member's selected organization context.
   *
   * Implementation steps:
   * 1. Resolve the current organization from the authenticated request context.
   * 2. Query hrm_time_tracking_activity_records by activity_record_id and organization_id together so that cross-organization access is impossible.
   * 3. Join or separately resolve the actor reference if the response schema exposes actor identity details, but only within the same organization scope and without leaking unrelated membership data.
   * 4. Return a single record when found; otherwise return 404.
   *
   * Validation and access rules:
   * - Require organization management permission to access this endpoint.
   * - Reject requests from members who do not have visibility to the organization activity log.
   * - Never return records from a different organization, even if the same user belongs to both organizations.
   * - Do not accept any query or body parameters; the path identifier and selected organization context are sufficient.
   *
   * Data handling:
   * - Treat the activity record as historical fact data; do not mutate it here.
   * - Preserve the timestamp, acting user reference, action type, target entity metadata, and detail payload exactly as stored.
   * - If the schema stores the target entity as structured fields rather than a nested object, map those fields directly in the response model.
   *
   * Error behavior:
   * - 404 when no record exists in the current organization for the supplied identifier.
   * - 403 when the caller lacks organization management access.
   * - 401 when authentication is missing or invalid.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":activityRecordId")
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("activityRecordId")
    activityRecordId: string & tags.Format<"uuid">,
  ): Promise<IHrmTimeTrackingActivityRecord> {
    try {
      return await getHrmTimeTrackingMemberHrmTimeTrackingActivityRecordsActivityRecordId(
        {
          member,
          activityRecordId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
