import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { postShoppingMallCustomerShoppingMallCarts } from "../../../../providers/postShoppingMallCustomerShoppingMallCarts";
import { CustomerAuth } from "../../../../decorators/CustomerAuth";
import { CustomerPayload } from "../../../../decorators/payload/CustomerPayload";
import { patchShoppingMallCustomerShoppingMallCarts } from "../../../../providers/patchShoppingMallCustomerShoppingMallCarts";
import { getShoppingMallCustomerShoppingMallCartsShoppingMallCartId } from "../../../../providers/getShoppingMallCustomerShoppingMallCartsShoppingMallCartId";
import { putShoppingMallCustomerShoppingMallCartsShoppingMallCartId } from "../../../../providers/putShoppingMallCustomerShoppingMallCartsShoppingMallCartId";
import { deleteShoppingMallCustomerShoppingMallCartsShoppingMallCartId } from "../../../../providers/deleteShoppingMallCustomerShoppingMallCartsShoppingMallCartId";

import { IShoppingMallCart } from "../../../../api/structures/IShoppingMallCart";
import { IPageIShoppingMallCart } from "../../../../api/structures/IPageIShoppingMallCart";

@Controller("/shoppingMall/customer/shoppingMallCarts")
export class ShoppingmallCustomerShoppingmallcartsController {
  /**
   * Create a new shopping mall cart.
   *
   * This operation allows authenticated customers to create a new shopping mall
   * cart, which represents a persistent collection of selected product SKUs
   * intended for purchase.
   *
   * Each cart must be associated with a customer through a valid customer ID.
   * Optionally, it can be linked to a specific customer session for enhanced
   * tracking across sessions.
   *
   * The system records creation and update timestamps automatically. The cart
   * can also be soft deleted by setting the 'deleted_at' timestamp, but this is
   * managed internally and not part of this operation.
   *
   * Security: Only authenticated users with the 'customer' actor can create
   * carts. The operation enforces ownership checks and validates referenced
   * customer and session IDs.
   *
   * Related APIs: Update cart (PUT /shoppingMallCarts/{shoppingMallCartId}) for
   * modifying existing carts.
   *
   * @param connection
   * @param body Shopping mall cart creation payload
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedBody()
    body: IShoppingMallCart.ICreate,
  ): Promise<IShoppingMallCart> {
    try {
      return await postShoppingMallCustomerShoppingMallCarts({
        customer,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * List and search shopping mall carts.
   *
   * Retrieve a paginated list of shopping mall carts with advanced filtering,
   * sorting, and pagination capabilities.
   *
   * This operation allows clients to query shopping carts belonging to
   * registered customers or guest sessions. Filters can be applied based on
   * customer IDs, session IDs, creation dates, and soft deletion status.
   * Pagination parameters control page size and offsets ensuring efficient data
   * retrieval for user interfaces and reporting tools.
   *
   * Security considerations include ensuring that only authorized users can
   * access cart data. Soft-deleted carts are either excluded or included based
   * on request parameters.
   *
   * This operation interacts directly with the shopping_mall_carts table in the
   * Prisma schema, which records cart metadata including ownership, timestamps,
   * and deletion flags. It provides comprehensive data to facilitate cart
   * management in an e-commerce environment.
   *
   * @param connection
   * @param body Search criteria, pagination, and filter parameters for shopping
   *   mall carts
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedBody()
    body: IShoppingMallCart.IRequest,
  ): Promise<IPageIShoppingMallCart.ISummary> {
    try {
      return await patchShoppingMallCustomerShoppingMallCarts({
        customer,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Get details of a shopping mall cart by ID.
   *
   * Retrieve detailed information of a specific shopping mall cart by its
   * unique ID.
   *
   * This operation allows authorized users to fetch all pertinent data related
   * to a single shopping cart, including customer association, session linkage,
   * creation and update timestamps, and soft deletion status.
   *
   * The operation ensures that the cart exists and is accessible based on the
   * provided identifier, returning comprehensive cart metadata to facilitate
   * checkout workflows, cart editing, or analytics.
   *
   * Security restrictions apply to ensure only the owning user or authorized
   * parties can perform this query.
   *
   * This API directly reflects the structure and constraints of the
   * shopping_mall_carts Prisma table.
   *
   * @param connection
   * @param shoppingMallCartId Unique identifier of the target shopping mall
   *   cart
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":shoppingMallCartId")
  public async at(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("shoppingMallCartId")
    shoppingMallCartId: string & tags.Format<"uuid">,
  ): Promise<IShoppingMallCart> {
    try {
      return await getShoppingMallCustomerShoppingMallCartsShoppingMallCartId({
        customer,
        shoppingMallCartId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update an existing shopping mall cart.
   *
   * This operation allows authenticated customers to update details of an
   * existing shopping mall cart by specifying its unique identifier.
   *
   * Fields such as 'updated_at' can be modified to reflect the latest changes.
   * Soft deletion can be indicated by setting 'deleted_at' timestamp, which is
   * nullable.
   *
   * The operation validates that the cart belongs to the requesting user and
   * ensures referential integrity with the associated customer and session.
   *
   * Security considerations include strict ownership validation and
   * authorization checks for the 'customer' actor.
   *
   * Related APIs: Create cart (POST /shoppingMallCarts) for creating new carts.
   *
   * @param connection
   * @param shoppingMallCartId Unique identifier of the target shopping mall
   *   cart (UUID)
   * @param body Shopping mall cart update payload
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":shoppingMallCartId")
  public async update(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("shoppingMallCartId")
    shoppingMallCartId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IShoppingMallCart.IUpdate,
  ): Promise<IShoppingMallCart> {
    try {
      return await putShoppingMallCustomerShoppingMallCartsShoppingMallCartId({
        customer,
        shoppingMallCartId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete a shopping mall cart by ID.
   *
   * Permanently deletes the specified shopping mall cart and all related cart
   * items from the system. This action removes the cart record from the
   * database and cannot be undone.
   *
   * Security: Only the authenticated customer who owns the cart or authorized
   * admin users should perform this operation. Proper authorization validation
   * is required.
   *
   * The operation directly affects the shopping_mall_carts table, enforcing
   * referential integrity and cascade deletion of dependent cart items.
   *
   * No request body is needed for this operation.
   *
   * Related operations: Retrieve cart items (PATCH
   * /shoppingMallCarts/{shoppingMallCartId}/shoppingMallCartItems), Create cart
   * (POST /shoppingMallCarts), Update cart (PUT
   * /shoppingMallCarts/{shoppingMallCartId}).
   *
   * @param connection
   * @param shoppingMallCartId Unique identifier of the target shopping mall
   *   cart
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":shoppingMallCartId")
  public async erase(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("shoppingMallCartId")
    shoppingMallCartId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteShoppingMallCustomerShoppingMallCartsShoppingMallCartId(
        {
          customer,
          shoppingMallCartId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
