import { tags } from "typia";

import { IShoppingMallCustomer } from "./IShoppingMallCustomer";
import { IShoppingMallOrderAddress } from "./IShoppingMallOrderAddress";
import { IShoppingMallOrderItem } from "./IShoppingMallOrderItem";

/**
 * Complete order entity containing all order details including customer information, shipping address snapshot, and order items with their individual statuses. Orders are preserved indefinitely for legal compliance and audit purposes. Each order item maintains complete snapshot data captured at purchase time for historical accuracy.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallOrder = {
  id: string & tags.Format<"uuid">;
  order_number: string;
  total_price: number;
  status: string;
  customer: IShoppingMallCustomer.ISummary;
  address: IShoppingMallOrderAddress;
  orderItems: IShoppingMallOrderItem[];
  created_at: string & tags.Format<"date-time">;
  updated_at: string & tags.Format<"date-time">;
};
export namespace IShoppingMallOrder {
  /**
   * Request parameters for searching and filtering customer order history.
   *
   * This DTO provides comprehensive filtering capabilities for customers to search their order history. Multiple filters can be combined to narrow down results. All fields are optional; when not provided, no filtering is applied for that criterion.
   *
   * **Filter Types:**
   * - Status filtering: Exact match on order status
   * - Order number search: Partial, case-insensitive matching
   * - Date range: Filter orders within a specific time period
   * - Price range: Filter orders within a price bracket
   * - Pagination: Control page number and items per page
   *
   * **Authentication Note:**
   * Customer ID is automatically inferred from authentication token - do not include in request.
   */
  export type IRequest = {
    /**
     * Filter by order status. Exact match on the derived order status.
     */
    status?: string | undefined;

    /**
     * Search by order number. Partial matching (case-insensitive) allows customers to find orders by partial order number.
     */
    order_number?: string | undefined;

    /**
     * Filter orders created on or after this datetime. Used with created_at_to for date range filtering.
     */
    created_at_from?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter orders created on or before this datetime. Used with created_at_from for date range filtering.
     */
    created_at_to?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter orders with total price greater than or equal to this value.
     */
    total_price_min?: (number & tags.Minimum<0>) | undefined;

    /**
     * Filter orders with total price less than or equal to this value.
     */
    total_price_max?: (number & tags.Minimum<0>) | undefined;

    /**
     * Page number for pagination. Default: 1
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of items per page. Default: 20, Maximum: 100
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };

  /**
   * Lightweight order summary for list views and embedded references. Contains essential order identification (id, order number), financial summary (total price), current status, customer information, and creation timestamp. Used in paginated customer order history listings and as embedded reference in related entities requiring order context.
   */
  export type ISummary = {
    /**
     * Unique identifier for the order, formatted as UUID.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from shopping_mall_orders.id. UUID format, auto-generated on order creation.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Human-readable order reference number for customer tracking and support inquiries.
     *
     * @x-autobe-database-schema-property order_number
     * @x-autobe-specification Direct mapping from shopping_mall_orders.order_number. Human-readable order reference like 'ORD-2024-001234', auto-generated on order creation.
     */
    orderNumber: string;

    /**
     * Total order amount calculated as the sum of all order item prices.
     *
     * @x-autobe-database-schema-property total_price
     * @x-autobe-specification Direct mapping from shopping_mall_orders.total_price. Decimal/Double precision for monetary values. Sum of all order item prices (quantity × unit price).
     */
    totalPrice: number;

    /**
     * Current order status derived from all order item statuses.
     *
     * @x-autobe-database-schema-property status
     * @x-autobe-specification Direct mapping from shopping_mall_orders.status. Derived from constituent order item statuses: 'paid' (all items paid), 'shipped' (any item shipped), 'delivered' (all items delivered), 'cancelled' (all items cancelled), 'refunded' (all items refunded), 'partially_completed' (mixed statuses).
     */
    status: string;

    /**
     * Customer who placed this order, containing essential profile information.
     *
     * @x-autobe-database-schema-property customer
     * @x-autobe-specification Relation mapping from shopping_mall_orders.customer (belongs-to). Fetched via JOIN on shopping_mall_customer_id, transformed to IShoppingMallCustomer.ISummary format with id, email, displayName, phoneNumber, isDeleted, createdAt, updatedAt.
     */
    customer: IShoppingMallCustomer.ISummary;

    /**
     * Timestamp when the order was placed after successful payment.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from shopping_mall_orders.created_at. ISO 8601 timestamp with timezone, captured when payment succeeds and order is created.
     */
    createdAt: string & tags.Format<"date-time">;
  };

  /**
   * Request body for administrator force-refund operation. Contains the mandatory explanation for the administrative refund action. Administrators must provide a clear, descriptive reason for the force-refund which will be recorded in the audit trail for compliance, dispute resolution, and accountability purposes. This operation bypasses normal refund restrictions including seller approval and the 7-day refund window.
   */
  export type IForceRefund = {
    /**
     * Mandatory explanation for the force-refund action. This reason is recorded in the administrative audit log for compliance and dispute resolution purposes. Must be a clear, descriptive justification for bypassing normal refund restrictions.
     *
     * @x-autobe-specification Validated as non-empty string (minLength: 1). Stored in shopping_mall_admin_audit_logs.details JSON field as {reason: <value>, order_number: <order_number>}. The reason provides accountability and audit trail for administrative override of normal refund processes.
     */
    reason: string & tags.MinLength<1>;
  };

  /**
   * Request body for administrator force-cancel operation. Contains the mandatory explanation for the administrative cancellation action. Administrators must provide a clear, descriptive reason for the force-cancel which will be recorded in the audit trail for compliance, dispute resolution, and accountability purposes. This operation bypasses normal cancellation restrictions including seller approval and the paid-only status requirement.
   */
  export type IForceCancel = {
    /**
     * The administrative reason for force-cancelling the order. Must be a clear, descriptive explanation that will be permanently recorded in the audit log for compliance purposes.
     *
     * @x-autobe-specification Validated at API layer for non-empty string (minLength: 1). After validation, stored in shopping_mall_admin_audit_logs.details as a JSON object field alongside order_number, cancelled_item_count, and total_refund_amount. The reason becomes part of the permanent audit trail for the force-cancellation action, enabling compliance tracking and dispute resolution.
     */
    reason: string & tags.MinLength<1>;
  };

  /**
   * Request body for placing a new order after successful payment processing. Contains the shipping address reference that will be captured as an immutable snapshot at order placement time, ensuring shipping information remains unchanged even if the customer later modifies or deletes addresses from their address book.
   */
  export type ICreate = {
    /**
     * Unique identifier of the shipping address to use for this order. Must reference an address owned by the authenticated customer. The address will be captured as an immutable snapshot at order placement, preserving the shipping information even if the customer later modifies or deletes the original address.
     *
     * @x-autobe-specification References a customer's address from their address book. Validated to ensure it belongs to the authenticated customer and is not soft-deleted. Used during order creation to create an immutable snapshot in shopping_mall_order_addresses table with recipient_name, phone, street, city, state, postal_code, and country copied from the source address.
     */
    address_id: string & tags.Format<"uuid">;
  };
}
