import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIRedditLikeCommunitySubscription } from "../../../../structures/IPageIRedditLikeCommunitySubscription";
import { IRedditLikeCommunitySubscription } from "../../../../structures/IRedditLikeCommunitySubscription";

/**
 * Subscribe to a community to receive its posts in your home feed and gain posting access.
 *
 * This operation creates a subscription record linking the authenticated member to the specified community. Subscription is required before creating posts in a community. The system prevents duplicate subscriptions, so subscribing to an already-followed community will be rejected.
 *
 * **Business Rules**:
 * - Member must be authenticated to subscribe
 * - Community must exist and not be deleted
 * - Duplicate subscriptions are prevented (one subscription per member-community pair)
 * - Banned users cannot subscribe to the community they are banned from
 * - Subscription enables posting access and adds community posts to the member's home feed
 *
 * **Error Conditions**:
 * - 400: Duplicate subscription (already subscribed)
 * - 403: User is banned from the community
 * - 404: Community does not exist
 *
 * **Related Operations**:
 * - Unsubscribe: DELETE /subscriptions/{subscriptionId}
 * - View Subscriptions: PATCH /subscriptions (list owned subscriptions)
 *
 * @param props.connection
 * @param props.body Subscription request containing the community ID to subscribe to.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification 1. Authenticate the member from the request session/token.
 * 2. Validate the request body contains a valid communityId.
 * 3. Query reddit_like_communities table to verify the community exists and deleted_at is NULL.
 * 4. Check reddit_like_community_bans table to ensure the member is not banned from this community.
 * 5. Query reddit_like_community_subscriptions table with the unique constraint [reddit_like_member_id, reddit_like_community_id] to check for existing subscription.
 * 6. If duplicate subscription exists, return 400 error with appropriate message.
 * 7. If banned, return 403 error.
 * 8. If community not found, return 404 error.
 * 9. Create a new subscription record in reddit_like_community_subscriptions with:
 *    - reddit_like_member_id: authenticated member's ID
 *    - reddit_like_community_id: from request body
 *    - created_at and updated_at: current timestamp
 *    - deleted_at: NULL
 * 10. Return the created subscription entity.
 *
 * **Validation Rules**:
 * - communityId: required, valid UUID format
 * - Member authentication: required via session token
 *
 * **Edge Cases**:
 * - Handle race conditions for duplicate subscription attempts using database unique constraint
 * - Cascade delete: if community is deleted, subscriptions are automatically removed
 * @path /redditLike/member/subscriptions
 * @accessor api.functional.redditLike.member.subscriptions.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Subscription request containing the community ID to subscribe to.
     */
    body: IRedditLikeCommunitySubscription.ICreate;
  };
  export type Body = IRedditLikeCommunitySubscription.ICreate;
  export type Response = IRedditLikeCommunitySubscription;

  export const METADATA = {
    method: "POST",
    path: "/redditLike/member/subscriptions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditLike/member/subscriptions";
  export const random = (): IRedditLikeCommunitySubscription =>
    typia.random<IRedditLikeCommunitySubscription>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a paginated list of community subscriptions for the authenticated member.
 *
 * This endpoint returns subscription records that track which communities a member has subscribed to. Subscriptions determine which communities appear in the member's home feed and grant posting permissions within those communities.
 *
 * **Features**
 *
 * - Filter subscriptions by community to find specific subscriptions
 * - Paginate through results using cursor or offset-based pagination
 * - Sort by subscription date (newest or oldest first)
 * - Includes embedded community summaries for quick reference
 *
 * **Security**
 *
 * Only the authenticated member can view their own subscriptions. Member ID is derived from authentication context, not from request parameters.
 *
 * **Relationships**
 *
 * Each subscription links a member to a community. The response includes community summaries to display community name and icon without additional API calls.
 *
 * @param props.connection
 * @param props.body Search criteria including optional community filter, pagination parameters (limit, offset), and sorting options.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query reddit_like_community_subscriptions table for the authenticated member.
 *
 * Implementation steps:
 * 1. Extract member ID from authentication context (JWT token)
 * 2. Query subscriptions where reddit_like_member_id matches authenticated member
 * 3. Apply optional community_id filter if provided in request
 * 4. Apply pagination: limit and offset from request body
 * 5. Sort by created_at (descending by default for newest subscriptions first)
 * 6. Join with reddit_like_communities to fetch community summaries (name, icon)
 * 7. Exclude soft-deleted subscriptions (deleted_at IS NULL)
 * 8. Return paginated response with IPageIRedditLikeCommunitySubscription.ISummary
 *
 * Validation rules:
 * - Reject if limit exceeds maximum page size (e.g., 100)
 * - Reject if offset is negative
 * - Reject if community_id is invalid UUID format
 *
 * Error handling:
 * - Return 401 if authentication missing or invalid
 * - Return 400 for invalid pagination parameters or UUID format
 * @path /redditLike/member/subscriptions
 * @accessor api.functional.redditLike.member.subscriptions.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria including optional community filter, pagination parameters (limit, offset), and sorting options.
     */
    body: IRedditLikeCommunitySubscription.IRequest;
  };
  export type Body = IRedditLikeCommunitySubscription.IRequest;
  export type Response = IPageIRedditLikeCommunitySubscription.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditLike/member/subscriptions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditLike/member/subscriptions";
  export const random = (): IPageIRedditLikeCommunitySubscription.ISummary =>
    typia.random<IPageIRedditLikeCommunitySubscription.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Unsubscribe from a community by deleting the subscription record.
 *
 * This operation removes a member's subscription to a specific community, preventing the community's posts from appearing in the member's home feed. The subscription record is soft-deleted by setting the deleted_at timestamp, preserving the record for audit purposes while marking it as inactive.
 *
 * **Business Rules**
 * - The authenticated member must own the subscription record
 * - The subscription must exist and be currently active (deleted_at is null)
 * - Unsubscribing does not delete posts the member created in the community
 * - The member can resubscribe to the community later by creating a new subscription
 *
 * **Error Conditions**
 * - Subscription not found: Returns 404 if no subscription exists with the given ID
 * - Subscription already deleted: Returns 400 if the subscription has already been unsubscribed (deleted_at is set)
 * - Unauthorized: Returns 403 if the authenticated member does not own the subscription
 *
 * @param props.connection
 * @param props.subscriptionId Unique identifier of the subscription record to unsubscribe from (UUID format).
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Implement soft delete for subscription unsubscription:
 *
 * 1. Extract subscriptionId from path parameter (UUID format)
 * 2. Authenticate the requesting member and obtain their member ID
 * 3. Query reddit_like_community_subscriptions table where:
 *    - id = subscriptionId
 *    - reddit_like_member_id = authenticated member ID
 *    - deleted_at IS NULL (subscription is active)
 * 4. If no record found, return 404 Not Found
 * 5. If record found with deleted_at already set, return 400 Bad Request (already unsubscribed)
 * 6. Update the record by setting deleted_at to current timestamp
 * 7. Return 200 OK with no response body
 *
 * **Database Query**
 * ```sql
 * UPDATE reddit_like_community_subscriptions
 * SET deleted_at = NOW()
 * WHERE id = $1
 *   AND reddit_like_member_id = $2
 *   AND deleted_at IS NULL
 * RETURNING id;
 * ```
 *
 * **Edge Cases**
 * - Handle concurrent unsubscribe attempts (use row-level locking or optimistic concurrency)
 * - Verify the subscription belongs to the authenticated member before deletion
 * - Ensure the operation is idempotent for retry safety
 * @path /redditLike/member/subscriptions/:subscriptionId
 * @accessor api.functional.redditLike.member.subscriptions.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * Unique identifier of the subscription record to unsubscribe from (UUID format).
     */
    subscriptionId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/redditLike/member/subscriptions/:subscriptionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditLike/member/subscriptions/${encodeURIComponent(props.subscriptionId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("subscriptionId")(() => typia.assert(props.subscriptionId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
