import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IPageIEcommerceMallCancellationRequestSnapshot } from "../../../../../../../api/structures/IPageIEcommerceMallCancellationRequestSnapshot";
import { CustomerAuth } from "../../../../../../../decorators/CustomerAuth";
import { CustomerPayload } from "../../../../../../../decorators/payload/CustomerPayload";
import { getEcommerceMallCustomerCustomersMeCancellationRequestsRequestIdSnapshots } from "../../../../../../../providers/getEcommerceMallCustomerCustomersMeCancellationRequestsRequestIdSnapshots";

@Controller(
  "/ecommerceMall/customer/customers/me/cancellation-requests/:requestId/snapshots",
)
export class EcommercemallCustomerCustomersMeCancellation_requestsSnapshotsController {
  /**
   * Retrieves the complete history of snapshots for a specific cancellation request belonging to the authenticated customer.
   *
   * Each snapshot captures the state of the cancellation request at the moment a seller responded (approved or rejected), preserving the reason text and status for audit and dispute resolution purposes. Customers can review the full timeline of their cancellation request, including any responses from sellers.
   *
   * **Authorization**: Only the customer who created the cancellation request can view its snapshots. The system validates ownership by comparing the ecommerce_mall_customer_id on the cancellation request with the authenticated customer ID from the JWT token.
   *
   * **Snapshot Contents**: Each record includes the reason text that was submitted and the status (approved or rejected) at the time of snapshot creation.
   *
   * **Ordering**: Results are ordered by created_at descending, showing the most recent seller response first.
   *
   * **Error Handling**: Returns 404 if the cancellation request does not exist or does not belong to the authenticated customer.
   *
   * @param connection
   * @param requestId Unique identifier of the cancellation request whose snapshots are being retrieved. Must be a valid UUID.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor customer
   * @x-autobe-specification Query the ecommerce_mall_cancellation_requests table to verify the request exists and belongs to the authenticated customer. Compare the ecommerce_mall_customer_id field with the authenticated customer ID extracted from the JWT token. If the cancellation request does not exist or ownership validation fails, return a 404 error.
   *
   * If valid, query the ecommerce_mall_cancellation_request_snapshots table where ecommerce_mall_cancellation_request_id matches the requestId path parameter.
   *
   * Order results by created_at in descending order (most recent snapshot first) to display the latest seller response at the top.
   *
   * Return the snapshot records including: id (UUID), reason (the reason text at snapshot time), status (approved or rejected), and created_at (timestamp of when the seller responded).
   *
   * Implement pagination with page and limit query parameters. Default page to 1 and limit to 20. Return total count for client-side pagination controls.
   *
   * If no snapshots exist (seller has not yet responded), return an empty data array with pagination metadata.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async cancellationRequestSnapshot(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("requestId")
    requestId: string & tags.Format<"uuid">,
  ): Promise<IPageIEcommerceMallCancellationRequestSnapshot> {
    try {
      return await getEcommerceMallCustomerCustomersMeCancellationRequestsRequestIdSnapshots(
        {
          customer,
          requestId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
