import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IHrmPlatformOrganizationSnapshot } from "../../../../../structures/IHrmPlatformOrganizationSnapshot";
import { IPageIHrmPlatformOrganizationSnapshot } from "../../../../../structures/IPageIHrmPlatformOrganizationSnapshot";

/**
 * Retrieve a filtered and paginated list of organization setting snapshots for audit trail purposes.
 *
 * This operation provides access to historical organization configuration changes, capturing point-in-time states of organization settings including branding (name, description, logo), operational settings (currency, timezone), and fiscal period configuration. Each snapshot represents the complete organization state at a specific moment, enabling compliance tracking, change auditing, and historical reconstruction.
 *
 * Snapshots are created automatically when organization settings are modified, forming an immutable append-only audit trail. This operation allows users with organization management permissions to browse the complete history of organization configuration changes.
 *
 * Supports comprehensive filtering by date range, pagination with configurable page sizes, and sorting by creation timestamp. Response includes snapshot summary information optimized for audit log browsing and compliance review.
 *
 * Access is restricted to users with org:manage permission to ensure audit trail confidentiality and prevent unauthorized access to organizational change history.
 *
 * @param props.connection
 * @param props.organizationId Target organization's unique identifier (UUID)
 * @param props.body Pagination, filtering, and sorting parameters for snapshot retrieval
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query hrm_platform_organization_snapshots table filtered by organization ID. Apply pagination with cursor or offset-based pagination. Support filtering by date range (created_at), sorting by created_at descending (newest first). Join with hrm_platform_organizations to validate organization exists and user has org:manage permission. Return paginated snapshot summaries excluding sensitive fields. Enforce organization context isolation - only return snapshots for the specified organization. Validate user has org:manage permission before returning results.
 * @path /hrmPlatform/member/organizations/:organizationId/snapshots
 * @accessor api.functional.hrmPlatform.member.organizations.snapshots.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Target organization's unique identifier (UUID)
     */
    organizationId: string & tags.Format<"uuid">;

    /**
     * Pagination, filtering, and sorting parameters for snapshot retrieval
     */
    body: IHrmPlatformOrganizationSnapshot.IRequest;
  };
  export type Body = IHrmPlatformOrganizationSnapshot.IRequest;
  export type Response = IPageIHrmPlatformOrganizationSnapshot.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/hrmPlatform/member/organizations/:organizationId/snapshots",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/hrmPlatform/member/organizations/${encodeURIComponent(props.organizationId ?? "null")}/snapshots`;
  export const random = (): IPageIHrmPlatformOrganizationSnapshot.ISummary =>
    typia.random<IPageIHrmPlatformOrganizationSnapshot.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("organizationId")(() => typia.assert(props.organizationId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific organization snapshot by its unique identifier.
 *
 * This operation provides access to historical organization configuration data captured at a specific point in time. Organization snapshots preserve the complete state of organization settings including branding information (name, description, logo), operational settings (currency, timezone), and fiscal period configuration (fiscal start month) as they existed when the snapshot was created.
 *
 * Snapshots are automatically generated when organization settings are modified, forming an immutable append-only audit trail. This enables compliance tracking, change auditing, and historical reconstruction of organization configurations over time.
 *
 * Access to organization snapshots requires the `org:manage` permission. The requesting user must be authenticated and have their organization context properly established. The organizationId in the path validates that the snapshot belongs to the current organization context, ensuring proper data isolation across the multi-tenant platform.
 *
 * The snapshot data is read-only and cannot be modified through this or any other API operation. To view the current organization settings, use the organization details endpoint instead. For viewing all snapshots of an organization, use the organization snapshots list endpoint.
 *
 * @param props.connection
 * @param props.organizationId Target organization's unique identifier (global scope)
 * @param props.snapshotId Target snapshot's unique identifier
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query hrm_platform_organization_snapshots table by primary key id and validate organization context.
 *
 * 1. Validate authentication and extract current organization context from session
 * 2. Verify organizationId in path matches the organization context from authentication
 * 3. Query hrm_platform_organization_snapshots WHERE id = {snapshotId} AND hrm_platform_organization_id = {organizationId}
 * 4. Return 404 if snapshot not found or belongs to different organization
 * 5. Verify user has org:manage permission before returning data
 * 6. Return 403 if user lacks required permission
 * 7. Return snapshot record with all fields: id, hrm_platform_organization_id, name, description, logo_url, currency, timezone, fiscal_start_month, created_at
 * 8. No write operations or side effects - pure read operation
 * @path /hrmPlatform/member/organizations/:organizationId/snapshots/:snapshotId
 * @accessor api.functional.hrmPlatform.member.organizations.snapshots.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Target organization's unique identifier (global scope)
     */
    organizationId: string & tags.Format<"uuid">;

    /**
     * Target snapshot's unique identifier
     */
    snapshotId: string & tags.Format<"uuid">;
  };
  export type Response = IHrmPlatformOrganizationSnapshot;

  export const METADATA = {
    method: "GET",
    path: "/hrmPlatform/member/organizations/:organizationId/snapshots/:snapshotId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrmPlatform/member/organizations/${encodeURIComponent(props.organizationId ?? "null")}/snapshots/${encodeURIComponent(props.snapshotId ?? "null")}`;
  export const random = (): IHrmPlatformOrganizationSnapshot =>
    typia.random<IHrmPlatformOrganizationSnapshot>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("organizationId")(() => typia.assert(props.organizationId));
      assert.param("snapshotId")(() => typia.assert(props.snapshotId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
