import { tags } from "typia";

/**
 * Read-only detail schema for a customer login session.
 *
 * Provides authentication metadata and lifecycle timestamps for individual customer login sessions managed by the platform. Enables registered customers to review their session history for security verification and account management.
 *
 * This schema includes the session ID, owning customer ID, originating IP address, referer information, and session lifetime boundaries. Security-sensitive data such as JWT tokens are explicitly excluded.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEcommerceMallCustomerSession = {
  /**
   * Unique identifier for the session record.
   *
   * A UUID that uniquely identifies this authentication session within the platform's session management system.
   *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from
     *   ecommerce_mall_customer_sessions.id. UUID type.
   */
  id: string & tags.Format<"uuid">;

  /**
   * The unique identifier of the customer account that owns this session.
   *
   * Links this authentication session to the specific customer profile via a foreign key constraint. Used to verify ownership when retrieving session details.
   *
     * @x-autobe-database-schema-property ecommerce_mall_customer_id
     * @x-autobe-specification Direct mapping from
     *   ecommerce_mall_customer_sessions.ecommerce_mall_customer_id. UUID type.
   */
  customer_id: string & tags.Format<"uuid">;

  /**
   * The IPv4 network address of the client computer that initiated this authentication session.
   *
   * Captured at login time and used for security auditing, anomaly detection, and session traceability.
   *
     * @x-autobe-database-schema-property ip
     * @x-autobe-specification Direct mapping from
     *   ecommerce_mall_customer_sessions.ip. IPv4 address format, max 15
     *   characters.
   */
  ip: string & tags.Format<"ipv4">;

  /**
   * The original web address from which the user navigated to initiate the login process.
   *
   * Represents the top-level referrer URL that led the customer to the login form. May be null if the browser did not send an origin header or when the session was created through an application client without browser context.
   *
     * @x-autobe-database-schema-property href
     * @x-autobe-specification Direct mapping from
     *   ecommerce_mall_customer_sessions.href. Nullable — null when the
     *   originating URL could not be determined.
   */
  href: (string & tags.Format<"uri">) | null;

  /**
   * The immediate web address where the user clicked the login link, tracking entry points to the authentication flow.
   *
   * Captured from the HTTP Referer header at login time. May be null if the referrer header was absent or if the session was established through an application client without browser context.
   *
     * @x-autobe-database-schema-property referrer
     * @x-autobe-specification Direct mapping from
     *   ecommerce_mall_customer_sessions.referrer. Nullable — null when the
     *   immediate page where the user clicked the login link could not be
     *   determined.
   */
  referrer: (string & tags.Format<"uri">) | null;

  /**
   * The precise timestamp when the customer successfully authenticated and the session was provisioned.
   *
   * Captured at the moment of successful login and used to calculate session age and determine whether the session is still within its valid lifetime period.
   *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from
     *   ecommerce_mall_customer_sessions.created_at. Timestamp when the
     *   customer successfully authenticated.
   */
  createdAt: string & tags.Format<"date-time">;

  /**
   * The absolute expiration timestamp defining when the session's access tokens become invalid to enforce security policies.
   *
   * After this time, the JWT access token must be renewed via the refresh token flow or the customer must re-authenticate to obtain a fresh session.
   *
     * @x-autobe-database-schema-property expired_at
     * @x-autobe-specification Direct mapping from
     *   ecommerce_mall_customer_sessions.expired_at. Timestamp defining when
     *   session tokens become invalid.
   */
  expiredAt: string & tags.Format<"date-time">;
};
export namespace IEcommerceMallCustomerSession {
  /**
   * Summary of a customer authentication session for account security auditing.
   *
   * Represents a single login session record containing essential metadata such as client IP address, originating URLs, creation time, and token expiration time. This compact representation is optimized for paginated list views where customers monitor their active and recent sessions.
   */
  export type ISummary = {
    /**
     * Unique identifier for the authentication session record.
     *
     * A UUID assigned to each session entry to enable precise tracking and retrieval within the session audit log.
     *
         * @x-autobe-database-schema-property id
         * @x-autobe-specification Direct mapping from
         *   ecommerce_mall_customer_sessions.id.
     */
    id: string & tags.Format<"uuid">;

    /**
     * The IPv4 network address of the client computer that initiated this specific authentication session.
     *
     * Captured server-side to provide traceability for security auditing and anomaly detection.
     *
         * @x-autobe-database-schema-property ip
         * @x-autobe-specification Direct mapping from
         *   ecommerce_mall_customer_sessions.ip.
     */
    ip: string & tags.Format<"ipv4">;

    /**
     * The original web address from which the user navigated to initiate the login process.
     *
     * Tracked for traffic analytics; optional when the referring URL is unavailable or stripped by the browser.
     *
         * @x-autobe-database-schema-property href
         * @x-autobe-specification Direct mapping from
         *   ecommerce_mall_customer_sessions.href. Nullable.
     */
    href: (string & tags.Format<"uri">) | null;

    /**
     * The immediate web address of the page where the user clicked the login link, tracking user entry points.
     *
     * Records the direct source of the authentication request; may be null if hidden by privacy settings.
     *
         * @x-autobe-database-schema-property referrer
         * @x-autobe-specification Direct mapping from
         *   ecommerce_mall_customer_sessions.referrer. Nullable.
     */
    referrer: (string & tags.Format<"uri">) | null;

    /**
     * The precise timestamp when the customer successfully authenticated and the session was provisioned.
     *
     * Marks the beginning of the session lifetime, used for duration calculations and audit timelines.
     *
         * @x-autobe-database-schema-property created_at
         * @x-autobe-specification Direct mapping from
         *   ecommerce_mall_customer_sessions.created_at.
     */
    createdAt: string & tags.Format<"date-time">;

    /**
     * The absolute expiration timestamp defining when the session's tokens become invalid.
     *
     * Determines session validity; clients must refresh tokens before this point to maintain access.
     *
         * @x-autobe-database-schema-property expired_at
         * @x-autobe-specification Direct mapping from
         *   ecommerce_mall_customer_sessions.expired_at.
     */
    expiredAt: string & tags.Format<"date-time">;

    /**
     * Computed flag indicating whether the session is currently valid based on expiration time.
     *
     * Evaluated dynamically by comparing the expired_at value against the current server time. Returns true if the token remains active, false otherwise.
     *
         * @x-autobe-specification Computed boolean: true if current server time
         *   is before expired_at; false otherwise.
     */
    isActive: boolean;
  };

  /**
   * Search criteria and pagination parameters for filtering the authenticated customer's sessions by IP address, originating URL, referrer, and active status.
   *
   * This request body specifies filtering criteria, pagination parameters, and sorting preferences when querying the customer's login session history. All fields are optional and are safely applied to the authenticated user's own session records for account security auditing.
   */
  export type IRequest = {
    /**
     * The IPv4 network address of the client computer that initiated this specific authentication session.
     *
     * Captured server-side to provide traceability for security auditing and anomaly detection.
     *
         * @x-autobe-database-schema-property ip
         * @x-autobe-specification Direct mapping from
         *   ecommerce_mall_customer_sessions.ip.
     */
    ip?: (string & tags.Format<"ipv4">) | undefined;
    href?: (string & tags.Format<"uri">) | undefined;
    referrer?: (string & tags.Format<"uri">) | undefined;

    /**
     * Filter by computed active status based on expiration timestamp.
     */
    isActive?: boolean | undefined;

    /**
     * Array of sorting directives. Order determines priority.
     */
    sort?:
      | (
          | "created_at.asc"
          | "created_at.desc"
          | "expired_at.asc"
          | "expired_at.desc"
          | "id.asc"
          | "id.desc"
        )[]
      | undefined;

    /**
     * Page number for pagination.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of items per page.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };
}
