import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IPageIRedditCommunityBanOfMember } from "../../../../structures/IPageIRedditCommunityBanOfMember";
import { IRedditCommunityBanOfMember } from "../../../../structures/IRedditCommunityBanOfMember";

/**
 * Retrieve a filtered and paginated list of community bans.
 *
 * This operation enables moderators and platform administrators to search and view active and historical bans across communities. It supports filtering by specific community, banned actor (member, owner, or moderator), and ban status (active or historical).
 *
 * Responses include comprehensive details about the ban, including the community name, moderator who imposed it, the banned actor's identifier, the reason for the ban, and timestamps. This provides full audit capability for moderation actions.
 *
 * This endpoint is intended for moderation governance and compliance purposes. It requires elevated permissions and should not be exposed to regular members.
 *
 * @param props.connection
 * @param props.body Search criteria for filtering bans
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor communityModerator
 * @x-autobe-specification Query reddit_community_bans table with pagination and filtering.
 * - Filter by community_id if provided
 * - Filter by banned_member_id, banned_owner_id, or banned_moderator_id if provided
 * - Filter by deleted_at = null (active bans) or deleted_at != null (inactive/banned history)
 * - Include relations: community, moderator, and banned_actor details
 * - Return cursor-based pagination for large result sets
 * - Ensure actor authorization: only moderators and admins may access
 * @path /redditCommunity/communityModerator/bans
 * @accessor api.functional.redditCommunity.communityModerator.bans.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria for filtering bans
     */
    body: IRedditCommunityBanOfMember.IRequest;
  };
  export type Body = IRedditCommunityBanOfMember.IRequest;
  export type Response = IPageIRedditCommunityBanOfMember.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditCommunity/communityModerator/bans",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditCommunity/communityModerator/bans";
  export const random = (): IPageIRedditCommunityBanOfMember.ISummary =>
    typia.random<IPageIRedditCommunityBanOfMember.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific community ban record by its unique ID.
 *
 * This endpoint returns the complete record of a ban action imposed on a community member, owner, or moderator. The response includes the banning moderator, the banned entity, the reason for the ban, and the timestamps of creation and last update.
 *
 * The endpoint requires the requesting user to hold either moderator or platform admin privileges for the community. Users who are not authorized will receive a 403 Forbidden response, even if the ban ID exists.
 *
 * This operation is critical for moderation audit trails and is typically used by moderators to review the context of a ban before performing actions like lifting it. This endpoint does not return information about the banning moderator's identity if the banning moderator's account has since been deleted.
 *
 * Note: This endpoint follows the 'at' pattern for single resource retrieval, where the UUID-based banId serves as the primary key. It should not be confused with the list bans endpoint which returns multiple records.
 *
 * @param props.connection
 * @param props.banId The unique UUID identifier of the ban record to retrieve. This is system-generated and immutable.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor communityModerator
 * @x-autobe-specification Query reddit_community_bans table by id field. Return complete ban record including link to community, moderator, and banned entity. Must validate that requestor has moderator or platform admin permissions to view ban details. Use JOIN to include moderator identity and banned entity type (member/owner/moderator). Only return record if deleted_at is null (active ban).
 * @path /redditCommunity/communityModerator/bans/:banId
 * @accessor api.functional.redditCommunity.communityModerator.bans.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The unique UUID identifier of the ban record to retrieve. This is system-generated and immutable.
     */
    banId: string & tags.Format<"uuid">;
  };
  export type Response = IRedditCommunityBanOfMember;

  export const METADATA = {
    method: "GET",
    path: "/redditCommunity/communityModerator/bans/:banId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditCommunity/communityModerator/bans/${encodeURIComponent(props.banId ?? "null")}`;
  export const random = (): IRedditCommunityBanOfMember =>
    typia.random<IRedditCommunityBanOfMember>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("banId")(() => typia.assert(props.banId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
