import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IDiscussionBoardMember } from "../../../structures/IDiscussionBoardMember";
import { IPageIDiscussionBoardMember } from "../../../structures/IPageIDiscussionBoardMember";

/**
 * Retrieve a filtered and paginated list of registered member accounts from the discussion board platform.
 *
 * This operation provides comprehensive search and filtering capabilities for browsing member profiles. Members can search for other users by display name or email, filter by account status, and sort results by various criteria. The response includes essential profile information optimized for list displays and search results.
 *
 * Search functionality supports partial text matching on display names using trigram similarity for flexible user discovery. Email filtering allows exact matching or domain-based searches. Account status filtering enables viewing only active members or including banned accounts (administrator access required).
 *
 * Pagination is supported with configurable page sizes and sorting options. Results can be ordered by registration date, last update time, or display name in ascending or descending order. The default sorting is by registration date with newest members first.
 *
 * Security considerations: Regular members can only view public profile information of other users. Administrators have access to additional fields including ban status and can view all members regardless of account state. Password hashes and sensitive authentication data are never included in responses.
 *
 * Related operations: Use GET /members/{memberId} to retrieve detailed information about a specific member, including their articles and comments. Use PUT /members/{memberId} to update member profile information (own profile only).
 *
 * @param props.connection
 * @param props.body Search criteria, pagination parameters, and sorting options for member list query
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query the discussion_board_members table with pagination and filtering capabilities.
 *
 * 1. Apply search filters:
 *    - Partial text matching on display_name using trigram similarity (GIN index)
 *    - Email domain or exact matching
 *    - Account status filtering (banned boolean)
 *    - Date range filtering on created_at
 *
 * 2. Apply sorting:
 *    - Default: created_at descending (newest first)
 *    - Supported: created_at, updated_at, display_name (ascending/descending)
 *
 * 3. Apply pagination:
 *    - Cursor-based or offset-based pagination
 *    - Configurable page size with reasonable defaults (e.g., 20 items)
 *    - Return pagination metadata (total count, has more)
 *
 * 4. Authorization checks:
 *    - Members: can query other members' public profiles
 *    - Administrators: can query all members including banned status
 *    - Exclude deleted members (deleted_at is not null) unless admin with explicit flag
 *
 * 5. Response transformation:
 *    - Return ISummary variant with essential fields only
 *    - Exclude password_hash for security
 *    - Include derived fields: article count, comment count (via relation counts)
 *
 * 6. Error handling:
 *    - Invalid sort field: return 400 Bad Request
 *    - Invalid pagination parameters: return 400 Bad Request
 *    - Unauthorized access: return 403 Forbidden
 * @path /discussionBoard/members
 * @accessor api.functional.discussionBoard.members.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria, pagination parameters, and sorting options for member list query
     */
    body: IDiscussionBoardMember.IRequest;
  };
  export type Body = IDiscussionBoardMember.IRequest;
  export type Response = IPageIDiscussionBoardMember.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/discussionBoard/members",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/discussionBoard/members";
  export const random = (): IPageIDiscussionBoardMember.ISummary =>
    typia.random<IPageIDiscussionBoardMember.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed profile information for a specific discussion board member by their unique identifier.
 *
 * This operation returns comprehensive member profile data including display name, biographical information, account status, and timestamps. The member's email address and password hash are never exposed in the response for security reasons.
 *
 * Authorization rules: Members can view their own complete profile and other members' public profiles. Administrators have access to view all member profiles including sensitive status information such as banned status. Guest users cannot access member profiles.
 *
 * The operation supports viewing profiles for the purpose of understanding article authorship, comment attribution, and community member information. When a member is banned, their profile remains viewable but their ability to log in and create new content is restricted.
 *
 * Related operations include viewing articles written by a member, viewing comments written by a member, and for administrators, managing member accounts through ban/unban operations.
 *
 * @param props.connection
 * @param props.memberId Unique identifier of the member whose profile is being retrieved
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query the discussion_board_members table for a single record matching the provided memberId UUID.
 *
 * Implementation steps:
 * 1. Validate that memberId is a valid UUID format
 * 2. Query discussion_board_members WHERE id = memberId AND deleted_at IS NULL
 * 3. If no record found, return 404 Not Found
 * 4. Check authorization: caller must be the member themselves, an administrator, or have appropriate permissions
 * 5. Return member data excluding password_hash field
 * 6. Include display_name, bio, banned status, created_at, updated_at fields
 * 7. Handle soft-deleted members by excluding them from results (deleted_at IS NULL check)
 * 8. Log the access for observability and audit trail purposes
 * @path /discussionBoard/members/:memberId
 * @accessor api.functional.discussionBoard.members.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the member whose profile is being retrieved
     */
    memberId: string & tags.Format<"uuid">;
  };
  export type Response = IDiscussionBoardMember;

  export const METADATA = {
    method: "GET",
    path: "/discussionBoard/members/:memberId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/discussionBoard/members/${encodeURIComponent(props.memberId ?? "null")}`;
  export const random = (): IDiscussionBoardMember =>
    typia.random<IDiscussionBoardMember>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("memberId")(() => typia.assert(props.memberId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
