import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

/**
 * Delete a specific SKU option value assignment in the
 * shopping_mall_sku_option_value_assignments table.
 *
 * Remove a specific option value assignment from a SKU that belongs to a
 * particular product, effectively detaching that option value from the SKU
 * configuration.
 *
 * This operation targets the `shopping_mall_sku_option_value_assignments`
 * Prisma table, which represents the association between a SKU record from
 * `shopping_mall_product_skus` and an option value from
 * `shopping_mall_product_option_values`. The path parameters `productCode` and
 * `skuCode` are business-facing identifiers used to locate the parent product
 * and its SKU within the catalog. Once the SKU is resolved, the
 * `skuOptionValueAssignmentId` parameter is used to locate the exact assignment
 * row under that SKU.
 *
 * From a security perspective, only authenticated actors who manage catalog
 * data, such as sellers responsible for the product or platform administrators,
 * should be allowed to call this endpoint. The implementation should enforce
 * that the caller either owns the product's catalog entry (for sellers) or has
 * elevated platform-level permissions (for admins). Unauthorized access
 * attempts must be rejected with appropriate error responses.
 *
 * The operation must validate that the product identified by `productCode`
 * exists, that the SKU identified by `skuCode` belongs to that product, and
 * that the referenced option value assignment belongs to that SKU. If any of
 * those checks fail, the service should return a not-found or conflict-style
 * error rather than performing a deletion. When the assignment exists and is
 * successfully removed, the system should update any cached SKU configuration
 * or derived attributes that depend on its option values.
 *
 * Related operations in this area typically include listing option value
 * assignments for a SKU and creating new assignments when defining or extending
 * SKU variants. Client applications that allow sellers to configure SKU
 * variants would commonly call those operations for configuration and then call
 * this delete endpoint when removing a previously assigned option value from a
 * SKU.
 *
 * @param props.connection
 * @param props.productCode Unique business identifier code of the target
 *   product (global scope) whose SKU option value assignment is being removed.
 * @param props.skuCode Unique business identifier code of the target SKU within
 *   the product (scoped to productCode) from which the option value assignment
 *   will be removed.
 * @param props.skuOptionValueAssignmentId Unique identifier of the specific SKU
 *   option value assignment record in the
 *   shopping_mall_sku_option_value_assignments table to be deleted.
 * @path /shoppingMall/platformAdmin/products/:productCode/skus/:skuCode/optionValueAssignments/:skuOptionValueAssignmentId
 * @accessor api.functional.shoppingMall.platformAdmin.products.skus.optionValueAssignments.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * Unique business identifier code of the target product (global scope)
     * whose SKU option value assignment is being removed.
     */
    productCode: string;

    /**
     * Unique business identifier code of the target SKU within the product
     * (scoped to productCode) from which the option value assignment will
     * be removed.
     */
    skuCode: string;

    /**
     * Unique identifier of the specific SKU option value assignment record
     * in the shopping_mall_sku_option_value_assignments table to be
     * deleted.
     */
    skuOptionValueAssignmentId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/shoppingMall/platformAdmin/products/:productCode/skus/:skuCode/optionValueAssignments/:skuOptionValueAssignmentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/platformAdmin/products/${encodeURIComponent(props.productCode ?? "null")}/skus/${encodeURIComponent(props.skuCode ?? "null")}/optionValueAssignments/${encodeURIComponent(props.skuOptionValueAssignmentId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productCode")(() => typia.assert(props.productCode));
      assert.param("skuCode")(() => typia.assert(props.skuCode));
      assert.param("skuOptionValueAssignmentId")(() =>
        typia.assert(props.skuOptionValueAssignmentId),
      );
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
