import { ICommunityPlatformCommunity } from "@ORGANIZATION/PROJECT-api/lib/structures/ICommunityPlatformCommunity";
import { ICommunityPlatformModerator } from "@ORGANIZATION/PROJECT-api/lib/structures/ICommunityPlatformModerator";
import { ICommunityPlatformPost } from "@ORGANIZATION/PROJECT-api/lib/structures/ICommunityPlatformPost";
import { ICommunityPlatformUser } from "@ORGANIZATION/PROJECT-api/lib/structures/ICommunityPlatformUser";
import { IEntity } from "@ORGANIZATION/PROJECT-api/lib/structures/IEntity";
import { ArrayUtil } from "@nestia/e2e";
import { HttpException } from "@nestjs/common";
import { Prisma } from "@prisma/sdk";
import jwt from "jsonwebtoken";
import typia, { tags } from "typia";
import { v4 } from "uuid";

import { MyGlobal } from "../MyGlobal";
import { GuestPayload } from "../decorators/payload/GuestPayload";
import { CommunityPlatformPostTransformer } from "../transformers/CommunityPlatformPostTransformer";
import { PasswordUtil } from "../utils/PasswordUtil";
import { toISOStringSafe } from "../utils/toISOStringSafe";

export async function getCommunityPlatformGuestPostsPostId(props: {
  guest: GuestPayload;
  postId: string & tags.Format<"uuid">;
}): Promise<ICommunityPlatformPost> {
  const post = await MyGlobal.prisma.community_platform_posts.findUniqueOrThrow(
    {
      where: { id: props.postId },
      select: {
        id: true,
        community_id: true,
        author_user_id: true,
        author_moderator_id: true,
        title: true,
        post_type: true,
        authorUser: {
          select: {
            id: true,
            email: true,
            username: true,
            display_name: true,
            bio: true,
            avatar_url: true,
            karma: true,
            created_at: true,
            updated_at: true,
            deleted_at: true,
            comments: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                content: true,
                post_id: true,
                user_id: true,
                parent_id: true,
                is_deleted: true,
              },
            },
            posts: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_id: true,
                author_user_id: true,
                author_moderator_id: true,
                title: true,
                post_type: true,
              },
            },
            bans: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_id: true,
                user_id: true,
                banned_at: true,
                unbanned_at: true,
                ban_reason: true,
              },
            },
            bannedUsers: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_platform_user_id: true,
                banned_at: true,
                unbanned_at: true,
                reason: true,
                community_platform_community_id: true,
              },
            },
            username: true,
            password_hash: true,
            display_name: true,
            karma: true,
            bio: true,
            avatar_url: true,
            sessions: {
              select: {
                id: true,
                created_at: true,
                deleted_at: true,
                user_id: true,
                ip: true,
                href: true,
                referrer: true,
                expired_at: true,
              },
            },
            passwordResets: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_platform_user_id: true,
                token: true,
                expires_at: true,
                used: true,
              },
            },
            emailVerifications: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                user_id: true,
                token: true,
                expires_at: true,
                is_verified: true,
              },
            },
            activityLogs: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                user_id: true,
                action_type: true,
                ip_address: true,
                user_agent: true,
                metadata: true,
              },
            },
            ownedCommunities: {
              select: {
                id: true,
                owner_user_id: true,
                name: true,
                description: true,
                icon_url: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
              },
            },
            communitySubscriptions: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_id: true,
                user_id: true,
              },
            },
            communityBans: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_id: true,
                user_id: true,
                banned_at: true,
                unbanned_at: true,
                reason: true,
              },
            },
            postVotes: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                vote_type: true,
                user_id: true,
                post_vote_id: true,
              },
            },
            postComments: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                post_id: true,
                user_id: true,
                parent_comment_id: true,
                content_text: true,
              },
            },
            commentVotes: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                vote_type: true,
                community_platform_comment_id: true,
                community_platform_user_id: true,
              },
            },
            postReports: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_platform_user_id: true,
                status: true,
                reason: true,
                community_platform_post_id: true,
              },
            },
            commentReports: {
              select: {
                id: true,
                description: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                status: true,
                comment_id: true,
                reporter_user_id: true,
                report_reason_id: true,
              },
            },
            deletedContents: {
              select: {
                id: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                post_id: true,
                user_id: true,
                reason: true,
                moderator_id: true,
                comment_id: true,
              },
            },
            reports: {
              select: {
                id: true,
                description: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                community_platform_user_id: true,
                community_platform_report_reason_id: true,
                status: true,
              },
            },
          },
        },
        community: {
          select: {
            id: true,
            name: true,
            description: true,
            icon_url: true,
            created_at: true,
            updated_at: true,
            deleted_at: true,
            ownerUser: {
              select: {
                id: true,
                email: true,
                username: true,
                display_name: true,
                bio: true,
                avatar_url: true,
                karma: true,
                created_at: true,
                updated_at: true,
                deleted_at: true,
                comments: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    content: true,
                    post_id: true,
                    user_id: true,
                    parent_id: true,
                    is_deleted: true,
                  },
                },
                posts: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_id: true,
                    author_user_id: true,
                    author_moderator_id: true,
                    title: true,
                    post_type: true,
                  },
                },
                bans: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_id: true,
                    user_id: true,
                    banned_at: true,
                    unbanned_at: true,
                    ban_reason: true,
                  },
                },
                bannedUsers: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_platform_user_id: true,
                    banned_at: true,
                    unbanned_at: true,
                    reason: true,
                    community_platform_community_id: true,
                  },
                },
                username: true,
                password_hash: true,
                display_name: true,
                karma: true,
                bio: true,
                avatar_url: true,
                sessions: {
                  select: {
                    id: true,
                    created_at: true,
                    deleted_at: true,
                    user_id: true,
                    ip: true,
                    href: true,
                    referrer: true,
                    expired_at: true,
                  },
                },
                passwordResets: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_platform_user_id: true,
                    token: true,
                    expires_at: true,
                    used: true,
                  },
                },
                emailVerifications: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    user_id: true,
                    token: true,
                    expires_at: true,
                    is_verified: true,
                  },
                },
                activityLogs: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    user_id: true,
                    action_type: true,
                    ip_address: true,
                    user_agent: true,
                    metadata: true,
                  },
                },
                ownedCommunities: {
                  select: {
                    id: true,
                    owner_user_id: true,
                    name: true,
                    description: true,
                    icon_url: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                  },
                },
                communitySubscriptions: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_id: true,
                    user_id: true,
                  },
                },
                communityBans: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_id: true,
                    user_id: true,
                    banned_at: true,
                    unbanned_at: true,
                    reason: true,
                  },
                },
                postVotes: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    vote_type: true,
                    user_id: true,
                    post_vote_id: true,
                  },
                },
                postComments: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    post_id: true,
                    user_id: true,
                    parent_comment_id: true,
                    content_text: true,
                  },
                },
                commentVotes: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    vote_type: true,
                    community_platform_comment_id: true,
                    community_platform_user_id: true,
                  },
                },
                postReports: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_platform_user_id: true,
                    status: true,
                    reason: true,
                    community_platform_post_id: true,
                  },
                },
                commentReports: {
                  select: {
                    id: true,
                    description: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    status: true,
                    comment_id: true,
                    reporter_user_id: true,
                    report_reason_id: true,
                  },
                },
                deletedContents: {
                  select: {
                    id: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    post_id: true,
                    user_id: true,
                    reason: true,
                    moderator_id: true,
                    comment_id: true,
                  },
                },
                reports: {
                  select: {
                    id: true,
                    description: true,
                    created_at: true,
                    updated_at: true,
                    deleted_at: true,
                    community_platform_user_id: true,
                    community_platform_report_reason_id: true,
                    status: true,
                  },
                },
              },
            },
          },
          postVotes: true,
          postComments: { select: { id: true } },
          created_at: true,
          updated_at: true,
          deleted_at: true,
          reports: { select: { id: true } },
          postSnapshots: { select: { id: true } },
          postTexts: { select: { id: true, content: true } },
          postImages: { select: { id: true } },
          postLink: { select: { id: true, url: true } },
          postReports: { select: { id: true } },
          moderationLogs: { select: { id: true } },
          comments: { select: { id: true } },
          deletionRecords: { select: { id: true } },
        },
      },
    },
  );
  return await CommunityPlatformPostTransformer.transform(post);
}
