import { tags } from "typia";

import { ITodoAppTodoUser } from "./ITodoAppTodoUser";

/**
 * Detailed TodoApp list DTO. Maps to the Prisma model `todo_app_lists`. This
 * response type exposes public-facing list fields and a summary of the owner.
 * Sensitive fields and raw FK columns are intentionally omitted from the
 * response. Use this type for GET /todoApp/lists/{listId} when the caller is
 * authorized to view the list.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppList = {
  /** Unique identifier of the todo list (maps to todo_app_lists.id). */
  id: string & tags.Format<"uuid">;

  /**
   * List title. Business rule: required, non-empty after trimming; max length
   * 250 characters.
   */
  title: string & tags.MaxLength<250>;

  /** Optional list description or notes. Nullable. */
  description?: string | null | undefined;

  /**
   * List visibility semantic. Allowed values: 'private',
   * 'shared-invite-only', 'public'. This field is required and maps to the
   * non-nullable Prisma column todo_app_lists.visibility.
   */
  visibility: "private" | "shared-invite-only" | "public";

  /**
   * Owner summary object (replaces raw todo_app_todouser_id). Contains
   * minimal, non-sensitive owner information for context.
   */
  owner: ITodoAppTodoUser.ISummary;

  /**
   * Record creation timestamp (maps to todo_app_lists.created_at). Use ISO
   * 8601 / RFC3339 format.
   */
  createdAt: string & tags.Format<"date-time">;

  /**
   * Record last modification timestamp (maps to todo_app_lists.updated_at).
   * Use ISO 8601 / RFC3339 format.
   */
  updatedAt: string & tags.Format<"date-time">;

  /**
   * Soft-delete timestamp (nullable). Maps to todo_app_lists.deleted_at.
   * Inclusion in responses should be authorization-gated (owner/admin) to
   * avoid leaking deletion status to unauthorized callers.
   */
  deletedAt?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ITodoAppList {
  /**
   * Query parameters for searching and paginating todo lists. This request
   * schema is used for list retrieval endpoints and maps to the
   * `todo_app_lists` model for filtering purposes. Note: authentication
   * context is required for owner/collaborator scopes; private lists will
   * never be returned to unauthorized callers.
   */
  export type IRequest = {
    /** Page number (1-based) for pagination. */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /** Maximum items per page (bounded by server maximum). */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<200>)
      | undefined;

    /**
     * Full-text search string applied to title and description (max 256
     * chars).
     */
    query?: (string & tags.MaxLength<256>) | undefined;

    /**
     * Filter lists by visibility. Allowed values:
     * 'private','shared-invite-only','public'.
     */
    visibility?: "private" | "shared-invite-only" | "public" | undefined;

    /**
     * Result scope: 'owned' = lists owned by requesting user;
     * 'collaborating' = lists where requesting user is an accepted
     * collaborator; 'public' = public lists. If omitted, returns all lists
     * visible to the requesting user.
     */
    scope?: "owned" | "collaborating" | "public" | undefined;

    /**
     * Field to sort by. Allowed values: 'createdAt','title'. Default:
     * createdAt.
     */
    sortBy?: "createdAt" | "title" | undefined;

    /** Sort direction. Allowed values: 'asc','desc'. Default: asc. */
    order?: "asc" | "desc" | undefined;

    /**
     * When true and caller is owner/admin, include soft-deleted lists in
     * results (default: false). This is a semantic boolean flag; callers
     * transmitting via query string may send 'true'/'false', but the schema
     * models the semantic type as boolean.
     */
    includeDeleted?: boolean | undefined;
  };

  /**
   * Create DTO for todo_app_lists. The authenticated user's id
   * (todo_app_todouser_id) MUST NOT be provided by clients; it is injected by
   * the server from the authentication context. On creation of a 'public'
   * visibility list, server may create associated public-index preferences
   * and an audit log entry.
   */
  export type ICreate = {
    /**
     * List title. Required. Application trims surrounding whitespace and
     * enforces a max length of 250 characters.
     */
    title: string & tags.MinLength<1> & tags.MaxLength<250>;

    /** Optional list description or notes (max 4000 characters). */
    description?: (string & tags.MaxLength<4000>) | null | undefined;

    /**
     * List visibility. Defaults to 'private' when omitted. Allowed values:
     * 'private','shared-invite-only','public'.
     */
    visibility?: "private" | "shared-invite-only" | "public" | undefined;
  };

  /**
   * Update DTO for todo lists. All fields are optional; ownership must be
   * verified by the server. This DTO does NOT accept immutable or
   * system-managed fields (id, createdAt, updatedAt, todo_app_todouser_id).
   * Use this for PATCH/PUT semantics where only the provided fields are
   * applied.
   */
  export type IUpdate = {
    /**
     * New title for the list. If provided, MUST be a non-empty string after
     * trimming and no longer than 250 characters. Use omission (do not
     * include the property) to leave the title unchanged. Clearing the
     * title to null is NOT allowed by this DTO.
     */
    title?: (string & tags.MinLength<1> & tags.MaxLength<250>) | undefined;

    /**
     * Optional description. Provide null to clear the field. Max length
     * enforced at application layer (4000 chars).
     */
    description?: string | null | undefined;

    /**
     * Updated visibility for the list. Only allowed values are listed;
     * ownership checks must be enforced server-side.
     */
    visibility?: "private" | "shared-invite-only" | "public" | undefined;
  };

  /**
   * Summary representation of a todo list. Maps to Prisma model
   * `todo_app_lists`. Designed for embedding in activity and task summaries —
   * includes ownership context but intentionally excludes composition arrays
   * (no tasks[] in summary). Property names use camelCase for API consistency
   * (createdAt/updatedAt/deletedAt).
   */
  export type ISummary = {
    /** Unique identifier of the list. Maps to todo_app_lists.id. */
    id: string & tags.Format<"uuid">;

    /**
     * List title as provided by the owner. Application enforces trimming
     * and max length at the API layer.
     */
    title: string;

    /**
     * List visibility setting (e.g.,
     * 'private','shared-invite-only','public'). Maps to
     * todo_app_lists.visibility.
     */
    visibility: string;

    /**
     * Owner of the list represented as a user summary (belongs-to
     * reference). Replaces raw foreign key todo_app_todouser_id.
     */
    owner: ITodoAppTodoUser.ISummary;

    /**
     * Optional list description or notes. Nullable. Maps to
     * todo_app_lists.description.
     */
    description?: string | null | undefined;

    /**
     * List creation timestamp (ISO 8601). Maps to
     * todo_app_lists.created_at.
     */
    createdAt: string & tags.Format<"date-time">;

    /**
     * List last modification timestamp (ISO 8601). Maps to
     * todo_app_lists.updated_at.
     */
    updatedAt: string & tags.Format<"date-time">;

    /**
     * Soft-delete timestamp. Nullable when the list is active. Maps to
     * todo_app_lists.deleted_at.
     */
    deletedAt?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
