import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { MemberAuth } from "../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../decorators/payload/MemberPayload";
import { deleteRedditCommunityMemberSubscriptionsSubscriptionId } from "../../../../providers/deleteRedditCommunityMemberSubscriptionsSubscriptionId";

@Controller("/redditCommunity/member/subscriptions/:subscriptionId")
export class RedditcommunityMemberSubscriptionsController {
  /**
   * Permanently remove a member's subscription to a specific community.
   *
   * This operation deletes the subscription record between a user and a community, effectively unsubscribing them from the community. This action is irreversible—there are no soft-delete fields in the database, and the record is permanently removed.
   *
   * After deletion, the user will no longer be able to create posts in this community, and their feed will no longer include content from this community. The community's subscriberCount is decremented automatically by the system.
   *
   * This endpoint is only accessible to the authenticated member who holds the subscription. A member cannot unsubscribe from a community they are not subscribed to—this validation is enforced by the system before the request is made.
   *
   * This operation does not affect the member's account status, the community's existence, or other subscriptions. It is solely for voluntary, user-initiated unsubscription.
   *
   * @param connection
   * @param subscriptionId Unique UUID identifier of the subscription record.
   *
   *                       This is the primary key of the reddit_community_subscriptions table.
   *                       Each subscription has a unique UUID generated upon creation.
   *                       This parameter is not derived from relationships like user_id or community_id.
   *                       It uniquely identifies the subscription record itself.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Perform a hard delete on the reddit_community_subscriptions record where id = subscriptionId.
   * Query by UUID primary key. Use Prisma's delete() method with where: { id: subscriptionId }.
   * Ensure transactional integrity: if deletion fails, return 500. After deletion, asynchronously trigger karma recalculation if applicable.
   * Return HTTP status 200 OK.
   * Validate: user making request must be owner of the subscription.
   * Discourage batch deletion—all deletions must be one-off by authorized user.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete()
  public async erase(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("subscriptionId")
    subscriptionId: string,
  ): Promise<void> {
    try {
      return await deleteRedditCommunityMemberSubscriptionsSubscriptionId({
        member,
        subscriptionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
