import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { ICommunityPlatformUser } from "../../../../structures/ICommunityPlatformUser";

/**
 * Update the authenticated user's profile information, including display name, biography, and avatar URL.
 *
 * This operation allows a logged-in user to modify their profile details to reflect their current identity and preferences. It excludes changes to email or password for security reasons, which should be handled by separate dedicated endpoints.
 *
 * - The 'display_name' field is mandatory and visible publicly.
 * - The 'bio' field is optional and can be set to provide a brief user biography.
 * - The 'avatar_url' field is optional and holds the URL to the user's avatar image.
 *
 * Only the authenticated user can perform this operation on their own profile.
 *
 * Upon success, the updated full user profile is returned, reflecting all current data including unchanged fields.
 *
 * Related operations include:
 * - POST /users for new user registration
 * - PATCH /users for querying user lists
 * - PUT /users/{id} for admin-level user updates
 *
 * This endpoint references the 'community_platform_users' user entity and aligns with its fields and constraints.
 *
 * @param props.connection
 * @param props.body User profile information to update
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor user
 * @x-autobe-specification Authenticate the user making the request. Extract the authenticated user's ID from the session or JWT token.
 *
 * Validate the request body against the ICommunityPlatformUsers.IUpdate schema.
 *
 * Update the matching user record in 'community_platform_users' table setting the fields: display_name, bio, avatar_url.
 *
 * Ensure no changes to email or password_hash via this operation.
 *
 * Return the updated user record as response body.
 *
 * Handle errors such as unauthorized access or invalid input with appropriate HTTP status codes.
 *
 * Log the update action for auditing.
 *
 * Ensure database transactionality and data integrity during update.
 * @path /communityPlatform/user/profile
 * @accessor api.functional.communityPlatform.user.profile.updateProfile
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function updateProfile(
  connection: IConnection,
  props: updateProfile.Props,
): Promise<updateProfile.Response> {
  return true === connection.simulate
    ? updateProfile.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...updateProfile.METADATA,
          path: updateProfile.path(),
          status: null,
        },
        props.body,
      );
}
export namespace updateProfile {
  export type Props = {
    /**
     * User profile information to update
     */
    body: ICommunityPlatformUser.IUpdate;
  };
  export type Body = ICommunityPlatformUser.IUpdate;
  export type Response = ICommunityPlatformUser;

  export const METADATA = {
    method: "PUT",
    path: "/communityPlatform/user/profile",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/user/profile";
  export const random = (): ICommunityPlatformUser =>
    typia.random<ICommunityPlatformUser>();
  export const simulate = (
    connection: IConnection,
    props: updateProfile.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: updateProfile.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
