import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IHrmPlatformActivityLog } from "../../../../structures/IHrmPlatformActivityLog";
import { IPageIHrmPlatformActivityLog } from "../../../../structures/IPageIHrmPlatformActivityLog";

/**
 * Search and list activity log entries with pagination, filtering, and sorting capabilities.
 *
 * Retrieves audit trail records from the activity log system. This operation is accessible only to users with the org:manage permission. Results are scoped to the user's active organization context.
 *
 * Supported operations include:
 * - Time range filtering (created_at range)
 * - Entity type filtering (project, task, employee, etc.)
 * - Action type filtering (create, update, delete, etc.)
 * - Member attribution filtering
 * - Custom JSON field searching via extra_data
 *
 * Activity log entries are immutable audit records. Users can only view them, never modify or delete.
 *
 * @param props.connection
 * @param props.body Search criteria for activity logs including entity filters, time ranges, pagination, and sorting options.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Execute a paginated search query on
 *   hrm_platform_activity_logs table.
 *
 * 1. Permission Check:
 *    - Validate user has 'org:manage' permission before executing query
 *    - Throw 403 Forbidden if permission is missing
 *
 * 2. Organization Scoping:
 *    - Filter by organization_id from user's active organization context
 *    - Do NOT expose activity logs from other organizations
 *
 * 3. Filter Application:
 *    - Apply entity_type filter if provided
 *    - Apply action_type filter if provided
 *    - Apply action_name filter if provided
 *    - Apply member_id filter if provided
 *    - Apply time range filters (created_at >= from, created_at <= to)
 *    - Apply extra_data JSON search if provided
 *    - Exclude soft-deleted records (deleted_at IS NULL)
 *
 * 4. Index Usage:
 *    - Use (entity_type, entity_id) unique index for entity_type filters
 *    - Use action_type index for action_type filters
 *    - Use (organization_id, created_at) composite index for organization + time filtering
 *    - Use GIN index on extra_data for JSON field searches
 *
 * 5. Sorting:
 *    - Default sort by created_at DESC (most recent first)
 *    - Allow custom sorting by created_at, updated_at
 *    - Prevent sorting by non-indexed fields for performance
 *
 * 6. Pagination:
 *    - Implement cursor-based or offset-based pagination
 *    - Default page size: 20 items
 *    - Max page size: 100 items
 *    - Return total count, page number, page size, total pages
 *
 * 7. Response Construction:
 *    - Return summary fields: id, entity_type, entity_id, action_name, action_type, member_id (if accessible), created_at, organization_id
 *    - Exclude extra_data from summary (use full view for details)
 *
 * 8. Error Handling:
 *    - 403 Forbidden: User lacks org:manage permission
 *    - 400 Bad Request: Invalid pagination parameters, invalid sort fields
 *    - 500 Internal Server Error: Database query failure
 *
 * 9. Security:
 *    - Never expose extra_data sensitive information
 *    - Sanitize all filter inputs to prevent SQL injection
 *    - Log the search query for audit purposes
 * @path /hrmPlatform/member/activity-logs
 * @accessor api.functional.hrmPlatform.member.activity_logs.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria for activity logs including entity filters, time ranges, pagination, and sorting options.
     */
    body: IHrmPlatformActivityLog.IRequest;
  };
  export type Body = IHrmPlatformActivityLog.IRequest;
  export type Response = IPageIHrmPlatformActivityLog.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/hrmPlatform/member/activity-logs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/hrmPlatform/member/activity-logs";
  export const random = (): IPageIHrmPlatformActivityLog.ISummary =>
    typia.random<IPageIHrmPlatformActivityLog.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific activity log entry by its unique identifier.
 *
 * This operation returns the full activity log record including the member who performed the action, the organization, the affected entity, action details, and any extra metadata. Activity log entries are immutable audit records that cannot be modified or deleted.
 *
 * The operation is read-only and does not allow any modifications to the activity log entry. The returned data includes all fields from the hrm_platform_activity_logs table.
 *
 * @param props.connection
 * @param props.activityLogId The unique identifier of the activity log entry to retrieve.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query hrm_platform_activity_logs table by UUID id.
 *
 * 1. Validate that activityLogId is a valid UUID format.
 * 2. Look up the activity log entry by id.
 * 3. If not found, return 404 Not Found.
 * 4. Verify the requesting user has organization management permission (org:manage) for the organization_id in the activity log.
 * 5. Return the full activity log record.
 *
 * Security: Activity logs are organization-scoped. The user can only view activity logs from their currently selected organization. Users without org:manage permission cannot access activity logs at all.
 *
 * Immutability: This is a read-only operation. No modifications are allowed to activity log entries.
 * @path /hrmPlatform/member/activity-logs/:activityLogId
 * @accessor api.functional.hrmPlatform.member.activity_logs.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The unique identifier of the activity log entry to retrieve.
     */
    activityLogId: string & tags.Format<"uuid">;
  };
  export type Response = IHrmPlatformActivityLog;

  export const METADATA = {
    method: "GET",
    path: "/hrmPlatform/member/activity-logs/:activityLogId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrmPlatform/member/activity-logs/${encodeURIComponent(props.activityLogId ?? "null")}`;
  export const random = (): IHrmPlatformActivityLog =>
    typia.random<IHrmPlatformActivityLog>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("activityLogId")(() => typia.assert(props.activityLogId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
