import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IHrmTrackerAnalytic } from "../../../../../../api/structures/IHrmTrackerAnalytic";
import { IPageIHrmTrackerAnalytic } from "../../../../../../api/structures/IPageIHrmTrackerAnalytic";
import { MemberAuth } from "../../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../../decorators/payload/MemberPayload";
import { patchHrmTrackerMemberOrganizationsOrganizationIdAnalyticsEmployees } from "../../../../../../providers/patchHrmTrackerMemberOrganizationsOrganizationIdAnalyticsEmployees";

@Controller(
  "/hrmTracker/member/organizations/:organizationId/analytics/employees",
)
export class HrmtrackerMemberOrganizationsAnalyticsEmployeesController {
  /**
   * Retrieve aggregated employee statistics and distribution metrics for a specific organization.
   *
   * This operation calculates and returns key employee analytics including total employee count, active/deactivated breakdown, distribution by employment type (full-time, part-time, contractor, intern), and department-level statistics. It serves as a dashboard analytics endpoint for organizational oversight and workforce planning.
   *
   * The operation enforces strict multi-tenancy: only users within the selected organization context can view its employee statistics. All data is automatically scoped to the organization identified by the organizationId path parameter. Deactivated employees are included in counts but excluded from active queries unless explicitly requested.
   *
   * The request body allows optional filtering by department, employment type, and status to generate custom reports. When no filters are applied, the response provides a complete overview of the organization's employee composition.
   *
   * @param connection
   * @param organizationId Organization's unique identifier for multi-tenancy isolation
   * @param body Optional filters for analytics aggregation
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Query hrm_tracker_employees table with organization context.
   * Apply optional filters from request body: department_id, employment_type, status.
   * Calculate aggregate statistics: total count, active count, deactivated count.
   * Calculate employment type distribution using GROUP BY on employment_type.
   * Calculate department breakdown with employee counts per department.
   * Return paginated summary statistics rather than raw employee records.
   * Ensure organization_id from path matches organization context.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("organizationId")
    organizationId: string,
    @TypedBody()
    body: IHrmTrackerAnalytic.IEmployeeStatisticsRequest,
  ): Promise<IPageIHrmTrackerAnalytic.IEmployeeStatistic> {
    try {
      return await patchHrmTrackerMemberOrganizationsOrganizationIdAnalyticsEmployees(
        {
          member,
          organizationId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
