import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { postTodoListUserTodos } from "../../../../providers/postTodoListUserTodos";
import { UserAuth } from "../../../../decorators/UserAuth";
import { UserPayload } from "../../../../decorators/payload/UserPayload";
import { patchTodoListUserTodos } from "../../../../providers/patchTodoListUserTodos";
import { getTodoListUserTodosTodoId } from "../../../../providers/getTodoListUserTodosTodoId";
import { putTodoListUserTodosTodoId } from "../../../../providers/putTodoListUserTodosTodoId";
import { deleteTodoListUserTodosTodoId } from "../../../../providers/deleteTodoListUserTodosTodoId";

import { ITodoListTodo } from "../../../../api/structures/ITodoListTodo";
import { IPageITodoListTodo } from "../../../../api/structures/IPageITodoListTodo";

@Controller("/todoList/user/todos")
export class TodolistUserTodosController {
  /**
   * Create a new Todo item in the todo_list_todos table for the authenticated
   * user.
   *
   * Create a new Todo item for the authenticated user.
   *
   * When invoked, the system validates the request: description is required,
   * must not be blank, and is limited to 250 characters. If provided, done date
   * must be a future ISO 8601 datetime. The system also checks that no existing
   * Todo for this user shares both description and due date.
   *
   * Upon passing validation, the Todo is created with completed set to false by
   * default, completion timestamp null, and timestamps for creation and update
   * set to current time. If validations fail (e.g., missing/invalid input,
   * duplicate, exceeding user Todo limit, or rate limit exceeded), an error is
   * returned with explicit details and guidance.
   *
   * Only authenticated users may perform this operation. Ownership and privacy
   * are strictly enforced: the new Todo is linked only to the user who
   * submitted the request. Related endpoints include GET /todos/{todoId}
   * (retrieve), PATCH /todos (list), PUT /todos/{todoId} (update), and DELETE
   * /todos/{todoId} (deletion).
   *
   * @param connection
   * @param body Description, optional due date, and required details for Todo
   *   creation. All constraints and field rules are enforced.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @UserAuth()
    user: UserPayload,
    @TypedBody()
    body: ITodoListTodo.ICreate,
  ): Promise<ITodoListTodo> {
    try {
      return await postTodoListUserTodos({
        user,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a paginated, filtered list of the authenticated user's Todo items
   * from the todo_list_todos table.
   *
   * This endpoint allows an authenticated user to list their own Todo items,
   * retrieving them with advanced filtering options. Users may filter Todos by
   * completion status (completed or uncompleted) and due date range. All
   * results are strictly scoped to the requesting user's ownership, enforcing
   * privacy and preventing cross-user access.
   *
   * The operation enforces pagination for performance, with a maximum per-page
   * limit as specified in business rules (up to 50 items per page by default).
   * Sorting by creation date, completion status, and due date is supported for
   * flexible list organization.
   *
   * Only authenticated users are permitted to call this operation;
   * unauthenticated or expired tokens receive 401 errors. Users never see or
   * interact with any other user's data. All fields (description, completion
   * status, due date, timestamps) are present, with summary DTOs optimized for
   * bulk transfer. This operation relies entirely on the todo_list_todos
   * schema, with user reference integrity and business logic enforced by
   * backend providers.
   *
   * @param connection
   * @param body Filter, search, and pagination parameters for retrieving the
   *   user's Todo list.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @UserAuth()
    user: UserPayload,
    @TypedBody()
    body: ITodoListTodo.IRequest,
  ): Promise<IPageITodoListTodo.ISummary> {
    try {
      return await patchTodoListUserTodos({
        user,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve details of a specific Todo item from the todo_list_todos table.
   *
   * Retrieve the details of a specific Todo item owned by the authenticated
   * user.
   *
   * On invocation, the API validates that the provided todoId uniquely
   * identifies an existing Todo belonging to the requester. If the Todo is
   * found and access is permitted, the response contains complete information:
   * task description, optional due date, completion boolean, and precise
   * timestamps for creation, last update, and completion (if applicable).
   *
   * Strict user isolation is enforced: the user may only access their own
   * Todos. Attempts to access a non-existent or unauthorized Todo will result
   * in a 404 Not Found or 403 Forbidden error. Sensitive ownership validation
   * is performed at every request. No information about other users' Todos is
   * ever leaked.
   *
   * Related operations: PATCH /todos (list/filter/search), POST /todos
   * (creation), PUT /todos/{todoId} (update), DELETE /todos/{todoId}
   * (deletion). Any write operation requires similar ownership checks.
   *
   * @param connection
   * @param todoId Unique identifier of the Todo item to retrieve (must be a
   *   UUID v4). User may access only Todos they own.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":todoId")
  public async at(
    @UserAuth()
    user: UserPayload,
    @TypedParam("todoId")
    todoId: string & tags.Format<"uuid">,
  ): Promise<ITodoListTodo> {
    try {
      return await getTodoListUserTodosTodoId({
        user,
        todoId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update a single todo item in the todo_list_todos table by its unique
   * identifier.
   *
   * Update an existing todo item using the todo item's unique identifier.
   *
   * This operation allows an authenticated user to modify the details of one of
   * their todo entries. All requested update fields are strictly validated
   * according to the todo_list_todos table schema. Business logic ensures that
   * users cannot modify todos belonging to other users and that field-level
   * constraints (such as completion date or description requirements) are
   * enforced.
   *
   * This endpoint is secured; only the owner of the target todo item may access
   * it. Operations on system-generated or audit fields are forbidden. On
   * success, the API returns the complete updated todo item entity. Edge cases,
   * such as attempting to update non-existent items or fields not present in
   * the schema, are handled gracefully, with clear error responses.
   *
   * @param connection
   * @param todoId Unique identifier of the target todo item record in the
   *   todo_list_todos table.
   * @param body Fields and values to update in the target todo item, following
   *   ITodoListTodo.IUpdate structure.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":todoId")
  public async update(
    @UserAuth()
    user: UserPayload,
    @TypedParam("todoId")
    todoId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ITodoListTodo.IUpdate,
  ): Promise<ITodoListTodo> {
    try {
      return await putTodoListUserTodosTodoId({
        user,
        todoId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete (erase) a single todo item, given its unique ID, from the
   * todo_list_todos table.
   *
   * Permanently remove a specific todo item identified by its unique ID from
   * the todo_list_todos table.
   *
   * This operation allows an authenticated user to delete (hard remove) a todo
   * item that they own. It verifies ownership and ensures only the correct item
   * is removed. All system integrity and authorization checks are strictly
   * enforced.
   *
   * There is no soft deletion logic and no request body. Deletion of items not
   * present or not owned by the user triggers meaningful error feedback. No
   * representation of the deleted item is returned.
   *
   * @param connection
   * @param todoId Unique identifier of the target todo item record in the
   *   todo_list_todos table.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":todoId")
  public async erase(
    @UserAuth()
    user: UserPayload,
    @TypedParam("todoId")
    todoId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteTodoListUserTodosTodoId({
        user,
        todoId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
