import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IRedditCommunityMember } from "../../../api/structures/IRedditCommunityMember";
import { getRedditCommunityUsersUsername } from "../../../providers/getRedditCommunityUsersUsername";

@Controller("/redditCommunity/users/:username")
export class RedditcommunityUsersController {
  /**
   * Retrieve a user's public profile by username. This is a read-only endpoint that provides user information based on the requester's relationship to the target user.
   *
   * When the requester is the authenticated owner of the profile (matching username), the response includes the full profile: username, display_name, bio, avatar_url, karma_score, created_at, and updated_at.
   *
   * When the requester is any other user (authenticated or guest), the response only includes the minimal profile: username, display_name, bio, avatar_url, karma_score, and created_at. All sensitive fields like email and updated_at are excluded.
   *
   * The endpoint returns HTTP 404 Not Found if the username does not exist. Query parameters are not supported. Profiles are always publicly accessible regardless of user status (banned, suspended, etc.), per system requirements.
   *
   * This endpoint is used by frontend components to display author profiles on posts, comments, and community content. It is also called when navigating to a user's profile page.
   *
   * The operation does not support pagination or filtering. Only one user can be queried at a time using the username path parameter.
   *
   * Note: This endpoint does not return post or comment lists. Those are separate endpoints (/users/{username}/posts and /users/{username}/comments).
   *
   * @param connection
   * @param username The unique username identifier of the target user profile. Must match exactly with the username field in reddit_community_members.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification Query reddit_community_members table by username (case-sensitive exact match). Use Prisma findOne with where: { username: username, is_deleted: false }. Apply visibility logic: if requester.userId matches user.id, return full object; else, return minimal object with only: id, username, display_name, bio, avatar_url, karma_score, created_at. Return 404 if no matching user or is_deleted is true. No caching layer required as data changes infrequently. Can be called by unauthenticated guests.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @TypedParam("username")
    username: string,
  ): Promise<IRedditCommunityMember.ISummary> {
    try {
      return await getRedditCommunityUsersUsername({
        username,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
