import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICommunityPlatformShipment } from "../../../../structures/ICommunityPlatformShipment";
export * as addresses from "./addresses/index";
export * as costs from "./costs/index";
export * as notes from "./notes/index";
export * as packages from "./packages/index";
export * as trackings from "./trackings/index";
export * as insurances from "./insurances/index";
export * as return_authorizations from "./return_authorizations/index";
export * as complete from "./complete/index";

/**
 * Submit a new shipment request to initiate logistics processing for a product
 * delivery. This operation triggers the creation of a shipment record in the
 * community_platform_shipments database table, which contains metadata about
 * shipping details and allocates carrier resources for delivery. The request
 * must include essential information such as recipient address, preferred
 * delivery window, insurance details, and packaging specifications to ensure
 * successful fulfillment. This operation is restricted to authenticated members
 * who have completed a purchase and logged the corresponding order, and the
 * shipment will be automatically linked to the associated order record in the
 * system.
 *
 * Security considerations include authenticating the requesting user and
 * verifying their ownership of the associated order. The system validates that
 * all required fields are provided and that the recipient address complies with
 * format standards. The request body must contain both primary shipment details
 * and optional enhancements like insurance coverage and special handling
 * instructions.
 *
 * This operation works in coordination with other systems: after submission, it
 * triggers inventory allocation for the associated products, initiates carrier
 * assignment through the community_platform_carriers system, and generates
 * tracking events through the community_platform_shipment_tracking entity. The
 * shipment request must reference a previously created order in the system and
 * cannot be submitted for unassociated products or guest users. Subsequent
 * operations include retrieving shipment details via GET
 * /shipments/{shipmentId} and canceling shipments via DELETE
 * /shipments/{shipmentId} if executed before carrier assignment.
 *
 * @param props.connection
 * @param props.body Complete shipment request data including recipient address,
 *   delivery preferences, and packaging details for creating a new shipment
 *   record in the community_platform_shipments entity.
 * @path /communityPlatform/member/shipments
 * @accessor api.functional.communityPlatform.member.shipments.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Complete shipment request data including recipient address, delivery
     * preferences, and packaging details for creating a new shipment record
     * in the community_platform_shipments entity.
     */
    body: ICommunityPlatformShipment.ICreate;
  };
  export type Body = ICommunityPlatformShipment.ICreate;
  export type Response = ICommunityPlatformShipment;

  export const METADATA = {
    method: "POST",
    path: "/communityPlatform/member/shipments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/member/shipments";
  export const random = (): ICommunityPlatformShipment =>
    typia.random<ICommunityPlatformShipment>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update the delivery status and tracking information for a specific shipment
 * in the community platform.
 *
 * This operation allows authenticated members to update shipment details for
 * their orders. It modifies the shipment record based on the provided data,
 * including tracking number, carrier information, and delivery status. This is
 * a critical operation for maintaining accurate shipping information throughout
 * the fulfillment process.
 *
 * Security considerations require that only the member who created the
 * associated order can update its shipment details. The operation validates the
 * member's authentication token against the order's owner ID before allowing
 * updates. The system tracks all changes to shipment records for audit purposes
 * in the shipment_tracking log.
 *
 * When updating a shipment, all fields are subject to validation against the
 * database schema's constraints. The delivery_status must be one of the
 * officially supported enums defined in the
 * community_platform_delivery_statuses table, and the tracking_number must
 * follow the carrier's specific format. Any invalid values will be rejected
 * with appropriate error codes.
 *
 * This operation is closely related to the GET /shipments/{shipmentId} endpoint
 * which retrieves detailed shipment information and the PATCH /shipments
 * endpoint which searches for shipments based on filters. The update operation
 * triggers notifications to the member about shipment status changes and
 * updates the corresponding order status in the community_platform_orders
 * table.
 *
 * Note: This is not a soft-delete operation and does not use any soft delete
 * keywords; it performs a direct update of the shipment record.
 *
 * @param props.connection
 * @param props.shipmentId Unique identifier of the target shipment (UUID format
 *   for the community_platform_shipments table)
 * @param props.body The shipment update data containing fields to be modified
 * @path /communityPlatform/member/shipments/:shipmentId
 * @accessor api.functional.communityPlatform.member.shipments.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Unique identifier of the target shipment (UUID format for the
     * community_platform_shipments table)
     */
    shipmentId: string;

    /** The shipment update data containing fields to be modified */
    body: ICommunityPlatformShipment.IUpdate;
  };
  export type Body = ICommunityPlatformShipment.IUpdate;
  export type Response = ICommunityPlatformShipment;

  export const METADATA = {
    method: "PUT",
    path: "/communityPlatform/member/shipments/:shipmentId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/member/shipments/${encodeURIComponent(props.shipmentId ?? "null")}`;
  export const random = (): ICommunityPlatformShipment =>
    typia.random<ICommunityPlatformShipment>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("shipmentId")(() => typia.assert(props.shipmentId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Permanently delete a shipment record from the system.
 *
 * This operation performs a hard delete on the community_platform_shipments
 * table, removing the shipment record and all associated shipment data from the
 * database. This deletion cannot be undone and results in permanent removal of
 * the shipment and its related tracking history.
 *
 * Security: This operation requires authentication. Only users with ownership
 * of the shipment or administrative privileges can delete it. The system
 * enforces ownership verification by checking that the authenticated user is
 * associated with the shipment's origin or destination.
 *
 * This operation does not support soft delete. All shipment records, including
 * tracking events, carrier information, and insurance details, are permanently
 * purged from the database upon successful execution.
 *
 * Related Operations: GET /shipments/{shipmentId} can be used to retrieve
 * shipment details before deletion. PATCH /shipments can be used to search for
 * shipments to identify which ones need deletion.
 *
 * @param props.connection
 * @param props.shipmentId Unique identifier of the target shipment to be
 *   deleted
 * @path /communityPlatform/member/shipments/:shipmentId
 * @accessor api.functional.communityPlatform.member.shipments.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the target shipment to be deleted */
    shipmentId: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/communityPlatform/member/shipments/:shipmentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/member/shipments/${encodeURIComponent(props.shipmentId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("shipmentId")(() => typia.assert(props.shipmentId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
