import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIRedditCommunityMemberSession } from "../../../../structures/IPageIRedditCommunityMemberSession";
import { IRedditCommunityMemberSession } from "../../../../structures/IRedditCommunityMemberSession";

/**
 * Retrieve a filtered and paginated list of your active authentication sessions across all devices and browsers.
 *
 * This operation provides comprehensive visibility into your account's session activity, allowing you to review where you're logged in, when sessions were created, and their current status. Each session record includes connection metadata such as IP address, device information, and expiration details for security auditing purposes.
 *
 * Supports advanced filtering by session status (active, expired, revoked), creation date ranges, and sorting options. Response includes pagination information to efficiently navigate through large numbers of sessions. This endpoint is particularly useful for security-conscious users who want to review and manage their active logins across multiple devices.
 *
 * @param props.connection
 * @param props.body Search criteria and filtering parameters for session list
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query reddit_community_member_sessions table with filtering and pagination.
 *
 * Filtering applied:
 * - member_id: automatically filtered to current authenticated user's ID (from authentication context)
 * - deleted_at: exclude soft-deleted (logged out) sessions unless explicitly requested
 * - expired_at: filter by date range for expired sessions
 * - created_at: filter by date range for creation window
 * - ip: optional IP address filter for connection audit
 * - status: filter by session status (active, expired, revoked)
 *
 * Join operations: LEFT JOIN with reddit_community_members to include member username for session ownership verification.
 *
 * Sorting: Support sorting by created_at (descending = newest first), expired_at, or ip address.
 *
 * Pagination: Cursor-based pagination for efficient large result set handling. Default page size: 20 sessions per page. Maximum page size: 100 sessions per page.
 *
 * Security validation:
 * - Verify member_id in authentication token matches query filter
 * - Never return sessions for other users
 * - Mask sensitive token values in response (return only first 8 characters of tokens)
 * - Log session listing for audit trail
 *
 * Edge cases:
 * - Empty result set: return paginated response with empty data array and total_count: 0
 * - All sessions expired: return with total_count and appropriate pagination metadata
 * - Very large session history: use cursor pagination for consistent results across pages
 * @path /redditCommunity/member/sessions
 * @accessor api.functional.redditCommunity.member.sessions.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and filtering parameters for session list
     */
    body: IRedditCommunityMemberSession.IRequest;
  };
  export type Body = IRedditCommunityMemberSession.IRequest;
  export type Response = IPageIRedditCommunityMemberSession.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditCommunity/member/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditCommunity/member/sessions";
  export const random = (): IPageIRedditCommunityMemberSession.ISummary =>
    typia.random<IPageIRedditCommunityMemberSession.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific authentication session.
 *
 * This operation fetches comprehensive details about a session record from the reddit_community_member_sessions table, including the member account it belongs to via member_id, connection metadata (ip, href, referrer), creation timestamp (created_at), update timestamp (updated_at), and expiration status (expired_at). Sessions track member authentication across devices and browsers, enabling members to maintain concurrent sessions with separate JWT tokens.
 *
 * Security considerations:
 * - This operation requires the user to be authenticated (logged in as a member).
 * - A member can view their own sessions by providing their sessionId, or administrators can view any session for security auditing purposes.
 * - Sensitive token values (access_token, refresh_token) are excluded from the response to prevent token exposure and maintain security.
 * - The response includes session status based on expired_at and deleted_at timestamps for monitoring purposes.
 *
 * The session information helps members understand their active login instances across devices and supports security auditing, detecting unauthorized access, and managing multi-device sessions. Soft-delete via deleted_at enables session history audit trail while expired_at enables automatic session cleanup based on configured token lifetime.
 *
 * @param props.connection
 * @param props.sessionId UUID of the session to retrieve
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query the reddit_community_member_sessions table for a session matching the sessionId path parameter.
 *
 * 1. Validate sessionId is a valid UUID format.
 * 2. If authenticated user is not an administrator, verify that member_id matches the authenticated user's ID.
 * 3. Retrieve session record with all non-sensitive fields.
 * 4. Join with reddit_community_members to include member username and profile information.
 * 5. Calculate session status based on expired_at and deleted_at timestamps.
 * 6. Return session details excluding token fields (access_token, refresh_token).
 * 7. Handle case where session does not exist by returning 404 Not Found.
 * @path /redditCommunity/member/sessions/:sessionId
 * @accessor api.functional.redditCommunity.member.sessions.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * UUID of the session to retrieve
     */
    sessionId: string & tags.Format<"uuid">;
  };
  export type Response = IRedditCommunityMemberSession;

  export const METADATA = {
    method: "GET",
    path: "/redditCommunity/member/sessions/:sessionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditCommunity/member/sessions/${encodeURIComponent(props.sessionId ?? "null")}`;
  export const random = (): IRedditCommunityMemberSession =>
    typia.random<IRedditCommunityMemberSession>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("sessionId")(() => typia.assert(props.sessionId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
