import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia from "typia";
import { patchDiscussionBoardAdminUserArticlesArticleIdAttachmentsAttachmentIdReportLinks } from "../../../../../../providers/patchDiscussionBoardAdminUserArticlesArticleIdAttachmentsAttachmentIdReportLinks";
import { AdminuserAuth } from "../../../../../../decorators/AdminuserAuth";
import { AdminuserPayload } from "../../../../../../decorators/payload/AdminuserPayload";

import { IPageIDiscussionBoardReport } from "../../../../../../api/structures/IPageIDiscussionBoardReport";
import { IDiscussionBoardReport } from "../../../../../../api/structures/IDiscussionBoardReport";

@Controller(
  "/discussionBoard/adminUser/articles/:articleId/attachments/:attachmentId/reportLinks",
)
export class DiscussionboardAdminuserArticlesAttachmentsReportlinksController {
  /**
   * Search and paginate reports (discussion_board_reports) associated with a
   * specific article attachment via link records.
   *
   * Retrieve a filtered and paginated collection of report records targeting a
   * specific attachment on an article, enabling moderators to review how that
   * attachment has been reported.
   *
   * This endpoint operates over the discussion_board_reports primary table,
   * which holds individual report entities describing why a piece of content
   * has been flagged, and the discussion_board_report_of_attachments subsidiary
   * table, which associates those reports with a particular attachment. The
   * attachment itself is defined in the discussion_board_attachments table and
   * is related to a parent article in the discussion_board_articles table. The
   * path parameters articleId and attachmentId together identify the attachment
   * whose related reports are to be listed.
   *
   * Because report data often contains sensitive information such as reporter
   * identities, internal moderation notes, and detailed reason text, this API
   * must be restricted to privileged actors. The authorizationActors field is
   * set to ["adminUser"] to indicate that only authenticated administrative
   * users, as modeled in the discussion_board_adminusers table, should be
   * permitted to access this endpoint. Implementations must enforce appropriate
   * authentication and authorization around this actor.
   *
   * The request body uses the IDiscussionBoardReport.IRequest DTO, which
   * encapsulates complex search criteria including status filters (for example,
   * pending, under_review, resolved), reason categories, reporter account type
   * (guest, member, or admin), and date ranges. It also supports pagination and
   * sorting settings so that clients can request specific pages of results in a
   * particular order. The server must interpret these criteria, construct a
   * corresponding query that joins discussion_board_reports with
   * discussion_board_report_of_attachments and their related article/attachment
   * records, and apply pagination.
   *
   * The response body returns an IPageIDiscussionBoardReport.ISummary payload
   * representing a paginated container of report summary records. Each summary
   * entry should provide enough information for moderators to quickly
   * understand the nature of the report (such as status, primary reason,
   * created timestamp, and minimal reporter/target identifiers) without
   * exposing unnecessary internal details. If either the articleId or
   * attachmentId does not correspond to an existing record, or if the
   * attachment is not actually linked to the given article, the implementation
   * should respond with an appropriate domain error (typically a 404 Not Found)
   * instead of returning an empty list, to avoid masking misuse of the path
   * parameters.
   *
   * This operation is intended to be used alongside other report management
   * APIs, such as endpoints that retrieve full report details for a particular
   * report ID or that update report status. Together they support a complete
   * moderation workflow for attachment-related content on the discussion
   * board.
   *
   * @param connection
   * @param articleId Unique identifier of the article that owns the target
   *   attachment whose related reports are being queried.
   * @param attachmentId Unique identifier of the attachment belonging to the
   *   specified article for which associated reports should be listed.
   * @param body Search criteria, filters, and pagination parameters for
   *   retrieving reports about the specified attachment.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @AdminuserAuth()
    adminUser: AdminuserPayload,
    @TypedParam("articleId")
    articleId: string,
    @TypedParam("attachmentId")
    attachmentId: string,
    @TypedBody()
    body: IDiscussionBoardReport.IRequest,
  ): Promise<IPageIDiscussionBoardReport.ISummary> {
    try {
      return await patchDiscussionBoardAdminUserArticlesArticleIdAttachmentsAttachmentIdReportLinks(
        {
          adminUser,
          articleId,
          attachmentId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
