import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IDiscussionBoardArticleFile } from "../../../../../api/structures/IDiscussionBoardArticleFile";
import { SuperadminAuth } from "../../../../../decorators/SuperadminAuth";
import { SuperadminPayload } from "../../../../../decorators/payload/SuperadminPayload";
import { deleteDiscussionBoardSuperAdminArticlesArticleIdFilesFileId } from "../../../../../providers/deleteDiscussionBoardSuperAdminArticlesArticleIdFilesFileId";
import { postDiscussionBoardSuperAdminArticlesArticleIdFiles } from "../../../../../providers/postDiscussionBoardSuperAdminArticlesArticleIdFiles";

@Controller("/discussionBoard/superAdmin/articles/:articleId/files")
export class DiscussionboardSuperadminArticlesFilesController {
  /**
   * Upload files to an article. This operation allows users to attach multiple files to an article, with each file stored with its metadata including original filename, file size, file type, and upload timestamp.
   *
   * @param connection
   * @param articleId Target article's ID
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor superAdmin
   * @x-autobe-specification Upload files to an article by creating FileAttachment records. Validate that the user is authenticated and not banned. Enforce file size and type limits. Associate files with the specified article. Return all file metadata including file URL.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @SuperadminAuth()
    superAdmin: SuperadminPayload,
    @TypedParam("articleId")
    articleId: string & tags.Format<"uuid">,
  ): Promise<IDiscussionBoardArticleFile> {
    try {
      return await postDiscussionBoardSuperAdminArticlesArticleIdFiles({
        superAdmin,
        articleId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete a specific file attachment from an article.
   *
   * This operation permanently removes the file attachment record and the associated file from storage. It is typically used when users or administrators want to remove attachments from articles.
   *
   * @param connection
   * @param articleId The ID of the article containing the file attachment
   * @param fileId The ID of the file attachment to delete
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor superAdmin
   * @x-autobe-specification Delete the file attachment record from the database. Cascade delete the associated file from storage. Ensure the file belongs to the specified article before deletion. Return 204 No Content on success.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":fileId")
  public async erase(
    @SuperadminAuth()
    superAdmin: SuperadminPayload,
    @TypedParam("articleId")
    articleId: string & tags.Format<"uuid">,
    @TypedParam("fileId")
    fileId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteDiscussionBoardSuperAdminArticlesArticleIdFilesFileId({
        superAdmin,
        articleId,
        fileId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
