import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IRedditCommunityUserProfiles } from "../../../../structures/IRedditCommunityUserProfiles";

/**
 * Retrieve detailed user profile information by profile ID.
 *
 * Retrieve detailed user profile information for a specific community member
 * identified by their profile ID. This operation provides comprehensive access
 * to user profile data including public display information, biographical
 * details, and account verification status.
 *
 * The operation returns complete profile information including the member's
 * display name, bio text, location, website URL, avatar image URL, verification
 * status, and custom profile banner. All data is retrieved from the
 * reddit_community_user_profiles table which serves as the central identity hub
 * for community members.
 *
 * Security considerations include ensuring that only authenticated members can
 * access profile information, with appropriate privacy controls based on user
 * preferences. The operation respects privacy settings configured by profile
 * owners while providing necessary information for community interaction.
 *
 * Profile data is essential for community engagement, allowing users to
 * understand each other's background, interests, and contribution history. The
 * avatar and banner URLs enable visual profile customization while verification
 * status ensures community trust and authenticity.
 *
 * @param props.connection
 * @param props.profileId Unique identifier of the user profile to retrieve
 * @path /redditCommunity/member/userProfiles/:profileId
 * @accessor api.functional.redditCommunity.member.userProfiles.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the user profile to retrieve */
    profileId: string & tags.Format<"uuid">;
  };
  export type Response = IRedditCommunityUserProfiles;

  export const METADATA = {
    method: "GET",
    path: "/redditCommunity/member/userProfiles/:profileId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditCommunity/member/userProfiles/${encodeURIComponent(props.profileId ?? "null")}`;
  export const random = (): IRedditCommunityUserProfiles =>
    typia.random<IRedditCommunityUserProfiles>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("profileId")(() => typia.assert(props.profileId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing user profile with new information.
 *
 * Update an existing user profile with authenticated user's profile
 * information. This operation allows community members to modify their profile
 * details including display name, personal bio, avatar image URL, and other
 * customizable profile settings.
 *
 * The operation enforces strict ownership validation to ensure users can only
 * update their own profiles. Profile updates are processed with immediate
 * effect and the updated profile information becomes visible across all
 * community interactions. The operation supports partial updates, allowing
 * users to modify specific fields without affecting unchanged attributes.
 *
 * Security measures include ownership verification through JWT authentication,
 * input validation to prevent malicious content, and privacy controls that
 * respect user privacy settings. The operation integrates with the user
 * profiles table and maintains consistency with related privacy and preference
 * settings.
 *
 * @param props.connection
 * @param props.profileId Unique identifier of the user profile to be updated
 * @param props.body Updated profile information including display name, bio,
 *   avatar URL, and other profile settings
 * @path /redditCommunity/member/userProfiles/:profileId
 * @accessor api.functional.redditCommunity.member.userProfiles.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique identifier of the user profile to be updated */
    profileId: string & tags.Format<"uuid">;

    /**
     * Updated profile information including display name, bio, avatar URL,
     * and other profile settings
     */
    body: IRedditCommunityUserProfiles.IUpdate;
  };
  export type Body = IRedditCommunityUserProfiles.IUpdate;
  export type Response = IRedditCommunityUserProfiles;

  export const METADATA = {
    method: "PUT",
    path: "/redditCommunity/member/userProfiles/:profileId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditCommunity/member/userProfiles/${encodeURIComponent(props.profileId ?? "null")}`;
  export const random = (): IRedditCommunityUserProfiles =>
    typia.random<IRedditCommunityUserProfiles>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("profileId")(() => typia.assert(props.profileId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Permanently delete a user profile and associated user data from the system.
 * This operation allows authenticated users to remove their profiles
 * completely, including all profile information, privacy settings, and
 * preferences.
 *
 * The operation performs a hard delete that removes the profile record from the
 * database. Associated data in snapshot tables is preserved for audit and
 * historical purposes. The deletion is immediate and irreversible, making the
 * profile permanently unavailable across all community interactions.
 *
 * Security measures include strict ownership verification to prevent
 * unauthorized deletions, confirmation of user intent through authentication,
 * and safeguards against accidental deletion. The operation maintains
 * referential integrity by updating related entities and ensuring consistent
 * data state across the platform.
 *
 * @param props.connection
 * @param props.profileId Unique identifier of the user profile to be
 *   permanently deleted
 * @path /redditCommunity/member/userProfiles/:profileId
 * @accessor api.functional.redditCommunity.member.userProfiles.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the user profile to be permanently deleted */
    profileId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/redditCommunity/member/userProfiles/:profileId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditCommunity/member/userProfiles/${encodeURIComponent(props.profileId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("profileId")(() => typia.assert(props.profileId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Create a new user profile with personal information and customization.
 *
 * Create a new user profile for an authenticated community member. This
 * operation establishes the user's public identity within the Reddit-style
 * community platform by creating a comprehensive profile record with personal
 * information and customization settings.
 *
 * The operation accepts user profile data including display name, biography
 * text, location, website URL, avatar image URL, and custom profile banner URL.
 * All information is validated for appropriate content and stored in the
 * reddit_community_user_profiles table which serves as the central identity
 * management system for community members.
 *
 * Profile creation requires an authenticated member context and establishes the
 * foundation for community participation. The display name becomes the user's
 * public identifier within communities, while the biography allows users to
 * share personal information and interests. Location and website URL fields
 * enable users to provide additional context about themselves.
 *
 * The avatar and banner URLs support visual profile customization, allowing
 * users to personalize their community presence. Verification status is
 * automatically set based on email verification completion. Profile creation
 * triggers the establishment of user karma tracking and community participation
 * capabilities.
 *
 * Privacy considerations include default visibility settings, with users able
 * to configure detailed privacy preferences through separate operations. The
 * created profile becomes immediately visible to other community members for
 * engagement and interaction purposes.
 *
 * @param props.connection
 * @param props.body User profile creation data including display name,
 *   biography, and customization settings
 * @path /redditCommunity/member/userProfiles
 * @accessor api.functional.redditCommunity.member.userProfiles.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * User profile creation data including display name, biography, and
     * customization settings
     */
    body: IRedditCommunityUserProfiles.ICreate;
  };
  export type Body = IRedditCommunityUserProfiles.ICreate;
  export type Response = IRedditCommunityUserProfiles;

  export const METADATA = {
    method: "POST",
    path: "/redditCommunity/member/userProfiles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditCommunity/member/userProfiles";
  export const random = (): IRedditCommunityUserProfiles =>
    typia.random<IRedditCommunityUserProfiles>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
