import { tags } from "typia";

import { IHrmPlatformOrganization } from "./IHrmPlatformOrganization";

/**
 * Full session information including authentication token metadata, device identification, organization context, and session lifecycle timestamps.
 *
 * **Session Identity**:
 *
 * Contains the unique session identifier and references to the member account that owns the session. The session is linked to an optional organization context that represents the current working environment for the member.
 *
 * **Device Fingerprinting**:
 *
 * Records client IP address and user agent string for device identification and security monitoring. The referrer URL is captured at session creation to track the source of authentication requests.
 *
 * **Token Expiration**:
 *
 * Tracks separate expiration times for access tokens (short-lived) and refresh tokens (longer-lived). This enables token rotation where access tokens can be invalidated while maintaining the session through refresh tokens. The `expired_at` field indicates whether the session has been terminated.
 *
 * **Security Note**:
 *
 * Token values (access_token, refresh_token) are never exposed in the response for security reasons. Only their expiration metadata is returned.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IHrmPlatformMemberSession = {
  /**
   * @x-autobe-database-schema-property id
   */
  id: string & tags.Format<"uuid">;
  /**
   * @x-autobe-database-schema-property hrm_platform_member_id
   */
  member_id: string & tags.Format<"uuid">;
  /**
   * @x-autobe-database-schema-property organization_id
   */
  organization_id: (string & tags.Format<"uuid">) | null;
  /**
   * @x-autobe-database-schema-property access_token_expires_at
   */
  access_token_expires_at: string & tags.Format<"date-time">;
  /**
   * @x-autobe-database-schema-property refresh_token_expires_at
   */
  refresh_token_expires_at: string & tags.Format<"date-time">;
  /**
   * @x-autobe-database-schema-property ip_address
   */
  ip_address: string;
  /**
   * @x-autobe-database-schema-property user_agent
   */
  user_agent: string;

  /**
   * Referring URL from the login request. Captures where the user came from before authentication.
   *
   * @x-autobe-specification Direct mapping from hrm_platform_member_sessions.referrer column (VarChar 80000 with URI format). Nullable field that may be empty.
   * @x-autobe-database-schema-property referrer
   */
  referrer: (string & tags.Format<"uri">) | null;
  /**
   * @x-autobe-database-schema-property created_at
   */
  created_at: string & tags.Format<"date-time">;
  /**
   * @x-autobe-database-schema-property updated_at
   */
  updated_at: string & tags.Format<"date-time">;
  /**
   * @x-autobe-database-schema-property expired_at
   */
  expired_at: (string & tags.Format<"date-time">) | null;
};
export namespace IHrmPlatformMemberSession {
  /**
   * Request parameters for searching and listing member sessions with pagination, filtering, and sorting.
   *
   * This DTO defines the query criteria for filtering member authentication sessions, including device information, IP addresses, and token expiration times. All fields are optional to allow flexible partial queries.
   *
   * **Search Filters**:
   * - `search`: Text search across IP addresses and user agent strings
   * - `ip_address`: Filter by specific IP address pattern
   * - `user_agent`: Filter by browser/device type pattern
   *
   * **Organization Filtering**:
   * - `organization_id`: Filter sessions by organization context
   *
   * **Status Filtering**:
   * - `status`: Filter by session status (active or expired)
   *
   * **Pagination**:
   * - `page`: Page number (1-indexed)
   * - `limit`: Number of items per page (default: 20, max: 100)
   *
   * **Sorting**:
   * - `sort`: Sort field (created_at, access_token_expires_at, refresh_token_expires_at)
   * - `order`: Sort direction (ASC or DESC)
   */
  export type IRequest = {
    /**
     * Search text across IP addresses and user agent strings
     */
    search?: string | undefined;

    /**
     * Filter by IP address pattern
     *
     * @x-autobe-database-schema-property ip_address
     */
    ip_address?: string | undefined;

    /**
     * Filter by browser or device user agent pattern
     *
     * @x-autobe-database-schema-property user_agent
     */
    user_agent?: string | undefined;

    /**
     * Filter sessions by organization context
     *
     * @x-autobe-database-schema-property organization_id
     * @x-autobe-specification Filter sessions by organization context. Only includes sessions where organization_id matches the filter value.
     */
    organization_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Filter by session status
     */
    status?: "active" | "expired" | undefined;

    /**
     * Page number (1-indexed)
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of items per page
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Sort field
     */
    sort?:
      | "created_at"
      | "access_token_expires_at"
      | "refresh_token_expires_at"
      | undefined;

    /**
     * Sort direction
     */
    order?: "ASC" | "DESC" | undefined;
  };

  /**
   * Summary representation of a member authentication session for list views and dashboards.
   *
   * **Identification**: Unique session identifier for reference.
   *
   * **Device Information**: IP address and user agent string for device identification and security auditing.
   *
   * **Organization Context**: Current organization association if the session has an active organization context (for cross-organization members).
   *
   * **Timestamps**: Session creation time and expiration time. The `expired_at` field indicates whether the session is active (null) or expired (timestamp).
   */
  export type ISummary = {
    /**
     * @x-autobe-database-schema-property id
     */
    id: string & tags.Format<"uuid">;
    /**
     * @x-autobe-database-schema-property ip_address
     */
    ip_address: string;
    /**
     * @x-autobe-database-schema-property user_agent
     */
    user_agent: string;
    /**
     * @x-autobe-database-schema-property created_at
     */
    created_at: string & tags.Format<"date-time">;
    /**
     * @x-autobe-database-schema-property expired_at
     */
    expired_at: (string & tags.Format<"date-time">) | null;
    /**
     * @x-autobe-database-schema-property organization
     */
    organization?: IHrmPlatformOrganization.ISummary | null | undefined;
  };
}
