/**
 * Filter options for retrieving todos based on completion status.
 *
 * This enum defines three filtering modes for todo list queries. The 'all' option returns both complete and incomplete todos without any completion status filter. The 'complete' option returns only todos that have been marked as finished. The 'incomplete' option returns only todos that are still pending and not yet completed.
 *
 * When 'all' is selected or when the filter parameter is null/undefined, the query returns all todos regardless of their completion state. This is useful for viewing the complete todo list. The 'complete' and 'incomplete' filters enable focused views on finished or pending tasks respectively.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IETodoAppTodoFilter = "all" | "complete" | "incomplete";
