import { tags } from "typia";

import { ITodoAppMember } from "./ITodoAppMember";

/**
 * Complete member session information including metadata and client details.
 *
 * This type represents an authenticated session for a member, containing session metadata such as creation time, expiration time, and client information (IP address, page href, referrer). The actual JWT tokens (access_token, refresh_token) are intentionally omitted from responses to prevent token exposure.
 *
 * Sessions are created when a member successfully logs in and are invalidated on logout or expiration. Members can view their active sessions to monitor authenticated access and identify unrecognized devices or locations.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppMemberSession = {
  /**
   * Unique identifier for the session.
   *
   * This is the primary key of the session record, generated as a UUID when the session is created during login.
   *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from todo_app_member_sessions.id.
     *   UUID format primary key.
   */
  id: string & tags.Format<"uuid">;

  /**
   * The member who owns this session.
   *
   * This object contains the profile information of the authenticated member associated with this session. The relation is established via the todo_app_member_id foreign key in the database.
   *
     * @x-autobe-database-schema-property member
     * @x-autobe-specification Relation join from
     *   todo_app_member_sessions.todo_app_member_id to todo_app_members.id.
     *   Returns ITodoAppMember.ISummary with member profile data.
   */
  member: ITodoAppMember.ISummary;

  /**
   * IP address of the client that created this session.
   *
   * Recorded for security auditing and to detect suspicious login patterns. Used to identify the geographic location and device network.
   *
     * @x-autobe-database-schema-property ip
     * @x-autobe-specification Direct mapping from todo_app_member_sessions.ip.
     *   Captured from the client request during session creation.
   */
  ip: string;

  /**
   * URL of the page where the login was initiated.
   *
   * Captures the entry point for the authentication flow. Useful for redirecting users back after successful login and for analytics.
   *
     * @x-autobe-database-schema-property href
     * @x-autobe-specification Direct mapping from
     *   todo_app_member_sessions.href. Captured from the client request during
     *   session creation.
   */
  href: string & tags.Format<"uri">;

  /**
   * HTTP referrer header from the login request.
   *
   * Indicates which page or external site referred the user to the login page. Used for security analysis and traffic source tracking.
   *
     * @x-autobe-database-schema-property referrer
     * @x-autobe-specification Direct mapping from
     *   todo_app_member_sessions.referrer. Captured from the HTTP referrer
     *   header during session creation.
   */
  referrer: string & tags.Format<"uri">;

  /**
   * Timestamp when this session was created.
   *
   * Set automatically when the member successfully logs in. Used for session age calculations and audit trails.
   *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from
     *   todo_app_member_sessions.created_at. Set automatically when the member
     *   successfully logs in.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when this session expires.
   *
   * Sessions are automatically invalidated after this time. Members must log in again to create a new session. Typically set to 7-30 days from creation depending on security policy.
   *
     * @x-autobe-database-schema-property expired_at
     * @x-autobe-specification Direct mapping from
     *   todo_app_member_sessions.expired_at. Sessions are automatically
     *   invalidated after this time.
   */
  expired_at: string & tags.Format<"date-time">;
};
export namespace ITodoAppMemberSession {
  /**
   * Request parameters for paginated session list queries with optional filtering.
   *
   * Pagination is controlled through page and limit parameters. The status field filters sessions by expiration state. Date range filtering uses created_at_from and created_at_to to bound session creation timestamps.
   *
   * All parameters are optional to support flexible querying patterns.
   */
  export type IRequest = {
    /**
     * Page number for pagination.
     *
     * Specifies which page of results to retrieve. Page numbering starts from 1, so the first page is page 1. This parameter works with limit to control result set size.
     *
     * Defaults to 1 if not provided. Must be a positive integer.
     *
         * @x-autobe-specification Query parameter for pagination page number.
         *   Defaults to 1. Applied as OFFSET in SQL query.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Maximum number of records per page.
     *
     * Controls how many session records are returned in a single response. This parameter works with page to implement pagination.
     *
     * Must be between 1 and 100. If not provided, uses a default value determined by the server implementation.
     *
         * @x-autobe-specification Query parameter for page size. Defaults to
         *   implementation-defined value (typically 10-50). Maximum 100.
         *   Applied as LIMIT in SQL query.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Filter sessions by expiration status.
     *
     * Filters the session list based on whether sessions are currently active or expired. The status is computed by comparing expired_at with the current timestamp.
     *
     * - 'active': Session has not yet expired (expired_at is in the future)
     * - 'expired': Session has expired (expired_at is in the past or present)
     *
     * Optional parameter. If not provided, returns both active and expired sessions.
     *
         * @x-autobe-specification Optional filter for session expiration state.
         *   'active' means expired_at > current timestamp. 'expired' means
         *   expired_at <= current timestamp. Computed at query time, not
         *   stored.
     */
    status?: "active" | "expired" | undefined;

    /**
     * Start of creation date range filter.
     *
     * Filters sessions to only include those created on or after this timestamp. Uses greater-than-or-equal comparison against the created_at column.
     *
     * Optional parameter. Format is ISO 8601 date-time (e.g., 2024-01-15T10:30:00Z). If not provided, no lower bound is applied.
     *
         * @x-autobe-specification Optional lower bound filter for session
         *   creation timestamp. Filters sessions where created_at >=
         *   created_at_from. ISO 8601 date-time format.
     */
    created_at_from?: (string & tags.Format<"date-time">) | undefined;

    /**
     * End of creation date range filter.
     *
     * Filters sessions to only include those created on or before this timestamp. Uses less-than-or-equal comparison against the created_at column.
     *
     * Optional parameter. Format is ISO 8601 date-time (e.g., 2024-01-15T10:30:00Z). If not provided, no upper bound is applied.
     *
         * @x-autobe-specification Optional upper bound filter for session
         *   creation timestamp. Filters sessions where created_at <=
         *   created_at_to. ISO 8601 date-time format.
     */
    created_at_to?: (string & tags.Format<"date-time">) | undefined;
  };

  /**
   * Summary representation of a member login session for display in session management interfaces.
   *
   * This DTO provides essential session information including client connection details (IP address, login page URL, referrer), session timestamps, and a reference to the associated member account. Sensitive authentication tokens are intentionally excluded for security.
   *
   * Use this type when displaying active or recent login sessions in account security settings. The expired_at field enables clients to determine session validity status. Sessions are automatically invalidated after their expiration time.
   */
  export type ISummary = {
    /**
     * Unique identifier for the login session.
     *
     * This UUID identifies a specific authentication session for the member. Each login creates a new session with a distinct ID. Used to reference the session in session management operations.
     *
         * @x-autobe-database-schema-property id
         * @x-autobe-specification Direct mapping from
         *   todo_app_member_sessions.id. UUID format generated by database.
     */
    id: string & tags.Format<"uuid">;

    /**
     * The member account associated with this session.
     *
     * This relation connects the session to its owner. Contains the member's profile summary including display name and account timestamps. Loaded via foreign key join to the members table.
     *
         * @x-autobe-database-schema-property member
         * @x-autobe-specification Relation loaded via JOIN from
         *   todo_app_member_sessions.todo_app_member_id to todo_app_members.id.
         *   Returns ITodoAppMember.ISummary with member profile data.
     */
    member: ITodoAppMember.ISummary;

    /**
     * IP address of the client device that created this session.
     *
     * Recorded when the member logs in for security auditing and session identification. Helps detect suspicious login patterns and unauthorized access attempts. Useful for geographic location identification.
     *
         * @x-autobe-database-schema-property ip
         * @x-autobe-specification Direct mapping from
         *   todo_app_member_sessions.ip. Captured from HTTP request at session
         *   creation time.
     */
    ip: string;

    /**
     * URL of the page where the login was initiated.
     *
     * Captures the entry point for the authentication flow. Useful for redirecting users back to their intended destination after successful login and for analytics purposes.
     *
         * @x-autobe-database-schema-property href
         * @x-autobe-specification Direct mapping from
         *   todo_app_member_sessions.href. Captured from browser location at
         *   login time.
     */
    href: string & tags.Format<"uri">;

    /**
     * HTTP referrer header from the login request.
     *
     * Indicates which page or external site referred the user to the login page. Used for security analysis to detect suspicious referral patterns and for traffic source tracking.
     *
         * @x-autobe-database-schema-property referrer
         * @x-autobe-specification Direct mapping from
         *   todo_app_member_sessions.referrer. Captured from HTTP Referrer
         *   header at login time.
     */
    referrer: string & tags.Format<"uri">;

    /**
     * Timestamp when this session was created.
     *
     * Set automatically when the member successfully authenticates and a new session record is inserted. Used for session age calculations, audit trails, and sorting sessions by login time.
     *
         * @x-autobe-database-schema-property created_at
         * @x-autobe-specification Direct mapping from
         *   todo_app_member_sessions.created_at. Set automatically by database
         *   on session creation.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when this session expires and becomes invalid.
     *
     * Sessions are automatically rejected by the authentication middleware after this time. Members must log in again to create a new session. The expiration duration is determined by security policy at session creation.
     *
         * @x-autobe-database-schema-property expired_at
         * @x-autobe-specification Direct mapping from
         *   todo_app_member_sessions.expired_at. Calculated at session creation
         *   based on security policy (typically 7-30 days).
     */
    expired_at: string & tags.Format<"date-time">;
  };
}
