import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallPlatformCommission } from "../../../../structures/IShoppingMallPlatformCommission";
import { IPageIShoppingMallPlatformCommission } from "../../../../structures/IPageIShoppingMallPlatformCommission";

/**
 * Retrieve a filtered and paginated list of platform commission records
 * tracking revenue generated by the marketplace. This operation provides
 * comprehensive search capabilities for finding commission records based on
 * multiple criteria including date ranges, commission amount ranges, associated
 * orders, and commission calculation status.
 *
 * The operation supports full pagination with configurable page sizes and
 * sorting options. Administrators can sort commission records by transaction
 * date, commission amount, order reference, or other relevant fields in
 * ascending or descending order. This enables detailed financial reporting and
 * revenue analysis.
 *
 * Security considerations include strict authorization to ensure only platform
 * administrators can access commission data, as this represents sensitive
 * financial information. The response includes detailed commission information
 * including calculated amounts, associated order references, commission rates
 * applied, and timestamps for audit and accounting purposes.
 *
 * This operation integrates with the shopping_mall_platform_commissions table
 * as defined in the Prisma schema, incorporating all commission tracking fields
 * and relationships to orders and transactions. The response is optimized for
 * financial reporting dashboards and accounting reconciliation processes.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for filtering
 *   platform commission records
 * @path /shoppingMall/admin/platformCommissions
 * @accessor api.functional.shoppingMall.admin.platformCommissions.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for filtering platform
     * commission records
     */
    body: IShoppingMallPlatformCommission.IRequest;
  };
  export type Body = IShoppingMallPlatformCommission.IRequest;
  export type Response = IPageIShoppingMallPlatformCommission.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/admin/platformCommissions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/admin/platformCommissions";
  export const random = (): IPageIShoppingMallPlatformCommission.ISummary =>
    typia.random<IPageIShoppingMallPlatformCommission.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific platform commission record
 * from the marketplace system. This operation provides complete commission
 * details including the commission amount, percentage rate, order reference,
 * seller information, and transaction timestamps.
 *
 * Platform commissions represent the fees charged by the marketplace platform
 * on seller transactions. Each commission record is associated with a specific
 * order and tracks the revenue generated by the platform from that transaction.
 * The commission amount is calculated based on the platform's commission rate
 * applied to the order value.
 *
 * Security considerations: This operation is restricted to admin users only, as
 * platform commission data contains sensitive financial information about
 * platform revenue and seller transaction fees. The operation returns complete
 * commission details for administrative review, financial reporting, and
 * revenue analysis purposes.
 *
 * This operation integrates with the shopping_mall_platform_commissions table
 * as defined in the Prisma schema, providing access to all commission fields
 * including relationships to orders and sellers. The response includes
 * comprehensive commission information optimized for administrative financial
 * analysis and audit purposes.
 *
 * @param props.connection
 * @param props.commissionId Unique identifier of the target platform commission
 *   record
 * @path /shoppingMall/admin/platformCommissions/:commissionId
 * @accessor api.functional.shoppingMall.admin.platformCommissions.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the target platform commission record */
    commissionId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallPlatformCommission;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/admin/platformCommissions/:commissionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/admin/platformCommissions/${encodeURIComponent(props.commissionId ?? "null")}`;
  export const random = (): IShoppingMallPlatformCommission =>
    typia.random<IShoppingMallPlatformCommission>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("commissionId")(() => typia.assert(props.commissionId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
