import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IEconPoliticBoardAdminRequest } from "../../../../structures/IEconPoliticBoardAdminRequest";
import { IPageIEconPoliticBoardAdminRequest } from "../../../../structures/IPageIEconPoliticBoardAdminRequest";

/**
 * Retrieve a filtered and paginated list of administrative account requests from the system. This operation allows super administrators to view and manage user requests for administrative roles, providing details on pending, approved, and rejected requests including user identity, request reason, status, and creation time.
 *
 * The operation supports comprehensive filtering based on request status (pending, approved, rejected), request reason text (case-insensitive partial match), and date ranges for creation time. Results are paginated with configurable page size (default 15 items per page) and support sorting by most recent request first.
 *
 * Security considerations include strict permission enforcement requiring super administrator role, rate limiting of 300 requests per minute per user to prevent abuse, and automatic filtering of sensitive information like IP addresses from the response.
 *
 * This operation integrates with the econ_politic_board_admin_requests database table as defined in the schema, incorporating all relevant fields and relationships. The response provides only essential information optimized for listing, with options to include additional details based on authorization level.
 *
 * @param props.connection
 * @param props.body Filtering parameters for administrative request search
 * @x-autobe-specification Query econ_politic_board_admin_requests table with pagination and filtering by request status (pending, approved, rejected), request reason filters, and created_at range. Apply security layer to restrict access to super administrators. Return cursor-based pagination for large datasets. Cache search results for 2 minutes with search-parameter-based cache keys to improve performance for repeated queries.
 * @path /econPoliticBoard/admin/requests
 * @accessor api.functional.econPoliticBoard.admin.requests.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Filtering parameters for administrative request search
     */
    body: IEconPoliticBoardAdminRequest.IRequest;
  };
  export type Body = IEconPoliticBoardAdminRequest.IRequest;
  export type Response = IPageIEconPoliticBoardAdminRequest.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/econPoliticBoard/admin/requests",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/econPoliticBoard/admin/requests";
  export const random = (): IPageIEconPoliticBoardAdminRequest.ISummary =>
    typia.random<IPageIEconPoliticBoardAdminRequest.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve specific administrative request details including request type, status, and related user information. This operation provides detailed information about a single administrative request such as password resets or role changes.
 *
 * The endpoint is designed for authorized administrators to view the current state of administrative requests. It returns comprehensive details such as the request type (e.g., 'password_reset', 'role_change'), current status (e.g., 'pending', 'approved', 'rejected'), creation timestamp, and associated user identifiers.
 *
 * Security considerations include strict authorization checks to ensure only authorized administrators can access this endpoint. Responses exclude sensitive fields like token values or internal identifiers to maintain security. The implementation handles request ID validation and returns appropriate HTTP status codes for invalid IDs or unauthorized access.
 *
 * This operation directly maps to the econ_politic_board_admin_requests database table structure, utilizing fields such as id, request_type, status, user_id, admin_id, details, and created_at. The response structure accurately reflects the database schema fields with no assumed fields beyond those defined in the loaded schema.
 *
 * @param props.connection
 * @param props.requestId Unique identifier of the administrative request to retrieve
 * @x-autobe-specification Fetch admin request by requestId from econ_politic_board_admin_requests table. Include user display name via join with users table (without sensitive fields). Enforce admin authorization (handled by Endpoint agent). Include createdAt timestamp and request status. Return 404 for invalid requestId. Cache response for 5 minutes with requestId-based cache key.
 * @path /econPoliticBoard/admin/requests/:requestId
 * @accessor api.functional.econPoliticBoard.admin.requests.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the administrative request to retrieve
     */
    requestId: string & tags.Format<"uuid">;
  };
  export type Response = IEconPoliticBoardAdminRequest;

  export const METADATA = {
    method: "GET",
    path: "/econPoliticBoard/admin/requests/:requestId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/econPoliticBoard/admin/requests/${encodeURIComponent(props.requestId ?? "null")}`;
  export const random = (): IEconPoliticBoardAdminRequest =>
    typia.random<IEconPoliticBoardAdminRequest>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update the status of an administrative user request (e.g., approve or reject a user's request to become an administrator).
 *
 * This endpoint is used by administrators to process requests submitted by users who want to become administrators. When a user submits a request to become an administrator, the system creates a record in a request table with status 'pending'. Administrators can then use this endpoint to update the status to 'approved' or 'rejected' and optionally provide a reason for their decision.
 *
 * Security: The endpoint is restricted to users with administrative privileges (admin or super admin). The endpoint returns the updated request object, including the new status and adminReason. If the request ID doesn't exist or the user's permissions are insufficient, the system returns a 404 or 403 error respectively.
 *
 * This operation directly relates to the administrative request workflow described in section 4.6.1 of the requirements document ("WHEN a user submits a request to become an administrator... WHEN approved, THE system SHALL grant regular administrator permissions to the user.")
 *
 * @param props.connection
 * @param props.requestId Unique identifier of the request to update
 * @param props.body Details for updating the administrative request status and reason
 * @x-autobe-specification Update an administrative request (e.g., approving or rejecting a user's request to become an administrator). The implementation updates the status and adminReason fields in the econ_politic_board_admin_requests table. The endpoint validates that the request ID exists, the status is one of 'pending', 'approved', or 'rejected', and the adminReason is provided when status is 'approved' or 'rejected'. If the user making the request does not have sufficient permissions, a 403 error is returned. This is a critical operation that requires administrative privileges (admin or super admin).
 * @path /econPoliticBoard/admin/requests/:requestId
 * @accessor api.functional.econPoliticBoard.admin.requests.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Unique identifier of the request to update
     */
    requestId: string & tags.Format<"uuid">;

    /**
     * Details for updating the administrative request status and reason
     */
    body: IEconPoliticBoardAdminRequest.IUpdate;
  };
  export type Body = IEconPoliticBoardAdminRequest.IUpdate;
  export type Response = IEconPoliticBoardAdminRequest;

  export const METADATA = {
    method: "PUT",
    path: "/econPoliticBoard/admin/requests/:requestId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/econPoliticBoard/admin/requests/${encodeURIComponent(props.requestId ?? "null")}`;
  export const random = (): IEconPoliticBoardAdminRequest =>
    typia.random<IEconPoliticBoardAdminRequest>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Permanently removes the administrative request record from the system after processing either approval or rejection. This operation completes the administrative request lifecycle by deleting the request record in the 'econ_politic_board_admin_requests' table. The request may represent a user's application for administrator privileges or other administrative actions requiring approval.
 *
 * Security considerations: This operation requires administrator authentication and is only accessible through the administration interface. The requesting user must have sufficient permissions to manage administrative requests. The system validates that the request exists and is in a pending state before deletion.
 *
 * Business context: When administrators either approve or reject user requests for administrative privileges (covered in section 4.6.1 of requirements), they complete the process by deleting the request record. This operation serves as the final step to clear processed requests from the system while maintaining audit history of all actions.
 *
 * @param props.connection
 * @param props.requestId Unique identifier of the administrative request to be processed
 * @x-autobe-specification Hard delete the administrative request record from econ_politic_board_admin_requests table based on provided requestId. The operation requires the request to be in an active (pending) state. After deletion, the system marks the request as processed with no retention of the request record. The associated user account process status is updated in the corresponding member table. Audit log entry created with action 'REQUEST_DELETED'.
 * @path /econPoliticBoard/admin/requests/:requestId
 * @accessor api.functional.econPoliticBoard.admin.requests.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * Unique identifier of the administrative request to be processed
     */
    requestId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/econPoliticBoard/admin/requests/:requestId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/econPoliticBoard/admin/requests/${encodeURIComponent(props.requestId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
