import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IHrmTimeTrackRole } from "../../../../../api/structures/IHrmTimeTrackRole";
import { IHrmTimeTrackRolePermission } from "../../../../../api/structures/IHrmTimeTrackRolePermission";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { deleteHrmTimeTrackMemberRolesRoleIdPermissionsPermissionId } from "../../../../../providers/deleteHrmTimeTrackMemberRolesRoleIdPermissionsPermissionId";
import { getHrmTimeTrackMemberRolesRoleIdPermissionsPermissionId } from "../../../../../providers/getHrmTimeTrackMemberRolesRoleIdPermissionsPermissionId";
import { patchHrmTimeTrackMemberRolesRoleIdPermissions } from "../../../../../providers/patchHrmTimeTrackMemberRolesRoleIdPermissions";
import { postHrmTimeTrackMemberRolesRoleIdPermissions } from "../../../../../providers/postHrmTimeTrackMemberRolesRoleIdPermissions";

@Controller("/hrmTimeTrack/member/roles/:roleId/permissions")
export class HrmtimetrackMemberRolesPermissionsController {
  /**
   * Add one or more permissions to an existing role within an organization.
   *
   * This endpoint grants additional access rights to a role by creating permission entries in the role-permissions junction table. Each permission defines a specific capability such as organization management, employee management, project viewing, time tracking approval, or report access. The operation validates that the role exists, the requesting user has appropriate authorization to modify role permissions, and each permission code is valid. Duplicate permission assignments are ignored without error due to the unique constraint on role-permission pairs.
   *
   * Role permissions determine what actions employees assigned to that role can perform within the organization. Available permissions include organization_management, employee_management, employee_viewing, project_management, project_viewing, time_management, timesheet_approval, time_viewing_all, and report_viewing. The response includes the complete updated role with all its current permissions.
   *
   * @param connection
   * @param roleId UUID of the role to add permissions to. The role must exist within the organization and not be soft-deleted.
   * @param body Array of permission codes to add to the role. Each permission must be a valid permission code from the allowed list. Duplicate permissions in the array or permissions already assigned to the role are handled gracefully without error.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Validate the roleId path parameter is a valid
     *   UUID. Query hrm_time_track_roles table to find the role by id. Verify
     *   the role exists and is not soft-deleted (deleted_at is null). Check
     *   that the requesting user has permission to modify role permissions
     *   (typically requires organization_management or similar elevated
     *   permission). Validate each permission code in the request body against
     *   the allowed permission list: organization_management,
     *   employee_management, employee_viewing, project_management,
     *   project_viewing, time_management, timesheet_approval, time_viewing_all,
     *   report_viewing. For each valid permission, insert a new record into
     *   hrm_time_track_role_permissions with the role id, permission code, and
     *   current timestamp. Handle unique constraint violations gracefully by
     *   ignoring duplicate permission assignments (permission already exists
     *   for this role). After successful inserts, reload the role with all its
     *   permissions joined from hrm_time_track_role_permissions. Return the
     *   complete role object including the permissions array. Log the
     *   permission addition event in activity logs if audit tracking is
     *   enabled.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async addPermissions(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("roleId")
    roleId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IHrmTimeTrackRole.IAddPermission,
  ): Promise<IHrmTimeTrackRole> {
    try {
      return await postHrmTimeTrackMemberRolesRoleIdPermissions({
        member,
        roleId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update the permission set for a role within an organization.
   *
   * This operation replaces all existing permissions for the specified role with a new set of permissions. It is used by organization owners to modify custom role permissions when organizational needs change. Built-in roles (Owner, Manager, Employee) cannot have their permissions modified and will result in an error if an update is attempted. Custom roles must have at least one permission assigned; requests with empty permission sets are rejected.
   *
   * The operation performs the following validations: verifies the role exists and belongs to the requesting organization, ensures the role is not a built-in role, validates that at least one permission is provided, and confirms all requested permissions are from the allowed permission list. Upon success, all existing permissions for the role are removed and replaced with the new permission set.
   *
   * @param connection
   * @param roleId UUID identifier of the role whose permissions are being updated. This role must exist and belong to the current organization context.
   * @param body New set of permissions to assign to the role. This replaces all existing permissions. The array must contain at least one valid permission value. Valid permissions include: organization_management, employee_management, employee_viewing, project_management, project_viewing, time_management, timesheet_approval, time_viewing_all, and report_viewing.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification 1. Validate the roleId parameter is a valid UUID.
     *   2. Query hrm_time_track_roles table for the role with the given id. 3.
     *   Verify the role exists and belongs to the current organization context.
     *   4. Check if is_builtin is true - if so, reject the request with an
     *   error (built-in roles cannot be modified per Section 333). 5. Verify
     *   the role is not soft-deleted (deleted_at is null). 6. Validate the
     *   request body contains a non-empty array of permissions. 7. Validate
     *   each permission value against the allowed list:
     *   organization_management, employee_management, employee_viewing,
     *   project_management, project_viewing, time_management,
     *   timesheet_approval, time_viewing_all, report_viewing. 8. Begin a
     *   database transaction. 9. Delete all existing records from
     *   hrm_time_track_role_permissions where hrm_time_track_role_id matches
     *   the roleId. 10. Insert new permission records for each permission in
     *   the request body, with current timestamp for created_at. 11. Update the
     *   role's updated_at timestamp. 12. Commit the transaction. 13. Return the
     *   updated role object including the new permissions list.
   *
   * Error handling:
   * - Return 404 if role not found or belongs to different organization
   * - Return 403 or 400 if attempting to modify built-in role
   * - Return 400 if permission array is empty
   * - Return 400 if any permission value is invalid
   * - Return 500 for database transaction failures
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async update(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("roleId")
    roleId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IHrmTimeTrackRole.IUpdatePermission,
  ): Promise<IHrmTimeTrackRole> {
    try {
      return await patchHrmTimeTrackMemberRolesRoleIdPermissions({
        member,
        roleId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieves a specific permission assignment for a role.
   *
   * This operation returns the permission details for a given role and permission code combination, including the permission identifier, code, and grant timestamp. The permission assignment is uniquely identified by the role ID and permission code.
   *
   * Permission assignments define what actions are allowed for a role, including organization management, employee management, project management, time tracking, and reporting capabilities. Each permission entry is unique per role and cannot be duplicated.
   *
   * @param connection
   * @param roleId UUID of the role to retrieve the permission for (global scope).
   * @param permissionId Permission code identifying the specific permission (e.g., organization_management, employee_management).
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query the hrm_time_track_role_permissions table
     *   for a record matching the provided roleId and permissionId.
   *
   * 1. Validate that the roleId exists in hrm_time_track_roles and belongs to the requesting user's organization
   * 2. Query hrm_time_track_role_permissions where hrm_time_track_role_id = roleId AND permission = permissionId
   * 3. If no record found, return 404 Not Found
   * 4. Validate that the permission code is a valid permission value (organization_management, employee_management, employee_viewing, project_management, project_viewing, time_management, timesheet_approval, time_viewing_all, report_viewing)
   * 5. Return the permission record with id, hrm_time_track_role_id, permission, and created_at fields
   * 6. Ensure organization-level data isolation - only return permissions for roles within the authenticated user's organization
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":permissionId")
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("roleId")
    roleId: string & tags.Format<"uuid">,
    @TypedParam("permissionId")
    permissionId: string,
  ): Promise<IHrmTimeTrackRolePermission> {
    try {
      return await getHrmTimeTrackMemberRolesRoleIdPermissionsPermissionId({
        member,
        roleId,
        permissionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Remove a specific permission from a role within an organization.
   *
   * This operation deletes a permission assignment from a custom role, effectively revoking that permission from all employees assigned to the role. The permission can include organization management, employee management, project management, time management, timesheet approval, or other available permissions.
   *
   * Built-in roles (Owner, Manager, Employee) cannot have their permissions modified. Only custom roles created by organization owners can have permissions added or removed. The deletion is immediate and affects all employees with the affected role.
   *
   * The operation requires organization owner or employee management permissions to execute successfully.
   *
   * @param connection
   * @param roleId UUID of the role from which to remove the permission (scoped to organization)
   * @param permissionId UUID of the specific permission assignment to remove
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query hrm_time_track_roles table to verify the
     *   role exists and belongs to the authenticated user's organization. Check
     *   that the role is not a built-in role (is_builtin = false) - reject with
     *   403 Forbidden if it is built-in. Query hrm_time_track_role_permissions
     *   table to verify the permission assignment exists with the given roleId
     *   and permissionId. Delete the permission record from
     *   hrm_time_track_role_permissions table. Return 204 No Content on
     *   successful deletion. Return 404 Not Found if role or permission
     *   assignment does not exist. Return 403 Forbidden if attempting to modify
     *   a built-in role. Ensure proper transaction handling and cascade delete
     *   behavior.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":permissionId")
  public async erase(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("roleId")
    roleId: string & tags.Format<"uuid">,
    @TypedParam("permissionId")
    permissionId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteHrmTimeTrackMemberRolesRoleIdPermissionsPermissionId({
        member,
        roleId,
        permissionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
