import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IDiscussionBoardComment } from "../../../../structures/IDiscussionBoardComment";
import { IPageIDiscussionBoardComment } from "../../../../structures/IPageIDiscussionBoardComment";

/**
 * Retrieve a paginated list of comments for a specific article in chronological order.
 *
 * This operation returns all active comments associated with the specified article, sorted by creation timestamp in oldest-first order to maintain discussion thread continuity. Each comment includes the author's display name, comment content, and creation timestamp for display in the article's discussion section.
 *
 * Comments are single-level only with no nested replies supported. The response is paginated to handle articles with large numbers of comments efficiently. Only comments from non-deleted articles are accessible, and soft-deleted comments are automatically filtered from results.
 *
 * Guest users can view all comments on accessible articles. Member users can additionally create, edit, and delete their own comments through separate endpoints. Administrators have full moderation capabilities including deletion of any comment.
 *
 * @param props.connection
 * @param props.articleId Target article's ID (UUID format)
 * @param props.body Pagination and sorting parameters for comment list
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query discussion_board_comments table filtered by discussion_board_article_id matching the path parameter. Join with discussion_board_members to retrieve author display_name for each comment. Filter out soft-deleted comments (deleted_at IS NOT NULL). Order by created_at ASC for oldest-first chronological display. Apply pagination with cursor or offset-based strategy. Return summary DTO with essential comment fields optimized for list display. Ensure article exists and is not soft-deleted before returning comments.
 * @path /discussionBoard/articles/:articleId/comments
 * @accessor api.functional.discussionBoard.articles.comments.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Target article's ID (UUID format)
     */
    articleId: string & tags.Format<"uuid">;

    /**
     * Pagination and sorting parameters for comment list
     */
    body: IDiscussionBoardComment.IRequest;
  };
  export type Body = IDiscussionBoardComment.IRequest;
  export type Response = IPageIDiscussionBoardComment.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/discussionBoard/articles/:articleId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/discussionBoard/articles/${encodeURIComponent(props.articleId ?? "null")}/comments`;
  export const random = (): IPageIDiscussionBoardComment.ISummary =>
    typia.random<IPageIDiscussionBoardComment.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("articleId")(() => typia.assert(props.articleId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific comment on an article by its unique identifier.
 *
 * This operation returns detailed information about a single comment including the comment content, author information (display name), creation timestamp, and last update timestamp. The comment must belong to the specified article, ensuring proper contextual access.
 *
 * Comments are single-level discussion entries that allow users to provide feedback on articles. Each comment is authored by a registered member and displays the author's public display name. The comment content is required and subject to minimum and maximum length validation rules.
 *
 * This endpoint supports viewing individual comments in detail, which is useful when navigating directly to a specific comment or when comment-specific actions are needed. The response includes the complete comment record with all metadata from the discussion_board_comments table including the deleted_at timestamp for soft delete tracking.
 *
 * Authorization: Guests can view comments on accessible articles. Members can view all comments. Banned users' comments remain visible per platform policy. If the comment or article has been soft deleted (deleted_at timestamp is set), access is restricted to administrators only.
 *
 * Related operations: PATCH /discussionBoard/articles/{articleId}/comments retrieves the list of all comments on an article sorted oldest first. PUT /discussionBoard/articles/{articleId}/comments/{commentId} updates an existing comment. DELETE /discussionBoard/articles/{articleId}/comments/{commentId} removes a comment.
 *
 * @param props.connection
 * @param props.articleId Target article's ID (global scope)
 * @param props.commentId Target comment's ID (scoped to article)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query the discussion_board_comments table by comment ID with article context validation.
 *
 * 1. Validate that the articleId exists in discussion_board_articles table and is not soft deleted (deleted_at is null)
 * 2. Query discussion_board_comments where id equals commentId AND discussion_board_article_id equals articleId
 * 3. Join with discussion_board_members to retrieve author display_name
 * 4. Verify the comment is not soft deleted (deleted_at is null) unless requester is administrator
 * 5. Return the comment record with author information
 *
 * Handle edge cases:
 * - Article not found: return 404
 * - Comment not found: return 404
 * - Comment belongs to different article: return 404
 * - Article or comment soft deleted: return 404 for non-admin users
 * - Banned user accessing: allow read access to comments
 *
 * Use UUID format validation for both path parameters. Ensure the join with members table handles deleted author accounts gracefully (show anonymous indicator if member is deleted).
 * @path /discussionBoard/articles/:articleId/comments/:commentId
 * @accessor api.functional.discussionBoard.articles.comments.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Target article's ID (global scope)
     */
    articleId: string & tags.Format<"uuid">;

    /**
     * Target comment's ID (scoped to article)
     */
    commentId: string & tags.Format<"uuid">;
  };
  export type Response = IDiscussionBoardComment;

  export const METADATA = {
    method: "GET",
    path: "/discussionBoard/articles/:articleId/comments/:commentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/discussionBoard/articles/${encodeURIComponent(props.articleId ?? "null")}/comments/${encodeURIComponent(props.commentId ?? "null")}`;
  export const random = (): IDiscussionBoardComment =>
    typia.random<IDiscussionBoardComment>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("articleId")(() => typia.assert(props.articleId));
      assert.param("commentId")(() => typia.assert(props.commentId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
