import { tags } from "typia";

import { IDiscussionBoardUser } from "./IDiscussionBoardUser";

/**
 * Complete user session information including authentication tokens, connection metadata, and timestamps for session management and security auditing.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardUserSession = {
  /**
   * Unique session identifier
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.id. Primary key identifier.
   */
  id: string & tags.Format<"uuid">;

  /**
   * JWT access token for API authentication
   *
   * @x-autobe-database-schema-property access_token
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.access_token. JWT token for API authentication.
   */
  access_token: string;

  /**
   * JWT refresh token for token renewal
   *
   * @x-autobe-database-schema-property refresh_token
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.refresh_token. JWT token for token renewal.
   */
  refresh_token: string;

  /**
   * IP address of the connection for security auditing
   *
   * @x-autobe-database-schema-property ip
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.ip. IP address for security auditing.
   */
  ip: string & tags.Format<"ipv4">;

  /**
   * Browser or client user agent string
   *
   * @x-autobe-database-schema-property user_agent
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.user_agent. Browser or client identification string.
   */
  user_agent: string;

  /**
   * HTTP referrer header for connection context
   *
   * @x-autobe-database-schema-property referrer
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.referrer. HTTP referrer header for connection context.
   */
  referrer?: string | null | undefined;

  /**
   * Timestamp when the session was created
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.created_at. Session creation timestamp.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the session expires
   *
   * @x-autobe-database-schema-property expired_at
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.expired_at. Session expiration timestamp.
   */
  expired_at: string & tags.Format<"date-time">;

  /**
   * Timestamp of last session activity
   *
   * @x-autobe-database-schema-property last_accessed_at
   * @x-autobe-specification Direct mapping from discussion_board_user_sessions.last_accessed_at. Last session activity timestamp.
   */
  last_accessed_at: string & tags.Format<"date-time">;

  /**
   * User associated with this session
   *
   * @x-autobe-database-schema-property user
   * @x-autobe-specification Relation mapping from discussion_board_user_sessions.user via discussion_board_user_id foreign key. Returns IDiscussionBoardUser.ISummary.
   */
  user: IDiscussionBoardUser.ISummary;
};
export namespace IDiscussionBoardUserSession {
  /**
   * Search criteria for filtering user authentication sessions. Supports filtering by specific user, session status (active/expired), IP address ranges, and creation time windows. Includes pagination parameters for managing large result sets.
   */
  export type IRequest = {
    user_id?: (string & tags.Format<"uuid">) | null | undefined;
    ip?: string | undefined;
    active?: boolean | undefined;
    created_at_min?: (string & tags.Format<"date-time">) | undefined;
    created_at_max?: (string & tags.Format<"date-time">) | undefined;
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };

  /**
   * Lightweight summary of user authentication session for display in lists and search results. Provides essential session metadata including creation time, expiration time, and last activity timestamp, along with user context for session management purposes.
   */
  export type ISummary = {
    /**
     * @x-autobe-database-schema-property id
     */
    id: string & tags.Format<"uuid">;
    /**
     * @x-autobe-database-schema-property user
     */
    user: IDiscussionBoardUser.ISummary;
    /**
     * @x-autobe-database-schema-property created_at
     */
    created_at: string & tags.Format<"date-time">;
    /**
     * @x-autobe-database-schema-property expired_at
     */
    expired_at: string & tags.Format<"date-time">;
    /**
     * @x-autobe-database-schema-property last_accessed_at
     */
    last_accessed_at: string & tags.Format<"date-time">;
  };
}
