import { tags } from "typia";

import { IDiscussionBoardComment } from "./IDiscussionBoardComment";
import { IDiscussionBoardUser } from "./IDiscussionBoardUser";

/**
 * Complete user mention record representing @mentions within comment content. Contains character position information, creation timestamp, and relationship data linking to the containing comment and mentioned user. Used for notification systems and mention highlighting features.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardCommentMention = {
  /**
   * Unique identifier for the mention record.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.id column. UUID primary key automatically generated by database.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Starting character position of the user mention within the comment text.
   *
   * @x-autobe-database-schema-property position_start
   * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.position_start column. Represents the starting character index (0-based) of the mention within the comment content. Must be non-negative and less than position_end.
   */
  position_start: number & tags.Type<"int32"> & tags.Minimum<0>;

  /**
   * Ending character position of the user mention within the comment text.
   *
   * @x-autobe-database-schema-property position_end
   * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.position_end column. Represents the ending character index (exclusive) of the mention within the comment content. Must be greater than position_start and within comment length bounds.
   */
  position_end: number & tags.Type<"int32"> & tags.Minimum<0>;

  /**
   * Timestamp when the user mention was created.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.created_at column. System-generated timestamp when the mention record was created. Uses UTC timezone for consistency.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * The comment containing this user mention.
   *
   * @x-autobe-database-schema-property comment
   * @x-autobe-specification Relation mapping from discussion_board_comment_mentions.discussion_board_comment_id foreign key. JOIN discussion_board_comments ON discussion_board_comment_mentions.discussion_board_comment_id = discussion_board_comments.id. Returns IDiscussionBoardComment.ISummary DTO.
   */
  comment: IDiscussionBoardComment.ISummary;

  /**
   * The user who was mentioned in the comment.
   *
   * @x-autobe-database-schema-property mentionedUser
   * @x-autobe-specification Relation mapping from discussion_board_comment_mentions.discussion_board_user_id foreign key. JOIN discussion_board_users ON discussion_board_comment_mentions.discussion_board_user_id = discussion_board_users.id. Returns IDiscussionBoardUser.ISummary DTO.
   */
  mentioned_user: IDiscussionBoardUser.ISummary;
};
export namespace IDiscussionBoardCommentMention {
  /**
   * Summary representation of user mentions within comment content, showing mention position data and referenced user information for display in comment mention lists.
   */
  export type ISummary = {
    /**
     * Unique identifier for the comment mention record.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.id column. UUID primary key.
     */
    id: string & tags.Format<"uuid">;

    /**
     * The user who was mentioned in the comment, showing their public profile information.
     *
     * @x-autobe-database-schema-property mentionedUser
     * @x-autobe-specification JOIN from discussion_board_comment_mentions.discussion_board_user_id to discussion_board_users.id. Returns IDiscussionBoardUser.ISummary with display_name, bio, and timestamps.
     */
    mentionedUser: IDiscussionBoardUser.ISummary;

    /**
     * Starting character position of the mention within the comment text.
     *
     * @x-autobe-database-schema-property position_start
     * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.position_start column. Integer representing starting character position.
     */
    position_start: number & tags.Type<"int32">;

    /**
     * Ending character position of the mention within the comment text.
     *
     * @x-autobe-database-schema-property position_end
     * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.position_end column. Integer representing ending character position.
     */
    position_end: number & tags.Type<"int32">;

    /**
     * Timestamp when the user mention was recorded in the system.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from discussion_board_comment_mentions.created_at column. Timestamp when the mention was created.
     */
    created_at: string & tags.Format<"date-time">;
  };

  /**
   * Request parameters for searching and filtering comment mentions within a specific comment. Provides filtering capabilities by mentioned users, position ranges within comment text, and creation time ranges. Supports pagination and sorting for efficient result retrieval.
   */
  export type IRequest = {
    /**
     * Array of user IDs to filter mentions by specific mentioned users
     */
    mentioned_user_ids?: (string & tags.Format<"uuid">)[] | undefined;

    /**
     * Minimum starting position for mention filtering
     */
    position_start?:
      | (number & tags.Type<"int32"> & tags.Minimum<0>)
      | undefined;

    /**
     * Maximum ending position for mention filtering
     */
    position_end?: (number & tags.Type<"int32"> & tags.Minimum<0>) | undefined;

    /**
     * Earliest creation timestamp for mention filtering
     */
    created_at_start?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Latest creation timestamp for mention filtering
     */
    created_at_end?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Page number for pagination
     */
    page?:
      | (number & tags.Type<"int32"> & tags.Default<1> & tags.Minimum<1>)
      | undefined;

    /**
     * Number of results per page
     */
    limit?:
      | (number &
          tags.Type<"int32"> &
          tags.Default<20> &
          tags.Minimum<1> &
          tags.Maximum<100>)
      | undefined;

    /**
     * Field to sort results by
     */
    sort_by?: "created_at" | "position_start" | undefined;

    /**
     * Sort order for results
     */
    sort_order?: "asc" | "desc" | undefined;
  };

  /**
   * Request body for creating a user mention within a comment. Specifies the mentioned user and the character position range within the comment text.
   */
  export type ICreate = {
    discussion_board_user_id: string & tags.Format<"uuid">;
    position_start: number & tags.Type<"int32"> & tags.Minimum<0>;
    position_end: number & tags.Type<"int32"> & tags.Minimum<0>;
  };
}
