import { tags } from "typia";

import { IDiscussionBoardAdmin } from "./IDiscussionBoardAdmin";

/**
 * Analytics data representing administrator workload distribution and efficiency metrics for moderation queue assignments. Provides insights into individual administrator performance including assignment volume, processing efficiency, and workload distribution across the moderation team.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardAdministratorDistributionStatistic = {
  /**
   * Administrator profile information for workload attribution.
   *
   * @x-autobe-specification JOIN from discussion_board_content_moderation_queues.assigned_admin_id to discussion_board_admins.id. Returns ISummary view for administrator identification.
   */
  administrator: IDiscussionBoardAdmin.ISummary;

  /**
   * Total number of resolved moderation assignments handled by this administrator.
   *
   * @x-autobe-specification COUNT(*) aggregation from discussion_board_content_moderation_queues WHERE assigned_admin_id IS NOT NULL AND resolved_at IS NOT NULL GROUP BY assigned_admin_id
   */
  assignment_count: number & tags.Type<"int32">;

  /**
   * Normalized efficiency score where higher values indicate faster resolution times.
   *
   * @x-autobe-specification Calculated as (1 / average_processing_time_seconds) * 1000 to normalize efficiency metric for comparative analysis across administrators
   */
  efficiency_score: number;

  /**
   * Average processing time in seconds for resolving moderation assignments.
   *
   * @x-autobe-specification AVG(EXTRACT(EPOCH FROM (resolved_at - assigned_at))) from discussion_board_content_moderation_queues WHERE assigned_admin_id IS NOT NULL AND resolved_at IS NOT NULL
   */
  average_processing_time_seconds: number;
};
export namespace IDiscussionBoardAdministratorDistributionStatistic {
  /**
   * Administrator workload distribution statistics showing assignment counts and efficiency metrics for moderation queue performance analysis. Used for administrative dashboard analytics and performance monitoring.
   */
  export type IPagination = {
    /**
     * Unique identifier of the administrator for whom statistics are calculated
     *
     * @x-autobe-specification References administrator.id from discussion_board_administrators table for administrator identification in aggregation queries. Used to link statistics to specific administrator entities.
     */
    administrator_id: string & tags.Format<"uuid">;

    /**
     * Total number of moderation queue assignments received by the administrator
     *
     * @x-autobe-specification COUNT(*) aggregation from discussion_board_content_moderation_queue_assignments table grouped by administrator_id. Represents total number of moderation tasks assigned to this administrator regardless of status.
     */
    total_assignments: number & tags.Type<"int32"> & tags.Minimum<0>;

    /**
     * Number of moderation assignments completed or resolved by the administrator
     *
     * @x-autobe-specification COUNT(*) aggregation from discussion_board_content_moderation_queue_assignments table WHERE status IN ('resolved', 'completed', 'closed') grouped by administrator_id. Represents successfully processed moderation tasks.
     */
    completed_assignments: number & tags.Type<"int32"> & tags.Minimum<0>;

    /**
     * Efficiency ratio showing percentage of completed assignments (0.0 to 1.0 scale)
     *
     * @x-autobe-specification Calculated as completed_assignments / total_assignments ratio. Returns 0 when total_assignments is 0 to prevent division by zero. Represents the administrator's completion rate for assigned moderation tasks.
     */
    efficiency_score: number & tags.Minimum<0> & tags.Maximum<1>;
  };
}
