import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallSellerPayout } from "../../../../structures/IShoppingMallSellerPayout";
import { IPageIShoppingMallSellerPayout } from "../../../../structures/IPageIShoppingMallSellerPayout";

/**
 * Retrieve paginated list of seller payout records for earnings settlement
 * tracking.
 *
 * Retrieve a filtered and paginated list of seller payout records from the
 * shopping mall platform. This operation provides advanced search capabilities
 * for finding seller payouts based on multiple criteria including payout
 * status, settlement period, payout amounts, processing dates, seller
 * identification, and payment method information.
 *
 * The operation supports comprehensive pagination with configurable page sizes
 * and flexible sorting options. Users can sort payouts by settlement date,
 * payout amount, processing status, seller name, or other relevant fields in
 * ascending or descending order. This functionality is essential for sellers
 * tracking their earnings and for platform administrators managing the payout
 * workflow.
 *
 * Security and authorization are carefully managed in this operation. Sellers
 * can only view their own payout records, while platform administrators have
 * access to all seller payouts for financial reconciliation and dispute
 * resolution. The operation implements proper filtering based on the
 * authenticated user's actor type to ensure data privacy and security.
 *
 * This operation integrates with the shopping_mall_seller_payouts table as
 * defined in the Prisma schema, incorporating all payout-related fields
 * including gross revenue, platform commission deductions, net payout amounts,
 * payment processing fees, settlement periods, and payout status tracking. The
 * response provides sellers with complete visibility into their earnings
 * settlement process.
 *
 * Typical use cases include sellers monitoring their monthly earnings
 * settlements, tracking pending payouts, reviewing historical payout records,
 * and reconciling revenue against sales performance. Administrators use this
 * operation for financial reporting, payout batch processing verification, and
 * resolving seller payout inquiries.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for filtering
 *   seller payouts by status, settlement period, amount range, seller
 *   identification, and payment processing details
 * @path /shoppingMall/seller/sellerPayouts
 * @accessor api.functional.shoppingMall.seller.sellerPayouts.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for filtering seller
     * payouts by status, settlement period, amount range, seller
     * identification, and payment processing details
     */
    body: IShoppingMallSellerPayout.IRequest;
  };
  export type Body = IShoppingMallSellerPayout.IRequest;
  export type Response = IPageIShoppingMallSellerPayout.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/sellerPayouts",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/seller/sellerPayouts";
  export const random = (): IPageIShoppingMallSellerPayout.ISummary =>
    typia.random<IPageIShoppingMallSellerPayout.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information for a specific seller payout transaction.
 *
 * Retrieve comprehensive details about a specific seller payout transaction
 * from the shopping mall platform. This operation provides complete information
 * about a payout including the payout amount, current status, creation and
 * processing timestamps, and the associated seller account.
 *
 * This endpoint is essential for sellers to track their earnings settlements
 * and for platform administrators to audit payout transactions. The payout
 * information includes all relevant financial details and status tracking
 * necessary for accounting and reconciliation purposes.
 *
 * Security considerations: Only authenticated sellers can access their own
 * payout records, while administrators have access to all payout transactions
 * for platform oversight and financial auditing. The operation implements
 * proper authorization checks to ensure sellers can only view their own payout
 * history.
 *
 * This operation integrates with the shopping_mall_seller_payouts table as
 * defined in the Prisma schema, returning complete payout record details
 * including all financial and status information for the specified payout
 * transaction.
 *
 * @param props.connection
 * @param props.payoutId Unique identifier of the target seller payout
 *   transaction
 * @path /shoppingMall/seller/sellerPayouts/:payoutId
 * @accessor api.functional.shoppingMall.seller.sellerPayouts.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the target seller payout transaction */
    payoutId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallSellerPayout;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/seller/sellerPayouts/:payoutId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/seller/sellerPayouts/${encodeURIComponent(props.payoutId ?? "null")}`;
  export const random = (): IShoppingMallSellerPayout =>
    typia.random<IShoppingMallSellerPayout>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("payoutId")(() => typia.assert(props.payoutId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
