import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IRedditComment } from "../../../../../structures/IRedditComment";
import { IRedditCommentVote } from "../../../../../structures/IRedditCommentVote";

/**
 * Allow users to cast votes on comments with immediate score updates.
 *
 * This endpoint enables authenticated users to upvote, downvote, or remove their existing vote on comments they did not author. Each user may only vote once per comment, with vote changes counted as new votes. Vote actions are immediately reflected in the comment's score, which is recalculated as the difference between upvotes and downvotes.
 *
 * The system rejects votes on comments by the same author, enforcing an important voting integrity rule. When a vote is received, the system immediately updates the score and returns the full comment object with the current score for display.
 *
 * This operation is part of the core comment interaction system, working with the /comments/{id} endpoint to provide real-time voting updates throughout the application.
 *
 * @param props.connection
 * @param props.commentId Unique identifier of the comment to vote on (UUID)
 * @param props.body Vote action (up/down/remove) to cast on the comment
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Validate user is authenticated and not the comment author. Check existing vote in reddit_comment_votes. Insert or update vote record based on vote type (up/down/remove). Recalculate comment score from reddit_comment_votes. Update score in reddit_comments table. Return updated IRedditComment with current score.
 * @path /reddit/member/comments/:commentId/votes
 * @accessor api.functional.reddit.member.comments.votes.postByCommentid
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function postByCommentid(
  connection: IConnection,
  props: postByCommentid.Props,
): Promise<postByCommentid.Response> {
  return true === connection.simulate
    ? postByCommentid.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...postByCommentid.METADATA,
          path: postByCommentid.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace postByCommentid {
  export type Props = {
    /**
     * Unique identifier of the comment to vote on (UUID)
     */
    commentId: string & tags.Format<"uuid">;

    /**
     * Vote action (up/down/remove) to cast on the comment
     */
    body: IRedditComment.IVote;
  };
  export type Body = IRedditComment.IVote;
  export type Response = IRedditComment;

  export const METADATA = {
    method: "POST",
    path: "/reddit/member/comments/:commentId/votes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/reddit/member/comments/${encodeURIComponent(props.commentId ?? "null")}/votes`;
  export const random = (): IRedditComment => typia.random<IRedditComment>();
  export const simulate = (
    connection: IConnection,
    props: postByCommentid.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: postByCommentid.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("commentId")(() => typia.assert(props.commentId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Record a vote for a comment as either an upvote, downvote, or removal of a previous vote. The system calculates the vote score (upvotes - downvotes) immediately upon vote processing. For "remove", the vote is soft-deleted (marked as deleted) rather than physically removed, preserving voting history. Votes are restricted to logged-in members only. The operation returns the updated comment with the new vote score reflected.
 *
 * Security considerations: Requires authenticated member user. Each user may only have one vote (up/down) per comment, with "remove" to undo previous votes.
 *
 * Related operations: To fetch comment details including vote score, use GET /comments/{commentId}.
 *
 * @param props.connection
 * @param props.commentId The unique identifier of the comment being voted on
 * @param props.body Vote direction to apply (up, down, or remove)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Processes the vote transaction for a comment. Handles vote insertion, update, or removal by creating/updating/deleting the reddit_comment_votes record. Validates user authentication (requires member), ensures one vote per user per comment, updates the comment vote score, and triggers real-time score updates. Handles the vote direction "remove" by soft-deleting the vote record.
 * @path /reddit/member/comments/:commentId/votes
 * @accessor api.functional.reddit.member.comments.votes.patchByCommentid
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function patchByCommentid(
  connection: IConnection,
  props: patchByCommentid.Props,
): Promise<patchByCommentid.Response> {
  return true === connection.simulate
    ? patchByCommentid.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...patchByCommentid.METADATA,
          path: patchByCommentid.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace patchByCommentid {
  export type Props = {
    /**
     * The unique identifier of the comment being voted on
     */
    commentId: string & tags.Format<"uuid">;

    /**
     * Vote direction to apply (up, down, or remove)
     */
    body: IRedditComment.IVote;
  };
  export type Body = IRedditComment.IVote;
  export type Response = IRedditComment.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/reddit/member/comments/:commentId/votes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/reddit/member/comments/${encodeURIComponent(props.commentId ?? "null")}/votes`;
  export const random = (): IRedditComment.ISummary =>
    typia.random<IRedditComment.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: patchByCommentid.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: patchByCommentid.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("commentId")(() => typia.assert(props.commentId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve the detailed information about a specific vote on a comment, including the vote type, voter, timestamp, and associated comment. This endpoint is used to view the specific voting details as recorded in the system.
 *
 * @param props.connection
 * @param props.commentId ID of the comment the vote belongs to
 * @param props.voteId ID of the specific vote record
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Fetch the vote record from reddit_comment_votes table using voteId. Include associated user name from reddit_members table. The response should include: vote type (up/down), user ID, created timestamp, and related comment ID. Ensure access control allows authorized users to view their own vote history.
 * @path /reddit/member/comments/:commentId/votes/:voteId
 * @accessor api.functional.reddit.member.comments.votes.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * ID of the comment the vote belongs to
     */
    commentId: string & tags.Format<"uuid">;

    /**
     * ID of the specific vote record
     */
    voteId: string & tags.Format<"uuid">;
  };
  export type Response = IRedditComment.IVote;

  export const METADATA = {
    method: "GET",
    path: "/reddit/member/comments/:commentId/votes/:voteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/reddit/member/comments/${encodeURIComponent(props.commentId ?? "null")}/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): IRedditComment.IVote =>
    typia.random<IRedditComment.IVote>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("commentId")(() => typia.assert(props.commentId));
      assert.param("voteId")(() => typia.assert(props.voteId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Modify a user's vote on a comment.
 *
 * This operation allows a logged-in user to change their existing vote on a comment. Users may update their vote from upvote to downvote, downvote to upvote, or remove their vote entirely. The operation immediately updates the comment's score and the author's karma.
 *
 * Only the user who cast the original vote may modify their vote. The endpoint requires authentication to prevent unauthorized vote changes. After a successful update:
 * - The comment's vote score is recalculated instantly
 * - The author's karma is adjusted based on the new vote direction
 * - The system tracks the change as part of the comment's audit trail
 *
 * The response returns the fully populated comment with the updated score, allowing the client to reflect the change immediately without additional requests.
 *
 * **Important Notes**:
 * - Votes on own comments are prohibited by system rules
 * - Removal of vote performs soft delete on vote record
 * - This operation updates the system state without requiring confirmations
 *
 * @param props.connection
 * @param props.commentId UUID of the comment being voted on (matches database uniqueId field)
 * @param props.voteId UUID of the vote record being modified (unique identifier in the votes table)
 * @param props.body New vote direction for the comment (up, down, or remove)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification 1. Verify request user owns the vote record using reddit_comment_votes.userId = currentUserId
 * 2. Validate voteId exists in reddit_comment_votes
 * 3. Check commentId matches the vote's commentId
 * 4. Update vote value to new direction (up/down/remove)
 * 5. If vote is 'remove', delete the vote record
 * 6. Recalculate comment score in reddit_comments: score = upVotes - downVotes
 * 7. Update author's karma in reddit_profiles using karma update rule (delta = newVoteValue - oldVoteValue)
 * 8. Return the updated reddit_comments record with new score
 * @path /reddit/member/comments/:commentId/votes/:voteId
 * @accessor api.functional.reddit.member.comments.votes.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * UUID of the comment being voted on (matches database uniqueId field)
     */
    commentId: string & tags.Format<"uuid">;

    /**
     * UUID of the vote record being modified (unique identifier in the votes table)
     */
    voteId: string & tags.Format<"uuid">;

    /**
     * New vote direction for the comment (up, down, or remove)
     */
    body: IRedditCommentVote.IUpdate;
  };
  export type Body = IRedditCommentVote.IUpdate;
  export type Response = IRedditComment;

  export const METADATA = {
    method: "PUT",
    path: "/reddit/member/comments/:commentId/votes/:voteId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/reddit/member/comments/${encodeURIComponent(props.commentId ?? "null")}/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): IRedditComment => typia.random<IRedditComment>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("commentId")(() => typia.assert(props.commentId));
      assert.param("voteId")(() => typia.assert(props.voteId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Removes a specific vote from a comment. This operation requires the user to be authenticated and to have proper permissions for the vote (either as the original voter or a community moderator). The vote being removed must belong to the current user or the user must be a moderator of the community.
 *
 * The operation performs immediate adjustments to the comment's vote score and the author's karma:
 * - If removing an upvote, the author's karma decreases by 1
 * - If removing a downvote, the author's karma increases by 1
 *
 * The response returns the updated comment vote score after the removal, providing real-time feedback to the user.
 *
 * This endpoint follows the business requirement that vote changes must be handled immediately with appropriate score and karma adjustments.
 *
 * @param props.connection
 * @param props.commentId The unique identifier of the comment to remove the vote from
 * @param props.voteId The unique identifier of the specific vote to be removed
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification 1. Validate the commentId and voteId parameters as UUIDs
 * 2. Check that the vote exists in reddit_comment_votes with the specified voteId
 * 3. Verify the vote's commentId matches the requested commentId
 * 4. Determine user's permissions:
 *    - Check if current user is the owner of the vote (userId matches)
 *    - OR check if user is a moderator in the community of the comment
 * 5. Determine the vote direction (up or down) from vote record
 * 6. Calculate the new comment score:
 *    - For upvote removal: newScore = currentScore - 1
 *    - For downvote removal: newScore = currentScore + 1
 * 7. Update the comment's score in reddit_comments table
 * 8. Adjust the author's karma in reddit_profiles:
 *    - Upvote removal: authorKarma -= 1
 *    - Downvote removal: authorKarma += 1
 * 9. Remove the vote record from reddit_comment_votes
 * 10. Return the new comment score as the response body.
 *
 * Edge cases:
 * - If vote does not exist, return 404
 * - If user has no permission, return 403
 * - If database operation fails, return 500
 * @path /reddit/member/comments/:commentId/votes/:voteId
 * @accessor api.functional.reddit.member.comments.votes.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * The unique identifier of the comment to remove the vote from
     */
    commentId: string & tags.Format<"uuid">;

    /**
     * The unique identifier of the specific vote to be removed
     */
    voteId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/reddit/member/comments/:commentId/votes/:voteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/reddit/member/comments/${encodeURIComponent(props.commentId ?? "null")}/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("commentId")(() => typia.assert(props.commentId));
      assert.param("voteId")(() => typia.assert(props.voteId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
