import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IEcommerceMallProductVariant } from "../../../../../structures/IEcommerceMallProductVariant";

/**
 * Create a new product variant for an existing product.
 *
 * This operation allows sellers to add a new variant (specific option combination) to their product catalog. Each variant represents a unique product configuration with its own SKU code, stock quantity, and optionally a price override from the product's base price.
 *
 * Security & Authorization:
 * - Only the product's owning seller can create variants
 * - Seller must have approved account status
 * - Product must exist and be accessible by the seller
 *
 * Business Rules:
 * - SKU code must be unique within the product (not globally unique)
 * - At least one variant is required for a product to be purchasable
 * - Option values must be provided as JSON to describe the variant configuration (e.g., {"size":"Large","color":"Red"})
 * - Stock quantity must be a positive integer
 * - If price_override is null, the product's base_price is used
 *
 * Validation:
 * - SKU code uniqueness is validated before variant creation
 * - Stock quantity must be ≥ 0
 * - Product must exist and belong to the authenticated seller
 *
 * Related Operations:
 * - GET /products/{productId} - View product details before adding variants
 * - PATCH /products/{productId}/variants/{variantId} - Update variant after creation
 * - GET /products/{productId}/variants - List all variants for a product
 * - DELETE /products/{productId}/variants/{variantId} - Delete a variant (if not the last one)
 *
 * @param props.connection
 * @param props.productId The unique identifier of the parent product
 * @param props.body Variant creation data including SKU code, option values, stock quantity, and optional price override
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification 1. Authenticate the request and verify the user has seller role
 * 2. Load the product by productId from ecommerce_mall_products table
 * 3. Verify the product exists and seller_id matches the authenticated seller's id
 * 4. Validate that the product is not soft-deleted (deleted_at is null)
 * 5. Validate request body:
 *    - sku_code: required, max 50 characters, unique within this product
 *    - option_values: required, valid JSON object
 *    - stock_quantity: required, integer ≥ 0
 *    - price_override: optional, float (null allowed)
 * 6. Check for SKU code conflict within the product (@@unique([sku_code]))
 * 7. If this is the first variant, verify the product can accept variants
 * 8. Insert new record into ecommerce_mall_product_variants with:
 *    - id: generated UUID
 *    - product_id: from path parameter
 *    - sku_code: from request body
 *    - option_values: JSON string from request body
 *    - price_override: from request body or null
 *    - stock_quantity: from request body
 *    - is_active: true (default)
 *    - created_at: current timestamp
 *    - updated_at: current timestamp
 * 9. Return the complete created variant with all fields
 * @path /ecommerceMall/seller/products/:productId/variants
 * @accessor api.functional.ecommerceMall.seller.products.variants.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * The unique identifier of the parent product
     */
    productId: string & tags.Format<"uuid">;

    /**
     * Variant creation data including SKU code, option values, stock quantity, and optional price override
     */
    body: IEcommerceMallProductVariant.ICreate;
  };
  export type Body = IEcommerceMallProductVariant.ICreate;
  export type Response = IEcommerceMallProductVariant;

  export const METADATA = {
    method: "POST",
    path: "/ecommerceMall/seller/products/:productId/variants",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/ecommerceMall/seller/products/${encodeURIComponent(props.productId ?? "null")}/variants`;
  export const random = (): IEcommerceMallProductVariant =>
    typia.random<IEcommerceMallProductVariant>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing product variant with new option values, SKU code, price override, or stock quantity.
 *
 * This operation allows sellers to modify their product variants to reflect changes in product specifications, pricing, or inventory levels. The variant must belong to the authenticated seller's product and will be validated against business rules before any changes are applied.
 *
 * The update operation performs comprehensive validation including SKU uniqueness within the product's variant set, verification that at least one variant remains active after the update, and stock quantity constraints. Snapshot records are created to preserve the before and after state for dispute resolution and audit trails.
 *
 * The operation supports partial updates - only the fields included in the request body will be modified. All updates are logged to the product variant snapshot table for audit trail purposes.
 *
 * **Important**: This operation does not modify the variant's `deleted_at` field. Variants are marked as soft-deleted through a separate deletion operation. When a variant has `deleted_at` set, it is considered deleted but preserved for historical reference.
 *
 * @param props.connection
 * @param props.productId Parent product's UUID
 * @param props.variantId Variant's UUID
 * @param props.body Fields to update for the product variant. Only include fields that need to be modified.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification 1. Verify seller authorization - authenticated seller must own the parent product
 * 2. Fetch variant from database matching product_id and variant_id
 * 3. Validate variant exists and is not already deleted (deleted_at is null)
 * 4. Validate SKU uniqueness - new SKU must not exist in other variants of the same product (allow current SKU if unchanged)
 * 5. Apply only provided fields from request body (partial update)
 * 6. If stock_quantity is being updated to 0 and this is the last active variant, reject with error
 * 7. Ensure stock_quantity >= 0
 * 8. Validate option_values JSON structure if provided
 * 9. Update variant record with new values and updated_at timestamp
 * 10. Create snapshot record for audit trail with oldValues and newValues
 * 11. Return updated variant with all fields including timestamps
 * 12. Handle constraint violations with appropriate HTTP status codes (400, 404, 409)
 * @path /ecommerceMall/seller/products/:productId/variants/:variantId
 * @accessor api.functional.ecommerceMall.seller.products.variants.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Parent product's UUID
     */
    productId: string & tags.Format<"uuid">;

    /**
     * Variant's UUID
     */
    variantId: string & tags.Format<"uuid">;

    /**
     * Fields to update for the product variant. Only include fields that need to be modified.
     */
    body: IEcommerceMallProductVariant.IUpdate;
  };
  export type Body = IEcommerceMallProductVariant.IUpdate;
  export type Response = IEcommerceMallProductVariant;

  export const METADATA = {
    method: "PUT",
    path: "/ecommerceMall/seller/products/:productId/variants/:variantId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/ecommerceMall/seller/products/${encodeURIComponent(props.productId ?? "null")}/variants/${encodeURIComponent(props.variantId ?? "null")}`;
  export const random = (): IEcommerceMallProductVariant =>
    typia.random<IEcommerceMallProductVariant>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.param("variantId")(() => typia.assert(props.variantId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
