import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IECommerceMallProduct } from "../../../../../api/structures/IECommerceMallProduct";
import { SellerAuth } from "../../../../../decorators/SellerAuth";
import { SellerPayload } from "../../../../../decorators/payload/SellerPayload";
import { getECommerceMallSellerProductsProductIdRatings } from "../../../../../providers/getECommerceMallSellerProductsProductIdRatings";

@Controller("/eCommerceMall/seller/products/:productId/ratings")
export class EcommercemallSellerProductsRatingsController {
  /**
   * Retrieve the aggregated rating summary for a specific product.
   *
   * The rating summary provides the average star rating (calculated from all non-deleted reviews) and the total count of reviews for the product. The average rating is rounded to one decimal place. This endpoint is used to display rating information on product listing pages, category browsing pages, search result pages, and the product detail page.
   *
   * When a product has no non-deleted reviews, the average rating returns 0 and the review count returns 0.
   *
   * @param connection
   * @param productId The unique identifier of the product to retrieve ratings for.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor seller
     * @x-autobe-specification Query the e_commerce_mall_reviews table filtered
     *   by product_id and where deleted_at IS NULL.
   *
   * Calculate average rating: SELECT AVG(rating) FROM e_commerce_mall_reviews WHERE e_commerce_mall_product_id = {productId} AND deleted_at IS NULL.
   *
   * Calculate total review count: SELECT COUNT(*) FROM e_commerce_mall_reviews WHERE e_commerce_mall_product_id = {productId} AND deleted_at IS NULL.
   *
   * Round the average to one decimal place. If no non-deleted reviews exist, return average_rating = 0 and total_count = 0.
   *
   * Validate that the product exists (query e_commerce_mall_products by id). If product not found, return 404.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
  ): Promise<IECommerceMallProduct.IRating> {
    try {
      return await getECommerceMallSellerProductsProductIdRatings({
        seller,
        productId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
