import { tags } from "typia";

/**
 * Individual product snapshot image record storing URL and display order.
 *
 * Contains the URL of the image and its display order for sorting within the product snapshot gallery. Images are ordered by display_order ascending (lower values appear first).
 *
 * Use Cases: Displaying historical product images in snapshot views for dispute resolution, showing what product images looked like at the time of snapshot creation.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEcommerceMallProductSnapshotImage = {
  /**
   * Timestamp when the image record was created.
   *
   * ISO 8601 formatted datetime indicating when this specific image was captured in the snapshot.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from ecommerce_mall_product_snapshot_images.created_at. ISO 8601 formatted datetime.
   */
  createdAt: string & tags.Format<"date-time">;

  /**
   * Display order of the image for sorting.
   *
   * Lower values appear first in the image gallery. Used to maintain the intended image sequence when displaying product snapshot images.
   *
   * @x-autobe-database-schema-property display_order
   * @x-autobe-specification Direct mapping from ecommerce_mall_product_snapshot_images.display_order. Integer value where lower numbers appear first in sorting.
   */
  displayOrder: number & tags.Type<"int32">;

  /**
   * Unique identifier of the product snapshot image.
   *
   * Auto-generated UUID primary key that uniquely identifies this image record within the snapshot.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from ecommerce_mall_product_snapshot_images.id. Auto-generated UUID primary key.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Timestamp when the image record was last updated.
   *
   * ISO 8601 formatted datetime indicating the last modification time of this image record.
   *
   * @x-autobe-database-schema-property updated_at
   * @x-autobe-specification Direct mapping from ecommerce_mall_product_snapshot_images.updated_at. ISO 8601 formatted datetime.
   */
  updatedAt: string & tags.Format<"date-time">;

  /**
   * URL of the image in the product snapshot.
   *
   * The full URL pointing to the image resource as it appeared at snapshot creation time. Used for displaying the historical product image.
   *
   * @x-autobe-specification Direct mapping from ecommerce_mall_product_snapshot_images.url. URI format.
   * @x-autobe-database-schema-property url
   */
  url: string & tags.Format<"uri">;
};
