/**
 * Individual option key-value pair for a product variant during checkout display.
 *
 * Represents a single selectable attribute such as color, size, or any product-specific option. Each option consists of a key (the attribute name) and a value (the selected option).
 *
 * Use Cases:
 * - Displayed as variant options in cart items and checkout
 * - Shown during order preview and confirmation
 * - Used to identify specific variant combinations (e.g., Color: Red, Size: Large)
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEcommerceMallCheckoutItemVariantOption = {
  /**
   * Option key name identifying the attribute type.
   *
   * Specifies the name of the option attribute (e.g., 'color', 'size', 'material'). This is the label used when displaying the option to customers in cart and checkout interfaces.
   *
   * @x-autobe-specification Maps to ecommerce_mall_product_variant_option_values.key column. The option key name such as 'color', 'size', or any attribute identifier. Direct scalar mapping from the 'key' column in the normalized option values table.
   */
  key: string;

  /**
   * Option value representing the selected attribute.
   *
   * Contains the actual value chosen for this option key (e.g., 'Red' for color, 'Large' for size). Displayed alongside the key in cart and checkout to show the specific variant selection.
   *
   * @x-autobe-specification Maps to ecommerce_mall_product_variant_option_values.value column. The option value such as 'Red', 'Large', or corresponding attribute value. Direct scalar mapping from the 'value' column in the normalized option values table.
   */
  value: string;
};
