import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallCancellationRequest } from "../../../../../structures/IPageIShoppingMallCancellationRequest";
import { IShoppingMallCancellationRequest } from "../../../../../structures/IShoppingMallCancellationRequest";

export * as snapshots from "./snapshots/index";

/**
 * Retrieve a filtered and paginated list of cancellation requests for a specific order item.
 *
 * This operation provides access to cancellation requests associated with a particular order item. Customers can view their own cancellation requests, while sellers can view requests for order items belonging to their products. The endpoint supports filtering by cancellation status (pending, approved, rejected) and includes pagination for efficient data retrieval.
 *
 * Each cancellation request includes the customer's reason for cancellation, current status, and timestamps. The response is optimized for list displays with summary information suitable for UI rendering.
 *
 * @param props.connection
 * @param props.orderItemId Order item UUID (scoped to specific order)
 * @param props.body Filter criteria and pagination parameters for cancellation request search
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Query shopping_mall_cancellation_requests table filtered by shopping_mall_order_item_id path parameter.
 *
 * Apply status filter from request body if provided (pending, approved, or rejected).
 * Join with shopping_mall_customers to include customer information in response.
 * Implement cursor-based pagination with configurable page size.
 *
 * Authorization: Customer can only access their own cancellation requests. Seller can access requests for order items belonging to their products.
 *
 * Return 404 if order item does not exist. Return empty array if no cancellation requests match the criteria.
 * @path /shoppingMall/seller/order-items/:orderItemId/cancellation-requests
 * @accessor api.functional.shoppingMall.seller.order_items.cancellation_requests.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Order item UUID (scoped to specific order)
     */
    orderItemId: string & tags.Format<"uuid">;

    /**
     * Filter criteria and pagination parameters for cancellation request search
     */
    body: IShoppingMallCancellationRequest.IRequest;
  };
  export type Body = IShoppingMallCancellationRequest.IRequest;
  export type Response = IPageIShoppingMallCancellationRequest.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/order-items/:orderItemId/cancellation-requests",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/seller/order-items/${encodeURIComponent(props.orderItemId ?? "null")}/cancellation-requests`;
  export const random = (): IPageIShoppingMallCancellationRequest.ISummary =>
    typia.random<IPageIShoppingMallCancellationRequest.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderItemId")(() => typia.assert(props.orderItemId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific cancellation request for an order item by its unique identifier.
 *
 * This operation returns the complete cancellation request details including the customer's cancellation reason, current approval status (pending, approved, or rejected), and timestamps. The endpoint validates that the cancellation request belongs to the specified order item before returning the data.
 *
 * Customers can use this to check the status of their cancellation requests. Sellers can use this to review cancellation requests for order items they need to respond to. The response includes all fields necessary to understand the request state and history.
 *
 * @param props.connection
 * @param props.orderItemId Order item ID (scoped to order)
 * @param props.cancellationRequestId Cancellation request ID (global scope)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Query shopping_mall_cancellation_requests table by primary key (cancellationRequestId).
 *
 * Validate that the cancellation request's shopping_mall_order_item_id matches the provided orderItemId parameter. Return 404 if no match found or if the cancellation request has been soft deleted (deleted_at is not null).
 *
 * Include customer information by joining with shopping_mall_customers table.
 * Return the full cancellation request entity with id, order_item_id, customer_id, reason, status, created_at, and updated_at fields.
 *
 * Handle edge cases:
 * - Return 404 if cancellation request not found
 * - Return 404 if orderItemId doesn't match the request's order item
 * - Return 403 if caller is not the customer who created the request or the seller of the order item
 * @path /shoppingMall/seller/order-items/:orderItemId/cancellation-requests/:cancellationRequestId
 * @accessor api.functional.shoppingMall.seller.order_items.cancellation_requests.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Order item ID (scoped to order)
     */
    orderItemId: string & tags.Format<"uuid">;

    /**
     * Cancellation request ID (global scope)
     */
    cancellationRequestId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallCancellationRequest;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/seller/order-items/:orderItemId/cancellation-requests/:cancellationRequestId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/seller/order-items/${encodeURIComponent(props.orderItemId ?? "null")}/cancellation-requests/${encodeURIComponent(props.cancellationRequestId ?? "null")}`;
  export const random = (): IShoppingMallCancellationRequest =>
    typia.random<IShoppingMallCancellationRequest>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderItemId")(() => typia.assert(props.orderItemId));
      assert.param("cancellationRequestId")(() =>
        typia.assert(props.cancellationRequestId),
      );
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update a cancellation request by responding to it as a seller.
 *
 * This operation allows sellers to approve or reject customer cancellation requests for individual order items. The seller must provide a response reason explaining the approval or rejection decision.
 *
 * When approved, the order item status changes to cancelled and stock is restored through an automatic inventory record. When rejected, the order item continues normal fulfillment. A snapshot of the request state is created upon response for audit trail purposes.
 *
 * Only sellers responsible for the order item can respond to its cancellation requests. Cancellation requests can only be responded to when in pending status.
 *
 * @param props.connection
 * @param props.orderItemId Order item ID (scoped to order)
 * @param props.cancellationRequestId Cancellation request ID
 * @param props.body Seller response with approval status and reason
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Validate that the cancellation request exists and is in pending status. Verify the authenticated seller is the owner of the order item (match shopping_mall_seller_id). Update the cancellation request status to approved or rejected based on request body. Set the response_reason field with the seller's provided reason. Create a snapshot record in shopping_mall_cancellation_request_snapshots capturing the status, reason, response_reason, and timestamp. If approved, update the order item status to cancelled and create an inventory record with positive quantity to restore stock. Return the updated cancellation request entity. Reject with 404 if request not found, 403 if seller doesn't own the order item, 409 if request is not in pending status.
 * @path /shoppingMall/seller/order-items/:orderItemId/cancellation-requests/:cancellationRequestId
 * @accessor api.functional.shoppingMall.seller.order_items.cancellation_requests.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Order item ID (scoped to order)
     */
    orderItemId: string & tags.Format<"uuid">;

    /**
     * Cancellation request ID
     */
    cancellationRequestId: string & tags.Format<"uuid">;

    /**
     * Seller response with approval status and reason
     */
    body: IShoppingMallCancellationRequest.IUpdate;
  };
  export type Body = IShoppingMallCancellationRequest.IUpdate;
  export type Response = IShoppingMallCancellationRequest;

  export const METADATA = {
    method: "PUT",
    path: "/shoppingMall/seller/order-items/:orderItemId/cancellation-requests/:cancellationRequestId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/seller/order-items/${encodeURIComponent(props.orderItemId ?? "null")}/cancellation-requests/${encodeURIComponent(props.cancellationRequestId ?? "null")}`;
  export const random = (): IShoppingMallCancellationRequest =>
    typia.random<IShoppingMallCancellationRequest>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderItemId")(() => typia.assert(props.orderItemId));
      assert.param("cancellationRequestId")(() =>
        typia.assert(props.cancellationRequestId),
      );
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
