import { TypedBody, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IEcommerceMallSellerProfile } from "../../../../../api/structures/IEcommerceMallSellerProfile";
import { SellerAuth } from "../../../../../decorators/SellerAuth";
import { SellerPayload } from "../../../../../decorators/payload/SellerPayload";
import { getEcommerceMallSellerSellerProfile } from "../../../../../providers/getEcommerceMallSellerSellerProfile";
import { putEcommerceMallSellerSellerProfile } from "../../../../../providers/putEcommerceMallSellerSellerProfile";

@Controller("/ecommerceMall/seller/seller/profile")
export class EcommercemallSellerSellerProfileController {
  /**
   * Retrieve the authenticated seller's own seller profile.
   *
   * This endpoint allows authenticated sellers to view their complete seller profile information as it appears to customers on the platform. The profile includes the shop name displayed on product listings and orders, the shop description providing business details to customers, and the shop logo image URL.
   *
   * The seller profile is automatically created when a seller account is approved by an administrator. Sellers can update their profile information using the PUT /seller/profile endpoint, which also creates an automatic snapshot of the previous state before applying changes.
   *
   * This operation is restricted to authenticated sellers only and returns the profile associated with the authenticated seller account. The returned profile matches exactly what customers see when viewing the seller's public profile through GET /sellers/:id/public.
   *
   * @param connection
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Retrieve the seller profile for the authenticated seller from the ecommerce_mall_seller_profiles table using the seller_id from the authenticated session. Return the shop_name, shop_description, and logo_image fields. If no profile exists for the seller, return a 404 error indicating profile not found.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @SellerAuth()
    seller: SellerPayload,
  ): Promise<IEcommerceMallSellerProfile> {
    try {
      return await getEcommerceMallSellerSellerProfile({
        seller,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update the authenticated seller's shop profile with new shop name, description, and logo information.
   *
   * This operation modifies the seller's public-facing shop profile that customers see when browsing products or visiting seller pages. The shop name appears on product listings, in order records, and throughout the platform. The business description provides background information about the shop's offerings, while the logo image serves as brand identification.
   *
   * When the profile is updated, the system automatically creates an immutable snapshot of the previous state before applying the changes. This snapshot preserves the shop name, description, and logo URI as they existed prior to the update, along with a timestamp and seller identifier. These snapshots are used for historical tracking and dispute resolution, ensuring a complete audit trail of all profile modifications.
   *
   * The authenticated seller is determined from the session token, not from path parameters. The request body must contain at least one field to update; sending an empty body will result in a validation error.
   *
   * @param connection
   * @param body Updated profile information including shop name, description, and logo URI
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Retrieve the authenticated seller from the session token. Fetch the current seller profile from the ecommerce_mall_seller_profiles table using the seller's profile relationship. Validate the request body fields (name, description, logoUri) according to the schema constraints. Before updating, create a new snapshot record in ecommerce_mall_seller_profile_snapshots capturing the current state (shop_name, shop_description, logo_url) with the current timestamp. Apply the update to the seller profile record, setting updated_at to the current timestamp. Return the fully updated seller profile including all fields and the new updated_at timestamp. Handle errors: 401 if not authenticated, 404 if seller profile does not exist, 400 for validation failures.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put()
  public async update(
    @SellerAuth()
    seller: SellerPayload,
    @TypedBody()
    body: IEcommerceMallSellerProfile.IUpdate,
  ): Promise<IEcommerceMallSellerProfile> {
    try {
      return await putEcommerceMallSellerSellerProfile({
        seller,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
