import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICommunityPlatformComment } from "../../../../../structures/ICommunityPlatformComment";
import { IPageICommunityPlatformComment } from "../../../../../structures/IPageICommunityPlatformComment";
export * as replies from "./replies/index";

/**
 * Create a new comment for the specified post within the community platform.
 *
 * This operation targets the `community_platform_comments` table, which stores
 * individual comments and nested replies associated with posts. Each comment
 * belongs to a single post from `community_platform_posts` and is authored by a
 * registered member user from `community_platform_memberusers`. The API expects
 * a valid `postId` path parameter that corresponds to an existing post and a
 * JSON request body that matches the `ICommunityPlatformComment.ICreate`
 * schema, containing the comment content and, when applicable, a parent comment
 * reference for replies.
 *
 * From a security and authorization perspective, only authenticated member
 * users are allowed to create comments. The implementation must verify that the
 * requesting user is a valid member and that their account is not currently
 * subject to blocking or restriction episodes recorded in tables such as
 * `community_platform_account_restrictions`. Additionally, the community that
 * owns the post must be in a state that allows new comments; for example,
 * archived or locked communities, as well as locked posts, should prevent
 * comment creation and return appropriate error responses.
 *
 * In terms of business logic, the operation must enforce validation rules
 * described in the Prisma schema comments and business requirements. These
 * rules typically cover limits on comment length, prevention of empty or
 * whitespace-only comments, and consistent handling of nested threading using
 * parent comment references. If a `parentCommentId` or similar relationship
 * field is provided, the implementation must validate that the parent comment
 * belongs to the same post to maintain a coherent discussion tree.
 *
 * This endpoint is typically used together with list and detail retrieval
 * operations on comments. For example, clients may first call a post detail API
 * to display a post, then call a comment listing API to fetch existing
 * comments, and finally use this creation API to submit new comments or
 * replies. On success, the operation returns the full created comment as
 * `ICommunityPlatformComment`, including identifiers, content, author linkage,
 * timestamps, and any other fields defined in the Prisma model so that the
 * client can immediately render the new comment in the UI.
 *
 * @param props.connection
 * @param props.postId Unique identifier of the target post in the
 *   `community_platform_posts` table for which the comment is being created.
 * @param props.body Payload containing content and optional parent reference
 *   for creating a new comment on the specified post.
 * @path /communityPlatform/memberUser/posts/:postId/comments
 * @accessor api.functional.communityPlatform.memberUser.posts.comments.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Unique identifier of the target post in the
     * `community_platform_posts` table for which the comment is being
     * created.
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Payload containing content and optional parent reference for creating
     * a new comment on the specified post.
     */
    body: ICommunityPlatformComment.ICreate;
  };
  export type Body = ICommunityPlatformComment.ICreate;
  export type Response = ICommunityPlatformComment;

  export const METADATA = {
    method: "POST",
    path: "/communityPlatform/memberUser/posts/:postId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/memberUser/posts/${encodeURIComponent(props.postId ?? "null")}/comments`;
  export const random = (): ICommunityPlatformComment =>
    typia.random<ICommunityPlatformComment>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a filtered and paginated list of comments for a specific post, using
 * the community_platform_comments table as the primary data source.
 *
 * This endpoint is used by clients when displaying the comment thread under an
 * individual post. The underlying community_platform_comments table holds both
 * top-level comments and nested replies. Each record is linked to a parent post
 * via a foreign key and can optionally reference another comment to form
 * threaded structures. The operation takes the postId path parameter to ensure
 * that only comments belonging to the target post are considered, providing a
 * clean scope for querying.
 *
 * The request body leverages the ICommunityPlatformComment.IRequest DTO to
 * express rich query semantics. Typical fields in this request object include
 * pagination controls (page size, cursor or offset, and direction), sorting
 * preferences (by creation time, score, or other ranking signals), and
 * filtering flags (e.g., whether to include comments that have been removed,
 * collapsed due to low score, or hidden behind moderation actions). This design
 * allows clients to implement a variety of comment viewing modes while keeping
 * the path stable and consistent.
 *
 * The response is a paginated list represented by
 * IPageICommunityPlatformComment.ISummary. Each summary object is derived from
 * the community_platform_comments Prisma model but trimmed to fields most
 * relevant for listing, such as comment identifier, truncated content, author
 * information references, score or vote aggregates, and key moderation
 * indicators. Pagination metadata in the wrapper allows clients to implement
 * infinite scroll or page-based navigation. Authorization and visibility logic
 * should take into account the viewer's role and any related moderation
 * structures, ensuring that restricted comments are either omitted or
 * represented with appropriate placeholders. Errors may be returned when the
 * post does not exist, when the post is not visible to the caller, or when
 * invalid pagination parameters are provided.
 *
 * @param props.connection
 * @param props.postId Unique identifier of the post whose associated comments
 *   should be listed and searched.
 * @param props.body Search, filtering, and pagination parameters used to query
 *   comments for the specified post.
 * @path /communityPlatform/memberUser/posts/:postId/comments
 * @accessor api.functional.communityPlatform.memberUser.posts.comments.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Unique identifier of the post whose associated comments should be
     * listed and searched.
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Search, filtering, and pagination parameters used to query comments
     * for the specified post.
     */
    body: ICommunityPlatformComment.IRequest;
  };
  export type Body = ICommunityPlatformComment.IRequest;
  export type Response = IPageICommunityPlatformComment.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/memberUser/posts/:postId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/memberUser/posts/${encodeURIComponent(props.postId ?? "null")}/comments`;
  export const random = (): IPageICommunityPlatformComment.ISummary =>
    typia.random<IPageICommunityPlatformComment.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing comment record in the community platform that is attached
 * to a specific post.
 *
 * This operation targets the community_platform_comments table, which stores
 * comments and nested replies on posts. Each record in this table is linked to
 * a post through the post_id foreign key referencing
 * community_platform_posts.id and to its author via author_memberuser_id
 * referencing community_platform_memberusers.id. The table’s description
 * explains that it represents user comments attached to posts and nested
 * replies to other comments, with threading modeled via the optional
 * parent_comment_id self-reference. Only the current version of each comment’s
 * text is stored in this table; edit histories are captured separately by
 * community_platform_comment_edit_histories.
 *
 * When a client calls this API, it must supply both the postId and commentId as
 * path parameters so the system can resolve the exact
 * community_platform_comments row where community_platform_comments.post_id
 * equals the provided postId and community_platform_comments.id equals the
 * provided commentId. This dual-parameter approach prevents accidental
 * cross-post updates and ensures that a comment is always updated in the
 * context of its owning post. The request body, represented by
 * ICommunityPlatformComment.IUpdate, contains fields that map to updatable
 * columns in the Prisma schema, primarily body, status, and is_locked. The body
 * field is a non-null string in the schema and must comply with content policy
 * and length rules described at the business layer, while status is a non-null
 * string that represents the business-level visibility and lifecycle state of
 * the comment such as visible, deleted_by_author, or removed_by_moderation. The
 * is_locked boolean indicates whether new replies are disallowed on this
 * comment according to moderation or thread-locking rules.
 *
 * Security-wise, the operation is protected for authenticated users only, and
 * the actual permission model is enforced in the service layer. The
 * implementation should ensure that typical memberUser actors can only modify
 * comments they authored, and even then only within allowed business
 * constraints (such as time windows or disallowing changes once the comment has
 * been moderated). Admin or moderation actors may be able to update status and
 * lock flags irrespective of authorship, reflecting broader moderation powers
 * described in the platform’s requirements. The updated_at field is always
 * refreshed on successful update, while created_at and author_memberuser_id are
 * immutable. The deleted_at field is only set or modified when transitions to
 * certain status values require it, following the schema’s description that
 * this field holds the timestamp when the comment was soft deleted by the
 * author or moderation.
 *
 * The response returns the full current representation of the comment as
 * ICommunityPlatformComment, including the updated body text, status, is_locked
 * flag, and timestamps. Related API operations for this resource include
 * creating new comments on a post (POST /posts/{postId}/comments), retrieving
 * the list of comments for a post with sorting and pagination (PATCH
 * /posts/{postId}/comments), and deleting a specific comment (DELETE
 * /posts/{postId}/comments/{commentId}). Consumers are expected to use this
 * update endpoint when editing an existing comment while relying on the list
 * and detail endpoints to display the latest state of comment threads. Error
 * handling includes not-found responses when the comment does not exist for the
 * given postId and commentId combination, authorization failures when the
 * caller is not permitted to modify the target comment, and validation errors
 * when the update payload violates data or business rules.
 *
 * @param props.connection
 * @param props.postId Unique identifier (UUID) of the post that owns the target
 *   comment. This value is matched against community_platform_comments.post_id
 *   to ensure the comment is updated in the correct post context.
 * @param props.commentId Unique identifier (UUID) of the comment to update.
 *   This value is matched against community_platform_comments.id within the
 *   specified post context.
 * @param props.body Fields to update on the target comment, mapped to body,
 *   status, is_locked, and related updatable properties of the
 *   community_platform_comments record.
 * @path /communityPlatform/memberUser/posts/:postId/comments/:commentId
 * @accessor api.functional.communityPlatform.memberUser.posts.comments.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Unique identifier (UUID) of the post that owns the target comment.
     * This value is matched against community_platform_comments.post_id to
     * ensure the comment is updated in the correct post context.
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Unique identifier (UUID) of the comment to update. This value is
     * matched against community_platform_comments.id within the specified
     * post context.
     */
    commentId: string & tags.Format<"uuid">;

    /**
     * Fields to update on the target comment, mapped to body, status,
     * is_locked, and related updatable properties of the
     * community_platform_comments record.
     */
    body: ICommunityPlatformComment.IUpdate;
  };
  export type Body = ICommunityPlatformComment.IUpdate;
  export type Response = ICommunityPlatformComment;

  export const METADATA = {
    method: "PUT",
    path: "/communityPlatform/memberUser/posts/:postId/comments/:commentId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/memberUser/posts/${encodeURIComponent(props.postId ?? "null")}/comments/${encodeURIComponent(props.commentId ?? "null")}`;
  export const random = (): ICommunityPlatformComment =>
    typia.random<ICommunityPlatformComment>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("commentId")(() => typia.assert(props.commentId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Erase a specific comment row from the community_platform_comments table for a
 * given post.
 *
 * This delete operation targets the same domain as the update endpoint but
 * performs a hard removal of a comment rather than a status-based visibility
 * change. The community_platform_comments table represents comments and nested
 * replies attached to posts, with each row linked to a post via post_id
 * referencing community_platform_posts.id and optionally to a parent comment
 * via parent_comment_id for nested threads. It stores the current version of
 * each comment’s body text and its status and lock state, while historical
 * edits reside in community_platform_comment_edit_histories.
 *
 * The client must provide both postId and commentId as path parameters.
 * Internally, the service resolves the target row by ensuring that
 * community_platform_comments.post_id equals the supplied postId and
 * community_platform_comments.id equals the supplied commentId. This dual-key
 * check guarantees that the comment being erased indeed belongs to the
 * specified post and prevents deletion of a comment from an unintended context.
 * The operation then performs a permanent deletion of the matching record from
 * community_platform_comments. Unlike flows that toggle the status field or set
 * the deleted_at timestamp to hide a comment while preserving its structure,
 * this operation removes the record itself from the table.
 *
 * From a security and governance perspective, this endpoint should be exposed
 * only to privileged actors, which in this API contract are represented by the
 * adminUser actor type and will be further distinguished in the business logic
 * based on roles. Typical memberUser actors should not be allowed to call this
 * endpoint directly; instead they should use comment update flows that mark a
 * comment as deleted_by_author while keeping it stored for thread integrity and
 * audit purposes. The service implementation should enforce strict checks,
 * ensuring only authorized moderation or administrative users can execute an
 * erase, and should decide how to handle dependent data such as votes, reports,
 * or child replies.
 *
 * On success, the endpoint does not return a representation of the deleted
 * comment; responseBody is null to indicate that consumers should use list or
 * detail retrieval endpoints to observe the resulting state of the post’s
 * comment tree. Error handling includes returning not-found when no comment
 * exists for the provided postId and commentId combination, authorization
 * failures when the caller lacks permission to perform destructive deletions,
 * and conflict responses when business rules forbid erasing a comment in
 * certain states (for example, when regulations require retaining specific
 * moderation records).
 *
 * @param props.connection
 * @param props.postId Unique identifier (UUID) of the post that owns the
 *   comment to erase. This value is matched against
 *   community_platform_comments.post_id.
 * @param props.commentId Unique identifier (UUID) of the comment to erase from
 *   the community_platform_comments table.
 * @path /communityPlatform/memberUser/posts/:postId/comments/:commentId
 * @accessor api.functional.communityPlatform.memberUser.posts.comments.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * Unique identifier (UUID) of the post that owns the comment to erase.
     * This value is matched against community_platform_comments.post_id.
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Unique identifier (UUID) of the comment to erase from the
     * community_platform_comments table.
     */
    commentId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/communityPlatform/memberUser/posts/:postId/comments/:commentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/memberUser/posts/${encodeURIComponent(props.postId ?? "null")}/comments/${encodeURIComponent(props.commentId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("commentId")(() => typia.assert(props.commentId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
