import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallAdminPromotionRequestSnapshot } from "../../../../../structures/IPageIShoppingMallAdminPromotionRequestSnapshot";
import { IShoppingMallAdminPromotionRequestSnapshot } from "../../../../../structures/IShoppingMallAdminPromotionRequestSnapshot";

/**
 * Retrieve a paginated list of immutable snapshots for a specific administrator promotion request.
 *
 * This operation provides a complete audit trail of all status changes for an admin promotion request. Each snapshot captures the actor type, status, decision reason, and responding super administrator at the moment of change. Snapshots are created automatically whenever the request status changes and cannot be modified or deleted.
 *
 * Supports filtering by actor type, status, and creation date range. Results are sorted by creation timestamp in descending order. Only the request owner (customer or seller) and super administrators can access these snapshots.
 *
 * @param props.connection
 * @param props.requestId UUID of the administrator promotion request (global scope)
 * @param props.body Filter criteria and pagination parameters for snapshot search
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdministrator
 * @x-autobe-specification Query shopping_mall_admin_promotion_request_snapshots table filtered by shopping_mall_admin_promotion_request_id. Apply pagination with cursor-based or offset-based approach. Support filtering by actor_type, status, and created_at date range. Join with shopping_mall_super_administrators to include responding super administrator details when available. Validate that requesting user has permission to view this request's snapshots (request owner or super administrator). Return snapshots sorted by created_at descending (newest first).
 * @path /shoppingMall/superAdministrator/admin-promotion-requests/:requestId/snapshots
 * @accessor api.functional.shoppingMall.superAdministrator.admin_promotion_requests.snapshots.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * UUID of the administrator promotion request (global scope)
     */
    requestId: string & tags.Format<"uuid">;

    /**
     * Filter criteria and pagination parameters for snapshot search
     */
    body: IShoppingMallAdminPromotionRequestSnapshot.IRequest;
  };
  export type Body = IShoppingMallAdminPromotionRequestSnapshot.IRequest;
  export type Response =
    IPageIShoppingMallAdminPromotionRequestSnapshot.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/superAdministrator/admin-promotion-requests/:requestId/snapshots",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/superAdministrator/admin-promotion-requests/${encodeURIComponent(props.requestId ?? "null")}/snapshots`;
  export const random =
    (): IPageIShoppingMallAdminPromotionRequestSnapshot.ISummary =>
      typia.random<IPageIShoppingMallAdminPromotionRequestSnapshot.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific immutable snapshot of an administrator promotion request.
 *
 * This operation returns the complete state of an admin promotion request snapshot at a specific point in time, including the actor type (customer or seller), status (pending, approved, or rejected), decision reason provided by the super administrator, and the responding super administrator's identity.
 *
 * Snapshots are created automatically whenever a promotion request's status changes and cannot be modified or deleted. This endpoint allows authorized users (the request submitter, responding super administrator, or administrators) to view historical states for audit and dispute resolution purposes.
 *
 * The snapshot includes the timestamp when it was created, preserving the exact moment the status change occurred. All snapshot data is immutable and retained indefinitely, even after the original promotion request is deleted.
 *
 * @param props.connection
 * @param props.requestId Parent promotion request ID (global scope, UUID format)
 * @param props.snapshotId Snapshot ID to retrieve (global scope, UUID format)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdministrator
 * @x-autobe-specification Query shopping_mall_admin_promotion_request_snapshots table by snapshot ID.
 *
 * Validate that the snapshotId exists and is a valid UUID.
 * Validate that the requestId matches the snapshot's shopping_mall_admin_promotion_request_id (parent context validation).
 *
 * Authorization: Allow access if requester is:
 * - The actor who submitted the promotion request (check shopping_mall_admin_promotion_request_of_customers or shopping_mall_admin_promotion_request_of_sellers)
 * - The responding super administrator (match responding_super_administrator_id)
 * - An administrator or super administrator
 *
 * Join with shopping_mall_super_administrators to include responding super administrator details if responding_super_administrator_id is not null.
 *
 * Return the complete snapshot record including: id, shopping_mall_admin_promotion_request_id, responding_super_administrator_id, actor_type, status, reason, created_at.
 *
 * Handle 404 if snapshot not found or requestId mismatch.
 * Handle 403 if requester lacks authorization.
 * @path /shoppingMall/superAdministrator/admin-promotion-requests/:requestId/snapshots/:snapshotId
 * @accessor api.functional.shoppingMall.superAdministrator.admin_promotion_requests.snapshots.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Parent promotion request ID (global scope, UUID format)
     */
    requestId: string & tags.Format<"uuid">;

    /**
     * Snapshot ID to retrieve (global scope, UUID format)
     */
    snapshotId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallAdminPromotionRequestSnapshot;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/superAdministrator/admin-promotion-requests/:requestId/snapshots/:snapshotId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/superAdministrator/admin-promotion-requests/${encodeURIComponent(props.requestId ?? "null")}/snapshots/${encodeURIComponent(props.snapshotId ?? "null")}`;
  export const random = (): IShoppingMallAdminPromotionRequestSnapshot =>
    typia.random<IShoppingMallAdminPromotionRequestSnapshot>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
      assert.param("snapshotId")(() => typia.assert(props.snapshotId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
