import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

/**
 * Permanently deletes a comment associated with a specific product review. This
 * hard delete operation immediately removes the comment record from the
 * database, making it irrecoverable. The comment is identified by its unique
 * code within the target review's context.
 *
 * The deletion operation validates that the requesting user (customer or
 * seller) owns the comment or has administrative privileges. Unauthorized
 * deletion attempts will return a 403 Forbidden response. System administrators
 * can delete any comment regardless of ownership.
 *
 * This operation corresponds to the shopping_mall_review_comments table's
 * primary record definition. The unique constraint (review_code, comment_code)
 * ensures the parameters provide unambiguous identification of the target
 * comment record.
 *
 * @param props.connection
 * @param props.reviewCode Unique business identifier code of the target review
 *   (global scope)
 * @param props.commentCode Unique business identifier code of the comment
 *   within the review (scoped to review)
 * @path /shoppingMall/seller/reviews/:reviewCode/comments/:commentCode
 * @accessor api.functional.shoppingMall.seller.reviews.comments.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique business identifier code of the target review (global scope) */
    reviewCode: string;

    /**
     * Unique business identifier code of the comment within the review
     * (scoped to review)
     */
    commentCode: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/shoppingMall/seller/reviews/:reviewCode/comments/:commentCode",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/seller/reviews/${encodeURIComponent(props.reviewCode ?? "null")}/comments/${encodeURIComponent(props.commentCode ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("reviewCode")(() => typia.assert(props.reviewCode));
      assert.param("commentCode")(() => typia.assert(props.commentCode));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
