import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IMallPlatformProductImage } from "../../../../../../api/structures/IMallPlatformProductImage";
import { SellerAuth } from "../../../../../../decorators/SellerAuth";
import { SellerPayload } from "../../../../../../decorators/payload/SellerPayload";
import { patchMallPlatformSellerProductsProductIdImagesReorder } from "../../../../../../providers/patchMallPlatformSellerProductsProductIdImagesReorder";

@Controller("/mallPlatform/seller/products/:productId/images/reorder")
export class MallplatformSellerProductsImagesReorderController {
  /**
   * Reorder the images attached to a product.
   *
   * This operation updates the maintained presentation order for a product’s image set. The first image in the order is treated as the main thumbnail image used in product listings and on the product detail page, so the requested order directly affects how customers see the product across browsing surfaces.
   *
   * Only the seller who owns the product may perform this action. The product must still exist and remain available for image maintenance. If the requested image sequence is invalid, refers to an unavailable image, or would leave the product without a valid main image position, the request is rejected and the existing image order remains unchanged.
   *
   * A successful reorder is recorded in the product’s snapshot history so the previous visual presentation can be reconstructed for dispute review and audit purposes.
   *
   * @param connection
   * @param productId Identifier of the product whose images are being reordered.
   * @param body New image ordering for the specified product. The order of identifiers in this body becomes the maintained presentation order, and the first image becomes the main thumbnail image.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor seller
   * @x-autobe-specification Load the target product by productId and verify the authenticated seller owns it and is allowed to maintain its images. Reject the request if the product does not exist, is unavailable for maintenance, or belongs to another seller.
   *
   * Validate that the request provides a complete new ordering of existing product image identifiers for that product, with no duplicates and no missing images. Reject any request that references an image not attached to the product or any image that is no longer available.
   *
   * Apply the reorder atomically so the maintained order changes only if all validations pass. Ensure exactly one first-position image after the update, since the first image is the main thumbnail. Persist the new order on mall_platform_product_images, then create the corresponding product snapshot and product image snapshot history entries to preserve the previous state.
   *
   * Return the updated product image collection in maintained order. On failure, do not alter the stored order and do not create a snapshot for the failed attempt.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async reorderProductImages(
    @SellerAuth()
    seller: SellerPayload,
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IMallPlatformProductImage.IUpdate,
  ): Promise<IMallPlatformProductImage.ISummary> {
    try {
      return await patchMallPlatformSellerProductsProductIdImagesReorder({
        seller,
        productId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
