import { tags } from "typia";

import { ICommunityPlatformCommunity } from "./ICommunityPlatformCommunity";
import { ICommunityPlatformMember } from "./ICommunityPlatformMember";

/**
 * Membership record representing a member's subscription to a community.
 *
 * Tracking which members are subscribed to which communities. Each subscription
 * record represents one member's membership in one community. Subscriptions
 * include join timestamp, enabling activity history and member tenure
 * calculation.
 *
 * Subscriptions are the mechanism for determining community membership,
 * controlling content visibility, and personalizing member feeds. Each
 * member-community pair has at most one subscription (no duplicates).
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformCommunitySubscription = {
  /** Primary Key. Unique identifier for the subscription record. */
  id: string & tags.Format<"uuid">;

  /**
   * Community being subscribed to. References the community entity with full
   * details.
   */
  community: ICommunityPlatformCommunity.ISummary;

  /**
   * Member subscribed to the community. References the member entity with
   * profile information.
   */
  member: ICommunityPlatformMember.ISummary;

  /**
   * Timestamp when member subscribed to community. Immutable after
   * subscription creation. Used to calculate member tenure in community.
   */
  subscribed_at: string & tags.Format<"date-time">;

  /**
   * Record creation timestamp. Typically matches subscribed_at. Used for
   * audit trail.
   */
  created_at: string & tags.Format<"date-time">;
};
export namespace ICommunityPlatformCommunitySubscription {
  /**
   * Query parameters for searching, filtering, and sorting community
   * subscriptions.
   *
   * Supports comprehensive filtering: search members by username (partial
   * matching), filter by subscription date range (find recent or long-time
   * members), and filter by member karma score (find experienced vs new
   * members). Pagination controlled via page and limit parameters.
   *
   * All filtering parameters are optional. When not provided, filters are not
   * applied and all matching records are included. Supports pagination with
   * configurable page size (default 20, maximum 100) for efficient data
   * retrieval across large communities.
   */
  export type IRequest = {
    /** Page number for pagination. Starts at 1. Default: 1. */
    page?:
      | (number & tags.Type<"int32"> & tags.Default<1> & tags.Minimum<1>)
      | undefined;

    /** Number of items per page. Range: 1-100. Default: 20. */
    limit?:
      | (number &
          tags.Type<"int32"> &
          tags.Default<20> &
          tags.Minimum<1> &
          tags.Maximum<100>)
      | undefined;

    /**
     * Filter subscriptions by member username using partial matching.
     * Case-insensitive search across member usernames. Optional - if not
     * provided, all members are included regardless of username.
     */
    search_username?: string | undefined;

    /**
     * Filter subscriptions starting from this date (inclusive). Returns
     * members who subscribed on or after this date. Used to find recent
     * members or members subscribed within a specific timeframe. Optional -
     * if not provided, no lower date bound is applied.
     */
    subscribed_from?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter subscriptions up to this date (inclusive). Returns members who
     * subscribed on or before this date. Used to find long-time members or
     * members subscribed within a specific timeframe. Optional - if not
     * provided, no upper date bound is applied.
     */
    subscribed_to?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter subscriptions by minimum member karma score (inclusive).
     * Returns members with karma score greater than or equal to this value.
     * Used to find experienced members. Optional - if not provided, no
     * minimum karma threshold is applied.
     */
    min_karma?: number | undefined;

    /**
     * Filter subscriptions by maximum member karma score (inclusive).
     * Returns members with karma score less than or equal to this value.
     * Used to find newer members with lower karma. Optional - if not
     * provided, no maximum karma threshold is applied.
     */
    max_karma?: number | undefined;

    /**
     * Sort order for results. Options: 'newest' (most recent
     * subscriptions), 'oldest' (earliest subscriptions), 'community_name'
     * (alphabetical by member username). Default: 'newest'.
     */
    sort_by?: "newest" | "oldest" | "community_name" | undefined;
  };

  /**
   * Lightweight summary of a community subscription representing a member's
   * membership in a community.
   *
   * Contains subscription metadata including unique subscription ID,
   * references to the community and member, and timestamps indicating when
   * the member joined and when the record was created. Optimized for list
   * displays and embedded contexts in community member rosters, subscription
   * lists, and membership checks.
   *
   * The subscribed_at timestamp enables sorting and filtering by member
   * tenure, allowing discovery of recent members, long-time members, or
   * members who joined within a specific date range. This summary form is
   * used when full member or community profile details are not required.
   */
  export type ISummary = {
    /**
     * Primary Key. Unique identifier for the subscription record. Used to
     * reference this specific member-community membership relationship.
     */
    id: string & tags.Format<"uuid">;

    /**
     * ID of the community being subscribed to. References
     * community_platform_communities.id for the community in this M:N
     * membership relationship. Identifies which community this member
     * belongs to.
     */
    community_id: string & tags.Format<"uuid">;

    /**
     * ID of the member subscribed to the community. References
     * community_platform_members.id. Tracks which member has this
     * subscription and their membership status.
     */
    member_id: string & tags.Format<"uuid">;

    /**
     * Timestamp when member subscribed to community. Immutable after
     * subscription creation. Used to calculate member tenure in community
     * and for sorting member lists by join date. Enables filtering members
     * by subscription recency (recent vs long-time members).
     */
    subscribed_at: string & tags.Format<"date-time">;

    /**
     * Record creation timestamp. Typically matches subscribed_at (record
     * created when subscription occurs). Used for audit trail and tracking
     * when the membership record was established in the system. Provides
     * immutable timestamp of when the subscription was recorded.
     */
    created_at: string & tags.Format<"date-time">;
  };

  /**
   * Request body for subscribing a member to a community.
   *
   * The authenticated member automatically becomes the subscriber - no
   * member_id field is accepted. The subscription timestamp is set
   * automatically by the backend. Only the community to be subscribed to is
   * required.
   *
   * Subscriptions are simple operations - member subscribes to one community
   * at a time.
   */
  export type ICreate = {
    /**
     * ID of the community to subscribe to. Must be a valid, active
     * community.
     */
    community_id: string & tags.Format<"uuid">;
  };
}
