import { tags } from "typia";

import { ICommunityPlatformMember } from "./ICommunityPlatformMember";
import { ICommunityPlatformReportDecision } from "./ICommunityPlatformReportDecision";
import { ICommunityPlatformModerator } from "./ICommunityPlatformModerator";

/**
 * Moderation appeal record representing a user's formal request to reconsider a
 * moderation decision.
 *
 * Records appeals submitted by members who disagree with moderation actions
 * (content removal, suspension, warning, ban). Appeals enable fairness in the
 * moderation system by allowing independent review of moderator decisions. Each
 * appeal includes the member's explanation, supporting evidence, and can result
 * in decision reversal, punishment reduction, or denial.
 *
 * Appeals follow a defined workflow: 'submitted' (initial) → 'in_review'
 * (reviewer assigned) → final decision ('approved'/'denied'/'reduced').
 * Requires separate moderator review different from original decision moderator
 * to prevent bias and conflict of interest. Provides complete audit trail of
 * appeal lifecycle.
 *
 * Appeals are eligible for submission within specific windows: 30 days for
 * content removals and suspensions, 1 year for permanent bans. System prevents
 * duplicate appeals on same decision and enforces rate limiting to prevent
 * abuse.
 *
 * The appeal record includes the original moderation decision context (via
 * decision reference), appellant information (via appellant reference), and
 * reviewer information (via reviewer reference) for complete transparency and
 * accountability.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformModerationAppeal = {
  /**
   * Unique identifier for the moderation appeal (UUID format).
   *
   * Primary key. Immutable. Used to reference this appeal in all operations
   * and relationships.
   */
  id: string & tags.Format<"uuid">;

  /**
   * UUID of the member who submitted this appeal.
   *
   * The user who disagrees with the moderation decision. Links to the
   * appellant in the community_platform_members table. Identifies who
   * initiated the appeal request.
   */
  community_platform_member_id: string & tags.Format<"uuid">;

  /**
   * UUID of the moderation decision being appealed.
   *
   * References community_platform_report_decisions table. The specific
   * moderator action the member is requesting be reconsidered. Establishes
   * the link to the original moderation decision.
   */
  community_platform_report_decision_id: string & tags.Format<"uuid">;

  /**
   * UUID of the moderator/administrator assigned to review this appeal.
   *
   * Null while appeal is pending reviewer assignment (status = submitted or
   * in_review before assignment). Populated when appeal transitions to
   * in_review status with an assigned reviewer. Different from the original
   * decision moderator to prevent bias and conflict of interest.
   */
  appeal_reviewer_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Summary information of the member who submitted the appeal.
   *
   * Includes member ID, username, email, account status, and karma score for
   * context about the appellant.
   */
  appellant: ICommunityPlatformMember.ISummary;

  /**
   * Summary of the moderation decision being appealed.
   *
   * Includes decision ID, action type (remove_content, suspend_user,
   * ban_user, etc.), reason, moderator information, and creation timestamp.
   * Provides complete context of the original decision.
   */
  decision: ICommunityPlatformReportDecision.ISummary;

  /**
   * Summary of the moderator/administrator reviewing this appeal.
   *
   * Null while appeal is pending reviewer assignment (status = submitted or
   * in_review before assignment). Populated when appeal transitions to
   * in_review status with an assigned reviewer. Includes moderator ID and
   * username for accountability.
   */
  reviewer?: ICommunityPlatformModerator.ISummary | null | undefined;

  /**
   * Member's explanation of why the moderation decision should be reversed
   * (50-1000 characters).
   *
   * Required field submitted by appellant during appeal submission. Explains
   * the member's perspective on why they believe the moderator decision was
   * incorrect or unfair. Must be substantive with minimum character length.
   */
  appeal_reason: string & tags.MinLength<50> & tags.MaxLength<1000>;

  /**
   * Optional link or attachment reference for evidence supporting the appeal
   * (up to 2048 characters).
   *
   * Allows member to provide additional context, screenshots, documentation,
   * or external references to support their case. Null if member has no
   * additional evidence. When provided, should be valid URLs or file
   * references.
   */
  supporting_evidence?: (string & tags.MaxLength<2048>) | null | undefined;

  /**
   * Current status of the appeal workflow.
   *
   * Valid values: 'submitted' (initial state after appeal submission),
   * 'in_review' (reviewer assigned and reviewing), 'approved' (decision
   * reversed by reviewer), 'denied' (decision upheld by reviewer), 'reduced'
   * (lesser punishment applied by reviewer). Tracks progression through the
   * appeal workflow.
   */
  appeal_status: "submitted" | "in_review" | "approved" | "denied" | "reduced";

  /**
   * Result of appeal review when a final decision is made.
   *
   * Examples: 'overturned_restore_content', 'suspension_reduced_to_warning',
   * 'ban_reduced_to_suspension', 'decision_upheld'. Null while status is
   * 'submitted' or 'in_review'. Describes the specific action taken or
   * decision rendered by the reviewer. Required field when status transitions
   * to approved, denied, or reduced.
   */
  appeal_outcome?:
    | "overturned_restore_content"
    | "suspension_reduced_to_warning"
    | "ban_reduced_to_suspension"
    | "decision_upheld"
    | null
    | undefined;

  /**
   * Reviewer's explanation of the appeal decision (shown to appellant).
   *
   * Justifies why the appeal was approved, denied, or resulted in reduced
   * punishment. Null while appeal is pending review or assigned to reviewer.
   * Provides transparency and detailed reasoning to the appellant. Documents
   * the review justification for record-keeping.
   */
  reviewer_notes?: string | null | undefined;

  /**
   * Appeal submission timestamp (ISO 8601 UTC).
   *
   * Immutable. Used to calculate appeal deadline (30 days for most decisions,
   * 1 year for permanent bans) and track when the appeal was initiated.
   * Different from created_at if appeals are backfilled into the system.
   */
  submitted_at: string & tags.Format<"date-time">;

  /**
   * Appeal review completion timestamp (ISO 8601 UTC).
   *
   * When the reviewer made the final decision. Null while appeal is pending,
   * submitted, or in_review without final decision. Updated when appeal
   * transitions to approved, denied, or reduced status.
   */
  reviewed_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Record creation timestamp (ISO 8601 UTC).
   *
   * Immutable. Typically same as submitted_at. Tracks when the appeal record
   * was created in the system. Used for audit trail.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Last update timestamp (ISO 8601 UTC).
   *
   * Updated whenever appeal status, outcome, reviewer information, or notes
   * change. Tracks modification history and provides audit trail.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft delete timestamp (ISO 8601 UTC).
   *
   * Null for active appeals. Set when appeal is withdrawn or archived by
   * member or administrator. Enables logical deletion while preserving audit
   * trail and historical records.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ICommunityPlatformModerationAppeal {
  /**
   * Search and filter parameters for querying moderation appeals with
   * pagination and sorting.
   *
   * Enables comprehensive appeal management by supporting complex filtering
   * on appeal status, appellant member, assigned reviewer, and submission
   * timing. Supports pagination for efficient large result set handling.
   *
   * Common use cases include: finding all pending appeals
   * (status='submitted'), appeals assigned to current moderator
   * (appeal_reviewer_id=self), appeals from specific member
   * (community_platform_member_id=X), or recently submitted appeals
   * (order_by='submitted_at', sort_order='desc').
   *
   * All filter parameters are optional - omitting filters returns all visible
   * appeals per user's authorization level. Pagination defaults to page 1
   * with 20 results per page for reasonable data volumes.
   */
  export type IRequest = {
    /**
     * Page number for pagination (1-indexed). Defaults to 1 if not
     * specified. Used to navigate through result sets.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of appeals per page. Defaults to 20. Maximum allowed is 100 to
     * prevent excessive data transfer.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Filter by appeal status. Optional. Allowed values: 'submitted'
     * (initial submission), 'in_review' (reviewer assigned), 'approved'
     * (decision reversed), 'denied' (decision upheld), 'reduced' (lesser
     * punishment applied). When null or omitted, all statuses are
     * included.
     */
    appeal_status?:
      | "submitted"
      | "in_review"
      | "approved"
      | "denied"
      | "reduced"
      | null
      | undefined;

    /**
     * Filter by appellant member ID. Optional UUID. When provided, returns
     * only appeals from this specific member. Used to view all appeals
     * submitted by a particular member.
     */
    community_platform_member_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;

    /**
     * Filter by reviewer moderator ID. Optional UUID. When provided,
     * returns only appeals assigned to this specific moderator for review.
     * Null/omitted includes unassigned appeals and appeals not yet under
     * review.
     */
    appeal_reviewer_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Sort field. Defaults to 'submitted_at'. Options: 'submitted_at' (sort
     * by submission time), 'reviewed_at' (sort by review completion),
     * 'appeal_status' (sort by status field). Combined with sort_order for
     * complete ordering.
     */
    order_by?: "submitted_at" | "reviewed_at" | "appeal_status" | undefined;

    /**
     * Sort direction. Defaults to 'desc' (newest/latest first). Options:
     * 'asc' (ascending, oldest first), 'desc' (descending, newest first).
     * Applied to the field specified by order_by.
     */
    sort_order?: "asc" | "desc" | undefined;
  };

  /**
   * Lightweight appeal representation for efficient display in appeal queues
   * and list views.
   *
   * Optimized for paginated appeal queue displays and appeal history views.
   * Contains essential appeal information for quick assessment without
   * loading full appeal details. Includes appellant context and original
   * decision summary for queue display.
   *
   * Emphasizes current status and submission context for moderators and
   * administrators reviewing pending appeals. Excludes reviewer information
   * and detailed decision notes (available in detail view).
   *
   * Used in paginated responses when listing appeals or in embedded contexts
   * where complete appeal detail is not required.
   */
  export type ISummary = {
    /**
     * Unique identifier for the moderation appeal.
     *
     * Primary key used to reference this appeal in APIs and relationships.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Summary information of the member who submitted the appeal.
     *
     * Includes member ID, username, email, account status, and karma score
     * for identification and context about the appellant.
     */
    appellant: ICommunityPlatformMember.ISummary;

    /**
     * Summary of the moderation decision being appealed.
     *
     * Includes decision ID, action type, reason, and moderator information
     * for quick understanding of what's being appealed.
     */
    decision: ICommunityPlatformReportDecision.ISummary;

    /**
     * Current status of the appeal workflow.
     *
     * Valid values: 'submitted', 'in_review', 'approved', 'denied',
     * 'reduced'. Indicates where the appeal stands in the review process.
     */
    appeal_status:
      | "submitted"
      | "in_review"
      | "approved"
      | "denied"
      | "reduced";

    /**
     * Member's explanation of why the moderation decision should be
     * reversed.
     *
     * The appellant's substantive reasoning. Displayed in appeal queue and
     * review interfaces.
     */
    appeal_reason: string & tags.MinLength<50> & tags.MaxLength<1000>;

    /**
     * Appeal submission timestamp (ISO 8601 UTC).
     *
     * Immutable. Used to calculate appeal deadline and track submission
     * time. Useful for sorting appeal queues by recency and priority.
     */
    submitted_at: string & tags.Format<"date-time">;
  };

  /**
   * Request body for creating a new moderation appeal.
   *
   * Submitted by members when they disagree with a moderation decision and
   * request independent review. The appeal submission includes the decision
   * being appealed (via reference to the report decision), the member's
   * explanation, and optional supporting evidence.
   *
   * **Important: User does NOT provide these fields - they are auto-managed
   * by the system:**
   *
   * - `community_platform_member_id`: Auto-captured from authenticated JWT
   *   context. Ensures appeal is always attributed to the authenticated
   *   member and prevents identity spoofing.
   * - `appeal_status`: Auto-set to 'submitted' on creation. Initializes the
   *   appeal workflow in the correct state.
   * - `submitted_at`: Auto-set to current UTC timestamp on creation. Immutable
   *   record of when appeal was submitted.
   * - `created_at`: Auto-set to current UTC timestamp on creation. Audit trail
   *   of record creation.
   *
   * Validation enforces: (1) Decision reference exists and is appealable (not
   * already reversed, within appeal window), (2) Appeal reason meets minimum
   * length (50 chars) for substantive content, (3) Supporting evidence is
   * valid URL/file reference if provided, (4) No duplicate appeals on same
   * decision within cooldown period.
   *
   * Upon successful creation, the appeal receives initial status 'submitted'
   * and is immediately routed to the moderation appeals review queue for
   * independent moderator/administrator review.
   */
  export type ICreate = {
    /**
     * UUID of the moderation decision being appealed.
     *
     * Required reference to the original report decision record (from
     * community_platform_report_decisions table). This links the appeal to
     * the specific content removal, suspension, warning, or ban decision
     * the member is challenging.
     *
     * Validation ensures this decision exists and is within the appeal
     * window for the action type (30 days for most decisions, 1 year for
     * permanent bans).
     */
    community_platform_report_decision_id: string & tags.Format<"uuid">;

    /**
     * Member's detailed explanation of why they believe the moderation
     * decision should be reversed.
     *
     * Required field. Minimum 50 characters ensures thoughtful, substantive
     * appeals rather than dismissive rejections. Maximum 1000 characters
     * provides practical submission constraints. Member explains their
     * perspective on why the decision was incorrect, unfair, or needs
     * reconsideration.
     *
     * Examples: 'The post was educational content about historical events,
     * not the political attack the moderator claimed' or 'I was addressing
     * a false accusation in that thread and my response was taken out of
     * context'.
     */
    appeal_reason: string & tags.MinLength<50> & tags.MaxLength<1000>;

    /**
     * Optional URL or file reference providing additional context
     * supporting the appeal.
     *
     * Up to 2048 characters for URLs or file references. Member can provide
     * links to external documentation, screenshots showing context, or
     * other evidence supporting their case. Null if member has no
     * additional evidence to provide.
     *
     * When supplied, must be valid URLs (https://example.com/screenshot) or
     * file references. Examples: URLs to related discussion threads,
     * external documentation, or proof of previous context.
     */
    supporting_evidence?: (string & tags.MaxLength<2048>) | null | undefined;
  };

  /**
   * Update information for moderation appeal records during the review
   * process.
   *
   * Enables appeal reviewers to transition appeal status through the workflow
   * (submitted → in_review → final decision), assign reviewers, record review
   * outcomes, and document decision reasoning. All fields are optional to
   * support partial updates during different stages of the appeal workflow.
   *
   * **Partial Update Pattern**: This DTO supports progressive updates as
   * reviewers work through the appeal workflow:
   *
   * 1. **Stage 1 - Assign Reviewer**: Update `appeal_status` to 'in_review' and
   *    set `appeal_reviewer_id` to assign reviewer. Other fields remain
   *    unchanged.
   * 2. **Stage 2 - Record Decision**: Update `appeal_status` to final state
   *    (approved/denied/reduced), set `appeal_outcome` with specific result,
   *    optionally add `reviewer_notes` with reasoning.
   * 3. **Optional - Withdraw**: Set `deleted_at` timestamp if appeal is
   *    withdrawn before or during review.
   *
   * Used in PUT /communityPlatform/moderator/moderationAppeals/{appealId}
   * operations where authenticated moderators can update appeals. Status
   * transitions must follow valid state machine rules (submitted → in_review,
   * in_review → approved/denied/reduced). Soft deletion is supported for
   * withdrawing appeals.
   *
   * Validation enforces state machine constraints: (1) Status transitions
   * only in valid directions, (2) reviewer_id must differ from original
   * decision moderator when transitioning to in_review, (3) appeal_outcome
   * required when status becomes approved/denied/reduced, (4) reviewer_notes
   * should be substantive when final decision recorded.
   *
   * The system automatically updates `updated_at` timestamp on any
   * modification and `reviewed_at` timestamp when final decision is
   * recorded.
   */
  export type IUpdate = {
    /**
     * Updated appeal status reflecting the current workflow state.
     *
     * Valid values and transitions:
     *
     * - `submitted`: Initial state after appeal creation. Only transition: →
     *   `in_review` when reviewer is assigned.
     * - `in_review`: Reviewer is actively reviewing the appeal. Transitions:
     *   → `approved` (decision reversed), → `denied` (decision upheld), →
     *   `reduced` (lesser punishment applied).
     * - `approved`: Appeal reviewer determined the original moderation
     *   decision was incorrect or unfair. Affected content is restored or
     *   user access reinstated.
     * - `denied`: Appeal reviewer determined the original moderation decision
     *   was justified. Status quo maintained.
     * - `reduced`: Appeal reviewer determined punishment should be lessened
     *   (e.g., suspension reduced to warning, ban reduced to suspension).
     *
     * This field drives the appeal workflow and determines what outcomes
     * are possible.
     */
    appeal_status?:
      | "submitted"
      | "in_review"
      | "approved"
      | "denied"
      | "reduced"
      | undefined;

    /**
     * UUID of the moderator/administrator assigned to review this appeal.
     *
     * Required when transitioning appeal to 'in_review' status. Must be
     * different from the original decision moderator to prevent bias and
     * conflict of interest in appeal review. Identifies the independent
     * reviewer responsible for the appeal decision.
     *
     * Validation enforces: reviewer_id ≠ original decision moderator_id,
     * reviewer exists and is active moderator/administrator.
     */
    appeal_reviewer_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Result of the appeal review when a final decision is made.
     *
     * Examples of valid outcomes:
     *
     * - `overturned_restore_content`: Original content removal decision
     *   reversed, content restored
     * - `overturned_reinstate_user`: Ban or suspension overturned, user
     *   access restored
     * - `suspension_reduced_to_warning`: Suspension reduced to formal warning
     * - `ban_reduced_to_suspension`: Permanent ban reduced to temporary
     *   suspension
     * - `decision_upheld`: Original moderation decision was justified, no
     *   change
     * - `partial_reduction_warning_removed`: Multiple violations had
     *   different outcomes, this one cleared
     *
     * Required when status transitions to 'approved', 'denied', or
     * 'reduced'. Null while status is 'submitted' or 'in_review' without
     * final decision. Describes the specific action taken or decision
     * rendered by reviewer. Must be meaningful and reflect actual outcome
     * applied.
     */
    appeal_outcome?: string | null | undefined;

    /**
     * Moderator/administrator's explanation of the appeal decision.
     *
     * Shown to the appellant to justify the outcome decision. Should
     * provide clear, professional reasoning for why the appeal was
     * approved, denied, or resulted in reduced punishment. Explains how
     * reviewer assessed the appeal reason and any supporting evidence.
     *
     * Null while appeal is pending review or in_review state without final
     * decision. Documents the review justification for transparency,
     * record-keeping, and future reference. Should address the appellant's
     * specific claims and explain the reviewer's reasoning.
     *
     * Example: 'After reviewing the original thread context, the flagged
     * comment was indeed a factual rebuttal, not a personal attack as
     * originally reported. Decision reversed and content restored.'
     */
    reviewer_notes?: string | null | undefined;

    /**
     * Soft delete timestamp (ISO 8601 UTC).
     *
     * Null for active appeals. Set when an appeal is withdrawn by member or
     * archived by administrator. Enables logical deletion while preserving
     * audit trail integrity and historical records. Withdrawn appeals
     * remain visible to moderators/admins for compliance auditing.
     *
     * Example usage: Member changes mind and withdraws appeal, or appeal is
     * archived after resolution.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
