import { tags } from "typia";

import { ICommunityPlatformCategory } from "./ICommunityPlatformCategory";
import { ICommunityPlatformMember } from "./ICommunityPlatformMember";

/**
 * Core community entity representing a discussion space or organizational unit
 * on the platform.
 *
 * Communities are self-contained spaces where members create posts, comments,
 * and engage in discussions. Each community has its own configuration, rules,
 * moderators, and membership subscriptions. Communities are fundamental to
 * platform architecture - all posts and comments belong to specific
 * communities.
 *
 * Community Lifecycle: Created by authenticated members who automatically
 * become creators with full permissions. Immediately visible (if public) or
 * accessible to creator (if private). Can be modified by creator and senior
 * moderators. Can be soft-deleted (with 30-day recovery window) or permanently
 * deleted by admins.
 *
 * Community Configuration: Each community controls post creation permissions
 * (open_to_all, moderators_only, etc.), allowed post types (text, images,
 * links), visibility (public/private), and category classification. Settings
 * can be updated anytime by creator/moderators and affect all subsequent
 * content operations.
 *
 * Community Relationships: Communities maintain relationships to categories
 * (classification), members (creator and subscribers), posts (content),
 * comments (discussion), and subscription tracking. Communities are not
 * globally unique by name but identifiers are globally unique and immutable.
 *
 * Community Metrics: Track subscriber count (real-time members), post count
 * (engagement), and comment count (discussion level). These metrics inform
 * discovery algorithms, trending calculations, and community ranking.
 *
 * Relation Handling: Foreign key fields (category, creator) are transformed to
 * complete object references using .ISummary types. This transformation enables
 * atomic read operations - clients receive complete context (category name,
 * creator info) in a single API response without requiring additional calls.
 * The .ISummary pattern prevents circular reference risks while maintaining API
 * consistency.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformCommunity = {
  /**
   * Unique identifier for the community (primary key, UUID format).
   *
   * Generated automatically when community is created. Immutable and globally
   * unique across the platform. Used internally for relationships and API
   * operations.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Unique, URL-safe community identifier (handle) used in URLs and for
   * discovery.
   *
   * Format restricted to lowercase letters, numbers, and underscores only
   * (3-32 characters). Immutable after community creation. Globally unique
   * across entire platform - no two communities can share the same
   * identifier. Used in community URLs (e.g., r/[identifier]). Example:
   * 'tech_news', 'gaming_discussions'.
   *
   * This field distinguishes communities by human-readable names rather than
   * UUIDs, enabling intuitive URL structures and community search.
   */
  identifier: string &
    tags.MinLength<3> &
    tags.MaxLength<32> &
    tags.Pattern<"^[a-z0-9_]+$">;

  /**
   * Community display name shown to users in headers and search results.
   *
   * Length: 3-100 characters. May contain spaces and special characters. Not
   * required to be globally unique - multiple communities can share the same
   * display name. Used in community headers, directory listings, and search
   * result titles. Distinguished from `identifier` which is the unique
   * URL-safe handle.
   */
  name: string & tags.MinLength<3> & tags.MaxLength<100>;

  /**
   * Optional community description explaining community purpose, topic scope,
   * and culture.
   *
   * Length: 0-500 characters. Shown in community directory, sidebar, and
   * profile pages. Used to communicate community rules, focus areas, and
   * member expectations. Can be updated by community creator anytime.
   * Optional field - can be null if not set.
   */
  description?: (string & tags.MaxLength<500>) | null | undefined;

  /**
   * Community access level controlling visibility and membership.
   *
   * Public communities are discoverable in the public directory, appear in
   * search results, and posts are readable by anyone. Private communities are
   * hidden from discovery and require subscription approval. Can be toggled
   * by community creator - changing visibility cascades to affect
   * post/comment visibility in public discovery.
   */
  visibility: "public" | "private";

  /**
   * Restriction level controlling who can create posts in the community.
   *
   * Default: 'open_to_all'. Allows community creators to moderate post
   * quality and prevent spam. Options range from completely open (any member)
   * to restricted (moderators only, karma/age requirements). Can be adjusted
   * by community creator based on community needs and maturity level. Affects
   * new post submission workflow and permissions.
   */
  post_creation_restriction:
    | "open_to_all"
    | "moderators_only"
    | "approved_members_only"
    | "karma_requirement"
    | "account_age_requirement";

  /**
   * Allowed post content types restricting format of posts in the community.
   *
   * Default: 'all_types'. Enables communities to enforce content policies
   * (e.g., art communities might use 'images_only', discussion communities
   * might use 'text_only'). Can be modified by community creator. Affects
   * post creation UI and validation - posts not matching the restriction are
   * rejected.
   */
  post_type_restriction:
    | "all_types"
    | "text_only"
    | "text_and_images"
    | "text_and_links"
    | "images_only";

  /**
   * Current number of members subscribed to this community.
   *
   * Incremented when members subscribe, decremented when unsubscribe.
   * Automatically set to 1 when community is created (creator is
   * auto-subscribed). Used for community discovery rankings, trending
   * calculations, and activity metrics. Real-time value reflecting current
   * community size and engagement potential.
   */
  subscriber_count: number & tags.Type<"int32"> & tags.Minimum<0>;

  /**
   * Total count of non-deleted posts in this community.
   *
   * Incremented when posts created, decremented when deleted (soft-delete).
   * Provides activity engagement metric. Used in community statistics and
   * feeds. Excludes archived/deleted posts.
   */
  post_count: number & tags.Type<"int32"> & tags.Minimum<0>;

  /**
   * Total count of non-deleted comments across all posts in this community.
   *
   * Provides community engagement level indicator. Incremented when comments
   * created, decremented when deleted. Reflects discussion activity across
   * all posts in community. Excludes deleted/archived comments.
   */
  comment_count: number & tags.Type<"int32"> & tags.Minimum<0>;

  /**
   * Timestamp when community was created (immutable after creation).
   *
   * Stored in UTC. Used for community age calculations, discovery sorting
   * (new communities), and audit trail. Automatically set to current
   * timestamp when community is created.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when community was last modified (settings, rules, description
   * changed).
   *
   * Updated whenever community configuration is modified. Used for tracking
   * administrative actions, optimistic locking, and sorting communities by
   * recent activity. Automatically updated by system on modifications.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft-delete timestamp for community archival with recovery window.
   *
   * Null if community is active. Set to deletion time if community is
   * archived/deleted. Allows community recovery within grace period
   * (typically 30 days). Communities with deleted_at set are hidden from
   * search, discovery, and public directory but preserved in database. Used
   * to implement soft-delete pattern enabling data recovery and audit trail
   * preservation.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Community category classification providing context and enabling
   * discovery.
   *
   * References the category this community belongs to (e.g., Technology,
   * Entertainment, Sports). Determines community topic area and affects
   * discovery and recommendation algorithms. Every community must be assigned
   * to a category. Returned as complete object with category details (id,
   * name, slug) enabling atomic read operations without requiring separate
   * GET calls.
   *
   * Transformed from community_platform_category_id FK to provide complete
   * context. Uses .ISummary to prevent circular reference risks and maintain
   * optimal response payload size.
   */
  category: ICommunityPlatformCategory.ISummary;

  /**
   * Community creator identity and public profile information.
   *
   * References the member who created this community and automatically became
   * the community creator with all moderator permissions. Includes creator's
   * public information (id, name, avatar) for display in community headers
   * and attribution. The creator can transfer ownership to another member
   * through designated endpoint. Critical for authorization - creator can
   * modify settings and delete community.
   *
   * Transformed from community_platform_member_id FK to provide complete
   * context. Uses .ISummary to prevent circular reference risks and maintain
   * optimal response payload size.
   */
  creator: ICommunityPlatformMember.ISummary;
};
export namespace ICommunityPlatformCommunity {
  /**
   * Query parameters for searching, filtering, and paginating communities.
   *
   * Supports text search, visibility filtering, category filtering, and
   * various sort options. All parameters are optional - can be combined for
   * complex queries.
   */
  export type IRequest = {
    /**
     * Search keyword for filtering communities by name or identifier.
     *
     * Searches community names and identifiers for matching patterns.
     * Optional - omit for no text filtering. Supports partial matching on
     * both name and identifier fields.
     */
    search?:
      | (string & tags.MinLength<1> & tags.MaxLength<100>)
      | null
      | undefined;

    /**
     * Filter communities by visibility level (public or private).
     *
     * Optional - omit to include both public and private communities (based
     * on access permissions). Useful for discovery filtering.
     */
    visibility?: "public" | "private" | null | undefined;

    /**
     * Filter communities by category classification.
     *
     * Optional - omit to include all categories. Narrows results to
     * specific topic area.
     */
    category_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Sort order for community results.
     *
     * Optional - default behavior if omitted. Options: 'name'
     * (alphabetical), 'created_at' (newest first), 'subscriber_count' (most
     * subscribed), 'post_count' (most active).
     */
    sort?:
      | "name"
      | "created_at"
      | "subscriber_count"
      | "post_count"
      | null
      | undefined;

    /**
     * Sort direction (ascending or descending).
     *
     * Optional - default descending if omitted. Used with sort parameter to
     * control ordering direction.
     */
    direction?: "asc" | "desc" | null | undefined;

    /**
     * Maximum number of results to return per page.
     *
     * Default: 20. Maximum: 100. Controls pagination page size.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Number of results to skip for pagination.
     *
     * Default: 0. Used for offset-based pagination to retrieve subsequent
     * pages.
     */
    offset?: (number & tags.Type<"int32"> & tags.Minimum<0>) | undefined;
  };

  /**
   * Lightweight community representation for use in list views and embedded
   * references.
   *
   * Contains essential community information for efficient display in
   * community lists, trending feeds, moderator assignment contexts, and as
   * embedded references in other entities. Optimized for performance when
   * communities are referenced in high-volume contexts.
   *
   * Excludes full relationship objects (category, creator) and complex
   * configuration to maintain optimal payload size while providing sufficient
   * context for UI display. Suitable for paginated list responses and
   * embedded contexts where full community details are not required.
   *
   * Field Summary: Includes unique identifiers (id, identifier), display
   * information (name), engagement metrics (subscriber_count, post_count),
   * and creation timestamp. This subset enables efficient caching and quick
   * rendering in UI components without full DTO overhead.
   */
  export type ISummary = {
    /**
     * Unique identifier for the community.
     *
     * Generated automatically when community is created. Immutable and
     * globally unique across the platform. Used internally for
     * relationships and API operations.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Unique, URL-safe community identifier (handle) used in URLs and for
     * discovery.
     *
     * Format restricted to lowercase letters, numbers, and underscores only
     * (3-32 characters). Immutable after community creation. Globally
     * unique across entire platform. Used in community URLs (e.g.,
     * r/[identifier]).
     */
    identifier: string &
      tags.MinLength<3> &
      tags.MaxLength<32> &
      tags.Pattern<"^[a-z0-9_]+$">;

    /**
     * Community display name shown to users in headers and search results.
     *
     * Length: 3-100 characters. May contain spaces and special characters.
     * Not required to be globally unique - multiple communities can share
     * the same display name.
     */
    name: string & tags.MinLength<3> & tags.MaxLength<100>;

    /**
     * Current number of members subscribed to this community.
     *
     * Incremented when members subscribe, decremented when unsubscribe.
     * Used for community discovery rankings, trending calculations, and
     * activity metrics. Real-time value reflecting current community size.
     */
    subscriber_count: number & tags.Type<"int32"> & tags.Minimum<0>;

    /**
     * Total count of non-deleted posts in this community.
     *
     * Incremented when posts created, decremented when deleted. Provides
     * activity engagement metric. Excludes archived/deleted posts.
     */
    post_count: number & tags.Type<"int32"> & tags.Minimum<0>;

    /**
     * Timestamp when community was created.
     *
     * Stored in UTC. Immutable after creation. Used for community age
     * calculations and discovery sorting.
     */
    created_at: string & tags.Format<"date-time">;
  };

  /**
   * Request body for creating a new community.
   *
   * Captures essential community configuration at creation time. The
   * authenticated member becomes the community creator automatically - no
   * creator_id field is accepted in the request. Community identifiers
   * (handles) are globally unique and immutable after creation, so they must
   * be chosen carefully.
   *
   * Community names are not required to be globally unique, allowing
   * flexibility in naming. Description is optional. All settings can be
   * modified later through update operations, except the community identifier
   * which remains permanent.
   *
   * Relation Handling: The category_slug field uses the category's unique
   * code identifier rather than UUID, following the principle of using unique
   * code fields in request bodies for improved API consistency and developer
   * experience. Upon successful creation, the response DTO transforms this to
   * a complete category object reference (category:
   * ICommunityPlatformCategory.ISummary).
   *
   * FK Pattern: Create DTO uses code fields (category_slug) for external
   * references, while response DTOs use transformed object references
   * providing complete context in single response.
   */
  export type ICreate = {
    /**
     * Community display name. Length: 3-100 characters. May contain spaces
     * and special characters.
     */
    name: string & tags.MinLength<3> & tags.MaxLength<100>;

    /**
     * Unique, URL-safe community identifier. Format: lowercase letters,
     * numbers, underscores only. Will be globally unique and immutable
     * after creation.
     */
    identifier: string &
      tags.MinLength<3> &
      tags.MaxLength<32> &
      tags.Pattern<"^[a-z0-9_]+$">;

    /**
     * Optional community description. Length: 0-500 characters. Explains
     * purpose and scope of the community. Can be omitted or set to null.
     */
    description?: (string & tags.MaxLength<500>) | null | undefined;

    /**
     * Community access level: 'public' (discoverable by all users) or
     * 'private' (restricted to approved members). Default: 'public'.
     */
    visibility: "public" | "private";

    /**
     * Restriction level for who can create posts. Controls initial post
     * permissions. Default: 'open_to_all'.
     */
    post_creation_restriction:
      | "open_to_all"
      | "moderators_only"
      | "approved_members_only"
      | "karma_requirement"
      | "account_age_requirement";

    /**
     * Allowed post types. Restricts content format per community rules.
     * Default: 'all_types'.
     */
    post_type_restriction:
      | "all_types"
      | "text_only"
      | "text_and_images"
      | "text_and_links"
      | "images_only";

    /**
     * Category slug identifier for the community. References the category
     * this community belongs to (e.g., 'technology', 'entertainment',
     * 'sports'). Uses unique code field instead of UUID for consistency
     * with endpoint path parameters and improved developer experience.
     */
    category_slug: string;
  };

  /**
   * Request body for updating an existing community's configuration and
   * settings.
   *
   * All fields are optional - only include fields you want to modify.
   * Supports partial updates where only modified fields are provided.
   * Community identifier (handle) cannot be changed after creation as it is
   * immutable. Community creator cannot be changed through this endpoint -
   * ownership transfer would require a dedicated endpoint if supported.
   *
   * Authorization: Only community creators, senior moderators, and platform
   * administrators can modify community settings. Updates are restricted
   * based on moderator tier - junior moderators cannot modify community
   * settings.
   *
   * Fields: Name and description can be modified freely (name: 3-100 chars,
   * description: 0-500 chars or null). Visibility can be toggled between
   * public/private. Post restrictions control content creation policies and
   * can be adjusted based on community needs. Category can be reassigned to a
   * different topic area.
   *
   * Audit: All setting changes are recorded in an immutable audit trail
   * capturing timestamp, user ID of modifier, and field changes. Community
   * last-modified timestamp (updated_at) is automatically updated on any
   * modification.
   *
   * Cascading Effects: When visibility changes from private to public, all
   * existing posts become discoverable in public directory. When changing
   * from public to private, posts are hidden from public search. When post
   * creation restrictions change from 'open to all' to 'moderators only', new
   * posts from regular members are rejected.
   */
  export type IUpdate = {
    /**
     * Community display name shown to users. Length: 3-100 characters. May
     * contain spaces and special characters. Used in community headers,
     * directory listings, and search results. Distinct from the immutable
     * 'identifier' field which serves as the URL-safe handle.
     */
    name?: (string & tags.MinLength<3> & tags.MaxLength<100>) | undefined;

    /**
     * Community description explaining purpose and scope. Length: 0-500
     * characters. Optional field. Used in community directory, sidebar, and
     * profile pages to communicate community rules, focus areas, and member
     * expectations. Can be cleared by passing null.
     */
    description?: (string & tags.MaxLength<500>) | null | undefined;

    /**
     * Community access level controlling visibility and membership.
     *
     * Public communities are discoverable in the public directory, appear
     * in search results, and posts are readable by anyone. Private
     * communities are hidden from discovery and require subscription
     * approval. Can be toggled by community creator - changing visibility
     * cascades to affect post/comment visibility in public discovery.
     */
    visibility?: "public" | "private" | undefined;

    /**
     * Restriction level controlling who can create posts in the community.
     *
     * Default: 'open_to_all'. Allows community creators to moderate post
     * quality and prevent spam. Options range from completely open (any
     * member) to restricted (moderators only, karma/age requirements). Can
     * be adjusted by community creator based on community needs and
     * maturity level. Affects new post submission workflow and
     * permissions.
     */
    post_creation_restriction?:
      | "open_to_all"
      | "moderators_only"
      | "approved_members_only"
      | "karma_requirement"
      | "account_age_requirement"
      | undefined;

    /**
     * Allowed post content types restricting format of posts in the
     * community.
     *
     * Default: 'all_types'. Enables communities to enforce content policies
     * (e.g., art communities might use 'images_only', discussion
     * communities might use 'text_only'). Can be modified by community
     * creator. Affects post creation UI and validation - posts not matching
     * the restriction are rejected.
     */
    post_type_restriction?:
      | "all_types"
      | "text_only"
      | "text_and_images"
      | "text_and_links"
      | "images_only"
      | undefined;

    /**
     * Unique identifier of the category this community belongs to.
     * References community_platform_categories.id.
     *
     * Determines community topic area (Technology, Entertainment, Sports,
     * etc.) and affects community discovery and recommendations.
     * Communities must be assigned to a valid category. Can be updated to
     * recategorize the community. Updates are restricted to valid category
     * IDs that exist in the system.
     */
    category_id?: (string & tags.Format<"uuid">) | undefined;
  };

  export namespace IPasswordResetConfirm {
    /**
     * Request to complete a password reset for a member account.
     *
     * This DTO completes the password reset workflow after a member has
     * requested a reset and received a reset token via email. The member
     * provides the reset token (which was sent to their email) along with
     * their new password.
     *
     * The system validates that the reset token is valid, not expired (1
     * hour validity window), and has not been used previously. The new
     * password must meet security requirements: minimum 8 characters,
     * contain uppercase letters, lowercase letters, numbers, and special
     * characters. The new password cannot match any of the member's last 5
     * passwords.
     *
     * Upon successful validation and password change, all existing refresh
     * tokens for the member are invalidated, forcing logout from all
     * devices. A confirmation email is sent to verify the password change.
     */
    export type ICreate = {
      /**
       * The password reset token received via email. This is a
       * cryptographically secure, single-use token generated when the
       * member requested the password reset. The token is valid for 1
       * hour from generation. The token uniquely identifies the password
       * reset request and the member account.
       */
      token: string;

      /**
       * The new password for the member account. Must meet security
       * requirements: minimum 8 characters, must contain at least one
       * uppercase letter, one lowercase letter, one number, and one
       * special character. Cannot match any of the member's last 5
       * passwords to prevent reuse of compromised credentials.
       */
      password: string & tags.MinLength<8>;
    };
  }
}
