import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IPageIRedditCommunityPost } from "../../../../structures/IPageIRedditCommunityPost";
import { IRedditCommunityPost } from "../../../../structures/IRedditCommunityPost";

/**
 * Retrieve a paginated feed of popular posts from all communities across the platform, sorted by user-selected criteria.
 *
 * This endpoint delivers the platform's popular feed, which is accessible to both authenticated members and anonymous guests. The feed aggregates posts from every public community on the platform, ranked according to one of four algorithms: 'hot', 'new', 'top', or 'controversial', with optional time-based filters ('today', 'week', 'month', 'year', 'all').
 *
 * Results are always limited to posts with visibility = 'public' and are excluded from the feed if they have been deleted, archived, or reported and dismissed. The operation supports cursor-based pagination with a fixed page size of 25, ensuring consistent performance at scale.
 *
 * Unlike the home feed, this endpoint does not require authentication and reflects the platform's most engaging content to drive discovery and user growth. The response structure matches the IPageIRedditCommunityPost.ISummary schema to ensure consistency between all paginated list endpoints.
 *
 * This operation serves as the backbone of the platform's public visibility and is critical for user onboarding and content discovery.
 *
 * Dependencies: Requires the POST /posts endpoint to create posts, and POST /posts/{postId}/vote to influence sorting metrics. Uses the reddit_community_posts and reddit_community_communities tables as primary sources.
 *
 * @param props.connection
 * @param props.body Filter, sort, and pagination parameters for popular feed
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query reddit_community_posts table with joins to reddit_community_communities for community details. Filter only public posts. Apply sorting algorithm based on request: hot (score / time decay), new (createdAt descending), top (total vote score), controversial (ratio of upvotes to downvotes). Apply time filter if specified: today, week, month, year, all. Return paginated results with cursor-based pagination (limit 25). Include calculated fields: voteScore, commentCount, author.username, community.name. Exclude posts with status = 'deleted' or 'archived'.
 * @path /redditCommunity/feeds/popular
 * @accessor api.functional.redditCommunity.feeds.popular.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Filter, sort, and pagination parameters for popular feed
     */
    body: IRedditCommunityPost.IRequest;
  };
  export type Body = IRedditCommunityPost.IRequest;
  export type Response = IPageIRedditCommunityPost.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditCommunity/feeds/popular",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditCommunity/feeds/popular";
  export const random = (): IPageIRedditCommunityPost.ISummary =>
    typia.random<IPageIRedditCommunityPost.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
