import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IREdditLikeCommunityReport } from "../../../../../api/structures/IREdditLikeCommunityReport";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { postRedditLikeCommunityMemberReportsReportIdDismiss } from "../../../../../providers/postRedditLikeCommunityMemberReportsReportIdDismiss";

@Controller("/redditLikeCommunity/member/reports/:reportId/dismiss")
export class RedditlikecommunityMemberReportsDismissController {
  /**
   * Dismiss a pending community report, rejecting it while keeping the reported content intact.
   *
   * When a moderator dismisses a report, the report status transitions from pending to dismissed. The reported content (post or comment) remains fully visible and unaffected. The dismissed report is removed from the active moderator report list via soft-deletion, but audit history is preserved.
   *
   * Only moderators with an active moderator role in the community where the report was filed can dismiss reports. Reports that have already been approved or dismissed cannot be acted upon again — attempting to dismiss an already-handled report results in an error.
   *
   * @param connection
   * @param reportId UUID of the report to dismiss (scoped to community).
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification 1. Validate the current member has an active
     *   moderator role (OWNER or MODERATOR) in the community associated with
     *   the report (reddit_like_community_community_id).
   *
   * 2. Query the report by UUID from reddit_like_community_reports table.
   *
   * 3. Verify the report exists and is not soft-deleted (deleted_at IS NULL).
   *
   * 4. Verify the report status is 'pending'. Reject with error if status is already 'approved' or 'dismissed' — a report cannot be dismissed after it has been handled.
   *
   * 5. If validation passes, update the report in a single transaction:
   *    - Set status to 'dismissed'
   *    - Set resolved_by_member_id to the current member's UUID
   *    - Set resolved_at to the current timestamp
   *    - Set deleted_at to the current timestamp (soft-delete for removal from visible queue)
   *    - Update updated_at to the current timestamp
   *
   * 6. Return the updated report record including the new status, resolved_by_member_id, resolved_at, and deleted_at values.
   *
   * Edge cases:
   * - Report not found: return 404
   * - Report already handled (approved/dismissed): return 409 conflict
   * - Current member is not a moderator in the report's community: return 403 forbidden
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async postByReportid(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("reportId")
    reportId: string & tags.Format<"uuid">,
  ): Promise<IREdditLikeCommunityReport> {
    try {
      return await postRedditLikeCommunityMemberReportsReportIdDismiss({
        member,
        reportId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
