import { Module } from "@nestjs/common";

import { DiscussionboardAdministratorAdministrator_grade_changesController } from "./controllers/discussionBoard/administrator/administrator-grade-changes/DiscussionboardAdministratorAdministrator_grade_changesController";
import { DiscussionboardAdministratorAdministratorBanController } from "./controllers/discussionBoard/administrator/administrator/ban/DiscussionboardAdministratorAdministratorBanController";
import { DiscussionboardAdministratorAdministratorBanned_usersController } from "./controllers/discussionBoard/administrator/administrator/banned-users/DiscussionboardAdministratorAdministratorBanned_usersController";
import { DiscussionboardAdministratorAdministratorBansController } from "./controllers/discussionBoard/administrator/administrator/bans/DiscussionboardAdministratorAdministratorBansController";
import { DiscussionboardAdministratorAdministratorGradesController } from "./controllers/discussionBoard/administrator/administrator/grades/DiscussionboardAdministratorAdministratorGradesController";
import { DiscussionboardAdministratorAdministratorController } from "./controllers/discussionBoard/administrator/administrator/unban/DiscussionboardAdministratorAdministratorController";
import { DiscussionboardAdministratorAdministratorUnbansController } from "./controllers/discussionBoard/administrator/administrator/unbans/DiscussionboardAdministratorAdministratorUnbansController";
import { DiscussionboardAdministratorArticle_search_indexesController } from "./controllers/discussionBoard/administrator/article-search-indexes/DiscussionboardAdministratorArticle_search_indexesController";
import { DiscussionboardAdministratorArticle_statisticsOverviewController } from "./controllers/discussionBoard/administrator/article-statistics/overview/DiscussionboardAdministratorArticle_statisticsOverviewController";
import { DiscussionboardAdministratorArticle_tag_mappingsController } from "./controllers/discussionBoard/administrator/article-tag-mappings/DiscussionboardAdministratorArticle_tag_mappingsController";
import { DiscussionboardAdministratorArticlesController } from "./controllers/discussionBoard/administrator/articles/DiscussionboardAdministratorArticlesController";
import { DiscussionboardAdministratorArticlesFilesController } from "./controllers/discussionBoard/administrator/articles/files/DiscussionboardAdministratorArticlesFilesController";
import { DiscussionboardAdministratorArticlesImagesController } from "./controllers/discussionBoard/administrator/articles/images/DiscussionboardAdministratorArticlesImagesController";
import { DiscussionboardAdministratorArticlesTag_mappingsController } from "./controllers/discussionBoard/administrator/articles/tag-mappings/DiscussionboardAdministratorArticlesTag_mappingsController";
import { DiscussionboardAdministratorAuditlogsController } from "./controllers/discussionBoard/administrator/auditLogs/DiscussionboardAdministratorAuditlogsController";
import { DiscussionboardAdministratorCommentsController } from "./controllers/discussionBoard/administrator/comments/DiscussionboardAdministratorCommentsController";
import { DiscussionboardAdministratorFeatureflagsController } from "./controllers/discussionBoard/administrator/featureFlags/DiscussionboardAdministratorFeatureflagsController";
import { DiscussionboardAdministratorHealthchecksController } from "./controllers/discussionBoard/administrator/healthChecks/DiscussionboardAdministratorHealthchecksController";
import { DiscussionboardAdministratorScheduledtasksController } from "./controllers/discussionBoard/administrator/scheduledTasks/DiscussionboardAdministratorScheduledtasksController";
import { DiscussionboardAdministratorSectionadminlogsController } from "./controllers/discussionBoard/administrator/sectionAdminLogs/DiscussionboardAdministratorSectionadminlogsController";
import { DiscussionboardAdministratorSectionsController } from "./controllers/discussionBoard/administrator/sections/DiscussionboardAdministratorSectionsController";
import { DiscussionboardAdministratorSystemmessagesController } from "./controllers/discussionBoard/administrator/systemMessages/DiscussionboardAdministratorSystemmessagesController";
import { DiscussionboardAdministratorSystemsettingsController } from "./controllers/discussionBoard/administrator/systemSettings/DiscussionboardAdministratorSystemsettingsController";
import { DiscussionboardAdministratorTag_usage_statsController } from "./controllers/discussionBoard/administrator/tag-usage-stats/DiscussionboardAdministratorTag_usage_statsController";
import { DiscussionboardAdministratorTagsController } from "./controllers/discussionBoard/administrator/tags/DiscussionboardAdministratorTagsController";
import { DiscussionboardAdministratorTagsUsage_statsController } from "./controllers/discussionBoard/administrator/tags/usage-stats/DiscussionboardAdministratorTagsUsage_statsController";
import { DiscussionboardAdministratorsController } from "./controllers/discussionBoard/administrators/DiscussionboardAdministratorsController";
import { DiscussionboardAuthAdministratorController } from "./controllers/discussionBoard/auth/administrator/DiscussionboardAuthAdministratorController";
import { DiscussionboardAuthGuestController } from "./controllers/discussionBoard/auth/guest/DiscussionboardAuthGuestController";
import { DiscussionboardAuthRegistereduserController } from "./controllers/discussionBoard/auth/registeredUser/DiscussionboardAuthRegistereduserController";
import { DiscussionboardAuthSuperadministratorController } from "./controllers/discussionBoard/auth/superAdministrator/DiscussionboardAuthSuperadministratorController";
import { DiscussionboardCommentsSnapshotsController } from "./controllers/discussionBoard/comments/snapshots/DiscussionboardCommentsSnapshotsController";
import { DiscussionboardGuestSearchArticlesController } from "./controllers/discussionBoard/guest/search/articles/DiscussionboardGuestSearchArticlesController";
import { DiscussionboardGuestSectionsController } from "./controllers/discussionBoard/guest/sections/DiscussionboardGuestSectionsController";
import { DiscussionboardGuestSessionsController } from "./controllers/discussionBoard/guest/sessions/DiscussionboardGuestSessionsController";
import { DiscussionboardGuestsController } from "./controllers/discussionBoard/guests/DiscussionboardGuestsController";
import { DiscussionboardRegistereduserAdministratorRequestsController } from "./controllers/discussionBoard/registeredUser/administrator/requests/DiscussionboardRegistereduserAdministratorRequestsController";
import { DiscussionboardRegistereduserArticle_tag_mappingsController } from "./controllers/discussionBoard/registeredUser/article-tag-mappings/DiscussionboardRegistereduserArticle_tag_mappingsController";
import { DiscussionboardRegistereduserArticlesController } from "./controllers/discussionBoard/registeredUser/articles/DiscussionboardRegistereduserArticlesController";
import { DiscussionboardRegistereduserArticlesFilesController } from "./controllers/discussionBoard/registeredUser/articles/files/DiscussionboardRegistereduserArticlesFilesController";
import { DiscussionboardRegistereduserArticlesImagesController } from "./controllers/discussionBoard/registeredUser/articles/images/DiscussionboardRegistereduserArticlesImagesController";
import { DiscussionboardRegistereduserArticlesTag_mappingsController } from "./controllers/discussionBoard/registeredUser/articles/tag-mappings/DiscussionboardRegistereduserArticlesTag_mappingsController";
import { DiscussionboardRegistereduserCommentsController } from "./controllers/discussionBoard/registeredUser/comments/DiscussionboardRegistereduserCommentsController";
import { DiscussionboardRegistereduserEmailverificationsController } from "./controllers/discussionBoard/registeredUser/emailVerifications/DiscussionboardRegistereduserEmailverificationsController";
import { DiscussionboardRegistereduserPasswordresetsController } from "./controllers/discussionBoard/registeredUser/passwordResets/DiscussionboardRegistereduserPasswordresetsController";
import { DiscussionboardRegistereduserProfileController } from "./controllers/discussionBoard/registeredUser/profile/DiscussionboardRegistereduserProfileController";
import { DiscussionboardRegistereduserSearchArticlesController } from "./controllers/discussionBoard/registeredUser/search/articles/DiscussionboardRegistereduserSearchArticlesController";
import { DiscussionboardRegistereduserSectionsController } from "./controllers/discussionBoard/registeredUser/sections/DiscussionboardRegistereduserSectionsController";
import { DiscussionboardRegistereduserTagsController } from "./controllers/discussionBoard/registeredUser/tags/DiscussionboardRegistereduserTagsController";
import { DiscussionboardRegisteredusersController } from "./controllers/discussionBoard/registeredUsers/DiscussionboardRegisteredusersController";
import { DiscussionboardSuperadministratorAdministrator_grade_changesController } from "./controllers/discussionBoard/superAdministrator/administrator-grade-changes/DiscussionboardSuperadministratorAdministrator_grade_changesController";
import { DiscussionboardSuperadministratorAdministratorBansController } from "./controllers/discussionBoard/superAdministrator/administrator/bans/DiscussionboardSuperadministratorAdministratorBansController";
import { DiscussionboardSuperadministratorAdministratorDemoteController } from "./controllers/discussionBoard/superAdministrator/administrator/demote/DiscussionboardSuperadministratorAdministratorDemoteController";
import { DiscussionboardSuperadministratorAdministratorGradesController } from "./controllers/discussionBoard/superAdministrator/administrator/grades/DiscussionboardSuperadministratorAdministratorGradesController";
import { DiscussionboardSuperadministratorAdministratorPromoteController } from "./controllers/discussionBoard/superAdministrator/administrator/promote/DiscussionboardSuperadministratorAdministratorPromoteController";
import { DiscussionboardSuperadministratorAdministratorPromotionsController } from "./controllers/discussionBoard/superAdministrator/administrator/promotions/DiscussionboardSuperadministratorAdministratorPromotionsController";
import { DiscussionboardSuperadministratorAdministratorRequestsController } from "./controllers/discussionBoard/superAdministrator/administrator/requests/DiscussionboardSuperadministratorAdministratorRequestsController";
import { DiscussionboardSuperadministratorAdministratorRequestsApproveController } from "./controllers/discussionBoard/superAdministrator/administrator/requests/approve/DiscussionboardSuperadministratorAdministratorRequestsApproveController";
import { DiscussionboardSuperadministratorAdministratorRequestsRejectController } from "./controllers/discussionBoard/superAdministrator/administrator/requests/reject/DiscussionboardSuperadministratorAdministratorRequestsRejectController";
import { DiscussionboardSuperadministratorAdministratorUnbansController } from "./controllers/discussionBoard/superAdministrator/administrator/unbans/DiscussionboardSuperadministratorAdministratorUnbansController";
import { DiscussionboardSuperadministratorArticle_reportsActivityController } from "./controllers/discussionBoard/superAdministrator/article-reports/activity/DiscussionboardSuperadministratorArticle_reportsActivityController";
import { DiscussionboardSuperadministratorArticlesController } from "./controllers/discussionBoard/superAdministrator/articles/DiscussionboardSuperadministratorArticlesController";
import { DiscussionboardSuperadministratorArticlesFilesController } from "./controllers/discussionBoard/superAdministrator/articles/files/DiscussionboardSuperadministratorArticlesFilesController";
import { DiscussionboardSuperadministratorArticlesImagesController } from "./controllers/discussionBoard/superAdministrator/articles/images/DiscussionboardSuperadministratorArticlesImagesController";
import { DiscussionboardSuperadministratorArticlesTag_mappingsController } from "./controllers/discussionBoard/superAdministrator/articles/tag-mappings/DiscussionboardSuperadministratorArticlesTag_mappingsController";
import { DiscussionboardSuperadministratorAuditlogsController } from "./controllers/discussionBoard/superAdministrator/auditLogs/DiscussionboardSuperadministratorAuditlogsController";
import { DiscussionboardSuperadministratorFeatureflagsController } from "./controllers/discussionBoard/superAdministrator/featureFlags/DiscussionboardSuperadministratorFeatureflagsController";
import { DiscussionboardSuperadministratorHealthchecksController } from "./controllers/discussionBoard/superAdministrator/healthChecks/DiscussionboardSuperadministratorHealthchecksController";
import { DiscussionboardSuperadministratorScheduledtasksController } from "./controllers/discussionBoard/superAdministrator/scheduledTasks/DiscussionboardSuperadministratorScheduledtasksController";
import { DiscussionboardSuperadministratorSectionadminlogsController } from "./controllers/discussionBoard/superAdministrator/sectionAdminLogs/DiscussionboardSuperadministratorSectionadminlogsController";
import { DiscussionboardSuperadministratorSectionsController } from "./controllers/discussionBoard/superAdministrator/sections/DiscussionboardSuperadministratorSectionsController";
import { DiscussionboardSuperadministratorSystemmessagesController } from "./controllers/discussionBoard/superAdministrator/systemMessages/DiscussionboardSuperadministratorSystemmessagesController";
import { DiscussionboardSuperadministratorSystemsettingsController } from "./controllers/discussionBoard/superAdministrator/systemSettings/DiscussionboardSuperadministratorSystemsettingsController";
import { DiscussionboardSuperadministratorsController } from "./controllers/discussionBoard/superAdministrators/DiscussionboardSuperadministratorsController";

@Module({
  controllers: [
    DiscussionboardAuthGuestController,
    DiscussionboardAuthRegistereduserController,
    DiscussionboardAuthAdministratorController,
    DiscussionboardAuthSuperadministratorController,
    DiscussionboardGuestSessionsController,
    DiscussionboardGuestsController,
    DiscussionboardRegistereduserProfileController,
    DiscussionboardRegisteredusersController,
    DiscussionboardRegistereduserPasswordresetsController,
    DiscussionboardRegistereduserEmailverificationsController,
    DiscussionboardAdministratorsController,
    DiscussionboardSuperadministratorsController,
    DiscussionboardGuestSectionsController,
    DiscussionboardRegistereduserSectionsController,
    DiscussionboardAdministratorSectionsController,
    DiscussionboardSuperadministratorSectionsController,
    DiscussionboardAdministratorSectionadminlogsController,
    DiscussionboardSuperadministratorSectionadminlogsController,
    DiscussionboardRegistereduserArticlesController,
    DiscussionboardAdministratorArticlesController,
    DiscussionboardSuperadministratorArticlesController,
    DiscussionboardRegistereduserArticlesFilesController,
    DiscussionboardAdministratorArticlesFilesController,
    DiscussionboardSuperadministratorArticlesFilesController,
    DiscussionboardRegistereduserArticlesImagesController,
    DiscussionboardAdministratorArticlesImagesController,
    DiscussionboardSuperadministratorArticlesImagesController,
    DiscussionboardRegistereduserArticlesTag_mappingsController,
    DiscussionboardAdministratorArticlesTag_mappingsController,
    DiscussionboardSuperadministratorArticlesTag_mappingsController,
    DiscussionboardAdministratorAdministrator_grade_changesController,
    DiscussionboardSuperadministratorAdministrator_grade_changesController,
    DiscussionboardRegistereduserCommentsController,
    DiscussionboardAdministratorCommentsController,
    DiscussionboardCommentsSnapshotsController,
    DiscussionboardSuperadministratorAdministratorRequestsController,
    DiscussionboardRegistereduserAdministratorRequestsController,
    DiscussionboardAdministratorAdministratorGradesController,
    DiscussionboardSuperadministratorAdministratorGradesController,
    DiscussionboardSuperadministratorAdministratorPromotionsController,
    DiscussionboardAdministratorAdministratorBansController,
    DiscussionboardSuperadministratorAdministratorBansController,
    DiscussionboardAdministratorAdministratorUnbansController,
    DiscussionboardSuperadministratorAdministratorUnbansController,
    DiscussionboardRegistereduserTagsController,
    DiscussionboardAdministratorTagsController,
    DiscussionboardRegistereduserArticle_tag_mappingsController,
    DiscussionboardAdministratorArticle_tag_mappingsController,
    DiscussionboardAdministratorArticle_search_indexesController,
    DiscussionboardAdministratorTag_usage_statsController,
    DiscussionboardAdministratorSystemsettingsController,
    DiscussionboardSuperadministratorSystemsettingsController,
    DiscussionboardAdministratorAuditlogsController,
    DiscussionboardSuperadministratorAuditlogsController,
    DiscussionboardAdministratorScheduledtasksController,
    DiscussionboardSuperadministratorScheduledtasksController,
    DiscussionboardAdministratorFeatureflagsController,
    DiscussionboardSuperadministratorFeatureflagsController,
    DiscussionboardAdministratorSystemmessagesController,
    DiscussionboardSuperadministratorSystemmessagesController,
    DiscussionboardAdministratorHealthchecksController,
    DiscussionboardSuperadministratorHealthchecksController,
    DiscussionboardAdministratorArticle_statisticsOverviewController,
    DiscussionboardSuperadministratorArticle_reportsActivityController,
    DiscussionboardSuperadministratorAdministratorRequestsApproveController,
    DiscussionboardSuperadministratorAdministratorRequestsRejectController,
    DiscussionboardSuperadministratorAdministratorPromoteController,
    DiscussionboardSuperadministratorAdministratorDemoteController,
    DiscussionboardAdministratorAdministratorBanController,
    DiscussionboardAdministratorAdministratorController,
    DiscussionboardAdministratorAdministratorBanned_usersController,
    DiscussionboardGuestSearchArticlesController,
    DiscussionboardRegistereduserSearchArticlesController,
    DiscussionboardAdministratorTagsUsage_statsController,
  ],
})
export class MyModule {}
