import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IShoppingMallSellerApproval } from "../../../../../structures/IShoppingMallSellerApproval";

/**
 * Approve a seller registration application identified by sellerApprovalId.
 *
 * This API operation allows an administrator to approve a pending seller registration request by setting the approval status to 'approved' in the shopping_mall_seller_approvals table. Upon approval, the seller gains permission to manage products and orders.
 *
 * Only authorized administrators have access to this endpoint.
 *
 * The approval record is uniquely identified by the sellerApprovalId path parameter. The request body is empty, as the approval action always sets the status field to 'approved' and clears any rejection reason.
 *
 * Response returns the full updated seller approval record reflecting the approved status.
 *
 * If the specified sellerApprovalId does not exist or is not in pending state, the operation returns an error.
 *
 * This operation complements related endpoints for rejecting seller applications and viewing approval status.
 *
 * @param props.connection
 * @param props.sellerApprovalId Unique identifier of the seller approval to be approved.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor administrator
 * @x-autobe-specification Validate the requesting user is an administrator.
 * Fetch the seller approval record by sellerApprovalId.
 * If not found or status is not 'pending', respond with error 404 or 400.
 * Update the status field to 'approved' and clear rejection_reason.
 * Update updated_at timestamp.
 * Persist changes in a single database transaction.
 * Return the updated seller approval record in the response body.
 * Ensure standard error handling for concurrency and database errors.
 * Audit the approval action for compliance.
 * @path /shoppingMall/administrator/seller-approvals/:sellerApprovalId/approve
 * @accessor api.functional.shoppingMall.administrator.seller_approvals.approve.approveSellerApproval
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function approveSellerApproval(
  connection: IConnection,
  props: approveSellerApproval.Props,
): Promise<approveSellerApproval.Response> {
  return true === connection.simulate
    ? approveSellerApproval.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...approveSellerApproval.METADATA,
          path: approveSellerApproval.path(props),
          status: null,
        },
      );
}
export namespace approveSellerApproval {
  export type Props = {
    /**
     * Unique identifier of the seller approval to be approved.
     */
    sellerApprovalId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallSellerApproval;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/administrator/seller-approvals/:sellerApprovalId/approve",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/administrator/seller-approvals/${encodeURIComponent(props.sellerApprovalId ?? "null")}/approve`;
  export const random = (): IShoppingMallSellerApproval =>
    typia.random<IShoppingMallSellerApproval>();
  export const simulate = (
    connection: IConnection,
    props: approveSellerApproval.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: approveSellerApproval.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("sellerApprovalId")(() =>
        typia.assert(props.sellerApprovalId),
      );
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
