import { TypedBody, TypedRoute } from "@nestia/core";
import { Controller, Ip } from "@nestjs/common";
import typia from "typia";

import { IEcommercePlatformGuest } from "../../../../api/structures/IEcommercePlatformGuest";
import { postEcommercePlatformAuthGuestJoin } from "../../../../providers/postEcommercePlatformAuthGuestJoin";
import { postEcommercePlatformAuthGuestRefresh } from "../../../../providers/postEcommercePlatformAuthGuestRefresh";

@Controller("/ecommercePlatform/auth/guest")
export class EcommerceplatformAuthGuestController {
  /**
   * Join endpoint for guest registration without credentials.
   *
   * Registers a new guest account or retrieves existing guest session using device fingerprint. The device fingerprint uniquely identifies visitors based on browser and device characteristics including user agent, screen resolution, and timezone.
   *
   * Upon successful join, the system creates or retrieves a guest record in ecommerce_platform_guests and establishes an authenticated session in ecommerce_platform_guest_sessions.
   *
   * No email or password required - guests authenticate via device fingerprint only. This enables unauthenticated visitors to access registration and login pages before creating full accounts.
   *
   * Related operations: refresh for token renewal.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Join request containing device fingerprint for guest identification.
   *
   *             The device_fingerprint uniquely identifies the visitor based on browser and device characteristics including user agent, screen resolution, timezone, installed plugins, and other device attributes.
   *
   *             Field: device_fingerprint (string, required) - Unique identifier derived from visitor's browser and device characteristics. Must be a valid identifier that distinguishes this visitor from others.
     * @x-autobe-authorization-type join
     * @x-autobe-authorization-actor guest
     * @x-autobe-specification POST /auth/guest/join
   *
   * Service Logic:
   * 1. Extract device fingerprint from request body
   * 2. Query ecommerce_platform_guests for existing active guest with matching device_fingerprint (deleted_at IS NULL)
   * 3. If exists: use existing guest record and create fresh session
   * 4. If not exists: create new record in ecommerce_platform_guests with:
   *    - device_fingerprint from request
   *    - created_at = current timestamp
   *    - updated_at = current timestamp
   *    - deleted_at = null
   * 5. Create new session in ecommerce_platform_guest_sessions:
   *    - ecommerce_platform_guest_id = guest id
   *    - ip = request IP
   *    - href = current page URL
   *    - referrer = referrer URL
   *    - created_at = current timestamp
   *    - expired_at = created_at + session duration (24h default)
   * 6. Generate JWT access and refresh tokens
   * 7. Return IAuthorized response with tokens
   *
   * Edge Cases:
   * - Duplicate fingerprint: Idempotent - return existing guest tokens
   * - Invalid fingerprint format: 400 Bad Request
   * - Guest soft-deleted: Create new guest record
   *
   * Error Handling:
   * - 400: Invalid device fingerprint format (empty, too short, non-UUID)
   * - 500: Database error during guest/session creation
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("join")
  public async join(
    @Ip()
    ip: string,
    @TypedBody()
    body: IEcommercePlatformGuest.IJoin,
  ): Promise<IEcommercePlatformGuest.IAuthorized> {
    try {
      return await postEcommercePlatformAuthGuestJoin({
        ip,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Refresh endpoint for renewing guest authentication tokens.
   *
   * Renews JWT access and refresh tokens for active guest sessions. Validates the provided refresh token against the guest's current session state in ecommerce_platform_guest_sessions.
   *
   * The system checks that the guest account exists in ecommerce_platform_guests, is not soft-deleted, and has an active session in ecommerce_platform_guest_sessions with expired_at in the future.
   *
   * Returns new tokens enabling continued guest authentication for accessing registration and login pages. Token rotation invalidates the old refresh token for security.
   *
   * Related operations: join for initial guest registration.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Refresh request containing valid refresh token for guest token renewal.
   *
   *             The refreshToken is required to validate the existing guest session and generate new authentication tokens. This token was obtained from a previous join or refresh operation.
   *
   *             Field: refreshToken (string, required) - JWT refresh token from previous join or refresh response. Must be valid, unexpired, and correspond to an active guest session in ecommerce_platform_guest_sessions.
     * @x-autobe-authorization-type refresh
     * @x-autobe-authorization-actor guest
     * @x-autobe-specification POST /auth/guest/refresh
   *
   * Service Logic:
   * 1. Validate refresh token structure and signature
   * 2. Decode refresh token to extract guest_id claim
   * 3. Query ecommerce_platform_guests for guest with matching id
   * 4. If guest not found or soft-deleted (deleted_at IS NOT NULL): reject 401 Unauthorized
   * 5. Query ecommerce_platform_guest_sessions for valid session:
   *    - ecommerce_platform_guest_id = guest id
   *    - expired_at > current timestamp
   *    - Session tied to the refresh token
   * 6. If no valid session: reject 401 Unauthorized
   * 7. Rotate tokens: invalidate old refresh token
   * 8. Generate new JWT access and refresh tokens
   * 9. Update session record:
   *    - Set expired_at = current time + session duration (24h)
   * 10. Return IAuthorized response with new tokens
   *
   * Edge Cases:
   * - Expired session: 401 Unauthorized
   * - Invalid refresh token: 401 Unauthorized
   * - Deleted guest account: 401 Unauthorized
   * - Revoked token: 403 Forbidden
   *
   * Error Handling:
   * - 401: Invalid refresh token, expired session, or deleted guest account
   * - 403: Token revoked by administrator
   * - 500: Database error during token validation or session update
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("refresh")
  public async refresh(
    @TypedBody()
    body: IEcommercePlatformGuest.IRefresh,
  ): Promise<IEcommercePlatformGuest.IAuthorized> {
    try {
      return await postEcommercePlatformAuthGuestRefresh({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
