import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IHrmsFile } from "../../../../../api/structures/IHrmsFile";
import { IPageIHrmsFile } from "../../../../../api/structures/IPageIHrmsFile";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { patchHrmsMemberOrganizationsOrganizationIdFiles } from "../../../../../providers/patchHrmsMemberOrganizationsOrganizationIdFiles";

@Controller("/hrms/member/organizations/:organizationId/files")
export class HrmsMemberOrganizationsFilesController {
  /**
   * Retrieve a filtered and paginated list of files within the specified organization.
   *
   * This operation provides comprehensive file browsing capabilities with organization-scoped access. Users can search for files by name, filter by file category (organization logo, user avatar, document), validation status, and owner type. The endpoint supports date range filtering to find files uploaded within a specific time period.
   *
   * Pagination is included with configurable page size and sorting options, allowing efficient browsing of large file libraries. Results are automatically scoped to the organization context specified in the path parameter, ensuring data isolation between organizations.
   *
   * Soft-deleted files are excluded by default to maintain a clean file list, but can be included when explicitly requested for administrative purposes.
   *
   * @param connection
   * @param organizationId The unique identifier of the organization
   * @param body Search criteria, filters, sorting, and pagination parameters
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Query the hrms_files table for files belonging to the specified organization.
   *
   * Apply organization context from the organizationId path parameter to scope all queries.
   *
   * Apply filters:
   * - category: filter by file_category ('organization_logo', 'user_avatar', 'document')
   * - validationStatus: filter by validation_status ('pending', 'validated', 'rejected')
   * - ownerType: filter by owner_type ('member' or null for organization-owned)
   * - ownerId: filter files by specific owner when owner_type is 'member'
   * - filename: partial match search on filename field using gin_trgm_ops index
   * - dateRange: filter by created_at between startDate and endDate
   * - deleted: filter to include/exclude soft-deleted files
   *
   * Sort results by specified field (created_at, filename, file_size, file_category) in ascending or descending order.
   *
   * Apply pagination: page number, page size, and cursor-based navigation for large result sets.
   *
   * Exclude soft-deleted files (deleted_at IS NULL) unless explicitly requested.
   *
   * Return paginated results with total count, current page, and file summary data.
   *
   * Validate that the organizationId exists and the requesting user has permission to view files in that organization.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("organizationId")
    organizationId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IHrmsFile.IRequest,
  ): Promise<IPageIHrmsFile.ISummary> {
    try {
      return await patchHrmsMemberOrganizationsOrganizationIdFiles({
        member,
        organizationId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
