import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIRedditCommunityComment } from "../../../../../structures/IPageIRedditCommunityComment";
import { IRedditCommunityComment } from "../../../../../structures/IRedditCommunityComment";

/**
 * Retrieve a paginated list of all comments written by a specified user across the platform.
 *
 * This operation displays the user's complete comment history with each comment entry showing content preview, the post it belongs to (title and author), vote score, and timestamp. Comments are sorted in reverse chronological order with the most recent comments appearing first.
 *
 * The operation supports pagination for users with many comments, allowing efficient navigation through their comment history. Each comment summary includes essential information for list display while avoiding excessive data transfer.
 *
 * Users can view other users' comments lists without restriction. The operation requires the userId path parameter to identify which user's comments to retrieve. Soft-deleted comments (marked by deleted_at) do not appear in the results, whether deleted by the author or moderators.
 *
 * @param props.connection
 * @param props.userId ID of the user whose comments to retrieve
 * @param props.body Pagination and filtering parameters for the comment list
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor guest
 * @x-autobe-specification Query reddit_community_comments table filtering by reddit_community_members_id = userId.
 * Apply pagination with configurable page size and cursor-based navigation.
 * Sort by created_at DESC for reverse chronological ordering.
 * Exclude records where deleted_at IS NOT NULL.
 * Join with reddit_community_posts to include post_id, post_title, and post_author_id.
 * Aggregate vote counts from reddit_community_vote_of_comments joined with reddit_community_votes.
 * Return paginated results with IPageIRedditCommunityComment.ISummary structure.
 * Validate userId is a valid UUID before querying.
 * @path /redditCommunity/guest/users/:userId/comments
 * @accessor api.functional.redditCommunity.guest.users.comments.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * ID of the user whose comments to retrieve
     */
    userId: string & tags.Format<"uuid">;

    /**
     * Pagination and filtering parameters for the comment list
     */
    body: IRedditCommunityComment.IRequest;
  };
  export type Body = IRedditCommunityComment.IRequest;
  export type Response = IPageIRedditCommunityComment.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditCommunity/guest/users/:userId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditCommunity/guest/users/${encodeURIComponent(props.userId ?? "null")}/comments`;
  export const random = (): IPageIRedditCommunityComment.ISummary =>
    typia.random<IPageIRedditCommunityComment.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("userId")(() => typia.assert(props.userId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
