import { tags } from "typia";

import { IDiscussionBoardSection } from "./IDiscussionBoardSection";

/**
 * Complete section snapshot entity representing the historical state of a section at a specific point in time. This immutable record captures all section properties (name, description) and temporal information (when the section was created, when it was last modified before this snapshot, and when the snapshot itself was created) for audit trail and revision history purposes. The section field provides context about the parent section this snapshot belongs to.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardSectionSnapshot = {
  /**
   * Unique identifier for this section snapshot record.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.id. Primary key UUID identifying this snapshot record.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Name of the section at the time of snapshot.
   *
   * @x-autobe-database-schema-property name
   * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.name. Captures the section name at the time this snapshot was taken.
   */
  name: string;

  /**
   * Description of the section at the time of snapshot. May be null if no description was set.
   *
   * @x-autobe-database-schema-property description
   * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.description. Nullable field capturing the section description at the time of snapshot.
   */
  description: string | null;

  /**
   * Timestamp when the original section was created (captured from parent section).
   *
   * @x-autobe-database-schema-property section_created_at
   * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.section_created_at. Captures when the original section was created (from parent section record).
   */
  section_created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the section was last modified before this snapshot was taken (captured from parent section).
   *
   * @x-autobe-database-schema-property section_updated_at
   * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.section_updated_at. Captures when the section was last modified before this snapshot was taken (from parent section record).
   */
  section_updated_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when this snapshot was created.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.created_at. Timestamp when this snapshot record was created.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * The parent section to which this snapshot belongs.
   *
   * @x-autobe-database-schema-property section
   * @x-autobe-specification Relation mapping from discussion_board_section_snapshots.section (belongs-to). JOIN with discussion_board_sections table on discussion_board_sections_id = sections.id. Returns ISummary type with id, name, description, created_at, updated_at fields.
   */
  section: IDiscussionBoardSection.ISummary;
};
export namespace IDiscussionBoardSectionSnapshot {
  /**
   * Request body for filtering and paginating section snapshot records. This DTO allows administrators to search through historical section snapshots with various criteria including text search on section names and descriptions, date range filtering on snapshot creation time, and pagination controls. All fields are optional, enabling flexible querying of the audit trail data.
   */
  export type IRequest = {
    /**
     * Text search query for filtering snapshots by section name or description. Performs case-insensitive partial matching across both fields.
     *
     * @x-autobe-specification LIKE query on name and description columns. Performs case-insensitive partial match search across both fields. SQL: WHERE name ILIKE '%search%' OR description ILIKE '%search%'.
     */
    search?: string | undefined;

    /**
     * Start date for filtering snapshots. Only includes snapshots created on or after this date-time. Uses ISO 8601 format.
     *
     * @x-autobe-specification Filter created_at field with >= operator. SQL: WHERE created_at >= fromDate. Excludes snapshots created before this timestamp. Format: ISO 8601 date-time string.
     */
    fromDate?: (string & tags.Format<"date-time">) | undefined;

    /**
     * End date for filtering snapshots. Only includes snapshots created on or before this date-time. Uses ISO 8601 format.
     *
     * @x-autobe-specification Filter created_at field with <= operator. SQL: WHERE created_at <= toDate. Excludes snapshots created after this timestamp. Format: ISO 8601 date-time string.
     */
    toDate?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Page number for pagination (1-indexed). Defaults to 1 if not provided. Use with pageSize to navigate through result sets.
     *
     * @x-autobe-specification 1-indexed page number for pagination. SQL: OFFSET (page - 1) * pageSize. Defaults to 1 if not provided. Minimum value is 1.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of records to return per page. Range: 1-100. Defaults to 20 if not provided. Use with page to navigate through results.
     *
     * @x-autobe-specification Number of records per page. SQL: LIMIT pageSize. Defaults to 20 if not provided. Range: 1-100. Controls how many snapshots are returned per page.
     */
    pageSize?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Field name to sort results by. Valid options: created_at, name, description, section_created_at, section_updated_at. Defaults to 'created_at'.
     *
     * @x-autobe-specification Field name for ORDER BY clause. SQL: ORDER BY {sortBy} {sortOrder}. Valid fields: created_at, name, description, section_created_at, section_updated_at. Defaults to 'created_at' if not provided.
     */
    sortBy?: string | undefined;

    /**
     * Sort direction for results. Valid values: 'asc' (ascending) or 'desc' (descending). Defaults to 'desc' to show most recent snapshots first.
     *
     * @x-autobe-specification Sort direction for ORDER BY clause. SQL: ORDER BY {sortBy} {sortOrder}. Valid values: 'asc' (ascending) or 'desc' (descending). Defaults to 'desc' for recent snapshots first.
     */
    sortOrder?: "asc" | "desc" | undefined;

    /**
     * Maximum number of records to return per page. Alternative to pageSize. Defaults to 100 if not provided. Server may enforce upper bounds.
     *
     * @x-autobe-specification Maximum number of records to return. Alternative to pageSize. SQL: LIMIT {limit}. Defaults to 100 if null or not provided. Server may enforce upper bounds to prevent excessive resource consumption.
     */
    limit?: null | (number & tags.Type<"int32"> & tags.Minimum<0>) | undefined;
  };

  /**
   * Lightweight section snapshot summary for listing in paginated audit trail results.
   *
   * This DTO represents a point-in-time snapshot of a section's state at the moment of modification. Each snapshot captures the section's name, description, and timestamps, preserving historical data for audit and compliance purposes.
   *
   * The section property provides a reference to the parent section being snapshot, enabling users to identify which section configuration this snapshot represents. All timestamps are preserved from the original section state to maintain accurate historical records.
   *
   * Used primarily in the PATCH /discussionBoard/sections/{sectionId}/snapshots operation for retrieving filtered and paginated lists of section modification history.
   */
  export type ISummary = {
    /**
     * Unique identifier for the section snapshot record.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.id. UUID primary key uniquely identifying each snapshot record.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Name of the section at the time this snapshot was taken.
     *
     * @x-autobe-database-schema-property name
     * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.name. Captures the section name at the time of snapshot.
     */
    name: string;

    /**
     * Optional description of the section at the time this snapshot was taken.
     *
     * @x-autobe-database-schema-property description
     * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.description. Nullable field capturing the section description at the time of snapshot. Uses oneOf for nullable type representation.
     */
    description: string | null;

    /**
     * Timestamp when the original section was created (captured from parent section).
     *
     * @x-autobe-database-schema-property section_created_at
     * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.section_created_at. Captures the original section's created_at timestamp from the parent section at the time of snapshot.
     */
    section_created_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when the section was last modified before this snapshot was taken (captured from parent section).
     *
     * @x-autobe-database-schema-property section_updated_at
     * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.section_updated_at. Captures the section's updated_at timestamp from the parent section at the time of snapshot.
     */
    section_updated_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when this snapshot was created.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from discussion_board_section_snapshots.created_at. Timestamp when this snapshot record was created.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Reference to the parent section that this snapshot represents.
     *
     * @x-autobe-database-schema-property section
     * @x-autobe-specification Transform from discussion_board_sections_id FK column to section relation. Join via discussion_board_section_snapshots.discussion_board_sections_id to discussion_board_sections.id. Returns IDiscussionBoardSection.ISummary object representing the parent section being snapshot.
     */
    section: IDiscussionBoardSection.ISummary;
  };
}
