import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia, { tags } from "typia";
import { patchShoppingMallCustomerCustomersCustomerIdAddresses } from "../../../../../providers/patchShoppingMallCustomerCustomersCustomerIdAddresses";
import { CustomerAuth } from "../../../../../decorators/CustomerAuth";
import { CustomerPayload } from "../../../../../decorators/payload/CustomerPayload";
import { getShoppingMallCustomerCustomersCustomerIdAddressesAddressId } from "../../../../../providers/getShoppingMallCustomerCustomersCustomerIdAddressesAddressId";

import { IPageIShoppingMallAddress } from "../../../../../api/structures/IPageIShoppingMallAddress";
import { IShoppingMallAddress } from "../../../../../api/structures/IShoppingMallAddress";

@Controller("/shoppingMall/customer/customers/:customerId/addresses")
export class ShoppingmallCustomerCustomersAddressesController {
  /**
   * Retrieve a paginated and filterable list of address records for a specific
   * customer.
   *
   * This endpoint is accessible to authenticated customers (for their own
   * addresses) and admins (for platform oversight). The operation enables
   * customers to view all of their stored addresses (up to the business maximum
   * of 10). Query capabilities allow for search by name, city, or status, and
   * results are paginated for efficient display in user interfaces. Security
   * and ownership checks ensure that only the owner/customer or platform admins
   * may access this data.
   *
   * Returned records cover all structured address fields, including recipient
   * name, full address breakdown, contact phone, whether it is the default, and
   * address creation time. Results conform to the business schema, omitting
   * fields that do not exist in shopping_mall_addresses (such as deleted_at).
   * Error conditions include access violation if an actor requests another
   * customer's addresses without admin privileges.
   *
   * Related operations include address retrieval and modification (GET, PUT,
   * DELETE /customers/{customerId}/addresses/{addressId}), which allow
   * management of individual address entries. This operation only lists the
   * current user's addresses, never those of sellers or other actors.
   *
   * @param connection
   * @param customerId Unique identifier of the target customer whose addresses
   *   will be listed.
   * @param body Search, filtering, and pagination parameters for querying the
   *   address list of a specific customer.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("customerId")
    customerId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IShoppingMallAddress.IRequest,
  ): Promise<IPageIShoppingMallAddress.ISummary> {
    try {
      return await patchShoppingMallCustomerCustomersCustomerIdAddresses({
        customer,
        customerId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve the complete details of a single address by ID for a given
   * customer.
   *
   * Only the account owner (authenticated customer) or an admin is allowed to
   * access the requested address. The addressId parameter must refer to an
   * address record that belongs to the customer identified by customerId;
   * otherwise, an error is returned. The returned data covers full address
   * structure in line with schema guidelines, ensuring only user-manageable
   * data is present. This is commonly used for editing addresses in personal
   * profile sections and for reviewing address details prior to order
   * checkout.
   *
   * If an address does not belong to the given customer, or the actor lacks
   * sufficient permissions, an authorization error is triggered. Related
   * endpoints include the paginated address list and update/delete operations
   * for the same resource.
   *
   * @param connection
   * @param customerId Unique identifier of the customer who owns the address.
   * @param addressId Unique identifier of the target address record being
   *   retrieved.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":addressId")
  public async at(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("customerId")
    customerId: string & tags.Format<"uuid">,
    @TypedParam("addressId")
    addressId: string & tags.Format<"uuid">,
  ): Promise<IShoppingMallAddress> {
    try {
      return await getShoppingMallCustomerCustomersCustomerIdAddressesAddressId(
        {
          customer,
          customerId,
          addressId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
