import { TypedBody, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { ITodoAppMember } from "../../../../api/structures/ITodoAppMember";
import { MemberAuth } from "../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../decorators/payload/MemberPayload";
import { putTodoAppMemberProfile } from "../../../../providers/putTodoAppMemberProfile";

@Controller("/todoApp/member/profile")
export class TodoappMemberProfileController {
  /**
   * Update the authenticated member's profile information.
   *
   * This operation allows members to modify their display name within the application. The display name is a user-chosen identifier that appears in the application interface, providing personalization while keeping the email address private for authentication purposes.
   *
   * Profile updates are strictly limited to the authenticated member's own account. Each member's data is completely isolated from other users, ensuring privacy and security. The system automatically updates the timestamp to track when changes are made.
   *
   * This operation only modifies the display_name field and cannot be used to change email addresses, authentication credentials, or other sensitive account information. After successful update, the complete member profile information is returned including all current field values.
   *
   * Note: Profile updates require an active authenticated session and will be rejected for accounts that have been soft-deleted.
   *
   * @param connection
   * @param body Profile update fields
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Authenticate the requesting member via session token. Verify the member exists and is not soft-deleted (deleted_at is null). Extract the display_name from the request body. Update the todo_app_members record for the authenticated member with the new display_name. Set updated_at to current timestamp. Return the updated member record including all fields: id, email, display_name, created_at, updated_at, deleted_at.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put()
  public async update(
    @MemberAuth()
    member: MemberPayload,
    @TypedBody()
    body: ITodoAppMember.IUpdate,
  ): Promise<ITodoAppMember> {
    try {
      return await putTodoAppMemberProfile({
        member,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
