import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IEconPoliticBoardArticle } from "../../../../structures/IEconPoliticBoardArticle";

/**
 * Trigger a new export operation for specified content. The export process generates an archive file containing requested data. This operation supports exporting different content types (articles, comments, sections) in various formats (CSV, JSON, PDF) with optional date filters and content filters.
 *
 * The export ID returned allows users to track progress and download the result. Admins can request exports for all published content, while users can only request exports for their own content.
 *
 * Business rules:
 * - Maximum export size is 500MB per export
 * - Export requests cannot exceed 10 concurrent exports per user
 * - Exports require proper authorization based on user role
 * - System records all export requests for audit purposes
 *
 * @param props.connection
 * @param props.body Export request parameters
 * @x-autobe-specification Validate user permissions and authenticate the request (requires authenticated user). Parse request parameters and validate all required fields: type (must be one of ['articles', 'comments', 'all']), format (must be one of ['csv', 'json', 'pdf']), startDate (optional ISO 8601 date), endDate (optional ISO 8601 date), maxItems (optional integer, default 1000). Create a new export request record in export_requests table with status 'pending'. Add to the export queue for background processing. Return the export ID to the client with status 201. Implement rate limiting: max 10 exports per 1 hour per user. Implement audit logging for export requests. Return a meaningful error if any parameters are invalid or if user lacks permissions.
 * @path /econPoliticBoard/admin/export
 * @accessor api.functional.econPoliticBoard.admin._export.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Export request parameters
     */
    body: IEconPoliticBoardArticle.IRequest;
  };
  export type Body = IEconPoliticBoardArticle.IRequest;
  export type Response = IEconPoliticBoardArticle.IResponse;

  export const METADATA = {
    method: "POST",
    path: "/econPoliticBoard/admin/export",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/econPoliticBoard/admin/export";
  export const random = (): IEconPoliticBoardArticle.IResponse =>
    typia.random<IEconPoliticBoardArticle.IResponse>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
