import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICommunityPlatformSearchDocuments } from "../../../../structures/ICommunityPlatformSearchDocuments";
import { IPageICommunityPlatformSearchResult } from "../../../../structures/IPageICommunityPlatformSearchResult";

/**
 * Execute a rich, cross-entity search over public documents in the community
 * platform.
 *
 * This operation is conceptually built on top of several primary Prisma models,
 * including community_platform_communities for community containers,
 * community_platform_posts for main post content, community_platform_comments
 * for discussion threads, and community_platform_user_profiles for
 * public-facing user profile information. In addition, it leverages subsidiary
 * or supporting structures such as community_platform_search_indexes, which
 * store derived search index metadata, and potentially
 * community_platform_discovery_items for boosted or recommended content. While
 * the exact fields of these models are defined in the Prisma schema, their
 * combined purpose is to provide a searchable corpus of public "documents" that
 * can be discovered through this endpoint.
 *
 * From a security perspective, this is a read-only search API that should
 * typically be available to both guests and authenticated members. The
 * implementation must enforce visibility and privacy rules implied by the
 * Prisma models: for example, communities may have status or visibility fields
 * (e.g., public, restricted, archived) and posts or comments may include flags
 * for removal, moderation status, or visibility. The search query must filter
 * out any items that are not eligible to be shown to the requesting actor based
 * on those fields and any linked moderation actions stored in tables such as
 * community_platform_moderation_actions_on_content or
 * community_platform_moderation_actions_on_communities.
 *
 * The request body ICommunityPlatformSearchDocuments.IRequest encapsulates
 * full-text query strings, lists of community identifiers or codes, filters by
 * content type (community, post, comment, profile), time-range constraints,
 * sorting options like relevance or recency, and pagination parameters. These
 * are translated into a query against the search index and/or directly against
 * the backing Prisma tables. The response uses a paginated container
 * IPageICommunityPlatformSearchResult which aggregates heterogeneous search
 * hits into a unified list, where each element may reference underlying
 * entities by their identifiers and include summary fields suitable for search
 * result cards.
 *
 * This search endpoint is expected to be used together with specialized
 * endpoints that fetch full details of specific entities once selected from
 * search results, such as dedicated GET endpoints for posts or communities.
 * Errors may occur when invalid filters are provided (e.g., impossible sort
 * keys or malformed pagination cursors); these should be reported with clear
 * validation messages while never exposing internal schema details or
 * implementation-specific index structures.
 *
 * @param props.connection
 * @param props.body Search criteria, filters, sort options, and pagination
 *   parameters for document search across the community platform.
 * @path /communityPlatform/search/documents
 * @accessor api.functional.communityPlatform.search.documents.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria, filters, sort options, and pagination parameters for
     * document search across the community platform.
     */
    body: ICommunityPlatformSearchDocuments.IRequest;
  };
  export type Body = ICommunityPlatformSearchDocuments.IRequest;
  export type Response = IPageICommunityPlatformSearchResult;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/search/documents",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/search/documents";
  export const random = (): IPageICommunityPlatformSearchResult =>
    typia.random<IPageICommunityPlatformSearchResult>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
