import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia from "typia";
import { postRedditCommunityModeratorCommunitiesCommunityNameModerators } from "../../../../../providers/postRedditCommunityModeratorCommunitiesCommunityNameModerators";
import { ModeratorAuth } from "../../../../../decorators/ModeratorAuth";
import { ModeratorPayload } from "../../../../../decorators/payload/ModeratorPayload";
import { deleteRedditCommunityModeratorCommunitiesCommunityNameModeratorsUsername } from "../../../../../providers/deleteRedditCommunityModeratorCommunitiesCommunityNameModeratorsUsername";

import { IRedditCommunityCommunityModerator } from "../../../../../api/structures/IRedditCommunityCommunityModerator";

@Controller("/redditCommunity/moderator/communities/:communityName/moderators")
export class RedditcommunityModeratorCommunitiesModeratorsController {
  /**
   * Assign a new moderator to a specific community, granting them moderation
   * authority and privileges within that community space. This operation
   * creates a new moderator assignment by establishing a relationship between
   * an existing moderator account and the target community.
   *
   * The operation requires specification of which moderator (by their moderator
   * ID or username) should be granted authority in the community. Only users
   * with appropriate permissions can assign moderators - typically existing
   * community moderators with elevated privileges or platform administrators.
   * The system validates that the moderator account exists and is not already
   * assigned to this community to prevent duplicate assignments.
   *
   * Security and authorization are critical for this operation. The requesting
   * user must have sufficient authority within the community (such as being a
   * senior moderator or community founder) or be a platform administrator. The
   * operation logs the moderator assignment action for audit trail purposes,
   * recording who granted the moderation privileges and when.
   *
   * This operation integrates with the reddit_community_community_moderators
   * junction table as defined in the Prisma schema. Upon successful assignment,
   * the newly appointed moderator gains access to moderation tools and
   * capabilities within the community, including content review, user
   * management, and rule enforcement features. The response includes the
   * complete moderator assignment record confirming the new relationship.
   *
   * @param connection
   * @param communityName Unique business identifier code of the target
   *   community (global scope)
   * @param body Moderator assignment information specifying which moderator to
   *   assign to the community
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @ModeratorAuth()
    moderator: ModeratorPayload,
    @TypedParam("communityName")
    communityName: string,
    @TypedBody()
    body: IRedditCommunityCommunityModerator.ICreate,
  ): Promise<IRedditCommunityCommunityModerator> {
    try {
      return await postRedditCommunityModeratorCommunitiesCommunityNameModerators(
        {
          moderator,
          communityName,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Remove moderator authority from a community by deleting the
   * moderator-community relationship.
   *
   * This operation allows community owners or platform administrators to revoke
   * moderation privileges from a user in a specific community. The moderator
   * loses all content management capabilities within that community, including
   * the ability to review reports, remove posts/comments, and ban users.
   *
   * Security and Authorization: CRITICAL - Only community owners or platform
   * administrators can remove moderators. The operation performs the following
   * authorization validations:
   *
   * 1. Verifies the requesting user is the community owner OR a platform
   *    administrator
   * 2. Prevents regular moderators from removing other moderators
   * 3. Prevents moderators from removing themselves (self-removal requires
   *    separate resign endpoint)
   * 4. Returns 403 Forbidden if authorization checks fail
   * 5. Logs all moderator removal actions for audit purposes
   *
   * The moderator being removed must currently have active moderation status in
   * the specified community. The operation performs a hard delete on the
   * reddit_community_community_moderators relationship record. Once removed,
   * the user reverts to regular member status in the community (if they are
   * subscribed) or guest status (if not subscribed). To reinstate moderation
   * privileges, a new moderator appointment must be created through the
   * appropriate endpoint.
   *
   * Related operations: Appoint moderator (POST
   * /communities/{communityName}/moderators), List community moderators (PATCH
   * /communities/{communityName}/moderators).
   *
   * @param connection
   * @param communityName Unique business identifier name of the target
   *   community (global scope)
   * @param username Unique username of the moderator to be removed from the
   *   community
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":username")
  public async erase(
    @ModeratorAuth()
    moderator: ModeratorPayload,
    @TypedParam("communityName")
    communityName: string,
    @TypedParam("username")
    username: string,
  ): Promise<IRedditCommunityCommunityModerator> {
    try {
      return await deleteRedditCommunityModeratorCommunitiesCommunityNameModeratorsUsername(
        {
          moderator,
          communityName,
          username,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
