import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIRedditCommunityPost } from "../../../../../structures/IPageIRedditCommunityPost";
import { IRedditCommunityPost } from "../../../../../structures/IRedditCommunityPost";

/**
 * Retrieve a paginated list of posts created by a specific member.
 *
 * This operation returns all posts authored by the specified member, excluding deleted posts. Results can be sorted by various criteria including recency (New), vote score (Top with time filters), engagement (Hot), or controversy level (Controversial).
 *
 * Each post summary includes the title, author information, community name, current vote score, comment count, and creation timestamp. Text posts show the first 200 characters of content, image posts include thumbnail paths, and link posts display the domain name.
 *
 * Supports comprehensive pagination for browsing large result sets. Only active (non-deleted) posts are included in results.
 *
 * @param props.connection
 * @param props.memberId UUID of the member whose posts to retrieve
 * @param props.body Search criteria including pagination, sorting, and time filters
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query reddit_community_posts table filtered by reddit_community_member_id = {memberId}. Exclude soft-deleted posts (deleted_at IS NULL). Join with reddit_community_communities for community name. Compute vote_score by summing reddit_community_post_votes (upvote=+1, downvote=-1). Compute comment_count by counting reddit_community_comments where reddit_community_post_id matches. Apply sorting based on request: 'new' by created_at DESC, 'top' by vote_score DESC with time filter on created_at, 'hot' by combination of vote_score and recency, 'controversial' by vote variance with score near zero. Apply pagination with cursor or offset. Return IPageIRedditCommunityPost.ISummary with post summaries including title, author username, community name, vote score, comment count, created timestamp, and post type indicator.
 * @path /redditCommunity/member/members/:memberId/posts
 * @accessor api.functional.redditCommunity.member.members.posts.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * UUID of the member whose posts to retrieve
     */
    memberId: string & tags.Format<"uuid">;

    /**
     * Search criteria including pagination, sorting, and time filters
     */
    body: IRedditCommunityPost.IRequest;
  };
  export type Body = IRedditCommunityPost.IRequest;
  export type Response = IPageIRedditCommunityPost.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditCommunity/member/members/:memberId/posts",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditCommunity/member/members/${encodeURIComponent(props.memberId ?? "null")}/posts`;
  export const random = (): IPageIRedditCommunityPost.ISummary =>
    typia.random<IPageIRedditCommunityPost.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("memberId")(() => typia.assert(props.memberId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
