import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IMallPlatformProductImage } from "../../../../structures/IMallPlatformProductImage";
import { IPageIMallPlatformProductImage } from "../../../../structures/IPageIMallPlatformProductImage";

/**
 * Update the ordered image set for a product.
 *
 * This operation lets the seller who owns the product maintain the product’s presentation by adding images, reordering them, or removing images as part of one product-scoped update. The first image in the final order becomes the main thumbnail used in listings and product detail pages.
 *
 * Only the owning seller may use this endpoint. The server must reject requests for products that do not belong to the authenticated seller, and it must preserve the product’s existing image state when validation fails or when any target image is unavailable. Successful changes must be recorded in the product snapshot history so the previous and updated image order can be reviewed later for disputes or audit purposes.
 *
 * @param props.connection
 * @param props.productId The unique identifier of the product whose image set is being maintained.
 * @param props.body The desired product image maintenance change, including new images, the final order, or image removals to apply to the product's gallery.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Load the product by productId and confirm the authenticated seller owns it. Treat this as a product-image maintenance command over the product's ordered image set. Apply the requested image changes atomically so partial reorder/delete/add operations do not leave the gallery in a mixed state.
 *
 * Validate that every referenced image belongs to the target product, that any reorder request covers only existing images, and that unavailable targets are rejected as business errors. If the request adds images, create new product image rows tied to the product and insert them in the requested order. If it reorders images, persist the new ordering and make the first item the main image. If it removes images, delete only the specified product image rows after confirming they still exist and belong to the product.
 *
 * After a successful change, create the corresponding product snapshot entry that captures the previous and new image state together with the rest of the product's editable data. On any validation or business-rule failure, roll back all database changes and do not create a snapshot. Return the updated product image collection in paginated summary form consistent with the index operation contract.
 * @path /mallPlatform/products/:productId/images
 * @accessor api.functional.mallPlatform.products.images.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * The unique identifier of the product whose image set is being maintained.
     */
    productId: string & tags.Format<"uuid">;

    /**
     * The desired product image maintenance change, including new images, the final order, or image removals to apply to the product's gallery.
     */
    body: IMallPlatformProductImage.IRequest;
  };
  export type Body = IMallPlatformProductImage.IRequest;
  export type Response = IPageIMallPlatformProductImage.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/mallPlatform/products/:productId/images",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/mallPlatform/products/${encodeURIComponent(props.productId ?? "null")}/images`;
  export const random = (): IPageIMallPlatformProductImage.ISummary =>
    typia.random<IPageIMallPlatformProductImage.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve one product image within its parent product.
 *
 * This operation returns the full image record for a single image attached to the requested product, including the image URL, display order, and whether it is the main thumbnail. The nested product context ensures the image is resolved only inside its owning product and prevents cross-product access to unrelated image records.
 *
 * The system should verify that both the product and image exist, that the image belongs to the given product, and that the caller is allowed to view the product's image data. If the product or image cannot be found, or if the image is not associated with the specified product, the request should fail with a normal business not-found error.
 *
 * @param props.connection
 * @param props.productId The product identifier in UUID form.
 * @param props.imageId The product image identifier in UUID form.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Load the product by `productId`, then load the image by `imageId` constrained to `mall_platform_product_images.mall_platform_product_id = productId`.
 *
 * Return the single product image record with its id, product id, image URL, sort order, main-image flag, created timestamp, updated timestamp, and deleted timestamp if applicable. Do not return images from other products.
 *
 * If the product does not exist, the image does not exist, or the image does not belong to the specified product, return a not-found style business error. Apply the same product access restrictions used elsewhere in the product image feature so unauthorized users cannot infer image existence across products. No write side effects are required.
 * @path /mallPlatform/products/:productId/images/:imageId
 * @accessor api.functional.mallPlatform.products.images.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The product identifier in UUID form.
     */
    productId: string & tags.Format<"uuid">;

    /**
     * The product image identifier in UUID form.
     */
    imageId: string & tags.Format<"uuid">;
  };
  export type Response = IMallPlatformProductImage;

  export const METADATA = {
    method: "GET",
    path: "/mallPlatform/products/:productId/images/:imageId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/mallPlatform/products/${encodeURIComponent(props.productId ?? "null")}/images/${encodeURIComponent(props.imageId ?? "null")}`;
  export const random = (): IMallPlatformProductImage =>
    typia.random<IMallPlatformProductImage>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.param("imageId")(() => typia.assert(props.imageId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
