import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IDiscussionBoardArticle } from "../../../../../structures/IDiscussionBoardArticle";
import { IPageIDiscussionBoardArticle } from "../../../../../structures/IPageIDiscussionBoardArticle";

/**
 * Create a new article in a discussion board section.
 *
 * This operation allows authenticated members to create new articles within a specific section of the discussion board. The article will be associated with the authenticated user as the author and the specified section as its category.
 *
 * When creating an article, users must provide a title and content body. The system enforces content validation including title length (1-200 characters) and content requirements. Users can optionally attach files and images to enrich their articles, and add tags for categorization and searchability.
 *
 * The operation validates user permissions, section existence, and content requirements before creating the article record. Upon successful creation, the article becomes immediately visible in the section's article list and other users can view and comment on it.
 *
 * The article uses a soft delete pattern with the `deleted_at` field to support content management while preserving historical data for audit purposes. When an article is "deleted", it is marked with a deletion timestamp rather than being permanently removed from the database.
 *
 * @param props.connection
 * @param props.sectionId Section's ID where the article will be created
 * @param props.body Article creation information
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdmin
 * @x-autobe-specification Create a new article in the specified section by inserting a record into the discussion_board_articles table.
 *
 * Database operations:
 * 1. Validate that section_id exists in discussion_board_sections table
 * 2. Create article record with provided title, content, section_id, and author_id
 * 3. Set created_at and updated_at to current timestamp
 * 4. Initialize view_count to 0
 * 5. Return the created article with all fields
 *
 * Validation rules:
 * - Title: Required, 1-200 characters
 * - Content: Required, minimum length requirement
 * - Section ID: Must exist in discussion_board_sections
 * - Authentication: User must be authenticated as member
 *
 * Post-creation:
 * - Increment section article count if applicable
 * - Return full article details including auto-generated fields
 * @path /discussionBoard/superAdmin/sections/:sectionId/articles
 * @accessor api.functional.discussionBoard.superAdmin.sections.articles.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Section's ID where the article will be created
     */
    sectionId: string;

    /**
     * Article creation information
     */
    body: IDiscussionBoardArticle.ICreate;
  };
  export type Body = IDiscussionBoardArticle.ICreate;
  export type Response = IDiscussionBoardArticle;

  export const METADATA = {
    method: "POST",
    path: "/discussionBoard/superAdmin/sections/:sectionId/articles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/discussionBoard/superAdmin/sections/${encodeURIComponent(props.sectionId ?? "null")}/articles`;
  export const random = (): IDiscussionBoardArticle =>
    typia.random<IDiscussionBoardArticle>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("sectionId")(() => typia.assert(props.sectionId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a filtered and paginated list of articles from a specific section.
 *
 * This operation provides comprehensive search and filtering capabilities for articles within a discussion board section. Users can search by title or content, filter by tags, sort by creation date, and navigate through paginated results.
 *
 * The operation supports advanced search functionality including partial text matching, multiple tag filtering, and configurable result ordering. Response includes article summary information optimized for list displays with essential metadata.
 *
 * @param props.connection
 * @param props.sectionId Target section's unique identifier.
 * @param props.body Search criteria and pagination parameters for article listing
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdmin
 * @x-autobe-specification Query discussion_board_articles table filtered by section_id with pagination and comprehensive search capabilities.
 * Apply title and content search filters using case-insensitive LIKE operations.
 * Apply tag filtering to return only articles matching all specified tags.
 * Support sorting by newest first (created_at DESC) or oldest first (created_at ASC).
 * Join with discussion_board_members table to include author information.
 * Join with discussion_board_article_tags and discussion_board_tags tables for tag filtering.
 * Implement pagination with configurable page size and offset calculation.
 * Return article summaries with essential fields for list displays.
 * @path /discussionBoard/superAdmin/sections/:sectionId/articles
 * @accessor api.functional.discussionBoard.superAdmin.sections.articles.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Target section's unique identifier.
     */
    sectionId: string;

    /**
     * Search criteria and pagination parameters for article listing
     */
    body: IDiscussionBoardArticle.IRequest;
  };
  export type Body = IDiscussionBoardArticle.IRequest;
  export type Response = IPageIDiscussionBoardArticle.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/discussionBoard/superAdmin/sections/:sectionId/articles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/discussionBoard/superAdmin/sections/${encodeURIComponent(props.sectionId ?? "null")}/articles`;
  export const random = (): IPageIDiscussionBoardArticle.ISummary =>
    typia.random<IPageIDiscussionBoardArticle.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("sectionId")(() => typia.assert(props.sectionId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
