import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { ICommunityPlatformPostVote } from "../../../../../structures/ICommunityPlatformPostVote";
import { ICommunityPlatformPostVoteScore } from "../../../../../structures/ICommunityPlatformPostVoteScore";

/**
 * Update the current user's vote on a specific post.
 *
 * This operation allows authenticated users to change their vote on a post by either upvoting, downvoting, or removing their previous vote. The system maintains vote integrity by ensuring each user can only have one vote per post and prevents users from voting on their own content.
 *
 * When a vote is changed, the system updates the post's aggregated vote scores in real-time and records the voting transaction for audit purposes. The response provides the updated vote counts including total upvotes, downvotes, and the calculated score difference.
 *
 * Vote operations follow strict business rules: users must be authenticated, cannot vote on their own posts, and are subject to rate limiting to prevent vote manipulation. The system ensures data consistency through transactional updates across multiple voting-related tables.
 *
 * @param props.connection
 * @param props.postId UUID identifier of the post to vote on
 * @param props.body Vote operation to perform on the post
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query the community_platform_post_votes table to check if the user already has a vote on this post. If vote exists, update the vote_type and record the change in voting_transactions with operation_type 'update'. If vote doesn't exist, create a new vote record with operation_type 'create'. Update the community_platform_post_vote_scores table to recalculate upvote_count, downvote_count, and total_score. Ensure user cannot vote on their own posts. Handle concurrent vote operations with optimistic locking. Return the updated vote scores for the post.
 * @path /communityPlatform/admin/posts/:postId/votes
 * @accessor api.functional.communityPlatform.admin.posts.votes.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * UUID identifier of the post to vote on
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Vote operation to perform on the post
     */
    body: ICommunityPlatformPostVote.IUpdate;
  };
  export type Body = ICommunityPlatformPostVote.IUpdate;
  export type Response = ICommunityPlatformPostVoteScore;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/admin/posts/:postId/votes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/admin/posts/${encodeURIComponent(props.postId ?? "null")}/votes`;
  export const random = (): ICommunityPlatformPostVoteScore =>
    typia.random<ICommunityPlatformPostVoteScore>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific vote cast on a post.
 *
 * This operation allows users to fetch complete details about a particular vote record, including the voter's information, vote type (upvote or downvote), and timestamps for when the vote was created and last updated. The operation validates that the vote ID corresponds to a vote on the specified post ID to ensure data integrity.
 *
 * Vote records contain metadata about user engagement with content and are used for calculating post scores and user karma. Each vote is uniquely identified by its ID and maintains relationships with both the voter and the post being voted on. The response includes all vote attributes as defined in the community_platform_post_votes database schema.
 *
 * This operation requires authentication as vote information is user-specific and contributes to the platform's engagement tracking system. Access controls ensure users can only view votes on publicly accessible posts or posts within communities they have appropriate access to.
 *
 * @param props.connection
 * @param props.postId ID of the post that received the vote
 * @param props.voteId ID of the specific vote record to retrieve
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Retrieve a specific vote record from the community_platform_post_votes table by its ID. Validate that the vote belongs to the specified post by checking the post_id foreign key relationship. Include user relationship data to show who cast the vote. Return complete vote information including vote type and timestamps.
 * @path /communityPlatform/admin/posts/:postId/votes/:voteId
 * @accessor api.functional.communityPlatform.admin.posts.votes.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * ID of the post that received the vote
     */
    postId: string & tags.Format<"uuid">;

    /**
     * ID of the specific vote record to retrieve
     */
    voteId: string & tags.Format<"uuid">;
  };
  export type Response = ICommunityPlatformPostVote;

  export const METADATA = {
    method: "GET",
    path: "/communityPlatform/admin/posts/:postId/votes/:voteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/admin/posts/${encodeURIComponent(props.postId ?? "null")}/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): ICommunityPlatformPostVote =>
    typia.random<ICommunityPlatformPostVote>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("voteId")(() => typia.assert(props.voteId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
