import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IEcommerceMallReview } from "../../../api/structures/IEcommerceMallReview";
import { getEcommerceMallReviewsReviewId } from "../../../providers/getEcommerceMallReviewsReviewId";

@Controller("/ecommerceMall/reviews/:reviewId")
export class EcommercemallReviewsController {
  /**
   * Retrieve a single review by its unique identifier.
   *
   * This endpoint retrieves the complete details of a specific review including the rating, text content, creation and update timestamps, and related information about the reviewer and product. Soft-deleted reviews are not accessible and return a 404 response.
   *
   * The response includes a summary of the customer who wrote the review. If the customer has been deleted, the customer name displays as 'deleted user' while preserving the rating and content. The product summary provides context about which product was reviewed.
   *
   * This operation is useful for displaying individual reviews in admin dashboards, customer service contexts, or when deep-linking to specific review pages.
   *
   * @param connection
   * @param reviewId Unique identifier of the review (UUID format)
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification Query the ecommerce_mall_reviews table using the provided reviewId.
   *
   * 1. Validate that reviewId is a valid UUID format.
   * 2. Query the review by id where deleted_at IS NULL (exclude soft-deleted reviews).
   * 3. If not found or soft-deleted, return 404 with error message 'Review not found'.
   * 4. Join with ecommerce_mall_customers table to get customer information (id, email).
   * 5. Join with ecommerce_mall_products table to get product information (id, name).
   * 6. Build the response with:
   *    - Review: id, rating, content, created_at, updated_at
   *    - Customer summary: id, displayName (or 'deleted user' if customer deleted_at is not null)
   *    - Product summary: id, name
   * 7. Return 200 with the complete review object.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @TypedParam("reviewId")
    reviewId: string & tags.Format<"uuid">,
  ): Promise<IEcommerceMallReview> {
    try {
      return await getEcommerceMallReviewsReviewId({
        reviewId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
