import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { deleteTodoAppAdminUsersUserId } from "../../../../providers/deleteTodoAppAdminUsersUserId";
import { AdminAuth } from "../../../../decorators/AdminAuth";
import { AdminPayload } from "../../../../decorators/payload/AdminPayload";

@Controller("/todoApp/admin/users/:userId")
export class TodoappAdminUsersController {
  /**
   * Permanently delete a user account.
   *
   * This operation performs a hard delete of a user account from the system.
   * When executed, the entire user record is permanently removed from the
   * todo_app_users table in the database with no possibility of recovery.
   *
   * This is an administrative operation intended for system administrators to
   * remove unwanted or problematic user accounts. It should not be used for
   * users deleting their own accounts, as that functionality is intentionally
   * not provided to preserve data integrity and compliance with data retention
   * policies.
   *
   * The user account record contains personal information, authentication data,
   * and associated permissions that are completely purged from the system when
   * this operation is executed. This includes all linked data and references
   * within the system.
   *
   * Security considerations require that this operation can only be executed by
   * authorized administrators and is subject to strict access controls. Log
   * entries must be created the authentication or audit log system to track
   * this destructive action.
   *
   * This operation has no request body and does not return a response body as
   * per system design, indicating successful deletion through HTTP status code
   * alone.
   *
   * @param connection
   * @param userId Unique identifier of the target user account to be
   *   permanently deleted from the system
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete()
  public async erase(
    @AdminAuth()
    admin: AdminPayload,
    @TypedParam("userId")
    userId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteTodoAppAdminUsersUserId({
        admin,
        userId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
