import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallOrderItem } from "../../../../../structures/IPageIShoppingMallOrderItem";
import { IShoppingMallOrderItem } from "../../../../../structures/IShoppingMallOrderItem";

/**
 * Retrieve a filtered and paginated list of order items from the shopping mall platform.
 *
 * This operation provides comprehensive search capabilities for order items, allowing users to filter by status, date ranges, price ranges, and specific order or product identifiers. The endpoint supports multiple actor types with appropriate data isolation: customers can view their own order items, sellers can view items containing their products, and administrators can view all order items across the platform.
 *
 * Order items represent individual line items within customer orders, each capturing a specific purchase with quantity, price at time of purchase, and current fulfillment status. The status field indicates the item's position in the fulfillment workflow: paid (order placed), shipped (item dispatched), delivered (item received), cancelled (pre-shipment cancellation approved), or refunded (post-delivery return approved).
 *
 * The response includes product and variant snapshots that preserve the state of these entities at order placement time, ensuring historical accuracy even if products or variants are later modified or deleted. Each order item is an independent entity that can be individually shipped, cancelled, refunded, or reviewed.
 *
 * For customers, this endpoint is useful for viewing purchase history and tracking order status. For sellers, it enables order management and fulfillment tracking. For administrators, it provides oversight of all platform transactions. Related operations include GET /orders/:orderId for detailed order information and POST /shipments for creating shipments for order items.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for order items
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Query shopping_mall_order_items table with pagination and filtering support.
 *
 * 1. AUTHENTICATION & DATA ISOLATION:
 *    - Customer context: Filter by shopping_mall_customer_id via order relationship
 *    - Seller context: Filter by shopping_mall_seller_id directly
 *    - Admin context: No filtering by actor, return all items
 *    - Apply soft delete filter: deleted_at IS NULL
 *
 * 2. SEARCH FILTERS (from IShoppingMallOrderItem.IRequest):
 *    - status: Filter by order item status (paid, shipped, delivered, cancelled, refunded)
 *    - orderId: Filter by specific order ID
 *    - productId: Filter by product ID (requires join)
 *    - variantId: Filter by variant ID (requires join)
 *    - createdAtFrom/createdAtTo: Date range filter on created_at
 *    - priceMin/priceMax: Price range filter
 *    - quantityMin/quantityMax: Quantity range filter
 *
 * 3. PAGINATION:
 *    - Accept page (default 1) and limit (default 20, max 100)
 *    - Return total count for pagination metadata
 *    - Support cursor-based pagination for large result sets
 *
 * 4. SORTING:
 *    - Default: created_at DESC (newest first)
 *    - Support: created_at, updated_at, price, quantity
 *    - Direction: ASC or DESC
 *
 * 5. JOIN OPERATIONS:
 *    - Join with shopping_mall_orders for customer_id access
 *    - Join with shopping_mall_products via product_snapshot parsing (if productId filter used)
 *    - Join with shopping_mall_product_variants via variant_snapshot parsing (if variantId filter used)
 *
 * 6. RESPONSE CONSTRUCTION:
 *    - Return IShoppingMallOrderItem.ISummary for each item
 *    - Include: id, orderId, status, quantity, price, createdAt, productSnapshot (parsed), variantSnapshot (parsed)
 *    - Exclude sensitive data based on actor type
 *    - Parse JSON snapshots for product/variant/seller information
 *
 * 7. ERROR HANDLING:
 *    - Return 404 if no items match criteria
 *    - Return 403 if actor lacks permission to view items
 *    - Validate pagination parameters (page >= 1, limit 1-100)
 *    - Validate status enum values
 * @path /shoppingMall/seller/orders/items
 * @accessor api.functional.shoppingMall.seller.orders.items.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for order items
     */
    body: IShoppingMallOrderItem.IRequest;
  };
  export type Body = IShoppingMallOrderItem.IRequest;
  export type Response = IPageIShoppingMallOrderItem.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/orders/items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/seller/orders/items";
  export const random = (): IPageIShoppingMallOrderItem.ISummary =>
    typia.random<IPageIShoppingMallOrderItem.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information for a specific order item by its unique identifier.
 *
 * This operation returns complete order item details including the product and variant information at the time of purchase, seller profile snapshot, quantity ordered, unit price, current fulfillment status, and creation/update timestamps. The order item represents a single line item within a customer's order transaction.
 *
 * Order items capture the state of products and sellers at purchase time through JSON snapshots, ensuring historical accuracy even if products are later modified or deleted. The status field indicates the current fulfillment state: paid (order placed), shipped (dispatched), delivered (received), cancelled (pre-shipment cancellation approved), or refunded (post-delivery return approved).
 *
 * Access Control:
 * - Customers can view order items from their own orders
 * - Sellers can view order items containing their products
 * - Administrators can view all order items across the platform
 * - Soft-deleted order items are not accessible
 *
 * Related Operations:
 * - GET /orders/{orderId} - Retrieve the parent order containing this item
 * - GET /shipments/{shipmentId} - View shipment details if item has been shipped
 * - POST /orders/items/{itemId}/cancel - Request cancellation (if status is 'paid')
 * - POST /orders/items/{itemId}/refund - Request refund (if status is 'delivered')
 * - POST /products/{productId}/reviews - Create a review (if status is 'delivered')
 *
 * @param props.connection
 * @param props.itemId Unique identifier of the order item to retrieve
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Query the shopping_mall_order_items table for a single record by primary key (id = itemId).
 *
 * Authorization Logic:
 * 1. If customer: verify shopping_mall_order_id belongs to the authenticated customer's orders
 * 2. If seller: verify shopping_mall_seller_id matches the authenticated seller
 * 3. If admin: allow access to any order item
 * 4. Return 404 if item not found or access denied
 *
 * Database Query:
 * - SELECT * FROM shopping_mall_order_items WHERE id = ? AND deleted_at IS NULL
 * - Join with shopping_mall_orders to verify customer ownership if needed
 * - Return single record or null if not found
 *
 * Data Transformation:
 * - Parse JSON snapshot fields (product_snapshot, variant_snapshot, seller_profile_snapshot)
 * - Include all fields: id, orderId, sellerId, quantity, price, status, snapshots, timestamps
 * - Handle soft-deleted items (deleted_at IS NOT NULL) - return 404
 *
 * Error Handling:
 * - 404 Not Found: item doesn't exist or is soft-deleted
 * - 403 Forbidden: authenticated user lacks permission to view this item
 * - 401 Unauthorized: missing or invalid authentication token
 * @path /shoppingMall/seller/orders/items/:itemId
 * @accessor api.functional.shoppingMall.seller.orders.items.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the order item to retrieve
     */
    itemId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallOrderItem;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/seller/orders/items/:itemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/seller/orders/items/${encodeURIComponent(props.itemId ?? "null")}`;
  export const random = (): IShoppingMallOrderItem =>
    typia.random<IShoppingMallOrderItem>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("itemId")(() => typia.assert(props.itemId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
