import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallProductReviewStatisticsBySeller } from "../../../../../../structures/IShoppingMallProductReviewStatisticsBySeller";
import { IPageIShoppingMallProductReviewStatisticsBySeller } from "../../../../../../structures/IPageIShoppingMallProductReviewStatisticsBySeller";

/**
 * Compute and retrieve aggregated review statistics grouped by seller from
 * shopping_mall_product_reviews.
 *
 * Retrieve aggregated review statistics per seller, derived from records in
 * `shopping_mall_product_reviews` and related catalog entities that associate
 * reviews with seller accounts.
 *
 * The `shopping_mall_product_reviews` table stores "Customer-authored product
 * reviews and star ratings" and is expected to reference products or SKUs,
 * which in turn are associated with sellers through catalog ownership
 * relationships. This operation takes a filter payload typed as
 * `IShoppingMallProductReviewStatisticsBySeller.IRequest`, including optional
 * seller identifiers, category filters, rating ranges, date intervals (for
 * example, last 30 days), and moderation state constraints. Using these
 * filters, the service aggregates review data per seller to compute metrics
 * such as total number of reviews, average rating, and rating distribution
 * buckets.
 *
 * The response is a paginated collection
 * `IPageIShoppingMallProductReviewStatisticsBySeller`, where each entry
 * summarizes the computed statistics for a single seller under the specified
 * filters. This Aggregated information is used by admin dashboards for
 * marketplace health monitoring, by seller performance views, and by risk or
 * fraud analysis tools that may combine these statistics with other signals
 * such as `shopping_mall_seller_performance_summaries`.
 *
 * Access to this endpoint is restricted to authenticated actors, specifically
 * platform administrators and sellers, declared as `authorizationActors:
 * ["platformAdmin", "seller"]`. Platform administrators generally have full
 * visibility across all sellers, while each seller is limited to viewing only
 * their own statistics. These constraints must be enforced by the authorization
 * layer. Error handling should cover invalid identifiers or filter
 * combinations, attempts to access data outside the caller’s scope, and
 * requests that are too broad to serve efficiently within system limits.
 *
 * @param props.connection
 * @param props.body Filter, grouping, and pagination criteria used to compute
 *   seller-level review statistics.
 * @path /shoppingMall/seller/reviews/statistics/bySeller
 * @accessor api.functional.shoppingMall.seller.reviews.statistics.bySeller.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Filter, grouping, and pagination criteria used to compute
     * seller-level review statistics.
     */
    body: IShoppingMallProductReviewStatisticsBySeller.IRequest;
  };
  export type Body = IShoppingMallProductReviewStatisticsBySeller.IRequest;
  export type Response = IPageIShoppingMallProductReviewStatisticsBySeller;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/reviews/statistics/bySeller",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/seller/reviews/statistics/bySeller";
  export const random = (): IPageIShoppingMallProductReviewStatisticsBySeller =>
    typia.random<IPageIShoppingMallProductReviewStatisticsBySeller>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
