import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIHrmPlatformProjectWeeklySummary } from "../../../../../../structures/IPageIHrmPlatformProjectWeeklySummary";

/**
 * Retrieves paginated week-by-week aggregated time tracking data for a specific project, grouping timelogs by week (Monday through Sunday).
 *
 * Returns weekly summary records with total hours logged, timelog entry count, and distinct employee participation count for each week.
 *
 * Results are ordered by week_start in descending order (most recent weeks first). The endpoint supports cursor-based pagination for navigating large historical datasets.
 *
 * Requires valid project UUID in the path. Returns 404 if the project does not exist or has been soft-deleted.
 *
 * @param props.connection
 * @param props.projectId UUID identifier of the project to retrieve weekly time tracking report data for.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query hrm_platform_timelogs for timelogs where
 *   hrm_platform_project_id matches the projectId parameter AND deleted_at IS
 *   NULL. GROUP BY week_start (Monday of the week), calculating: - week_start:
 *   Monday timestamp for each week - week_end: Sunday timestamp for each week -
 *   total_hours: SUM(duration_minutes) / 60 converted to hours -
 *   timelogs_count: COUNT of timelog entries for the week - employee_count:
 *   COUNT DISTINCT hrm_platform_employee_id
 *
 * ORDER BY week_start DESC (most recent weeks first)
 * Apply cursor-based pagination for large result sets, returning matching paginated structure with total count, page size, and cursor fields.
 * Return 404 NOT_FOUND if the project does not exist or has been soft-deleted (deleted_at IS NOT NULL).
 * @path /hrmPlatform/member/projects/:projectId/reports/weekly
 * @accessor api.functional.hrmPlatform.member.projects.reports.weekly.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * UUID identifier of the project to retrieve weekly time tracking report data for.
     */
    projectId: string & tags.Format<"uuid">;
  };
  export type Response = IPageIHrmPlatformProjectWeeklySummary.ISummary;

  export const METADATA = {
    method: "GET",
    path: "/hrmPlatform/member/projects/:projectId/reports/weekly",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrmPlatform/member/projects/${encodeURIComponent(props.projectId ?? "null")}/reports/weekly`;
  export const random = (): IPageIHrmPlatformProjectWeeklySummary.ISummary =>
    typia.random<IPageIHrmPlatformProjectWeeklySummary.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("projectId")(() => typia.assert(props.projectId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
