import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IMallPlatformSellerAccount } from "../../../../api/structures/IMallPlatformSellerAccount";
import { IPageIMallPlatformSellerAccount } from "../../../../api/structures/IPageIMallPlatformSellerAccount";
import { AdministratorAuth } from "../../../../decorators/AdministratorAuth";
import { AdministratorPayload } from "../../../../decorators/payload/AdministratorPayload";
import { getMallPlatformAdministratorSellerAccountsSellerAccountId } from "../../../../providers/getMallPlatformAdministratorSellerAccountsSellerAccountId";
import { patchMallPlatformAdministratorSellerAccounts } from "../../../../providers/patchMallPlatformAdministratorSellerAccounts";

@Controller("/mallPlatform/administrator/sellerAccounts")
export class MallplatformAdministratorSelleraccountsController {
  /**
   * Retrieve a paginated list of seller accounts for browsing, review, and account-management workflows.
   *
   * This operation returns seller account records in summary form so consumers can inspect seller identity and current account state without loading full detail records. It is intended for seller administration, approval review, moderation, and account discovery flows where filtering, sorting, and pagination are required.
   *
   * The list reflects the current seller account lifecycle state stored in the seller account records, allowing consumers to search by approval or moderation-related conditions and to page through large datasets safely. When a seller account is not available because it has been rejected, suspended, or otherwise restricted, the list should still reflect that state rather than omitting the account from administrative results.
   *
   * Validation and access control must ensure that only authorized members can use this operation. Invalid search criteria, unsupported sort options, or pagination values outside accepted bounds must be rejected with a clear error response.
   *
   * @param connection
   * @param body Seller account search, filtering, sorting, and pagination criteria.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor administrator
   * @x-autobe-specification Query mall_platform_sellers and related seller account records for searchable account management.
   * Support pagination, keyword search, status filtering, and sorting in the request body.
   * Return summary rows only; do not include sensitive authentication material.
   * Apply authorization checks so only permitted administrators or otherwise authorized actors can access the collection.
   * Use stable ordering for pagination and deterministic sorting to avoid duplicates or gaps between pages.
   * If the underlying schema exposes approval or moderation state fields, filter and sort by those fields directly; otherwise, rely only on fields that exist in the seller account schema.
   * Handle empty result sets with a valid empty page response.
   * Reject invalid pagination, unsupported sort keys, and malformed filters with validation errors.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @AdministratorAuth()
    administrator: AdministratorPayload,
    @TypedBody()
    body: IMallPlatformSellerAccount.IRequest,
  ): Promise<IPageIMallPlatformSellerAccount.ISummary> {
    try {
      return await patchMallPlatformAdministratorSellerAccounts({
        administrator,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve the full seller account record for a single merchant account.
   *
   * This operation returns the current seller account state used for authentication, approval tracking, and account lifecycle control. It is intended for seller self-service views and administrator moderation screens where the platform needs to inspect whether the account is pending, approved, rejected, suspended, or otherwise unavailable for selling.
   *
   * The response is centered on the seller account entity itself, which is the privileged merchant identity used to sign in and access seller features. When the account has a rejected approval status, the response should expose the stored rejection reason so the seller can understand why the request was denied and decide whether to submit a new registration request. Authorization must ensure that a seller can only read their own account, while administrators may read any seller account.
   *
   * If the seller account cannot be found, has been deleted, or is not accessible to the current caller, the service should return an appropriate not-found or forbidden-style error according to the platform’s standard error handling rules.
   *
   * @param connection
   * @param sellerAccountId The seller account identifier (UUID).
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor administrator
   * @x-autobe-specification Load the seller account row by primary identifier and return it as a complete entity view. Do not include authentication session data, password reset data, or unrelated seller profile content in this endpoint.
   *
   * Verify that the caller is either the owner of the seller account or an administrator with permission to inspect seller accounts. Reject access to other sellers’ accounts for non-admin callers.
   *
   * If the seller account is missing, deleted, banned, suspended, or otherwise unavailable, return a not-found or access-denied response consistent with platform rules. If the approval status is rejected, include the rejection reason stored on the account. No mutation or snapshot creation occurs in this read operation.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":sellerAccountId")
  public async at(
    @AdministratorAuth()
    administrator: AdministratorPayload,
    @TypedParam("sellerAccountId")
    sellerAccountId: string & tags.Format<"uuid">,
  ): Promise<IMallPlatformSellerAccount> {
    try {
      return await getMallPlatformAdministratorSellerAccountsSellerAccountId({
        administrator,
        sellerAccountId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
