import { Controller, Ip } from "@nestjs/common";
import { TypedRoute, TypedBody } from "@nestia/core";
import typia from "typia";
import { postAuthAdminJoin } from "../../../providers/postAuthAdminJoin";
import { postAuthAdminLogin } from "../../../providers/postAuthAdminLogin";
import { postAuthAdminRefresh } from "../../../providers/postAuthAdminRefresh";

import { ITodoListAdmin } from "../../../api/structures/ITodoListAdmin";

@Controller("/auth/admin")
export class AuthAdminController {
  /**
   * Registers a new admin in the 'todo_list_admins' table and issues initial
   * tokens.
   *
   * This API endpoint enables the registration of a new administrator.
   *
   * The core operation corresponds to the 'todo_list_admins' Prisma schema,
   * utilizing the 'email' field (globally unique) and a strong 'password_hash'
   * for secret management. New administrator accounts must be immediately
   * associated with required user metadata ('created_at', 'updated_at'),
   * maintaining compliance and audit granularity.
   *
   * On registration, the password is never stored directly; only the securely
   * hashed 'password_hash' is populated. The endpoint follows strict validation
   * logic to ensure both the uniqueness of the email (enforced at the schema
   * and API layers) and password policy compliance.
   *
   * Successful registration initiates a first authentication session (see:
   * 'todo_list_admin_sessions') and issues JWT tokens for subsequent admin
   * requests. The account's 'is_locked' property is always set to 'false' at
   * creation for initial access unless overridden by compliance/triggers.
   *
   * For onboarding flows, consider integrating this operation with an external
   * approval or notification workflow. Related operations: 'login', 'refresh'.
   *
   * @param connection
   * @param body Administrator registration payload. Expects email and password
   *   (hashed before storage).
   * @setHeader token.access Authorization
   *
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("join")
  public async join(
    @Ip()
    ip: string,
    @TypedBody()
    body: ITodoListAdmin.IJoin,
  ): Promise<ITodoListAdmin.IAuthorized> {
    try {
      return await postAuthAdminJoin({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Authenticates admin credentials and issues access tokens from
   * 'todo_list_admins'.
   *
   * The login API enables administrators to obtain access credentials after
   * verifying their identity.
   *
   * Relies on 'todo_list_admins' for credential validation—'email' uniquely
   * identifies the admin, and the provided password must hash-exactly match
   * 'password_hash' in the schema. The account's 'is_locked' flag is strictly
   * enforced: locked admins are denied authentication.
   *
   * Upon success, a new session record is created in
   * 'todo_list_admin_sessions', associating login metadata such as IP address
   * and user agent for audit tracking.
   *
   * Authentication tokens (JWT) are returned as part of the response, following
   * RBAC best practices. Account lockouts and repeated failed attempts are to
   * be handled by an external security process if not described in this
   * schema.
   *
   * This operation is the primary authentication gateway and should be
   * integrated with 'join' and 'refresh'. Error responses include generic
   * credentials invalidation and lock status reporting.
   *
   * @param connection
   * @param body Admin login credentials (email and password).
   * @setHeader token.access Authorization
   *
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("login")
  public async login(
    @Ip()
    ip: string,
    @TypedBody()
    body: ITodoListAdmin.ILogin,
  ): Promise<ITodoListAdmin.IAuthorized> {
    try {
      return await postAuthAdminLogin({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Refreshes admin JWT tokens using a valid session in
   * 'todo_list_admin_sessions'.
   *
   * The refresh endpoint enables administrators to renew their authentication
   * tokens without resubmitting credentials.
   *
   * Works with the 'todo_list_admin_sessions' Prisma model: the request must
   * include a valid, unexpired refresh token that links to an existing session
   * (fields: 'created_at', 'expired_at').
   *
   * Additional checks verify the associated admin in 'todo_list_admins' is
   * still active (not 'is_locked'), guaranteeing only authorized, eligible
   * admins may refresh their sessions.
   *
   * Success results in new tokens and session lifespan extension, while
   * invalid, expired, or revoked sessions are rejected for security compliance.
   * Token rotation and audit events should be managed as described by system
   * security policies.
   *
   * Frequently used together with 'login' and 'join' operations; follow best
   * practices to limit session duration and enforce single-device or
   * multi-session limits as needed by business logic.
   *
   * @param connection
   * @param body Payload containing the refresh token associated with an active
   *   admin session.
   * @setHeader token.access Authorization
   *
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("refresh")
  public async refresh(
    @TypedBody()
    body: ITodoListAdmin.IRefresh,
  ): Promise<ITodoListAdmin.IAuthorized> {
    try {
      return await postAuthAdminRefresh({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
