import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIRedditCloneComment } from "../../../../../structures/IPageIRedditCloneComment";
import { IRedditCloneComment } from "../../../../../structures/IRedditCloneComment";

/**
 * Retrieve a sorted and paginated list of comments on a specific post.
 *
 * This operation returns all top-level comments on the specified post, each with its nested replies displayed hierarchically. Comments can be sorted by Best (highest vote score), New (most recent), or Controversial (many votes but score near zero).
 *
 * Each comment in the response includes the author's username, content text, vote score, creation timestamp, and a nested array of replies. Deleted comments are included with a placeholder indicator while preserving their reply structure.
 *
 * The response is paginated to handle posts with many comments efficiently. Clients can specify page size and cursor-based pagination parameters.
 *
 * @param props.connection
 * @param props.postId Unique identifier of the post (UUID format)
 * @param props.body Search criteria including sort order, pagination parameters, and optional filters
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query reddit_clone_comments table filtered by postId for top-level comments (parent_comment_id IS NULL).
 *
 * Apply sorting based on sort parameter:
 * - Best: ORDER BY vote_score DESC, created_at DESC
 * - New: ORDER BY created_at DESC
 * - Controversial: ORDER BY ABS(vote_score) ASC, vote_score DESC, created_at DESC
 *
 * Join with reddit_clone_members to include author username.
 *
 * Include nested replies by recursively loading child comments where parent_comment_id matches parent comment IDs.
 *
 * For deleted comments (deleted_at IS NOT NULL), set content to null/placeholder in response but still include the record to preserve tree structure.
 *
 * Apply pagination with configurable page size (default 20, max 100) and cursor-based navigation.
 *
 * Validate postId exists in reddit_clone_posts table before querying comments.
 * @path /redditClone/redditClone/posts/:postId/comments
 * @accessor api.functional.redditClone.redditClone.posts.comments.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Unique identifier of the post (UUID format)
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Search criteria including sort order, pagination parameters, and optional filters
     */
    body: IRedditCloneComment.IRequest;
  };
  export type Body = IRedditCloneComment.IRequest;
  export type Response = IPageIRedditCloneComment.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditClone/redditClone/posts/:postId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditClone/redditClone/posts/${encodeURIComponent(props.postId ?? "null")}/comments`;
  export const random = (): IPageIRedditCloneComment.ISummary =>
    typia.random<IPageIRedditCloneComment.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a single comment by its unique identifier.
 *
 * This endpoint fetches a specific comment belonging to a post. The response includes the comment's content, author information, vote score, and all nested replies recursively indented under the parent comment.
 *
 * When the comment has been soft-deleted (deleted_at is not null), the response includes the comment with a null content field while still preserving and recursively including all nested replies to maintain conversation continuity.
 *
 * The comment's replies are sorted by Best (vote score descending). This endpoint is publicly accessible and does not require authentication.
 *
 * @param props.connection
 * @param props.postId Unique identifier of the parent post (global scope)
 * @param props.commentId Unique identifier of the comment (global scope)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Query reddit_clone_comments table by comment_id, verifying it belongs to the specified post_id.
 *
 * Join with reddit_clone_members to retrieve author information: member id and username.
 *
 * Include all nested replies by querying for child comments where parent_comment_id equals the requested comment_id. Recursively load replies for each nested comment.
 *
 * Calculate relative timestamp for created_at display (e.g., "3 hours ago").
 *
 * If comment is soft-deleted (deleted_at is not null), return content as null but still include nested replies.
 *
 * Return 404 if comment does not exist or does not belong to the specified post.
 * @path /redditClone/redditClone/posts/:postId/comments/:commentId
 * @accessor api.functional.redditClone.redditClone.posts.comments.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the parent post (global scope)
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Unique identifier of the comment (global scope)
     */
    commentId: string & tags.Format<"uuid">;
  };
  export type Response = IRedditCloneComment.IInvert;

  export const METADATA = {
    method: "GET",
    path: "/redditClone/redditClone/posts/:postId/comments/:commentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditClone/redditClone/posts/${encodeURIComponent(props.postId ?? "null")}/comments/${encodeURIComponent(props.commentId ?? "null")}`;
  export const random = (): IRedditCloneComment.IInvert =>
    typia.random<IRedditCloneComment.IInvert>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("commentId")(() => typia.assert(props.commentId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
