import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallProduct } from "../../../structures/IShoppingMallProduct";
import { IPageIShoppingMallProduct } from "../../../structures/IPageIShoppingMallProduct";
export * as skus from "./skus/index";
export * as images from "./images/index";

/**
 * Create a new product entry in the shopping mall's catalog.
 *
 * The API accepts data for a new product, including its name, business
 * description, default listing price, workflow status string (e.g., draft,
 * published, archived, blocked), and the identifier of the owning seller. The
 * system automatically sets creation and update timestamps. This operation
 * enforces business logic such as requiring the title to be unique for each
 * seller, setting appropriate initial status, and storing the core catalog
 * structure to enable future expansion with SKUs, images, and categorization.
 *
 * The response returns the full product record as stored, including all fields
 * present in the shopping_mall_products schema. Any attempted creation with
 * non-unique title per seller or invalid field values will result in validation
 * errors, which must be handled according to business rules.
 *
 * @param props.connection
 * @param props.body Product creation information to populate the
 *   shopping_mall_products table
 * @path /shoppingMall/products
 * @accessor api.functional.shoppingMall.products.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Product creation information to populate the shopping_mall_products
     * table
     */
    body: IShoppingMallProduct.ICreate;
  };
  export type Body = IShoppingMallProduct.ICreate;
  export type Response = IShoppingMallProduct;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/products",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/products";
  export const random = (): IShoppingMallProduct =>
    typia.random<IShoppingMallProduct>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * List and search products in the shopping mall catalog using complex query,
 * filtering, and pagination.
 *
 * This operation is accessible to all users and does not require
 * authentication, enabling public discovery of marketplace offerings. It
 * supports filtering by title, description, seller, workflow status,
 * creation/modification date, and more. Query results are paginated and
 * returned in summary DTO format, optimized for grid or list display in user
 * interfaces. Sorting options such as by price, popularity, and recency are
 * supported for flexible UX needs.
 *
 * The operation enforces query-side validation for supported fields, size
 * limits (to prevent overload), and input sanitization for search safety.
 * Related operations include creating, updating, retrieving, or deleting
 * individual products and categories. The resulting dataset is suitable for
 * front-facing discovery surfaces, search bars, and product suggestion features
 * across the platform. Hard-deleted or archived products are automatically
 * excluded from results.
 *
 * @param props.connection
 * @param props.body Filter and search criteria, pagination, and sorting for
 *   product list retrieval.
 * @path /shoppingMall/products
 * @accessor api.functional.shoppingMall.products.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Filter and search criteria, pagination, and sorting for product list
     * retrieval.
     */
    body: IShoppingMallProduct.IRequest;
  };
  export type Body = IShoppingMallProduct.IRequest;
  export type Response = IPageIShoppingMallProduct.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/products",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/products";
  export const random = (): IPageIShoppingMallProduct.ISummary =>
    typia.random<IPageIShoppingMallProduct.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve the complete product details for the specified product.
 *
 * This API is used to access all business and presentation data of a single
 * product, including its title, core description, default display price,
 * business status (such as draft, published, archived, etc.), and audit
 * timestamps such as creation and last update times. It returns seller
 * association by referencing the owning seller's unique identifier and provides
 * information on whether the product is soft-deleted or active via the
 * deleted_at field.
 *
 * Only public data and fields marked as non-sensitive are exposed in this
 * response; sensitive seller or internal audit information should be handled at
 * the service layer or via access scopes in the API layer.
 *
 * This endpoint strictly references the shopping_mall_products table as
 * described in the Prisma schema and ensures that all fields are included in
 * the response in accordance with the current schema structure. Related
 * entities such as SKUs, images, or category assignments are not directly
 * included in this response unless explicitly expanded through other
 * endpoints.
 *
 * @param props.connection
 * @param props.productId Unique identifier of the target product in the catalog
 * @path /shoppingMall/products/:productId
 * @accessor api.functional.shoppingMall.products.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the target product in the catalog */
    productId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallProduct;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/products/:productId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/products/${encodeURIComponent(props.productId ?? "null")}`;
  export const random = (): IShoppingMallProduct =>
    typia.random<IShoppingMallProduct>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
