import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IErpHrmTimeTrackingReportOutputMetric } from "../../../api/structures/IErpHrmTimeTrackingReportOutputMetric";
import { deleteErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId } from "../../../providers/deleteErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId";
import { getErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId } from "../../../providers/getErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId";
import { postErpHrmTimeTrackingReportOutputMetrics } from "../../../providers/postErpHrmTimeTrackingReportOutputMetrics";
import { putErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId } from "../../../providers/putErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId";

@Controller("/erpHrmTimeTracking/reportOutputMetrics")
export class ErphrmtimetrackingReportoutputmetricsController {
  /**
   * Retrieve one generated report output metric line by its identifier.
   *
   * This operation is intended for viewing a specific metric breakdown row that is produced as part of a time-tracking report run. The underlying database model stores metric name/value pairs (for example, hours, amount, or billable_hours) for a specific parent report output row, with deterministic audit fields (created_at/updated_at) and an optional deleted_at timestamp to represent removed configuration/rows.
   *
   * Access to this endpoint is governed by the same organization-context and report-viewing requirements as other report-related operations. If the caller does not have an active organization context selected, the system must block the request with a business validation message. If the caller attempts to access a metric that belongs to a different organization than the selected context, the system must reject the request to prevent cross-organization data leakage.
   *
   * The response is a single metric record identified by reportOutputMetricId. The operation does not trigger any report generation workflow; it only reads persisted results produced by previous report run executions.
   *
   * Related behavior consistency: when the requested metric cannot be found for the given organization context, the system should reject with a clear, human-readable failure response consistent with other error scenarios, without exposing details that would allow identifying data in other organizations.
   *
   * @param connection
   * @param reportOutputMetricId Identifier of the report output metric line to retrieve (UUID).
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification Implementation steps:
   *
   * 1) Parse the path parameter reportOutputMetricId (UUID) and load erp_hrm_time_tracking_report_output_metrics where id = reportOutputMetricId AND deleted_at is null (or treat deleted rows as not retrievable, consistent with DTO stance).
   *
   * 2) Join/validate ownership in the selected organization context:
   *    - Follow relations from report_output_metrics.reportOutput -> report_generation_run -> report_definition -> erp_hrm_time_tracking_organizations.
   *    - Ensure the resolved organization matches the currently selected organization context for the authenticated member.
   *
   * 3) Authorization checks:
   *    - Verify the actor has permission to view reports for the selected organization context (report:view capability).
   *    - If organization context is missing, block with the business message described in the report error scenarios.
   *
   * 4) Return the mapped DTO for the metric record, including:
   *    - metric_name
   *    - metric_value
   *    - created_at, updated_at
   *    - (and any other fields exposed by IErpHrmTimeTrackingReportOutputMetric per DTO mapping)
   *
   * 5) Error handling:
   *    - If no row matches within the selected organization context, reject the request with a consistent error response (do not reveal existence in other organizations).
   *    - If internal unexpected failures occur, reject without partial updates.
   *
   * No transactions are required because this is a read-only operation.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":reportOutputMetricId")
  public async at(
    @TypedParam("reportOutputMetricId")
    reportOutputMetricId: string & tags.Format<"uuid">,
  ): Promise<IErpHrmTimeTrackingReportOutputMetric> {
    try {
      return await getErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId(
        {
          reportOutputMetricId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Updates a single report output metric record identified by `reportOutputMetricId`.
   *
   * This endpoint operates on {@link erp_hrm_time_tracking_report_output_metrics}, which stores one metric breakdown line (by `metric_name`) and its numeric `metric_value` for a specific report output row (`erp_hrm_time_tracking_report_output_id`). The table is uniquely constrained by `@@unique([erp_hrm_time_tracking_report_output_id, metric_name])`, so updates must preserve that invariant for the parent report output grouping.
   *
   * Authorization and organization context: report outputs and their metrics are generated within an organization and are protected by report-view permissions. The system must enforce organization-scoped authorization checks (the selected organization context is required for report operations). If organization context is missing, the request must be blocked with a business validation message as required for report operations.
   *
   * Validation and update rules: the request targets a single metric row by its primary key (`id`). The service layer must validate that the caller is allowed to modify the corresponding report output (reachable via `erp_hrm_time_tracking_report_output_id` → {@link erp_hrm_time_tracking_report_outputs} → {@link erp_hrm_time_tracking_report_generation_runs}). Business validation should ensure the update does not create inconsistencies in the metric breakdown: in particular, the unique constraint on `(erp_hrm_time_tracking_report_output_id, metric_name)` must not be violated.
   *
   * Edge cases: if the target metric id does not exist, the system must return an appropriate not-found error. If the caller lacks permission for the organization that owns the parent report output, the system must block the update. If the update is rejected by business validation, the system must not produce misleading activity log success records; activity log entries must reflect actual outcomes only.
   *
   * @param connection
   * @param reportOutputMetricId Primary key of the report output metric row to update.
   * @param body Update payload for a single report output metric row. Fields included here should modify the metric breakdown (for example, the numeric metric value), while preserving the parent linkage and uniqueness invariants.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification 1) Extract `reportOutputMetricId` from path.
   * 2) Parse and validate request body using DTO `IErpHrmTimeTrackingReportOutputMetric.IUpdate`.
   * 3) Load the metric row by primary key from `erp_hrm_time_tracking_report_output_metrics`.
   * 4) Authorization: resolve the parent `erp_hrm_time_tracking_report_outputs` row via `erp_hrm_time_tracking_report_output_id`, then resolve its `report_generation_run_id` via `erp_hrm_time_tracking_report_generation_runs` (organization scoping). Enforce that the caller has the required report access within the currently selected organization context.
   * 5) Apply updates in a transaction:
   *    - Always keep `erp_hrm_time_tracking_report_output_id` immutable (unless the DTO explicitly allows it; by default updates should only affect `metric_value` and any other mutable fields present in the DTO).
   *    - If `metric_name` is updatable, validate uniqueness by checking whether another metric row exists with the same `(erp_hrm_time_tracking_report_output_id, metric_name)`.
   * 6) Persist changes; update `updated_at` automatically as per model behavior.
   * 7) Return the updated metric entity.
   *
   * Error handling:
   * - Not found: return 404 when id does not exist.
   * - Permission/context missing: block with a business validation error per report rules.
   * - Constraint violation: return 409 or a business error mapped from unique constraint failure.
   *
   * Activity log:
   * - If the operation fails validation, ensure no misleading successful activity log is created.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":reportOutputMetricId")
  public async update(
    @TypedParam("reportOutputMetricId")
    reportOutputMetricId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IErpHrmTimeTrackingReportOutputMetric.IUpdate,
  ): Promise<IErpHrmTimeTrackingReportOutputMetric> {
    try {
      return await putErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId(
        {
          reportOutputMetricId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Permanently removes one report output metric row identified by its id.
   *
   * This operation targets the erp_hrm_time_tracking_report_output_metrics model, which stores a normalized breakdown metric (metric_name + metric_value) for a single erp_hrm_time_tracking_report_outputs row. Each metric row is uniquely identified by erp_hrm_time_tracking_report_output_metrics.id, and is additionally constrained by a unique key on (erp_hrm_time_tracking_report_output_id, metric_name) so that the same metric_name cannot be duplicated within the same parent report output.
   *
   * Authorization is based on the user’s selected organization context and time/report viewing or management capabilities. The caller must have permission to modify reporting outputs within the selected organization; otherwise the request must be rejected.
   *
   * Validation and behavior:
   * - The path parameter reportOutputMetricId must be a valid UUID.
   * - If no metric row exists for the provided id, the operation must fail with a not-found error.
   * - The removed metric row must no longer be returned by any report generation output retrieval that depends on erp_hrm_time_tracking_report_output_metrics.
   *
   * Error handling:
   * - If the organization context is missing, the system must block report-related access and return a business validation message requiring an organization context selection.
   * - If the system cannot find the targeted metric row within the selected organization scope, the request must be rejected as not found.
   *
   * Related operations:
   * - Use the corresponding report output endpoints (e.g., fetching report outputs and their metric breakdown) before or after this deletion to understand how the removal affects the overall generated report result set.
   *
   * @param connection
   * @param reportOutputMetricId The unique id of the report output metric row to remove (UUID).
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification Realize DELETE /reportOutputMetrics/{reportOutputMetricId}.
   *
   * 1) Parse and validate reportOutputMetricId as UUID.
   * 2) Resolve the selected organization context for the authenticated member.
   * 3) Authorization check: ensure the actor has permission to manage reporting outputs within the selected organization context. Deny when unauthorized.
   * 4) Query erp_hrm_time_tracking_report_output_metrics by id and join (or filter through) erp_hrm_time_tracking_report_outputs to ensure the parent report output belongs to the selected organization.
   * 5) If no row exists in that scope, return not-found.
   * 6) Permanently remove the erp_hrm_time_tracking_report_output_metrics row.
   *    - If the implementation uses ORM delete, ensure cascade rules do not unexpectedly affect other unrelated report outputs.
   * 7) Optionally create an ActivityLogEntry capturing the performed deletion (who/when/what entity), if the service layer standard for auditable operations is enabled in this codebase.
   * 8) Return 200/204 with an empty JSON body (responseBody is null in the API contract).
   *
   * Edge cases:
   * - Concurrent deletions of the same metric id: if the row is already gone, treat as not-found.
   * - Organization mismatch: treat as not-found (do not leak existence across organizations).
   *
   * No request body is accepted.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":reportOutputMetricId")
  public async erase(
    @TypedParam("reportOutputMetricId")
    reportOutputMetricId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteErpHrmTimeTrackingReportOutputMetricsReportOutputMetricId(
        {
          reportOutputMetricId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Create a report output metric breakdown line for a generated report output.
   *
   * This operation inserts a single metric row in the time tracking reporting domain. The row is identified by `metric_name` and stored as a normalized name/value metric linked to a specific report output grouping row.
   *
   * It is intended to be used by the report generation workflow that produces `erp_hrm_time_tracking_report_generation_runs` and writes `erp_hrm_time_tracking_report_outputs`. The parent-child relationship means the metric row always belongs to an existing report output row (`erp_hrm_time_tracking_report_output_id`).
   *
   * Authorization should restrict access so only callers allowed to manage report generation outputs can create metric rows. Input validation must ensure the referenced parent report output exists and that the provided numeric value is accepted as the metric amount for the parent output.
   *
   * Expected behavior is to reject requests that violate the per-output uniqueness of `metric_name` (i.e., the same metric cannot be inserted twice for the same parent output). If the insert succeeds, the operation returns the created metric record representation.
   *
   * Related operations include creating the parent report output rows (`erp_hrm_time_tracking_report_outputs`) and accessing the report generation run context (`erp_hrm_time_tracking_report_generation_runs`) for traceability of what was generated.
   *
   * @param connection
   * @param body Creation payload for a single report output metric breakdown line.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor null
   * @x-autobe-specification Implementation steps:
   * 1) Validate the actor has permission to create report output metric rows. If the system treats report generation as internal-only, block external callers.
   * 2) Parse request body into DTO for report output metric creation.
   * 3) Validate parent linkage by reading `erp_hrm_time_tracking_report_outputs` where `id = erp_hrm_time_tracking_report_output_id`. If not found, reject with a business validation error.
   * 4) Enforce uniqueness: attempt insert and rely on unique constraint `(report_output_id, metric_name)`. If constraint fails, reject with a clear error stating that the metric_name already exists for the parent output.
   * 5) Insert into `erp_hrm_time_tracking_report_output_metrics` with:
   *    - `erp_hrm_time_tracking_report_output_id`
   *    - `metric_name`
   *    - `metric_value`
   *    - timestamps (created_at/updated_at) managed by application or database defaults
   *    - `deleted_at` should be null on creation.
   * 6) Return the created record fields required by the response DTO.
   *
   * Edge cases:
   * - Concurrent inserts for the same `(output_id, metric_name)` should result in one success and other failure due to the unique constraint.
   * - Reject if parent output is deleted/absent (if deleted_at handling is implemented at query level).
   *
   * Transactionality:
   * - This endpoint writes a single row; if used as part of a larger report generation workflow, the calling workflow should wrap multi-row insertion in a transaction or treat failures as a full generation failure, ensuring no misleading partial results are emitted.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async createReportOutputMetric(
    @TypedBody()
    body: IErpHrmTimeTrackingReportOutputMetric.ICreate,
  ): Promise<IErpHrmTimeTrackingReportOutputMetric> {
    try {
      return await postErpHrmTimeTrackingReportOutputMetrics({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
