import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IPageIEconomicDiscussionAdministratorRequest } from "../../../../../structures/IPageIEconomicDiscussionAdministratorRequest";

/**
 * Retrieve a paginated list of all pending administrator promotion requests submitted by citizens.
 *
 * This operation enables super administrators to review and act upon administrator promotion requests. The system collects request submissions from citizens through a formal application process, and this endpoint exposes those pending requests for administrative review.
 *
 * Relevant database table: economic_discussion_administrator_requests. This table stores all administrator requests with fields including requester_id, reason, created_at, and status. The status field determines whether a request is pending, approved, or rejected. This endpoint filters for only those records where status is "pending".
 *
 * Security: This operation is restricted to super administrators only. Ordinary administrators and citizen users have no access to this endpoint. Authorization is enforced by the Endpoint agent.
 *
 * This endpoint is used in conjunction with the POST /administrator-requests endpoint (where citizens submit requests) and the PATCH /administrator-requests/{requestId}/approve and PATCH /administrator-requests/{requestId}/reject endpoints (where super administrators act on requests). This endpoint is specifically for the "pending" status views in the administrative dashboard.
 *
 * The operation returns a paginated response with 20 requests per page, sorted by creation time (newest first), and includes relevant details such as the requester's username, request reason, and submission timestamp.
 *
 * The system does not implement soft deletion for administrator requests - requests are permanently marked as approved or rejected when processed.
 *
 * @param props.connection
 * @x-autobe-specification Query economic_discussion_administrator_requests table filtered by status='pending'. Apply pagination with cursor-based strategy for efficiency. Sort by created_at descending (newest first). Limit results to 20 per page. Join with economic_discussion_citizens to retrieve requester username. Cache results for 30 seconds with cache key including page number and sort direction. Return response with pagination metadata and data array.
 * @path /economicDiscussion/superAdministrator/administrator-requests/pending
 * @accessor api.functional.economicDiscussion.superAdministrator.administrator_requests.pending.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(connection: IConnection): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
      );
}
export namespace index {
  export type Response = IPageIEconomicDiscussionAdministratorRequest;

  export const METADATA = {
    method: "GET",
    path: "/economicDiscussion/superAdministrator/administrator-requests/pending",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () =>
    "/economicDiscussion/superAdministrator/administrator-requests/pending";
  export const random = (): IPageIEconomicDiscussionAdministratorRequest =>
    typia.random<IPageIEconomicDiscussionAdministratorRequest>();
  export const simulate = (_connection: IConnection): Response => {
    return random();
  };
}
