import { tags } from "typia";

/**
 * A notification record informing a member about relevant events such as
 * comment replies, mentions, and moderation actions. Each notification
 * represents a discrete event requiring user awareness and support independent
 * user workflows including browsing, marking as read, and deletion.
 *
 * Notifications can be triggered by various events: when another member replies
 * to a user's comment, when a user is mentioned in a comment, when a moderator
 * removes a user's article, or when a user's comment is removed by a
 * moderator.
 *
 * Each notification contains context about what triggered it
 * (triggering_article_id, triggering_comment_id, source_member_id) to enable
 * users to quickly navigate to the related content. The notification_type field
 * categorizes the event for filtering and display. Users can interact with
 * notifications by marking them as read/unread or soft-deleting them from their
 * inbox (setting deleted_at timestamp).
 *
 * Notifications also support email delivery tracking with email_sent_at,
 * email_failed_at, and email_send_error fields for monitoring notification
 * delivery to user email addresses.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardNotification = {
  /**
   * Unique identifier for the notification record. System-generated UUID used
   * to identify and reference this specific notification throughout the
   * platform.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Reference to the member who is the recipient of this notification. The
   * authenticated member who should receive and view this notification about
   * the triggering event.
   */
  recipient_member_id: string & tags.Format<"uuid">;

  /**
   * Optional reference to the article that triggered this notification if
   * applicable. Present when notification is about article comments, article
   * moderation, or other article-related events. NULL if notification is not
   * article-related.
   */
  triggering_article_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Optional reference to the comment that triggered this notification if
   * applicable. Present when notification is about comment replies, comment
   * moderation, or other comment-related events. NULL if notification is not
   * comment-related.
   */
  triggering_comment_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Optional reference to the member who caused or triggered this
   * notification if applicable. The user who commented, mentioned, or
   * triggered the event that generated this notification. NULL if
   * notification was system-generated without a specific source member.
   */
  source_member_id?: (string & tags.Format<"uuid">) | null | undefined;

  /**
   * Type of notification event that triggered this notification. Valid
   * values: 'comment_reply' (someone replied to user's comment), 'mention'
   * (user was mentioned in comment), 'article_moderation' (user's article was
   * moderated/removed), 'comment_moderation' (user's comment was
   * moderated/removed). Categorizes what event triggered this notification
   * for filtering and display purposes.
   */
  notification_type: string;

  /**
   * Short title or subject of the notification for display in notification
   * lists and headers. Examples: 'New reply to your comment', 'Your article
   * was removed', 'You were mentioned'. Kept brief (50-100 characters) for
   * quick scanning by users.
   */
  title: string;

  /**
   * Full notification message body providing detailed context about the
   * event. Includes information about what happened, who it was from (if
   * applicable), and relevant article/comment information. Supports markdown
   * or plain text formatting (typically 200-500 characters).
   */
  message: string;

  /**
   * Whether the user has read or viewed this notification. False indicates
   * unread notification that should be visually highlighted in user's
   * notification inbox. Used for tracking user engagement with notifications
   * and calculating unread notification counts.
   */
  is_read: boolean;

  /**
   * ISO 8601 UTC timestamp when the user read or viewed this notification.
   * NULL if notification has not been read yet (is_read = false). Updated
   * automatically when user marks notification as read. Used for tracking
   * engagement timing and sorting notifications.
   */
  read_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Optional URL or deep link to navigate directly to the related content
   * when notification is clicked. Examples:
   * '/articles/[articleId]#comment-[commentId]' for comment reply
   * notifications or '/articles/[articleId]' for article-related
   * notifications. NULL for notifications without a direct action target.
   */
  action_url?: (string & tags.Format<"uri">) | null | undefined;

  /**
   * ISO 8601 UTC timestamp when this notification was sent via email to the
   * recipient member. NULL if notification has not been emailed yet or if
   * user has email notifications disabled. Used to track which notifications
   * have been delivered via email and for email retry logic.
   */
  email_sent_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * ISO 8601 UTC timestamp when email delivery for this notification failed.
   * NULL if email was sent successfully or notification was not attempted to
   * be sent via email. Used to track failed email deliveries for retry and
   * debugging.
   */
  email_failed_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Error message or reason code if email delivery failed. NULL if email sent
   * successfully or was not attempted. Examples: 'SMTP_TIMEOUT',
   * 'INVALID_ADDRESS', 'BOUNCE'. Enables troubleshooting of email delivery
   * failures and support escalation.
   */
  email_send_error?: string | null | undefined;

  /**
   * Email address of the recipient member at the time of notification
   * creation. Denormalized from member record for efficient email delivery
   * without additional database queries. NULL if member has no email address
   * or email delivery is disabled. Allows sending emails even if member
   * record is subsequently updated.
   */
  recipient_email?: (string & tags.Format<"email">) | null | undefined;

  /**
   * ISO 8601 UTC timestamp when this notification was created and generated.
   * Marks when the triggering event occurred in the system. System-generated
   * and immutable. Used for chronological sorting (newest first) and for
   * notification cleanup policies.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * ISO 8601 UTC timestamp when this notification record was last modified.
   * Updated when notification status changes (marked read, email sent, etc.).
   * Used for audit trail tracking and monitoring notification lifecycle
   * changes.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * ISO 8601 UTC timestamp when this notification was deleted/archived by the
   * user. NULL indicates active notification. Used for soft deletion allowing
   * recovery and maintains audit trail of user actions on notifications.
   * Deleted notifications are hidden from user's notification inbox.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IDiscussionBoardNotification {
  /**
   * Search criteria, filtering options, and pagination parameters for
   * retrieving a filtered list of member notifications.
   *
   * Supports advanced notification filtering including notification type
   * filtering (comment_reply, mention, article_moderation,
   * comment_moderation), read status filtering (read vs unread), and
   * full-text search on title and message fields. Pagination parameters
   * (page, limit) control result set size and offset for handling large
   * notification lists.
   *
   * Used by GET /member/notifications endpoint to retrieve the authenticated
   * member's complete notification history with advanced filtering and
   * sorting capabilities. This DTO enables members to query their
   * notification inbox with sophisticated search workflows.
   */
  export type IRequest = {
    /**
     * Page number for pagination (1-indexed). Defaults to 1 if not
     * specified. Used to control which set of notifications are returned
     * when results exceed page size.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of notifications to return per page. Maximum 100 to prevent
     * excessive data transfer. Defaults to 20 if not specified. Controls
     * the page size for notification list retrieval.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Optional filter to return only notifications of a specific type.
     * Valid values: 'comment_reply', 'mention', 'article_moderation',
     * 'comment_moderation'. NULL or omitted means return all notification
     * types.
     */
    notification_type?: string | null | undefined;

    /**
     * Optional filter to return only notifications with specific read
     * status. True returns only read notifications, False returns only
     * unread notifications. NULL or omitted means return both read and
     * unread notifications.
     */
    is_read?: boolean | null | undefined;

    /**
     * Optional full-text search query to find notifications by title or
     * message content. Uses trigram indexes for efficient matching. NULL or
     * omitted means no search filtering. Searches across title and message
     * fields with relevance ranking.
     */
    search?: string | null | undefined;

    /**
     * Field to sort notifications by. Valid values: 'created_at'
     * (notification creation time, newest first), 'read_at' (when
     * notification was read, most recent reads first), 'updated_at' (last
     * modification time, newest first). Defaults to 'created_at' if not
     * specified.
     */
    sort_by?: "created_at" | "read_at" | "updated_at" | undefined;
  };

  /**
   * Update DTO for modifying notification state. Allows authenticated members
   * to mark notifications as read/unread or soft-delete notifications from
   * their inbox.
   *
   * Supported operations:
   *
   * - Mark as read: Set is_read to true to mark notification as read, which
   *   populates read_at with current timestamp
   * - Mark as unread: Set is_read to false to mark notification as unread,
   *   which clears read_at
   * - Delete (soft): Set deleted_at to current timestamp to hide notification
   *   from inbox
   * - Restore (undelete): Set deleted_at to null if notification was previously
   *   deleted
   *
   * Ownership verification is enforced at the operation level - authenticated
   * users can only update notifications belonging to their own account (where
   * recipient_member_id matches their user ID).
   */
  export type IUpdate = {
    /**
     * Whether the notification has been read by the user. Set to true to
     * mark notification as read (populates read_at), set to false to mark
     * as unread (clears read_at). Used by users to track which
     * notifications they have reviewed.
     */
    is_read?: boolean | undefined;

    /**
     * ISO 8601 UTC timestamp to soft-delete the notification from user's
     * inbox. Set to current timestamp to delete notification (hide from
     * user), set to null to restore/undelete a previously deleted
     * notification. Supports soft deletion allowing recovery.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
