import { Module } from "@nestjs/common";

import { EconomicpoliticaldiscussionboardAdminAdminRequestsController } from "./controllers/economicPoliticalDiscussionBoard/admin/admin/requests/EconomicpoliticaldiscussionboardAdminAdminRequestsController";
import { EconomicpoliticaldiscussionboardAdminAdminsController } from "./controllers/economicPoliticalDiscussionBoard/admin/admins/EconomicpoliticaldiscussionboardAdminAdminsController";
import { EconomicpoliticaldiscussionboardAdminArticlesController } from "./controllers/economicPoliticalDiscussionBoard/admin/articles/EconomicpoliticaldiscussionboardAdminArticlesController";
import { EconomicpoliticaldiscussionboardAdminBansController } from "./controllers/economicPoliticalDiscussionBoard/admin/bans/EconomicpoliticaldiscussionboardAdminBansController";
import { EconomicpoliticaldiscussionboardAdminRequestsController } from "./controllers/economicPoliticalDiscussionBoard/admin/requests/EconomicpoliticaldiscussionboardAdminRequestsController";
import { EconomicpoliticaldiscussionboardAdminSectionsController } from "./controllers/economicPoliticalDiscussionBoard/admin/sections/EconomicpoliticaldiscussionboardAdminSectionsController";
import { EconomicpoliticaldiscussionboardAdminTagsController } from "./controllers/economicPoliticalDiscussionBoard/admin/tags/EconomicpoliticaldiscussionboardAdminTagsController";
import { EconomicpoliticaldiscussionboardAdminUsersController } from "./controllers/economicPoliticalDiscussionBoard/admin/users/EconomicpoliticaldiscussionboardAdminUsersController";
import { EconomicpoliticaldiscussionboardArticlesController } from "./controllers/economicPoliticalDiscussionBoard/articles/EconomicpoliticaldiscussionboardArticlesController";
import { EconomicpoliticaldiscussionboardArticlesAttachmentsController } from "./controllers/economicPoliticalDiscussionBoard/articles/attachments/EconomicpoliticaldiscussionboardArticlesAttachmentsController";
import { EconomicpoliticaldiscussionboardArticlesCommentsController } from "./controllers/economicPoliticalDiscussionBoard/articles/comments/EconomicpoliticaldiscussionboardArticlesCommentsController";
import { EconomicpoliticaldiscussionboardAuthAdminController } from "./controllers/economicPoliticalDiscussionBoard/auth/admin/EconomicpoliticaldiscussionboardAuthAdminController";
import { EconomicpoliticaldiscussionboardAuthGuestController } from "./controllers/economicPoliticalDiscussionBoard/auth/guest/EconomicpoliticaldiscussionboardAuthGuestController";
import { EconomicpoliticaldiscussionboardAuthUserController } from "./controllers/economicPoliticalDiscussionBoard/auth/user/EconomicpoliticaldiscussionboardAuthUserController";
import { EconomicpoliticaldiscussionboardSectionsController } from "./controllers/economicPoliticalDiscussionBoard/sections/EconomicpoliticaldiscussionboardSectionsController";
import { EconomicpoliticaldiscussionboardTagsController } from "./controllers/economicPoliticalDiscussionBoard/tags/EconomicpoliticaldiscussionboardTagsController";
import { EconomicpoliticaldiscussionboardUserArticlesController } from "./controllers/economicPoliticalDiscussionBoard/user/articles/EconomicpoliticaldiscussionboardUserArticlesController";
import { EconomicpoliticaldiscussionboardUserArticlesAttachmentsController } from "./controllers/economicPoliticalDiscussionBoard/user/articles/attachments/EconomicpoliticaldiscussionboardUserArticlesAttachmentsController";
import { EconomicpoliticaldiscussionboardUserArticlesCommentsController } from "./controllers/economicPoliticalDiscussionBoard/user/articles/comments/EconomicpoliticaldiscussionboardUserArticlesCommentsController";
import { EconomicpoliticaldiscussionboardUserEmail_verificationsController } from "./controllers/economicPoliticalDiscussionBoard/user/email-verifications/EconomicpoliticaldiscussionboardUserEmail_verificationsController";
import { EconomicpoliticaldiscussionboardUserPassword_resetsController } from "./controllers/economicPoliticalDiscussionBoard/user/password-resets/EconomicpoliticaldiscussionboardUserPassword_resetsController";
import { EconomicpoliticaldiscussionboardUserProfileController } from "./controllers/economicPoliticalDiscussionBoard/user/profile/EconomicpoliticaldiscussionboardUserProfileController";
import { EconomicpoliticaldiscussionboardUserRequestsController } from "./controllers/economicPoliticalDiscussionBoard/user/requests/EconomicpoliticaldiscussionboardUserRequestsController";
import { EconomicpoliticaldiscussionboardUserSessionsController } from "./controllers/economicPoliticalDiscussionBoard/user/sessions/EconomicpoliticaldiscussionboardUserSessionsController";
import { EconomicpoliticaldiscussionboardUsersController } from "./controllers/economicPoliticalDiscussionBoard/users/EconomicpoliticaldiscussionboardUsersController";

@Module({
  controllers: [
    EconomicpoliticaldiscussionboardAuthGuestController,
    EconomicpoliticaldiscussionboardAuthUserController,
    EconomicpoliticaldiscussionboardAuthAdminController,
    EconomicpoliticaldiscussionboardUserSessionsController,
    EconomicpoliticaldiscussionboardUserPassword_resetsController,
    EconomicpoliticaldiscussionboardUserEmail_verificationsController,
    EconomicpoliticaldiscussionboardAdminUsersController,
    EconomicpoliticaldiscussionboardUsersController,
    EconomicpoliticaldiscussionboardUserProfileController,
    EconomicpoliticaldiscussionboardAdminAdminsController,
    EconomicpoliticaldiscussionboardSectionsController,
    EconomicpoliticaldiscussionboardAdminSectionsController,
    EconomicpoliticaldiscussionboardArticlesController,
    EconomicpoliticaldiscussionboardUserArticlesController,
    EconomicpoliticaldiscussionboardAdminArticlesController,
    EconomicpoliticaldiscussionboardTagsController,
    EconomicpoliticaldiscussionboardAdminTagsController,
    EconomicpoliticaldiscussionboardArticlesAttachmentsController,
    EconomicpoliticaldiscussionboardUserArticlesAttachmentsController,
    EconomicpoliticaldiscussionboardArticlesCommentsController,
    EconomicpoliticaldiscussionboardUserArticlesCommentsController,
    EconomicpoliticaldiscussionboardAdminAdminRequestsController,
    EconomicpoliticaldiscussionboardAdminRequestsController,
    EconomicpoliticaldiscussionboardUserRequestsController,
    EconomicpoliticaldiscussionboardAdminBansController,
  ],
})
export class MyModule {}
