import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallFraudRuleViolation } from "../../../../../structures/IShoppingMallFraudRuleViolation";
import { IPageIShoppingMallFraudRuleViolation } from "../../../../../structures/IPageIShoppingMallFraudRuleViolation";

/**
 * Search and retrieve a paginated list of fraud rule violations from the
 * shopping_mall_fraud_rule_violations table.
 *
 * Retrieve a filtered and paginated list of fraud rule violations recorded in
 * the shoppingMall platform for risk analysis and monitoring.
 *
 * This operation focuses on the `shopping_mall_fraud_rule_violations` table,
 * which stores recorded violations or hits of configured fraud and risk rules
 * evaluated against various entities, including orders, payment transactions,
 * accounts, and possibly sessions. Each row in this table typically includes
 * references to the violated fraud rule (from
 * `shopping_mall_fraud_rule_definitions`), the target object (such as an order
 * or payment transaction), timestamps, severity classification, and outcome
 * metadata that indicates how the platform reacted to the violation.
 *
 * The endpoint is read-only and intended for use by security, risk, and
 * operations staff. As fraud and risk data is highly sensitive, access must be
 * restricted to privileged administrative actors. The `authorizationActor` and
 * `authorizationActors` settings therefore limit usage to the `platformAdmin`
 * role, and the underlying implementation should further enforce fine-grained
 * authorization, auditing of access, and rate limiting to avoid mass extraction
 * of sensitive fraud models.
 *
 * The request body type `IShoppingMallFraudRuleViolation.IRequest` supports
 * multiple filter dimensions, such as date/time ranges, rule codes or rule IDs,
 * affected actor types (customer, seller, platform), severity bands, status or
 * disposition (e.g., open, underReview, resolved), and optional free-text
 * search across any descriptive fields captured with the violation. It also
 * defines standard pagination and sorting properties, for example by violation
 * timestamp, severity, or rule priority. The design ensures that no path
 * parameters are duplicated in the body and that the body only carries
 * analytical criteria.
 *
 * The response body uses `IPageIShoppingMallFraudRuleViolation.ISummary` to
 * deliver a paginated collection of violation summaries, each containing the
 * core attributes required for list and dashboard views. Typical fields in the
 * summary might include violation identifier, rule code, brief rule
 * description, impacted entity references (order number, transaction reference,
 * or account identifier), violation time, severity, and disposition.
 * Implementations are expected to handle edge cases such as empty result sets,
 * large time windows, and invalid filter combinations by returning appropriate
 * error responses or validation messages according to the platform’s general
 * error-handling guidelines. Related operations would include detail retrieval
 * for a single violation or for associated orders and payments, but those are
 * not part of this specific endpoint.
 *
 * @param props.connection
 * @param props.body Search criteria, filters, and pagination options for
 *   querying fraud rule violations.
 * @path /shoppingMall/platformAdmin/analytics/fraudViolations
 * @accessor api.functional.shoppingMall.platformAdmin.analytics.fraudViolations.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria, filters, and pagination options for querying fraud
     * rule violations.
     */
    body: IShoppingMallFraudRuleViolation.IRequest;
  };
  export type Body = IShoppingMallFraudRuleViolation.IRequest;
  export type Response = IPageIShoppingMallFraudRuleViolation.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/platformAdmin/analytics/fraudViolations",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () =>
    "/shoppingMall/platformAdmin/analytics/fraudViolations";
  export const random = (): IPageIShoppingMallFraudRuleViolation.ISummary =>
    typia.random<IPageIShoppingMallFraudRuleViolation.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
