import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommercePlatformCategory } from "../../../../structures/IEcommercePlatformCategory";

/**
 * Create a new product category with a name and description. Administrators can create both top-level categories and subcategories with one level of nesting. The category name must be unique within the same parent scope, and the description must be non-empty. Subcategories can only be created under top-level categories.
 *
 * @param props.connection
 * @param props.body Category creation payload including required name and description fields, and optional parent category identifier for subcategory creation.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification 1. Validate the authenticated user has administrator
 *   privileges; reject non-admin requests.
 *
 * 2. Validate name is present and not empty/whitespace-only.
 *
 * 3. Validate description is present and not empty/whitespace-only.
 *
 * 4. If parentEcommercePlatformCategoryId is provided:
 *    - Verify the parent category exists and is active (deleted_at is null)
 *    - Verify the parent category is a root category (its parent_ecommerce_platform_category_id is null)
 *    - If parent is a subcategory, reject with error: nesting limit exceeded
 *
 * 5. Validate name uniqueness within same parent scope:
 *    - Check no existing active category has the same name with the same parent_ecommerce_platform_category_id
 *    - Exclude soft-deleted categories (deleted_at is not null) from uniqueness check
 *    - Reject if duplicate found
 *
 * 6. Insert new record into ecommerce_platform_categories:
 *    - id: auto-generated UUID
 *    - name: from request
 *    - description: from request
 *    - parent_ecommerce_platform_category_id: from request (null if root category)
 *    - created_at: current timestamp
 *    - updated_at: current timestamp
 *    - deleted_at: null
 *
 * 7. Return the complete created category record.
 * @path /ecommercePlatform/admin/categories
 * @accessor api.functional.ecommercePlatform.admin.categories.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Category creation payload including required name and description fields, and optional parent category identifier for subcategory creation.
     */
    body: IEcommercePlatformCategory.ICreate;
  };
  export type Body = IEcommercePlatformCategory.ICreate;
  export type Response = IEcommercePlatformCategory;

  export const METADATA = {
    method: "POST",
    path: "/ecommercePlatform/admin/categories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/ecommercePlatform/admin/categories";
  export const random = (): IEcommercePlatformCategory =>
    typia.random<IEcommercePlatformCategory>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing category's name and description.
 *
 * This endpoint allows administrators to modify category details. Category names must remain unique within the same parent category scope. Both name and description fields must be non-empty when provided. The one-level nesting hierarchy constraint is enforced—subcategories cannot have their own subcategories.
 *
 * Administrators only have permission to edit categories. Requests from customers or sellers will be rejected with an authorization error. If the specified category does not exist or has been soft-deleted, a 404 error is returned.
 *
 * @param props.connection
 * @param props.categoryId UUID identifier of the category to update (global scope)
 * @param props.body Updated category details including name and description fields. Both fields are optional; only provided fields will be updated.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query ecommerce_platform_categories table by id to
 *   retrieve the existing category.
 *
 * Validate that the category exists and is not soft-deleted (deleted_at IS NULL).
 *
 * Apply the update:
 * - Optional name field: validate non-empty string, trim whitespace. Enforce unique constraint by checking @@unique([name, parent_ecommerce_platform_category_id]) does not conflict with another category under the same parent.
 * - Optional description field: validate non-empty string.
 * - Updated category name or description must differ from current values or return success with unchanged data.
 *
 * Update the record with provided fields and set updated_at to current timestamp.
 *
 * Return the updated category entity including id, name, description, parent reference, created_at, updated_at, and deleted_at fields.
 *
 * Edge cases:
 * - Return 404 if category id not found or deleted_at is not null
 * - Return 409 if the proposed name already exists as a sibling under the same parent
 * - Return 400 if name or description is blank/whitespace-only when provided
 * - Authorization middleware must enforce admin-only access
 * @path /ecommercePlatform/admin/categories/:categoryId
 * @accessor api.functional.ecommercePlatform.admin.categories.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * UUID identifier of the category to update (global scope)
     */
    categoryId: string & tags.Format<"uuid">;

    /**
     * Updated category details including name and description fields. Both fields are optional; only provided fields will be updated.
     */
    body: IEcommercePlatformCategory.IUpdate;
  };
  export type Body = IEcommercePlatformCategory.IUpdate;
  export type Response = IEcommercePlatformCategory;

  export const METADATA = {
    method: "PUT",
    path: "/ecommercePlatform/admin/categories/:categoryId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/ecommercePlatform/admin/categories/${encodeURIComponent(props.categoryId ?? "null")}`;
  export const random = (): IEcommercePlatformCategory =>
    typia.random<IEcommercePlatformCategory>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Soft deletes a specified category from the platform.
 *
 * When a category is deleted, it is removed from customer browsing lists and search filters, ensuring deleted items do not appear in dropdown selectors or filter options. If the deleted category is a root category, all associated subcategories are also soft-deleted. Products previously linked to the deleted category or its subcategories are dissociated, rendering them uncategorized while preserving all product data. Only platform administrators possess the authority to perform this operation.
 *
 * @param props.connection
 * @param props.categoryId The unique identifier of the category to delete.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query the `ecommerce_platform_categories` table by
 *   `{categoryId}`. Validate that the requesting actor possesses administrative
 *   privileges. If valid, update the target category record by setting the
 *   `deleted_at` timestamp to the current time. If the category is a root
 *   category (`parent_ecommerce_platform_category_id` is NULL), execute a
 *   cascading soft delete on all directly linked subcategories by setting their
 *   `deleted_at` timestamps. For all products associated with either the target
 *   category or its cascaded subcategories, update the product records to
 *   dissociate them from any category assignment, transitioning them to an
 *   uncategorized state. Ensure the deleted category and its subcategories are
 *   excluded from all subsequent customer browsing and filtering queries.
 * @path /ecommercePlatform/admin/categories/:categoryId
 * @accessor api.functional.ecommercePlatform.admin.categories.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * The unique identifier of the category to delete.
     */
    categoryId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/ecommercePlatform/admin/categories/:categoryId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommercePlatform/admin/categories/${encodeURIComponent(props.categoryId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
