import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IHrmPlatformTaskHistory } from "../../../../../structures/IHrmPlatformTaskHistory";
import { IPageIHrmPlatformTaskHistory } from "../../../../../structures/IPageIHrmPlatformTaskHistory";

/**
 * Retrieve the complete audit history of a task, showing all status changes and modifications.
 *
 * Returns a paginated list of history entries for the specified task. Each entry records when a change occurred, what type of change it was, the previous and new values, and which user made the change.
 *
 * History entries are automatically created by the system whenever a task is modified. Users with view permission for the task can view its complete history, regardless of when the changes occurred.
 *
 * @param props.connection
 * @param props.taskId UUID of the task to retrieve history for.
 * @param props.body Pagination and filtering criteria for task history list.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query hrm_platform_task_histories table for all
 *   entries where task_id matches the path parameter.
 *
 * 1. Validate taskId is a valid UUID format
 * 2. Verify the task exists and is not soft-deleted (deleted_at IS NULL)
 * 3. Check user has permission to view the task (either assigned to task or has project management permission)
 * 4. Query history entries with task_id = {taskId}, ordered by changed_at DESC
 * 5. Apply pagination from requestBody: limit, offset, sort by changed_at
 * 6. Only include non-deleted history entries (deleted_at IS NULL)
 * 7. Return paginated results with total count and pagination metadata
 *
 * Edge cases:
 * - Task not found: return 404 Not Found
 * - User lacks permission: return 403 Forbidden
 * - Task has no history: return empty paginated list with total_count: 0 (not error)
 * - History entry cannot be created during status change: rollback status change (atomic operation)
 * - System error retrieving history: return 500 Internal Server Error
 * @path /hrmPlatform/member/tasks/:taskId/histories
 * @accessor api.functional.hrmPlatform.member.tasks.histories.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * UUID of the task to retrieve history for.
     */
    taskId: string & tags.Format<"uuid">;

    /**
     * Pagination and filtering criteria for task history list.
     */
    body: IHrmPlatformTaskHistory.IRequest;
  };
  export type Body = IHrmPlatformTaskHistory.IRequest;
  export type Response = IPageIHrmPlatformTaskHistory.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/hrmPlatform/member/tasks/:taskId/histories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/hrmPlatform/member/tasks/${encodeURIComponent(props.taskId ?? "null")}/histories`;
  export const random = (): IPageIHrmPlatformTaskHistory.ISummary =>
    typia.random<IPageIHrmPlatformTaskHistory.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("taskId")(() => typia.assert(props.taskId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
