import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IHrmPlatformTimesheetWeeklyStat } from "../../../../../structures/IHrmPlatformTimesheetWeeklyStat";

/**
 * Retrieve the total hours logged by the employee for the current week (Monday to Sunday).
 *
 * This endpoint provides the weekly hours summary that appears on the personal dashboard, showing the sum of all timelogs with dates falling within the current week's date range. The week calculation follows the standard Monday-to-Sunday pattern used across the timesheet system.
 *
 * Employees can use this metric to monitor their weekly time accumulation and ensure they are meeting their expected working hours. The data is pre-aggregated in the timesheet_weekly_stats table for efficient dashboard performance.
 *
 * @param props.connection
 * @param props.employeeId The unique identifier of the employee whose weekly hours are being retrieved.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Retrieve the current week's total hours logged by the employee from hrm_platform_timesheet_weekly_stats.
 *
 * Implementation steps:
 * 1. Extract the employeeId from the authenticated user's context (from organization-scoped session) or use the path parameter
 * 2. Calculate the current week period: find the Monday (week_start) and Sunday (week_end) for the current week based on the employee's organization timezone
 * 3. Query hrm_platform_timesheet_weekly_stats for the record matching employee_id and week_start for the current week
 * 4. Return the total_hours field from the weekly statistics record
 * 5. If no record exists (employee hasn't logged time yet), return 0.0 hours
 *
 * Business rules:
 * - The week period calculation must align with the timesheet week definition (Monday to Sunday)
 * - Only active timelogs (deleted_at is null) are included in the aggregation
 * - The operation is read-only and does not modify any data
 * - Return 404 if the employee_id is not found or not a valid member of the organization
 * @path /hrmPlatform/member/timetracking/weekly-hours/:employeeId
 * @accessor api.functional.hrmPlatform.member.timetracking.weekly_hours.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The unique identifier of the employee whose weekly hours are being retrieved.
     */
    employeeId: string & tags.Format<"uuid">;
  };
  export type Response = IHrmPlatformTimesheetWeeklyStat.ISummary;

  export const METADATA = {
    method: "GET",
    path: "/hrmPlatform/member/timetracking/weekly-hours/:employeeId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrmPlatform/member/timetracking/weekly-hours/${encodeURIComponent(props.employeeId ?? "null")}`;
  export const random = (): IHrmPlatformTimesheetWeeklyStat.ISummary =>
    typia.random<IHrmPlatformTimesheetWeeklyStat.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("employeeId")(() => typia.assert(props.employeeId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
