import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IRedditCommunityModerationActionOfPost } from "../../../../structures/IRedditCommunityModerationActionOfPost";

/**
 * Create a new moderation action to enforce community rules.
 *
 * This endpoint allows authenticated moderators or administrators to take disciplinary actions against content or users, including deletion of posts/comments, banning users, approving reports, or dismissing false reports. All actions are logged auditably, including the actor identity, target type (post or comment), specific action taken, and reason.
 *
 * This system ensures accountability: every action taken by a moderator is permanently recorded and traceable back to the actor.
 *
 * All moderation actions are permanent, immutable audit entries and cannot be deleted, edited, or overridden after creation. This operation does NOT return a response body. Success is signaled by HTTP 201 Created. The generated moderation_action_id can be used to fetch audit details via GET /moderation-actions/{id}.
 *
 * Important: This feature is only accessible to authorized actor types (community moderator, community owner, or platform admin). Guests and regular members cannot access this endpoint.
 *
 * @param props.connection
 * @param props.body Details of the moderation action to perform.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor communityOwner
 * @x-autobe-specification Create a new moderation action in reddit_community_moderation_actions. Validate that actor_id corresponds to an active moderator or admin session. Verify that target_type is either 'post' or 'comment'. Validate that action_type is one of: 'delete', 'ban', 'approve', 'dismiss'. For target_type = 'post', insert record and link via reddit_community_moderation_action_of_posts using generated moderation_action_id. For target_type = 'comment', insert record and link via reddit_community_moderation_action_of_comments using generated moderation_action_id. Ensure reason is UTF-8 string ≤ 500 characters. Log timestamp as current system time. Return 201 Created with empty body. Do not allow creation if actor lacks permission (must be admin or moderator of target community).
 * @path /redditCommunity/communityOwner/moderation-actions
 * @accessor api.functional.redditCommunity.communityOwner.moderation_actions.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<void> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Details of the moderation action to perform.
     */
    body: IRedditCommunityModerationActionOfPost.ICreate;
  };
  export type Body = IRedditCommunityModerationActionOfPost.ICreate;

  export const METADATA = {
    method: "POST",
    path: "/redditCommunity/communityOwner/moderation-actions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () =>
    "/redditCommunity/communityOwner/moderation-actions";
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
