name: build
on:
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - name: Install Backend-Server
        run: pnpm install

      - name: Build Swagger
        run: pnpm run build:swagger

      - name: Build SDK
        run: pnpm run build:sdk

      - name: Compile Backend-Server
        run: pnpm run build

      - name: Run Test Program
        run: pnpm run test -- --reset true --simultaneous 16

      - name: EsLint
        run: pnpm run eslint
