import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IProjectAnalytic } from "../../../../../structures/IProjectAnalytic";

/**
 * Retrieve comprehensive analytics and aggregated statistics for a specific project.
 *
 * This endpoint provides a snapshot of project health and progress by aggregating data from timelogs and tasks. The response includes total hours logged, budget utilization percentage, task status distribution, and member activity metrics.
 *
 * Data sources include:
 * - Timelogs: Sum of duration_minutes grouped by billable/non-billable
 * - Tasks: Count and distribution across status values (TODO, IN_PROGRESS, IN_REVIEW, DONE)
 * - Budget: Comparison of logged hours against budget_hours (if set)
 * - Members: Count of employees with timelogs or task assignments on the project
 *
 * The analytics are computed at query time to reflect real-time project state.
 *
 * @param props.connection
 * @param props.projectId UUID identifier of the project to retrieve analytics for.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification 1. Fetch project from hrm_platform_projects table by
 *   UUID (projectId). 2. Verify project exists and is not soft-deleted
 *   (deleted_at IS NULL). 3. Compute timelog aggregations: - Total duration:
 *   SUM(duration_minutes) WHERE project_id = projectId AND deleted_at IS NULL -
 *   Billable duration: SUM(duration_minutes) WHERE project_id = projectId AND
 *   billable = true AND deleted_at IS NULL - Non-billable duration:
 *   SUM(duration_minutes) WHERE project_id = projectId AND billable = false AND
 *   deleted_at IS NULL 4. Compute task aggregations: - Task counts by status:
 *   COUNT(*) GROUP BY status WHERE project_id = projectId AND deleted_at IS
 *   NULL 5. Compute budget utilization: - If budget_hours IS NOT NULL:
 *   utilization = (total_duration_minutes / 60) / budget_hours * 100 - If
 *   budget_hours IS NULL: utilization = NULL 6. Compute member activity: -
 *   Count distinct employees with timelogs OR task assignments in the project
 *   7. Return aggregated analytics object.
 * @path /hrmPlatform/member/projects/:projectId/analytics
 * @accessor api.functional.hrmPlatform.member.projects.analytics.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * UUID identifier of the project to retrieve analytics for.
     */
    projectId: string & tags.Format<"uuid">;
  };
  export type Response = IProjectAnalytic;

  export const METADATA = {
    method: "GET",
    path: "/hrmPlatform/member/projects/:projectId/analytics",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrmPlatform/member/projects/${encodeURIComponent(props.projectId ?? "null")}/analytics`;
  export const random = (): IProjectAnalytic =>
    typia.random<IProjectAnalytic>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("projectId")(() => typia.assert(props.projectId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
