import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IPageIShoppingMallCartItem } from "../../../../structures/IPageIShoppingMallCartItem";
import { IShoppingMallCartItem } from "../../../../structures/IShoppingMallCartItem";

/**
 * Add a product variant to the authenticated customer's shopping cart.
 *
 * This operation allows authenticated customers to add specific product variants (SKUs) to their shopping cart with a desired quantity. The cart stores the variant reference and quantity, along with the unit price at the time of addition for price change detection during checkout.
 *
 * When the same variant is added multiple times, the system automatically combines the quantities into a single cart item instead of creating duplicates. The total quantity is capped at 99 units per variant.
 *
 * **Business Rules:**
 * - Customer must be authenticated (JWT token required)
 * - Variant must exist and not be deleted
 * - Product must exist and not be deleted
 * - Product's seller must not be suspended
 * - Quantity must be between 1 and 99
 * - If variant already in cart, quantities are combined
 *
 * **Stock Validation:**
 * Stock is not validated at add time. Customers can add items even if stock is insufficient. Stock warnings are displayed during cart viewing and checkout validation.
 *
 * @param props.connection
 * @param props.body Cart item creation data including the variant to add and quantity
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Implementation steps:
 *
 * 1. Extract authenticated customer ID from JWT token
 * 2. Validate request body: variantId (valid UUID), quantity (integer 1-99)
 * 3. Query shopping_mall_product_variants to verify variant exists and is not deleted (deleted_at IS NULL)
 * 4. Query shopping_mall_products to verify product exists, is not deleted, and seller is not suspended
 * 5. Get variant price: use variant.price if set, otherwise product.base_price
 * 6. Check if cart item already exists for this customer+variant combination (unique constraint)
 * 7. If exists:
 *    - Add new quantity to existing quantity
 *    - Cap total at 99 if exceeds maximum
 *    - Update updated_at timestamp
 *    - Keep existing unit_price (original price when first added)
 * 8. If not exists:
 *    - Create new cart item with customer_id, variant_id, quantity, unit_price
 *    - Set created_at and updated_at to current timestamp
 * 9. Return the created/updated cart item with variant and product details
 *
 * **Database Operations:**
 * - SELECT shopping_mall_product_variants WHERE id = variantId AND deleted_at IS NULL
 * - SELECT shopping_mall_products WHERE id = variant.product_id AND deleted_at IS NULL
 * - SELECT shopping_mall_sellers WHERE id = product.seller_id
 * - SELECT/UPDATE/INSERT shopping_mall_cart_items
 *
 * **Error Responses:**
 * - 401 Unauthorized: Invalid or missing JWT token
 * - 400 Bad Request: Invalid variantId format or quantity out of range
 * - 404 Not Found: Variant does not exist or is deleted
 * - 400 Bad Request: Product deleted or seller suspended
 * @path /shoppingMall/customer/cart
 * @accessor api.functional.shoppingMall.customer.cart.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Cart item creation data including the variant to add and quantity
     */
    body: IShoppingMallCartItem.ICreate;
  };
  export type Body = IShoppingMallCartItem.ICreate;
  export type Response = IShoppingMallCartItem;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/customer/cart",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/cart";
  export const random = (): IShoppingMallCartItem =>
    typia.random<IShoppingMallCartItem>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a paginated list of cart items for the authenticated customer with comprehensive search, filter, and sorting capabilities.
 *
 * This operation provides customers with full visibility into their shopping cart contents, including detailed product and variant information, current pricing, stock availability status, and calculated subtotals. Each cart item represents a specific product variant (SKU) with its quantity and the unit price at the time of addition.
 *
 * The cart display supports multiple availability status indicators: items with sufficient stock are marked as 'In Stock', items with limited stock show 'Only X available', out-of-stock items display 'Out of Stock', and deleted or unavailable items show appropriate unavailable status. These status indicators help customers make informed decisions before proceeding to checkout.
 *
 * Cart items are linked to shopping_mall_product_variants table via shopping_product_variant_id, and each belongs to a specific customer via shopping_customer_id. The unit_price field captures the variant's price at addition time, enabling price change detection during checkout.
 *
 * Maximum constraints: 50 distinct variants per cart and 99 units per item. When viewing cart, customers can search by product name, filter by stock status or price range, and sort by date added, price, or quantity.
 *
 * @param props.connection
 * @param props.body Search criteria including search terms, stock status filters, price range filters, pagination parameters, and sorting options
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query shopping_mall_cart_items table for the authenticated customer with pagination and filtering.
 *
 * Service layer implementation:
 * 1. Extract customer ID from JWT authentication token
 * 2. Query cart_items where shopping_customer_id matches the authenticated customer
 * 3. Join with shopping_mall_product_variants to get variant details
 * 4. Join with shopping_mall_products to get product name and base_price
 * 5. Join with shopping_mall_sellers to get shop information
 * 6. Calculate current stock by summing inventory history records for each variant
 * 7. Determine availability status for each cart item based on stock level vs requested quantity
 * 8. Apply search filters (product name contains, stock status, price range)
 * 9. Apply sorting (created_at, unit_price, quantity)
 * 10. Implement cursor-based pagination for consistent results
 * 11. Calculate line totals (unit_price * quantity) and cart grand total
 * 12. Return paginated results with stock warnings for insufficient availability
 *
 * Edge cases:
 * - Empty cart returns empty data array with zero pagination
 * - Deleted variants are flagged as unavailable with appropriate status
 * - Products from suspended sellers show 'Temporarily Unavailable' status
 * - Price changes since addition are detected by comparing stored unit_price with current variant price
 * @path /shoppingMall/customer/cart
 * @accessor api.functional.shoppingMall.customer.cart.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria including search terms, stock status filters, price range filters, pagination parameters, and sorting options
     */
    body: IShoppingMallCartItem.IRequest;
  };
  export type Body = IShoppingMallCartItem.IRequest;
  export type Response = IPageIShoppingMallCartItem.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/customer/cart",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/cart";
  export const random = (): IPageIShoppingMallCartItem.ISummary =>
    typia.random<IPageIShoppingMallCartItem.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update the quantity of a specific item in the customer's shopping cart.
 *
 * This operation allows authenticated customers to modify the quantity of a product variant already in their cart. The quantity must be between 1 and 99 units per item. If the customer has multiple of the same variant, they are already combined into a single cart item with aggregated quantity.
 *
 * **Security and Authorization:**
 * Only the customer who owns the cart item can update it. The operation verifies that the cartItemId belongs to the authenticated customer before performing the update. Attempting to update another customer's cart item returns a 404 Not Found error to prevent information disclosure.
 *
 * **Quantity Validation:**
 * - Minimum quantity: 1 unit
 * - Maximum quantity: 99 units per item
 * - Quantities outside this range return a validation error
 *
 * **Business Logic:**
 * When the quantity is updated, the updated_at timestamp is automatically refreshed. The unit_price remains unchanged from when the item was originally added to the cart. This enables price change detection during checkout.
 *
 * **Unavailable Items:**
 * Even if the associated product variant has been deleted or is out of stock, the cart item can still be updated. Such items are marked as unavailable during cart retrieval operations, but the update operation itself succeeds. This allows customers to adjust quantities before deciding whether to proceed with checkout or remove unavailable items.
 *
 * **Related Operations:**
 * - GET /cart - View the complete cart with all items and availability status
 * - POST /cart - Add a new variant to the cart
 * - DELETE /cart/{cartItemId} - Remove an item from the cart
 *
 * @param props.connection
 * @param props.cartItemId Unique identifier of the cart item to update. Must belong to the authenticated customer.
 * @param props.body New quantity value for the cart item (must be between 1 and 99)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Update cart item quantity with customer ownership verification.
 *
 * **Implementation Steps:**
 *
 * 1. **Authentication & Authorization:**
 *    - Extract customerId from JWT token
 *    - Query cart item by id and shopping_customer_id
 *    - Return 404 if cart item not found or doesn't belong to customer
 *
 * 2. **Validation:**
 *    - Validate quantity is between 1 and 99
 *    - Return 400 Bad Request with error message if validation fails
 *
 * 3. **Update Operation:**
 *    - Update the quantity field with the new value
 *    - Update the updated_at timestamp to current time
 *    - Do NOT modify unit_price or any other fields
 *
 * 4. **Database Transaction:**
 *    - Execute within a transaction for data consistency
 *    - Return the updated cart item with all fields
 *
 * 5. **Response Construction:**
 *    - Include cart item id, quantity, unit_price, updated_at
 *    - Include related variant information (joined from shopping_mall_product_variants)
 *    - Include product information (joined through variant relationship)
 *
 * **Error Handling:**
 * - 401 Unauthorized: Customer not authenticated
 * - 404 Not Found: Cart item not found or doesn't belong to customer
 * - 400 Bad Request: Invalid quantity (not 1-99)
 * @path /shoppingMall/customer/cart/:cartItemId
 * @accessor api.functional.shoppingMall.customer.cart.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Unique identifier of the cart item to update. Must belong to the authenticated customer.
     */
    cartItemId: string;

    /**
     * New quantity value for the cart item (must be between 1 and 99)
     */
    body: IShoppingMallCartItem.IUpdate;
  };
  export type Body = IShoppingMallCartItem.IUpdate;
  export type Response = IShoppingMallCartItem;

  export const METADATA = {
    method: "PUT",
    path: "/shoppingMall/customer/cart/:cartItemId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/cart/${encodeURIComponent(props.cartItemId ?? "null")}`;
  export const random = (): IShoppingMallCartItem =>
    typia.random<IShoppingMallCartItem>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartItemId")(() => typia.assert(props.cartItemId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
