import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommerceMallCancellationRequest } from "../../../../../structures/IEcommerceMallCancellationRequest";
import { IPageIEcommerceMallCancellationRequest } from "../../../../../structures/IPageIEcommerceMallCancellationRequest";

/**
 * Retrieve a paginated list of snapshots for a specific cancellation request.
 *
 * Each snapshot captures the cancellation request state at the moment when a seller approved or rejected the request, preserving the reason text and response status for audit trail and dispute resolution purposes.
 *
 * This endpoint is accessible to the customer who submitted the cancellation request, the seller who received the request, and administrators for oversight purposes. The snapshots are immutable records that cannot be modified or deleted.
 *
 * The response includes snapshot identifiers, timestamps, and the captured reason and status values for each historical snapshot.
 *
 * @param props.connection
 * @param props.requestId Unique identifier of the cancellation request (global scope)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query ecommerce_mall_cancellation_request_snapshots table filtering by the provided cancellation request ID.
 * Join with ecommerce_mall_cancellation_requests to verify the request exists.
 * Verify the requesting user has permission: must be the customer who created the request, the seller assigned to the request, or an administrator.
 * Apply pagination using page and limit query parameters (default page 1, limit 20, max 100).
 * Order snapshots by created_at descending (newest first).
 * Return snapshot id, ecommerce_mall_cancellation_request_id, reason, status, and created_at for each record.
 * Handle case where cancellation request does not exist - return 404 error.
 * Handle unauthorized access - return 403 error if user lacks permission.
 * @path /ecommerceMall/customer/cancellation-requests/:requestId/snapshots
 * @accessor api.functional.ecommerceMall.customer.cancellation_requests.snapshots.list
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function list(
  connection: IConnection,
  props: list.Props,
): Promise<list.Response> {
  return true === connection.simulate
    ? list.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...list.METADATA,
          path: list.path(props),
          status: null,
        },
      );
}
export namespace list {
  export type Props = {
    /**
     * Unique identifier of the cancellation request (global scope)
     */
    requestId: string & tags.Format<"uuid">;
  };
  export type Response = IPageIEcommerceMallCancellationRequest.ISummary;

  export const METADATA = {
    method: "GET",
    path: "/ecommerceMall/customer/cancellation-requests/:requestId/snapshots",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommerceMall/customer/cancellation-requests/${encodeURIComponent(props.requestId ?? "null")}/snapshots`;
  export const random = (): IPageIEcommerceMallCancellationRequest.ISummary =>
    typia.random<IPageIEcommerceMallCancellationRequest.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: list.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: list.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific cancellation request snapshot by its unique identifier.
 *
 * This endpoint returns an immutable snapshot of a cancellation request that was captured when the seller responded (approved or rejected) to the request. The snapshot preserves the reason text and status at that moment for audit and dispute resolution purposes.
 *
 * Access is restricted to: the customer who submitted the original cancellation request, the seller who received and responded to the request, or platform administrators. The requestId path parameter establishes the authorization context - users can only view snapshots for cancellation requests they are involved in.
 *
 * The snapshot record is immutable and cannot be modified or deleted. It provides a permanent audit trail linked to its parent cancellation request.
 *
 * @param props.connection
 * @param props.requestId Unique identifier of the parent cancellation request (provides authorization context).
 * @param props.snapshotId Unique identifier of the cancellation request snapshot.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Retrieve the cancellation request snapshot from ecommerce_mall_cancellation_request_snapshots table using the snapshotId.
 *
 * Verify authorization: Check that the authenticated user is either:
 * 1. The customer who submitted the cancellation request (ecommerce_mall_cancellation_requests.ecommerce_mall_customer_id)
 * 2. The seller who received the cancellation request (ecommerce_mall_cancellation_requests.ecommerce_mall_seller_id)
 * 3. An administrator or super administrator
 *
 * If requestId does not match any existing cancellation request, return 404 Not Found.
 *
 * If snapshotId does not match any snapshot for this request, return 404 Not Found.
 *
 * If user is not authorized to view this snapshot, return 403 Forbidden.
 *
 * Return the complete snapshot record including: id, ecommerce_mall_cancellation_request_id, reason, status, and created_at.
 *
 * No pagination required - returns single snapshot record.
 * @path /ecommerceMall/customer/cancellation-requests/:requestId/snapshots/:snapshotId
 * @accessor api.functional.ecommerceMall.customer.cancellation_requests.snapshots.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the parent cancellation request (provides authorization context).
     */
    requestId: string & tags.Format<"uuid">;

    /**
     * Unique identifier of the cancellation request snapshot.
     */
    snapshotId: string & tags.Format<"uuid">;
  };
  export type Response = IEcommerceMallCancellationRequest;

  export const METADATA = {
    method: "GET",
    path: "/ecommerceMall/customer/cancellation-requests/:requestId/snapshots/:snapshotId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommerceMall/customer/cancellation-requests/${encodeURIComponent(props.requestId ?? "null")}/snapshots/${encodeURIComponent(props.snapshotId ?? "null")}`;
  export const random = (): IEcommerceMallCancellationRequest =>
    typia.random<IEcommerceMallCancellationRequest>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
      assert.param("snapshotId")(() => typia.assert(props.snapshotId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
