import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IEcommerceRefundRequestSnapshot } from "../../../../../../../api/structures/IEcommerceRefundRequestSnapshot";
import { IPageIEcommerceRefundRequestSnapshot } from "../../../../../../../api/structures/IPageIEcommerceRefundRequestSnapshot";
import { CustomerAuth } from "../../../../../../../decorators/CustomerAuth";
import { CustomerPayload } from "../../../../../../../decorators/payload/CustomerPayload";
import { getEcommerceCustomerOrdersOrderIdItemsItemIdRefundRequestsRequestIdSnapshotsSnapshotId } from "../../../../../../../providers/getEcommerceCustomerOrdersOrderIdItemsItemIdRefundRequestsRequestIdSnapshotsSnapshotId";
import { patchEcommerceCustomerOrdersOrderIdItemsItemIdRefundRequestsRequestIdSnapshots } from "../../../../../../../providers/patchEcommerceCustomerOrdersOrderIdItemsItemIdRefundRequestsRequestIdSnapshots";

@Controller(
  "/ecommerce/customer/orders/:orderId/items/:itemId/refund-requests/:requestId/snapshots",
)
export class EcommerceCustomerOrdersItemsRefund_requestsSnapshotsController {
  /**
   * Retrieve paginated list of snapshots for a specific refund request, providing complete audit trail of status changes and seller responses.
   *
   * This endpoint returns all snapshot records for the specified refund request, ordered chronologically from oldest to newest. Each snapshot captures the state of the refund request at a specific point in time, including the reason, status, and seller response when applicable.
   *
   * **Access Control**
   * - Customers can view snapshots of their own refund requests
   * - Sellers can view snapshots of refund requests for their products
   * - Administrators can view snapshots of any refund request on the platform
   *
   * **Snapshot Contents**
   * Each snapshot includes the refund reason, current status (pending/approved/rejected), seller response message, response timestamp, and creation timestamp. Snapshots are immutable and cannot be modified or deleted.
   *
   * **Pagination**
   * Results are paginated with cursor-based navigation for large audit histories.
   *
   * @param connection
   * @param orderId UUID of the parent order containing the order item
   * @param itemId UUID of the order item associated with the refund request
   * @param requestId UUID of the refund request whose snapshots to retrieve
   * @param body Search criteria for filtering refund request snapshots including status filter, date range, and pagination parameters.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor customer
     * @x-autobe-specification Query ecommerce_refund_request_snapshots table
     *   with the following constraints:
   *
   * 1. **Path Parameter Validation**
   *    - Validate orderId exists in ecommerce_orders
   *    - Validate itemId exists in ecommerce_order_items and belongs to orderId
   *    - Validate requestId exists in ecommerce_refund_requests and belongs to itemId
   *    - Return 404 if any resource not found
   *
   * 2. **Authorization Check**
   *    - If customer: verify order belongs to authenticated customer
   *    - If seller: verify order item's product belongs to authenticated seller
   *    - If admin: allow access regardless of ownership
   *    - Return 403 if unauthorized
   *
   * 3. **Query Execution**
   *    - Filter snapshots by ecommerce_refund_request_id = requestId
   *    - Apply status filter from request body if provided
   *    - Apply date range filter on created_at if provided
   *    - Order by created_at ASC (chronological)
   *    - Apply cursor-based pagination from request body
   *
   * 4. **Response Construction**
   *    - Return paginated summary with snapshot id, reason, status, seller_response, response_at, created_at
   *    - Include pagination metadata (next cursor, hasMore)
   *
   * 5. **Edge Cases**
   *    - Empty snapshot list: return empty page with hasMore=false
   *    - Invalid cursor: return 400 Bad Request
   *    - Snapshot creation failures should prevent refund request status changes (atomic transaction)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("orderId")
    orderId: string & tags.Format<"uuid">,
    @TypedParam("itemId")
    itemId: string & tags.Format<"uuid">,
    @TypedParam("requestId")
    requestId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IEcommerceRefundRequestSnapshot.IRequest,
  ): Promise<IPageIEcommerceRefundRequestSnapshot.ISummary> {
    try {
      return await patchEcommerceCustomerOrdersOrderIdItemsItemIdRefundRequestsRequestIdSnapshots(
        {
          customer,
          orderId,
          itemId,
          requestId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a specific refund request snapshot by its unique identifier.
   *
   * This operation returns the complete state of a refund request at a specific point in time, including the refund reason, status, and any seller response. Snapshots are immutable audit records created when a refund request is submitted or when the seller responds with approval or rejection.
   *
   * **Access Control**:
   *
   * - **Customers**: Can view snapshots of their own refund requests only
   * - **Sellers**: Can view snapshots of refund requests for products they sell
   * - **Administrators**: Can view snapshots of any refund request on the platform
   *
   * **Relationship Chain**:
   *
   * The path requires all parent identifiers to ensure unambiguous access:
   * - `orderId`: The parent order containing the item
   * - `itemId`: The order item associated with the refund request
   * - `requestId`: The refund request containing the snapshot
   * - `snapshotId`: The specific snapshot to retrieve
   *
   * **Snapshot Contents**:
   *
   * Each snapshot captures the complete state of the refund request at modification time, including the reason for the refund, current status, seller response message (if applicable), and response timestamp. This denormalized approach allows complete reconstruction of the refund request history.
   *
   * **Immutability**:
   *
   * Snapshots are immutable audit records. They cannot be modified or deleted once created. This ensures the audit trail remains intact even if the parent refund request is deleted.
   *
   * @param connection
   * @param orderId Unique identifier of the parent order (UUID scope).
   * @param itemId Unique identifier of the order item within the order (UUID scope).
   * @param requestId Unique identifier of the refund request (UUID scope).
   * @param snapshotId Unique identifier of the snapshot to retrieve (UUID scope).
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor customer
     * @x-autobe-specification Retrieve a specific refund request snapshot with
     *   full authorization and relationship validation.
   *
   * **Authorization Flow**:
   * 1. Validate the authenticated user's actor type (customer, seller, or admin)
   * 2. For customers: verify the order belongs to the authenticated customer
   * 3. For sellers: verify the order item's product belongs to the authenticated seller
   * 4. For admins: allow access to any snapshot
   *
   * **Relationship Validation**:
   * 1. Verify order exists and matches the orderId path parameter
   * 2. Verify order item exists, belongs to the order, and matches the itemId path parameter
   * 3. Verify refund request exists, belongs to the order item, and matches the requestId path parameter
   * 4. Verify snapshot exists, belongs to the refund request, and matches the snapshotId path parameter
   * 5. All relationships must be validated in sequence before returning the snapshot
   *
   * **Business Rules**:
   * - Snapshots are immutable and cannot be modified or deleted
   * - Return 404 if any entity in the chain does not exist or does not match the path parameters
   * - Return 403 if the authenticated user lacks permission to view this snapshot
   * - Include all snapshot fields: id, reason, status, seller_response, response_at, created_at
   *
   * **Error Handling**:
   * - 404 Not Found: Any entity in the chain missing or ID mismatch
   * - 403 Forbidden: User lacks authorization to view this snapshot
   * - 401 Unauthorized: User not authenticated
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":snapshotId")
  public async at(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("orderId")
    orderId: string & tags.Format<"uuid">,
    @TypedParam("itemId")
    itemId: string & tags.Format<"uuid">,
    @TypedParam("requestId")
    requestId: string & tags.Format<"uuid">,
    @TypedParam("snapshotId")
    snapshotId: string & tags.Format<"uuid">,
  ): Promise<IEcommerceRefundRequestSnapshot> {
    try {
      return await getEcommerceCustomerOrdersOrderIdItemsItemIdRefundRequestsRequestIdSnapshotsSnapshotId(
        {
          customer,
          orderId,
          itemId,
          requestId,
          snapshotId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
