import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IDiscussionBoardArticleComment } from "../../../../structures/IDiscussionBoardArticleComment";

/**
 * Create a new comment on an article.
 *
 * This endpoint allows authenticated users to add comments to existing articles. The comment will be associated with the specified article and the currently authenticated user.
 *
 * Security considerations:
 * - Users must be authenticated to create comments
 * - Banned users cannot create comments
 * - Comment content must meet length requirements
 *
 * Database relationships:
 * - Comment is linked to the author (member) via foreign key
 * - Comment is linked to the article via foreign key
 * - Creating a comment increments the article's comment count
 *
 * Validation rules:
 * - Comment content must be between minimum and maximum length
 * - Article must exist before comment can be created
 * - User must not be banned from commenting
 *
 * Related operations:
 * - GET /articles/{articleId}/comments to view comments on an article
 * - PUT /comments/{commentId} to edit your own comment
 * - DELETE /comments/{commentId} to delete your own comment
 *
 * @param props.connection
 * @param props.body Comment creation input
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Create new comment on specified article.
 *
 * 1. Extract comment content from request body
 * 2. Verify user is authenticated (extract from JWT token)
 * 3. Validate user is not banned
 * 4. Validate comment content length requirements
 * 5. Create comment record in database with:
 *    - Content from request body
 *    - Author ID from authenticated user
 *    - Article ID from request body
 *    - Timestamps (createdAt, updatedAt)
 * 6. Increment article's comment count
 * 7. Return created comment with full details
 * @path /discussionBoard/admin/comments
 * @accessor api.functional.discussionBoard.admin.comments.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Comment creation input
     */
    body: IDiscussionBoardArticleComment.ICreate;
  };
  export type Body = IDiscussionBoardArticleComment.ICreate;
  export type Response = IDiscussionBoardArticleComment;

  export const METADATA = {
    method: "POST",
    path: "/discussionBoard/admin/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/discussionBoard/admin/comments";
  export const random = (): IDiscussionBoardArticleComment =>
    typia.random<IDiscussionBoardArticleComment>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
