import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia, { tags } from "typia";
import { patchShoppingMallProductsProductIdSkusSkuIdImages } from "../../../../../providers/patchShoppingMallProductsProductIdSkusSkuIdImages";
import { getShoppingMallProductsProductIdSkusSkuIdImagesImageId } from "../../../../../providers/getShoppingMallProductsProductIdSkusSkuIdImagesImageId";

import { IPageIShoppingMallProductImage } from "../../../../../api/structures/IPageIShoppingMallProductImage";
import { IShoppingMallProductImage } from "../../../../../api/structures/IShoppingMallProductImage";

@Controller("/shoppingMall/products/:productId/skus/:skuId/images")
export class ShoppingmallProductsSkusImagesController {
  /**
   * Retrieve a filtered and paginated list of images linked to a specific SKU
   * variant of a product. This endpoint allows clients to search for images by
   * specifying image attributes—such as display position, alt text content, or
   * label—and supports advanced filtering, sorting, and pagination options
   * tailored for asset galleries in product detail views.
   *
   * For each image, details such as CDN URI, alt text, display position, and
   * internal label are included along with status information. Only images that
   * have not been soft deleted (i.e., deleted_at is null) will be returned in
   * results. Business logic ensures that either the SKU-scoped or
   * product-scoped images are queried according to the given identifiers, but
   * not both at the same time, maintaining category integrity.
   *
   * Security measures restrict access to image assets strictly based on SKU and
   * product binding. Only images valid for the given SKU and product are
   * included, with further constraints as needed for unpublished or hidden
   * products. This operation is useful for rendering SKU image carousels,
   * supporting accessibility via alt text, and moderation or auditing
   * functions.
   *
   * @param connection
   * @param productId Unique identifier of the target catalog product (global
   *   scope).
   * @param skuId Unique identifier of the target SKU within the specified
   *   product (scoped to product).
   * @param body Filter and search criteria for querying images associated with
   *   a product SKU, including pagination and sorting parameters.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
    @TypedParam("skuId")
    skuId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IShoppingMallProductImage.IRequest,
  ): Promise<IPageIShoppingMallProductImage.ISummary> {
    try {
      return await patchShoppingMallProductsProductIdSkusSkuIdImages({
        productId,
        skuId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Fetches metadata and asset details for a single image associated with the
   * specified SKU of a product. The operation requires all identifiers
   * (productId, skuId, imageId) to correctly scope the query and ensure the
   * image is indeed linked to both entities. Resulting data includes the CDN
   * URI, alt text for accessibility, position, label, and creation/update
   * timestamps. Only active (not soft-deleted) images are returned; if the
   * image does not exist or does not belong to the given SKU/product, an error
   * is returned.
   *
   * Business logic ensures that either the SKU or the product association is
   * present and correct, preventing cross-linking between unrelated entities.
   * This endpoint supports validation for asset moderation, gallery management,
   * or accessibility auditing tasks.
   *
   * Security checks prevent disclosure of media assets beyond the permissible
   * scope, in line with business and compliance requirements for digital asset
   * storage.
   *
   * @param connection
   * @param productId Unique identifier of the target catalog product (global
   *   scope).
   * @param skuId Unique identifier of the target SKU within the specified
   *   product (scoped to product).
   * @param imageId Unique identifier of the target image asset record.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":imageId")
  public async at(
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
    @TypedParam("skuId")
    skuId: string & tags.Format<"uuid">,
    @TypedParam("imageId")
    imageId: string & tags.Format<"uuid">,
  ): Promise<IShoppingMallProductImage> {
    try {
      return await getShoppingMallProductsProductIdSkusSkuIdImagesImageId({
        productId,
        skuId,
        imageId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
