import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallCustomerAddress } from "../../../../structures/IPageIShoppingMallCustomerAddress";
import { IShoppingMallCustomerAddress } from "../../../../structures/IShoppingMallCustomerAddress";

export * as _default from "./_default/index";

/**
 * Create a new shipping address for the authenticated customer.
 *
 * This operation allows registered customers to add new shipping addresses to their account. Customers can maintain multiple addresses for different shipping purposes and select which one to use during checkout.
 *
 * The address creation requires complete shipping information including recipient details and full address components. When a customer has no addresses, the newly created address automatically becomes their default shipping address.
 *
 * The operation validates all required fields and returns the complete address record with system-generated fields such as the unique identifier.
 *
 * @param props.connection
 * @param props.body Shipping address information for the new address
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Create new customer shipping address record with validation. Include recipient name, phone number, street address, city, state/province, postal code, and country fields. Validate all required fields before creating record. When customer has no existing addresses, set the new address as default. Return complete address record including system-generated address ID.
 * @path /shoppingMall/customer/addresses
 * @accessor api.functional.shoppingMall.customer.addresses.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Shipping address information for the new address
     */
    body: IShoppingMallCustomerAddress.ICreate;
  };
  export type Body = IShoppingMallCustomerAddress.ICreate;
  export type Response = IShoppingMallCustomerAddress;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/customer/addresses",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/addresses";
  export const random = (): IShoppingMallCustomerAddress =>
    typia.random<IShoppingMallCustomerAddress>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a filtered and paginated list of customer shipping addresses.
 *
 * This operation provides advanced search and filtering capabilities including address field matching, default address filtering, and comprehensive pagination support. Customers can view all their saved shipping addresses with the ability to filter by specific criteria and navigate through large result sets.
 *
 * The operation enforces strict customer isolation - users can only access their own addresses. The system automatically filters results based on the authenticated customer's identity.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query shopping_mall_customer_addresses table filtered by the authenticated customer's ID.
 * Apply search filters on recipient_name, phone_number, street_address, city, state, postal_code, country fields.
 * Filter by is_default flag if provided.
 * Implement cursor-based pagination with configurable page sizes.
 * Return customer-scoped address summaries optimized for list displays.
 * @path /shoppingMall/customer/addresses
 * @accessor api.functional.shoppingMall.customer.addresses.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters
     */
    body: IShoppingMallCustomerAddress.IRequest;
  };
  export type Body = IShoppingMallCustomerAddress.IRequest;
  export type Response = IPageIShoppingMallCustomerAddress.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/customer/addresses",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/addresses";
  export const random = (): IPageIShoppingMallCustomerAddress.ISummary =>
    typia.random<IPageIShoppingMallCustomerAddress.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific customer shipping address by its unique identifier.
 *
 * This operation allows customers to view the complete details of a saved shipping address in their address book. It provides detailed information about the recipient, full address components, and address metadata including whether it is set as the default shipping address.
 *
 * The address information is populated when customers create or edit shipping addresses. This endpoint supports viewing address details for use during checkout or address management workflows.
 *
 * This operation requires authentication as the customer. Only addresses belonging to the authenticated customer can be accessed. Customers cannot view other customers' address information.
 *
 * @param props.connection
 * @param props.addressId Unique identifier of the shipping address
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query shopping_mall_customer_addresses table by addressId. Validate that the address belongs to the authenticated customer by joining with shopping_mall_customers table and matching customer_id. Return complete address record including all fields (recipient_name, phone_number, street_address, city, state, postal_code, country, is_default). Return 404 error if address not found or if address belongs to a different customer. Implement authentication check to ensure only the address owner can access it.
 * @path /shoppingMall/customer/addresses/:addressId
 * @accessor api.functional.shoppingMall.customer.addresses.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the shipping address
     */
    addressId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallCustomerAddress;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/addresses/:addressId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/addresses/${encodeURIComponent(props.addressId ?? "null")}`;
  export const random = (): IShoppingMallCustomerAddress =>
    typia.random<IShoppingMallCustomerAddress>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("addressId")(() => typia.assert(props.addressId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing customer shipping address with new recipient information and location details.
 *
 * This endpoint allows customers to modify their saved shipping addresses, including changing the recipient name, contact phone number, full street address, city, state/province, postal code, and country information. All address fields must be provided in the request body to ensure complete address information is maintained.
 *
 * Security Considerations: Customers can only update addresses that belong to their own account. The system validates address ownership before applying updates to prevent unauthorized modifications to other customers' addresses.
 *
 * Database Relationship: This operation updates the shopping_mall_customer_addresses table, specifically the recipient_name, phone_number, street_address, city, state, postal_code, and country columns. The address remains associated with the original customer through the shopping_mall_customer_id foreign key.
 *
 * **CRITICAL WARNING about soft delete keywords**: This description correctly references soft deletion behavior. The database schema has a `deleted_at` field, so this is appropriate.
 *
 * @param props.connection
 * @param props.addressId Target address's unique identifier
 * @param props.body Updated address information including recipient details and location
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Update customer shipping address in shopping_mall_customer_addresses table.
 *
 * 1. Retrieve target address record by addressId (UUID)
 * 2. Validate address ownership: ensure shopping_mall_customer_id matches current customer's ID
 * 3. If ownership validation fails, return 404 Not Found
 * 4. Update address fields: recipient_name, phone_number, street_address, city, state, postal_code, country
 * 5. Update updated_at timestamp to current timestamp
 * 6. Create inventory history record with reason 'address_update'
 * 7. Return updated address record
 *
 * Edge Cases:
 * - Address not found: Return 404 Not Found
 * - Address belongs to different customer: Return 404 Not Found
 * - Invalid UUID format for addressId: Return 400 Bad Request
 * - Empty or whitespace-only field values: Return 422 Unprocessable Entity
 * - Soft-deleted address: Return 404 Not Found (do not restore)
 *
 * Optimistic concurrency control: Include updated_at timestamp check if implemented in schema.
 * @path /shoppingMall/customer/addresses/:addressId
 * @accessor api.functional.shoppingMall.customer.addresses.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Target address's unique identifier
     */
    addressId: string & tags.Format<"uuid">;

    /**
     * Updated address information including recipient details and location
     */
    body: IShoppingMallCustomerAddress.IUpdate;
  };
  export type Body = IShoppingMallCustomerAddress.IUpdate;
  export type Response = IShoppingMallCustomerAddress;

  export const METADATA = {
    method: "PUT",
    path: "/shoppingMall/customer/addresses/:addressId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/addresses/${encodeURIComponent(props.addressId ?? "null")}`;
  export const random = (): IShoppingMallCustomerAddress =>
    typia.random<IShoppingMallCustomerAddress>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("addressId")(() => typia.assert(props.addressId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete a shipping address from the customer's address list.
 *
 * This operation permanently removes a specific shipping address from the customer's saved addresses. The address must belong to the authenticated customer, and only the address owner can delete their addresses.
 *
 * When the default shipping address is deleted, another address is automatically promoted to default status to ensure the customer always has a default address available for checkout.
 *
 * **Security**: Only the customer who owns the address can delete it. Authentication is required.
 *
 * **Related Operations**:
 * - `GET /addresses` - List all customer addresses
 * - `POST /addresses` - Create a new address
 * - `PUT /addresses/:addressId` - Update an existing address
 * - `PUT /addresses/:addressId/default` - Set an address as default shipping
 *
 * @param props.connection
 * @param props.addressId The unique identifier of the shipping address to delete
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Delete a customer's shipping address by ID.
 *
 * 1. Validate authentication - only the address owner can delete
 * 2. Fetch address by ID and verify ownership
 * 3. If address is default shipping, promote another address to default
 * 4. Delete the address record from the database
 * 5. Return the deleted address object
 * 6. Handle edge case where customer has no other addresses (delete allowed but no promotion needed)
 * @path /shoppingMall/customer/addresses/:addressId
 * @accessor api.functional.shoppingMall.customer.addresses.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * The unique identifier of the shipping address to delete
     */
    addressId: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/shoppingMall/customer/addresses/:addressId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/addresses/${encodeURIComponent(props.addressId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("addressId")(() => typia.assert(props.addressId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
