import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia from "typia";

import { IRedditLikeCommunityGuest } from "../../../../structures/IRedditLikeCommunityGuest";

/**
 * Create an ephemeral guest identity for unauthenticated platform access. Guests are temporary visitors browsing the platform without a registered account. This operation establishes a guest record in the reddit_like_community_guests table, optionally identified by device_fingerprint - a cryptographic hash derived from browser properties like user-agent and screen resolution that enables session continuity across requests.
 *
 * Upon successful join, the system creates a guest record and an associated session in reddit_like_community_guest_sessions capturing client context including IP address, current URL (href), referrer source, and an expiration timestamp. JWT tokens granting read-only access to public content are issued.
 *
 * If a device_fingerprint is provided and matches an existing active guest record, the system reuses that identity rather than creating a duplicate, respecting the unique constraint on device_fingerprint. Guests can view the popular feed, community feeds, all community listings, user profiles, posts, and comments.
 *
 * @setHeader token.access Authorization
 *
 * @param props.connection
 * @param props.body Guest join request containing optional device fingerprint for session continuity.
 * @x-autobe-authorization-type join
 * @x-autobe-authorization-actor guest
 * @x-autobe-specification Create a new guest identity and establish an initial
 *   session. Generate a unique guest record in reddit_like_community_guests
 *   table with optional device_fingerprint for cross-session continuity. Create
 *   an associated session in reddit_like_community_guest_sessions capturing
 *   client IP, href, referrer, and setting expiration (e.g., 24 hours). Return
 *   JWT tokens granting guest-level read-only access. If device_fingerprint is
 *   provided and an active guest exists with it, return existing tokens instead
 *   of creating a duplicate. Handle unique constraint on device_fingerprint
 *   gracefully.
 * @path /redditLikeCommunity/auth/guest/join
 * @accessor api.functional.redditLikeCommunity.auth.guest.join
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function join(
  connection: IConnection,
  props: join.Props,
): Promise<join.Response> {
  const output: join.Response =
    true === connection.simulate
      ? join.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...join.METADATA,
            path: join.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace join {
  export type Props = {
    /**
     * Guest join request containing optional device fingerprint for session continuity.
     */
    body: IRedditLikeCommunityGuest.IJoin;
  };
  export type Body = IRedditLikeCommunityGuest.IJoin;
  export type Response = IRedditLikeCommunityGuest.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/redditLikeCommunity/auth/guest/join",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditLikeCommunity/auth/guest/join";
  export const random = (): IRedditLikeCommunityGuest.IAuthorized =>
    typia.random<IRedditLikeCommunityGuest.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: join.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: join.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Refresh the guest's authentication session and obtain new access tokens. When a guest's session tokens approach expiration, this operation renews authentication without requiring re-identification. The guest provides their current refresh token, which the system validates against the reddit_like_community_guest_sessions table.
 *
 * The system verifies that the associated guest session exists, belongs to a non-deleted guest record, and has not yet expired. Upon validation success, a new session with a fresh expiration timestamp is created and new JWT tokens are issued.
 *
 * If the token is invalid, expired, or the guest record has been soft-deleted, the request is rejected and the guest must perform a new join operation. This enables guests to maintain browsing sessions across extended periods without re-authentication.
 *
 * @setHeader token.access Authorization
 *
 * @param props.connection
 * @param props.body Guest refresh request containing the current refresh token for session renewal.
 * @x-autobe-authorization-type refresh
 * @x-autobe-authorization-actor guest
 * @x-autobe-specification Refresh an existing guest session token. Validate the
 *   provided refresh token against active guest sessions in
 *   reddit_like_community_guest_sessions. Verify the session has not expired
 *   (expired_at > now) and the linked guest record is not soft-deleted. If
 *   valid, create a new guest session record with updated timestamps and new
 *   expiration. Return new JWT tokens. If invalid, expired, or revoked, return
 *   401 unauthorized. The guest identity record remains unchanged - only the
 *   session is refreshed.
 * @path /redditLikeCommunity/auth/guest/refresh
 * @accessor api.functional.redditLikeCommunity.auth.guest.refresh
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function refresh(
  connection: IConnection,
  props: refresh.Props,
): Promise<refresh.Response> {
  const output: refresh.Response =
    true === connection.simulate
      ? refresh.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...refresh.METADATA,
            path: refresh.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace refresh {
  export type Props = {
    /**
     * Guest refresh request containing the current refresh token for session renewal.
     */
    body: IRedditLikeCommunityGuest.IRefresh;
  };
  export type Body = IRedditLikeCommunityGuest.IRefresh;
  export type Response = IRedditLikeCommunityGuest.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/redditLikeCommunity/auth/guest/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/redditLikeCommunity/auth/guest/refresh";
  export const random = (): IRedditLikeCommunityGuest.IAuthorized =>
    typia.random<IRedditLikeCommunityGuest.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: refresh.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: refresh.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
