/**
 * Complete administrative action record with full context of the action performed.
 *
 * This entity represents an immutable audit record of governance actions performed on the shoppingMall platform, including administrator approvals, rejections, suspensions, bans, and other overrides. Each record captures the full context of the action: which administrator performed it, what type of entity was affected (seller, product, order, customer, or category), the specific reason for the action, and the exact timestamp of when it occurred.
 *
 * Access to this information is critical for compliance, dispute resolution, and platform integrity. Administrators can use this record to review historical decisions, verify that proper procedures were followed, and understand the context behind any platform action that affected users or data. The immutable nature of these records ensures that every administrative intervention is permanently traceable for legal and regulatory purposes, in accordance with the platform's snapshot principle.
 *
 * All audit records are generated by the system and reflect actions performed by administrators as defined in the shopping_mall_admin_actions schema. No data in this table is ever modified or removed after creation.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallAdminAction = {};
export namespace IShoppingMallAdminAction {
  /**
   * Summary statistics for inventory analytics per product category. Contains aggregated metrics including total available stock, total units sold, total restocks, percentage of out-of-stock variants, and the number of unique products in the category. This object represents compressed, computed insights for administrative reporting — not a direct representation of any single database entity. All values are derived from immutable inventory history records and are guaranteed to remain unchanged even if product or seller profiles are later modified.
   */
  export type ISummary = {};

  /**
   * Request parameters used to filter and paginate administrative actions and platform analytics. Allows administrators to narrow results by date range, category, seller, or product name. Cursor-based pagination via after_key enables efficient navigation of large audit trails.
   */
  export type IRequest = {};
}
