import { tags } from "typia";

export namespace IShoppingMallProductCategory {
  /**
   * Search and pagination parameters for filtering and sorting the category
   * results.
   */
  export type IRequest = string;

  /** Product-category association details with product and category metadata. */
  export type IInvert = string;

  /**
   * Summary view of a product category for use in list displays and embedded
   * references.
   *
   * This schema represents a lightweight version of the product category. It
   * provides essential information needed to display category information in
   * lists, product detail pages, and other contexts where a full category
   * description is unnecessary.
   *
   * The ISummary type is designed for performance optimization, minimizing
   * data transfer while maintaining sufficient context for user interaction.
   * Navigation links, product filtering, and category identification can all
   * be accomplished using just these fields.
   *
   * References the shopping_mall_categories model in the database and maps to
   * the fields that are most commonly needed in read-only contexts.
   *
   * Includes all essential field relationships while avoiding data bloat by
   * excluding detailed descriptions and related entity arrays which would be
   * included in the full IShoppingMallProductCategory type.
   */
  export type ISummary = {
    /**
     * Unique identifier for the product category.
     *
     * This UUID serves as the primary key in the database and references
     * the shopping_mall_categories table. It is used to uniquely identify
     * each category across all system operations and relationships.
     *
     * The ID is generated by the system upon category creation and should
     * not be provided by clients in request bodies. It is used in various
     * endpoint paths (e.g., /categories/{id}) and reference objects
     * throughout the API.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Display name of the category.
     *
     * This is the human-readable name shown to users in the interface, such
     * as 'Electronics', 'Books > Fiction', or 'Home & Garden'. The name
     * should be concise and descriptive enough for users to understand what
     * products belong in this category.
     *
     * The name field is used for display purposes in navigation menus,
     * search filters, and product listing pages.
     *
     * MaxLength: 100 characters to ensure UI display compatibility. Must be
     * unique within the same parent category to prevent ambiguity.
     */
    name: string;

    /**
     * URL-friendly identifier for this category.
     *
     * Derived from the category name, the slug transforms the display name
     * into a URL-safe format by replacing spaces with hyphens, removing
     * special characters, and converting to lowercase. This is used in
     * category-specific URLs like /category/electronics to create
     * SEO-friendly and user-readable links.
     *
     * Example: 'Electronics' becomes 'electronics', 'Books > Fiction'
     * becomes 'books-fiction'.
     *
     * The slug must be globally unique across all categories to ensure each
     * category has a distinct, direct-access URL.
     *
     * Used in frontend routing, sitemaps, and backend routing logic for
     * category page access.
     */
    slug: string & tags.Format<"uri">;

    /**
     * Detailed description of the category and what products belong in it.
     *
     * This optional field provides additional context about the category's
     * scope and purpose. It can help users understand category boundaries
     * and what types of products are typically included.
     *
     * Example: 'All electronic devices including smartphones, laptops, and
     * accessories designed for personal use.'
     *
     * Length: Up to 500 characters to maintain readability while providing
     * sufficient context.
     *
     * This description is displayed on category landing pages and is used
     * by search engines to understand category content.
     */
    description?: string | undefined;

    /**
     * Reference to the parent category in the hierarchy.
     *
     * Establishes a parent-child relationship between categories to create
     * a multilevel hierarchy. When this field is populated, it identifies
     * the parent category that this category belongs to.
     *
     * When this field is null, the category is a root-level category at the
     * top of the hierarchy.
     *
     * Used for implementing category navigation trees, breadcrumbs, and
     * hierarchical filtering.
     *
     * References the id field in the shopping_mall_categories table.
     * Maintains referential integrity through database constraints.
     */
    parent_category_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Whether this category is currently active and visible to customers.
     *
     * Controls the visibility of the category in storefront navigation and
     * product listings. When false, the category is hidden from customers
     * but still exists in the system for historical data and administrative
     * purposes.
     *
     * This field allows temporary deactivation of categories without
     * deleting them, preserving historical product associations and
     * analytics data.
     *
     * When deactivated, products previously categorized under this category
     * remain accessible but are no longer discoverable through category
     * browsing.
     */
    is_active: boolean;

    /**
     * Order in which this category should be displayed in UI lists.
     *
     * Determines the sorting sequence of categories within their parent
     * group. Categories with lower display_order values appear first in
     * navigation menus and category lists.
     *
     * This manual ordering allows administrators to prioritize important
     * categories (e.g., placing 'Featured Products' at the top) without
     * requiring cultural or alphabetical sorting.
     *
     * Values range from 0 (top priority) upward, with no theoretical
     * maximum but practical limits to prevent display issues.
     *
     * When multiple categories have the same display_order, they are sorted
     * alphabetically by name as a fallback. All organizations must ensure
     * this field is set to prevent unpredictable ordering.
     */
    display_order: number & tags.Type<"int32"> & tags.Minimum<0>;
  };
}
