/**
 * An immutable, point-in-time record of a seller's profile identity—including the shop name, description, and logo URL—as they existed at the exact moment a modification was made. This snapshot preserves the seller's display identity for historical accuracy in dispute resolution, audit trails, and order fulfillment verification. Every change to a seller's profile creates a new snapshot, ensuring no modification ever obliterates prior state. This record is never deleted, modified, or updated. It is referenced only when reconstructing the state of a transaction, review, or interaction as it appeared historically.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallSellerProfileSnapshot = {};
