import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ITodoListUserSession } from "../../../../structures/ITodoListUserSession";
import { IPageITodoListUserSession } from "../../../../structures/IPageITodoListUserSession";

/**
 * Fetch a paginated collection of user session records for the specified Todo
 * List user, using their global email address as a unique identifier.
 *
 * This endpoint is designed for system administrators and security personnel to
 * trace session activity for a particular user account. Each session record
 * includes metadata such as IP address, originating URL, referrer, session
 * creation timestamp, and expiry state. This operation can be used for
 * regulatory compliance, security incident response, or reviewing concurrent
 * device usage by a single user.
 *
 * The endpoint operates in accordance with the strict privacy and isolation
 * guarantees enforced by the todo_list_users schema. Only administrators are
 * permitted to access detailed session records, and no sensitive authentication
 * token material is ever returned. Pagination and filtering are supported in
 * the request body for large user histories. Record retrieval is sorted by
 * session creation time, with most recent logins first.
 *
 * @param props.connection
 * @param props.email User email address serving as globally unique identifier
 *   for the Todo List account (global scope).
 * @param props.body Request body specifying session filtering, pagination, and
 *   sorting criteria for session search.
 * @path /todoList/users/:email/sessions
 * @accessor api.functional.todoList.users.sessions.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * User email address serving as globally unique identifier for the Todo
     * List account (global scope).
     */
    email: string;

    /**
     * Request body specifying session filtering, pagination, and sorting
     * criteria for session search.
     */
    body: ITodoListUserSession.IRequest;
  };
  export type Body = ITodoListUserSession.IRequest;
  export type Response = IPageITodoListUserSession.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/todoList/users/:email/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/todoList/users/${encodeURIComponent(props.email ?? "null")}/sessions`;
  export const random = (): IPageITodoListUserSession.ISummary =>
    typia.random<IPageITodoListUserSession.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("email")(() => typia.assert(props.email));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Fetch full details for a single authenticated user session record from the
 * todo_list_user_sessions table. Both the user's globally unique email and the
 * session's unique ID (UUID) must be specified to identify the target session
 * entry.
 *
 * The returned data includes session metadata: originating IP address,
 * connection URL and referrer, session creation timestamp, and expiration
 * state. No sensitive authentication material or personal Todo data is ever
 * exposed via this endpoint.
 *
 * This endpoint is intended for system administrators performing session audits
 * or advanced troubleshooting. Access is strictly limited to users with
 * administrative privileges. Checks that the specified email corresponds to an
 * existing user account and that the sessionId is valid and associated with
 * that user. Error responses are provided if either does not match.
 *
 * @param props.connection
 * @param props.email Globally unique email address of the user account (global
 *   scope).
 * @param props.sessionId Globally unique identifier of the user session (UUID;
 *   scoped to email).
 * @path /todoList/users/:email/sessions/:sessionId
 * @accessor api.functional.todoList.users.sessions.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Globally unique email address of the user account (global scope). */
    email: string;

    /**
     * Globally unique identifier of the user session (UUID; scoped to
     * email).
     */
    sessionId: string & tags.Format<"uuid">;
  };
  export type Response = ITodoListUserSession;

  export const METADATA = {
    method: "GET",
    path: "/todoList/users/:email/sessions/:sessionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/todoList/users/${encodeURIComponent(props.email ?? "null")}/sessions/${encodeURIComponent(props.sessionId ?? "null")}`;
  export const random = (): ITodoListUserSession =>
    typia.random<ITodoListUserSession>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("email")(() => typia.assert(props.email));
      assert.param("sessionId")(() => typia.assert(props.sessionId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
