import { tags } from "typia";

import { IEcommerceMallProduct } from "./IEcommerceMallProduct";
import { IEcommerceMallProductVariant } from "./IEcommerceMallProductVariant";
import { IEcommerceMallSeller } from "./IEcommerceMallSeller";

/**
 * Query parameters for listing and filtering order items. Supports filtering by fulfillment status, seller, and product with pagination controls for paginated list views.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IEcommerceMallOrderItem = {
  /**
   * Filter by order item fulfillment status. Valid values: paid, shipped, delivered, cancelled, refunded.
   *
   * @x-autobe-specification Filter parameter corresponding to ecommerce_mall_order_items.status column. Valid values: 'paid', 'shipped', 'delivered', 'cancelled', 'refunded'. Applied as WHERE status = {value} condition.
   */
  status?: string | undefined;
};
export namespace IEcommerceMallOrderItem {
  /**
   * Request body for listing and filtering order items with pagination and sorting options. Used by customers, sellers, and administrators to query order items with various filter criteria.
   */
  export type IRequest = {
    /**
     * Search text for filtering by product name (partial match)
     *
     * @x-autobe-specification Filter parameter performing partial case-insensitive match on product names via JOIN to ecommerce_mall_products.name. Uses ILIKE or similar pattern matching. Optional - omit to disable name filtering.
     */
    search?: string | undefined;

    /**
     * Filter by order item fulfillment status
     *
     * @x-autobe-specification Filter by order item fulfillment status. Maps directly to ecommerce_mall_order_items.status column. Valid values: paid, shipped, delivered, cancelled, refunded. Optional - omit to include all statuses.
     */
    status?:
      | "paid"
      | "shipped"
      | "delivered"
      | "cancelled"
      | "refunded"
      | undefined;

    /**
     * Filter by seller ID (UUID)
     *
     * @x-autobe-specification Filter by seller UUID via ecommerce_mall_order_items.seller_id foreign key. For seller-scoped queries to show only items belonging to a specific seller. Optional - omit to include all sellers.
     */
    sellerId?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Filter by order ID (UUID)
     *
     * @x-autobe-specification Filter by order UUID via ecommerce_mall_order_items.order_id foreign key. Used when viewing items within a specific order. Optional - omit to include items from all orders.
     */
    orderId?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Filter by product ID (UUID)
     *
     * @x-autobe-specification Filter by product UUID via ecommerce_mall_order_items.product_id foreign key. Used to find all order items for a specific product across orders. Optional - omit to include all products.
     */
    productId?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Filter by product variant ID (UUID)
     *
     * @x-autobe-specification Filter by product variant UUID via ecommerce_mall_order_items.variant_id foreign key. Used to find all order items for a specific SKU variant. Optional - omit to include all variants.
     */
    variantId?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Filter by order item creation date - start of range (ISO 8601)
     *
     * @x-autobe-specification Filter by order item creation date range start. Maps to ecommerce_mall_order_items.created_at >= value. Accepts ISO 8601 date-time string. Optional - omit for no lower bound.
     */
    createdAtFrom?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter by order item creation date - end of range (ISO 8601)
     *
     * @x-autobe-specification Filter by order item creation date range end. Maps to ecommerce_mall_order_items.created_at <= value. Accepts ISO 8601 date-time string. Optional - omit for no upper bound.
     */
    createdAtTo?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Field to sort results by
     *
     * @x-autobe-specification Determines which field to sort results by. Maps to ORDER BY clause. created_at: sorts by ecommerce_mall_order_items.created_at. status: sorts by ecommerce_mall_order_items.status. seller_id: sorts by ecommerce_mall_order_items.seller_id. price_at_purchase: sorts by ecommerce_mall_order_items.price_at_purchase. quantity: sorts by ecommerce_mall_order_items.quantity. Optional - defaults to created_at.
     */
    sort?:
      | "created_at"
      | "status"
      | "seller_id"
      | "price_at_purchase"
      | "quantity"
      | undefined;

    /**
     * Sort direction (ascending or descending)
     *
     * @x-autobe-specification Determines sort direction for the selected sort field. asc: ascending order (A-Z, oldest first). desc: descending order (Z-A, newest first). Combined with sort parameter to form complete ORDER BY clause. Optional - defaults to desc for created_at, asc for other fields.
     */
    order?: "asc" | "desc" | undefined;

    /**
     * Page number for pagination (1-based indexing)
     *
     * @x-autobe-specification Page number for offset-based pagination (1-based indexing). Used to calculate OFFSET value as (page - 1) * limit. Minimum value 1. Combined with limit to control result window. Optional - defaults to 1.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of items per page
     *
     * @x-autobe-specification Maximum number of records to return per page. Controls LIMIT clause in query. Valid range 1-100. Higher values return more results per request but increase response size. Optional - defaults to system standard (typically 10 or 20).
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };

  /**
   * Request body for updating an order item's fulfillment status. Administrators can perform force-cancellation and force-refund operations. Sellers can update fulfillment status for their own items.
   */
  export type IUpdate = {
    /**
     * New fulfillment status for the order item. Valid values: paid (awaiting shipment), shipped (in transit), delivered (completed), cancelled (order cancelled), refunded (item refunded).
     *
     * @x-autobe-database-schema-property status
     * @x-autobe-specification Direct mapping to ecommerce_mall_order_items.status column. Accepts enum values: 'paid', 'shipped', 'delivered', 'cancelled', 'refunded'. Business logic validates allowed transitions server-side: paid→shipped (seller ships items), paid→cancelled (admin force-cancel or approved cancellation), shipped→delivered (delivery confirmation), shipped/delivered→refunded (approved refund). Invalid transitions return 400 Bad Request.
     */
    status?:
      | "paid"
      | "shipped"
      | "delivered"
      | "cancelled"
      | "refunded"
      | undefined;
  };

  /**
   * Summary view of an order item containing essential purchase information. Includes quantity, price at purchase time, fulfillment status, and references to product, variant, and seller summaries. Used for order item listings where full detail is not required.
   */
  export type ISummary = {
    /**
     * Unique identifier for the order item.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from ecommerce_mall_order_items.id. UUID primary key.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Number of units purchased for this product variant.
     *
     * @x-autobe-database-schema-property quantity
     * @x-autobe-specification Direct mapping from ecommerce_mall_order_items.quantity. Integer representing number of units purchased.
     */
    quantity: number & tags.Type<"int32"> & tags.Minimum<1>;

    /**
     * Price per unit at the time of purchase.
     *
     * @x-autobe-database-schema-property price_at_purchase
     * @x-autobe-specification Direct mapping from ecommerce_mall_order_items.price_at_purchase. Preserved from variant price at time of purchase for historical accuracy.
     */
    priceAtPurchase: number & tags.Minimum<0>;

    /**
     * Current fulfillment status of the order item.
     *
     * @x-autobe-database-schema-property status
     * @x-autobe-specification Direct mapping from ecommerce_mall_order_items.status. One of: paid, shipped, delivered, cancelled, refunded.
     */
    status: "paid" | "shipped" | "delivered" | "cancelled" | "refunded";

    /**
     * Timestamp when the order item was created.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from ecommerce_mall_order_items.created_at. Timestamp when order was placed.
     */
    createdAt: string & tags.Format<"date-time">;

    /**
     * Product information at the time of purchase.
     *
     * @x-autobe-database-schema-property product
     * @x-autobe-specification JOIN via product_id to ecommerce_mall_products. Returns IEcommerceMallProduct.ISummary with purchase-time snapshot data.
     */
    product: IEcommerceMallProduct.ISummary;

    /**
     * Product variant information at the time of purchase.
     *
     * @x-autobe-database-schema-property variant
     * @x-autobe-specification JOIN via variant_id to ecommerce_mall_product_variants. Returns IEcommerceMallProductVariant.ISummary with purchase-time snapshot data including SKU and options.
     */
    variant: IEcommerceMallProductVariant.ISummary;

    /**
     * Seller information at the time of purchase.
     *
     * @x-autobe-database-schema-property seller
     * @x-autobe-specification JOIN via seller_id to ecommerce_mall_sellers. Returns IEcommerceMallSeller.ISummary with purchase-time shop profile snapshot.
     */
    seller: IEcommerceMallSeller.ISummary;
  };

  /**
   * Request body for querying order items that are eligible for refund requests. Filters for delivered items within the 7-day return window belonging to the authenticated customer. Supports optional order filtering and standard pagination/sorting controls.
   */
  export type IEligibleForRefundRequest = {
    /**
     * Optional order ID filter. When provided, only returns eligible order items from the specified order. Null returns items from all orders.
     *
     * @x-autobe-specification Optional filter parameter to narrow results to items from a specific order. When provided, filters by ecommerce_mall_order_items.order_id matching the authenticated customer's order. Maps to order_id column for filtering logic. Null means return eligible items from all orders.
     */
    orderId?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Page number for pagination (1-indexed). Specifies which page of results to return.
     *
     * @x-autobe-specification Pagination parameter specifying which page of results to return. 1-indexed (first page is 1). Used to calculate OFFSET in SQL query: OFFSET = (page - 1) * limit. Default: 1. Minimum: 1. Not a database column - computed query parameter.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Maximum number of order items to return per page (1-100).
     *
     * @x-autobe-specification Pagination parameter specifying maximum number of records per page. Used as LIMIT in SQL query. Default: 10. Minimum: 1, Maximum: 100. Client can request fewer records for smaller page sizes. Not a database column - computed query parameter.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Field name to sort results by (e.g., 'created_at', 'quantity', 'price_at_purchase').
     *
     * @x-autobe-specification Sorting parameter specifying which field to sort results by. Maps to order item columns for ORDER BY clause. Supported values: 'created_at' (order date), 'quantity', 'price_at_purchase'. Default: 'created_at'. Not a database column - computed query parameter that translates to column reference.
     */
    sort?: string | undefined;

    /**
     * Sort direction: 'asc' for ascending or 'desc' for descending.
     *
     * @x-autobe-specification Sorting direction parameter specifying ascending or descending order. Used in SQL ORDER BY clause. Valid values: 'asc' (ascending) or 'desc' (descending). Pattern validated as ^(asc|desc)$. Default: 'desc' for newest first. Not a database column - computed query parameter.
     */
    order?: (string & tags.Pattern<"^(asc|desc)$">) | undefined;
  };
}
