import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IRedditCommunityCommunityBan } from "../../../../../structures/IRedditCommunityCommunityBan";
import { IPageIRedditCommunityCommunityBan } from "../../../../../structures/IPageIRedditCommunityCommunityBan";

/**
 * Retrieve a filtered and paginated list of all community bans associated with
 * a specific member identified by their username. This operation provides
 * comprehensive search capabilities for reviewing ban records across multiple
 * communities where the member has been banned.
 *
 * The operation supports advanced filtering options including ban status
 * (active, expired, appealed), ban date ranges, community filtering, and
 * moderator filtering. Results can be sorted by ban creation date, expiration
 * date, or community name in ascending or descending order. Pagination enables
 * efficient retrieval of large ban histories.
 *
 * Security: This operation is restricted to moderators and administrators who
 * need visibility into member ban histories for moderation purposes. Regular
 * members cannot access other members' ban information. The operation includes
 * appropriate authorization checks to ensure only authorized actors can view
 * ban records.
 *
 * This operation integrates with the reddit_community_community_bans table as
 * defined in the Prisma schema, incorporating ban details, associated community
 * information, moderator who issued the ban, and appeal status. The response
 * provides ban summary information optimized for administrative review
 * interfaces.
 *
 * @param props.connection
 * @param props.username Unique username of the target member whose ban history
 *   is being retrieved
 * @param props.body Search criteria and pagination parameters for filtering
 *   member ban records
 * @path /redditCommunity/moderator/members/:username/bans
 * @accessor api.functional.redditCommunity.moderator.members.bans.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Unique username of the target member whose ban history is being
     * retrieved
     */
    username: string;

    /**
     * Search criteria and pagination parameters for filtering member ban
     * records
     */
    body: IRedditCommunityCommunityBan.IRequest;
  };
  export type Body = IRedditCommunityCommunityBan.IRequest;
  export type Response = IPageIRedditCommunityCommunityBan.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditCommunity/moderator/members/:username/bans",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditCommunity/moderator/members/${encodeURIComponent(props.username ?? "null")}/bans`;
  export const random = (): IPageIRedditCommunityCommunityBan.ISummary =>
    typia.random<IPageIRedditCommunityCommunityBan.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("username")(() => typia.assert(props.username));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
