import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IRedditCommunityPostVote } from "../../../../../../structures/IRedditCommunityPostVote";
import { IPageIRedditCommunityPostVote } from "../../../../../../structures/IPageIRedditCommunityPostVote";

/**
 * Create a vote on a post within a community.
 *
 * This API endpoint facilitates the creation of a vote by a registered user on
 * a specific post within a defined community. It records the vote type,
 * associating the user, post, and community to maintain data integrity and
 * enforce voting rules.
 *
 * Security and permissions require the user to be authenticated, preventing
 * unauthorized votes and ensuring one vote per post per user. The system
 * validates the existence of the post and the community context before allowing
 * the vote.
 *
 * The operation corresponds to the 'reddit_community_post_votes' Prisma table,
 * capturing all necessary relational keys and timestamps to support vote
 * tracking and analytics. It returns the created vote record for confirmation.
 *
 * Users are responsible for providing the appropriate vote type ('upvote' or
 * 'downvote'), which impacts the user's and post's aggregate karma scores.
 *
 * Client applications should handle conflict responses gracefully when
 * attempting duplicate votes.
 *
 * This operation is typically invoked when users interact with the voting UI on
 * posts.
 *
 * @param props.connection
 * @param props.communityName Unique name of the target community (global scope)
 * @param props.postId Unique identifier of the target post
 * @param props.body Vote creation data including user, post, community
 *   association and vote type
 * @path /redditCommunity/user/communities/:communityName/posts/:postId/votes
 * @accessor api.functional.redditCommunity.user.communities.posts.votes.createVoteOnPost
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function createVoteOnPost(
  connection: IConnection,
  props: createVoteOnPost.Props,
): Promise<createVoteOnPost.Response> {
  return true === connection.simulate
    ? createVoteOnPost.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...createVoteOnPost.METADATA,
          path: createVoteOnPost.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace createVoteOnPost {
  export type Props = {
    /** Unique name of the target community (global scope) */
    communityName: string;

    /** Unique identifier of the target post */
    postId: string & tags.Format<"uuid">;

    /**
     * Vote creation data including user, post, community association and
     * vote type
     */
    body: IRedditCommunityPostVote.ICreate;
  };
  export type Body = IRedditCommunityPostVote.ICreate;
  export type Response = IRedditCommunityPostVote;

  export const METADATA = {
    method: "POST",
    path: "/redditCommunity/user/communities/:communityName/posts/:postId/votes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditCommunity/user/communities/${encodeURIComponent(props.communityName ?? "null")}/posts/${encodeURIComponent(props.postId ?? "null")}/votes`;
  export const random = (): IRedditCommunityPostVote =>
    typia.random<IRedditCommunityPostVote>();
  export const simulate = (
    connection: IConnection,
    props: createVoteOnPost.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: createVoteOnPost.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityName")(() => typia.assert(props.communityName));
      assert.param("postId")(() => typia.assert(props.postId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update votes on a specific post within a community.
 *
 * This operation handles updating votes for a specific post within a named
 * community. The votes are cast by authenticated users who wish to upvote or
 * downvote the content. The PATCH method is used to submit vote changes, which
 * allows adding, modifying, or possibly removing a vote.
 *
 * Security considerations include ensuring only authenticated users can vote,
 * and that they may only have one vote per post, prohibiting multiple votes or
 * vote spamming. Vote updates trigger recalculation of the karma score related
 * to the post author.
 *
 * The underlying database entity affected by this operation is the
 * 'reddit_community_post_votes' table, which tracks each vote's type
 * (upvote/downvote), user, post, and community associations. Business logic
 * must validate vote uniqueness per user-post pair and enforce correct vote
 * types.
 *
 * Error conditions such as duplicate votes, voting on own posts, or invalid
 * vote types should return appropriate errors. This operation relates to other
 * API calls managing posts, users, and karma points. The endpoint depends on
 * valid community and post identifiers.
 *
 * Successful results reflect updated vote states and may include refreshed vote
 * counts and summaries.
 *
 * @param props.connection
 * @param props.communityName Unique business identifier code of the target
 *   community (global scope)
 * @param props.postId Unique identifier of the target post
 * @param props.body Vote update payload for the specific post
 * @path /redditCommunity/user/communities/:communityName/posts/:postId/votes
 * @accessor api.functional.redditCommunity.user.communities.posts.votes.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Unique business identifier code of the target community (global
     * scope)
     */
    communityName: string;

    /** Unique identifier of the target post */
    postId: string & tags.Format<"uuid">;

    /** Vote update payload for the specific post */
    body: IRedditCommunityPostVote.IRequest;
  };
  export type Body = IRedditCommunityPostVote.IRequest;
  export type Response = IPageIRedditCommunityPostVote.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/redditCommunity/user/communities/:communityName/posts/:postId/votes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditCommunity/user/communities/${encodeURIComponent(props.communityName ?? "null")}/posts/${encodeURIComponent(props.postId ?? "null")}/votes`;
  export const random = (): IPageIRedditCommunityPostVote.ISummary =>
    typia.random<IPageIRedditCommunityPostVote.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityName")(() => typia.assert(props.communityName));
      assert.param("postId")(() => typia.assert(props.postId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Get detailed information about a specific vote on a post.
 *
 * Retrieve detailed information about a specific vote on a post within a
 * community. The operation is intended for authenticated users to view their or
 * others' vote records on posts.
 *
 * Security ensures that votes are only accessible by authorized users,
 * preventing unauthorized disclosure.
 *
 * The vote entity is represented in the 'reddit_community_post_votes' table,
 * which records each vote's type, associated user, community, and timestamps
 * for auditing.
 *
 * The GET method retrieves the vote's full details without a request body. The
 * path parameters include community name, post identifier, and vote
 * identifier.
 *
 * Error scenarios such as missing vote record or invalid IDs should be handled
 * properly with informative responses.
 *
 * This operation pairs with the vote update operation to manage votes
 * comprehensively.
 *
 * @param props.connection
 * @param props.communityName Unique business identifier code of the target
 *   community (global scope)
 * @param props.postId Unique identifier of the target post
 * @param props.voteId Unique identifier of the target vote
 * @path /redditCommunity/user/communities/:communityName/posts/:postId/votes/:voteId
 * @accessor api.functional.redditCommunity.user.communities.posts.votes.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique business identifier code of the target community (global
     * scope)
     */
    communityName: string;

    /** Unique identifier of the target post */
    postId: string & tags.Format<"uuid">;

    /** Unique identifier of the target vote */
    voteId: string & tags.Format<"uuid">;
  };
  export type Response = IRedditCommunityPostVote;

  export const METADATA = {
    method: "GET",
    path: "/redditCommunity/user/communities/:communityName/posts/:postId/votes/:voteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditCommunity/user/communities/${encodeURIComponent(props.communityName ?? "null")}/posts/${encodeURIComponent(props.postId ?? "null")}/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): IRedditCommunityPostVote =>
    typia.random<IRedditCommunityPostVote>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityName")(() => typia.assert(props.communityName));
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("voteId")(() => typia.assert(props.voteId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing vote on a post within a community.
 *
 * Updates a user's existing vote on a specific post within a community. This
 * allows changing the vote type, such as switching from upvote to downvote,
 * while maintaining all associations to user, post, and community.
 *
 * The operation requires authentication and verifies ownership of the vote to
 * ensure only authorized users modify their votes. It updates timestamps to
 * reflect the change.
 *
 * This operation corresponds to the 'reddit_community_post_votes' Prisma table,
 * updating the existing vote record by ID.
 *
 * Clients should handle potential conflict errors when attempting invalid
 * updates.
 *
 * Typical usage includes changing vote type or correcting previous votes.
 *
 * @param props.connection
 * @param props.communityName Unique name of the target community (global scope)
 * @param props.postId Unique identifier of the target post
 * @param props.voteId Unique identifier of the target vote
 * @param props.body Vote update data specifying new vote type
 * @path /redditCommunity/user/communities/:communityName/posts/:postId/votes/:voteId
 * @accessor api.functional.redditCommunity.user.communities.posts.votes.updateVoteOnPost
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function updateVoteOnPost(
  connection: IConnection,
  props: updateVoteOnPost.Props,
): Promise<updateVoteOnPost.Response> {
  return true === connection.simulate
    ? updateVoteOnPost.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...updateVoteOnPost.METADATA,
          path: updateVoteOnPost.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace updateVoteOnPost {
  export type Props = {
    /** Unique name of the target community (global scope) */
    communityName: string;

    /** Unique identifier of the target post */
    postId: string & tags.Format<"uuid">;

    /** Unique identifier of the target vote */
    voteId: string & tags.Format<"uuid">;

    /** Vote update data specifying new vote type */
    body: IRedditCommunityPostVote.IUpdate;
  };
  export type Body = IRedditCommunityPostVote.IUpdate;
  export type Response = IRedditCommunityPostVote;

  export const METADATA = {
    method: "PUT",
    path: "/redditCommunity/user/communities/:communityName/posts/:postId/votes/:voteId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditCommunity/user/communities/${encodeURIComponent(props.communityName ?? "null")}/posts/${encodeURIComponent(props.postId ?? "null")}/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): IRedditCommunityPostVote =>
    typia.random<IRedditCommunityPostVote>();
  export const simulate = (
    connection: IConnection,
    props: updateVoteOnPost.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: updateVoteOnPost.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityName")(() => typia.assert(props.communityName));
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("voteId")(() => typia.assert(props.voteId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete a specific vote on a post in a community.
 *
 * This DELETE operation permanently removes a specific vote on a post in a
 * given community. The vote is identified uniquely by the vote ID, and the
 * community is identified by its unique community name.
 *
 * Deletion affects the total vote counts and user karma related to the post.
 * Only authorized users, typically the vote owner or administrators, can
 * perform this action.
 *
 * No request body is necessary as identification happens via path parameters.
 *
 * The communityName parameter uses the unique community name (global scope)
 * ensuring correct community identification. The voteId parameter uses the UUID
 * format as unique identifier for the vote.
 *
 * @param props.connection
 * @param props.communityName Unique name of the target community (global scope)
 * @param props.voteId Unique identifier of the target vote
 * @path /redditCommunity/user/communities/:communityName/posts/:postId/votes/:voteId
 * @accessor api.functional.redditCommunity.user.communities.posts.votes.eraseVote
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function eraseVote(
  connection: IConnection,
  props: eraseVote.Props,
): Promise<void> {
  return true === connection.simulate
    ? eraseVote.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...eraseVote.METADATA,
          path: eraseVote.path(props),
          status: null,
        },
      );
}
export namespace eraseVote {
  export type Props = {
    /** Unique name of the target community (global scope) */
    communityName: string;
    postId: string;

    /** Unique identifier of the target vote */
    voteId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/redditCommunity/user/communities/:communityName/posts/:postId/votes/:voteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditCommunity/user/communities/${encodeURIComponent(props.communityName ?? "null")}/posts/${encodeURIComponent(props.postId ?? "null")}/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: eraseVote.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: eraseVote.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("communityName")(() => typia.assert(props.communityName));
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("voteId")(() => typia.assert(props.voteId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
