import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IMallPlatformCategory } from "../../../../../structures/IMallPlatformCategory";
import { IPageIMallPlatformCategory } from "../../../../../structures/IPageIMallPlatformCategory";

/**
 * List the direct subcategories of a category.
 *
 * This endpoint returns only the immediate child categories for the specified parent category. It is used to support customer browsing and administrator review of category structure, while preserving the marketplace rule that category nesting is limited to one level.
 *
 * The response never includes grandchildren or deeper descendants. If the category has no direct subcategories, the endpoint returns an empty page rather than an error. If the category does not exist, the service must return a not-found response. Access control should allow category browsing for customers, while category modification remains restricted to administrators elsewhere in the API.
 *
 * @param props.connection
 * @param props.categoryId The parent category identifier whose direct subcategories will be listed.
 * @param props.body Search, pagination, and sorting criteria for browsing direct subcategories under the selected category.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Resolve the parent category by categoryId first. If no category exists, return 404. Query only rows whose parent reference points to that category, and do not recurse beyond a single level. Apply request pagination and sorting consistently so the list is stable for browsing. Do not expose unrelated category-management metadata in the list response. If persisted data somehow violates the one-level nesting rule, fail the request with an integrity error rather than attempting to synthesize or flatten deeper relationships.
 * @path /mallPlatform/customer/categories/:categoryId/subcategories
 * @accessor api.functional.mallPlatform.customer.categories.subcategories.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * The parent category identifier whose direct subcategories will be listed.
     */
    categoryId: string & tags.Format<"uuid">;

    /**
     * Search, pagination, and sorting criteria for browsing direct subcategories under the selected category.
     */
    body: IMallPlatformCategory.IRequest;
  };
  export type Body = IMallPlatformCategory.IRequest;
  export type Response = IPageIMallPlatformCategory.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/mallPlatform/customer/categories/:categoryId/subcategories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/mallPlatform/customer/categories/${encodeURIComponent(props.categoryId ?? "null")}/subcategories`;
  export const random = (): IPageIMallPlatformCategory.ISummary =>
    typia.random<IPageIMallPlatformCategory.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a direct subcategory under a specific parent category.
 *
 * This endpoint returns the full category record for the requested subcategory and verifies that it belongs directly to the specified parent category. It is intended for customer browsing and category navigation within the marketplace's one-level category hierarchy.
 *
 * The parent category identifier scopes the lookup, and the subcategory identifier must resolve to a category whose parent_category_id matches that parent. If the parent category does not exist, the subcategory does not exist, or the relationship is not direct, the request must fail with a not-found response. Deleted categories should be excluded from normal browsing if the service applies deleted-record filtering.
 *
 * @param props.connection
 * @param props.categoryId The parent category identifier that scopes the subcategory lookup (UUID).
 * @param props.subcategoryId The direct subcategory identifier under the specified parent category (UUID).
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Load the parent category by categoryId, then load the child category by subcategoryId and verify that child.parent_category_id equals the parent category id. If either record is missing or the child is not a direct subcategory of the parent, return not found.
 *
 * Do not traverse beyond one level because the domain only permits direct subcategories. Return the complete category entity using the category table fields only. No request body is required. If the service excludes deleted categories from browsing, apply that filter consistently here.
 * @path /mallPlatform/customer/categories/:categoryId/subcategories/:subcategoryId
 * @accessor api.functional.mallPlatform.customer.categories.subcategories.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The parent category identifier that scopes the subcategory lookup (UUID).
     */
    categoryId: string & tags.Format<"uuid">;

    /**
     * The direct subcategory identifier under the specified parent category (UUID).
     */
    subcategoryId: string & tags.Format<"uuid">;
  };
  export type Response = IMallPlatformCategory;

  export const METADATA = {
    method: "GET",
    path: "/mallPlatform/customer/categories/:categoryId/subcategories/:subcategoryId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/mallPlatform/customer/categories/${encodeURIComponent(props.categoryId ?? "null")}/subcategories/${encodeURIComponent(props.subcategoryId ?? "null")}`;
  export const random = (): IMallPlatformCategory =>
    typia.random<IMallPlatformCategory>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
      assert.param("subcategoryId")(() => typia.assert(props.subcategoryId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
