import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallUserFlag } from "../../../../../structures/IShoppingMallUserFlag";

/**
 * Create a new user flag to denote specific status or condition for a user's
 * account. This operation allows authenticated users to create flags that will
 * be used for internal system tracking and administrative review. The flag is
 * stored in the shopping_mall_user_flags table and linked to the authenticated
 * user's ID from the JWT token.
 *
 * The flag must be created with a valid flag key and optional description. The
 * flag key is a predefined enumeration representing specific user states such
 * as suspicious_activity, policy_violation, or account_alert. Only one flag of
 * the same key per user can be active due to the database's composite unique
 * constraint on (user_id, flag_key). This prevents duplicate flag entries while
 * allowing multiple different flags per user.
 *
 * Security: Only authenticated users can create flags on their own accounts.
 * The user ID in the flag record is automatically populated from the JWT token
 * authentication context and cannot be spoofed. Admins can view these flags for
 * moderation purposes, but users cannot view or modify flags created by other
 * users. Rate limiting applies to prevent spam flag creation.
 *
 * This system enforces that flags are temporary markers for review purposes and
 * do not immediately change user permissions or access levels.
 *
 * Related Operations: GET /user/flags to retrieve active user flags, DELETE
 * /user/flags/{flagId} to remove a user flag (admin only).
 *
 * @param props.connection
 * @param props.body Creation data for a new user flag including the flag key
 *   and optional description.
 * @path /shoppingMall/customer/user/flags
 * @accessor api.functional.shoppingMall.customer.user.flags.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Creation data for a new user flag including the flag key and optional
     * description.
     */
    body: IShoppingMallUserFlag.ICreate;
  };
  export type Body = IShoppingMallUserFlag.ICreate;
  export type Response = IShoppingMallUserFlag;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/customer/user/flags",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/user/flags";
  export const random = (): IShoppingMallUserFlag =>
    typia.random<IShoppingMallUserFlag>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific user flag record from the system. This operation operates
 * on the shopping_mall_user_flags database table and returns detailed
 * information about a user flag identified by its unique flag identifier.
 *
 * The flag represents a user's interaction status or special designation within
 * the platform. This could indicate various user states such as flagged for
 * review, marked as premium user, or having specific permission overrides. The
 * flag data is used for access control, user experience personalization, and
 * platform moderation.
 *
 * Security considerations: Only authenticated administrators can access user
 * flag records. The system validates that the requested flagId exists and
 * returns appropriate status codes for unauthorized access attempts. Rate
 * limiting is applied to prevent enumeration attacks on flag identifiers.
 *
 * This operation integrates with the shopping_mall_user_flags table as defined
 * in the database schema, incorporating all available flag fields including
 * userId, flagType, status, createdAt, and metadata. The response contains
 * complete flag information optimized for client consumption, with no sensitive
 * system fields exposed that aren't relevant to the requesting admin.
 *
 * @param props.connection
 * @param props.flagId Unique identifier of the target user flag. This is a
 *   system-generated identifier that uniquely identifies each flag record in
 *   the shopping_mall_user_flags table. The flagId is a system-assigned string
 *   identifier (not a UUID) that follows the platform's identifier format.
 * @path /shoppingMall/customer/user/flags/:flagId
 * @accessor api.functional.shoppingMall.customer.user.flags.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the target user flag. This is a system-generated
     * identifier that uniquely identifies each flag record in the
     * shopping_mall_user_flags table. The flagId is a system-assigned
     * string identifier (not a UUID) that follows the platform's identifier
     * format.
     */
    flagId: string;
  };
  export type Response = IShoppingMallUserFlag;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/user/flags/:flagId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/user/flags/${encodeURIComponent(props.flagId ?? "null")}`;
  export const random = (): IShoppingMallUserFlag =>
    typia.random<IShoppingMallUserFlag>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("flagId")(() => typia.assert(props.flagId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing user flag's status in the system. This operation modifies
 * the state of a user flag identified by flagId, which represents a special
 * state or setting applied to a user account for moderation, compliance, or
 * notification purposes. The flag is associated with the user flags table in
 * the database schema, which stores user-specific flags with their
 * active/inactive state and metadata.
 *
 * The operation requires complete ownership verification - only the user
 * associated with the flag or system administrators can modify it. The flag's
 * status must be validated against business rules for flag state transitions,
 * preventing invalid state changes (e.g., from 'archived' to 'active'). No flag
 * data is returned in the response as this is a state update operation designed
 * for idempotent behavior.
 *
 * This operation is typically triggered when a user changes their notification
 * preferences or an administrator adjusts moderation settings. Related
 * operations include GET /user/flags/{flagId} for retrieving current status and
 * PATCH /user/flags for listing flags with search filters.
 *
 * @param props.connection
 * @param props.flagId Unique identifier of the target user flag
 *   (system-generated UUID)
 * @path /shoppingMall/customer/user/flags/:flagId
 * @accessor api.functional.shoppingMall.customer.user.flags.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<void> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
      );
}
export namespace update {
  export type Props = {
    /** Unique identifier of the target user flag (system-generated UUID) */
    flagId: string;
  };

  export const METADATA = {
    method: "PUT",
    path: "/shoppingMall/customer/user/flags/:flagId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/user/flags/${encodeURIComponent(props.flagId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("flagId")(() => typia.assert(props.flagId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
