import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IRedditLikeBan } from "../../../../structures/IRedditLikeBan";

/**
 * Retrieve detailed information about a specific community ban.
 *
 * This operation fetches the complete details of a ban record by its unique identifier, including information about the banned user, the community where the ban was issued, the current ban status, and timestamps for when the ban was created and last updated.
 *
 * Only users who are moderators or owners of the community where the ban was issued can access this ban information. Users without appropriate permissions in the relevant community will receive a 403 Forbidden response.
 *
 * The response includes the ban ID, banned user details, community information, ban status (active/inactive), and all timestamp information.
 *
 * @param props.connection
 * @param props.banId Unique identifier of the ban record
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query the reddit_like_bans table by primary key (id).
 * Return the complete ban record including the ban type from status field.
 * Include related banned user and community information through joins.
 * Enforce authorization: only moderators or owners of the community where the ban was issued can access it.
 * @path /redditLike/admin/bans/:banId
 * @accessor api.functional.redditLike.admin.bans.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the ban record
     */
    banId: string;
  };
  export type Response = IRedditLikeBan;

  export const METADATA = {
    method: "GET",
    path: "/redditLike/admin/bans/:banId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditLike/admin/bans/${encodeURIComponent(props.banId ?? "null")}`;
  export const random = (): IRedditLikeBan => typia.random<IRedditLikeBan>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("banId")(() => typia.assert(props.banId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update the status of a community ban.
 *
 * This operation allows moderators and owners to update the status of an existing community ban. Typically used to unban a user by changing the ban status from 'active' to 'inactive'. The ban record is preserved in the system, and the updated status determines whether the user is currently restricted from creating content in the community.
 *
 * Security Considerations: Only users with moderator or owner permissions for the community associated with the ban can perform this operation. The system validates that the requesting user has appropriate moderation privileges before allowing the status update.
 *
 * This operation aligns with the ban persistence logic that ensures ban records remain independent of moderator role changes. Even if a moderator who created a ban is later removed from their role, the ban record (and the ability to update its status) persists in the system.
 *
 * When a ban is updated to inactive, the system automatically restores the user's ability to create posts and comments in the community. When updated to active, the system enforces the restriction by blocking new content creation attempts from the banned user.
 *
 * Related Operations:
 * - POST /bans - Create a new community ban
 * - DELETE /bans/{banId} - Permanently remove a ban record (if soft delete is not used)
 * - GET /communities/{communityName}/banned - List all bans for a community
 *
 * **Important**: This operation only updates the ban status field. To modify the ban reason or other metadata, a different operation would be required, or the ban reason should be set during initial creation.
 *
 * @param props.connection
 * @param props.banId Unique identifier of the community ban to update
 * @param props.body Request body containing the new ban status
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Update the status of an existing community ban by ID.
 *
 * 1. Retrieve the ban record by ID from reddit_like_bans table
 * 2. Verify the user has moderator or owner permissions for the associated community
 * 3. Update only the status field based on request body
 * 4. Update the updated_at timestamp
 * 5. Return the updated ban record with all fields
 *
 * Handle edge cases:
 * - Ban not found (404 error)
 * - User lacks permission (403 error)
 * - Invalid status value (400 error)
 * - Concurrent updates (use optimistic locking if implemented)
 *
 * Return the complete updated ban record including all fields: id, reddit_like_user_id, reddit_like_community_id, status, created_at, updated_at, and deleted_at if applicable.
 * @path /redditLike/admin/bans/:banId
 * @accessor api.functional.redditLike.admin.bans.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Unique identifier of the community ban to update
     */
    banId: string;

    /**
     * Request body containing the new ban status
     */
    body: IRedditLikeBan.IUpdate;
  };
  export type Body = IRedditLikeBan.IUpdate;
  export type Response = IRedditLikeBan;

  export const METADATA = {
    method: "PUT",
    path: "/redditLike/admin/bans/:banId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/redditLike/admin/bans/${encodeURIComponent(props.banId ?? "null")}`;
  export const random = (): IRedditLikeBan => typia.random<IRedditLikeBan>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("banId")(() => typia.assert(props.banId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete a community ban.
 *
 * This operation permanently removes a ban record that was preventing a user from participating in a community. When executed, the specified ban entry is deleted from the system, and the previously banned user regains normal access to the community.
 *
 * **Security and Permissions:**
 *
 * - Only moderators and owners of the community can delete ban records
 * - Users cannot delete their own bans (self-unban is not allowed)
 * - The operation requires authentication and appropriate role authorization
 * - The system logs this action for audit trail purposes
 *
 * **Ban Record Information:**
 *
 * - The ban record includes the banned user identifier and community identifier
 * - Status field indicates whether the ban was active or inactive
 * - Created and updated timestamps track when the ban was issued and modified
 * - The deleted_at timestamp enables soft-delete functionality for audit purposes
 *
 * **Relationship to Other Operations:**
 *
 * - Use GET /communities/{communityName}/banned to view current banned users before deletion
 * - Use POST /communities/{communityName}/banned to create a new ban if needed
 * - This operation affects the user's ability to subscribe and interact with the community
 *
 * **Error Handling:**
 *
 * - Returns 404 if the ban record does not exist
 * - Returns 403 if the user lacks authorization to delete the ban
 * - Returns 400 if the ban ID format is invalid
 *
 * @param props.connection
 * @param props.banId Target ban's unique identifier
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query reddit_like_bans table by id (banId). Delete the ban record permanently. Use database transaction for data integrity. Return deleted ban information for confirmation.
 * @path /redditLike/admin/bans/:banId
 * @accessor api.functional.redditLike.admin.bans.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * Target ban's unique identifier
     */
    banId: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/redditLike/admin/bans/:banId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditLike/admin/bans/${encodeURIComponent(props.banId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("banId")(() => typia.assert(props.banId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
