import { tags } from "typia";

import { IMultiUserTodoTodo } from "./IMultiUserTodoTodo";

/**
 * Complete todo trash entry entity representing a soft-deleted todo in the trash system. Contains deletion, restoration, and permanent deletion timestamps along with the associated todo summary.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IMultiUserTodoTodoTrashEntry = {
  /**
   * Unique identifier for the trash entry.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from multi_user_todo_todo_trash_entries.id. UUID primary key.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Timestamp when the todo was soft-deleted and moved to trash.
   *
   * @x-autobe-database-schema-property deleted_at
   * @x-autobe-specification Direct mapping from multi_user_todo_todo_trash_entries.deleted_at. Timestamp when the todo was moved to trash.
   */
  deleted_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the todo was restored from trash, null if still in trash.
   *
   * @x-autobe-database-schema-property restored_at
   * @x-autobe-specification Direct mapping from multi_user_todo_todo_trash_entries.restored_at. Nullable timestamp when the todo was restored from trash.
   */
  restored_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Timestamp when the todo was permanently deleted from the system, null if still recoverable.
   *
   * @x-autobe-database-schema-property permanently_deleted_at
   * @x-autobe-specification Direct mapping from multi_user_todo_todo_trash_entries.permanently_deleted_at. Nullable timestamp when the todo was permanently deleted.
   */
  permanently_deleted_at?:
    | (string & tags.Format<"date-time">)
    | null
    | undefined;

  /**
   * Timestamp when the trash entry was created.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from multi_user_todo_todo_trash_entries.created_at. Timestamp when the trash entry was created.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the trash entry was last updated.
   *
   * @x-autobe-database-schema-property updated_at
   * @x-autobe-specification Direct mapping from multi_user_todo_todo_trash_entries.updated_at. Timestamp when the trash entry was last updated.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Summary of the associated todo that was moved to trash.
   *
   * @x-autobe-database-schema-property todo
   * @x-autobe-specification JOIN from multi_user_todo_todo_trash_entries.multi_user_todo_todo_id to multi_user_todo_todos.id. Returns ISummary view of the associated todo.
   */
  todo: IMultiUserTodoTodo.ISummary;
};
export namespace IMultiUserTodoTodoTrashEntry {
  /**
   * Request body for updating trash entry status - allows users to restore soft-deleted todos back to active status or permanently delete them from the system.
   */
  export type IUpdate = {
    /**
     * The action to perform on the trash entry - either restore the todo back to active status or permanently delete it from the system.
     *
     * @x-autobe-specification User selection determines which server-managed timestamp to update: 'restore' sets restored_at, 'permanently_delete' sets permanently_deleted_at. Validates trash entry state before applying action.
     */
    action: "restore" | "permanently_delete";
  };

  /**
   * Search criteria and pagination parameters for retrieving trash entries. Used to filter and paginate soft-deleted todos that haven't been restored or permanently deleted.
   */
  export type IRequest = {
    /**
     * Current page number for paginated trash list (1-indexed).
     *
     * @x-autobe-specification 1-indexed page number for paginated results. Controls which page of trash entries to retrieve. Defaults to 1 if not specified.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Maximum number of trash entries to return per page (1-100).
     *
     * @x-autobe-specification Maximum number of trash entries per page. Controls pagination size with range validation (1-100). Ensures reasonable response sizes for API performance.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Start timestamp for filtering trash entries by deletion date range.
     *
     * @x-autobe-specification Start of deletion date range filter (ISO 8601 format). Used to filter trash entries deleted after or on this timestamp. Optional parameter for narrowing search results.
     */
    deleted_at_start?: (string & tags.Format<"date-time">) | undefined;

    /**
     * End timestamp for filtering trash entries by deletion date range.
     *
     * @x-autobe-specification End of deletion date range filter (ISO 8601 format). Used to filter trash entries deleted before or on this timestamp. Optional parameter for narrowing search results.
     */
    deleted_at_end?: (string & tags.Format<"date-time">) | undefined;
  };

  /**
   * Summary view of trash entries for listing soft-deleted todos. Shows deletion management timestamps and essential todo information for trash browsing and recovery operations.
   */
  export type ISummary = {
    /**
     * Unique identifier for this trash entry
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from trash_entries.id. UUID primary key for unique trash entry identification.
     */
    id: string & tags.Format<"uuid">;

    /**
     * When this todo was soft-deleted and moved to trash
     *
     * @x-autobe-database-schema-property deleted_at
     * @x-autobe-specification Direct mapping from trash_entries.deleted_at. Timestamp when the todo was moved to trash.
     */
    deleted_at: string & tags.Format<"date-time">;

    /**
     * When this todo was restored from trash, null if still in trash
     *
     * @x-autobe-database-schema-property restored_at
     * @x-autobe-specification Direct mapping from trash_entries.restored_at. Nullable timestamp indicating when/if the todo was restored from trash.
     */
    restored_at: (string & tags.Format<"date-time">) | null;

    /**
     * When this todo was permanently deleted from trash, null if still recoverable
     *
     * @x-autobe-database-schema-property permanently_deleted_at
     * @x-autobe-specification Direct mapping from trash_entries.permanently_deleted_at. Nullable timestamp indicating when/if the todo was permanently deleted.
     */
    permanently_deleted_at: (string & tags.Format<"date-time">) | null;

    /**
     * The original todo that was soft-deleted
     *
     * @x-autobe-database-schema-property todo
     * @x-autobe-specification JOIN via multi_user_todo_todo_id to multi_user_todo_todos table. Returns ISummary view of the original todo.
     */
    todo: IMultiUserTodoTodo.ISummary;
  };
}
