import { tags } from "typia";

/**
 * Represents the current completion status of a todo item, including the status boolean and timestamp of the most recent completion status change event. Used for retrieving completion information via the GET /todoApp/user/todos/{todoId}/completion endpoint.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppTodoCompletion = {
  /**
   * Unique identifier for the completion status record
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from todo_app_todo_completions.id. Primary key identifier for the completion status record.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Completion status of the todo (true = completed, false = incomplete)
   *
   * @x-autobe-database-schema-property completed
   * @x-autobe-specification Direct mapping from todo_app_todo_completions.completed. Boolean flag indicating whether the todo was marked as completed (true) or incomplete (false) in this status change event.
   */
  completed: boolean;

  /**
   * Timestamp when the completion status was recorded
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from todo_app_todo_completions.created_at. Timestamp when this completion status change was recorded for audit trail purposes.
   */
  created_at: string & tags.Format<"date-time">;
};
