import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallOrderRefund } from "../../../../../structures/IShoppingMallOrderRefund";
import { IPageIShoppingMallOrderRefund } from "../../../../../structures/IPageIShoppingMallOrderRefund";

/**
 * Create a new refund request for a specific customer order through the
 * marketplace refund processing system. This operation handles refund
 * initiation from the shopping_mall_order_refunds table, managing financial
 * compensation for customer returns, seller credits, and dispute resolution
 * processes.
 *
 * The operation supports both partial and full refunds while maintaining
 * transparent accounting across all marketplace participants. When creating a
 * refund, the system validates the original order status, checks refund
 * eligibility based on configured policies, and determines responsible parties
 * for the refund amount.
 *
 * The refund process includes comprehensive validation including order state
 * verification, payment confirmation checking, refund reason categorization,
 * and automatic calculation of appropriate refund amounts including taxes,
 * fees, and promotional adjustments. The system maintains complete audit trails
 * throughout the refund lifecycle while supporting seller notification
 * workflows and customer communication protocols.
 *
 * Security considerations include transaction authorization verification,
 * customer identity validation, and protection against fraudulent refund
 * requests. The operation integrates with the payment processing system through
 * the shopping_mall_payment_refunds table to ensure proper fund transfers and
 * maintains financial reconciliation capabilities for platform operations and
 * regulatory compliance.
 *
 * The refund creation process also handles administrative approval requirements
 * for high-value refunds, implements customer satisfaction tracking, and
 * provides comprehensive supporting evidence documentation for complex refund
 * scenarios.
 *
 * @param props.connection
 * @param props.orderId Unique identifier of the order being refunded
 * @param props.body Refund creation request with details about the refund
 *   reason, amount, and supporting information
 * @path /shoppingMall/customer/orders/:orderId/refunds
 * @accessor api.functional.shoppingMall.customer.orders.refunds.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /** Unique identifier of the order being refunded */
    orderId: string & tags.Format<"uuid">;

    /**
     * Refund creation request with details about the refund reason, amount,
     * and supporting information
     */
    body: IShoppingMallOrderRefund.ICreate;
  };
  export type Body = IShoppingMallOrderRefund.ICreate;
  export type Response = IShoppingMallOrderRefund;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/customer/orders/:orderId/refunds",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/orders/${encodeURIComponent(props.orderId ?? "null")}/refunds`;
  export const random = (): IShoppingMallOrderRefund =>
    typia.random<IShoppingMallOrderRefund>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a filtered and paginated list of refund records associated with a
 * specific order in the shopping mall platform. This operation searches through
 * the shopping_mall_order_refunds table to find all financial compensation
 * records linked to the specified order, including full order refunds, partial
 * item refunds, and dispute resolution transactions.
 *
 * The operation supports comprehensive filtering capabilities including refund
 * reason categories, fault determination (seller, customer, or platform issue),
 * refund status (pending, approved, rejected), administrative approval status,
 * and completion status. Results can be sorted by request date, decision date,
 * or refund amount, providing flexible access to refund history for order
 * management and financial reconciliation.
 *
 * This endpoint is essential for customer service representatives handling
 * order inquiries, financial teams performing refund reconciliation, and
 * administrators monitoring refund patterns across the marketplace. The
 * paginated response includes detailed refund information with associated
 * payment transaction details, seller information, and resolution timelines.
 *
 * @param props.connection
 * @param props.orderId Unique identifier of the order whose refund records are
 *   being retrieved
 * @param props.body Search criteria and pagination parameters for filtering
 *   refund records associated with the specified order
 * @path /shoppingMall/customer/orders/:orderId/refunds
 * @accessor api.functional.shoppingMall.customer.orders.refunds.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Unique identifier of the order whose refund records are being
     * retrieved
     */
    orderId: string & tags.Format<"uuid">;

    /**
     * Search criteria and pagination parameters for filtering refund
     * records associated with the specified order
     */
    body: IShoppingMallOrderRefund.IRequest;
  };
  export type Body = IShoppingMallOrderRefund.IRequest;
  export type Response = IPageIShoppingMallOrderRefund;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/customer/orders/:orderId/refunds",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/orders/${encodeURIComponent(props.orderId ?? "null")}/refunds`;
  export const random = (): IPageIShoppingMallOrderRefund =>
    typia.random<IPageIShoppingMallOrderRefund>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific refund request associated with
 * a customer order. This operation provides comprehensive refund data from the
 * shopping_mall_order_refunds table including financial compensation details,
 * processing status, and resolution information for customer returns, seller
 * credits, and dispute resolutions.
 *
 * The operation returns complete refund lifecycle information including the
 * original order details, refund amount calculations, responsible party
 * determination, processing timelines, and administrative decision history. The
 * data includes financial transaction references for audit trail maintenance
 * and regulatory compliance requirements.
 *
 * The refund information encompasses multiple stakeholder perspectives
 * including customer satisfaction scores, seller response details, platform fee
 * adjustments, and administrative approval status for complex refund scenarios.
 * The system maintains comprehensive documentation throughout the refund
 * process to support financial reconciliation and dispute resolution
 * workflows.
 *
 * Customer satisfaction tracking provides insights into refund resolution
 * effectiveness while supporting evidence documentation helps explain
 * decision-making processes. The system maintains transparent accounting
 * showing how refund amounts affect seller commission calculations and platform
 * fee adjustments.
 *
 * Access is restricted to authorized users including the original customer,
 * associated sellers, and platform administrators to maintain privacy and
 * security standards. The operation provides real-time refund status updates
 * and integrates with payment processing systems to reflect current financial
 * transaction states and completion verification.
 *
 * @param props.connection
 * @param props.orderId Unique identifier of the order containing the refund
 * @param props.refundId Unique identifier of the specific refund to retrieve
 * @path /shoppingMall/customer/orders/:orderId/refunds/:refundId
 * @accessor api.functional.shoppingMall.customer.orders.refunds.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the order containing the refund */
    orderId: string & tags.Format<"uuid">;

    /** Unique identifier of the specific refund to retrieve */
    refundId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallOrderRefund;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/orders/:orderId/refunds/:refundId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/orders/${encodeURIComponent(props.orderId ?? "null")}/refunds/${encodeURIComponent(props.refundId ?? "null")}`;
  export const random = (): IShoppingMallOrderRefund =>
    typia.random<IShoppingMallOrderRefund>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.param("refundId")(() => typia.assert(props.refundId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
