import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IHrmTimesheetTimelog } from "../../../../structures/IHrmTimesheetTimelog";

export * as timelogs from "./timelogs/index";

/**
 * Retrieve a specific timesheet by its unique identifier.
 *
 * This endpoint returns the complete timesheet record including all associated timelog entries for the specified week. The timesheet contains workflow state information (draft, submitted, approved, or rejected), review metadata, and the aggregated total hours calculated from included timelogs.
 *
 * **Access Control**: Employees can view their own timesheets. Managers and owners can view any timesheet within their organization.
 *
 * **Response Contents**: The response includes the timesheet's week period (Monday to Sunday dates), current status, total hours, review information (reviewer, reviewed timestamp, rejection reason if applicable), and all timelog entries included in the timesheet with their project, task, duration, and billable status details.
 *
 * **Business Rules**: Approved timesheets have locked timelogs that cannot be modified. Rejected timesheets include the rejection reason explaining why they were returned to draft status for correction.
 *
 * @param props.connection
 * @param props.timesheetId The unique identifier of the timesheet to retrieve (UUID format).
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query the hrm_timesheets table by id (UUID primary key). Validate the timesheet exists and is not soft-deleted. Verify the requesting user has permission to view this timesheet (owner employee or manager/owner role). Join with hrm_timesheet_timelogs junction table to retrieve all included timelog IDs. For each timelog, join with hrm_timelogs table and optionally with hrm_projects and hrm_tasks tables for full context. Calculate total_hours from the aggregated timelog durations if not already stored. Apply soft delete filtering (deleted_at IS NULL) on all tables. Return the complete timesheet object with nested timelog array. Handle 404 error if timesheet not found or user lacks permission.
 * @path /hrm/member/timesheets/:timesheetId
 * @accessor api.functional.hrm.member.timesheets.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The unique identifier of the timesheet to retrieve (UUID format).
     */
    timesheetId: string & tags.Format<"uuid">;
  };
  export type Response = IHrmTimesheetTimelog;

  export const METADATA = {
    method: "GET",
    path: "/hrm/member/timesheets/:timesheetId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrm/member/timesheets/${encodeURIComponent(props.timesheetId ?? "null")}`;
  export const random = (): IHrmTimesheetTimelog =>
    typia.random<IHrmTimesheetTimelog>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("timesheetId")(() => typia.assert(props.timesheetId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing timesheet's metadata and week period.
 *
 * This operation modifies a timesheet record, allowing changes to the week period dates and other editable fields. The timesheet must be in draft status to be updated; submitted, approved, or rejected timesheets cannot be modified directly.
 *
 * **Workflow Constraints**
 *
 * Only timesheets in draft status can be updated. Once a timesheet is submitted for approval, it becomes locked until a reviewer approves or rejects it. Approved timesheets permanently lock all included timelogs. Rejected timesheets return to draft status and can be updated again.
 *
 * **Week Period Uniqueness**
 *
 * An employee can have at most one timesheet per week (Monday to Sunday). When updating the week_start_date, the system validates that no other timesheet exists for the same employee and week period in submitted or approved status.
 *
 * **Timelog Management**
 *
 * This endpoint updates timesheet metadata only. To add or remove timelogs from a draft timesheet, use the dedicated timelog management endpoint. The total_hours field is automatically recalculated based on included timelogs.
 *
 * @param props.connection
 * @param props.timesheetId UUID identifier of the timesheet to update (global scope).
 * @param props.body Timesheet update payload containing editable fields such as week period dates and rejection reason.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification 1. Validate authentication and organization context from request headers.
 * 2. Validate the timesheet exists and belongs to an employee in the same organization.
 * 3. Check timesheet status: only 'draft' status allows updates. Return 409 Conflict if status is submitted, approved, or rejected.
 * 4. If week_start_date or week_end_date is being updated:
 *    - Validate the new week period (Monday to Sunday).
 *    - Query for existing timesheets for the same employee with overlapping week periods in submitted or approved status.
 *    - Return 409 Conflict if duplicate week found.
 * 5. Update the timesheet fields (week_start_date, week_end_date, rejection_reason if returning to draft).
 * 6. Recalculate total_hours from hrm_timesheet_timelogs junction table if timelog inclusion changed.
 * 7. Update the updated_at timestamp.
 * 8. Return the updated timesheet entity with all relationships.
 *
 * **Edge Cases**
 *
 * - Timesheet not found: Return 404 Not Found
 * - Unauthorized access (timesheet belongs to different organization): Return 403 Forbidden
 * - Non-draft status update attempt: Return 409 Conflict
 * - Duplicate week period: Return 409 Conflict
 * - Invalid date format or non-Monday week_start_date: Return 400 Bad Request
 * @path /hrm/member/timesheets/:timesheetId
 * @accessor api.functional.hrm.member.timesheets.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * UUID identifier of the timesheet to update (global scope).
     */
    timesheetId: string & tags.Format<"uuid">;

    /**
     * Timesheet update payload containing editable fields such as week period dates and rejection reason.
     */
    body: IHrmTimesheetTimelog.IUpdate;
  };
  export type Body = IHrmTimesheetTimelog.IUpdate;
  export type Response = IHrmTimesheetTimelog;

  export const METADATA = {
    method: "PUT",
    path: "/hrm/member/timesheets/:timesheetId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/hrm/member/timesheets/${encodeURIComponent(props.timesheetId ?? "null")}`;
  export const random = (): IHrmTimesheetTimelog =>
    typia.random<IHrmTimesheetTimelog>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("timesheetId")(() => typia.assert(props.timesheetId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Approve a submitted timesheet and lock all included timelogs.
 *
 * This endpoint transitions a timesheet from 'submitted' to 'approved' status, finalizing the weekly time record for payroll and reporting purposes. The reviewer's identity and timestamp are recorded for audit trail purposes.
 *
 * Approval Workflow
 *
 * Only users with the time:approve permission can approve timesheets. The timesheet must be in 'submitted' status; draft timesheets cannot be approved directly, and already approved timesheets cannot be re-approved.
 *
 * Timelog Locking
 *
 * Upon approval, all timelogs included in the timesheet become permanently locked. Locked timelogs cannot be edited or deleted by any user, including the employee who created them. This ensures data integrity for approved time records used in payroll processing.
 *
 * Review Metadata
 *
 * The system records the reviewer's member ID (reviewed_by) and the approval timestamp (reviewed_at). These fields are populated during approval and remain immutable afterward.
 *
 * @param props.connection
 * @param props.timesheetId Unique identifier of the timesheet to approve (UUID format).
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification 1. Extract timesheetId from path parameter (UUID format).
 * 2. Query hrm_timesheets table by id with soft delete filter (deleted_at IS NULL).
 * 3. Validate timesheet exists; return 404 if not found.
 * 4. Validate timesheet.status equals 'submitted'; return 400 if not (cannot approve draft or already approved timesheets).
 * 5. Validate current user has time:approve permission in their organization role; return 403 if not.
 * 6. Begin database transaction.
 * 7. Update timesheet record:
 *    - Set status = 'approved'
 *    - Set reviewed_by = current user's member ID
 *    - Set reviewed_at = current timestamp
 * 8. Query hrm_timesheet_timelogs junction table to find all timelog IDs linked to this timesheet.
 * 9. For each timelog, ensure it cannot be edited/deleted (enforce at application layer via permission checks on timelog endpoints).
 * 10. Commit transaction.
 * 11. Return updated timesheet entity with 200 status.
 *
 * Edge Cases:
 * - Timesheet already approved: Return 400 with error message.
 * - Timesheet in rejected status: Return 400 (must resubmit first).
 * - No timelogs in timesheet: Allow approval but total_hours will be 0.
 * - Concurrent approval attempts: Use optimistic locking or transaction isolation to prevent duplicate approvals.
 * @path /hrm/member/timesheets/:timesheetId/approve
 * @accessor api.functional.hrm.member.timesheets.approve
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function approve(
  connection: IConnection,
  props: approve.Props,
): Promise<approve.Response> {
  return true === connection.simulate
    ? approve.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...approve.METADATA,
          path: approve.path(props),
          status: null,
        },
      );
}
export namespace approve {
  export type Props = {
    /**
     * Unique identifier of the timesheet to approve (UUID format).
     */
    timesheetId: string & tags.Format<"uuid">;
  };
  export type Response = IHrmTimesheetTimelog;

  export const METADATA = {
    method: "POST",
    path: "/hrm/member/timesheets/:timesheetId/approve",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrm/member/timesheets/${encodeURIComponent(props.timesheetId ?? "null")}/approve`;
  export const random = (): IHrmTimesheetTimelog =>
    typia.random<IHrmTimesheetTimelog>();
  export const simulate = (
    connection: IConnection,
    props: approve.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: approve.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("timesheetId")(() => typia.assert(props.timesheetId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
