import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallCart } from "../../../../structures/IShoppingMallCart";
import { IPageIShoppingMallCart } from "../../../../structures/IPageIShoppingMallCart";

/**
 * Search and retrieve shopping cart sessions with advanced filtering and
 * pagination capabilities.
 *
 * This operation provides comprehensive search functionality for shopping cart
 * sessions stored in the shopping_mall_carts table. It supports filtering by
 * cart status (active, abandoned, converted, expired), customer session
 * associations, date ranges, and applied coupon codes. The operation is
 * designed for administrative oversight and customer service scenarios where
 * cart analytics and session management are required.
 *
 * Search capabilities include filtering by creation date ranges, status
 * changes, expiration timelines, and shipping method selections. Pagination
 * parameters allow for efficient browsing of large cart datasets while
 * maintaining performance. The operation returns summarized cart information
 * optimized for list displays, including key metadata like status, expiration
 * dates, and session context.
 *
 * Security considerations ensure that customers can only search their own cart
 * sessions, while administrative users may access broader cart data for system
 * analytics and abandoned cart recovery initiatives. The operation supports
 * complex query structures while maintaining data privacy and access control
 * boundaries.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for cart
 *   filtering
 * @path /shoppingMall/admin/carts
 * @accessor api.functional.shoppingMall.admin.carts.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Search criteria and pagination parameters for cart filtering */
    body: IShoppingMallCart.IRequest;
  };
  export type Body = IShoppingMallCart.IRequest;
  export type Response = IPageIShoppingMallCart.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/admin/carts",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/admin/carts";
  export const random = (): IPageIShoppingMallCart.ISummary =>
    typia.random<IPageIShoppingMallCart.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
