import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
export * as replies from "./replies/index";

/**
 * Permanently delete a specific comment from the community_platform_comments
 * table for a given post.
 *
 * Erase a specific comment row from the community_platform_comments table for a
 * given post.
 *
 * This delete operation targets the same domain as the update endpoint but
 * performs a hard removal of a comment rather than a status-based visibility
 * change. The community_platform_comments table represents comments and nested
 * replies attached to posts, with each row linked to a post via post_id
 * referencing community_platform_posts.id and optionally to a parent comment
 * via parent_comment_id for nested threads. It stores the current version of
 * each comment’s body text and its status and lock state, while historical
 * edits reside in community_platform_comment_edit_histories.
 *
 * The client must provide both postId and commentId as path parameters.
 * Internally, the service resolves the target row by ensuring that
 * community_platform_comments.post_id equals the supplied postId and
 * community_platform_comments.id equals the supplied commentId. This dual-key
 * check guarantees that the comment being erased indeed belongs to the
 * specified post and prevents deletion of a comment from an unintended context.
 * The operation then performs a permanent deletion of the matching record from
 * community_platform_comments. Unlike flows that toggle the status field or set
 * the deleted_at timestamp to hide a comment while preserving its structure,
 * this operation removes the record itself from the table.
 *
 * From a security and governance perspective, this endpoint should be exposed
 * only to privileged actors, which in this API contract are represented by the
 * adminUser actor type and will be further distinguished in the business logic
 * based on roles. Typical memberUser actors should not be allowed to call this
 * endpoint directly; instead they should use comment update flows that mark a
 * comment as deleted_by_author while keeping it stored for thread integrity and
 * audit purposes. The service implementation should enforce strict checks,
 * ensuring only authorized moderation or administrative users can execute an
 * erase, and should decide how to handle dependent data such as votes, reports,
 * or child replies.
 *
 * On success, the endpoint does not return a representation of the deleted
 * comment; responseBody is null to indicate that consumers should use list or
 * detail retrieval endpoints to observe the resulting state of the post’s
 * comment tree. Error handling includes returning not-found when no comment
 * exists for the provided postId and commentId combination, authorization
 * failures when the caller lacks permission to perform destructive deletions,
 * and conflict responses when business rules forbid erasing a comment in
 * certain states (for example, when regulations require retaining specific
 * moderation records).
 *
 * @param props.connection
 * @param props.postId Unique identifier (UUID) of the post that owns the
 *   comment to erase. This value is matched against
 *   community_platform_comments.post_id.
 * @param props.commentId Unique identifier (UUID) of the comment to erase from
 *   the community_platform_comments table.
 * @path /communityPlatform/adminUser/posts/:postId/comments/:commentId
 * @accessor api.functional.communityPlatform.adminUser.posts.comments.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * Unique identifier (UUID) of the post that owns the comment to erase.
     * This value is matched against community_platform_comments.post_id.
     */
    postId: string & tags.Format<"uuid">;

    /**
     * Unique identifier (UUID) of the comment to erase from the
     * community_platform_comments table.
     */
    commentId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/communityPlatform/adminUser/posts/:postId/comments/:commentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/adminUser/posts/${encodeURIComponent(props.postId ?? "null")}/comments/${encodeURIComponent(props.commentId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("postId")(() => typia.assert(props.postId));
      assert.param("commentId")(() => typia.assert(props.commentId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
