import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IShoppingMallReturnReasonStatistics } from "../../../../../structures/IShoppingMallReturnReasonStatistics";

/**
 * Retrieve aggregated statistics of order return reasons from
 * shopping_mall_order_return_requests.
 *
 * Retrieve aggregated statistics for order return reasons based on the
 * `shopping_mall_order_return_requests` Prisma model.
 *
 * The `shopping_mall_order_return_requests` table stores individual return or
 * refund requests that customers create for delivered order items within the
 * allowed return window. Its schema comments describe it as the canonical
 * repository for after-delivery return interactions, including fields such as
 * normalized reason category, fine-grained reason code, optional free-text
 * notes, references to the related order and order line, and the initiating
 * customer identity. Because this table captures the structured reason metadata
 * for each return, it is the ideal basis for computing return reason
 * statistics.
 *
 * This analytics operation groups records in
 * `shopping_mall_order_return_requests` by the standardized reason dimensions
 * (for example, a reason category like `defective_product`, `wrong_item`,
 * `size_or_fit`, `changed_mind`, or `shipping_issue`, and a more specific
 * reason code where available). For each group, it counts the number of
 * matching return requests and may compute additional metrics such as the
 * proportion of total returns or breakdowns by associated seller or product.
 * Those aggregates are exposed through the DTO
 * `IShoppingMallReturnReasonStatistics`, which is defined specifically for this
 * statistics view and may include fields like reason code, reason label, total
 * count, and percentage share.
 *
 * From a security perspective, this endpoint exposes platform-wide operational
 * metrics about product quality and customer experience and therefore should be
 * restricted to privileged administrative actors rather than general customers
 * or sellers. The operation is strictly read-only: it performs SELECT and
 * aggregation queries against `shopping_mall_order_return_requests` and does
 * not insert, update, or delete any records. Any optional query parameters that
 * define the analysis window or filters must be validated for correct format
 * and range, and invalid inputs should be handled according to the platform’s
 * global error-handling rules.
 *
 * This API will typically be used together with other statistics endpoints such
 * as dispute reason statistics or seller performance summaries, enabling admins
 * to monitor trends, detect anomalies (for example, sudden spikes in
 * defect-related returns), and drive corrective actions with sellers or
 * logistics partners.
 *
 * @param props.connection
 * @path /shoppingMall/platformAdmin/statistics/returnReasons
 * @accessor api.functional.shoppingMall.platformAdmin.statistics.returnReasons.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(connection: IConnection): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
      );
}
export namespace index {
  export type Response = IShoppingMallReturnReasonStatistics;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/platformAdmin/statistics/returnReasons",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () =>
    "/shoppingMall/platformAdmin/statistics/returnReasons";
  export const random = (): IShoppingMallReturnReasonStatistics =>
    typia.random<IShoppingMallReturnReasonStatistics>();
  export const simulate = (_connection: IConnection): Response => {
    return random();
  };
}
