import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallProduct } from "../../../../structures/IPageIShoppingMallProduct";
import { IShoppingMallProduct } from "../../../../structures/IShoppingMallProduct";

export * as images from "./images/index";
export * as variants from "./variants/index";
export * as detail from "./detail/index";
export * as review_statistics from "./review_statistics/index";

/**
 * Search and browse products across the platform catalog.
 *
 * Returns a paginated list of product summaries optimized for search result displays and category browsing pages. Each summary includes the product's main thumbnail image, name, price information (base price or variant price range when variants have differing prices), seller shop name, and average rating from customer reviews.
 *
 * Products from suspended sellers, banned sellers, unapproved sellers, or deleted products are excluded from results. Products with no variants are included in results but marked as unavailable for purchase.
 *
 * Supports full-text search on product names, filtering by category (including subcategory browsing), price range constraints, and in-stock-only filtering. Results can be sorted by newest first, price ascending, or price descending.
 *
 * @param props.connection
 * @param props.body Search criteria for browsing and filtering products. Supports text search on product name, category filtering, price range constraints, in-stock-only filtering, sorting preferences, and pagination parameters.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query the shopping_mall_products table with the
 *   following inclusion rules: - Only products where deleted_at IS NULL - Only
 *   products from sellers where banned_at IS NULL and suspended_at IS NULL and
 *   approval_status = 'approved' - Join with shopping_mall_sellers and
 *   shopping_mall_seller_profiles for seller shop name - Left join with
 *   shopping_mall_product_images to determine the main thumbnail (image with
 *   lowest display_order where display_order >= 0) - Aggregate review data from
 *   shopping_mall_review_reviews for average rating and total review count
 *   (only non-deleted reviews)
 *
 * Apply search and filter criteria from the request body:
 * - Text search: use GIN trigram index (shopping_mall_products_name_idx) for name similarity matching
 * - Category filter: filter by shopping_mall_category_id; when browsing a parent category, also include products in its subcategories
 * - Price range: filter by base_price or variant price range (min/max of non-deleted variant prices)
 * - In-stock only: exclude products whose all non-deleted variants have zero stock (computed via sum of inventory_records)
 *
 * Apply sorting based on sort parameter:
 * - newest: ORDER BY created_at DESC
 * - price_asc: ORDER BY effective_price ASC (using variant price when set, base_price otherwise; for products with multiple variants, use the minimum effective price)
 * - price_desc: ORDER BY effective_price DESC
 *
 * Apply cursor-based or offset pagination. Return IPageIShoppingMallProduct.ISummary with items containing: product ID, name, thumbnail image URL (first image or null), effective price information (base price, minimum variant price, maximum variant price), seller shop name, average rating, total review count, and whether the product is purchasable (has at least one non-deleted variant with stock > 0).
 * @path /shoppingMall/customer/products
 * @accessor api.functional.shoppingMall.customer.products.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria for browsing and filtering products. Supports text search on product name, category filtering, price range constraints, in-stock-only filtering, sorting preferences, and pagination parameters.
     */
    body: IShoppingMallProduct.IRequest;
  };
  export type Body = IShoppingMallProduct.IRequest;
  export type Response = IPageIShoppingMallProduct.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/customer/products",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/products";
  export const random = (): IPageIShoppingMallProduct.ISummary =>
    typia.random<IPageIShoppingMallProduct.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieves the full details of a single product for display on the product detail page.
 *
 * The response includes the complete product information: name, description, base price, category, and the owning seller's shop name and logo. All product images are returned in display order, with the first image serving as the main thumbnail.
 *
 * Every purchasable variant is included with its SKU code, option values (e.g., color, size), price (or the base price if no override is set), and current stock status derived from the variant's inventory ledger. Products with no variants are shown with an empty variant list and are considered unavailable for purchase.
 *
 * All customer reviews for this product are returned sorted newest first, along with the calculated average rating and total review count. Reviews from customers who have deleted their accounts are preserved but the author is shown as "deleted user".
 *
 * This endpoint is accessible to all authenticated customers for browsing the catalog. The owning seller can view their product even if it is deleted or their account is suspended. Administrators have unrestricted access to any product, including deleted ones, supporting their oversight and snapshot review responsibilities.
 *
 * @param props.connection
 * @param props.productId UUID of the product to retrieve.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Retrieve a single product by its UUID primary key.
 *
 * Query the shopping_mall_products table by id. Join with shopping_mall_sellers to get the owning seller's email and approval_status, and with shopping_mall_seller_profiles to include the seller's shop_name, shop_description, and logo_image_uri. Join with shopping_mall_categories for the category's name and description.
 *
 * Include all non-deleted images from shopping_mall_product_images ordered by display_order ascending (the first image is the main thumbnail). Include all non-deleted variants from shopping_mall_product_variants with their option values from shopping_mall_product_variant_option_values. For each variant, calculate current stock by summing all shopping_mall_inventory_records for that variant — a variant is out of stock when the sum is zero or less. Include all non-deleted reviews from shopping_mall_review_reviews sorted by created_at descending (newest first). Calculate the average rating from all non-deleted reviews; if there are no reviews, the average rating is null. Include the total count of non-deleted reviews.
 *
 * Visibility rules: if the product's deleted_at is set, return 404 for customers and sellers who do not own the product. Sellers can view their own deleted products, and administrators can view any deleted product (for snapshot history access). If the seller's suspended_at is set, hide the product from customers but allow the owning seller and administrators to view it. If the seller's banned_at is set, still allow administrators to view the product.
 *
 * When the authoring customer of a review has deleted their account (the customer record no longer exists or is soft-deleted), display the review author as "deleted user" rather than the original display name.
 * @path /shoppingMall/customer/products/:productId
 * @accessor api.functional.shoppingMall.customer.products.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * UUID of the product to retrieve.
     */
    productId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallProduct;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/products/:productId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/products/${encodeURIComponent(props.productId ?? "null")}`;
  export const random = (): IShoppingMallProduct =>
    typia.random<IShoppingMallProduct>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
