import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IPageIRedditCommunityPost } from "../../../../../api/structures/IPageIRedditCommunityPost";
import { IRedditCommunityPost } from "../../../../../api/structures/IRedditCommunityPost";
import { GuestAuth } from "../../../../../decorators/GuestAuth";
import { GuestPayload } from "../../../../../decorators/payload/GuestPayload";
import { patchRedditCommunityGuestUsersUserIdPosts } from "../../../../../providers/patchRedditCommunityGuestUsersUserIdPosts";

@Controller("/redditCommunity/guest/users/:userId/posts")
export class RedditcommunityGuestUsersPostsController {
  /**
   * Retrieve a paginated list of all posts created by a specified user, as displayed on the user's profile page.
   *
   * This operation returns posts created by the target user, showing essential information including title, community association, vote score, and comment count. The list is sorted in reverse chronological order by default, with the most recently created posts appearing first.
   *
   * Users can browse through paginated results when a user has created many posts. The operation excludes archived posts and deleted posts from the results.
   *
   * The requesting user can be any authenticated user or guest, as profile information is publicly accessible. The target user's profile must exist and not be deleted.
   *
   * @param connection
   * @param userId The user ID to retrieve posts for (UUID format)
   * @param body Search criteria and pagination parameters for the user's posts list
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor guest
   * @x-autobe-specification Query reddit_community_posts table where author_id matches the userId path parameter and deleted_at is NULL.
   *
   * Apply reverse chronological ordering by created_at DESC as default sort.
   *
   * Apply pagination using cursor-based pagination for efficient large result sets. Support configurable page size with reasonable limits.
   *
   * Join with reddit_community_communities table to include community_name in each post summary.
   *
   * Apply filters if provided in requestBody (e.g., community filtering, keyword search in title).
   *
   * Validate that the target user exists in reddit_community_members table and has not been deleted.
   *
   * Ensure the requesting user has permission to view the profile (any authenticated user or guest can view public profiles).
   *
   * Return post summaries with fields: post_id, title, community_name, vote_score, comment_count, created_at.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @GuestAuth()
    guest: GuestPayload,
    @TypedParam("userId")
    userId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IRedditCommunityPost.IRequest,
  ): Promise<IPageIRedditCommunityPost.ISummary> {
    try {
      return await patchRedditCommunityGuestUsersUserIdPosts({
        guest,
        userId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
