/**
 * Represents a customer's cancellation request for an individual order item within the shopping mall platform. Provides detailed information including the cancellation reason, seller approval status and rationale, timestamps for request and processing, and linked customer and order item references. Used for managing cancellation workflows and enabling tracking and approval processes in the API.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallCancellationRequest = {};
export namespace IShoppingMallCancellationRequest {
  /**
   * Summary DTO of a cancellation request made by a customer for an order item, including seller decision status and timestamps for customer and seller interactions.
   */
  export type ISummary = {};

  /**
   * Request body schema to update a cancellation request of an order item within the shopping mall platform. Allows updating the customer-provided reason, seller approval status (enum pending|approved|rejected), optional seller approval reason, and processing timestamp when approved or rejected.
   */
  export type IUpdate = {};

  /**
   * Request body schema for creating a cancellation request by a customer, including the customer ID, order item ID, and cancellation reason.
   */
  export type ICreate = {};

  /**
   * Request DTO for filtered and paginated retrieval of cancellation requests submitted by customers for order items. Enables efficient management of cancellation requests by sellers and administrators with flexible filtering and pagination support.
   */
  export type IRequest = {};

  /**
   * Request payload for sellers to approve or reject a cancellation request. Contains the approval status and optional explanatory reason.
   */
  export type IApproveReject = {};
}
