import { tags } from "typia";

import { ICommunityMember } from "./ICommunityMember";

/**
 * Detailed representation of a member session token, including client IP address, request context, expiration details, and member profile summary. Designed for audit and security monitoring with no sensitive token data exposed.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityMemberSession = {
  /**
   * Unique session identifier
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from community_member_sessions.id (UUID primary key)
   */
  id: string & tags.Format<"uuid">;

  /**
   * Client IP address logged for security context
   *
   * @x-autobe-database-schema-property ip
   * @x-autobe-specification Direct mapping from community_member_sessions.ip
   */
  ip: string;

  /**
   * Full request URL where session was created
   *
   * @x-autobe-database-schema-property href
   * @x-autobe-specification Direct mapping from community_member_sessions.href
   */
  href: string;

  /**
   * Previous page URL that initiated the session (optional)
   *
   * @x-autobe-database-schema-property referrer
   * @x-autobe-specification Direct mapping from community_member_sessions.referrer (nullable field)
   */
  referrer?: string | null | undefined;

  /**
   * Timestamp when session was created
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from community_member_sessions.created_at (UTC timestamp)
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when session expires
   *
   * @x-autobe-database-schema-property expired_at
   * @x-autobe-specification Direct mapping from community_member_sessions.expired_at (UTC timestamp)
   */
  expired_at: string & tags.Format<"date-time">;

  /**
   * Member profile summary associated with this session
   *
   * @x-autobe-database-schema-property member
   * @x-autobe-specification The 'member' relation is mandatory due to non-nullable community_member_id foreign key. Should be in required[]
   */
  member: ICommunityMember.ISummary;
};
export namespace ICommunityMemberSession {
  /**
   * Request body containing session identifier (UUID) to identify and refresh an active member session's expiration period.
   */
  export type IRequest = {
    /**
     * Unique identifier of the session to refresh (UUID format).
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from community_member_sessions.id. UUID primary key field used for session identification and database lookups.
     */
    id: string & tags.Format<"uuid">;
  };
}
