import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IEcommerceMallProduct } from "../../../../api/structures/IEcommerceMallProduct";
import { AdminAuth } from "../../../../decorators/AdminAuth";
import { AdminPayload } from "../../../../decorators/payload/AdminPayload";
import { deleteEcommerceMallAdminProductsProductId } from "../../../../providers/deleteEcommerceMallAdminProductsProductId";
import { putEcommerceMallAdminProductsProductId } from "../../../../providers/putEcommerceMallAdminProductsProductId";

@Controller("/ecommerceMall/admin/products/:productId")
export class EcommercemallAdminProductsController {
  /**
   * Update an existing product's information.
   *
   * This operation allows sellers to modify their product details including name, description, category assignment, and base price. Only the seller who owns the product can perform updates. When a product is updated, a snapshot of the previous state is automatically created to preserve history for audit and dispute resolution purposes.
   *
   * **Authorization Required**: Seller authentication required. Only the product owner can update their products. Sellers with pending or rejected registration status are blocked from this operation.
   *
   * **Validation Rules**:
   * - Product name is required and must be unique within the same category
   * - Category must exist and be a valid category or subcategory
   * - Base price must be a positive number representing the default price
   * - Cannot update products that have been soft deleted
   *
   * **Snapshot Creation**: On successful update, a product snapshot is automatically created containing the complete state before the modification (name, description, category, base price, and images). This preserves the historical state for order reference and dispute resolution.
   *
   * **Business Rules**:
   * - Products are exclusively owned by the seller who created them
   * - Category changes immediately affect where the product appears in navigation
   * - The first image (sort order 1) serves as the thumbnail and is shown in listings
   * - Product changes do not affect existing orders which preserve snapshots at purchase time
   *
   * @param connection
   * @param productId Target product's ID (UUID format)
   * @param body Product update data containing fields to modify
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor admin
   * @x-autobe-specification Implement PUT /products/{productId} operation to update existing product records.
   *
   * **Service Layer Logic**:
   * 1. Authenticate as seller and extract seller_id from token
   * 2. Validate productId is a valid UUID format
   * 3. Query ecommerce_mall_products table to find product by id
   * 4. Verify product exists and is not soft deleted (deleted_at IS NULL)
   * 5. Verify requesting seller owns the product (seller_id matches)
   * 6. Verify seller registration status is approved (not pending or rejected)
   * 7. Validate request body fields:
   *    - name: non-empty string
   *    - description: non-empty string
   *    - category_id: valid UUID referencing ecommerce_mall_categories
   *    - base_price: positive number (Double)
   * 8. Verify new name is unique within the target category (@@unique([name, category_id]) constraint check)
   * 9. Create product snapshot BEFORE update:
   *    - Insert into ecommerce_mall_product_snapshots with current values
   *    - Include product_id, captured_at timestamp, name, description, category_id, base_price
   * 10. Update the product record in ecommerce_mall_products with new values
   * 11. Update updated_at timestamp to current time
   * 12. Return the updated product entity
   *
   * **Transaction Handling**:
   * - Use database transaction to ensure snapshot creation and update are atomic
   * - Rollback on any validation failure or database error
   *
   * **Error Handling**:
   * - 404: Product not found or soft deleted
   * - 403: Seller doesn't own the product or registration pending/rejected
   * - 400: Invalid category_id, name already exists in category, or validation errors
   * - 409: Concurrent modification detected
   *
   * **Related Operations**:
   * - GET /products/{productId} - Retrieve current product state
   * - GET /products/{productId}/snapshots - View edit history
   * - PATCH /products - Search products with filters
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put()
  public async update(
    @AdminAuth()
    admin: AdminPayload,
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IEcommerceMallProduct.IUpdate,
  ): Promise<IEcommerceMallProduct> {
    try {
      return await putEcommerceMallAdminProductsProductId({
        admin,
        productId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Permanently delete a product and all its associated data from the platform.
   *
   * This operation allows sellers to remove their own products from active listings. Deletion is only permitted when there are no blocking conditions that would affect ongoing transactions or customer orders.
   *
   * Before allowing deletion, the system validates:
   * 1. The requesting user is the product owner (seller)
   * 2. No order items with status "paid" or "shipped" exist for any variant of this product
   * 3. No pending cancellation requests exist for any order item of this product
   * 4. No pending refund requests exist for any order item of this product
   *
   * If any blocking conditions exist, the deletion is rejected with an appropriate error message explaining which orders or requests are preventing deletion.
   *
   * When deletion is permitted, the operation performs cascade removal:
   * - The product record is soft-deleted (deleted_at timestamp set)
   * - All product variants are soft-deleted
   * - All inventory records for those variants are removed
   * - All product images are dissociated
   * - The product no longer appears in search results or category listings
   *
   * This operation is restricted to the product owner (seller). Administrators can delete any product using a separate admin endpoint.
   *
   * The deleted product and its data are preserved in the database for historical order records and legal compliance purposes. Snapshots of the product state remain accessible for dispute resolution.
   *
   * @param connection
   * @param productId Target product's ID
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor admin
   * @x-autobe-specification Implement product deletion with blocking validation:
   *
   * 1. Authentication: Verify JWT token with seller role
   *
   * 2. Authorization checks:
   *    - Query ecommerce_mall_products by productId
   *    - Verify product.seller_id matches current session seller_id
   *    - Return 403 Forbidden if not owner
   *    - Return 404 Not Found if product already deleted (deleted_at IS NOT NULL)
   *
   * 3. Blocking condition validation:
   *    - Query ecommerce_mall_order_items where product_id = productId AND status IN ('paid', 'shipped')
   *    - Query ecommerce_mall_cancellation_requests joined with order_items where product_id = productId AND status = 'pending'
   *    - Query ecommerce_mall_refund_requests joined with order_items where product_id = productId AND status = 'pending'
   *    - If any records found, return 409 Conflict with specific error message indicating which blocking orders or requests exist
   *
   * 4. Cascade deletion in transaction:
   *    - UPDATE ecommerce_mall_products SET deleted_at = NOW() WHERE id = productId
   *    - UPDATE ecommerce_mall_product_variants SET deleted_at = NOW() WHERE product_id = productId
   *    - DELETE FROM ecommerce_mall_inventory_records WHERE variant_id IN (SELECT id FROM ecommerce_mall_product_variants WHERE product_id = productId)
   *    - DELETE FROM ecommerce_mall_product_images WHERE product_id = productId (or set null if snapshot preservation needed)
   *
   * 5. Side effects:
   *    - Wishlist items referencing this product are automatically removed via cascade (if configured) or become orphaned
   *    - Cart items with this product's variants become unavailable
   *
   * 6. Return 204 No Content on successful deletion
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete()
  public async erase(
    @AdminAuth()
    admin: AdminPayload,
    @TypedParam("productId")
    productId: string,
  ): Promise<void> {
    try {
      return await deleteEcommerceMallAdminProductsProductId({
        admin,
        productId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
