import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallPaymentTransaction } from "../../../../../structures/IShoppingMallPaymentTransaction";
import { IPageIShoppingMallPaymentTransaction } from "../../../../../structures/IPageIShoppingMallPaymentTransaction";

/**
 * Retrieve a filtered and paginated list of payment transactions associated
 * with a specific order in the shopping mall system. This operation provides
 * advanced search capabilities for finding payment transactions based on
 * multiple criteria including transaction status, payment method type,
 * transaction date ranges, amount ranges, and payment gateway responses.
 *
 * The operation supports comprehensive pagination with configurable page sizes
 * and sorting options. Users can sort payment transactions by transaction date,
 * amount, status, or other relevant fields in ascending or descending order.
 * This is particularly useful for buyers reviewing their payment history,
 * sellers tracking received payments, and administrators monitoring payment
 * system health.
 *
 * Security considerations include ensuring that only authorized actors can
 * access payment transaction details. Buyers can only view transactions for
 * their own orders, sellers can view transactions related to their order
 * portions, and administrators have full access for dispute resolution and
 * financial auditing. Sensitive payment information such as full card numbers
 * or bank account details are masked in the response, showing only the last 4
 * digits or partial information as required by PCI compliance standards.
 *
 * This operation integrates with the shopping_mall_payment_transactions table
 * as defined in the Prisma schema, along with related entities such as
 * shopping_mall_orders, shopping_mall_payment_methods, and
 * shopping_mall_buyers. The response includes payment transaction summary
 * information optimized for list displays, with support for including
 * additional transaction details based on authorization level and business
 * requirements.
 *
 * @param props.connection
 * @param props.orderId Unique identifier of the target order (global scope)
 * @param props.body Search criteria and pagination parameters for filtering
 *   payment transactions within the specified order
 * @path /shoppingMall/seller/orders/:orderId/paymentTransactions
 * @accessor api.functional.shoppingMall.seller.orders.paymentTransactions.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Unique identifier of the target order (global scope) */
    orderId: string & tags.Format<"uuid">;

    /**
     * Search criteria and pagination parameters for filtering payment
     * transactions within the specified order
     */
    body: IShoppingMallPaymentTransaction.IRequest;
  };
  export type Body = IShoppingMallPaymentTransaction.IRequest;
  export type Response = IPageIShoppingMallPaymentTransaction.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/orders/:orderId/paymentTransactions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/seller/orders/${encodeURIComponent(props.orderId ?? "null")}/paymentTransactions`;
  export const random = (): IPageIShoppingMallPaymentTransaction.ISummary =>
    typia.random<IPageIShoppingMallPaymentTransaction.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
