import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IPageIShoppingMallWishlistItem } from "../../../../structures/IPageIShoppingMallWishlistItem";
import { IShoppingMallWishlistItem } from "../../../../structures/IShoppingMallWishlistItem";

export * as snapshots from "./snapshots/index";

/**
 * Retrieve a specific entry from a customer's wishlist. This operation queries the wishlist item database record corresponding to the unique wishlistItemId and returns the product details associated with that entry, providing essential information like product name, description, and image URL.
 *
 * The operation strictly follows the customer's wishlist data structure. It returns only the necessary product summary information without variant details (as per business requirement: 'wishlist entries linking customers to products without variant specificity'). This ensures optimal performance for frequent wishlist access while maintaining data efficiency.
 *
 * Security: The operation validates that the requesting user is the owner of the wishlist item. Any attempt to access another customer's wishlist item results in HTTP 404 Not Found (preventing data leakage). The response includes only the product's basic information, preserving the platform's snapshot policy of not exposing deleted product details.
 *
 * @param props.connection
 * @param props.wishlistItemId Unique identifier of the wishlist item to retrieve
 * @x-autobe-specification Query shopping_mall_wishlist_items table to find the specific wishlist item by wishlistItemId. Join with shopping_mall_products to fetch product name, description, and image URL for display. Enforce authorization that customer can only access their own wishlist items. Return only essential product information - not full product details. Cache response for 15 seconds for frequent access items as per typical wishlist usage patterns.
 * @path /shoppingMall/customer/wishlist/:wishlistItemId
 * @accessor api.functional.shoppingMall.customer.wishlist.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the wishlist item to retrieve
     */
    wishlistItemId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallWishlistItem.ISummary;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/wishlist/:wishlistItemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/wishlist/${encodeURIComponent(props.wishlistItemId ?? "null")}`;
  export const random = (): IShoppingMallWishlistItem.ISummary =>
    typia.random<IShoppingMallWishlistItem.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("wishlistItemId")(() => typia.assert(props.wishlistItemId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update a customer's wishlist item with new details. This operation modifies specific fields of an existing wishlist item in the system, allowing customers to update their wishlist entries without needing to remove and recreate them.
 *
 * The operation validates that the wishlist item belongs to the current authenticated user, ensuring data privacy and security. Only the fields explicitly included in the request body are updated.
 *
 * The updated data is automatically timestamped with the latest update time. The operation preserves all other wishlist item fields in their current state, preventing accidental data loss.
 *
 * This endpoint supports modifying wishlist items to change product variants or other relevant properties, providing a dynamic way for customers to manage their shopping preferences.
 *
 * The database schema for shopping_mall_wishlist_items defines the available fields, and updates will only be authorized on fields defined in this schema.
 *
 * @param props.connection
 * @param props.wishlistItemId The unique identifier of the wishlist item to update
 * @param props.body Fields to update in the wishlist item
 * @x-autobe-specification Validate wishlist item exists and belongs to current user. Update only fields provided in request body. Ensure product reference is valid. Update the last_updated timestamp automatically. Apply appropriate authorization rules from endpoint agent.
 *
 * Implementation: Use Prisma to find wishlist item by ID and current user. Update provided fields. Return the updated entity with all fields including generated timestamps.
 * @path /shoppingMall/customer/wishlist/:wishlistItemId
 * @accessor api.functional.shoppingMall.customer.wishlist.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * The unique identifier of the wishlist item to update
     */
    wishlistItemId: string & tags.Format<"uuid">;

    /**
     * Fields to update in the wishlist item
     */
    body: IShoppingMallWishlistItem.IUpdate;
  };
  export type Body = IShoppingMallWishlistItem.IUpdate;
  export type Response = IShoppingMallWishlistItem;

  export const METADATA = {
    method: "PUT",
    path: "/shoppingMall/customer/wishlist/:wishlistItemId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/wishlist/${encodeURIComponent(props.wishlistItemId ?? "null")}`;
  export const random = (): IShoppingMallWishlistItem =>
    typia.random<IShoppingMallWishlistItem>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("wishlistItemId")(() => typia.assert(props.wishlistItemId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete a wishlist item from the customer's wishlist.
 *
 * This operation allows authenticated customers to remove items from their wishlist. The wishlist item is identified using the wishlistItemId parameter, and the operation permanently removes the association between the customer and the product in the wishlist.
 *
 * The system automatically handles the wishlist item removal and updates the customer's wishlist count in real-time. No request body is required as this operation is triggered solely by the wishlistItemId parameter.
 *
 * Security considerations include verifying that the wishlist item belongs to the currently authenticated customer. If the item doesn't exist or belongs to a different user, the operation returns HTTP 404 Not Found or HTTP 403 Forbidden with appropriate error code.
 *
 * This operation directly corresponds to the wishlist functionality described in section 6 of the business requirements document, which details customer wishlist management requirements.
 *
 * @param props.connection
 * @param props.wishlistItemId Unique identifier of the wishlist item to be deleted
 * @x-autobe-specification Delete a wishlist item from the shopping_mall_wishlist_items table. Verify the wishlist item exists and belongs to the authenticated user. Perform the deletion using Prisma's delete method with the specified wishlistItemId. Handle cases where the item doesn't exist or belongs to a different user with appropriate error codes.
 * @path /shoppingMall/customer/wishlist/:wishlistItemId
 * @accessor api.functional.shoppingMall.customer.wishlist.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * Unique identifier of the wishlist item to be deleted
     */
    wishlistItemId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/shoppingMall/customer/wishlist/:wishlistItemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/wishlist/${encodeURIComponent(props.wishlistItemId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("wishlistItemId")(() => typia.assert(props.wishlistItemId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Create a new wishlist item adding a product to the customer's wishlist without specifying variants. This operation creates a new wishlist item entry linking the current customer to a product in the catalog.
 *
 * The system automatically preserves product details (name, image, price) at the time of addition, allowing users to track products even if catalog details change later. The wishlist is managed at the customer level, and multiple wishlist entries for the same product are allowed within the same customer account.
 *
 * Security considerations: Only authenticated customers can add to their own wishlist. The API applies rate limiting to prevent abuse (10 requests per minute per user). The operation validates the product ID against active products in the catalog before creating a wishlist entry.
 *
 * This operation follows business rules that specifically state: 'WHEN a customer adds a product to wishlist, THE system SHALL: Store product ID without variant specificity; Allow multiple wishlist entries; Update wishlist count in real-time; Preserve product image and basic info.'
 *
 * The operation is designed to return minimal relevant product information for immediate UI update while preserving the catalog details at the time of wishlist addition.
 *
 * @param props.connection
 * @param props.body Product details to add to the wishlist
 * @x-autobe-specification Retrieve the current user from the authenticated session. Check if the product ID exists in the product catalog with valid status. Create a new wishlist item entry with the product ID and current user ID. Verify uniqueness of product-wishlist relationship for the user. Update the wishlist count for the user in real-time. Return the created wishlist item with product details for immediate UI update. The wishlist item should include product ID, product name, product image URL, and current price. Apply rate limiting of 10 requests per minute per user to prevent abuse.
 * @path /shoppingMall/customer/wishlist
 * @accessor api.functional.shoppingMall.customer.wishlist.add
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function add(
  connection: IConnection,
  props: add.Props,
): Promise<add.Response> {
  return true === connection.simulate
    ? add.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...add.METADATA,
          path: add.path(),
          status: null,
        },
        props.body,
      );
}
export namespace add {
  export type Props = {
    /**
     * Product details to add to the wishlist
     */
    body: IShoppingMallWishlistItem.ICreate;
  };
  export type Body = IShoppingMallWishlistItem.ICreate;
  export type Response = IShoppingMallWishlistItem;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/customer/wishlist",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/wishlist";
  export const random = (): IShoppingMallWishlistItem =>
    typia.random<IShoppingMallWishlistItem>();
  export const simulate = (
    connection: IConnection,
    props: add.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: add.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a paginated list of items currently stored in the customer's wishlist. This operation provides the customer with their wishlist contents with basic product information for display to UI components. Each wishlist item in the response includes the product ID, name, and basic pricing information, allowing the UI to display product details without requiring additional API calls.
 *
 * The implementation uses the shopping_mall_wishlist_items database table which stores the customer-wishlist-product relationships. This endpoint automatically filters results to only the currently authenticated customer's wishlist, ensuring strict user data isolation. The response format uses IPageIShoppingMallWishlistItem.ISummary to provide optimized data for list display with minimal fields per the requirements.
 *
 * Security and privacy considerations: Only the current user's wishlist items are accessible. The endpoint enforces authentication and prevents any cross-user data access. The implementation does not include variant-specific information since the requirements specifically state to 'store product ID without variant specificity' per the 00-toc.md business requirements.
 *
 * @param props.connection
 * @param props.body Filter, sort, and pagination parameters for wishlist items
 * @x-autobe-specification Fetch customer wishlist items from shopping_mall_wishlist_items table using cursor-based pagination. Retrieve product details through joins with shopping_mall_products table. Filter records by current customer ID from authentication token. Cache results for 5 minutes with user-specific cache keys.
 * @path /shoppingMall/customer/wishlist
 * @accessor api.functional.shoppingMall.customer.wishlist.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Filter, sort, and pagination parameters for wishlist items
     */
    body: IShoppingMallWishlistItem.IRequest;
  };
  export type Body = IShoppingMallWishlistItem.IRequest;
  export type Response = IPageIShoppingMallWishlistItem.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/customer/wishlist",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/wishlist";
  export const random = (): IPageIShoppingMallWishlistItem.ISummary =>
    typia.random<IPageIShoppingMallWishlistItem.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
