import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ITodoAppUser } from "../../../../structures/ITodoAppUser";
import { IPageITodoAppUser } from "../../../../structures/IPageITodoAppUser";
export * as roles from "./roles/index";

/**
 * Retrieve a filtered and paginated list of todoApp users. This operation
 * supports searching users based on various criteria such as username, email,
 * registration date, and status.
 *
 * The todo_app_users table represents registered users in the todoApp system,
 * storing personal and authentication-related information.
 *
 * Security considerations ensure that users can only access appropriately
 * authorized information, protecting sensitive data. Pagination and sorting
 * options enhance usability and performance when dealing with large user
 * datasets.
 *
 * This endpoint is crucial for user management, administrative overview, or
 * social features relying on user data aggregation.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for user
 *   filtering
 * @path /todoApp/user/users
 * @accessor api.functional.todoApp.user.users.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Search criteria and pagination parameters for user filtering */
    body: ITodoAppUser.IRequest;
  };
  export type Body = ITodoAppUser.IRequest;
  export type Response = IPageITodoAppUser.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/todoApp/user/users",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/todoApp/user/users";
  export const random = (): IPageITodoAppUser.ISummary =>
    typia.random<IPageITodoAppUser.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information of a specific user in the todoApp system by
 * their unique user ID.
 *
 * This operation directly accesses the todo_app_users database table that
 * stores user account and profile information. The user is identified uniquely
 * by a UUID passed in the path parameter.
 *
 * Security: Access to this endpoint is restricted to authenticated users to
 * protect private information. The authorization is enforced for the actor role
 * 'user'.
 *
 * This retrieval operation supports the client UI and administrative tools
 * requiring user details for profile viewing, account management, or support
 * purposes.
 *
 * This endpoint does not accept a request body as it is used purely for data
 * retrieval.
 *
 * Related operations: POST /users to create users, PATCH /users for searching
 * users, PUT /users/{userId} for updates, DELETE /users/{userId} for removals.
 *
 * @param props.connection
 * @param props.userId Unique identifier of the target user
 * @path /todoApp/user/users/:userId
 * @accessor api.functional.todoApp.user.users.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the target user */
    userId: string & tags.Format<"uuid">;
  };
  export type Response = ITodoAppUser;

  export const METADATA = {
    method: "GET",
    path: "/todoApp/user/users/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/todoApp/user/users/${encodeURIComponent(props.userId ?? "null")}`;
  export const random = (): ITodoAppUser => typia.random<ITodoAppUser>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("userId")(() => typia.assert(props.userId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update the specified user account identified by the userId parameter. This
 * operation allows an authenticated user to modify their own account
 * information. The todo_app_users table stores all user data, including
 * credentials, profile details, and account status.
 *
 * This operation requires the user to be authenticated as the owner of the
 * account to ensure data privacy and security. The update replaces existing
 * user information with the submitted payload, respecting all schema
 * validations. Proper error handling will address cases of invalid data or
 * unauthorized access.
 *
 * Related operations: GET /users/{userId} to retrieve user details, PATCH
 * /users to search users, DELETE /users/{userId} to delete a user account.
 *
 * @param props.connection
 * @param props.userId Unique identifier of the user to update
 * @param props.body User account update payload conforming to
 *   ITodoAppUser.IUpdate schema
 * @path /todoApp/user/users/:userId
 * @accessor api.functional.todoApp.user.users.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique identifier of the user to update */
    userId: string & tags.Format<"uuid">;

    /** User account update payload conforming to ITodoAppUser.IUpdate schema */
    body: ITodoAppUser.IUpdate;
  };
  export type Body = ITodoAppUser.IUpdate;
  export type Response = ITodoAppUser;

  export const METADATA = {
    method: "PUT",
    path: "/todoApp/user/users/:userId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/todoApp/user/users/${encodeURIComponent(props.userId ?? "null")}`;
  export const random = (): ITodoAppUser => typia.random<ITodoAppUser>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("userId")(() => typia.assert(props.userId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * This operation permanently deletes a user record from the todo_app_users
 * table in the todoApp database. The userId parameter, a UUID, specifies the
 * target user to be removed.
 *
 * Only authenticated users (authorizationActors: ["user"]) are permitted to
 * perform this action, ensuring that deletion rights are controlled.
 *
 * Upon successful deletion, the user record is irrevocably removed, with no
 * response content returned, conforming to REST standards.
 *
 * Security considerations include validation of the userId parameter and
 * authentication enforcement to prevent unauthorized deletions.
 *
 * @param props.connection
 * @param props.userId Unique identifier of the target user account
 * @path /todoApp/user/users/:userId
 * @accessor api.functional.todoApp.user.users.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the target user account */
    userId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/todoApp/user/users/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/todoApp/user/users/${encodeURIComponent(props.userId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("userId")(() => typia.assert(props.userId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
