import { TypedBody, TypedRoute } from "@nestia/core";
import { Controller, Ip } from "@nestjs/common";
import typia from "typia";

import { IEconomyPoliticsBoardSuperAdmin } from "../../../../api/structures/IEconomyPoliticsBoardSuperAdmin";
import { postEconomyPoliticsBoardAuthSuperAdminJoin } from "../../../../providers/postEconomyPoliticsBoardAuthSuperAdminJoin";
import { postEconomyPoliticsBoardAuthSuperAdminLogin } from "../../../../providers/postEconomyPoliticsBoardAuthSuperAdminLogin";
import { postEconomyPoliticsBoardAuthSuperAdminRefresh } from "../../../../providers/postEconomyPoliticsBoardAuthSuperAdminRefresh";

@Controller("/economyPoliticsBoard/auth/superAdmin")
export class EconomypoliticsboardAuthSuperadminController {
  /**
   * The join operation creates a new super administrator account.
   *
   * This endpoint handles new super administrator registration by creating a new user record in the database. The user provides a valid email address and password, which are verified against schema validation rules before processing. The email must match standard email format requirements to be accepted (validated by schema's string format), and the password must meet security requirements including minimum length and complexity (validated by business logic).
   *
   * When processing the registration request, the system performs:
   * - Email format validation (using database schema's email format)
   * - Password strength validation (minimum 8 characters, alphanumeric, special characters)
   * - Account creation with the current timestamp
   * - Password hashing using secure industry standards with salting
   *
   * After successful registration, the account is immediately available for login (deleted_at remains null, indicating active account). This operation requires a POST request with the IJoin DTO containing the email and password.
   *
   * The join operation does not require any prerequisites as it creates a new resource (super admin), not modifying an existing one.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Registration data for creating a new super administrator account
   * @x-autobe-authorization-type join
   * @x-autobe-authorization-actor superAdmin
   * @x-autobe-specification Implementation specification for user registration workflow. This operation handles new super admin account creation with mandatory email and password validation against schema requirements. Verifies email format validity and password security requirements through the database schema validation rules. The email must match the standard format as defined in the database schema. Password hashing follows industry standards with salting for secure storage. New accounts are created with initial timestamps and active status (deleted_at is null).
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("join")
  public async join(
    @Ip()
    ip: string,
    @TypedBody()
    body: IEconomyPoliticsBoardSuperAdmin.IJoin,
  ): Promise<IEconomyPoliticsBoardSuperAdmin.IAuthorized> {
    try {
      return await postEconomyPoliticsBoardAuthSuperAdminJoin({
        ip,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * The login operation authenticates a super administrator account.
   *
   * This endpoint validates user credentials for super administrator login. The user submits an email and password, which are verified against the database records. The system first checks if an account exists with the provided email address, then compares the supplied password (hashed and salted) against the stored password hash in the database schema.
   *
   * The authentication process involves:
   * - Database lookup by email (verified via schema's unique email constraint)
   * - Password verification with secure hashing and salting
   * - Account status check (ensuring deleted_at is null for active accounts)
   * - Token generation using JWT with proper claims
   * - Session management with expiration times
   *
   * Successful login provides a token for access to protected resources. Login attempts are tracked with a maximum of 5 failures before a 15-minute lockout, as defined in the business requirements.
   *
   * This operation requires a POST request with the ILogin DTO containing the email and password. It does not have any prerequisites as it directly authenticates an existing account.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Authentication credentials for logging into an existing super administrator account
   * @x-autobe-authorization-type login
   * @x-autobe-authorization-actor superAdmin
   * @x-autobe-specification Implementation specification for user login workflow. Validates credentials against secure password hashes stored in database. The operation queries account by email, verifies password hash, and generates JWT tokens following schema storage conventions. Checks for account lockouts after failed attempts per business rules.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("login")
  public async login(
    @Ip()
    ip: string,
    @TypedBody()
    body: IEconomyPoliticsBoardSuperAdmin.ILogin,
  ): Promise<IEconomyPoliticsBoardSuperAdmin.IAuthorized> {
    try {
      return await postEconomyPoliticsBoardAuthSuperAdminLogin({
        ip,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * The refresh operation regenerates access tokens for an authenticated super administrator.
   *
   * This endpoint allows users to obtain a new access token when the current one is about to expire, without requiring re-authentication. It accepts a refresh token (obtained during login) and verifies its validity against database session records.
   *
   * The refresh process involves:
   * - Validating the refresh token against the session records
   * - Ensuring the token has not expired
   * - Generating a new access token with a fresh expiration
   * - Maintaining the existing authenticated session
   * - Preventing token reuse for security
   *
   * This operation is critical for maintaining seamless access to the application without frequent re-authentication. The refresh token system provides a balance between security and user experience, allowing continuous access with minimal interruption.
   *
   * The operation uses a POST request with the IRefresh DTO containing the refresh token. It has no prerequisites as it operates on a valid session context that exists after successful authentication.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Refresh token data for regenerating access tokens
   * @x-autobe-authorization-type refresh
   * @x-autobe-authorization-actor superAdmin
   * @x-autobe-specification Implementation specification for token refresh workflow. Validates existing expiration tokens and generates new access tokens without requiring new credentials. This operation uses the JWT refresh token structure for security and manages token expiration times as specified in project requirements.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("refresh")
  public async refresh(
    @TypedBody()
    body: IEconomyPoliticsBoardSuperAdmin.IRefresh,
  ): Promise<IEconomyPoliticsBoardSuperAdmin.IAuthorized> {
    try {
      return await postEconomyPoliticsBoardAuthSuperAdminRefresh({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
