import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallCartItem } from "../../../../../structures/IShoppingMallCartItem";
import { IPageIShoppingMallCartItem } from "../../../../../structures/IPageIShoppingMallCartItem";

/**
 * Create a new cart item (SKU) in the shopping_mall_cart_items table for a
 * specified cart.
 *
 * Add a new SKU to the customer's shopping cart, specifying both the target SKU
 * and desired quantity.
 *
 * This operation uses the 'shopping_mall_cart_items' Prisma entity and enforces
 * the unique SKU-per-cart constraint by using a composite unique index (cart
 * ID, SKU ID). The request body must specify the SKU and quantity to be added.
 * On successful addition, the newly created cart item is returned, including
 * all related fields such as quantity and SKU associations.
 *
 * Validation is performed to block duplicate SKUs within the same cart and to
 * reject requests exceeding available inventory. The operation is only
 * accessible by authenticated customers and validates both cart ownership and
 * SKU eligibility before proceeding. Related operations include updating a cart
 * item's quantity and removing items from the cart. Any attempt to bypass
 * platform limits triggers validation errors with appropriate feedback to the
 * user.
 *
 * @param props.connection
 * @param props.cartId Unique identifier of the target cart (UUID format). Used
 *   for ownership and item creation context.
 * @param props.body SKU and quantity for the new cart item being added. Must
 *   specify a valid SKU in the catalog and a quantity within allowed stock.
 * @path /shoppingMall/customer/carts/:cartId/items
 * @accessor api.functional.shoppingMall.customer.carts.items.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Unique identifier of the target cart (UUID format). Used for
     * ownership and item creation context.
     */
    cartId: string & tags.Format<"uuid">;

    /**
     * SKU and quantity for the new cart item being added. Must specify a
     * valid SKU in the catalog and a quantity within allowed stock.
     */
    body: IShoppingMallCartItem.ICreate;
  };
  export type Body = IShoppingMallCartItem.ICreate;
  export type Response = IShoppingMallCartItem;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/customer/carts/:cartId/items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/carts/${encodeURIComponent(props.cartId ?? "null")}/items`;
  export const random = (): IShoppingMallCartItem =>
    typia.random<IShoppingMallCartItem>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartId")(() => typia.assert(props.cartId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Search and paginate items in a specific shopping cart
 * (shopping_mall_cart_items).
 *
 * Retrieve a filtered, paginated list of items for a given shopping cart.
 *
 * This operation is designed for the shopping_mall_cart_items subsidiary table,
 * listing all SKU records associated with a specific cart as identified by
 * cartId. It supports flexible querying, including search, filtering by SKU,
 * quantity constraints, and sorting options (e.g., by most recently updated).
 *
 * The relationship between shopping_mall_cart_items and shopping_mall_carts is
 * enforced, so only items belonging to the specified cartId are returned.
 * Business logic ensures each SKU appears only once per cart (composite
 * unique), and information about each item includes quantity and inventory
 * validation context.
 *
 * Pagination logic enables efficient navigation through large numbers of cart
 * items, with controls for page size and sort order. Security permissions
 * ensure only the cart owner or authorized actors may access the full item
 * list. This endpoint is typically used for cart views, checkout preparation,
 * and client-side cart management flows.
 *
 * @param props.connection
 * @param props.cartId Unique identifier of the shopping cart whose items are
 *   being queried. (UUID format)
 * @param props.body Filtering and pagination parameters for querying shopping
 *   cart items.
 * @path /shoppingMall/customer/carts/:cartId/items
 * @accessor api.functional.shoppingMall.customer.carts.items.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Unique identifier of the shopping cart whose items are being queried.
     * (UUID format)
     */
    cartId: string & tags.Format<"uuid">;

    /** Filtering and pagination parameters for querying shopping cart items. */
    body: IShoppingMallCartItem.IRequest;
  };
  export type Body = IShoppingMallCartItem.IRequest;
  export type Response = IPageIShoppingMallCartItem.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/customer/carts/:cartId/items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/carts/${encodeURIComponent(props.cartId ?? "null")}/items`;
  export const random = (): IPageIShoppingMallCartItem.ISummary =>
    typia.random<IPageIShoppingMallCartItem.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartId")(() => typia.assert(props.cartId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a single cart item from the shopping_mall_cart_items table by cart
 * and item ID.
 *
 * Retrieve a single item from a customer's shopping cart by its unique ID.
 *
 * This operation ensures users can view specific items within their own cart by
 * referencing both the cart ID and the item ID. Only authenticated customers
 * with access to the referenced cart are permitted to access item details,
 * maintaining strict cart ownership boundaries. Relevant information from the
 * 'shopping_mall_cart_items' Prisma model, such as quantity, SKU, creation, and
 * update times, is included in the response.
 *
 * Security is enforced by verifying cart ownership, blocking access for
 * non-owners or unauthorized users. Related operations include listing all
 * items in a cart and updating or removing specific cart items by their
 * identifiers. Errors such as "not found" or "forbidden" are handled according
 * to platform security policies and standard API practices.
 *
 * @param props.connection
 * @param props.cartId Unique identifier of the target cart (UUID format). Used
 *   for cart ownership and lookup.
 * @param props.itemId Unique identifier of the cart item (UUID format). Used to
 *   identify the specific item within the cart.
 * @path /shoppingMall/customer/carts/:cartId/items/:itemId
 * @accessor api.functional.shoppingMall.customer.carts.items.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the target cart (UUID format). Used for cart
     * ownership and lookup.
     */
    cartId: string & tags.Format<"uuid">;

    /**
     * Unique identifier of the cart item (UUID format). Used to identify
     * the specific item within the cart.
     */
    itemId: string & tags.Format<"uuid">;
  };
  export type Response = IShoppingMallCartItem;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/carts/:cartId/items/:itemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/carts/${encodeURIComponent(props.cartId ?? "null")}/items/${encodeURIComponent(props.itemId ?? "null")}`;
  export const random = (): IShoppingMallCartItem =>
    typia.random<IShoppingMallCartItem>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartId")(() => typia.assert(props.cartId));
      assert.param("itemId")(() => typia.assert(props.itemId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing shopping cart item (shopping_mall_cart_items) by itemId
 * within a specific cart.
 *
 * Update the details of a specific item in a customer's shopping cart
 * identified by its itemId. This operation enables modification of key cart
 * item properties, primarily the desired quantity, while ensuring inventory
 * constraints are enforced. The operation takes the cartId and itemId as path
 * parameters; these uniquely identify the cart and the item to update.
 *
 * User authentication is required; only the owner of the cart is allowed to
 * update its items. Inventory rules, such as the maximum allowed quantity (not
 * exceeding in-stock inventory), are validated during this operation. If the
 * updated quantity is zero, the client should use the DELETE endpoint instead
 * to remove the item. If the desired quantity exceeds current availability, the
 * request will be rejected. This operation is designed for efficient updating
 * of cart contents in all shopping and checkout flows.
 *
 * The endpoint operates over the shopping_mall_cart_items table, which is
 * subsidiary to the shopping_mall_carts table. Data integrity constraints
 * ensure only one cart item per SKU per cart is allowed; thus, itemId must
 * reference a unique cart item within the context of its parent cart. Related
 * operations include creation (POST to /carts/{cartId}/items), retrieval (GET),
 * and deletion (DELETE).
 *
 * @param props.connection
 * @param props.cartId Unique identifier of the shopping cart containing the
 *   target item.
 * @param props.itemId Unique identifier of the cart item to update.
 * @param props.body Fields for updating the cart item, such as new desired
 *   quantity.
 * @path /shoppingMall/customer/carts/:cartId/items/:itemId
 * @accessor api.functional.shoppingMall.customer.carts.items.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique identifier of the shopping cart containing the target item. */
    cartId: string & tags.Format<"uuid">;

    /** Unique identifier of the cart item to update. */
    itemId: string & tags.Format<"uuid">;

    /** Fields for updating the cart item, such as new desired quantity. */
    body: IShoppingMallCartItem.IUpdate;
  };
  export type Body = IShoppingMallCartItem.IUpdate;
  export type Response = IShoppingMallCartItem;

  export const METADATA = {
    method: "PUT",
    path: "/shoppingMall/customer/carts/:cartId/items/:itemId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/shoppingMall/customer/carts/${encodeURIComponent(props.cartId ?? "null")}/items/${encodeURIComponent(props.itemId ?? "null")}`;
  export const random = (): IShoppingMallCartItem =>
    typia.random<IShoppingMallCartItem>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartId")(() => typia.assert(props.cartId));
      assert.param("itemId")(() => typia.assert(props.itemId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Remove an item from a shopping cart (shopping_mall_cart_items) by itemId
 * within a specified cart.
 *
 * Remove a specific item from a customer's shopping cart by its itemId. This
 * operation is used when a user decides to no longer purchase a specific SKU in
 * their cart, immediately and permanently removing the item record from both
 * the user's cart and the shopping_mall_cart_items table.
 *
 * Only the owner of the shopping cart may remove items from their cart through
 * this endpoint. The operation ensures that child cart_items are deleted only
 * within the context of the currently authenticated user's cart, ensuring no
 * cross-user access is possible. Inventory is not adjusted until checkout, but
 * removing an item will reflect immediately in all cart read operations.
 *
 * Validation includes verifying ownership and correct association between the
 * cartId and itemId (the item must be part of the given cart). Related
 * operations include item creation (POST to /carts/{cartId}/items), list/detail
 * retrieval, and update (PUT).
 *
 * @param props.connection
 * @param props.cartId Unique identifier of the shopping cart containing the
 *   item.
 * @param props.itemId Unique identifier of the cart item to remove.
 * @path /shoppingMall/customer/carts/:cartId/items/:itemId
 * @accessor api.functional.shoppingMall.customer.carts.items.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the shopping cart containing the item. */
    cartId: string & tags.Format<"uuid">;

    /** Unique identifier of the cart item to remove. */
    itemId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/shoppingMall/customer/carts/:cartId/items/:itemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/shoppingMall/customer/carts/${encodeURIComponent(props.cartId ?? "null")}/items/${encodeURIComponent(props.itemId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("cartId")(() => typia.assert(props.cartId));
      assert.param("itemId")(() => typia.assert(props.itemId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
