import { TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IECommerceMallOrderItem } from "../../../../../api/structures/IECommerceMallOrderItem";
import { AdministratorAuth } from "../../../../../decorators/AdministratorAuth";
import { AdministratorPayload } from "../../../../../decorators/payload/AdministratorPayload";
import { postECommerceMallAdministratorOrderItemsItemIdForceCancel } from "../../../../../providers/postECommerceMallAdministratorOrderItemsItemIdForceCancel";

@Controller("/eCommerceMall/administrator/order-items/:itemId/force-cancel")
export class EcommercemallAdministratorOrder_itemsForce_cancelController {
  /**
   * Force-cancel an individual order item by administrator authority.
   *
   * Administrators can force-cancel any order item on the platform for policy violations, dispute resolution, or other administrative reasons. This action bypasses the normal cancellation request workflow — no seller approval is required.
   *
   * When a force-cancel is executed: the target order item's status transitions to 'cancelled', the customer is refunded for that item (financial reversal), and the product variant's stock quantity is restored via an inventory record with reason 'force-cancelled'. A status log entry is automatically created recording the transition with reason 'administrator_force_cancel' for complete audit trail purposes.
   *
   * @param connection
   * @param itemId UUID of the order item to force-cancel. Identifies a specific purchased product variant line item within a customer order.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor administrator
   * @x-autobe-specification 1. Lookup the order item by {itemId} in e_commerce_mall_order_items. If not found, reject with 404 Not Found.
   * 2. Verify the order item's current status. Force-cancel should only apply to items in non-terminal, non-cancelled states. If already 'cancelled' or 'refunded', reject with 409 Conflict explaining the item is already in a terminal state.
   * 3. Begin a database transaction:
   *    a. Update the order item's status to 'cancelled' in e_commerce_mall_order_items.
   *    b. Insert a status log entry in e_commerce_mall_order_item_status_logs with: from_status = current status, to_status = 'cancelled', reason = 'administrator_force_cancel'.
   *    c. Create an inventory record in e_commerce_mall_inventory_records on the associated product variant (e_commerce_mall_product_variant_id) with: quantity_change = +quantity (restoring the purchased quantity), reason = 'force-cancelled'.
   *    d. Process the financial refund (external payment gateway integration or internal credit system — implementation dependent).
   * 4. Commit the transaction. If any step fails, roll back all changes and reject with 500 Internal Server Error.
   *
   * Edge cases:
   * - Item already cancelled/refunded: reject with 409 Conflict.
   * - Item not found: reject with 404 Not Found.
   * - Transaction failure: full rollback, return 500 Internal Server Error.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async forceCancel(
    @AdministratorAuth()
    administrator: AdministratorPayload,
    @TypedParam("itemId")
    itemId: string & tags.Format<"uuid">,
  ): Promise<IECommerceMallOrderItem> {
    try {
      return await postECommerceMallAdministratorOrderItemsItemIdForceCancel({
        administrator,
        itemId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
