import { Module } from "@nestjs/common";

import { AuthUserController } from "./controllers/auth/user/AuthUserController";
import { AuthModeratorController } from "./controllers/auth/moderator/AuthModeratorController";
import { AuthAdministratorController } from "./controllers/auth/administrator/AuthAdministratorController";
import { CommunityplatformAdministratorSystemsettingsController } from "./controllers/communityPlatform/administrator/systemSettings/CommunityplatformAdministratorSystemsettingsController";
import { CommunityplatformAdministratorFeatureflagsController } from "./controllers/communityPlatform/administrator/featureFlags/CommunityplatformAdministratorFeatureflagsController";
import { CommunityplatformAdministratorEnvironmentsController } from "./controllers/communityPlatform/administrator/environments/CommunityplatformAdministratorEnvironmentsController";
import { CommunityplatformAdministratorGlobalconstraintsController } from "./controllers/communityPlatform/administrator/globalConstraints/CommunityplatformAdministratorGlobalconstraintsController";
import { CommunityplatformGlobalconstraintsController } from "./controllers/communityPlatform/globalConstraints/CommunityplatformGlobalconstraintsController";
import { CommunityplatformAdministratorPolicydocumentsController } from "./controllers/communityPlatform/administrator/policyDocuments/CommunityplatformAdministratorPolicydocumentsController";
import { CommunityplatformAdministratorUsersController } from "./controllers/communityPlatform/administrator/users/CommunityplatformAdministratorUsersController";
import { CommunityplatformAdministratorUsersSessionsController } from "./controllers/communityPlatform/administrator/users/sessions/CommunityplatformAdministratorUsersSessionsController";
import { CommunityplatformAdministratorUsersProfilesController } from "./controllers/communityPlatform/administrator/users/profiles/CommunityplatformAdministratorUsersProfilesController";
import { CommunityplatformUsersProfilesController } from "./controllers/communityPlatform/users/profiles/CommunityplatformUsersProfilesController";
import { CommunityplatformUserUsersProfilesController } from "./controllers/communityPlatform/user/users/profiles/CommunityplatformUserUsersProfilesController";
import { CommunityplatformAdministratorModeratorsController } from "./controllers/communityPlatform/administrator/moderators/CommunityplatformAdministratorModeratorsController";
import { CommunityplatformAdministratorModeratorsSessionsController } from "./controllers/communityPlatform/administrator/moderators/sessions/CommunityplatformAdministratorModeratorsSessionsController";
import { CommunityplatformAdministratorModeratorsProfilesController } from "./controllers/communityPlatform/administrator/moderators/profiles/CommunityplatformAdministratorModeratorsProfilesController";
import { CommunityplatformAdministratorAdministratorsController } from "./controllers/communityPlatform/administrator/administrators/CommunityplatformAdministratorAdministratorsController";
import { CommunityplatformAdministratorAdministratorsSessionsController } from "./controllers/communityPlatform/administrator/administrators/sessions/CommunityplatformAdministratorAdministratorsSessionsController";
import { CommunityplatformAdministratorAdministratorsProfilesController } from "./controllers/communityPlatform/administrator/administrators/profiles/CommunityplatformAdministratorAdministratorsProfilesController";
import { CommunityplatformCommunitiesController } from "./controllers/communityPlatform/communities/CommunityplatformCommunitiesController";
import { CommunityplatformUserCommunitiesController } from "./controllers/communityPlatform/user/communities/CommunityplatformUserCommunitiesController";
import { CommunityplatformAdministratorCommunitiesController } from "./controllers/communityPlatform/administrator/communities/CommunityplatformAdministratorCommunitiesController";
import { CommunityplatformCommunitiesSettingsController } from "./controllers/communityPlatform/communities/settings/CommunityplatformCommunitiesSettingsController";
import { CommunityplatformModeratorCommunitiesSettingsController } from "./controllers/communityPlatform/moderator/communities/settings/CommunityplatformModeratorCommunitiesSettingsController";
import { CommunityplatformCommunitiesRulesController } from "./controllers/communityPlatform/communities/rules/CommunityplatformCommunitiesRulesController";
import { CommunityplatformModeratorCommunitiesRulesController } from "./controllers/communityPlatform/moderator/communities/rules/CommunityplatformModeratorCommunitiesRulesController";
import { CommunityplatformCommunitiesModeratorsController } from "./controllers/communityPlatform/communities/moderators/CommunityplatformCommunitiesModeratorsController";
import { CommunityplatformAdministratorCommunitiesModeratorsController } from "./controllers/communityPlatform/administrator/communities/moderators/CommunityplatformAdministratorCommunitiesModeratorsController";
import { CommunityplatformModeratorCommunitiesJoinrequestsController } from "./controllers/communityPlatform/moderator/communities/joinRequests/CommunityplatformModeratorCommunitiesJoinrequestsController";
import { CommunityplatformAdministratorCommunitiesJoinrequestsController } from "./controllers/communityPlatform/administrator/communities/joinRequests/CommunityplatformAdministratorCommunitiesJoinrequestsController";
import { CommunityplatformUserCommunitiesJoinrequestsController } from "./controllers/communityPlatform/user/communities/joinRequests/CommunityplatformUserCommunitiesJoinrequestsController";
import { CommunityplatformUserCommunitiesMembershipsController } from "./controllers/communityPlatform/user/communities/memberships/CommunityplatformUserCommunitiesMembershipsController";
import { CommunityplatformModeratorCommunitiesMembershipsController } from "./controllers/communityPlatform/moderator/communities/memberships/CommunityplatformModeratorCommunitiesMembershipsController";
import { CommunityplatformAdministratorCommunitiesMembershipsController } from "./controllers/communityPlatform/administrator/communities/memberships/CommunityplatformAdministratorCommunitiesMembershipsController";
import { CommunityplatformPostsController } from "./controllers/communityPlatform/posts/CommunityplatformPostsController";
import { CommunityplatformUserPostsController } from "./controllers/communityPlatform/user/posts/CommunityplatformUserPostsController";
import { CommunityplatformUserPostsAttachmentsController } from "./controllers/communityPlatform/user/posts/attachments/CommunityplatformUserPostsAttachmentsController";
import { CommunityplatformPostsAttachmentsController } from "./controllers/communityPlatform/posts/attachments/CommunityplatformPostsAttachmentsController";
import { CommunityplatformAdministratorPostsEdithistoryController } from "./controllers/communityPlatform/administrator/posts/editHistory/CommunityplatformAdministratorPostsEdithistoryController";
import { CommunityplatformModeratorPostsStatuslogsController } from "./controllers/communityPlatform/moderator/posts/statusLogs/CommunityplatformModeratorPostsStatuslogsController";
import { CommunityplatformAdministratorPostsStatuslogsController } from "./controllers/communityPlatform/administrator/posts/statusLogs/CommunityplatformAdministratorPostsStatuslogsController";
import { CommunityplatformCommentsController } from "./controllers/communityPlatform/comments/CommunityplatformCommentsController";
import { CommunityplatformUserCommentsController } from "./controllers/communityPlatform/user/comments/CommunityplatformUserCommentsController";
import { CommunityplatformUserCommentsAttachmentsController } from "./controllers/communityPlatform/user/comments/attachments/CommunityplatformUserCommentsAttachmentsController";
import { CommunityplatformCommentsAttachmentsController } from "./controllers/communityPlatform/comments/attachments/CommunityplatformCommentsAttachmentsController";
import { CommunityplatformModeratorCommentsAttachmentsController } from "./controllers/communityPlatform/moderator/comments/attachments/CommunityplatformModeratorCommentsAttachmentsController";
import { CommunityplatformUserCommentsEdithistoryController } from "./controllers/communityPlatform/user/comments/editHistory/CommunityplatformUserCommentsEdithistoryController";
import { CommunityplatformAdministratorCommentsStatuslogsController } from "./controllers/communityPlatform/administrator/comments/statusLogs/CommunityplatformAdministratorCommentsStatuslogsController";
import { CommunityplatformAdministratorPostvotesController } from "./controllers/communityPlatform/administrator/postVotes/CommunityplatformAdministratorPostvotesController";
import { CommunityplatformModeratorPostvotesController } from "./controllers/communityPlatform/moderator/postVotes/CommunityplatformModeratorPostvotesController";
import { CommunityplatformUserPostvotesController } from "./controllers/communityPlatform/user/postVotes/CommunityplatformUserPostvotesController";
import { CommunityplatformModeratorCommentvotesController } from "./controllers/communityPlatform/moderator/commentVotes/CommunityplatformModeratorCommentvotesController";
import { CommunityplatformAdministratorCommentvotesController } from "./controllers/communityPlatform/administrator/commentVotes/CommunityplatformAdministratorCommentvotesController";
import { CommunityplatformUserCommentvotesController } from "./controllers/communityPlatform/user/commentVotes/CommunityplatformUserCommentvotesController";
import { CommunityplatformAdministratorVotingauditlogsController } from "./controllers/communityPlatform/administrator/votingAuditLogs/CommunityplatformAdministratorVotingauditlogsController";
import { CommunityplatformAdministratorVotingabuseflagsController } from "./controllers/communityPlatform/administrator/votingAbuseFlags/CommunityplatformAdministratorVotingabuseflagsController";
import { CommunityplatformAdministratorVotingratelimitsController } from "./controllers/communityPlatform/administrator/votingRateLimits/CommunityplatformAdministratorVotingratelimitsController";
import { CommunityplatformUserCommunitysubscriptionsController } from "./controllers/communityPlatform/user/communitySubscriptions/CommunityplatformUserCommunitysubscriptionsController";
import { CommunityplatformAdministratorCommunitysubscriptionsController } from "./controllers/communityPlatform/administrator/communitySubscriptions/CommunityplatformAdministratorCommunitysubscriptionsController";
import { CommunityplatformUserPostbookmarksController } from "./controllers/communityPlatform/user/postBookmarks/CommunityplatformUserPostbookmarksController";
import { CommunityplatformUserCommentbookmarksController } from "./controllers/communityPlatform/user/commentBookmarks/CommunityplatformUserCommentbookmarksController";
import { CommunityplatformUserCommunitysubscriptionsAuditlogsController } from "./controllers/communityPlatform/user/communitySubscriptions/auditLogs/CommunityplatformUserCommunitysubscriptionsAuditlogsController";
import { CommunityplatformAdministratorCommunitysubscriptionsAuditlogsController } from "./controllers/communityPlatform/administrator/communitySubscriptions/auditLogs/CommunityplatformAdministratorCommunitysubscriptionsAuditlogsController";
import { CommunityplatformAdministratorReportsController } from "./controllers/communityPlatform/administrator/reports/CommunityplatformAdministratorReportsController";
import { CommunityplatformModeratorReportsController } from "./controllers/communityPlatform/moderator/reports/CommunityplatformModeratorReportsController";
import { CommunityplatformUserReportsController } from "./controllers/communityPlatform/user/reports/CommunityplatformUserReportsController";
import { CommunityplatformAdministratorModerationactionsController } from "./controllers/communityPlatform/administrator/moderationActions/CommunityplatformAdministratorModerationactionsController";
import { CommunityplatformModeratorModerationactionsController } from "./controllers/communityPlatform/moderator/moderationActions/CommunityplatformModeratorModerationactionsController";
import { CommunityplatformAdministratorModerationactionsModeratoractionController } from "./controllers/communityPlatform/administrator/moderationActions/moderatorAction/CommunityplatformAdministratorModerationactionsModeratoractionController";
import { CommunityplatformModeratorModerationactionsModeratoractionController } from "./controllers/communityPlatform/moderator/moderationActions/moderatorAction/CommunityplatformModeratorModerationactionsModeratoractionController";
import { CommunityplatformAdministratorModerationactionsAdministratoractionController } from "./controllers/communityPlatform/administrator/moderationActions/administratorAction/CommunityplatformAdministratorModerationactionsAdministratoractionController";
import { CommunityplatformAdministratorReportescalationsController } from "./controllers/communityPlatform/administrator/reportEscalations/CommunityplatformAdministratorReportescalationsController";
import { CommunityplatformAdministratorContentquarantinesController } from "./controllers/communityPlatform/administrator/contentQuarantines/CommunityplatformAdministratorContentquarantinesController";
import { CommunityplatformAdministratorModerationauditlogsController } from "./controllers/communityPlatform/administrator/moderationAuditLogs/CommunityplatformAdministratorModerationauditlogsController";
import { CommunityplatformAdministratorUsersettingsController } from "./controllers/communityPlatform/administrator/userSettings/CommunityplatformAdministratorUsersettingsController";
import { CommunityplatformUserUsersettingsController } from "./controllers/communityPlatform/user/userSettings/CommunityplatformUserUsersettingsController";
import { CommunityplatformAdministratorNotificationsettingsController } from "./controllers/communityPlatform/administrator/notificationSettings/CommunityplatformAdministratorNotificationsettingsController";
import { CommunityplatformUserNotificationsettingsController } from "./controllers/communityPlatform/user/notificationSettings/CommunityplatformUserNotificationsettingsController";
import { CommunityplatformAdministratorPrivacysettingsController } from "./controllers/communityPlatform/administrator/privacySettings/CommunityplatformAdministratorPrivacysettingsController";
import { CommunityplatformUserPrivacysettingsController } from "./controllers/communityPlatform/user/privacySettings/CommunityplatformUserPrivacysettingsController";
import { CommunityplatformUserUsersProfileimagehistoryController } from "./controllers/communityPlatform/user/users/profileImageHistory/CommunityplatformUserUsersProfileimagehistoryController";
import { CommunityplatformModeratorUsersProfileimagehistoryController } from "./controllers/communityPlatform/moderator/users/profileImageHistory/CommunityplatformModeratorUsersProfileimagehistoryController";
import { CommunityplatformAdministratorUsersProfileimagehistoryController } from "./controllers/communityPlatform/administrator/users/profileImageHistory/CommunityplatformAdministratorUsersProfileimagehistoryController";
import { CommunityplatformUserUsersProfiledisplaymetricsController } from "./controllers/communityPlatform/user/users/profileDisplayMetrics/CommunityplatformUserUsersProfiledisplaymetricsController";
import { CommunityplatformAdministratorRankingalgorithmconfigsController } from "./controllers/communityPlatform/administrator/rankingAlgorithmConfigs/CommunityplatformAdministratorRankingalgorithmconfigsController";
import { CommunityplatformAdministratorRankingeventlogsController } from "./controllers/communityPlatform/administrator/rankingEventLogs/CommunityplatformAdministratorRankingeventlogsController";
import { CommunityplatformHotpostrankingsController } from "./controllers/communityPlatform/hotPostRankings/CommunityplatformHotpostrankingsController";
import { CommunityplatformToppostrankingsController } from "./controllers/communityPlatform/topPostRankings/CommunityplatformToppostrankingsController";
import { CommunityplatformControversialpostrankingsController } from "./controllers/communityPlatform/controversialPostRankings/CommunityplatformControversialpostrankingsController";

@Module({
  controllers: [
    AuthUserController,
    AuthModeratorController,
    AuthAdministratorController,
    CommunityplatformAdministratorSystemsettingsController,
    CommunityplatformAdministratorFeatureflagsController,
    CommunityplatformAdministratorEnvironmentsController,
    CommunityplatformAdministratorGlobalconstraintsController,
    CommunityplatformGlobalconstraintsController,
    CommunityplatformAdministratorPolicydocumentsController,
    CommunityplatformAdministratorUsersController,
    CommunityplatformAdministratorUsersSessionsController,
    CommunityplatformAdministratorUsersProfilesController,
    CommunityplatformUsersProfilesController,
    CommunityplatformUserUsersProfilesController,
    CommunityplatformAdministratorModeratorsController,
    CommunityplatformAdministratorModeratorsSessionsController,
    CommunityplatformAdministratorModeratorsProfilesController,
    CommunityplatformAdministratorAdministratorsController,
    CommunityplatformAdministratorAdministratorsSessionsController,
    CommunityplatformAdministratorAdministratorsProfilesController,
    CommunityplatformCommunitiesController,
    CommunityplatformUserCommunitiesController,
    CommunityplatformAdministratorCommunitiesController,
    CommunityplatformCommunitiesSettingsController,
    CommunityplatformModeratorCommunitiesSettingsController,
    CommunityplatformCommunitiesRulesController,
    CommunityplatformModeratorCommunitiesRulesController,
    CommunityplatformCommunitiesModeratorsController,
    CommunityplatformAdministratorCommunitiesModeratorsController,
    CommunityplatformModeratorCommunitiesJoinrequestsController,
    CommunityplatformAdministratorCommunitiesJoinrequestsController,
    CommunityplatformUserCommunitiesJoinrequestsController,
    CommunityplatformUserCommunitiesMembershipsController,
    CommunityplatformModeratorCommunitiesMembershipsController,
    CommunityplatformAdministratorCommunitiesMembershipsController,
    CommunityplatformPostsController,
    CommunityplatformUserPostsController,
    CommunityplatformUserPostsAttachmentsController,
    CommunityplatformPostsAttachmentsController,
    CommunityplatformAdministratorPostsEdithistoryController,
    CommunityplatformModeratorPostsStatuslogsController,
    CommunityplatformAdministratorPostsStatuslogsController,
    CommunityplatformCommentsController,
    CommunityplatformUserCommentsController,
    CommunityplatformUserCommentsAttachmentsController,
    CommunityplatformCommentsAttachmentsController,
    CommunityplatformModeratorCommentsAttachmentsController,
    CommunityplatformUserCommentsEdithistoryController,
    CommunityplatformAdministratorCommentsStatuslogsController,
    CommunityplatformAdministratorPostvotesController,
    CommunityplatformModeratorPostvotesController,
    CommunityplatformUserPostvotesController,
    CommunityplatformModeratorCommentvotesController,
    CommunityplatformAdministratorCommentvotesController,
    CommunityplatformUserCommentvotesController,
    CommunityplatformAdministratorVotingauditlogsController,
    CommunityplatformAdministratorVotingabuseflagsController,
    CommunityplatformAdministratorVotingratelimitsController,
    CommunityplatformUserCommunitysubscriptionsController,
    CommunityplatformAdministratorCommunitysubscriptionsController,
    CommunityplatformUserPostbookmarksController,
    CommunityplatformUserCommentbookmarksController,
    CommunityplatformUserCommunitysubscriptionsAuditlogsController,
    CommunityplatformAdministratorCommunitysubscriptionsAuditlogsController,
    CommunityplatformAdministratorReportsController,
    CommunityplatformModeratorReportsController,
    CommunityplatformUserReportsController,
    CommunityplatformAdministratorModerationactionsController,
    CommunityplatformModeratorModerationactionsController,
    CommunityplatformAdministratorModerationactionsModeratoractionController,
    CommunityplatformModeratorModerationactionsModeratoractionController,
    CommunityplatformAdministratorModerationactionsAdministratoractionController,
    CommunityplatformAdministratorReportescalationsController,
    CommunityplatformAdministratorContentquarantinesController,
    CommunityplatformAdministratorModerationauditlogsController,
    CommunityplatformAdministratorUsersettingsController,
    CommunityplatformUserUsersettingsController,
    CommunityplatformAdministratorNotificationsettingsController,
    CommunityplatformUserNotificationsettingsController,
    CommunityplatformAdministratorPrivacysettingsController,
    CommunityplatformUserPrivacysettingsController,
    CommunityplatformUserUsersProfileimagehistoryController,
    CommunityplatformModeratorUsersProfileimagehistoryController,
    CommunityplatformAdministratorUsersProfileimagehistoryController,
    CommunityplatformUserUsersProfiledisplaymetricsController,
    CommunityplatformAdministratorRankingalgorithmconfigsController,
    CommunityplatformAdministratorRankingeventlogsController,
    CommunityplatformHotpostrankingsController,
    CommunityplatformToppostrankingsController,
    CommunityplatformControversialpostrankingsController,
  ],
})
export class MyModule {}
