import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommerceMallSellerAdminRequest } from "../../../../../structures/IEcommerceMallSellerAdminRequest";
import { IPageIEcommerceMallSellerAdminRequest } from "../../../../../structures/IPageIEcommerceMallSellerAdminRequest";

/**
 * Retrieve a paginated list of all seller admin privilege requests for super administrator review.
 *
 * This endpoint allows super administrators to view all submitted admin privilege requests from sellers. Each request includes the submission date, current status (pending, approved, or rejected), the reason provided by the seller, and any rejection reason if applicable.
 *
 * Super administrators can filter results by status to focus on pending requests awaiting review, approved requests, or previously rejected requests. Results are sorted by creation date with newest first by default.
 *
 * Only super administrators have access to this operation. The response includes summary information optimized for list displays, showing request ID, seller reference, status, reason, submission timestamp, and rejection reason when present.
 *
 * Related operations:
 * - GET /ecommerceMall/superAdmin/seller/admin-requests/{sellerAdminRequestId}: Get detailed view of a specific seller admin request
 * - POST /ecommerceMall/admin/requests: Submit a new admin privilege request (seller role)
 * - PUT /ecommerceMall/superAdmin/seller/admin-requests/{sellerAdminRequestId}: Approve or reject a seller admin request
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for filtering seller admin requests
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdmin
 * @x-autobe-specification Query ecommerce_mall_seller_admin_requests table filtering by the authenticated seller's ID.
 *
 * 1. Extract seller ID from authenticated session
 * 2. Apply optional status filter from request body (pending, approved, rejected)
 * 3. Apply pagination parameters (page, limit)
 * 4. Order by created_at descending (newest first)
 * 5. Return paginated results with request summary: id, requested_grade, status, reason, created_at, rejection_reason (if any)
 * 6. Exclude soft-deleted records (where deleted_at is not null)
 * 7. Return IPageIEcommerceMallSellerAdminRequest.ISummary format
 * @path /ecommerceMall/superAdmin/seller/admin-requests
 * @accessor api.functional.ecommerceMall.superAdmin.seller.admin_requests.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for filtering seller admin requests
     */
    body: IEcommerceMallSellerAdminRequest.IRequest;
  };
  export type Body = IEcommerceMallSellerAdminRequest.IRequest;
  export type Response = IPageIEcommerceMallSellerAdminRequest.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/ecommerceMall/superAdmin/seller/admin-requests",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/ecommerceMall/superAdmin/seller/admin-requests";
  export const random = (): IPageIEcommerceMallSellerAdminRequest.ISummary =>
    typia.random<IPageIEcommerceMallSellerAdminRequest.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a specific seller admin privilege request by its unique identifier.
 *
 * This endpoint allows authenticated sellers to view the details of an admin privilege request they submitted. The response includes the request status (pending, approved, or rejected), the reason provided during submission, and any rejection reason if the request was denied by a super administrator.
 *
 * The seller can only access their own admin requests. If the request does not belong to the authenticated seller, the system returns a not found error for security reasons (preventing enumeration of other users' requests).
 *
 * Timestamps for submission and last modification are included for reference. Soft-deleted requests are not accessible through this endpoint.
 *
 * @param props.connection
 * @param props.requestId Unique identifier of the admin request
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdmin
 * @x-autobe-specification Query the ecommerce_mall_seller_admin_requests table using the provided requestId as the primary key. Verify the request belongs to the authenticated seller via session. If not found or belongs to another seller, return 404. Return all fields including reason, status, rejection_reason, created_at, and updated_at. Exclude soft-deleted requests where deleted_at is not null.
 * @path /ecommerceMall/superAdmin/seller/admin-requests/:requestId
 * @accessor api.functional.ecommerceMall.superAdmin.seller.admin_requests.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the admin request
     */
    requestId: string & tags.Format<"uuid">;
  };
  export type Response = IEcommerceMallSellerAdminRequest;

  export const METADATA = {
    method: "GET",
    path: "/ecommerceMall/superAdmin/seller/admin-requests/:requestId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommerceMall/superAdmin/seller/admin-requests/${encodeURIComponent(props.requestId ?? "null")}`;
  export const random = (): IEcommerceMallSellerAdminRequest =>
    typia.random<IEcommerceMallSellerAdminRequest>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("requestId")(() => typia.assert(props.requestId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
