import { TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IEcommerceSystemStatus } from "../../../../api/structures/IEcommerceSystemStatus";
import { AdminAuth } from "../../../../decorators/AdminAuth";
import { AdminPayload } from "../../../../decorators/payload/AdminPayload";
import { getEcommerceAdminStatusDistribution } from "../../../../providers/getEcommerceAdminStatusDistribution";

@Controller("/ecommerce/admin/status-distribution")
export class EcommerceAdminStatus_distributionController {
  /**
   * Retrieve the current distribution of system health statuses across all monitored components.
   *
   * This endpoint provides a real-time overview of system health state distribution for monitoring and alerting purposes. It aggregates the status field (healthy, warning, unhealthy) from the ecommerce_system_statuses table to show the count of components in each health state.
   *
   * The response enables system administrators to quickly assess the overall system health without drilling into individual components. This is a system-level metric that helps identify potential widespread issues across the platform architecture.
   *
   * The data represents the most recent status check values recorded in the system, with no filtering or pagination applied.
   *
   * @param connection
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor admin
   * @x-autobe-specification Group ecommerce_system_statuses records by status field to count healthy/warning/unhealthy components. Return the counts per status type. Use SQL aggregation query with GROUP BY status.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async statusDistribution(
    @AdminAuth()
    admin: AdminPayload,
  ): Promise<IEcommerceSystemStatus> {
    try {
      return await getEcommerceAdminStatusDistribution({
        admin,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
