import { ArrayUtil, RandomGenerator } from "@nestia/e2e";
import { randint } from "tstl";
import typia, { tags } from "typia";

import { DeepPartial } from "@ORGANIZATION/PROJECT-api/lib/typings/DeepPartial";
import { IEntity } from "@ORGANIZATION/PROJECT-api/lib/structures/IEntity";
import { IShoppingMallPayment } from "@ORGANIZATION/PROJECT-api/lib/structures/IShoppingMallPayment";
export function prepare_random_shopping_mall_payment(
  input?: DeepPartial<IShoppingMallPayment.ICreate> | undefined,
): IShoppingMallPayment.ICreate {
  return {
    order_id: typia.random<string & tags.Format<"uuid">>(),
    payment_method_id: typia.random<string & tags.Format<"uuid">>(),
    amount: typia.random<number & tags.Minimum<0.01>>(),
    currency: RandomGenerator.pick([
      "USD",
      "EUR",
      "JPY",
      "KRW",
      "GBP",
      "CAD",
      "AUD",
      "CHF",
      "CNY",
      "SEK",
      "NZD",
      "MXN",
      "SGD",
      "HKD",
      "NOK",
      "DKK",
      "INR",
      "BRL",
      "RUB",
      "TRY",
      "ZAR",
      "ARS",
      "CLP",
      "COP",
      "IDR",
      "MYR",
      "PHP",
      "THB",
      "VND",
      "PLN",
      "HUF",
      "CZK",
      "ILS",
      "SAR",
      "AED",
      "QAR",
      "KWD",
      "BHD",
      "OMR",
      "BND",
      "MMK",
      "LKR",
      "BDT",
      "PKR",
      "EGP",
      "NGN",
      "KES",
      "UGX",
      "TZS",
      "ZMW",
      "MWK",
      "MZN",
      "AOA",
      "SLL",
      "GHS",
      "XOF",
      "XAF",
      "CDF",
      "LYD",
      "DZD",
      "TND",
      "MAD",
      "ETB",
      "SYP",
      "IQR",
      "IRR",
      "TRY",
      "AZN",
      "AMD",
      "GEL",
      "KGS",
      "TJS",
      "UZS",
      "XPF",
      "XAG",
      "XAU",
    ] as const),
    payment_intent_id:
      input?.payment_intent_id ?? typia.random<string & tags.Format<"uuid">>(),
  };
}
