import { tags } from "typia";

/**
 * Predefined categories for organizing politicsBBS articles and discussions.
 * Categories facilitate content discoverability and filtering, focusing on
 * economic and political topics as specified in the requirements. Categories
 * are created and managed by moderators through the system interface.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPoliticsBbsCategory = {
  /** Primary key. Unique identifier for the category. */
  id: string & tags.Format<"uuid">;

  /**
   * Unique category code for internal reference and URL generation. Must be
   * unique across the system.
   */
  code: string;

  /** Display name for the category shown to users. */
  name: string;

  /** Detailed description of the category's purpose and scope. */
  description: string;

  /** CSS color code for visual identification of the category. */
  color?: string | null | undefined;

  /** Icon identifier for visual representation. */
  icon?: string | null | undefined;

  /** Display order for category sorting in lists. */
  sequence: number & tags.Type<"int32">;

  /** Whether this is a primary featured category. */
  primary: boolean;

  /** Whether this category is required to be assigned. */
  required: boolean;

  /** Whether multiple categories can be assigned to content. */
  multiplicative: boolean;

  /** Category creation timestamp. */
  created_at: string & tags.Format<"date-time">;

  /** Last modification timestamp. */
  updated_at: string & tags.Format<"date-time">;

  /** Soft delete timestamp. */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace IPoliticsBbsCategory {
  /**
   * Lightweight category summary representation for list views and interface
   * contexts where complete category metadata is needed for display and
   * filtering purposes. This summary type is specifically optimized for
   * combination with article information, navigation interfaces, and category
   * selection components within the politicsBBS discussion platform.
   *
   * The summary provides essential category information while maintaining
   * performance efficiency through selective field inclusion. All intrinsic
   * identifier fields (id, code, name) and configuration attributes
   * (sequence, primary, required, multiplicative) are included to support all
   * category-related UI operations without requiring additional database
   * queries.
   *
   * This format balances comprehensive category information resolution needs
   * with network efficiency requirements, enabling the atomic operation
   * principle by providing sufficient context in a single API call. The
   * summary is particularly valuable for member dashboards, article creation
   * flows, and browsing interfaces where category context enhances content
   * understanding while maintaining system performance for substantive
   * political and economic discussions.
   */
  export type ISummary = {
    /**
     * Category identifier from politics_bbs_categories.id field serving as
     * the primary key for category references across the politicsBBS
     * discussion board platform.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Unique category code from politics_bbs_categories.code field for
     * internal reference, URL generation, and programmatic access within
     * the politics discussion board API endpoints.
     */
    code: string;

    /**
     * Display name from politics_bbs_categories.name field shown to users
     * in interfaces, search filters, and navigation menus for political and
     * economic content discovery.
     */
    name: string;

    /**
     * Timestamp from politics_bbs_categories.created_at field tracking when
     * the category was first established in the system for administrative
     * reference and audit purposes.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Timestamp from politics_bbs_categories.updated_at field reflecting
     * the most recent modification to category configuration settings by
     * moderation admin or system maintenance operations.
     */
    updated_at: (string & tags.Format<"date-time">) | null;

    /**
     * Soft delete timestamp from politics_bbs_categories.deleted_at field
     * indicating when the category was logically removed from active use
     * while preserving historical associations for audit trail compliance.
     */
    deleted_at: (string & tags.Format<"date-time">) | null;

    /**
     * Display order from politics_bbs_categories.sequence field controlling
     * category positioning in user interfaces and navigation hierarchies
     * across the political discussion platform.
     */
    sequence: number & tags.Type<"int32">;

    /**
     * Primary category flag from politics_bbs_categories.primary field
     * determining prominent display placement within the politicsBBS system
     * for core economics and political discussion areas.
     */
    primary: boolean;

    /**
     * Required category flag from politics_bbs_categories.required field
     * indicating whether category assignment is mandatory for article
     * submissions to maintain consistent organization.
     */
    required: boolean;

    /**
     * Multiplicative flag from politics_bbs_categories.multiplicative field
     * enabling multiple simultaneous category assignments for nuanced
     * political and economic discussion topics.
     */
    multiplicative: boolean;

    /**
     * CSS color code from politics_bbs_categories.color field providing
     * visual differentiation in category selectors and user interfaces for
     * the politics discussion board platform.
     */
    color: string | null;

    /**
     * Icon identifier from politics_bbs_categories.icon field enhancing
     * visual recognition and category browsing experience throughout the
     * political and economic discussion platform.
     */
    icon: string | null;

    /**
     * Category description from politics_bbs_categories.description field
     * explaining scope and content guidelines for appropriate category
     * usage within the politicsBBS discussion organization system.
     */
    description: string;
  };

  /**
   * Request type for creating a new political discussion category in the
   * politicsBBS system. Categories organize economic and political
   * discussions by topic, facilitating content discovery and filtering within
   * the platform.
   *
   * Categories serve as the primary organizational structure for the
   * discussion board, enabling users to find relevant content pertaining to
   * economic policies, political analysis, international relations, and other
   * policy-focused topics. The designation helps users navigate discussions
   * by thematic focus rather than chronological order.
   *
   * The system enforces that articles must belong to at least one category,
   * ensuring all submitted content receives appropriate classification.
   * Categories support both primary featured distinction for prominent
   * display and required/optional settings to enforce organizational
   * consistency throughout the political discourse platform.
   */
  export type ICreate = {
    /**
     * Unique category code for internal reference and URL generation. This
     * code must be globally unique across the system and cannot be changed
     * after creation. Used for URL paths and API references, typically
     * formatted in lowercase with hyphens. Examples: 'economic-policy',
     * 'international-relations', 'domestic-politics'. The code serves as
     * the stable identifier for category references throughout the system.
     */
    code: string;

    /**
     * Display name for the category shown to users in the interface and
     * navigation. Should be human-readable and clearly describe the
     * category focus while maintaining professional tone appropriate for
     * political and economic discourse. Examples: 'Economic Policy',
     * 'International Relations', 'Domestic Politics'. The name provides the
     * primary visual identifier in user interfaces and search filtering.
     */
    name: string;

    /**
     * Detailed description of the category's purpose and scope, explaining
     * what types of discussions belong within its domain. Helps users
     * understand content guidelines and supports informed category
     * selection during article creation. Should provide clear guidance
     * about appropriate types of economic analysis, political commentary,
     * or policy discussions that align with the category focus while
     * maintaining substantive discourse standards.
     */
    description: string;

    /**
     * CSS color code for visual identification and UI theming of the
     * category. Used for visual differentiation in category selectors,
     * article badges, and navigation interfaces to enhance visual
     * recognition. Should be specified as hex color codes like '#1E88E5'
     * for blue themes or '#E53935' for red themes, providing visual
     * consistency across the platform. Can be null to use default system
     * styling.
     */
    color?: string | null | undefined;

    /**
     * Icon identifier for visual representation in category interfaces and
     * navigation elements. Could be CSS class names (e.g., 'fas
     * fa-economy'), fontawesome identifiers (e.g., 'fa-chart-line'), or
     * other icon references from supported icon libraries. Enhances visual
     * recognition and quick identification in category browsers and
     * selection interfaces. Can be null when visual icons are not required
     * or desired.
     */
    icon?: string | null | undefined;

    /**
     * Display order for category sorting in lists and selection interfaces.
     * Lower numeric values appear first in category drop-downs, navigation
     * menus, and category selection components. Enables moderator control
     * over presentation hierarchy, allowing popular or important categories
     * to be positioned prominently for improved discoverability of economic
     * and political content.
     */
    sequence: number & tags.Type<"int32">;

    /**
     * Whether this category should be featured prominently in the interface
     * as a primary discussion area. Primary categories receive enhanced
     * visibility in category selectors, home page displays, and navigation
     * elements to improve discoverability of key economic policy, political
     * analysis, or international relations content areas that represent
     * core discussion focuses of the platform.
     */
    primary: boolean;

    /**
     * Whether this category is mandatory for articles or optional for
     * content classification. When true, articles must be assigned to this
     * category, ensuring consistent organizational structure for essential
     * taxonomy areas like broad political or economic discussions. Can be
     * used to enforce categorization rules or create mandatory category
     * groups that maintain content organization standards across the
     * political discussion platform.
     */
    required: boolean;

    /**
     * Whether multiple categories can be assigned to content
     * simultaneously. When false, articles can only have this single
     * category identifier. When true, allows flexible categorization where
     * articles can belong to multiple overlapping categories such as both
     * 'Economic Policy' and 'Healthcare Policy' for health economics
     * discussions, supporting nuanced content classification appropriate
     * for complex political and economic topics.
     */
    multiplicative: boolean;
  };

  /**
   * Update DTO for modifying existing discussion categories in the
   * politicsBBS system. Allows moderators to adjust category properties
   * including name, description, visual styling, and configuration flags. All
   * fields are optional to enable partial updates without requiring full
   * category data representation.
   */
  export type IUpdate = {
    /**
     * Unique category code for internal reference and URL generation. Same
     * as in create DTO functionality. Can only be changed with moderator
     * privileges.
     */
    code?: string | undefined;

    /**
     * Display name for the category shown to users. Same as in create DTO
     * functionality.
     */
    name?: string | undefined;

    /**
     * Detailed description of the category's purpose and scope. Same as in
     * create DTO functionality.
     */
    description?: string | undefined;

    /**
     * CSS color code for visual identification. Same as in create DTO
     * functionality.
     */
    color?: string | null | undefined;

    /**
     * Icon identifier for visual representation. Same as in create DTO
     * functionality.
     */
    icon?: string | null | undefined;

    /**
     * Display order for category sorting. Same as in create DTO
     * functionality.
     */
    sequence?: (number & tags.Type<"int32">) | undefined;

    /**
     * Whether this is a primary featured category. Same as in create DTO
     * functionality.
     */
    primary?: boolean | undefined;

    /**
     * Whether this category is required for articles. Same as in create DTO
     * functionality.
     */
    required?: boolean | undefined;

    /**
     * Whether multiple categories can be assigned to content. Same as in
     * create DTO functionality.
     */
    multiplicative?: boolean | undefined;
  };

  /**
   * Search and filtering parameters for retrieving political discussion
   * categories. Supports complex queries across multiple criteria including
   * text search, visibility filters, pagination, and sorting options. This
   * enables users to find relevant categories for organizing economic and
   * political discussions.
   */
  export type IRequest = {
    /**
     * Search query to filter categories by name, code, or description. The
     * search is case-insensitive and matches partial strings using trigram
     * similarity scoring.
     */
    search: string;

    /**
     * Filter to show only primary featured categories (true) or non-primary
     * categories (false), or null to show all categories
     */
    primary: null | boolean;

    /**
     * Maximum number of categories to return per page. Defaults to 20 if
     * not specified. Valid range is 1-100.
     */
    limit:
      | null
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>);

    /**
     * Page number for pagination (1-based indexing). Defaults to 1. Higher
     * page numbers retrieve subsequent results when total categories exceed
     * the limit.
     */
    page: null | (number & tags.Type<"int32"> & tags.Minimum<1>);

    /**
     * Field to sort results by. 'sequence' sorts by display order, 'name'
     * sorts alphabetically, 'created_at' sorts by newest first. Defaults to
     * 'sequence'.
     */
    order_by: "sequence" | "name" | "created_at" | null;

    /**
     * Sort direction for the order_by field. 'asc' for ascending, 'desc'
     * for descending order. Defaults to 'asc' for sequence and name, 'desc'
     * for created_at.
     */
    direction: "asc" | "desc" | null;
  };
}
