import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IHrmPlatformActivityLog } from "../../../../structures/IHrmPlatformActivityLog";
import { IPageIHrmPlatformActivityLog } from "../../../../structures/IPageIHrmPlatformActivityLog";

/**
 * Retrieve a filtered and paginated list of activity log entries from the organization's audit trail.
 *
 * This operation provides comprehensive access to the activity log, which records all significant actions performed within the organization including employee management events (invitations, deactivations, reactivations), contract changes (creation, edits), project lifecycle events (creation, archival, completion, deletion), task status transitions, timesheet workflow actions (submission, approval, rejection), and role assignments.
 *
 * Access to this endpoint is restricted to members with the org:manage permission, ensuring that only authorized users can view the complete organizational audit trail. The activity log maintains strict organization isolation, meaning users can only see activity records from their currently selected organization.
 *
 * The operation supports advanced filtering capabilities including action type classification (employee:invited, contract:created, project:archived, etc.), target entity type (employee, contract, project, task, timesheet, role), specific user who performed the action, and date range constraints. Results are returned with cursor-based pagination for efficient browsing of large activity histories.
 *
 * Each activity log entry includes the timestamp of the action, the user who performed it, the action type classification, the target entity affected, and contextual details in JSON format. This comprehensive audit trail supports compliance requirements, debugging efforts, and organizational oversight.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for filtering activity log entries
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Query hrm_platform_activity_logs table with organization context from authenticated member's session.
 *
 * Validate user has org:manage permission for the current organization before proceeding.
 *
 * Apply filtering conditions from request body:
 * - Filter by action_type if provided (exact match or IN clause for multiple values)
 * - Filter by user_id if provided (match user who performed action)
 * - Filter by date range using created_at column (gte/lte comparisons)
 * - Filter by target_entity type if provided
 * - Filter by target_id if provided
 *
 * Join with hrm_platform_members table to fetch user display information (name, email).
 *
 * Implement cursor-based pagination using created_at and id as composite cursor for consistent ordering.
 *
 * Order results by created_at DESC (newest first) to show most recent activities.
 *
 * Return paginated response with IHrmPlatformActivityLog.ISummary schema containing essential fields (id, action_type, target_entity, created_at, user information) without full details JSON to optimize payload size.
 *
 * Enforce organization_id filter on all queries to maintain multi-tenancy isolation.
 *
 * Handle edge cases: empty result set returns IPageIHrmPlatformActivityLog.ISummary with empty data array, invalid permission returns 403 Forbidden, invalid filter parameters return 400 Bad Request.
 * @path /hrmPlatform/member/activity-logs
 * @accessor api.functional.hrmPlatform.member.activity_logs.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for filtering activity log entries
     */
    body: IHrmPlatformActivityLog.IRequest;
  };
  export type Body = IHrmPlatformActivityLog.IRequest;
  export type Response = IPageIHrmPlatformActivityLog.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/hrmPlatform/member/activity-logs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/hrmPlatform/member/activity-logs";
  export const random = (): IPageIHrmPlatformActivityLog.ISummary =>
    typia.random<IPageIHrmPlatformActivityLog.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve a detailed activity log entry by its unique identifier.
 *
 * This endpoint provides access to a specific audit trail record that captures significant organizational actions. Each activity log entry contains comprehensive information about when an action occurred, who performed it, what type of action was taken, and which business entity was affected.
 *
 * Activity log entries are immutable once created and serve as an official record of organizational events including employee management actions (invited, deactivated, reactivated), contract changes (created, edited), project lifecycle events (created, archived, completed, deleted), task status transitions, timesheet workflow actions (submitted, approved, rejected), and role assignments. These records cannot be modified or deleted after creation.
 *
 * Access to this endpoint requires the org:manage permission within the current organization context. All activity logs are scoped to the requesting user's organization, ensuring multi-tenancy data isolation. The response includes the complete activity log record with the action timestamp (created_at), performing user identifier (user_id), action type classification (action_type), target entity type (target_entity), target entity ID (target_id), and any contextual information stored in the details field in JSON format.
 *
 * @param props.connection
 * @param props.activityLogId Unique identifier of the activity log entry (global scope)
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor member
 * @x-autobe-specification Implement GET /activity-logs/{activityLogId} with the following logic:
 *
 * 1. Validate activityLogId is a valid UUID format
 * 2. Extract organization context from authentication token
 * 3. Verify user has org:manage permission for the organization
 * 4. Query hrm_platform_activity_logs table by id = activityLogId AND organization_id = current organization
 * 5. If record not found, return 404 Not Found
 * 6. If record found, construct response object with all fields: id, organization_id, user_id, action_type, target_entity, target_id, details, created_at
 * 7. Return 200 OK with activity log details
 *
 * Query optimization:
 * - Use indexed lookup on (id, organization_id) composite key
 * - Include JOIN with hrm_platform_members to fetch user display name if needed for response enrichment
 * - No caching required as activity logs are append-only and accessed infrequently
 *
 * Error handling:
 * - 400 Bad Request: Invalid UUID format for activityLogId
 * - 401 Unauthorized: Missing or invalid authentication token
 * - 403 Forbidden: User lacks org:manage permission
 * - 404 Not Found: Activity log entry does not exist or belongs to different organization
 * @path /hrmPlatform/member/activity-logs/:activityLogId
 * @accessor api.functional.hrmPlatform.member.activity_logs.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the activity log entry (global scope)
     */
    activityLogId: string & tags.Format<"uuid">;
  };
  export type Response = IHrmPlatformActivityLog;

  export const METADATA = {
    method: "GET",
    path: "/hrmPlatform/member/activity-logs/:activityLogId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/hrmPlatform/member/activity-logs/${encodeURIComponent(props.activityLogId ?? "null")}`;
  export const random = (): IHrmPlatformActivityLog =>
    typia.random<IHrmPlatformActivityLog>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("activityLogId")(() => typia.assert(props.activityLogId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
