import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IECommerceMallSeller } from "../../../../../structures/IECommerceMallSeller";

/**
 * Ban a seller account, revoking their login access while preserving existing orders and associated data.
 *
 * Administrators use this endpoint to ban a seller account for policy violations. When a seller is banned, they can no longer log into their account. Their existing orders remain unaffected — order items already paid or shipped continue processing normally, and the seller's order history is preserved. All products belonging to the banned seller are hidden from search results and category listings and cannot be purchased.
 *
 * The request must include a reason for the ban, which is recorded in the administrative audit trail for transparency and accountability. A seller who is already banned cannot be banned again — the endpoint returns a conflict error.
 *
 * @param props.connection
 * @param props.sellerId UUID of the seller account to ban (global scope).
 * @param props.body Ban request containing the mandatory reason explaining why the seller is being banned. The reason is recorded in the administrator audit trail for accountability.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor superAdministrator
 * @x-autobe-specification Validate that the requesting actor is an
 *   administrator or super administrator. Verify the seller exists and is not
 *   already banned (banned_at is null). Set the seller's banned_at field to the
 *   current timestamp. Record the action in
 *   e_commerce_mall_administrator_audit_logs (or
 *   e_commerce_mall_super_administrator_audit_logs) with action_type
 *   'ban_seller', target_type 'seller', target_id as the seller's UUID, and the
 *   reason from the request body. Return the updated seller record. If the
 *   seller is already banned, return a conflict error. If the seller account is
 *   soft-deleted (deleted_at is set), return a not-found error.
 * @path /eCommerceMall/superAdministrator/sellers/:sellerId/ban
 * @accessor api.functional.eCommerceMall.superAdministrator.sellers.ban.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * UUID of the seller account to ban (global scope).
     */
    sellerId: string & tags.Format<"uuid">;

    /**
     * Ban request containing the mandatory reason explaining why the seller is being banned. The reason is recorded in the administrator audit trail for accountability.
     */
    body: IECommerceMallSeller.IBan;
  };
  export type Body = IECommerceMallSeller.IBan;
  export type Response = IECommerceMallSeller;

  export const METADATA = {
    method: "POST",
    path: "/eCommerceMall/superAdministrator/sellers/:sellerId/ban",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/eCommerceMall/superAdministrator/sellers/${encodeURIComponent(props.sellerId ?? "null")}/ban`;
  export const random = (): IECommerceMallSeller =>
    typia.random<IECommerceMallSeller>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("sellerId")(() => typia.assert(props.sellerId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
