import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia from "typia";

import { ICommunityPlatformPost } from "../../../structures/ICommunityPlatformPost";

/**
 * Perform a unified search across the community platform, supporting searching across communities, posts, and users with a single query.
 *
 * This operation enables users to find relevant content and users across the entire platform using a unified search interface. The search spans multiple entity types including communities, posts, and user profiles, with configurable filtering options.
 *
 * Search results are paginated and can be filtered by entity type to focus on specific content categories. The search algorithm prioritizes exact matches followed by partial matches, with relevance scoring based on match quality and recency.
 *
 * Guest users can search public content including communities and non-deleted posts, while authenticated members have access to additional search capabilities. The operation respects privacy and content visibility settings, excluding soft-deleted content and respecting user account status.
 *
 * Related operations include GET /communities for browsing all communities, PATCH /posts for searching posts specifically, and GET /members for user directory access.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for unified platform search
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor null
 * @x-autobe-specification Implement global search across communities, posts, and users with unified query support.
 *
 * 1. Parse search query from request body:
 *    - Search text is case-insensitive and supports partial matching
 *    - Apply search to communities.name, communities.description, posts.title, posts.content_type, members.username, members.nickname
 *
 * 2. Filter by entity types if specified:
 *    - If entityTypes includes 'community', search community_platform_communities
 *    - If entityTypes includes 'post', search community_platform_posts
 *    - If entityTypes includes 'user', search community_platform_members
 *    - If entityTypes is empty, search all entities
 *
 * 3. Apply pagination:
 *    - Use page-based or cursor-based pagination
 *    - Default page size of 20 results
 *    - Return total count for pagination metadata
 *
 * 4. Security and visibility:
 *    - Guests can search public content (communities, non-deleted posts)
 *    - Members see same as guests
 *    - Respect deleted_at flags (exclude soft-deleted content)
 *    - Exclude deleted users
 *
 * 5. Search algorithm:
 *    - For communities: search name (primary) and description (secondary)
 *    - For posts: search title (primary) and content based on type
 *    - For users: search username (primary) and nickname (secondary)
 *    - Sort by relevance score
 *
 * 6. Response structure:
 *    - Each result includes entity type ('community', 'post', 'user')
 *    - Include relevant fields for each type
 *    - Return pagination metadata
 * @path /communityPlatform/search/unified
 * @accessor api.functional.communityPlatform.search.unified
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function unified(
  connection: IConnection,
  props: unified.Props,
): Promise<unified.Response> {
  return true === connection.simulate
    ? unified.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...unified.METADATA,
          path: unified.path(),
          status: null,
        },
        props.body,
      );
}
export namespace unified {
  export type Props = {
    /**
     * Search criteria and pagination parameters for unified platform search
     */
    body: ICommunityPlatformPost.IUnified;
  };
  export type Body = ICommunityPlatformPost.IUnified;
  export type Response = ICommunityPlatformPost.IUnifiedResponse;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/search/unified",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/search/unified";
  export const random = (): ICommunityPlatformPost.IUnifiedResponse =>
    typia.random<ICommunityPlatformPost.IUnifiedResponse>();
  export const simulate = (
    connection: IConnection,
    props: unified.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: unified.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
