import { tags } from "typia";

import { ICommunityPlatformCommunity } from "./ICommunityPlatformCommunity";

/**
 * Complete community flair entity representing a flair definition within a specific community. Flairs are badges or markers that help identify users and their roles within the community context. Each flair includes display text, color styling options, activation status, and metadata timestamps for creation, updates, and soft deletion.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformCommunityFlair = {
  /**
   * Unique identifier for the flair definition
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.id. Auto-generated UUID primary key.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Text that appears as the flair badge for user identification
   *
   * @x-autobe-database-schema-property display_text
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.display_text. Must be unique within the community scope.
   */
  display_text: string;

  /**
   * Background color code for the flair badge in hexadecimal format (e.g., '#FF0000')
   *
   * @x-autobe-database-schema-property background_color
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.background_color. Optional hexadecimal color code for flair background styling.
   */
  background_color?: string | null | undefined;

  /**
   * Text color code for optimal readability in hexadecimal format (e.g., '#FFFFFF')
   *
   * @x-autobe-database-schema-property text_color
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.text_color. Optional hexadecimal color code for text styling and readability.
   */
  text_color?: string | null | undefined;

  /**
   * Optional CSS class name for custom styling beyond basic color options
   *
   * @x-autobe-database-schema-property css_class
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.css_class. Optional custom CSS class name for advanced styling beyond basic color options.
   */
  css_class?: string | null | undefined;

  /**
   * Whether this flair is currently active and available for user assignment
   *
   * @x-autobe-database-schema-property is_active
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.is_active. Controls whether this flair is available for assignment to users.
   */
  is_active: boolean;

  /**
   * Timestamp when the flair definition was created
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.created_at. Timestamp when the flair definition was initially created.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the flair definition was last updated
   *
   * @x-autobe-database-schema-property updated_at
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.updated_at. Timestamp when the flair definition was last modified.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the flair was soft-deleted, null if currently active
   *
   * @x-autobe-database-schema-property deleted_at
   * @x-autobe-specification Direct mapping from community_platform_community_flairs.deleted_at. Timestamp when the flair was soft-deleted, null if active.
   */
  deleted_at: (string & tags.Format<"date-time">) | null;

  /**
   * Community that owns this flair definition.
   *
   * @x-autobe-specification Join via community_platform_communities using community_platform_community_flairs.community_platform_community_id. Returns ISummary.
   * @x-autobe-database-schema-property community
   */
  community: ICommunityPlatformCommunity.ISummary;
};
export namespace ICommunityPlatformCommunityFlair {
  /**
   * Request body for updating community-specific flair definitions. Allows modification of display properties, color scheme, custom styling, and activation status. All fields are optional to support partial updates without requiring complete object replacement.
   */
  export type IUpdate = {
    /**
     * The text that appears as the flair badge. Must be unique within the community.
     *
     * @x-autobe-database-schema-property display_text
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.display_text. Must be unique within the same community. Validated for uniqueness during update operation.
     */
    display_text?: string | undefined;

    /**
     * Background color code for the flair badge. Optional - null means use default background.
     *
     * @x-autobe-database-schema-property background_color
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.background_color. Optional field for custom background color styling. Null value means use default background.
     */
    background_color?: string | null | undefined;

    /**
     * Text color code for optimal readability. Optional - null means use default text color.
     *
     * @x-autobe-database-schema-property text_color
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.text_color. Optional field for custom text color styling. Null value means use default text color for optimal readability.
     */
    text_color?: string | null | undefined;

    /**
     * Optional CSS class for custom styling. Null means no custom CSS applied.
     *
     * @x-autobe-database-schema-property css_class
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.css_class. Optional field for custom CSS styling classes. Null value means no custom CSS applied.
     */
    css_class?: string | null | undefined;

    /**
     * Whether this flair is currently available for assignment.
     *
     * @x-autobe-database-schema-property is_active
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.is_active. Controls whether this flair is available for assignment within the community.
     */
    is_active?: boolean | undefined;
  };

  /**
   * Lightweight summary of community flair information suitable for list displays and management interfaces. Includes core identification fields and status information while excluding detailed styling properties for optimal performance in summary contexts.
   */
  export type ISummary = {
    /**
     * Unique identifier for the community flair
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.id. UUID primary key.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Text content displayed as the flair badge
     *
     * @x-autobe-database-schema-property display_text
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.display_text. Text that appears as the flair badge.
     */
    display_text: string;

    /**
     * Indicates whether this flair is currently available for assignment
     *
     * @x-autobe-database-schema-property is_active
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.is_active. Boolean flag indicating availability for assignment.
     */
    is_active: boolean;

    /**
     * Creation timestamp of the flair definition
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from community_platform_community_flairs.created_at. Timestamp when the flair was created.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * The community that owns this flair definition
     *
     * @x-autobe-database-schema-property community
     * @x-autobe-specification Join via community_platform_community_id foreign key. Returns ICommunityPlatformCommunity.ISummary for community context.
     */
    community: ICommunityPlatformCommunity.ISummary;
  };

  /**
   * Request body for creating a new community flair definition. Community flairs are badges or markers that help identify users and their roles within specific communities. Each flair includes display text, color styling options, and activation status for assignment management.
   */
  export type ICreate = {
    /**
     * Text that appears as the flair badge. Must be unique within the community to prevent duplicate flair definitions.
     *
     * @x-autobe-database-schema-property display_text
     * @x-autobe-specification Direct mapping from user input to community_platform_community_flairs.display_text. Must be unique within the community scope.
     */
    display_text: string;

    /**
     * Background color code for the flair badge in hexadecimal format (e.g., '#FF0000'). Optional for flexible styling.
     *
     * @x-autobe-database-schema-property background_color
     * @x-autobe-specification Direct mapping from user input to community_platform_community_flairs.background_color. Optional field for visual customization.
     */
    background_color?: string | null | undefined;

    /**
     * Text color code for optimal readability in hexadecimal format (e.g., '#FFFFFF'). Optional for flexible styling.
     *
     * @x-autobe-database-schema-property text_color
     * @x-autobe-specification Direct mapping from user input to community_platform_community_flairs.text_color. Optional field for readability optimization.
     */
    text_color?: string | null | undefined;

    /**
     * Optional CSS class name for custom styling beyond basic color options.
     *
     * @x-autobe-database-schema-property css_class
     * @x-autobe-specification Direct mapping from user input to community_platform_community_flairs.css_class. Optional field for advanced styling beyond basic colors.
     */
    css_class?: string | null | undefined;

    /**
     * Whether this flair is immediately available for assignment. Defaults to true if not specified.
     *
     * @x-autobe-database-schema-property is_active
     * @x-autobe-specification Direct mapping from user input to community_platform_community_flairs.is_active. Defaults to true if not specified.
     */
    is_active?: boolean | undefined;
  };

  /**
   * Search criteria and filtering parameters for community flairs within a specific community. Supports text-based search on flair display names, status filtering (active/inactive), and pagination controls for efficient result management.
   */
  export type IRequest = {
    /**
     * Text search query for flair display names using pattern matching
     *
     * @x-autobe-specification Text search parameter using PostgreSQL trigram similarity search (gin_trgm_ops) on display_text field. Supports partial matching and fuzzy search capabilities.
     */
    search?: string | undefined;

    /**
     * Filter by active status (true for active flairs, false for inactive)
     *
     * @x-autobe-specification Boolean filter parameter for active/inactive flairs. When true, returns only active flairs; when false, returns only inactive flairs; when null/undefined, returns all flairs regardless of status.
     */
    isActive?: boolean | undefined;

    /**
     * Page number for pagination (1-based)
     *
     * @x-autobe-specification 1-based page number for pagination. Used with limit parameter to implement offset-based pagination for large result sets.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of results per page (1-100)
     *
     * @x-autobe-specification Number of records per page for pagination. Maximum value of 100 to prevent excessive resource usage. Used with page parameter for result pagination.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };
}
