import { Module } from "@nestjs/common";

import { AuthGuestController } from "./controllers/auth/guest/AuthGuestController";
import { AuthRegistereduserController } from "./controllers/auth/registeredUser/AuthRegistereduserController";
import { AuthCommunitymoderatorController } from "./controllers/auth/communityModerator/AuthCommunitymoderatorController";
import { AuthAdminController } from "./controllers/auth/admin/AuthAdminController";
import { RedditcommunityAdminRedditcommunitysystemsettingsController } from "./controllers/redditCommunity/admin/redditCommunitySystemSettings/RedditcommunityAdminRedditcommunitysystemsettingsController";
import { RedditcommunityRedditcommunityGuestsController } from "./controllers/redditCommunity/redditCommunity/guests/RedditcommunityRedditcommunityGuestsController";
import { RedditcommunityAdminRedditcommunityGuestsController } from "./controllers/redditCommunity/admin/redditCommunity/guests/RedditcommunityAdminRedditcommunityGuestsController";
import { RedditcommunityAdminRedditcommunityRegisteredusersController } from "./controllers/redditCommunity/admin/redditCommunity/registeredUsers/RedditcommunityAdminRedditcommunityRegisteredusersController";
import { RedditcommunityRedditcommunityRegisteredusersController } from "./controllers/redditCommunity/redditCommunity/registeredUsers/RedditcommunityRedditcommunityRegisteredusersController";
import { RedditcommunityRegistereduserRedditcommunityRegisteredusersController } from "./controllers/redditCommunity/registeredUser/redditCommunity/registeredUsers/RedditcommunityRegistereduserRedditcommunityRegisteredusersController";
import { RedditcommunityAdminRedditcommunityRegisteredusersRegisteredusersessionsController } from "./controllers/redditCommunity/admin/redditCommunity/registeredUsers/registeredUserSessions/RedditcommunityAdminRedditcommunityRegisteredusersRegisteredusersessionsController";
import { RedditcommunityRegistereduserRedditcommunityRegisteredusersRegisteredusersessionsController } from "./controllers/redditCommunity/registeredUser/redditCommunity/registeredUsers/registeredUserSessions/RedditcommunityRegistereduserRedditcommunityRegisteredusersRegisteredusersessionsController";
import { RedditcommunityAdminRedditcommunityCommunitymoderatorsController } from "./controllers/redditCommunity/admin/redditCommunity/communityModerators/RedditcommunityAdminRedditcommunityCommunitymoderatorsController";
import { RedditcommunityAdminRedditcommunityCommunitymoderatorsCommunitymoderatorsessionsController } from "./controllers/redditCommunity/admin/redditCommunity/communityModerators/communityModeratorSessions/RedditcommunityAdminRedditcommunityCommunitymoderatorsCommunitymoderatorsessionsController";
import { RedditcommunityCommunitymoderatorRedditcommunityCommunitymoderatorsCommunitymoderatorsessionsController } from "./controllers/redditCommunity/communityModerator/redditCommunity/communityModerators/communityModeratorSessions/RedditcommunityCommunitymoderatorRedditcommunityCommunitymoderatorsCommunitymoderatorsessionsController";
import { RedditcommunityAdminRedditcommunityAdminsController } from "./controllers/redditCommunity/admin/redditCommunity/admins/RedditcommunityAdminRedditcommunityAdminsController";
import { RedditcommunityAdminRedditcommunityAdminsAdminsessionsController } from "./controllers/redditCommunity/admin/redditCommunity/admins/adminSessions/RedditcommunityAdminRedditcommunityAdminsAdminsessionsController";
import { RedditcommunityCommunitiesController } from "./controllers/redditCommunity/communities/RedditcommunityCommunitiesController";
import { RedditcommunityRegistereduserCommunitiesController } from "./controllers/redditCommunity/registeredUser/communities/RedditcommunityRegistereduserCommunitiesController";
import { RedditcommunityAdminCommunitiesController } from "./controllers/redditCommunity/admin/communities/RedditcommunityAdminCommunitiesController";
import { RedditcommunityCommunitymoderatorCommunitiesController } from "./controllers/redditCommunity/communityModerator/communities/RedditcommunityCommunitymoderatorCommunitiesController";
import { RedditcommunityAdminCommunitiesCommunitymoderatorassignmentsController } from "./controllers/redditCommunity/admin/communities/communityModeratorAssignments/RedditcommunityAdminCommunitiesCommunitymoderatorassignmentsController";
import { RedditcommunityCommunitymoderatorCommunitiesCommunitymoderatorassignmentsController } from "./controllers/redditCommunity/communityModerator/communities/communityModeratorAssignments/RedditcommunityCommunitymoderatorCommunitiesCommunitymoderatorassignmentsController";
import { RedditcommunityPostsController } from "./controllers/redditCommunity/posts/RedditcommunityPostsController";
import { RedditcommunityRegistereduserPostsController } from "./controllers/redditCommunity/registeredUser/posts/RedditcommunityRegistereduserPostsController";
import { RedditcommunityCommunitymoderatorPostsController } from "./controllers/redditCommunity/communityModerator/posts/RedditcommunityCommunitymoderatorPostsController";
import { RedditcommunityAdminPostsController } from "./controllers/redditCommunity/admin/posts/RedditcommunityAdminPostsController";
import { RedditcommunityRegistereduserPostsPostimagesController } from "./controllers/redditCommunity/registeredUser/posts/postImages/RedditcommunityRegistereduserPostsPostimagesController";
import { RedditcommunityRegistereduserRedditcommunitycommentsController } from "./controllers/redditCommunity/registeredUser/redditCommunityComments/RedditcommunityRegistereduserRedditcommunitycommentsController";
import { RedditcommunityAdminRedditcommunitypostvotesController } from "./controllers/redditCommunity/admin/redditCommunityPostVotes/RedditcommunityAdminRedditcommunitypostvotesController";
import { RedditcommunityRegistereduserRedditcommunitypostvotesController } from "./controllers/redditCommunity/registeredUser/redditCommunityPostVotes/RedditcommunityRegistereduserRedditcommunitypostvotesController";
import { RedditcommunityAdminRedditcommunitycommentvotesController } from "./controllers/redditCommunity/admin/redditCommunityCommentVotes/RedditcommunityAdminRedditcommunitycommentvotesController";
import { RedditcommunityRegistereduserRedditcommunitycommentvotesController } from "./controllers/redditCommunity/registeredUser/redditCommunityCommentVotes/RedditcommunityRegistereduserRedditcommunitycommentvotesController";
import { RedditcommunityRegistereduserRedditcommunitysubscriptionsController } from "./controllers/redditCommunity/registeredUser/redditCommunitySubscriptions/RedditcommunityRegistereduserRedditcommunitysubscriptionsController";
import { RedditcommunityAdminRedditcommunityuserkarmaController } from "./controllers/redditCommunity/admin/redditCommunityUserKarma/RedditcommunityAdminRedditcommunityuserkarmaController";
import { RedditcommunityAdminRedditcommunityreportsController } from "./controllers/redditCommunity/admin/redditCommunityReports/RedditcommunityAdminRedditcommunityreportsController";
import { RedditcommunityCommunitymoderatorRedditcommunityreportsController } from "./controllers/redditCommunity/communityModerator/redditCommunityReports/RedditcommunityCommunitymoderatorRedditcommunityreportsController";

@Module({
  controllers: [
    AuthGuestController,
    AuthRegistereduserController,
    AuthCommunitymoderatorController,
    AuthAdminController,
    RedditcommunityAdminRedditcommunitysystemsettingsController,
    RedditcommunityRedditcommunityGuestsController,
    RedditcommunityAdminRedditcommunityGuestsController,
    RedditcommunityAdminRedditcommunityRegisteredusersController,
    RedditcommunityRedditcommunityRegisteredusersController,
    RedditcommunityRegistereduserRedditcommunityRegisteredusersController,
    RedditcommunityAdminRedditcommunityRegisteredusersRegisteredusersessionsController,
    RedditcommunityRegistereduserRedditcommunityRegisteredusersRegisteredusersessionsController,
    RedditcommunityAdminRedditcommunityCommunitymoderatorsController,
    RedditcommunityAdminRedditcommunityCommunitymoderatorsCommunitymoderatorsessionsController,
    RedditcommunityCommunitymoderatorRedditcommunityCommunitymoderatorsCommunitymoderatorsessionsController,
    RedditcommunityAdminRedditcommunityAdminsController,
    RedditcommunityAdminRedditcommunityAdminsAdminsessionsController,
    RedditcommunityCommunitiesController,
    RedditcommunityRegistereduserCommunitiesController,
    RedditcommunityAdminCommunitiesController,
    RedditcommunityCommunitymoderatorCommunitiesController,
    RedditcommunityAdminCommunitiesCommunitymoderatorassignmentsController,
    RedditcommunityCommunitymoderatorCommunitiesCommunitymoderatorassignmentsController,
    RedditcommunityPostsController,
    RedditcommunityRegistereduserPostsController,
    RedditcommunityCommunitymoderatorPostsController,
    RedditcommunityAdminPostsController,
    RedditcommunityRegistereduserPostsPostimagesController,
    RedditcommunityRegistereduserRedditcommunitycommentsController,
    RedditcommunityAdminRedditcommunitypostvotesController,
    RedditcommunityRegistereduserRedditcommunitypostvotesController,
    RedditcommunityAdminRedditcommunitycommentvotesController,
    RedditcommunityRegistereduserRedditcommunitycommentvotesController,
    RedditcommunityRegistereduserRedditcommunitysubscriptionsController,
    RedditcommunityAdminRedditcommunityuserkarmaController,
    RedditcommunityAdminRedditcommunityreportsController,
    RedditcommunityCommunitymoderatorRedditcommunityreportsController,
  ],
})
export class MyModule {}
