import { Module } from "@nestjs/common";

import { AuthGuestController } from "./controllers/auth/guest/AuthGuestController";
import { AuthRegistereduserController } from "./controllers/auth/registeredUser/AuthRegistereduserController";
import { AuthModeratorController } from "./controllers/auth/moderator/AuthModeratorController";
import { AuthAdminController } from "./controllers/auth/admin/AuthAdminController";
import { RedditcommunityRedditcommunityguestsController } from "./controllers/redditCommunity/redditCommunityGuests/RedditcommunityRedditcommunityguestsController";
import { RedditcommunityAdminRedditcommunityguestsController } from "./controllers/redditCommunity/admin/redditCommunityGuests/RedditcommunityAdminRedditcommunityguestsController";
import { RedditcommunityAdminRedditcommunityguestsSessionsController } from "./controllers/redditCommunity/admin/redditCommunityGuests/sessions/RedditcommunityAdminRedditcommunityguestsSessionsController";
import { RedditcommunityRedditcommunityguestsSessionsController } from "./controllers/redditCommunity/redditCommunityGuests/sessions/RedditcommunityRedditcommunityguestsSessionsController";
import { RedditcommunityAdminRedditcommunityregisteredusersController } from "./controllers/redditCommunity/admin/redditCommunityRegisteredusers/RedditcommunityAdminRedditcommunityregisteredusersController";
import { RedditcommunityRedditcommunityregisteredusersController } from "./controllers/redditCommunity/redditCommunityRegisteredusers/RedditcommunityRedditcommunityregisteredusersController";
import { RedditcommunityRegistereduserRedditcommunityregisteredusersController } from "./controllers/redditCommunity/registeredUser/redditCommunityRegisteredusers/RedditcommunityRegistereduserRedditcommunityregisteredusersController";
import { RedditcommunityAdminRedditcommunityregisteredusersSessionsController } from "./controllers/redditCommunity/admin/redditCommunityRegisteredusers/sessions/RedditcommunityAdminRedditcommunityregisteredusersSessionsController";
import { RedditcommunityRegistereduserRedditcommunityregisteredusersSessionsController } from "./controllers/redditCommunity/registeredUser/redditCommunityRegisteredusers/sessions/RedditcommunityRegistereduserRedditcommunityregisteredusersSessionsController";
import { RedditcommunityAdminRedditcommunitymoderatorsController } from "./controllers/redditCommunity/admin/redditCommunityModerators/RedditcommunityAdminRedditcommunitymoderatorsController";
import { RedditcommunityAdminRedditcommunitymoderatorsSessionsController } from "./controllers/redditCommunity/admin/redditCommunityModerators/sessions/RedditcommunityAdminRedditcommunitymoderatorsSessionsController";
import { RedditcommunityModeratorRedditcommunitymoderatorsSessionsController } from "./controllers/redditCommunity/moderator/redditCommunityModerators/sessions/RedditcommunityModeratorRedditcommunitymoderatorsSessionsController";
import { RedditcommunityAdminRedditcommunityadminsController } from "./controllers/redditCommunity/admin/redditCommunityAdmins/RedditcommunityAdminRedditcommunityadminsController";
import { RedditcommunityAdminRedditcommunityadminsSessionsController } from "./controllers/redditCommunity/admin/redditCommunityAdmins/sessions/RedditcommunityAdminRedditcommunityadminsSessionsController";
import { RedditcommunityRedditcommunityCommunitiesController } from "./controllers/redditCommunity/redditCommunity/communities/RedditcommunityRedditcommunityCommunitiesController";
import { RedditcommunityRegistereduserRedditcommunityCommunitiesController } from "./controllers/redditCommunity/registeredUser/redditCommunity/communities/RedditcommunityRegistereduserRedditcommunityCommunitiesController";
import { RedditcommunityAdminRedditcommunityCommunitiesController } from "./controllers/redditCommunity/admin/redditCommunity/communities/RedditcommunityAdminRedditcommunityCommunitiesController";
import { RedditcommunityRegistereduserRedditcommunityCommunitiesCommunitysubscriptionsController } from "./controllers/redditCommunity/registeredUser/redditCommunity/communities/communitySubscriptions/RedditcommunityRegistereduserRedditcommunityCommunitiesCommunitysubscriptionsController";
import { RedditcommunityRegistereduserRedditcommunityPostsController } from "./controllers/redditCommunity/registeredUser/redditCommunity/posts/RedditcommunityRegistereduserRedditcommunityPostsController";
import { RedditcommunityRedditcommunityPostsCommentsController } from "./controllers/redditCommunity/redditCommunity/posts/comments/RedditcommunityRedditcommunityPostsCommentsController";
import { RedditcommunityRegistereduserRedditcommunityPostsCommentsController } from "./controllers/redditCommunity/registeredUser/redditCommunity/posts/comments/RedditcommunityRegistereduserRedditcommunityPostsCommentsController";
import { RedditcommunityRegistereduserRedditcommunityPostsPostvotesController } from "./controllers/redditCommunity/registeredUser/redditCommunity/posts/postVotes/RedditcommunityRegistereduserRedditcommunityPostsPostvotesController";
import { RedditcommunityRegistereduserRedditcommunityPostsCommentsCommentvotesController } from "./controllers/redditCommunity/registeredUser/redditCommunity/posts/comments/commentVotes/RedditcommunityRegistereduserRedditcommunityPostsCommentsCommentvotesController";
import { RedditcommunityModeratorRedditcommunityPostsCommentsCommentvotesController } from "./controllers/redditCommunity/moderator/redditCommunity/posts/comments/commentVotes/RedditcommunityModeratorRedditcommunityPostsCommentsCommentvotesController";
import { RedditcommunityAdminRedditcommunitypostreportsController } from "./controllers/redditCommunity/admin/redditCommunityPostReports/RedditcommunityAdminRedditcommunitypostreportsController";
import { RedditcommunityRegistereduserRedditcommunitypostreportsController } from "./controllers/redditCommunity/registeredUser/redditCommunityPostReports/RedditcommunityRegistereduserRedditcommunitypostreportsController";
import { RedditcommunityModeratorRedditcommunitypostreportsController } from "./controllers/redditCommunity/moderator/redditCommunityPostReports/RedditcommunityModeratorRedditcommunitypostreportsController";
import { RedditcommunityModeratorRedditcommunitycommentreportsController } from "./controllers/redditCommunity/moderator/redditCommunityCommentReports/RedditcommunityModeratorRedditcommunitycommentreportsController";
import { RedditcommunityAdminRedditcommunitycommentreportsController } from "./controllers/redditCommunity/admin/redditCommunityCommentReports/RedditcommunityAdminRedditcommunitycommentreportsController";
import { RedditcommunityRegistereduserRedditcommunitycommentreportsController } from "./controllers/redditCommunity/registeredUser/redditCommunityCommentReports/RedditcommunityRegistereduserRedditcommunitycommentreportsController";
import { RedditcommunityAdminRedditcommunitysystemconfigurationsController } from "./controllers/redditCommunity/admin/redditCommunitySystemConfigurations/RedditcommunityAdminRedditcommunitysystemconfigurationsController";

@Module({
  controllers: [
    AuthGuestController,
    AuthRegistereduserController,
    AuthModeratorController,
    AuthAdminController,
    RedditcommunityRedditcommunityguestsController,
    RedditcommunityAdminRedditcommunityguestsController,
    RedditcommunityAdminRedditcommunityguestsSessionsController,
    RedditcommunityRedditcommunityguestsSessionsController,
    RedditcommunityAdminRedditcommunityregisteredusersController,
    RedditcommunityRedditcommunityregisteredusersController,
    RedditcommunityRegistereduserRedditcommunityregisteredusersController,
    RedditcommunityAdminRedditcommunityregisteredusersSessionsController,
    RedditcommunityRegistereduserRedditcommunityregisteredusersSessionsController,
    RedditcommunityAdminRedditcommunitymoderatorsController,
    RedditcommunityAdminRedditcommunitymoderatorsSessionsController,
    RedditcommunityModeratorRedditcommunitymoderatorsSessionsController,
    RedditcommunityAdminRedditcommunityadminsController,
    RedditcommunityAdminRedditcommunityadminsSessionsController,
    RedditcommunityRedditcommunityCommunitiesController,
    RedditcommunityRegistereduserRedditcommunityCommunitiesController,
    RedditcommunityAdminRedditcommunityCommunitiesController,
    RedditcommunityRegistereduserRedditcommunityCommunitiesCommunitysubscriptionsController,
    RedditcommunityRegistereduserRedditcommunityPostsController,
    RedditcommunityRedditcommunityPostsCommentsController,
    RedditcommunityRegistereduserRedditcommunityPostsCommentsController,
    RedditcommunityRegistereduserRedditcommunityPostsPostvotesController,
    RedditcommunityRegistereduserRedditcommunityPostsCommentsCommentvotesController,
    RedditcommunityModeratorRedditcommunityPostsCommentsCommentvotesController,
    RedditcommunityAdminRedditcommunitypostreportsController,
    RedditcommunityRegistereduserRedditcommunitypostreportsController,
    RedditcommunityModeratorRedditcommunitypostreportsController,
    RedditcommunityModeratorRedditcommunitycommentreportsController,
    RedditcommunityAdminRedditcommunitycommentreportsController,
    RedditcommunityRegistereduserRedditcommunitycommentreportsController,
    RedditcommunityAdminRedditcommunitysystemconfigurationsController,
  ],
})
export class MyModule {}
