import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IPageITodoAppEditHistory } from "../../../../../api/structures/IPageITodoAppEditHistory";
import { ITodoAppEditHistory } from "../../../../../api/structures/ITodoAppEditHistory";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { getTodoAppMemberTodosTodoIdEditHistoriesHistoryId } from "../../../../../providers/getTodoAppMemberTodosTodoIdEditHistoriesHistoryId";
import { patchTodoAppMemberTodosTodoIdEditHistories } from "../../../../../providers/patchTodoAppMemberTodosTodoIdEditHistories";

@Controller("/todoApp/member/todos/:todoId/edit-histories")
export class TodoappMemberTodosEdit_historiesController {
  /**
   * Retrieve the paginated edit history for a specific todo.
   *
   * Every time a todo is edited, a history entry is automatically created recording which fields were changed and what their new values are. This endpoint returns those entries in reverse chronological order so you can see the most recent edits first.
   *
   * Each history entry contains a timestamp and the new values for any fields that changed during that edit. Fields that remained unchanged are omitted (null). Clearing an optional field (description, start date, due date) records the field as cleared.
   *
   * History is read-only — entries are immutable once created and cannot be modified or deleted except when the parent todo is permanently removed. Access is restricted to the member who owns the todo.
   *
   * @param connection
   * @param todoId The UUID of the todo whose edit history is being retrieved. (UUID format)
   * @param body Pagination and sorting parameters for browsing the edit history. Supports page number, page size, and sort direction by creation timestamp.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Query todo_app_edit_histories filtered by todo_app_todo_id = {todoId}. Verify the todo exists and belongs to the authenticated member (todo_app_member_id = current member ID) before returning results — if the todo doesn't exist or belongs to another user, return 404 Not Found (don't distinguish between non-existent and inaccessible).
   *
   * Apply pagination (page, limit) with cursor-based or offset pagination. Sort by created_at DESC (most recent first) by default. Support optional sort direction override via request body.
   *
   * The response items show changed-only fields: for each entry, include created_at, and include title/description/start_date/due_date only when they are non-null (the field was changed in that edit).
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("todoId")
    todoId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ITodoAppEditHistory.IRequest,
  ): Promise<IPageITodoAppEditHistory.ISummary> {
    try {
      return await patchTodoAppMemberTodosTodoIdEditHistories({
        member,
        todoId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieves the full details of a single edit history entry for a specific todo owned by the authenticated member.
   *
   * Each edit history entry is automatically created whenever a todo's fields (title, description, start date, or due date) are modified. The entry records what the fields were changed to, with unchanged fields stored as null. History entries are immutable after creation and are sorted from most recent to oldest.
   *
   * Access is restricted to the member who owns the parent todo. If the todo does not exist or belongs to another user, a 404 Not Found error is returned without revealing whether the resource exists.
   *
   * @param connection
   * @param todoId The UUID of the todo whose edit history entry is being retrieved.
   * @param historyId The UUID of the edit history entry to retrieve. Must belong to the specified todo.
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Validate that the authenticated member owns the todo identified by todoId. If the todo does not exist or its member_id does not match the authenticated member, return a 404 Not Found error without distinguishing between non-existent and inaccessible resources. Query the edit_histories table with the given historyId and verify that todo_app_todo_id matches todoId. Return the full edit history entry including id, created_at, title, description, start_date, and due_date fields.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":historyId")
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("todoId")
    todoId: string & tags.Format<"uuid">,
    @TypedParam("historyId")
    historyId: string & tags.Format<"uuid">,
  ): Promise<ITodoAppEditHistory> {
    try {
      return await getTodoAppMemberTodosTodoIdEditHistoriesHistoryId({
        member,
        todoId,
        historyId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
