import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IHrmTimeTrackingProject } from "../../../../api/structures/IHrmTimeTrackingProject";
import { IPageIHrmTimeTrackingProject } from "../../../../api/structures/IPageIHrmTimeTrackingProject";
import { MemberAuth } from "../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../decorators/payload/MemberPayload";
import { deleteHrmTimeTrackingMemberProjectsProjectId } from "../../../../providers/deleteHrmTimeTrackingMemberProjectsProjectId";
import { getHrmTimeTrackingMemberProjectsProjectId } from "../../../../providers/getHrmTimeTrackingMemberProjectsProjectId";
import { patchHrmTimeTrackingMemberProjects } from "../../../../providers/patchHrmTimeTrackingMemberProjects";
import { postHrmTimeTrackingMemberProjects } from "../../../../providers/postHrmTimeTrackingMemberProjects";
import { putHrmTimeTrackingMemberProjectsProjectId } from "../../../../providers/putHrmTimeTrackingMemberProjectsProjectId";

@Controller("/hrmTimeTracking/member/projects")
export class HrmtimetrackingMemberProjectsController {
  /**
   * Creates a new project within the user's currently selected organization.
   *
   * The project serves as a container for time tracking, task management, and reporting activities. When created, the project defaults to 'active' status, allowing employees assigned as project members to log time, create tasks, and manage project activities. Optional fields include a description for project scope, a budget_hours value for planned vs. actual hour comparisons, and start/end dates for timeline and scheduling views.
   *
   * The authenticated user's current organization context determines which organization the project belongs to. The color_code (hex format, e.g., '#FF5733') enables visual differentiation in project selection dropdowns and timelog entry displays. System-generated fields such as id, created_at, updated_at, and status are populated automatically and returned in the response.
   *
   * @param connection
   * @param body Project creation payload with the new project's display name, hex color code for UI differentiation, optional description, optional budget hours for planning, and optional start/end dates for project timeline.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query: Insert a new record into
     *   hrm_time_tracking_projects table with the provided fields.
   *
   * Fields to include in insert:
   * - id: auto-generated UUID
   * - hrm_time_tracking_organization_id: derived from the authenticated user's current organization context (not from request body)
   * - name: required from request
   * - description: optional from request
   * - color_code: required from request (hex color string)
   * - status: defaults to 'active' (not accepted from request body)
   * - budget_hours: optional from request (double precision)
   * - started_at: optional from request
   * - ended_at: optional from request
   * - created_at: current timestamp
   * - updated_at: current timestamp
   * - deleted_at: null (not soft-deleted on creation)
   *
   * Validation rules:
   * - Name must be a non-empty string
   * - Color_code must be a valid hex color code (e.g., '#FF5733')
   * - If provided, budget_hours must be a non-negative number
   * - If provided, started_at and ended_at must be valid ISO 8601 timestamps; ended_at must not be before started_at
   * - The organization must exist and be 'active'; if the organization is 'deleted', reject the creation
   *
   * The created project record is returned as the response body with all populated fields.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @MemberAuth()
    member: MemberPayload,
    @TypedBody()
    body: IHrmTimeTrackingProject.ICreate,
  ): Promise<IHrmTimeTrackingProject> {
    try {
      return await postHrmTimeTrackingMemberProjects({
        member,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Search and list projects within the current organization.
   *
   * This endpoint returns a paginated, filterable list of projects for the authenticated user's active organization context. It is designed for project management interfaces, project selector dropdowns, and dashboard widgets that need to display project summaries.
   *
   * Supports filtering by project name (partial match), lifecycle status (active, archived, completed), date ranges on start and end dates, and budget hour ranges. Results are sorted by creation date by default (newest first) with configurable sorting options. Soft-deleted projects are excluded from results.
   *
   * Each project summary includes the project's identity attributes (name, color code), lifecycle status, and planning attributes (budget hours, start/end dates) for efficient list rendering without loading full project details.
   *
   * @param connection
   * @param body Search criteria for filtering and paginating projects within the organization. Supports partial name search, status filtering, date range filters on planning dates, budget hour range, sorting, and cursor/offset-based pagination.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query hrm_time_tracking_projects table scoped to
     *   the authenticated user's current organization
     *   (hrm_time_tracking_organization_id from session context).
   *
   * Apply search and filter criteria from the request body:
   * - name: partial match search on the project name field (case-insensitive LIKE/ILIKE)
   * - status: filter by project lifecycle status (active, archived, completed) — may be a single value or array to allow multi-status filtering
   * - startedAtRange: date range filter on started_at (gte/lte)
   * - endedAtRange: date range filter on ended_at (gte/lte)
   * - budgetHoursRange: numeric range filter on budget_hours (gte/lte)
   * - colorCode: exact match filter on color_code
   *
   * Exclude soft-deleted records (WHERE deleted_at IS NULL).
   *
   * Support pagination via page/limit parameters in the request body. Default sorting by created_at descending. Support sortable fields: name, status, created_at, started_at, ended_at, budget_hours.
   *
   * Include total count for pagination metadata. Return summary fields only (id, name, status, color_code, budget_hours, started_at, ended_at, createdAt) — exclude full description for listing performance.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedBody()
    body: IHrmTimeTrackingProject.IRequest,
  ): Promise<IPageIHrmTimeTrackingProject.ISummary> {
    try {
      return await patchHrmTimeTrackingMemberProjects({
        member,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a single project by its unique identifier.
   *
   * Returns the full project record including name, description, color code, current status, optional budget hours, and optional start/end dates. The project status indicates the current lifecycle stage: 'active' (accepting new timelogs and tasks), 'archived' (data preserved but no new entries), or 'completed' (finished state with data preserved for historical reference).
   *
   * The response includes the organization ID for context, but the operation automatically scopes to the authenticated user's organization.
   *
   * Soft-deleted projects are excluded from this endpoint and return a not-found response.
   *
   * @param connection
   * @param projectId The unique identifier (UUID) of the project to retrieve.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query hrm_time_tracking_projects by primary key
     *   id matching {projectId}.
   *
   * 1. Scoped to the authenticated user's selected organization — hrm_time_tracking_organization_id must match the user's current organization context.
   * 2. Respect soft deletion: if deleted_at is non-null, treat as not found (return 404 or equivalent).
   * 3. Return the complete project record including: id, organization_id, name, description, color_code, status, budget_hours, started_at, ended_at, created_at, updated_at.
   * 4. The status field contains one of: 'active', 'archived', 'completed'.
   * 5. No JOINs needed for the base response — this returns the raw project entity.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":projectId")
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("projectId")
    projectId: string & tags.Format<"uuid">,
  ): Promise<IHrmTimeTrackingProject> {
    try {
      return await getHrmTimeTrackingMemberProjectsProjectId({
        member,
        projectId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update an existing project's attributes within the current organization context.
   *
   * The authenticated member must hold the `project:manage` permission within the organization to perform this operation. Only projects belonging to the member's currently selected organization can be updated — cross-organization access is strictly prevented.
   *
   * The following project attributes are editable: name, description, color code, status, budget hours, start date, and end date. Status transitions follow the project lifecycle flow: projects can be archived or completed from active status. Archived and completed projects cannot receive new timelogs but this endpoint only updates project metadata. Budget hours must be zero or a positive number. If both start and end dates are provided, the start date must be on or before the end date. The operation validates the target project exists and is not soft-deleted before applying changes.
   *
   * @param connection
   * @param projectId UUID primary key of the project to update. Must correspond to an existing non-deleted project within the current organization context.
   * @param body Updated project attributes. Only editable fields are accepted — system-managed fields (id, organization_id, created_at, updated_at, deleted_at) are ignored or rejected.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query hrm_time_tracking_projects by id and verify
     *   the project belongs to the currently selected organization
     *   (hrm_time_tracking_organization_id from member's session context).
   *
   * Verify the authenticated member has project:manage permission within the organization.
   *
   * Check that the project is not soft-deleted (deleted_at IS NULL) — if deleted, return 404 Not Found. If no project exists with the given id, return 404 Not Found.
   *
   * Validate the request body fields:
   * - name: required, non-empty string
   * - color_code: required, valid hex color string (e.g., '#FF5733')
   * - status: must be one of 'active', 'archived', 'completed'
   * - budget_hours: must be null or >= 0 (reject negative values)
   * - started_at / ended_at: if both provided, started_at must be <= ended_at
   * - description: optional, free-form text
   *
   * Status transition rules:
   * - Active projects can transition to 'archived' or 'completed'
   * - Archived/completed projects can only update other non-status fields (status remains unchanged) — transitions back to 'active' from 'archived'/'completed' are not supported per lifecycle rules
   *
   * Update the record with new values, set updated_at to current timestamp.
   *
   * Return the complete updated project record including all fields.
   *
   * Error cases:
   * - 403 Forbidden: member lacks project:manage permission
   * - 404 Not Found: project does not exist or is already deleted
   * - 422 Validation Error: invalid field values (bad status, negative budget, date conflict, missing required fields)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":projectId")
  public async update(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("projectId")
    projectId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IHrmTimeTrackingProject.IUpdate,
  ): Promise<IHrmTimeTrackingProject> {
    try {
      return await putHrmTimeTrackingMemberProjectsProjectId({
        member,
        projectId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Soft-delete a project within the organization.
   *
   * This operation removes a project from active use while preserving its historical data — including associated timelogs, tasks, timesheets, and project member records — for audit and reporting purposes. The project's `deleted_at` timestamp is set to the current time, marking it as inactive without permanent data loss.
   *
   * Deletion is only permitted when the project has no timelogs associated with it. If any timelogs exist, the system rejects the deletion to protect logged time entries. Archived and completed projects can be deleted as long as they have no timelogs.
   *
   * Only users with the `project:manage` permission can delete projects. Built-in roles with this permission include Owner and Manager; custom roles may also be granted this permission. When deletion succeeds, a project-deleted event is fired and delivered to all users with `project:view` permission or higher, as well as to all project members, notifying them that the project no longer exists.
   *
   * @param connection
   * @param projectId The unique identifier (UUID) of the project to delete, scoped to the authenticated user's organization.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Verify the authenticated user has
     *   `project:manage` permission within the current organization session.
     *   Look up the project by `projectId` where
     *   `hrm_time_tracking_organization_id` matches the current org — return
     *   404 if not found or if `deleted_at` is already non-null (already
     *   deleted). Check for associated timelogs: query
     *   `hrm_time_tracking_timelogs` where `hrm_time_tracking_project_id` =
     *   project's id and `deleted_at` is null. If any timelogs exist, reject
     *   with 422 status explaining that projects with existing timelogs cannot
     *   be deleted. Perform soft deletion: set `deleted_at` to current
     *   timestamp and update `updated_at` accordingly. Fire a project-deleted
     *   real-time event with the project details for notification delivery to
     *   authorized users and project members. Return the soft-deleted project
     *   entity (with `deleted_at` populated) as confirmation.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":projectId")
  public async erase(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("projectId")
    projectId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteHrmTimeTrackingMemberProjectsProjectId({
        member,
        projectId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
