import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICivicBoardPasswordResetTokenOfUser } from "../../../../../../structures/ICivicBoardPasswordResetTokenOfUser";

/**
 * Create a password reset token in civic_board_password_reset_tokens for a
 * member identified by email.
 *
 * This operation initiates a password reset for a member account by emitting a
 * token that permits a one-time password change. It inserts a record into
 * civic_board_password_reset_tokens with actor_type set to "user", generates a
 * unique civic_board_password_reset_tokens.token, sets
 * civic_board_password_reset_tokens.expires_at to a policy-driven time in the
 * future, and initializes civic_board_password_reset_tokens.used as false with
 * civic_board_password_reset_tokens.used_at left null until consumption.
 *
 * To associate the token with the correct user, a specialization row is created
 * in civic_board_password_reset_token_of_users linking
 * civic_board_password_reset_token_of_users.civic_board_password_reset_token_id
 * to the token and
 * civic_board_password_reset_token_of_users.civic_board_user_id to the
 * identified civic_board_users row corresponding to the submitted email. The
 * parent civic_board_users record is not modified at this stage.
 *
 * Security behavior avoids leaking account existence by returning a uniform
 * acknowledgement regardless of whether a matching civic_board_users.email was
 * found. Rate limiting can be enforced using civic_board_rate_limits by scope
 * such as "password.reset.request" with actor_type set appropriately.
 *
 * This request endpoint pairs with POST /auth/user/password/reset/confirm which
 * validates the token and sets a new password. Tokens are one-time and
 * time-limited as defined by civic_board_password_reset_tokens.expires_at and
 * civic_board_password_reset_tokens.used.
 *
 * @param props.connection
 * @param props.body Email submission for password reset initiation.
 * @path /auth/user/password/reset/request
 * @accessor api.functional.auth.user.password.reset.request.requestPasswordReset
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function requestPasswordReset(
  connection: IConnection,
  props: requestPasswordReset.Props,
): Promise<requestPasswordReset.Response> {
  return true === connection.simulate
    ? requestPasswordReset.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...requestPasswordReset.METADATA,
          path: requestPasswordReset.path(),
          status: null,
        },
        props.body,
      );
}
export namespace requestPasswordReset {
  export type Props = {
    /** Email submission for password reset initiation. */
    body: ICivicBoardPasswordResetTokenOfUser.IRequest;
  };
  export type Body = ICivicBoardPasswordResetTokenOfUser.IRequest;
  export type Response = ICivicBoardPasswordResetTokenOfUser.ISummary;

  export const METADATA = {
    method: "POST",
    path: "/auth/user/password/reset/request",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/auth/user/password/reset/request";
  export const random = (): ICivicBoardPasswordResetTokenOfUser.ISummary =>
    typia.random<ICivicBoardPasswordResetTokenOfUser.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: requestPasswordReset.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: requestPasswordReset.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
