import { tags } from "typia";

import { ICommunityPlatformComment } from "./ICommunityPlatformComment";
import { ICommunityPlatformPost } from "./ICommunityPlatformPost";
import { ICommunityPlatformReport } from "./ICommunityPlatformReport";

/**
 * Links a user report to either a reported post or comment content, including lifecycle timestamps and soft deletion metadata for moderation workflows.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformReportedContent = {
  /**
   * Unique identifier of the reported content link.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from community_platform_reported_contents.id UUID column.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Unique identifier of the associated user report linking this content.
   *
   * @x-autobe-specification Maps to community_platform_reported_contents.community_platform_report_id UUID column referencing the related user report. Although nullable in database, treated as required in DTO to ensure proper linking.
   * @x-autobe-database-schema-property community_platform_report_id
   */
  communityPlatformReportId: null | null;

  /**
   * Identifier of the reported post, or null if the report is about a comment.
   *
   * @x-autobe-specification Maps to community_platform_reported_post_id UUID column, nullable when report targets comment instead of post.
   * @x-autobe-database-schema-property community_platform_reported_post_id
   */
  communityPlatformReportedPostId: null | null;

  /**
   * Identifier of the reported comment, or null if the report is about a post.
   *
   * @x-autobe-specification Maps to community_platform_reported_comment_id UUID column, nullable when report targets post instead of comment.
   * @x-autobe-database-schema-property community_platform_reported_comment_id
   */
  communityPlatformReportedCommentId: null | null;

  /**
   * Record creation timestamp.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from community_platform_reported_contents.created_at timestamp column.
   */
  createdAt: string & tags.Format<"date-time">;

  /**
   * Record last updated timestamp.
   *
   * @x-autobe-database-schema-property updated_at
   * @x-autobe-specification Direct mapping from community_platform_reported_contents.updated_at timestamp column.
   */
  updatedAt: string & tags.Format<"date-time">;

  /**
   * Nullable timestamp of deletion, or null if active.
   *
   * @x-autobe-database-schema-property deleted_at
   * @x-autobe-specification Direct mapping from community_platform_reported_contents.deleted_at nullable timestamp column indicating soft deletion status.
   */
  deletedAt?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ICommunityPlatformReportedContent {
  /**
   * Request DTO for filtering and paginating reported content records linked to reports, used in administrator and moderator report management APIs.
   */
  export type IRequest = {
    /**
     * Type of the reported content to filter: 'post' or 'comment'.
     *
     * @x-autobe-specification Filter reported contents by their type: "post" for contents linked to reported_post_id, "comment" for reported_comment_id, or null for both types.
     */
    contentType?: "post" | "comment" | null | undefined;

    /**
     * Filter reported contents created after this ISO8601 datetime.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Filters reported contents with created_at greater than the specified datetime.
     */
    createdAfter?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Filter reported contents created before this ISO8601 datetime.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Filters reported contents with created_at less than the specified datetime.
     */
    createdBefore?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Filter by deletion status of the reported content link.
     *
     * @x-autobe-database-schema-property deleted_at
     * @x-autobe-specification Filters reported contents by null or not null deleted_at values for deletion status.
     */
    isDeleted?: boolean | null | undefined;

    /**
     * Pagination page number, starting from 1.
     *
     * @x-autobe-specification Number of the page to return, starting at 1.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of items per page, maximum 100.
     *
     * @x-autobe-specification Maximum number of items per page, capped at 100.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };

  /**
   * Summary representation of a reported content entity linking a report to either a post or a comment. Includes references to report and reported entities as summaries, with timestamps and deletion status.
   */
  export type ISummary = {
    /**
     * @x-autobe-database-schema-property id
     */
    id: string & tags.Format<"uuid">;
    /**
     * @x-autobe-database-schema-property created_at
     */
    created_at: string & tags.Format<"date-time">;
    /**
     * @x-autobe-database-schema-property updated_at
     */
    updated_at: string & tags.Format<"date-time">;

    /**
     * Soft deletion timestamp, or null if not deleted.
     *
     * @x-autobe-database-schema-property deleted_at
     * @x-autobe-specification Field deleted_at uses oneOf to allow null or ISO8601 date-time string to represent soft deletion status.
     */
    deleted_at: (string & tags.Format<"date-time">) | null;

    /**
     * The associated report for this reported content, or null if not present.
     *
     * @x-autobe-database-schema-property report
     * @x-autobe-specification Belongs-to relation, nullable due to optional FK field in DB. Represented as ICommunityPlatformReport.ISummary or null.
     */
    report: ICommunityPlatformReport.ISummary | null;

    /**
     * The associated reported post content, or null if not present.
     *
     * @x-autobe-database-schema-property reportedPost
     * @x-autobe-specification Belongs-to relation, nullable due to optional FK field in DB. Represented as ICommunityPlatformPost.ISummary or null.
     */
    reportedPost: ICommunityPlatformPost.ISummary | null;

    /**
     * The associated reported comment content, or null if not present.
     *
     * @x-autobe-database-schema-property reportedComment
     * @x-autobe-specification Belongs-to relation, nullable due to optional FK field in DB. Represented as ICommunityPlatformComment.ISummary or null.
     */
    reportedComment: ICommunityPlatformComment.ISummary | null;
  };

  /**
   * Request schema for updating a reported content linking a report to a post or comment in the community platform. Allows adjustment of the linked report, reported post or comment. Used by authorized moderators and admins.
   */
  export type IUpdate = {
    /**
     * Foreign key to the user report entity. Nullable in DB, required in DTO.
     *
     * @x-autobe-database-schema-property community_platform_report_id
     * @x-autobe-specification Direct mapping to nullable community_platform_reported_contents.community_platform_report_id UUID column. The field is required but nullable to allow for data consistency.
     */
    community_platform_report_id: (string & tags.Format<"uuid">) | null;
    /**
     * @x-autobe-database-schema-property community_platform_reported_post_id
     */
    community_platform_reported_post_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;
    /**
     * @x-autobe-database-schema-property community_platform_reported_comment_id
     */
    community_platform_reported_comment_id?:
      | (string & tags.Format<"uuid">)
      | null
      | undefined;
  };
}
