import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IErpHrmActivityLog } from "../../../../../api/structures/IErpHrmActivityLog";
import { IPageIErpHrmActivityLog } from "../../../../../api/structures/IPageIErpHrmActivityLog";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { getErpHrmMemberOrganizationsOrganizationIdActivityLogsActivityLogId } from "../../../../../providers/getErpHrmMemberOrganizationsOrganizationIdActivityLogsActivityLogId";
import { patchErpHrmMemberOrganizationsOrganizationIdActivityLogs } from "../../../../../providers/patchErpHrmMemberOrganizationsOrganizationIdActivityLogs";

@Controller("/erpHrm/member/organizations/:organizationId/activity-logs")
export class ErphrmMemberOrganizationsActivity_logsController {
  /**
   * Retrieve a filtered and paginated list of activity log entries for a specific organization.
   *
   * This operation provides a comprehensive audit trail view showing all significant actions performed within the organization. Activity log entries are automatically generated by the system when events occur such as employee lifecycle changes, contract updates, project state transitions, task modifications, timesheet approvals, and role assignments.
   *
   * Entries include details about what action was performed, who performed it (member or guest), when it occurred, the IP address and user agent of the requester, and what entity was affected. The operation supports flexible filtering by action type (e.g., 'create', 'update', 'delete', 'login'), entity type (e.g., 'member', 'department', 'project', 'task'), specific entity ID, date ranges, and actor.
   *
   * This API is critical for compliance auditing, security monitoring, and operational troubleshooting. It provides organizations with verifiable history of operations for regulatory requirements and internal governance. The immutable nature of activity log records ensures integrity of the organizational history.
   *
   * Organization data isolation is strictly enforced - users can only view activity log entries belonging to the organization specified in the path parameter. Entries from other organizations are never accessible even if the user has memberships in multiple organizations.
   *
   * @param connection
   * @param organizationId The unique identifier of the organization to retrieve activity logs from
   * @param body Search criteria and pagination parameters for filtering activity log entries
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Query erp_hrm_activity_logs table filtered by organization_id from path parameter. Join with erp_hrm_activity_log_details to provide complete context for each log entry.
   *
   * Apply search filters on:
   * - action: exact match or list of actions (e.g., ['create', 'update'])
   * - entity_type: exact match or list of entity types
   * - entity_id: specific entity affected
   * - actor_member_id: filter by member who performed action
   * - actor_guest_id: filter by guest who performed action
   * - created_at: date range filtering (start/end timestamps)
   * - ip_address: partial match for IP filtering
   *
   * Support pagination with configurable page size and sorting by created_at (descending by default).
   *
   * Join with erp_hrm_members to get actor names when actor_member_id is present. Join with erp_hrm_guests for guest actor information.
   *
   * Return summary data including activity log ID, action, entity type, entity ID, actor information (name, type), timestamp, and a preview of associated details. Full details can be retrieved via a separate endpoint if needed.
   *
   * Enforce permission check: caller must have permission to view activity logs in the organization.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("organizationId")
    organizationId: string,
    @TypedBody()
    body: IErpHrmActivityLog.IRequest,
  ): Promise<IPageIErpHrmActivityLog.ISummary> {
    try {
      return await patchErpHrmMemberOrganizationsOrganizationIdActivityLogs({
        member,
        organizationId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve detailed information for a specific activity log entry.
   *
   * This operation returns a complete activity log record including all metadata details stored as key-value pairs. Activity logs serve as immutable audit trail entries that document significant events within an organization, capturing who performed an action, when it occurred, what entity was affected, and additional contextual metadata.
   *
   * The response includes the activity log's core attributes (action type, entity type, entity ID, timestamps) along with an array of detail records providing granular metadata such as before/after values for status changes, rejection reasons, or other contextual information specific to the action type.
   *
   * Access is restricted to members with appropriate permissions viewing activity logs within their currently selected organization context. Organization data isolation is enforced - users can only view activity logs belonging to the organization specified in their active session context.
   *
   * Related operations include the list/index endpoint for searching and filtering activity logs across the organization.
   *
   * @param connection
   * @param organizationId Organization ID to scope the request
   * @param activityLogId Activity log entry unique identifier
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Query erp_hrm_activity_logs table by activityLogId UUID with organization_id matching the path parameter.
   *
   * Join with erp_hrm_activity_log_details to fetch all related metadata key-value pairs for this activity log entry.
   *
   * Include related entities:
   * - organization: minimal summary (id, name)
   * - actorMember: if actor_member_id exists, include member summary (id, user profile info)
   * - actorGuest: if actor_guest_id exists, include guest summary (id)
   * - details: all key-value pairs from erp_hrm_activity_log_details
   *
   * Validate organization context matches the authenticated member's current organization selection. Return 403 if member attempts to access activity logs outside their current organization context.
   *
   * Authorization: Requires member with 'activity_log:read' permission or equivalent organization management access.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":activityLogId")
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("organizationId")
    organizationId: string,
    @TypedParam("activityLogId")
    activityLogId: string,
  ): Promise<IErpHrmActivityLog> {
    try {
      return await getErpHrmMemberOrganizationsOrganizationIdActivityLogsActivityLogId(
        {
          member,
          organizationId,
          activityLogId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
