import { tags } from "typia";

import { ICommunityPlatformUser } from "./ICommunityPlatformUser";

/**
 * Represents an audit-trail record of a user's profile image event, recording
 * every historical profile image associated with a given user. Each record logs
 * the image URI, the moment of upload, when it became the active profile image,
 * and when it was removed (or soft deleted for privacy/compliance).
 *
 * Used for audit trails, rollback and account recovery scenarios, compliance,
 * and for administrators/support to diagnose profile activity history. Enables
 * strict historical integrity without retaining binary file blobs in the DB,
 * only image URIs. Fully linked N:1 to the parent user entity via
 * community_platform_user_id.
 *
 * Designed for operation in endpoints fetching or mutating user image history.
 * Sensitive fields are guarded.
 *
 * See creation and update DTOs for mutation constraints.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ICommunityPlatformProfileImageHistory = {
  /** Primary Key. Unique identifier for this profile image history record. */
  id: string & tags.Format<"uuid">;

  /**
   * Reference to the owning user (community_platform_users.id). Defines a N:1
   * relationship with users and tracks image history for a single user.
   */
  community_platform_user_id: string & tags.Format<"uuid">;

  /**
   * URI or path to the profile image (relative or absolute). No image blobs
   * are stored in the database. Only references to uploaded location are
   * kept.
   */
  image_uri: string & tags.Format<"uri">;

  /**
   * Timestamp (ISO 8601) when this profile image was uploaded for audit
   * trails and compliance checks. Set on creation.
   */
  uploaded_at: string & tags.Format<"date-time">;

  /** Timestamp (ISO 8601) when this image became active as the profile image. */
  effective_from: string & tags.Format<"date-time">;

  /**
   * Timestamp (ISO 8601) when this profile image was replaced or removed.
   * Null if still active.
   */
  removed_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Soft deletion timestamp (ISO 8601). Null unless record has been privacy
   * deleted.
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
};
export namespace ICommunityPlatformProfileImageHistory {
  /**
   * Request DTO for searching, paginating, and filtering a user's profile
   * image change history records in
   * community_platform_profile_image_history.
   *
   * Supports filtering by user, pagination, sorting, and optional inclusion
   * of soft-deleted images for audit review scenarios. Used by endpoints that
   * retrieve the full profile image audit trail for a single user.
   *
   * Page and limit control result slicing; sort_by and sort_direction dictate
   * ordering.
   */
  export type IRequest = {
    /**
     * Unique identifier of the user whose profile image history is to be
     * queried.
     *
     * Indicates the owner of image records to be retrieved. Must match a
     * valid community_platform_users.id in the DB.
     */
    user_id: string & tags.Format<"uuid">;

    /**
     * Page number for paginated results.
     *
     * Determines the offset into the result set. Must be 1 or higher.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Maximum number of results to return per page.
     *
     * Used for pagination control and workload management. Maximum allowed
     * value is 100.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;

    /**
     * Sort field for ordering image history results.
     *
     * Specifies which timestamp to use when ordering the returned profile
     * image history list. Allowed values: 'uploaded_at', 'effective_from',
     * 'removed_at'. Defaults to 'uploaded_at' if not specified.
     */
    sort_by?: "uploaded_at" | "effective_from" | "removed_at" | undefined;

    /**
     * Sort direction for the results.
     *
     * Determines sort order (ascending/descending) on the selected field.
     * Allowed values: 'asc' or 'desc'. Defaults to 'desc'.
     */
    sort_direction?: "asc" | "desc" | undefined;

    /**
     * If true, include profile image history entries that have been
     * soft-deleted in the results.
     *
     * Used for audit and compliance views. If false, only non-deleted
     * images are returned.
     */
    include_soft_deleted?: boolean | undefined;
  };

  /**
   * DTO for appending a new entry to the user's profile image history
   * (community_platform_profile_image_history). Used when a user
   * uploads/assigns a new profile image, which must be tracked for audit,
   * compliance, and recovery. Only includes business-editable fields;
   * timestamps require correct upload/activation time. All identity and
   * foreign/reference fields are controlled by the backend based on the
   * path/authorization context.
   *
   * No direct user ID should be supplied in this DTO by the client; user
   * context is extracted from the session/path. URI must be pre-uploaded and
   * validated, and timestamps must be accurate to system audit standards.
   */
  export type ICreate = {
    /**
     * URI or path to the pre-uploaded profile image that will be set as the
     * new profile image. Must be a valid image URI or storage path. Only
     * image reference, not the binary.
     */
    image_uri: string & tags.Format<"uri">;

    /**
     * Timestamp (ISO 8601) when this image was uploaded. Should reflect the
     * actual upload moment. Required for strict audit compliance.
     */
    uploaded_at: string & tags.Format<"date-time">;

    /**
     * Timestamp (ISO 8601) when this image becomes the user's active
     * profile image. Usually equal to upload time but may differ if delayed
     * activation.
     */
    effective_from: string & tags.Format<"date-time">;
  };

  /**
   * Data Transfer Object for updating a specific entry in the
   * community_platform_profile_image_history audit log. Intended for updates
   * to metadata such as effective or removal timestamps, controlled by strict
   * security rules and business logic.
   *
   * Fields here are typically mutable for marking image end-of-life,
   * reflecting removal time, or adjusting audit periods for regulatory
   * compliance. Does not permit setting of userId or image URI, which are
   * immutable for audit integrity.
   *
   * All updates are subject to strong authorization requirements (user or
   * admin) and audited for future trail/recovery.
   */
  export type IUpdate = {
    /**
     * The new or corrected timestamp marking when this profile image
     * started being displayed as the active image for the user. This can be
     * updated to correct audit records or to re-align historical records
     * during an administrative review. Must be an ISO 8601 datetime;
     * nulling usually not permitted for audit integrity.
     */
    effective_from: string & tags.Format<"date-time">;

    /**
     * When this history record ceased to apply (image removed, replaced, or
     * reverted to active). Setting to null may be allowed by admins for
     * system corrections or compliance workflows.
     */
    removed_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Logical deletion date/time for data retention and compliance. Admin
     * or backend-only; user cannot set directly except via formal account
     * deletion/workflow.
     */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };

  /**
   * Summary DTO for user profile image history audit entries.
   *
   * Each entry embeds context about the user as a BELONGS-TO reference object
   * for atomicity and API consistency. Represents an immutable record for
   * every profile image a user has ever uploaded, supporting audit, rollback,
   * and compliance for profile visuals. Links back to the owning user,
   * provides change history, and enables recovery in regulatory or
   * user-driven workflows.
   *
   * Does not include the raw image blob, only the reference URI (either
   * absolute or relative). Used when displaying historical profile images or
   * processing user audits.
   */
  export type ISummary = {
    /**
     * Unique identifier for the profile image history record.
     *
     * This value is a universally unique identifier (UUID) and serves as
     * the primary key for the table. Used for audit resolution,
     * traceability, and referencing image history in other operations.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Reference to the owning user of this profile image history entry
     * (BELONGS-TO). Transformed from FK to summary object association. The
     * user may have multiple entries in this table.
     */
    user: ICommunityPlatformUser.ISummary;

    /**
     * URI or path of the profile image. Not a raw blob, but a reference
     * (relative or absolute) to the uploaded profile image.
     */
    image_uri: string & tags.Format<"uri">;

    /**
     * Timestamp of the image upload event (ISO 8601). Specifies when this
     * image was uploaded to the platform.
     */
    uploaded_at: string & tags.Format<"date-time">;

    /**
     * Timestamp (ISO 8601) when this image started being used as the active
     * profile picture.
     */
    effective_from: string & tags.Format<"date-time">;

    /**
     * Timestamp when this image was replaced or removed. Null means this
     * image is currently in use.
     */
    removed_at?: (string & tags.Format<"date-time">) | null | undefined;

    /** Soft delete marker. Used only for audit/compliance. */
    deleted_at?: (string & tags.Format<"date-time">) | null | undefined;
  };
}
