import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IRedditPlatformKarmaThreshold } from "../../../../structures/IRedditPlatformKarmaThreshold";

/**
 * Retrieve a specific karma threshold configuration object from the system's
 * database. This operation identifies and returns the complete details of an
 * individual karma threshold entity using its unique identifier.
 *
 * The operation directly maps to the karma_thresholds database table which
 * contains all threshold definitions for user rank promotions and feature
 * access restrictions. Each threshold configuration includes the minimum karma
 * required for various status levels and privileges.
 *
 * Security considerations include strict access control to ensure only
 * authorized site administrators and community administrators can view
 * threshold configurations. Unauthorized access attempts will be blocked at the
 * authorization layer without any response data.
 *
 * This endpoint is specifically designed to fetch single karma threshold data
 * rather than performing complex searches or queries. The path parameter uses a
 * UUID identifier to ensure safe and unambiguous resource retrieval across the
 * platform.
 *
 * @param props.connection
 * @param props.thresholdId Unique identifier of the threshold to retrieve
 * @path /redditPlatform/communityAdmin/thresholds/:thresholdId
 * @accessor api.functional.redditPlatform.communityAdmin.thresholds.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the threshold to retrieve */
    thresholdId: string & tags.Format<"uuid">;
  };
  export type Response = IRedditPlatformKarmaThreshold;

  export const METADATA = {
    method: "GET",
    path: "/redditPlatform/communityAdmin/thresholds/:thresholdId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditPlatform/communityAdmin/thresholds/${encodeURIComponent(props.thresholdId ?? "null")}`;
  export const random = (): IRedditPlatformKarmaThreshold =>
    typia.random<IRedditPlatformKarmaThreshold>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("thresholdId")(() => typia.assert(props.thresholdId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete a specific karma threshold configuration from the system. This
 * operation permanently removes the threshold from the database and is designed
 * for system or community administrators who need to remove outdated or
 * incorrect threshold definitions. The operation targets the 'karma_thresholds'
 * table in the database, with the threshold identified by its unique ID (not a
 * code field).
 *
 * The system automatically handles related karma calculations and rule
 * applications during deletion, but administrators should ensure that no active
 * user behaviors are tied to the threshold being removed. Deletion is immediate
 * and irreversible, with no soft-delete option.
 *
 * Authorization requires administrative privileges (either site admin or
 * community admin) to prevent accidental or unauthorized threshold deletions.
 * The operation is read-only in its access control, meaning deletion operations
 * don't require any additional data in the request beyond the threshold ID.
 *
 * @param props.connection
 * @param props.thresholdId Unique identifier of the target karma threshold
 *   (UUID in database)
 * @path /redditPlatform/communityAdmin/thresholds/:thresholdId
 * @accessor api.functional.redditPlatform.communityAdmin.thresholds.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the target karma threshold (UUID in database) */
    thresholdId: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/redditPlatform/communityAdmin/thresholds/:thresholdId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/redditPlatform/communityAdmin/thresholds/${encodeURIComponent(props.thresholdId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("thresholdId")(() => typia.assert(props.thresholdId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
