import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody } from "@nestia/core";
import typia from "typia";
import { postTodoAppAuthRegister } from "../../../../providers/postTodoAppAuthRegister";

import { ITodoAppUser } from "../../../../api/structures/ITodoAppUser";

@Controller("/todoApp/auth/register")
export class TodoappAuthRegisterController {
  /**
   * Register a new user account for the Todo application.
   *
   * This endpoint allows new users to create an account for accessing the Todo
   * application. The registration process validates the email format, ensures
   * email uniqueness across all users, and enforces password complexity
   * requirements.
   *
   * Upon successful registration, the system creates a user account record in
   * the todo_app_users table with the provided email and securely hashed
   * password. The user account is initially set to 'active' status, and the
   * creation timestamp is recorded for audit purposes.
   *
   * Security considerations include password hashing using industry-standard
   * algorithms, email verification before full account activation, and
   * protection against duplicate account creation. The system validates that
   * the email follows proper format requirements and that the password meets
   * minimum security standards.
   *
   * @param connection
   * @param body User registration information including email and password
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @TypedBody()
    body: ITodoAppUser.ICreate,
  ): Promise<ITodoAppUser> {
    try {
      return await postTodoAppAuthRegister({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
