import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam } from "@nestia/core";
import typia from "typia";
import { getRedditCommunityModeratorCommunitiesCommunityNameReportsStatistics } from "../../../../../../providers/getRedditCommunityModeratorCommunitiesCommunityNameReportsStatistics";
import { ModeratorAuth } from "../../../../../../decorators/ModeratorAuth";
import { ModeratorPayload } from "../../../../../../decorators/payload/ModeratorPayload";

import { IRedditCommunityReportStatistics } from "../../../../../../api/structures/IRedditCommunityReportStatistics";

@Controller(
  "/redditCommunity/moderator/communities/:communityName/reports/statistics",
)
export class RedditcommunityModeratorCommunitiesReportsStatisticsController {
  /**
   * Retrieve comprehensive statistical data about content reports within a
   * specific community. This operation provides moderators with analytical
   * insights into reporting patterns, violation categories, resolution rates,
   * and temporal trends for their community.
   *
   * The statistics include aggregated data such as total report counts by
   * category, average resolution times, pending vs resolved report ratios, and
   * trending violation types. This information helps moderators understand
   * community health, identify problematic content patterns, and allocate
   * moderation resources effectively.
   *
   * Security: Only authenticated moderators with authority in the specified
   * community can access these statistics. The community is identified by its
   * unique name field for better URL readability. The operation validates that
   * the requesting moderator has active moderation privileges for the community
   * before returning sensitive moderation data.
   *
   * This operation aggregates data from the reddit_community_reports table and
   * related moderation entities from the Prisma schema, computing statistics
   * across multiple report types (posts and comments) to provide a unified view
   * of community moderation metrics.
   *
   * @param connection
   * @param communityName Unique business identifier code of the target
   *   community (global scope)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @ModeratorAuth()
    moderator: ModeratorPayload,
    @TypedParam("communityName")
    communityName: string,
  ): Promise<IRedditCommunityReportStatistics> {
    try {
      return await getRedditCommunityModeratorCommunitiesCommunityNameReportsStatistics(
        {
          moderator,
          communityName,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
