import { tags } from "typia";

import { IShoppingMallCustomer } from "./IShoppingMallCustomer";
import { IShoppingMallWishlistItem } from "./IShoppingMallWishlistItem";

/**
 * User-created wishlists for organizing desired products in the shopping mall
 * platform.
 *
 * Stores collections of products that customers want to save for future
 * purchase consideration. Each wishlist represents a curated selection that
 * supports personal shopping experiences, gift planning, and collaborative
 * shopping with friends and family.
 *
 * Wishlists support advanced features including priority ranking for
 * organization, public/private visibility settings for sharing control, and
 * status management for wishlist lifecycle tracking. The system maintains
 * comprehensive timestamps for creation, modification, and soft deletion to
 * support data retention policies.
 *
 * Security considerations ensure that system-managed fields like timestamps and
 * soft-delete flags are protected from client manipulation. The wishlist entity
 * integrates with the shopping_mall_wishlists Prisma schema, maintaining full
 * compatibility with the underlying database structure while providing rich API
 * functionality for customer wishlist management.
 *
 * Used across multiple API operations including wishlist creation, retrieval,
 * updating, and search functionality. The comprehensive field set supports both
 * detailed wishlist views and summary displays for efficient customer
 * experience across the shopping mall platform.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallWishlist = {
  /**
   * Primary Key. Unique identifier for the wishlist record generated
   * automatically using UUID v4 format.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Wishlist name for identification and organization. Displayed to users for
   * quick recognition and management of multiple wishlists.
   */
  name: string;

  /**
   * Optional description explaining the wishlist's purpose or theme. Provides
   * additional context for wishlist organization and collaborative sharing.
   */
  description?: string | undefined;

  /**
   * Whether the wishlist is publicly visible or private. Public wishlists can
   * be discovered by other users, while private wishlists are accessible only
   * to the owner.
   */
  is_public: boolean;

  /**
   * Priority level for sorting and organization. Higher numbers indicate
   * higher priority for wishlist display and management. Used for personal
   * organization and quick access to important wishlists.
   */
  priority: number & tags.Type<"int32">;

  /**
   * Current status of the wishlist as defined in the Prisma schema. Controls
   * wishlist visibility and functionality within the shopping platform.
   */
  status: "active" | "archived" | "shared";

  /**
   * Customer who owns this wishlist. Provides ownership context and access
   * control validation for wishlist operations.
   */
  customer: IShoppingMallCustomer.ISummary;

  /**
   * Individual products added to customer wishlists. Contains product
   * references, quantities, and customer notes for comprehensive wishlist
   * management.
   */
  items?: IShoppingMallWishlistItem.ISummary[] | undefined;

  /**
   * Timestamp when the wishlist was created. System-generated field for
   * tracking wishlist lifecycle and organization.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the wishlist was last modified. Automatically updated on
   * any changes to wishlist properties or items.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the wishlist was soft deleted. Used for data retention and
   * recovery purposes while maintaining referential integrity.
   */
  deleted_at?: (string & tags.Format<"date-time">) | undefined;
};
export namespace IShoppingMallWishlist {
  /**
   * Search and filtering parameters for wishlist queries with comprehensive
   * security context enforcement.
   *
   * This request type provides advanced search capabilities for wishlist
   * operations while maintaining strict authentication boundaries. Customers
   * can search their own wishlists or discover public wishlists from other
   * users, with automatic filtering based on the authenticated customer's
   * identity.
   *
   * The search functionality leverages database indexes on wishlist name,
   * description, customer relationships, and status fields for optimal
   * performance. Security considerations ensure customers cannot access
   * private wishlists belonging to other users, maintaining privacy while
   * enabling collaborative shopping experiences.
   *
   * This component supports both simple keyword searches and advanced
   * filtering combinations, including priority ranges, status filters, and
   * customer-specific queries. The system validates all search parameters
   * against business rules and security policies before executing database
   * queries.
   *
   * Integration with the shopping_mall_wishlists Prisma schema ensures type
   * safety and consistency with the underlying data model. Pagination and
   * sorting options provide efficient data retrieval for large wishlist
   * collections across the shopping mall platform.
   */
  export type IRequest = {
    /**
     * Search query for filtering wishlists by name or description content
     * using partial text matching. Supports fuzzy matching and
     * case-insensitive searches for improved discovery. Minimum length of 1
     * character ensures meaningful search terms.
     */
    search?: (string & tags.MinLength<1> & tags.MaxLength<255>) | undefined;

    /**
     * Filter wishlists by specific status values as defined in the Prisma
     * schema. Valid values include active, archived, and shared statuses
     * for comprehensive wishlist lifecycle management.
     */
    status?: "active" | "archived" | "shared" | undefined;

    /**
     * Filter wishlists by public/private visibility setting. When true,
     * returns only public wishlists available for discovery. When false,
     * returns private wishlists accessible only to the owner.
     */
    is_public?: boolean | undefined;

    /**
     * Minimum priority level for filtering wishlists. Used in combination
     * with priority_max to create priority range filters for wishlist
     * organization and sorting.
     */
    priority_min?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Maximum priority level for filtering wishlists. Defines the upper
     * bound of priority ranges for precise wishlist filtering and
     * organization.
     */
    priority_max?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Filter wishlists by specific customer identifier. When provided,
     * returns wishlists belonging to the specified customer. Requires
     * appropriate permissions for cross-customer access.
     */
    customer_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Page number for paginated results. Starts from 1 for the first page.
     * Combined with limit parameter for efficient large dataset
     * navigation.
     */
    page: number & tags.Type<"int32"> & tags.Minimum<1>;

    /**
     * Number of items per page for paginated results. Maximum value of 50
     * prevents excessive data retrieval and maintains API performance
     * standards.
     */
    limit: number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<50>;

    /**
     * Field to sort results by. Determines the primary sorting criteria for
     * wishlist organization and display.
     */
    order_by?: "name" | "priority" | "created_at" | "updated_at" | undefined;

    /**
     * Sort direction for organizing search results. Affects how wishlists
     * are ordered based on the selected order_by field.
     */
    order?: "asc" | "desc" | undefined;
  };

  /**
   * Data transfer object for creating new customer wishlists in the shopping
   * mall platform.
   *
   * This schema defines the complete input structure required to create
   * personalized wishlists that help customers organize products they want to
   * save for future purchase consideration. The operation validates all input
   * data against business rules and ensures wishlist names are unique within
   * each customer's account.
   *
   * Security considerations include automatic population of customer_id from
   * JWT authentication tokens to prevent unauthorized wishlist creation. The
   * system validates that wishlist names are not already used by the customer
   * for other active wishlists, maintaining organizational integrity.
   *
   * Integration with the shopping_mall_wishlists Prisma schema ensures all
   * database fields are properly mapped with appropriate validation rules and
   * default values applied when optional fields are not provided in the
   * request.
   */
  export type ICreate = {
    /**
     * Wishlist name for identification and organization within the
     * customer's account.
     *
     * Must be unique within the customer's wishlist collection to prevent
     * naming conflicts. Supports up to 255 characters for descriptive
     * naming that helps customers identify their wishlist purposes. The
     * name is validated against duplicate names within the same customer
     * account to ensure uniqueness.
     */
    name: string;

    /**
     * Optional description explaining the wishlist's purpose, theme, or
     * intended use.
     *
     * Provides additional context for customers to remember why they
     * created specific wishlists. Can include details about occasions,
     * recipients, or specific product categories the wishlist targets.
     * Maximum length of 1000 characters allows for comprehensive wishlist
     * descriptions.
     */
    description?: string | undefined;

    /**
     * Whether the wishlist is publicly visible or kept private for personal
     * use.
     *
     * Public wishlists can be shared with others for collaborative shopping
     * or gift planning. Private wishlists remain visible only to the
     * customer who created them. Default value is false (private) to
     * prioritize customer privacy by default.
     */
    is_public: boolean;

    /**
     * Priority level for sorting and organization within the customer's
     * wishlist collection.
     *
     * Higher numbers indicate higher priority for display and
     * organizational purposes. Used for sorting wishlists in customer
     * interfaces to highlight important collections. Supports values from 1
     * to 10, with 1 being lowest priority and 10 being highest priority.
     */
    priority: number & tags.Type<"int32">;

    /**
     * Current status of the wishlist indicating its lifecycle state and
     * availability.
     *
     * Valid values include: 'active' (currently in use), 'archived'
     * (preserved but inactive), 'shared' (collaborative mode). Default
     * status is 'active' for newly created wishlists. Status changes are
     * tracked for audit purposes and customer preference management.
     */
    status: string;
  };

  /**
   * Data transfer object for updating existing customer wishlists with
   * modified properties.
   *
   * This schema supports partial updates to wishlist attributes, allowing
   * customers to modify specific properties without requiring complete
   * wishlist redefinition. All fields are optional to enable flexible
   * wishlist management and gradual property updates.
   *
   * Security validations ensure that customers can only update wishlists they
   * own, with customer_id automatically validated from authentication
   * context. The system prevents modification of immutable fields like
   * creation timestamps and maintains referential integrity throughout update
   * operations.
   *
   * Integration with the shopping_mall_wishlists Prisma schema ensures
   * database consistency while applying appropriate business rules for each
   * updatable field. The updated_at timestamp is automatically refreshed to
   * track modification history for audit purposes.
   */
  export type IUpdate = {
    /**
     * Updated wishlist name for identification and organization.
     *
     * Must remain unique within the customer's wishlist collection after
     * modification. Validated against existing wishlist names to prevent
     * naming conflicts. Maximum length of 255 characters maintained for
     * consistency with creation constraints.
     */
    name?: string | undefined;

    /**
     * Updated description explaining the wishlist's purpose, theme, or
     * intended use.
     *
     * Allows customers to modify wishlist context and documentation as
     * their needs evolve. Supports up to 1000 characters for comprehensive
     * wishlist descriptions. Optional field that can be cleared by setting
     * to null if description is no longer needed.
     */
    description?: string | undefined;

    /**
     * Updated visibility setting determining whether the wishlist is
     * publicly visible or private.
     *
     * Customers can change wishlist privacy settings based on sharing
     * preferences. Public wishlists become shareable with others for
     * collaborative shopping experiences. Private wishlists remain
     * restricted to the customer's personal viewing only.
     */
    is_public?: boolean | undefined;

    /**
     * Updated priority level for organizational sorting within the
     * customer's wishlist collection.
     *
     * Higher numbers continue to indicate higher priority for display
     * purposes. Supports values from 1 to 10 for consistent priority
     * management. Allows customers to reorganize wishlist importance as
     * their needs change.
     */
    priority?: (number & tags.Type<"int32">) | undefined;

    /**
     * Updated status of the wishlist reflecting its current lifecycle state
     * and availability.
     *
     * Valid values include: 'active' (currently in use), 'archived'
     * (preserved but inactive), 'shared' (collaborative mode). Status
     * changes are tracked for audit purposes and customer preference
     * management. Archived wishlists preserve content while removing them
     * from active shopping workflows.
     */
    status?: string | undefined;
  };

  /**
   * Compact wishlist representation optimized for list displays and quick
   * overviews in the shopping mall platform.
   *
   * Provides essential wishlist information while excluding detailed
   * description fields and comprehensive item details to optimize performance
   * in list views and dashboard displays. Includes key metrics like priority
   * level for quick wishlist assessment and management.
   *
   * This summary format is ideal for customer dashboard interfaces, wishlist
   * management pages, shared wishlist previews, and administrative overviews
   * where full wishlist details are not immediately required. The inclusion
   * of customer context ensures proper ownership identification and access
   * control validation.
   *
   * Maintains referential integrity with the shopping_mall_wishlists Prisma
   * schema while providing essential fields for enhanced user experience
   * without requiring additional database queries.
   */
  export type ISummary = {
    /**
     * Primary unique identifier for the wishlist record. Generated
     * automatically using UUID v4 format upon wishlist creation. Used for
     * database operations and API endpoint references.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Wishlist name displayed to customers for identification and
     * organization purposes. Supports custom naming for personalized
     * wishlist management and categorization.
     */
    name: string;

    /**
     * Optional description explaining the wishlist's purpose, theme, or
     * intended use case. Provides additional context for customers
     * organizing multiple wishlists with different purposes.
     */
    description?: string | undefined;

    /**
     * Visibility setting determining whether the wishlist is publicly
     * accessible or kept private. Public wishlists can be shared via unique
     * URLs while private wishlists remain accessible only to the owner.
     */
    is_public: boolean;

    /**
     * Priority level for sorting and organizational purposes within the
     * customer's wishlist collection. Higher numerical values indicate
     * higher priority for display and access.
     */
    priority: number & tags.Type<"int32">;

    /**
     * Current operational status of the wishlist indicating its
     * availability and usage state. Valid values include: active (currently
     * in use), archived (retained but inactive), and shared (actively
     * shared with others).
     */
    status: string;

    /**
     * Timestamp recording when the wishlist was initially created by the
     * customer. Used for chronological sorting and wishlist lifecycle
     * tracking.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Timestamp indicating the last modification made to the wishlist,
     * including item additions/removals or metadata changes. Helps track
     * recent activity.
     */
    updated_at: string & tags.Format<"date-time">;

    /**
     * Customer who owns this wishlist. References
     * shopping_mall_customers.id for establishing the customer
     * relationship.
     */
    shopping_mall_customer_id: string & tags.Format<"uuid">;
  };
}
