/**
 * Type of analytics metric to include in customer behavior analysis reports.
 *
 * This enum defines the specific types of analytics metrics that can be
 * requested for inclusion in customer behavior analysis. Each metric type
 * corresponds to a different aspect of customer behavior analysis, allowing
 * administrators to selectively include the metrics most relevant to their
 * current business intelligence needs.
 *
 * The metric types cover purchase patterns, engagement metrics, retention
 * analysis, product affinity analysis, and customer segmentation insights,
 * providing comprehensive coverage of different behavioral analysis
 * dimensions.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallAnalyticsMetricType =
  | "purchase_patterns"
  | "engagement_metrics"
  | "retention_analysis"
  | "product_affinity"
  | "customer_segments";
