import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { getShoppingPlatformAnnouncementsPlatformAnnouncementId } from "../../../providers/getShoppingPlatformAnnouncementsPlatformAnnouncementId";

import { IShoppingPlatformAnnouncement } from "../../../api/structures/IShoppingPlatformAnnouncement";

@Controller("/shopping/platformAnnouncements/:platformAnnouncementId")
export class ShoppingPlatformannouncementsController {
  /**
   * Retrieve detailed information for a specific platform announcement
   * (shopping_platform_announcements).
   *
   * This endpoint provides the complete details for a single platform
   * announcement specified by the unique 'platformAnnouncementId'. It is
   * designed to support admin and user views that display scheduled, active, or
   * historical announcements published by administrators. The response includes
   * all announcement metadata, such as title, body content, audience targeting,
   * publication status, scheduling windows, and the authoring admin's
   * reference.
   *
   * Security is enforced so that only authenticated actors with viewing
   * permissions (such as admins or general platform users) may access the
   * announcement details. This operation reads from the
   * 'shopping_platform_announcements' Prisma table and reflects any changes to
   * announcement content or status in real time, ensuring up-to-date
   * information is always served.
   *
   * Error handling covers scenarios where the specified announcement does not
   * exist, is deleted, or the caller lacks permission to view the content. This
   * endpoint is typically used in any context requiring display or audit of
   * admin-issued platform announcements.
   *
   * @param connection
   * @param platformAnnouncementId Unique identifier (UUID) of the target
   *   platform announcement to retrieve (global scope)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @TypedParam("platformAnnouncementId")
    platformAnnouncementId: string & tags.Format<"uuid">,
  ): Promise<IShoppingPlatformAnnouncement> {
    try {
      return await getShoppingPlatformAnnouncementsPlatformAnnouncementId({
        platformAnnouncementId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
