import { TypedBody, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IPageIRedditCommunitySubscription } from "../../../../../api/structures/IPageIRedditCommunitySubscription";
import { IRedditCommunitySubscription } from "../../../../../api/structures/IRedditCommunitySubscription";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { patchRedditCommunityMemberCommunitySubscribed } from "../../../../../providers/patchRedditCommunityMemberCommunitySubscribed";

@Controller("/redditCommunity/member/community/subscribed")
export class RedditcommunityMemberCommunitySubscribedController {
  /**
   * Retrieve a paginated list of communities that the authenticated user is currently subscribed to.
   *
   * This endpoint returns metadata for all communities the user has subscribed to, including the community name, description preview, subscriber count, and subscription status. Each entry represents a community the user follows, allowing them to manage their subscriptions and access content.
   *
   * This operation does not return posts, comments, or moderator information—only core community metadata. Clients should use /communities/{communityId} to retrieve detailed information about a specific subscribed community.
   *
   * Authentication is required, and results are scoped to the authenticated user’s subscription list. The response supports pagination for performance when users follow many communities.
   *
   * @param connection
   * @param body Pagination and filtering parameters for subscribed communities list
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Query the reddit_community_subscriptions table filtered by the authenticated user's ID. Join with reddit_community_communities to retrieve community name, description, iconUrl, and subscriberCount. Apply pagination with limit and offset based on request body parameters. Return only the fields necessary for summary display: id, name, description, iconUrl, subscriberCount, and isSubscribed (always true for results).
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedBody()
    body: IRedditCommunitySubscription.IRequest,
  ): Promise<IPageIRedditCommunitySubscription.ISummary> {
    try {
      return await patchRedditCommunityMemberCommunitySubscribed({
        member,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
