import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { ICommunityPlatformVoteSummary } from "../../../../api/structures/ICommunityPlatformVoteSummary";
import { IPageICommunityPlatformVoteSummary } from "../../../../api/structures/IPageICommunityPlatformVoteSummary";
import { MemberAuth } from "../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../decorators/payload/MemberPayload";
import { getCommunityPlatformMemberVoteSummariesSummaryId } from "../../../../providers/getCommunityPlatformMemberVoteSummariesSummaryId";
import { patchCommunityPlatformMemberVoteSummaries } from "../../../../providers/patchCommunityPlatformMemberVoteSummaries";

@Controller("/communityPlatform/member/vote-summaries")
export class CommunityplatformMemberVote_summariesController {
  /**
   * Search and list vote summary records across all content on the platform.
   *
   * Vote summaries are precomputed aggregate statistics that track the net vote score, total upvotes, and total downvotes for each post and comment on the platform. Each summary record represents the current aggregated vote state of one target entity, updated automatically whenever a vote is cast, changed, or removed by any user.
   *
   * This endpoint allows filtering vote summaries by target type (posts or comments), vote score ranges, vote count thresholds (minimum upvotes, minimum downvotes), and time ranges based on when the summary was created or last updated. Results are returned as a paginated list sorted by net score, vote counts, or recency according to the requested sort criteria.
   *
   * Vote summaries are system-managed and read-only. To cast or modify votes on individual posts or comments, use the dedicated vote endpoints.
   *
   * @param connection
   * @param body Search criteria for filtering vote summary records. Supports optional filtering by target type (post or comment), net score range, upvote count range, downvote count range, creation date range, and last-updated date range. Includes sort preference and cursor-based pagination parameters.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query community_platform_vote_summaries table
     *   with dynamic filtering and pagination.
   *
   * Filters to support in ICommunityPlatformVoteSummary.IRequest:
   * - target_type: optional filter by 'post' or 'comment' (null/omitted returns both types)
   * - net_score range: min_net_score and max_net_score to filter by net vote score boundaries
   * - upvote_count range: min_upvote_count and max_upvote_count
   * - downvote_count range: min_downvote_count and max_downvote_count
   * - created_at range: filter summaries created within a date/time range
   * - updated_at range: filter summaries last updated within a date/time range
   * - sort: sort by net_score (asc/desc), upvote_count, downvote_count, created_at, or updated_at
   * - Pagination: cursor-based pagination with page size limit
   *
   * No joins required — all query fields exist directly on the community_platform_vote_summaries table. Use the existing indexes:
   * - @@unique([target_type, target_id]) for single-target lookups
   * - @@index([target_type, net_score]) for filtered/sorted queries
   *
   * Edge cases:
   * - If no vote summaries match the filter, return an empty page (HTTP 200 with empty items array, not an error)
   * - target_type filter must reject values other than 'post' or 'comment' via validation
   * - Negative net_score values are valid — ensure range filtering handles negative boundaries correctly
   * - When target_type is null/omitted, scan across both target types
   * - The summary may not exist for targets with zero votes — this is expected, no error
   * - updated_at can be equal to created_at if the target has only ever had one vote state
   *
   * Authorization: Requires member authentication. Vote summary data reveals voting patterns and should not be publicly queryable.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @MemberAuth()
    member: MemberPayload,
    @TypedBody()
    body: ICommunityPlatformVoteSummary.IRequest,
  ): Promise<IPageICommunityPlatformVoteSummary.ISummary> {
    try {
      return await patchCommunityPlatformMemberVoteSummaries({
        member,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve a single vote summary record by its unique identifier.
   *
   * Vote summaries store precomputed, denormalized vote statistics for posts and comments across the platform. Each summary contains the aggregated upvote count, downvote count, and net vote score for a single target entity (post or comment), updated reactively whenever a vote is cast, changed, or removed.
   *
   * Returns the full vote summary record including target type and target ID for identifying which content the summary belongs to. The `target_type` field discriminates between 'post' and 'comment' targets.
   *
   * @param connection
   * @param summaryId The unique identifier (UUID) of the target vote summary record to retrieve.
     * @x-autobe-authorization-type null
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Query community_platform_vote_summaries table by
     *   primary key (id) where id equals the provided {summaryId} UUID
     *   parameter.
   *
   * Return the complete vote summary record including: id, target_type, target_id, upvote_count, downvote_count, net_score, created_at, updated_at.
   *
   * If no record matches the provided {summaryId}, return a 404 Not Found error with an appropriate message indicating the vote summary was not found.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":summaryId")
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("summaryId")
    summaryId: string & tags.Format<"uuid">,
  ): Promise<ICommunityPlatformVoteSummary> {
    try {
      return await getCommunityPlatformMemberVoteSummariesSummaryId({
        member,
        summaryId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
