import { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import { IShoppingMallSaleViewStat } from "../../../../../structures/IShoppingMallSaleViewStat";

/**
 * Compute comprehensive sales performance metrics by aggregating data from the shopping_mall_sales table. This operation provides statistical insights into sales trends and performance without requiring direct access to individual sales records. The metrics include total sales revenue, number of transactions, average transaction value, and sales volume over time.
 *
 * The operation performs a complex aggregation computation using SQL equivalent to: SELECT SUM(total_amount) as total_revenue, COUNT(*) as transaction_count, AVG(total_amount) as average_transaction_value, SUM(quantity_sold) as total_units_sold FROM shopping_mall_sales WHERE status = 'completed'. This statistical aggregation serves the business need for sales trend analysis without exposing raw sales data.
 *
 * This operation is designed to meet the requirements for business intelligence reporting specified in the inventory management documentation, allowing management to monitor sales performance, identify trends, and make data-driven decisions about inventory and pricing strategies. It provides a high-level overview of sales metrics that can be used for dashboards and reports.
 *
 * Important note: This operation does not map directly to any single table in the database as it represents calculated business intelligence data rather than stored entity data. It complements the transactional sales operations by providing analytical insights derived from the same data source.
 *
 * @param props.connection
 * @x-autobe-specification Perform SQL aggregation on shopping_mall_sales table to compute total revenue, number of transactions, average transaction value, and total units sold. Filter for completed sales only. Use date range parameters if specified in request. Return structured metrics object with computed values. Cache results for 5 minutes to optimize repeated dashboard queries.
 * @path /shoppingMall/customer/sales/metrics
 * @accessor api.functional.shoppingMall.customer.sales.metrics.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(connection: IConnection): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
      );
}
export namespace index {
  export type Response = IShoppingMallSaleViewStat;

  export const METADATA = {
    method: "GET",
    path: "/shoppingMall/customer/sales/metrics",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/customer/sales/metrics";
  export const random = (): IShoppingMallSaleViewStat =>
    typia.random<IShoppingMallSaleViewStat>();
  export const simulate = (_connection: IConnection): Response => {
    return random();
  };
}
