import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia from "typia";

import { IShoppingMallAdmin } from "../../../../structures/IShoppingMallAdmin";

/**
 * Register a new administrator account.
 *
 * This endpoint is the admin actor’s public registration entry point and corresponds to creating an Admin record in the database-backed actor model (admin identity). The request payload must match the DTO contract `IShoppingMallAdmin.IJoin`, and the server returns `IShoppingMallAdmin.IAuthorized`, which contains the authenticated authorization result (e.g., JWT tokens and the authorized admin identity).
 *
 * Security considerations: credential material validation (if included in the join DTO) must be performed server-side using the project’s password hashing and verification approach. Any uniqueness constraints for the admin login identifiers must be enforced at the persistence layer to prevent duplicate accounts.
 *
 * Integration: after successful join, clients should use the returned authorization payload for subsequent authenticated requests to admin-only endpoints. This endpoint is intentionally not tied to other business operations via prerequisites because it is part of the authentication workflow.
 *
 * Error behavior: if validation fails or the account identifiers already exist, the API should respond with a suitable 4xx error and never return authorization tokens.
 *
 * @setHeader token.access Authorization
 *
 * @param props.connection
 * @param props.body Admin registration payload for creating a new admin account and initiating authorization.
 * @x-autobe-authorization-type join
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Implement POST /auth/admin/join as admin
 *   registration: validate input per IShoppingMallAdmin.IJoin, create or update
 *   admin account record, enforce any uniqueness/format constraints at the
 *   service layer, create initial admin session context as needed, and return
 *   tokens within IShoppingMallAdmin.IAuthorized. Use a transaction to persist
 *   the admin and any related session/session-token records consistently.
 *   Handle duplicate identifiers (e.g., existing email/username) with
 *   appropriate 4xx responses; handle invalid payload with 400. Include rate
 *   limiting on repeated join attempts if supported by infrastructure.
 * @path /shoppingMall/auth/admin/join
 * @accessor api.functional.shoppingMall.auth.admin.join
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function join(
  connection: IConnection,
  props: join.Props,
): Promise<join.Response> {
  const output: join.Response =
    true === connection.simulate
      ? join.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...join.METADATA,
            path: join.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace join {
  export type Props = {
    /**
     * Admin registration payload for creating a new admin account and initiating authorization.
     */
    body: IShoppingMallAdmin.IJoin;
  };
  export type Body = IShoppingMallAdmin.IJoin;
  export type Response = IShoppingMallAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/auth/admin/join",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/auth/admin/join";
  export const random = (): IShoppingMallAdmin.IAuthorized =>
    typia.random<IShoppingMallAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: join.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: join.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Authenticate an existing administrator account.
 *
 * This endpoint validates admin credentials provided in the request body `IShoppingMallAdmin.ILogin` and, upon success, returns `IShoppingMallAdmin.IAuthorized` which represents the authorized admin session context (typically including JWT access/refresh tokens and identity claims).
 *
 * Because the actor is `admin`, this endpoint is restricted by controller-level admin authentication flow semantics; however, credential validation itself is performed based on the provided login payload. The operation should not depend on any pre-existing business resources, and therefore it must not define prerequisite chains.
 *
 * Security considerations: enforce rate limiting and account lockout/suspension rules if they exist in the system. Never return sensitive information on authentication failure. Ensure password verification uses the configured hashing algorithm and that token issuance is performed only after successful credential verification.
 *
 * Related workflow integration: after login, clients will call admin-protected endpoints using the returned authorization tokens. If access tokens expire, clients should use the refresh endpoint described in `POST /auth/admin/refresh`.
 *
 * @setHeader token.access Authorization
 *
 * @param props.connection
 * @param props.body Admin login payload containing the credentials to authenticate.
 * @x-autobe-authorization-type login
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Implement POST /auth/admin/login as credential
 *   validation for admin: validate IShoppingMallAdmin.ILogin (e.g., admin login
 *   identifier and password), locate the corresponding admin account, verify
 *   credentials, and on success issue a fresh admin session/token set. Persist
 *   session token data using the admin session storage schema if present, and
 *   return IShoppingMallAdmin.IAuthorized. Use constant-time password
 *   comparison and avoid leaking whether the account exists. On failure, return
 *   401/403 without tokens.
 * @path /shoppingMall/auth/admin/login
 * @accessor api.functional.shoppingMall.auth.admin.login
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function login(
  connection: IConnection,
  props: login.Props,
): Promise<login.Response> {
  const output: login.Response =
    true === connection.simulate
      ? login.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...login.METADATA,
            path: login.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace login {
  export type Props = {
    /**
     * Admin login payload containing the credentials to authenticate.
     */
    body: IShoppingMallAdmin.ILogin;
  };
  export type Body = IShoppingMallAdmin.ILogin;
  export type Response = IShoppingMallAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/auth/admin/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/auth/admin/login";
  export const random = (): IShoppingMallAdmin.IAuthorized =>
    typia.random<IShoppingMallAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: login.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: login.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Renew authorization tokens for an administrator.
 *
 * This endpoint accepts a refresh request payload defined by `IShoppingMallAdmin.IRefresh` and returns `IShoppingMallAdmin.IAuthorized` containing newly issued authorization tokens for the admin actor.
 *
 * Security considerations: the refresh token must be validated for integrity, expiration, and (if supported by the schema) association with an existing admin session record. If token rotation is implemented, the old refresh token/session should be invalidated according to the system’s security policy. Do not allow refresh with missing/invalid tokens.
 *
 * Integration: clients should use this endpoint when an access token expires and they still possess a valid refresh credential. This endpoint is part of the authentication workflow and therefore has no business prerequisites.
 *
 * Error behavior: for invalid, expired, or revoked refresh credentials, return an appropriate 401/403 status and never return authorization tokens.
 *
 * @setHeader token.access Authorization
 *
 * @param props.connection
 * @param props.body Admin refresh payload used to renew tokens.
 * @x-autobe-authorization-type refresh
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Implement POST /auth/admin/refresh as token renewal
 *   for admin: validate IShoppingMallAdmin.IRefresh (e.g., refresh token or
 *   token renewal parameters). Verify the refresh token belongs to an active
 *   admin session/token store if applicable, rotate tokens if the system
 *   requires rotation, persist any updated session state, and return a fresh
 *   IShoppingMallAdmin.IAuthorized. Return 401/403 for invalid/expired tokens
 *   without issuing new tokens.
 * @path /shoppingMall/auth/admin/refresh
 * @accessor api.functional.shoppingMall.auth.admin.refresh
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function refresh(
  connection: IConnection,
  props: refresh.Props,
): Promise<refresh.Response> {
  const output: refresh.Response =
    true === connection.simulate
      ? refresh.simulate(connection, props)
      : await PlainFetcher.fetch(
          {
            ...connection,
            headers: {
              ...connection.headers,
              "Content-Type": "application/json",
            },
          },
          {
            ...refresh.METADATA,
            path: refresh.path(),
            status: null,
          },
          props.body,
        );
  connection.headers ??= {};
  connection.headers.Authorization = output.token.access;
  return output;
}
export namespace refresh {
  export type Props = {
    /**
     * Admin refresh payload used to renew tokens.
     */
    body: IShoppingMallAdmin.IRefresh;
  };
  export type Body = IShoppingMallAdmin.IRefresh;
  export type Response = IShoppingMallAdmin.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/shoppingMall/auth/admin/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/auth/admin/refresh";
  export const random = (): IShoppingMallAdmin.IAuthorized =>
    typia.random<IShoppingMallAdmin.IAuthorized>();
  export const simulate = (
    connection: IConnection,
    props: refresh.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: refresh.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
