import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IEcommerceOrder } from "../../../../structures/IEcommerceOrder";
import { IPageIEcommerceOrder } from "../../../../structures/IPageIEcommerceOrder";

export * as items from "./items/index";
export * as payment_transactions from "./payment_transactions/index";
export * as history from "./history/index";

/**
 * Create a new order from the customer's shopping cart contents.
 *
 * This operation converts the customer's current shopping cart into a completed order by processing payment, deducting inventory quantities, clearing the cart, and creating comprehensive order records with purchase-time snapshots. The operation validates that all cart items are available in sufficient quantities before proceeding with order creation.
 *
 * Security considerations require that only authenticated customers can create orders from their own shopping carts. Each order preserves complete transaction integrity through snapshots of product information, variant details, and seller profiles at the moment of purchase.
 *
 * The operation integrates with external payment gateways to process customer payments securely. Upon successful payment, the system creates the order record, updates inventory levels, and clears the customer's shopping cart. Order items maintain individual status tracking to support partial cancellations and refunds.
 *
 * Related operations include GET /customers/orders for viewing order history and PATCH /customers/cart for managing shopping cart contents before checkout. This operation represents the final step in the customer purchasing workflow, transitioning items from cart selections to completed orders.
 *
 * Validation rules ensure that all cart items have sufficient stock availability, the selected shipping address is valid, and payment information is properly formatted before order creation proceeds. The operation maintains atomic transaction integrity to prevent partial order creation in case of system failures.
 *
 * @param props.connection
 * @param props.body Order creation information including shipping address and payment details
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Validate customer authentication and retrieve current shopping cart. Check that all cart items have sufficient stock availability. Process payment through external gateway integration. Create order record with sequential order number. Convert cart items to order items with purchase-time snapshots of products, variants, and seller profiles. Deduct inventory quantities for purchased variants. Clear customer's shopping cart upon successful order creation. Send order confirmation email to customer. Return complete order details with individual item statuses.
 *
 * Implementation details: Use database transaction to ensure atomic order creation. Validate cart items against current stock levels before payment processing. Capture complete product and variant snapshots at purchase time. Create individual order items with seller attribution for multi-seller order support. Update inventory records with negative quantity transactions. Handle payment failures with proper rollback procedures.
 * @path /ecommerce/customer/orders
 * @accessor api.functional.ecommerce.customer.orders.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Order creation information including shipping address and payment details
     */
    body: IEcommerceOrder;
  };
  export type Body = IEcommerceOrder;
  export type Response = IEcommerceOrder;

  export const METADATA = {
    method: "POST",
    path: "/ecommerce/customer/orders",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/ecommerce/customer/orders";
  export const random = (): IEcommerceOrder => typia.random<IEcommerceOrder>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Search and retrieve a paginated list of orders with advanced filtering capabilities for authenticated customers.
 *
 * This operation provides comprehensive order search functionality supporting multiple filter criteria including date ranges and order status filtering. The system automatically restricts access to the authenticated customer's own orders, ensuring data privacy and security compliance. Customers cannot view or search orders belonging to other customers.
 *
 * The response includes summarized order information optimized for list displays, including order creation dates, item counts, total values, and status information. Pagination support ensures efficient handling of large result sets with configurable page sizes and sorting options.
 *
 * All filtering and search operations are performed server-side for data protection and performance optimization. The operation leverages the ecommerce_orders database table structure and maintains referential integrity with the ecommerce_customers table through the customer_id foreign key relationship. This design preserves order audit trails even when customer accounts are deleted for legal and business record-keeping requirements.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for filtering orders
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query the ecommerce_orders table with optional filtering criteria including customer ID, date ranges, and status filtering. Join with ecommerce_customers table to include customer display name in summary responses. Apply pagination using cursor-based or offset-based pagination. Validate that customers can only see their own orders unless the requester is an administrator. For administrators, return all orders with full access. Include order item count and total value calculations in the summary response.
 * @path /ecommerce/customer/orders
 * @accessor api.functional.ecommerce.customer.orders.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for filtering orders
     */
    body: IEcommerceOrder.IRequest;
  };
  export type Body = IEcommerceOrder.IRequest;
  export type Response = IPageIEcommerceOrder.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/ecommerce/customer/orders",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/ecommerce/customer/orders";
  export const random = (): IPageIEcommerceOrder.ISummary =>
    typia.random<IPageIEcommerceOrder.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific order including all order items, purchase snapshots, payment transactions, and shipment status.
 *
 * This operation provides comprehensive order details for authorized users. Customers can access their own orders to view purchase history and track order progress. The response includes the complete order structure with preserved purchase-time information through embedded purchase snapshots for each order item.
 *
 * Order details include customer information, order creation timestamp, order status derived from item statuses, and all individual order items with their purchase-time product, variant, and seller information. Each item includes quantity, unit price, total price, and current status (paid, shipped, delivered, cancelled, or refunded). The response also includes payment transaction details and shipment tracking information when available.
 *
 * The system preserves order history and purchase snapshots even when customer accounts are deleted, maintaining financial integrity and audit trails. This operation is essential for order tracking, customer service, and fulfillment management across the e-commerce platform.
 *
 * @param props.connection
 * @param props.orderId UUID identifier of the specific order to retrieve
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor customer
 * @x-autobe-specification Query the ecommerce_orders table by the provided orderId UUID. Include nested relations for order items, purchase snapshots, payment transactions, and shipment information. Apply authorization checks: customers can only access their own orders, sellers can access orders containing their products, administrators have full access. The order status should be derived from the individual item statuses following the platform's status hierarchy. Return all order details with comprehensive nested information for complete order visibility.
 * @path /ecommerce/customer/orders/:orderId
 * @accessor api.functional.ecommerce.customer.orders.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * UUID identifier of the specific order to retrieve
     */
    orderId: string & tags.Format<"uuid">;
  };
  export type Response = IEcommerceOrder;

  export const METADATA = {
    method: "GET",
    path: "/ecommerce/customer/orders/:orderId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommerce/customer/orders/${encodeURIComponent(props.orderId ?? "null")}`;
  export const random = (): IEcommerceOrder => typia.random<IEcommerceOrder>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("orderId")(() => typia.assert(props.orderId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
