import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { IEcommerceReview } from "../../../../../api/structures/IEcommerceReview";
import { CustomerAuth } from "../../../../../decorators/CustomerAuth";
import { CustomerPayload } from "../../../../../decorators/payload/CustomerPayload";
import { deleteEcommerceCustomerProductsProductIdReviewsReviewId } from "../../../../../providers/deleteEcommerceCustomerProductsProductIdReviewsReviewId";
import { postEcommerceCustomerProductsProductIdReviews } from "../../../../../providers/postEcommerceCustomerProductsProductIdReviews";
import { putEcommerceCustomerProductsProductIdReviewsReviewId } from "../../../../../providers/putEcommerceCustomerProductsProductIdReviewsReviewId";

@Controller("/ecommerce/customer/products/:productId/reviews")
export class EcommerceCustomerProductsReviewsController {
  /**
   * Create a new product review for a purchased and delivered product.
   *
   * This operation allows customers to submit reviews for products they have purchased and received. The system validates that the customer has purchased the product through a valid order item that has reached 'delivered' status. Each customer can write only one review per product per order to prevent duplicate feedback.
   *
   * Before creating the review, the system performs comprehensive validation checks including purchase verification, delivery status confirmation, and duplicate review prevention. The review creation process creates an immutable audit trail through the ecommerce_review_edits table to preserve the initial review state.
   *
   * Reviews include a required star rating (1-5) and optional text content up to 5000 characters. Once created, reviews are immediately visible on the product detail page and contribute to the product's average rating calculation. Customers can later edit or delete their reviews while maintaining the audit trail through snapshots.
   *
   * This operation requires valid customer authentication and authorization to ensure only legitimate purchasers can submit reviews. The system enforces business rules to maintain review integrity and prevent fraudulent or duplicate submissions.
   *
   * @param connection
   * @param productId Unique identifier of the product being reviewed
   * @param body Review creation data including required rating (1-5 stars) and optional text content (max 5000 characters)
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor customer
   * @x-autobe-specification Validate customer authentication and authorization first. Check if the customer has purchased the product by querying ecommerce_order_items table with conditions: customer_id matches authenticated customer, product_variant_id belongs to the target product (via ecommerce_product_variants.ecommerce_product_id), and status is 'delivered'. Verify no existing review exists for the same customer, product, and order item combination using the unique constraint on ecommerce_reviews table.
   *
   * If validation passes, create a new review record in ecommerce_reviews table with the provided rating and content. Set is_deleted to false and capture current timestamp. The system should automatically create the first snapshot in ecommerce_review_edits table to preserve the initial review state.
   *
   * Handle edge cases: product not found, customer hasn't purchased product, order item not delivered, duplicate review attempt, invalid rating (must be 1-5), content too long. Return appropriate error messages for each validation failure.
   *
   * After successful creation, update the product's average rating by recalculating from all non-deleted reviews for the product. Return the created review with standard fields including generated ID and timestamps.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IEcommerceReview.ICreate,
  ): Promise<IEcommerceReview> {
    try {
      return await postEcommerceCustomerProductsProductIdReviews({
        customer,
        productId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update an existing customer review for a specific product.
   *
   * This operation allows customers to modify their previously submitted reviews, including changing the star rating and updating the text content. The system enforces business rules requiring that customers can only edit their own reviews and that each review corresponds to a specific product purchase that has been delivered.
   *
   * When a review is updated, the system automatically creates an immutable snapshot of the previous review state through the ecommerce_review_edits table. This preserves the complete audit trail of all modifications for dispute resolution and compliance purposes. The product's average rating is recalculated to reflect the updated review content.
   *
   * Review updates follow the platform's financial integrity requirements where all customer-facing content modifications must be tracked. Customers can edit their reviews multiple times, with each edit generating a new snapshot record capturing both the rating changes and content modifications.
   *
   * The operation validates that the review belongs to the authenticated customer and that the specified product ID matches the review's product reference. Rating values must be between 1 and 5 stars, and text content cannot exceed 5000 characters.
   *
   * @param connection
   * @param productId Unique identifier of the product being reviewed
   * @param reviewId Unique identifier of the review to update
   * @param body Updated review content including rating and optional text
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor customer
   * @x-autobe-specification Validate that the authenticated customer owns the specified review. Check that the review exists and belongs to the correct product. Validate the rating (1-5 stars) and content length (max 5000 characters). Create a review edit snapshot before applying changes to preserve audit trail. Update the review with new rating and content. Update the product's average rating calculation. Return the updated review with current timestamp.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":reviewId")
  public async update(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
    @TypedParam("reviewId")
    reviewId: string & tags.Format<"uuid">,
    @TypedBody()
    body: IEcommerceReview.IUpdate,
  ): Promise<IEcommerceReview> {
    try {
      return await putEcommerceCustomerProductsProductIdReviewsReviewId({
        customer,
        productId,
        reviewId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete a customer's product review by marking it as deleted while preserving review snapshots for audit purposes.
   *
   * This operation allows customers to remove their reviews from public display while maintaining the integrity of the review system's audit trail. When a review is deleted, it is no longer visible on product pages or included in average rating calculations, but all historical snapshots of the review content and rating changes are preserved indefinitely.
   *
   * The deletion process validates that the authenticated customer owns the review being deleted and ensures that only the review owner can perform this operation. Reviews can only be deleted by the original author, and once deleted, they cannot be restored through normal customer actions.
   *
   * This operation follows the platform's data preservation principles where review content is maintained for legal and dispute resolution purposes even after customer-initiated deletion. The system maintains the relationship between the review, the product, and the order item that enabled the review creation.
   *
   * Related operations include creating reviews (POST /customers/orders/{orderId}/products/{productId}/reviews) and editing reviews (PUT /customers/reviews/{reviewId}) which also create immutable snapshots of review changes.
   *
   * @param connection
   * @param productId ID of the product associated with the review
   * @param reviewId ID of the review to be deleted
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor customer
   * @x-autobe-specification Validate that the authenticated customer owns the review before deletion. Update the review's is_deleted flag to true and set deleted_at timestamp. Preserve all review snapshots in ecommerce_review_edits table for audit trail. Ensure the review exists and belongs to the authenticated customer before proceeding with deletion.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":reviewId")
  public async erase(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("productId")
    productId: string & tags.Format<"uuid">,
    @TypedParam("reviewId")
    reviewId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteEcommerceCustomerProductsProductIdReviewsReviewId({
        customer,
        productId,
        reviewId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
