import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IEcommerceMallShipment } from "../../../../api/structures/IEcommerceMallShipment";
import { CustomerAuth } from "../../../../decorators/CustomerAuth";
import { CustomerPayload } from "../../../../decorators/payload/CustomerPayload";
import { getEcommerceMallCustomerShipmentsShipmentId } from "../../../../providers/getEcommerceMallCustomerShipmentsShipmentId";
import { putEcommerceMallCustomerShipmentsShipmentId } from "../../../../providers/putEcommerceMallCustomerShipmentsShipmentId";

@Controller("/ecommerceMall/customer/shipments/:shipmentId")
export class EcommercemallCustomerShipmentsController {
  /**
   * Retrieve detailed information about a specific shipment including carrier details and package contents.
   *
   * This operation provides comprehensive shipment tracking information for a specific physical package. The shipment contains one or more order items that are being delivered together, and includes carrier name and tracking number for delivery status monitoring.
   *
   * ## Shipment Context
   *
   * A shipment represents a physical package that contains one or more order items from the same seller. When an order includes items from multiple sellers, each seller creates their own separate shipment. The shipment tracks the delivery status of all included items together.
   *
   * ## Security and Authorization
   *
   * Only the seller who created the shipment or the customer who placed the order can access shipment details. The operation enforces ownership validation to ensure sellers can only view their own shipments and customers can only view shipments related to their orders.
   *
   * ## Shipment Items
   *
   * The response includes all shipment items that reference the order items included in this shipment. Each shipment item represents one order item that is part of this physical package.
   *
   * ## Delivery Tracking
   *
   * The shipment includes optional carrier name and tracking number fields that enable integration with shipping carriers. When these fields are populated, customers can track the delivery status of their package through the carrier's system.
   *
   * ## Status Progression
   *
   * Shipments follow a status flow: pending → shipped → delivered. The delivery confirmation can be done per shipment, which automatically marks all associated shipment items as delivered.
   *
   * @param connection
   * @param shipmentId Target shipment's unique identifier
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor customer
   * @x-autobe-specification Query ecommerce_mall_shipments table by id with seller and order relations.
   * Join with shipment_items to get order items in this shipment.
   * Include carrier_name and tracking_number for delivery tracking.
   * Return full shipment details with nested shipment items array.
   * Enforce seller ownership for sellers and order ownership for customers.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async at(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("shipmentId")
    shipmentId: string,
  ): Promise<IEcommerceMallShipment> {
    try {
      return await getEcommerceMallCustomerShipmentsShipmentId({
        customer,
        shipmentId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update shipment information for a seller-owned shipment.
   *
   * This operation allows sellers to update carrier and tracking information for their shipments. Sellers can only update shipments they own - cross-seller shipment updates are prohibited.
   *
   * The update modifies the shipment's carrier_name and tracking_number fields which are used for delivery tracking. When a seller ships items, they populate these fields with carrier details provided by the shipping service.
   *
   * The system enforces strict ownership validation: sellers can only update shipments where they are the designated seller, ensuring proper separation between sellers in multi-seller orders.
   *
   * This operation does not affect shipment items or their status - it only updates the shipment record metadata.
   *
   * @param connection
   * @param shipmentId Target shipment's unique identifier (UUID)
   * @param body Shipment update payload with carrier and tracking information
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor customer
   * @x-autobe-specification Update shipment carrier and tracking information for seller-owned shipments.
   * 1. Validate seller ownership by verifying the active seller matches shipment.ecommerce_mall_seller_id
   * 2. Reject update if shipment belongs to different seller
   * 3. Update carrier_name and tracking_number fields from request body
   * 4. Return complete shipment entity with updated values
   * 5. Apply soft delete filtering if shipment is deleted
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put()
  public async update(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedParam("shipmentId")
    shipmentId: string,
    @TypedBody()
    body: IEcommerceMallShipment.IUpdate,
  ): Promise<void> {
    try {
      return await putEcommerceMallCustomerShipmentsShipmentId({
        customer,
        shipmentId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
