import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IDiscussionBoardArticle } from "../../../../../structures/IDiscussionBoardArticle";

/**
 * Create a new article within a specific section of the discussion board.
 *
 * This operation allows authenticated users (members, administrators, and super administrators) to create new discussion articles within a selected section. When creating an article, the system requires a title (1-500 characters) and content (text), and automatically associates the article with the authenticated user as the author and the specified section.
 *
 * The operation supports optional file attachments that are validated for size and type according to system policies. Each attachment is linked to the article and stored with metadata including filename, file size, file type, and upload timestamp.
 *
 * Security considerations include role-based access control where only authenticated users can create articles, and section existence validation to prevent posting to non-existent sections. The operation enforces validation rules including title length constraints and content requirements.
 *
 * @param props.connection
 * @param props.sectionId The unique identifier of the section where the article will be created. Must be a valid section ID that exists in the system.
 * @param props.body Article creation data including title, content, and optional file attachments
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Create a new article within the specified section. The operation requires: 1) Valid section ID that exists and is not deleted, 2) Authenticated user (member, admin, or super admin), 3) Non-empty title (1-500 characters) and content, 4) Optional file attachments with size/type validation. The article is associated with the authenticated user as author and the specified section. Returns the created article with all fields including auto-generated timestamps and IDs.
 * @path /discussionBoard/admin/sections/:sectionId/articles
 * @accessor api.functional.discussionBoard.admin.sections.articles.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * The unique identifier of the section where the article will be created. Must be a valid section ID that exists in the system.
     */
    sectionId: string & tags.Format<"uuid">;

    /**
     * Article creation data including title, content, and optional file attachments
     */
    body: IDiscussionBoardArticle.ICreate;
  };
  export type Body = IDiscussionBoardArticle.ICreate;
  export type Response = IDiscussionBoardArticle;

  export const METADATA = {
    method: "POST",
    path: "/discussionBoard/admin/sections/:sectionId/articles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/discussionBoard/admin/sections/${encodeURIComponent(props.sectionId ?? "null")}/articles`;
  export const random = (): IDiscussionBoardArticle =>
    typia.random<IDiscussionBoardArticle>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("sectionId")(() => typia.assert(props.sectionId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
