import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IShoppingMallProductCategory } from "../../../../structures/IShoppingMallProductCategory";
import { IPageIShoppingMallProductCategory } from "../../../../structures/IPageIShoppingMallProductCategory";

/**
 * Retrieve a filtered and paginated list of shopping product categories from
 * the system. This operation operates on the ProductCategories table from the
 * database schema and provides advanced search capabilities for finding
 * categories based on multiple criteria including partial name matching,
 * hierarchy-based filtering, and category status.
 *
 * The operation supports comprehensive pagination with configurable page sizes
 * and sorting options. Categories can sort by name, hierarchy, creation date,
 * and active status in ascending or descending order.
 *
 * Security considerations include rate limiting for search operations and
 * appropriate filtering of sensitive category information based on the
 * requesting user's authorization level. Only users with appropriate
 * permissions (admins and sellers) can access detailed category information,
 * while basic category lists may be available to authenticated users.
 *
 * @param props.connection
 * @param props.body Search criteria, filters, and pagination parameters for
 *   product categories
 * @path /shoppingMall/seller/categories
 * @accessor api.functional.shoppingMall.seller.categories.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria, filters, and pagination parameters for product
     * categories
     */
    body: IShoppingMallProductCategory.IRequest;
  };
  export type Body = IShoppingMallProductCategory.IRequest;
  export type Response = IPageIShoppingMallProductCategory.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/shoppingMall/seller/categories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/shoppingMall/seller/categories";
  export const random = (): IPageIShoppingMallProductCategory.ISummary =>
    typia.random<IPageIShoppingMallProductCategory.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
