import { tags } from "typia";

import { ITodoAppUser } from "./ITodoAppUser";
import { ITodoAppAccessToken } from "./ITodoAppAccessToken";
import { ITodoAppRefreshToken } from "./ITodoAppRefreshToken";

/**
 * User session entity containing authentication data and metadata for the
 * todoApp system user sessions stored in the todo_app_user_sessions table. This
 * entity tracks session lifecycle, ownership, and security tokens for managing
 * logged-in user sessions.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type ITodoAppUserSession = {
  /**
   * Unique identifier for the user session record in the
   * todo_app_user_sessions table, generated as a UUID.
   */
  id: string & tags.Format<"uuid">;

  /**
   * JWT access token issued to authenticate API requests during the session.
   * Used for authorization and securing resource access.
   */
  accessTokens: string;

  /**
   * Refresh token issued to renew the access token without requiring user
   * re-authentication. Enables long-lived sessions securely.
   */
  refreshTokens: string;

  /**
   * Datetime when this session expires. Null if the session does not expire
   * or is indefinitely valid.
   */
  expired_at: (string & tags.Format<"date-time">) | null;

  /**
   * Timestamp recording when the session was created. Managed by the system
   * for auditing and session lifecycle tracking.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp recording the last time the session record was updated.
   * Nullable for initial creations before updates.
   */
  expired_at_updated_at: (string & tags.Format<"date-time">) | null;

  /**
   * IP address from which the session was initiated or last used. Nullable to
   * handle cases where IP info is unavailable.
   */
  ip: (string & tags.Format<"ipv4">) | (string & tags.Format<"ipv6">) | null;

  /**
   * HTTP User-Agent string from the client device or browser that initiated
   * the session. Nullable if not recorded.
   */
  href: string | null;

  /**
   * Associated user entity to whom this session belongs. Provides user
   * identification and summary information.
   */
  todoAppUser: ITodoAppUser.ISummary;
};
export namespace ITodoAppUserSession {
  /**
   * Request parameters for searching and paginating user sessions in the
   * todoApp system. Supports filtering by session status, creation and
   * expiration dates, IP addresses, and user agent strings, along with
   * pagination controls for scalable querying.
   */
  export type IRequest = {
    /**
     * Page number for paginated results. This value must be a positive
     * integer starting from 1. Pagination enables clients to retrieve
     * session data in manageable chunks for performance and usability.
     */
    page: number & tags.Type<"int32">;

    /**
     * Number of records to return per page in paginated results. This value
     * must be a positive integer and helps control the volume of data
     * transferred in a single response.
     */
    pageSize: number & tags.Type<"int32">;

    /**
     * Status of the user session, used to filter active or inactive
     * sessions based on session lifecycle states such as 'active',
     * 'expired', or 'revoked'.
     */
    status?: string | undefined;

    /**
     * Filter sessions created on or after this timestamp. The timestamp
     * must be in ISO 8601 date-time format. Enables retrieval of sessions
     * starting from a specific creation date.
     */
    createdFrom?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter sessions created before or on this timestamp. The timestamp
     * must be in ISO 8601 date-time format. Enables retrieval of sessions
     * up to a specific creation date.
     */
    createdTo?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filters sessions based on their expiration state. When true, only
     * expired sessions are returned; when false, only active sessions are
     * returned.
     */
    expired?: boolean | undefined;

    /**
     * Filter sessions updated on or after this timestamp. Useful for
     * retrieving sessions with recent activity. Must be a valid ISO 8601
     * date-time string.
     */
    lastUpdatedFrom?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter sessions updated before or on this timestamp. Useful for
     * retrieving sessions no longer recently updated. Must be a valid ISO
     * 8601 date-time string.
     */
    lastUpdatedTo?: (string & tags.Format<"date-time">) | undefined;

    /**
     * Filter sessions matching the specified client IP address. Useful for
     * security monitoring and detecting session origin. IP should be in
     * IPv4 or IPv6 format.
     */
    ip?: string | undefined;

    /**
     * Filter sessions where the client's user agent string matches this
     * value, enabling filtering by browser or device type.
     */
    userAgent?: string | undefined;
  };

  /**
   * Summary view of user sessions in the todoApp system, representing
   * essential metadata of active or inactive sessions associated with
   * authenticated users.
   */
  export type ISummary = {
    /** Unique identifier for the user session record. */
    id: string & tags.Format<"uuid">;

    /**
     * Summary information of the user associated with this session. This
     * replaces the raw todo_app_user_id foreign key for richer context.
     */
    user: ITodoAppUser.ISummary;

    /**
     * IP address from which the session was initiated. Used for security
     * monitoring and audit trails.
     */
    ip: string;

    /**
     * The URL from which the session originated, capturing the client-side
     * page location when the session was established.
     */
    href: string & tags.Format<"uri">;

    /**
     * The referrer URL indicating the previous page before the session was
     * established, useful for tracking user navigation paths.
     */
    referrer: string & tags.Format<"uri">;

    /** Timestamp indicating when the session was created. */
    createdAt: string & tags.Format<"date-time">;

    /**
     * Timestamp when this session is set to expire. Sessions beyond this
     * point are invalid and require re-authentication.
     */
    expiredAt: string & tags.Format<"date-time">;

    /**
     * List of access tokens issued for this session, representing the
     * authentication credentials used.
     */
    accessTokens: ITodoAppAccessToken.ISummary[];

    /**
     * List of refresh tokens associated with this session to maintain
     * long-term authentication securely.
     */
    refreshTokens: ITodoAppRefreshToken.ISummary[];
  };
}
