import { tags } from "typia";

import { IShoppingMallSale } from "./IShoppingMallSale";
import { IShoppingMallBuyer } from "./IShoppingMallBuyer";
import { IShoppingMallSaleQuestionAnswer } from "./IShoppingMallSaleQuestionAnswer";

/**
 * Complete representation of a customer question about a product sale.
 *
 * This entity represents a buyer's inquiry posted on a product listing, seeking
 * additional information before making a purchase decision. Questions enable
 * transparent communication between potential buyers and sellers, helping
 * customers understand product details, features, availability, and other
 * purchase-related concerns. The Q&A system supports informed decision-making
 * and can reduce purchase hesitation.
 *
 * Each question is associated with a specific product sale and authored by an
 * authenticated buyer. The question may have at most one seller answer,
 * establishing a one-to-one relationship that provides clear, authoritative
 * responses from the product owner. Unanswered questions are visible to
 * sellers, prompting timely responses that demonstrate engagement and customer
 * service quality.
 *
 * Visibility of questions and answers is public to all users viewing the
 * product, supporting marketplace transparency. This allows potential buyers to
 * benefit from questions asked by others, reducing duplicate inquiries and
 * providing comprehensive product information. The system tracks creation
 * timestamps to support chronological ordering and display question recency.
 *
 * Security considerations include buyer authentication to prevent spam
 * questions and ensure accountability. The system may implement rate limiting
 * to prevent abuse. Questions are permanently associated with the buyer who
 * posted them, supporting moderation and quality enforcement.
 *
 * This entity maps to the shopping_mall_sale_questions table in the Prisma
 * database schema. It maintains foreign key relationships with
 * shopping_mall_sales (parent product) and shopping_mall_buyers (question
 * author). The entity supports CRUD operations through dedicated API endpoints,
 * with sellers able to answer questions via related answer endpoints.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IShoppingMallSaleQuestion = {
  /**
   * Unique identifier for the customer question.
   *
   * This UUID uniquely identifies each question record in the
   * shopping_mall_sale_questions table. The ID is automatically generated by
   * the system upon question creation and remains immutable. It serves as the
   * primary key for referencing specific questions in database relationships
   * and API operations.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Foreign key reference to the parent product sale.
   *
   * This field establishes the relationship between the question and the
   * specific product sale it concerns. It references the id field in the
   * shopping_mall_sales table, enabling queries to retrieve all questions for
   * a particular product. This foreign key constraint ensures data integrity
   * and prevents orphaned question records.
   */
  shopping_mall_sale_id: string & tags.Format<"uuid">;

  /**
   * Foreign key reference to the buyer who posted the question.
   *
   * This field identifies which buyer authored this question, referencing the
   * id field in the shopping_mall_buyers table. It enables tracking of buyer
   * engagement and question history, and supports user-specific queries such
   * as retrieving all questions a buyer has asked across the platform.
   */
  shopping_mall_buyer_id: string & tags.Format<"uuid">;

  /**
   * Session identifier through which the question was submitted.
   *
   * This field references the specific buyer authentication session used when
   * posting the question, linking to the shopping_mall_buyer_sessions table.
   * It provides audit trail capabilities by tracking which session was active
   * during question submission.
   *
   * This information is crucial for security monitoring, fraud detection, and
   * compliance purposes. It enables administrators to trace question
   * submissions back to specific login sessions, helping identify suspicious
   * patterns or unauthorized access. The session context also supports
   * debugging and customer support by providing complete interaction
   * history.
   */
  shopping_mall_buyer_session_id: string & tags.Format<"uuid">;

  /**
   * Question title or subject summarizing the inquiry.
   *
   * This field contains a brief, concise summary of the question that helps
   * buyers and sellers quickly identify the topic without reading the full
   * question body. The title should be descriptive enough to understand the
   * question's focus at a glance.
   *
   * Titles are limited to a maximum of 200 characters to ensure they remain
   * concise and scannable in list views. Well-crafted titles improve the
   * browsing experience by allowing users to quickly find relevant questions
   * and answers. They also help avoid duplicate questions by making existing
   * inquiries more discoverable.
   */
  title: string & tags.MaxLength<200>;

  /**
   * Detailed question content with buyer's specific inquiry.
   *
   * This field contains the complete inquiry submitted by the buyer seeking
   * additional information about the product sale. Questions typically
   * concern product features, specifications, availability, shipping,
   * compatibility, or other purchase-related concerns. The body supports
   * multi-line text to accommodate detailed questions with multiple parts.
   *
   * The content must be between 10 and 2000 characters in length, ensuring
   * questions are substantive enough to be meaningful while preventing
   * excessively long submissions. Questions should be clear, specific, and
   * respectful to enable sellers to provide helpful, accurate responses.
   * Well-formulated questions benefit all potential buyers by building a
   * comprehensive knowledge base about the product.
   */
  body: string & tags.MinLength<10> & tags.MaxLength<2000>;

  /**
   * Timestamp when the question was originally posted.
   *
   * This field records the exact date and time when the buyer submitted their
   * question. The timestamp is automatically set by the system upon question
   * creation and remains immutable. It helps buyers and sellers understand
   * the recency of questions and supports chronological ordering of Q&A
   * interactions. The format follows ISO 8601 standard
   * (YYYY-MM-DDTHH:mm:ss.sssZ).
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the question was last modified.
   *
   * This field records the most recent modification time for the question
   * content. It is automatically updated by the system whenever the question
   * title or body is edited. The timestamp helps track question editing
   * history and displays to users when questions have been recently updated.
   *
   * The updated_at field is distinct from created_at, allowing the system to
   * differentiate between original posting time and subsequent modifications.
   * This supports transparency in the Q&A system by showing when questions
   * have been edited after initial submission. The format follows ISO 8601
   * standard (YYYY-MM-DDTHH:mm:ss.sssZ).
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Soft deletion timestamp for the question.
   *
   * When this field is set to a timestamp value, the question is considered
   * logically deleted and hidden from public display. However, the question
   * record and all associated data remain in the database to preserve audit
   * trails and maintain data integrity for historical orders or references.
   *
   * Soft deletion allows administrators to remove inappropriate or
   * policy-violating questions without losing the complete interaction
   * history. Questions can potentially be restored by clearing this field if
   * deletion was performed in error. When null, the question is active and
   * publicly visible. The timestamp format follows ISO 8601 standard
   * (YYYY-MM-DDTHH:mm:ss.sssZ).
   */
  deleted_at?: (string & tags.Format<"date-time">) | null | undefined;

  /**
   * Summary information about the product sale that this question concerns.
   *
   * This reference provides essential product context including the sale
   * name, price, and seller information. By including this summary, API
   * consumers can display product details alongside the question without
   * requiring additional API calls. The summary representation contains key
   * fields needed to understand what product is being asked about.
   */
  sale?: IShoppingMallSale.ISummary | undefined;

  /**
   * Summary information about the buyer who posted this question.
   *
   * This reference includes essential buyer details such as name and account
   * status. Displaying buyer information helps sellers understand who is
   * asking and may influence the nature of their response. The summary
   * provides key buyer attributes without exposing sensitive personal
   * information.
   */
  buyer?: IShoppingMallBuyer.ISummary | undefined;

  /**
   * The seller's answer to this question, if one has been provided.
   *
   * This field contains the complete answer entity when a seller has
   * responded to the question. It includes the answer content, seller
   * information, and timestamps. If no answer has been posted yet, this field
   * is null, indicating an unanswered question that awaits seller response.
   * The one-to-one relationship ensures each question has at most one
   * official seller answer.
   */
  answer?: IShoppingMallSaleQuestionAnswer | null | undefined;
};
export namespace IShoppingMallSaleQuestion {
  /**
   * Query parameters for searching, filtering, and paginating product sale
   * questions.
   *
   * Defines the request structure for retrieving filtered lists of customer
   * questions about a product sale. Supports pagination for efficient data
   * loading, filtering by buyer and answer status, date range selection,
   * full-text search, and flexible sorting options.
   *
   * This request DTO enables multiple use cases including seller dashboards
   * (filtering unanswered questions), buyer research interfaces (searching
   * answered questions), admin moderation tools (filtering by buyer or date
   * range), and general product Q&A browsing with customizable sort orders.
   *
   * Pagination parameters (limit and page) are required to enforce efficient
   * data retrieval and prevent large uncontrolled result sets. All filter
   * parameters are optional, allowing callers to apply filters as needed
   * while defaulting to showing all questions when no filters are specified.
   *
   * The search parameter leverages the GIN indexes on title and body fields
   * defined in the shopping_mall_sale_questions Prisma schema, enabling
   * performant full-text search across question content. Date range filtering
   * supports analytics and historical data review workflows.
   *
   * Used in PATCH /sales/{saleCode}/questions operations to retrieve
   * paginated, filtered question lists with flexible search and sorting
   * capabilities.
   */
  export type IRequest = {
    /**
     * Maximum number of question records to return per page.
     *
     * Controls the page size for paginated question list results. Accepts
     * values between 1 and 100 questions per page.
     *
     * Lower values improve response time and initial rendering performance.
     * Higher values reduce the number of requests needed to browse all
     * questions. Typical values range from 10-50 for optimal user
     * experience.
     */
    limit: number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>;

    /**
     * Page number for pagination, starting from 1.
     *
     * Specifies which page of question results to retrieve when the total
     * result set exceeds the limit. Page numbering is 1-indexed, meaning
     * the first page is page 1, not page 0.
     *
     * Combined with limit to calculate the offset for database queries. For
     * example, page=2 with limit=20 retrieves questions 21-40.
     */
    page: number & tags.Type<"int32"> & tags.Minimum<1>;

    /**
     * Optional filter to retrieve questions from a specific buyer.
     *
     * When provided, filters the question list to show only questions
     * posted by the buyer with this UUID. Useful for buyer-specific views
     * such as "My Questions" pages or admin interfaces reviewing a specific
     * buyer's activity.
     *
     * When null or omitted, returns questions from all buyers for the
     * specified product sale. The filter references the
     * shopping_mall_buyer_id field in the shopping_mall_sale_questions
     * table.
     */
    shopping_mall_buyer_id?: (string & tags.Format<"uuid">) | null | undefined;

    /**
     * Optional filter to retrieve questions based on answer status.
     *
     * When true, returns only questions that have been answered by sellers.
     * When false, returns only unanswered questions awaiting seller
     * response. When null or omitted, returns all questions regardless of
     * answer status.
     *
     * Sellers use has_answer=false to find pending questions requiring
     * attention. Buyers use has_answer=true to browse already-answered
     * questions for product information.
     */
    has_answer?: boolean | null | undefined;

    /**
     * Optional filter to retrieve questions created after a specific
     * timestamp.
     *
     * When provided, returns only questions with created_at >= this ISO
     * 8601 datetime value. Useful for finding recent questions,
     * implementing "What's New" features, or filtering by time period.
     *
     * Format follows ISO 8601 standard (YYYY-MM-DDTHH:mm:ss.sssZ). When
     * null or omitted, no lower bound filter is applied.
     */
    created_after?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Optional filter to retrieve questions created before a specific
     * timestamp.
     *
     * When provided, returns only questions with created_at < this ISO 8601
     * datetime value. Combined with created_after enables date range
     * filtering for historical question analysis or time-bounded
     * reporting.
     *
     * Format follows ISO 8601 standard (YYYY-MM-DDTHH:mm:ss.sssZ). When
     * null or omitted, no upper bound filter is applied.
     */
    created_before?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Optional full-text search query for question title and body content.
     *
     * When provided, performs text search across question titles and body
     * content to find questions matching the search terms. Uses the GIN
     * indexes on title and body fields defined in the Prisma schema for
     * efficient full-text search.
     *
     * Supports finding questions by keywords, phrases, or specific product
     * features mentioned in questions. When null or omitted, no text
     * filtering is applied. Search is case-insensitive and may support
     * partial word matching depending on database configuration.
     */
    search?: string | null | undefined;

    /**
     * Optional field name to sort question results by.
     *
     * Specifies which field to use for ordering the question list.
     * Supported values: created_at (default, chronological order),
     * updated_at (recently modified first).
     *
     * When null or omitted, defaults to created_at ordering. Combined with
     * the order parameter to control ascending vs descending sort
     * direction.
     */
    sort?: "created_at" | "updated_at" | null | undefined;

    /**
     * Optional sort direction for ordering results.
     *
     * Specifies whether to sort in ascending (asc) or descending (desc)
     * order. For created_at sorting, desc shows newest questions first
     * (typical default), while asc shows oldest first.
     *
     * When null or omitted, defaults to desc (newest first) for
     * timestamp-based sorting. This ensures users see the most recent
     * questions by default, which is the expected behavior in Q&A
     * interfaces.
     */
    order?: "asc" | "desc" | null | undefined;
  };

  /**
   * Lightweight summary representation of customer product questions for list
   * views and paginated displays.
   *
   * Provides essential question information optimized for performance in
   * question list contexts, search results, and Q&A browsing interfaces.
   * Includes key identification, content preview, timing, and answer status
   * without the full question body or detailed metadata.
   *
   * This summary variant is used when displaying multiple questions in list
   * format, enabling efficient rendering without loading complete question
   * content. The has_answer field allows users to quickly identify which
   * questions have seller responses, supporting both buyer research workflows
   * and seller response management.
   *
   * Excludes the full question body to reduce payload size in list
   * operations. Buyers can access complete question details including the
   * full body content and any seller answer by fetching the individual
   * question via the detail endpoint.
   *
   * Optimized for use in paginated question lists (PATCH
   * /sales/{saleCode}/questions), seller dashboards showing pending
   * questions, and buyer interfaces for browsing product Q&A sections. The
   * minimal field set ensures fast load times while providing sufficient
   * context for navigation and filtering decisions.
   */
  export type ISummary = {
    /**
     * Unique identifier for the customer question.
     *
     * This UUID uniquely identifies each question record in the
     * shopping_mall_sale_questions table. Used for referencing specific
     * questions in navigation, APIs, and database relationships.
     *
     * The ID is automatically generated by the system upon question
     * creation and remains immutable throughout the question lifecycle.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Question title or subject summarizing the inquiry.
     *
     * Brief summary of the question topic that helps buyers and sellers
     * quickly identify the question's focus without reading the full body
     * content. Limited to maximum 200 characters for concise display in
     * list views.
     *
     * Well-crafted titles improve Q&A browsing experience and help users
     * find relevant questions quickly. They also reduce duplicate questions
     * by making existing inquiries more discoverable.
     */
    title: string;

    /**
     * Timestamp when the question was originally posted by the buyer.
     *
     * Records the exact date and time when the buyer submitted their
     * question. Automatically set by the system upon question creation and
     * remains immutable.
     *
     * Supports chronological ordering of questions in list displays and
     * helps buyers assess question recency. Format follows ISO 8601
     * standard (YYYY-MM-DDTHH:mm:ss.sssZ).
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Summary information about the buyer who posted this question.
     *
     * Provides essential buyer context including name and account
     * identification for attribution purposes. Displaying buyer information
     * in question lists helps sellers prioritize responses and understand
     * their customer base.
     *
     * The summary representation contains key buyer attributes without
     * exposing sensitive personal information, maintaining appropriate
     * privacy boundaries in public Q&A displays.
     */
    buyer: IShoppingMallBuyer.ISummary;

    /**
     * Indicates whether a seller has provided an answer to this question.
     *
     * Computed boolean flag derived from the existence of a related record
     * in the shopping_mall_sale_question_answers table. True when an answer
     * exists, false when the question remains unanswered.
     *
     * Helps buyers quickly identify which questions have been addressed by
     * sellers when browsing Q&A sections. Also enables filtering to show
     * only unanswered questions requiring seller attention or only answered
     * questions for information gathering.
     */
    has_answer: boolean;
  };

  /**
   * Request body for creating a new customer question about a product sale.
   *
   * Contains the question content submitted by an authenticated buyer seeking
   * additional product information. The buyer's identity is automatically
   * extracted from the JWT authentication token and should not be included in
   * the request body.
   *
   * This DTO enables buyers to submit questions to sellers, facilitating
   * informed purchase decisions through direct communication. The question
   * will be associated with the product sale specified in the URL path
   * parameter.
   */
  export type ICreate = {
    /**
     * Question title or subject line.
     *
     * Brief summary of the question topic (1-200 characters) that helps
     * buyers and sellers quickly identify the question's focus. Should be
     * concise and descriptive to facilitate question browsing.
     *
     * Example: "What is the battery life?", "Does this come in other
     * colors?", "Is this compatible with Mac?"
     */
    title: string & tags.MinLength<1> & tags.MaxLength<200>;

    /**
     * Full question content submitted by the buyer.
     *
     * Detailed inquiry text (10-2000 characters) containing the buyer's
     * specific questions or information requests about the product. This is
     * the main body of the question that the seller will respond to.
     *
     * The minimum length of 10 characters ensures questions are substantive
     * enough to be meaningful. Questions should be clear, specific, and
     * respectful. Avoid including personal contact information or requests
     * for off-platform transactions.
     */
    body: string & tags.MinLength<10> & tags.MaxLength<2000>;
  };
}
