import { tags } from "typia";

import { IAuthorizationToken } from "./IAuthorizationToken";

/**
 * Guest account entity representing anonymous visitor identity for the discussion board platform.
 *
 * Guest accounts are temporary identity records created for unauthenticated visitors who browse the discussion board without full registration. Each guest is uniquely identified by a device fingerprint generated from browser/device characteristics, enabling session continuity across multiple requests from the same device.
 *
 * This entity stores core identification and audit information including the device fingerprint, account creation timestamp, last update timestamp, and soft deletion timestamp. Guest accounts can have multiple associated session records stored in the discussion_board_guest_sessions table, which track individual connection details like IP address and navigation context.
 *
 * Access to guest account information is restricted to administrator accounts only for moderation and security oversight purposes. Regular members and guests themselves cannot query guest account data.
 *
 * Guest accounts support soft deletion to maintain audit trails while removing active access. Soft-deleted guests (deleted_at is not null) are excluded from active queries but retained for historical records.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IDiscussionBoardGuest = {
  /**
   * Unique identifier for the guest account.
   *
   * @x-autobe-database-schema-property id
   * @x-autobe-specification Direct mapping from discussion_board_guests.id. Primary key, UUID format, unique constraint.
   */
  id: string & tags.Format<"uuid">;

  /**
   * Unique device fingerprint identifying the guest across sessions.
   *
   * @x-autobe-database-schema-property device_fingerprint
   * @x-autobe-specification Direct mapping from discussion_board_guests.device_fingerprint. Unique string generated from browser/device characteristics for anonymous guest identification.
   */
  device_fingerprint: string;

  /**
   * Timestamp when the guest account was created.
   *
   * @x-autobe-database-schema-property created_at
   * @x-autobe-specification Direct mapping from discussion_board_guests.created_at. Timestamp with timezone (timestamptz), auto-populated on record creation.
   */
  created_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the guest account was last updated.
   *
   * @x-autobe-database-schema-property updated_at
   * @x-autobe-specification Direct mapping from discussion_board_guests.updated_at. Timestamp with timezone (timestamptz), auto-updated on record modification.
   */
  updated_at: string & tags.Format<"date-time">;

  /**
   * Timestamp when the guest account was soft deleted. Null indicates active account.
   *
   * @x-autobe-database-schema-property deleted_at
   * @x-autobe-specification Direct mapping from discussion_board_guests.deleted_at. Nullable timestamp with timezone (timestamptz). Null indicates active account; non-null indicates soft-deleted guest excluded from active queries.
   */
  deleted_at: (string & tags.Format<"date-time">) | null;
};
export namespace IDiscussionBoardGuest {
  /**
   * Request body for creating a guest session for anonymous browsing access to the discussion board. This DTO accepts device fingerprint information to identify and track guest users without requiring traditional email/password authentication. The device fingerprint serves as the primary identifier for anonymous users, enabling session persistence across multiple requests from the same device. Connection metadata (current page URL, referrer, IP address) is captured for security auditing and session continuity. Guest users can browse sections, view articles and comments, and search content without full authentication.
   */
  export type IJoin = {
    /**
     * Unique device fingerprint identifying the guest user across sessions. Generated from device characteristics for anonymous identification and session continuity.
     *
     * @x-autobe-database-schema-property device_fingerprint
     * @x-autobe-specification Direct mapping from discussion_board_guests.device_fingerprint column. Unique constraint enforced at database level. Service layer validates non-empty string format.
     */
    device_fingerprint: string;

    /**
     * Current page URL where the guest session is initiated. Used for session tracking and audit purposes.
     *
     * @x-autobe-specification Session context captured from HTTP request during guest session creation. Stored in discussion_board_guest_sessions.href column, not in discussion_board_guests table. Used for security auditing and session tracking.
     */
    href: string & tags.Format<"uri">;

    /**
     * Referrer URL that led to this guest session. Used for session tracking and audit purposes.
     *
     * @x-autobe-specification Session context captured from HTTP request during guest session creation. Stored in discussion_board_guest_sessions.referrer column, not in discussion_board_guests table. Used for security auditing and session tracking.
     */
    referrer: string & tags.Format<"uri">;

    /**
     * Client IP address in IPv4 format. Optional for SSR cases where IP may not be available. Used for security auditing.
     *
     * @x-autobe-specification Session context captured from HTTP request during guest session creation. Stored in discussion_board_guest_sessions.ip column, not in discussion_board_guests table. Optional for SSR cases where client IP may not be available (server captures as fallback). Used for security auditing.
     */
    ip?: (string & tags.Format<"ipv4">) | undefined;
  };

  /**
   * Request body for refreshing guest session tokens. Contains the current refresh token that will be validated and rotated to generate new access and refresh tokens for continued guest browsing access without re-authentication.
   */
  export type IRefresh = {
    /**
     * The current refresh token to validate and rotate for session renewal.
     *
     * @x-autobe-specification JWT refresh token extracted from client request body. Service layer validates: 1) Token format and JWT signature, 2) Expiration against discussion_board_guest_sessions.expired_at, 3) Guest account exists (discussion_board_guests.id), 4) Guest not soft-deleted (deleted_at IS NULL). On validation success: generates new access/refresh tokens, updates session expired_at, returns IDiscussionBoardGuest.IAuthorized. Invalid token format returns 400, expired/deleted returns 401.
     */
    refresh: string;
  };

  /**
   * Guest authorization response containing the guest identifier and JWT tokens for authenticated session access. This response is returned after successful guest session creation through the join operation or token renewal through the refresh operation. The guest identifier uniquely identifies the guest account created or retrieved based on device fingerprint. The token object contains JWT credentials needed for subsequent authenticated requests to the discussion board API.
   */
  export type IAuthorized = {
    /**
     * Unique identifier for the guest account.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from discussion_board_guests.id. UUID primary key.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Unique device fingerprint identifying the guest across sessions for anonymous identification.
     *
     * @x-autobe-database-schema-property device_fingerprint
     * @x-autobe-specification Direct mapping from discussion_board_guests.device_fingerprint. Unique constraint enforced at database level.
     */
    device_fingerprint: string;

    /**
     * Timestamp when the guest account was created.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from discussion_board_guests.created_at. Auto-generated on record creation.
     */
    created_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when the guest account was last updated.
     *
     * @x-autobe-database-schema-property updated_at
     * @x-autobe-specification Direct mapping from discussion_board_guests.updated_at. Auto-updated on record modification.
     */
    updated_at: string & tags.Format<"date-time">;

    /**
     * Timestamp when the guest account was soft deleted. Null indicates active account.
     *
     * @x-autobe-database-schema-property deleted_at
     * @x-autobe-specification Direct mapping from discussion_board_guests.deleted_at. Nullable timestamp for soft deletion. Null indicates active account.
     */
    deleted_at: (string & tags.Format<"date-time">) | null;

    /**
     * Authorization token.
     *
     * @x-autobe-specification Authorization token comes from the session table.
     */
    token: IAuthorizationToken;
  };

  /**
   * Lightweight guest account summary for session records and anonymous user identification. Provides essential guest identification including the unique device fingerprint used for session continuity across requests. Used in unified session records to represent guest actor identity.
   */
  export type ISummary = {
    /**
     * Unique guest account identifier in UUID format.
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from discussion_board_guests.id. UUID primary key.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Unique device fingerprint identifying the guest user across sessions for anonymous identification and session continuity.
     *
     * @x-autobe-database-schema-property device_fingerprint
     * @x-autobe-specification Direct mapping from discussion_board_guests.device_fingerprint. Unique identifier for session continuity.
     */
    deviceFingerprint: string;

    /**
     * Timestamp when the guest account was created.
     *
     * @x-autobe-database-schema-property created_at
     * @x-autobe-specification Direct mapping from discussion_board_guests.created_at. Timestamp with timezone.
     */
    createdAt: string & tags.Format<"date-time">;

    /**
     * Timestamp when the guest account was last updated.
     *
     * @x-autobe-database-schema-property updated_at
     * @x-autobe-specification Direct mapping from discussion_board_guests.updated_at. Timestamp with timezone.
     */
    updatedAt: string & tags.Format<"date-time">;

    /**
     * Soft deletion timestamp. Null if account is active, set if account has been deleted.
     *
     * @x-autobe-database-schema-property deleted_at
     * @x-autobe-specification Direct mapping from discussion_board_guests.deleted_at. Nullable timestamp for soft deletion.
     */
    deletedAt: (string & tags.Format<"date-time">) | null;
  };
}
