import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommercePlatformProductVariant } from "../../../../../structures/IEcommercePlatformProductVariant";

export * as options from "./options/index";
export * as inventory from "./inventory/index";
export * as snapshots from "./snapshots/index";

/**
 * Create a new product variant for an existing product with a unique SKU code, option configurations, and optional price override.
 *
 * Product variants represent specific purchasable configurations of a product, such as different color or size combinations. Each variant must have a unique SKU code within its parent product scope.
 *
 * The seller creating the variant must be the owner of the parent product. When a price is not specified, the variant inherits the product's base price. Stock quantity is automatically initialized at zero upon creation, and an inventory ledger record is created to track all future stock changes.
 *
 * Option values define the variant's characteristics (such as color, size, material) as key-value pairs. After creation, the variant is immediately available for purchase once stock is added through inventory operations.
 *
 * @param props.connection
 * @param props.productId UUID of the parent product to which this variant will be added. The product must exist, not be soft-deleted, and be owned by the authenticated seller.
 * @param props.body Variant creation data including a unique SKU code, option key-value pairs defining the variant configuration, and an optional price override that takes precedence over the product's base price.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification Implementation steps:
 *
 * 1. Validate the product exists and is not soft-deleted by querying ecommerce_platform_products with the given productId.
 * 2. Verify seller authorization: the authenticated seller's seller_profile must match the product's ecommerce_platform_seller_profile_id.
 * 3. Validate SKU uniqueness: check that no existing variant with the same sku_code exists for this product (query ecommerce_platform_product_variants where ecommerce_platform_product_id = productId AND sku_code = input.skuCode AND deleted_at IS NULL).
 * 4. Begin database transaction:
 *    a. Insert new record into ecommerce_platform_product_variants with the product_id, sku_code, and price (if provided; null means inherit product base_price).
 *    b. For each option in the input options array, insert a record into ecommerce_platform_product_variant_options with the new variant's id, attribute_key, and attribute_value.
 *    c. Create an initial inventory record in ecommerce_platform_inventory_records with quantity_change = 0 to initialize stock at zero.
 * 5. Commit transaction.
 * 6. Return the created variant with its options populated and stock_quantity = 0.
 *
 * Error handling:
 * - Return 404 if product not found or soft-deleted.
 * - Return 403 if seller is not the product owner.
 * - Return 409 if sku_code already exists for this product.
 * - Validate that options array is not empty and contains valid key-value pairs.
 * - Validate attribute_key uniqueness within the options array (no duplicate keys).
 * @path /ecommercePlatform/seller/products/:productId/variants
 * @accessor api.functional.ecommercePlatform.seller.products.variants.create
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * UUID of the parent product to which this variant will be added. The product must exist, not be soft-deleted, and be owned by the authenticated seller.
     */
    productId: string & tags.Format<"uuid">;

    /**
     * Variant creation data including a unique SKU code, option key-value pairs defining the variant configuration, and an optional price override that takes precedence over the product's base price.
     */
    body: IEcommercePlatformProductVariant.ICreate;
  };
  export type Body = IEcommercePlatformProductVariant.ICreate;
  export type Response = IEcommercePlatformProductVariant;

  export const METADATA = {
    method: "POST",
    path: "/ecommercePlatform/seller/products/:productId/variants",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/ecommercePlatform/seller/products/${encodeURIComponent(props.productId ?? "null")}/variants`;
  export const random = (): IEcommercePlatformProductVariant =>
    typia.random<IEcommercePlatformProductVariant>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update an existing product variant including SKU code, pricing, and option attributes.
 *
 * Approved sellers can modify their own product variants by updating the SKU code (must remain unique within the parent product), adjusting the variant-specific price override, and changing option key-value pairs such as color, size, or material. The variant and its parent product must exist and not be soft-deleted.
 *
 * Every update automatically generates an edit snapshot preserving the complete previous state of the variant. This snapshot records the before-state of sku_code, price, and all option attributes for audit trail and dispute resolution purposes.
 *
 * The new SKU code must not conflict with any other active variant under the same product. Option attribute keys unique to this variant must also remain unique.
 *
 * @param props.connection
 * @param props.productId UUID of the parent product that owns this variant.
 * @param props.variantId UUID of the product variant to update.
 * @param props.body Variant update payload containing optional mutable fields: SKU code, price override, and option key-value pairs.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification 1. Validate both productId and variantId are valid
 *   UUIDs. 2. Query ecommerce_platform_product_variants by id = variantId where
 *   deleted_at IS NULL. 3. Verify the variant's ecommerce_platform_product_id
 *   matches productId; return 404 if mismatch. 4. Verify the current
 *   authenticated seller owns the parent product by matching
 *   ecommerce_platform_seller_profile_id; return 403 if not. 5. If sku_code is
 *   being changed, check unique constraint: query
 *   ecommerce_platform_product_variants where ecommerce_platform_product_id =
 *   productId AND sku_code = newSkuCode AND id != variantId AND deleted_at IS
 *   NULL. Return 409 if conflict found. 6. Record current state into
 *   ecommerce_platform_snapshots and ecommerce_platform_snapshot_variants
 *   before mutation - capture sku_code, price, and all option key-value pairs
 *   from ecommerce_platform_product_variant_options. 7. Update
 *   ecommerce_platform_product_variants with the new sku_code and price values.
 *   Set updated_at to current timestamp. 8. Synchronize
 *   ecommerce_platform_product_variant_options: soft-delete (set deleted_at)
 *   options whose attribute_key is no longer present, update existing matching
 *   attribute_keys, and insert new attribute_key/attribute_value pairs as
 *   needed. 9. Return the fully updated variant entity including all active
 *   option records.
 * @path /ecommercePlatform/seller/products/:productId/variants/:variantId
 * @accessor api.functional.ecommercePlatform.seller.products.variants.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * UUID of the parent product that owns this variant.
     */
    productId: string & tags.Format<"uuid">;

    /**
     * UUID of the product variant to update.
     */
    variantId: string & tags.Format<"uuid">;

    /**
     * Variant update payload containing optional mutable fields: SKU code, price override, and option key-value pairs.
     */
    body: IEcommercePlatformProductVariant.IUpdate;
  };
  export type Body = IEcommercePlatformProductVariant.IUpdate;
  export type Response = IEcommercePlatformProductVariant;

  export const METADATA = {
    method: "PUT",
    path: "/ecommercePlatform/seller/products/:productId/variants/:variantId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/ecommercePlatform/seller/products/${encodeURIComponent(props.productId ?? "null")}/variants/${encodeURIComponent(props.variantId ?? "null")}`;
  export const random = (): IEcommercePlatformProductVariant =>
    typia.random<IEcommercePlatformProductVariant>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.param("variantId")(() => typia.assert(props.variantId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Delete a product variant with validation of blocking conditions.
 *
 * Sellers can delete their own product variants to remove them from the product listing. The soft-delete mechanism preserves variant records for order history and tracking while removing the variant from product detail pages, search results, and category listings.
 *
 * Deletion is blocked when the variant has active order items in paid or shipped status, or when pending cancellation or refund requests exist for that variant. All snapshots associated with the variant are preserved for audit and dispute resolution.
 *
 * The product itself remains active if other variants exist. Products with all variants deleted are shown as unavailable and cannot be purchased by customers.
 *
 * @param props.connection
 * @param props.productId UUID of the parent product. Identifies the product under which the variant is scoped.
 * @param props.skuCode SKU code of the variant (scoped to product). The unique identifier for the variant within its parent product.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor seller
 * @x-autobe-specification 1. Locate the product variant using the composite
 *   identifier (ecommerce_platform_product_id = productId, sku_code = skuCode).
 *
 * 2. Verify ownership: Load the parent product via ecommerce_platform_product_id and confirm the requesting seller's seller_profile_id matches ecommerce_platform_seller_profile_id on the product.
 *
 * 3. Check blocking conditions:
 *    - Query ecommerce_platform_order_items where ecommerce_platform_product_variant_id matches the variant AND status IN ('paid', 'shipped'). Block deletion if any exist.
 *    - Query ecommerce_platform_cancellation_requests via order_items related to this variant where status = 'pending'. Block deletion if any exist.
 *    - Query ecommerce_platform_refund_requests via order_items related to this variant where status = 'pending'. Block deletion if any exist.
 *
 * 4. If all checks pass, perform soft delete:
 *    - Set deleted_at = NOW() on the variant record (ecommerce_platform_product_variants).
 *    - Set deleted_at = NOW() on all child records in ecommerce_platform_product_variant_options for this variant.
 *    - Delete all records from ecommerce_platform_inventory_records for this variant (onDelete: Cascade).
 *
 * 5. Snapshots in ecommerce_platform_snapshot_variants are preserved automatically (cascaded from parent). Do not delete any snapshot records.
 *
 * 6. Return 204 No Content on success.
 *
 * 7. Return 404 if variant or product not found. Return 403 if not the owner. Return 409 (Conflict) if blocking conditions are met.
 * @path /ecommercePlatform/seller/products/:productId/variants/:skuCode
 * @accessor api.functional.ecommercePlatform.seller.products.variants.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /**
     * UUID of the parent product. Identifies the product under which the variant is scoped.
     */
    productId: string & tags.Format<"uuid">;

    /**
     * SKU code of the variant (scoped to product). The unique identifier for the variant within its parent product.
     */
    skuCode: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/ecommercePlatform/seller/products/:productId/variants/:skuCode",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommercePlatform/seller/products/${encodeURIComponent(props.productId ?? "null")}/variants/${encodeURIComponent(props.skuCode ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("productId")(() => typia.assert(props.productId));
      assert.param("skuCode")(() => typia.assert(props.skuCode));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
