import { TypedBody, TypedRoute } from "@nestia/core";
import { Controller, Ip } from "@nestjs/common";
import typia from "typia";

import { IMultiUserTodoUserProfile } from "../../../../api/structures/IMultiUserTodoUserProfile";
import { postMultiUserTodoAuthMemberJoin } from "../../../../providers/postMultiUserTodoAuthMemberJoin";
import { postMultiUserTodoAuthMemberLogin } from "../../../../providers/postMultiUserTodoAuthMemberLogin";
import { postMultiUserTodoAuthMemberRefresh } from "../../../../providers/postMultiUserTodoAuthMemberRefresh";

@Controller("/multiUserTodo/auth/member")
export class MultiusertodoAuthMemberController {
  /**
   * Register a new member account and return JWT authorization tokens.
   *
   * This endpoint accepts an IMultiUserTodoMember.IJoin request body and creates the member identity used for subsequent authenticated workflows.
   *
   * Implementation details: validate the DTO payload, persist credentials securely (password hashing), then issue access/refresh tokens returned as IMultiUserTodoMember.IAuthorized.
   *
   * Security considerations: do not include password or sensitive secrets in responses; return generic 4xx messages for invalid or conflicting registration attempts.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Member registration payload as defined by IMultiUserTodoMember.IJoin.
     * @x-autobe-authorization-type join
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Implement member registration endpoint.
   *
   * - Accept request body matching IMultiUserTodoMember.IJoin.
   * - Validate payload according to the DTO constraints.
   * - Create the member account and persist password securely (hashing per service conventions).
   * - Mint JWT access/refresh tokens and return them in IMultiUserTodoMember.IAuthorized.
   * - Error handling: return 4xx for validation/uniqueness violations; return 5xx for unexpected failures. Avoid exposing sensitive details.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("join")
  public async join(
    @Ip()
    ip: string,
    @TypedBody()
    body: IMultiUserTodoUserProfile.IJoin,
  ): Promise<IMultiUserTodoUserProfile.IAuthorized> {
    try {
      return await postMultiUserTodoAuthMemberJoin({
        ip,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Authenticate a member using credentials and return JWT authorization tokens.
   *
   * This endpoint accepts an IMultiUserTodoMember.ILogin request body and returns IMultiUserTodoMember.IAuthorized on successful authentication.
   *
   * Implementation details: validate input, verify stored credentials, then issue new access/refresh tokens.
   *
   * Security considerations: use constant-time password verification where applicable and return consistent 401 responses for invalid credentials to reduce account-enumeration risk.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Member login credentials as defined by IMultiUserTodoMember.ILogin.
     * @x-autobe-authorization-type login
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Implement member login endpoint.
   *
   * - Accept request body matching IMultiUserTodoMember.ILogin.
   * - Validate DTO payload.
   * - Look up the member identity as defined by DTO fields (e.g., email/username) and verify the provided password.
   * - On success, mint JWT access/refresh tokens and return them in IMultiUserTodoMember.IAuthorized.
   * - Error handling: return 400 for malformed requests; return 401 for invalid credentials without confirming whether the account exists; return 5xx for unexpected failures.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("login")
  public async login(
    @Ip()
    ip: string,
    @TypedBody()
    body: IMultiUserTodoUserProfile.ILogin,
  ): Promise<IMultiUserTodoUserProfile.IAuthorized> {
    try {
      return await postMultiUserTodoAuthMemberLogin({
        ip,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Refresh a member session by exchanging a refresh token for new JWT authorization tokens.
   *
   * This endpoint accepts an IMultiUserTodoMember.IRefresh request body and returns IMultiUserTodoMember.IAuthorized containing newly issued tokens.
   *
   * Implementation details: validate input, verify refresh token integrity and expiry, then issue token pair (access/refresh) per the DTO contract.
   *
   * Security considerations: do not accept access tokens as refresh tokens unless explicitly defined by IMultiUserTodoMember.IRefresh; return generic 401 for invalid/expired refresh tokens.
   *
   * @setHeader token.access Authorization
   *
   * @param connection
   * @param body Member refresh payload as defined by IMultiUserTodoMember.IRefresh.
     * @x-autobe-authorization-type refresh
     * @x-autobe-authorization-actor member
     * @x-autobe-specification Implement member refresh endpoint.
   *
   * - Accept request body matching IMultiUserTodoMember.IRefresh.
   * - Validate DTO payload.
   * - Verify refresh token validity (signature, expiry, and any rotation/revocation rules encoded by the service).
   * - Mint new JWT access/refresh tokens and return them in IMultiUserTodoMember.IAuthorized.
   * - Error handling: return 400 for malformed requests; return 401 for invalid/expired refresh tokens; return 5xx for unexpected failures.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post("refresh")
  public async refresh(
    @TypedBody()
    body: IMultiUserTodoUserProfile.IRefresh,
  ): Promise<IMultiUserTodoUserProfile.IAuthorized> {
    try {
      return await postMultiUserTodoAuthMemberRefresh({
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
