import { TypedBody, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IDiscussionBoardAdministratorRequest } from "../../../../../api/structures/IDiscussionBoardAdministratorRequest";
import { IPageIDiscussionBoardAdministratorRequest } from "../../../../../api/structures/IPageIDiscussionBoardAdministratorRequest";
import { SuperadminAuth } from "../../../../../decorators/SuperadminAuth";
import { SuperadminPayload } from "../../../../../decorators/payload/SuperadminPayload";
import { patchDiscussionBoardSuperAdminRequestsPending } from "../../../../../providers/patchDiscussionBoardSuperAdminRequestsPending";

@Controller("/discussionBoard/superAdmin/requests/pending")
export class DiscussionboardSuperadminRequestsPendingController {
  /**
   * Retrieve a paginated list of pending administrator requests.
   *
   * This operation provides super administrators with visibility into all pending administrator privilege requests. The system shows the submitting member's display name, the request reason, and the submission timestamp.
   *
   * Only requests with status 'pending' are included in the results. Approved and rejected requests are excluded from this list to ensure administrators focus on actionable requests.
   *
   * Supports comprehensive pagination with configurable page sizes and sorting options. Request body accepts search criteria and pagination parameters.
   *
   * @param connection
   * @param body Search criteria and pagination parameters
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor superAdmin
   * @x-autobe-specification Query discussion_board_administrator_requests table where status equals 'pending'. Join with discussion_board_members to get submitter display name. Order by submitted_at descending for newest first. Apply pagination and sorting from request body. Return paginated results with configurable page size.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @SuperadminAuth()
    superAdmin: SuperadminPayload,
    @TypedBody()
    body: IDiscussionBoardAdministratorRequest.IRequest,
  ): Promise<IPageIDiscussionBoardAdministratorRequest.ISummary> {
    try {
      return await patchDiscussionBoardSuperAdminRequestsPending({
        superAdmin,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
