import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody } from "@nestia/core";
import typia from "typia";
import { patchShoppingMallCustomerProductSearchIndex } from "../../../../providers/patchShoppingMallCustomerProductSearchIndex";
import { CustomerAuth } from "../../../../decorators/CustomerAuth";
import { CustomerPayload } from "../../../../decorators/payload/CustomerPayload";

import { IPageIShoppingMallProductSearchIndex } from "../../../../api/structures/IPageIShoppingMallProductSearchIndex";
import { IShoppingMallProductSearchIndex } from "../../../../api/structures/IShoppingMallProductSearchIndex";

@Controller("/shoppingMall/customer/productSearchIndex")
export class ShoppingmallCustomerProductsearchindexController {
  /**
   * Search products and SKUs with filtering and pagination.
   *
   * Retrieve product and SKU search results from the platform using advanced
   * filtering and keyword search capabilities. This operation accesses the
   * denormalized search index containing precomputed searchable text combining
   * product and SKU data.
   *
   * Search requests include keyword, category filters, pagination parameters,
   * and sorting options to provide responsive and accurate results. The system
   * ensures low latency by leveraging PostgreSQL trigram full-text search
   * optimizations.
   *
   * Security considerations include limiting access to authenticated users and
   * preventing abuse via rate limiting.
   *
   * The response returns paginated lists of product search result summaries
   * including product and SKU codes, names, prices, and relevant attributes.
   *
   * @param connection
   * @param body Search criteria and pagination parameters for product and SKU
   *   search
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @CustomerAuth()
    customer: CustomerPayload,
    @TypedBody()
    body: IShoppingMallProductSearchIndex.IRequest,
  ): Promise<IPageIShoppingMallProductSearchIndex.ISummary> {
    try {
      return await patchShoppingMallCustomerProductSearchIndex({
        customer,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
