import { TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia from "typia";

import { IPageIEconomicBoardSectionDeletion } from "../../../../../api/structures/IPageIEconomicBoardSectionDeletion";
import { SuperadministratorAuth } from "../../../../../decorators/SuperadministratorAuth";
import { SuperadministratorPayload } from "../../../../../decorators/payload/SuperadministratorPayload";
import { getEconomicBoardSuperAdministratorAuditDeletions } from "../../../../../providers/getEconomicBoardSuperAdministratorAuditDeletions";

@Controller("/economicBoard/superAdministrator/audit/deletions")
export class EconomicboardSuperadministratorAuditDeletionsController {
  /**
   * Retrieve a paginated list of section deletion audit events.
   *
   * This endpoint provides a historical audit trail of all section deletion operations performed by administrators on the economic_board platform. Each audit record contains the section that was deleted, the administrator who performed the deletion, and the precise timestamp of the deletion event. This audit functionality ensures transparency and accountability in platform governance, allowing administrators to track when sections were removed and by whom.
   *
   * The audit records are retained even after the original sections have been deleted, providing a complete historical record of administrative actions. This feature is essential for forensic analysis, regulatory compliance, and platform integrity verification.
   *
   * The response provides pagination support to handle potentially large volumes of deletion events that may accumulate over time. Only authenticated administrators and super administrators have access to this endpoint, as specified in the platform's security model.
   *
   * Note: This endpoint returns audit records of section deletions only, not deletions of articles or comments. The system maintains separate audit trails for different types of administrative actions.
   *
   * @param connection
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor superAdministrator
   * @x-autobe-specification Query economic_board_section_deletions table to retrieve all deletion audit events.
   * Apply pagination with configurable page size (default 20, max 100).
   * Sort results by created_at descending (newest first) to show most recent deletions first.
   * Join with economic_board_administrators table to include administrator details.
   * Include total count of deletion events for pagination metadata.
   * Return structured audit records with section_id, administrator_id, and created_at fields.
   * Apply authorization check: Only users with role administrator or superAdministrator can access this endpoint.
   * Cache results for 60 seconds to improve performance for repeated requests.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get()
  public async index(
    @SuperadministratorAuth()
    superAdministrator: SuperadministratorPayload,
  ): Promise<IPageIEconomicBoardSectionDeletion> {
    try {
      return await getEconomicBoardSuperAdministratorAuditDeletions({
        superAdministrator,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
