import { tags } from "typia";

import { IHrmTrackerMember } from "./IHrmTrackerMember";
import { IHrmTrackerMemberSession } from "./IHrmTrackerMemberSession";
import { IHrmTrackerOrganization } from "./IHrmTrackerOrganization";

/**
 * Complete pending invitation details including organization context and inviter information.
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IHrmTrackerPendingInvitation = {
  /**
   * @x-autobe-database-schema-property id
   */
  id: string & tags.Format<"uuid">;
  /**
   * @x-autobe-database-schema-property organization
   */
  organization: IHrmTrackerOrganization.ISummary;
  /**
   * @x-autobe-database-schema-property invitedByMember
   */
  invited_by?: IHrmTrackerMember.ISummary | null | undefined;

  /**
   * Session context when invitation was sent. Reference to the active authentication session used for the invitation action.
   *
   * @x-autobe-specification Join from hrm_tracker_pending_invitations using invited_by_member_session_id to hrm_tracker_member_sessions. Returns IHrmTrackerMemberSession.ISummary.
   * @x-autobe-database-schema-property invitedByMemberSession
   */
  invitedByMemberSession?: IHrmTrackerMemberSession.ISummary | null | undefined;
  /**
   * @x-autobe-database-schema-property email
   */
  email: string;
  /**
   * @x-autobe-database-schema-property message
   */
  message?: string | null | undefined;
  /**
   * @x-autobe-database-schema-property role_name
   */
  role_name?: string | null | undefined;
  /**
   * @x-autobe-database-schema-property department_name
   */
  department_name?: string | null | undefined;
  /**
   * @x-autobe-database-schema-property invited_at
   */
  invited_at?: (string & tags.Format<"date-time">) | null | undefined;
  /**
   * @x-autobe-database-schema-property resolved_at
   */
  resolved_at?: (string & tags.Format<"date-time">) | null | undefined;
  /**
   * @x-autobe-database-schema-property status
   */
  status: string;
  /**
   * @x-autobe-database-schema-property token
   */
  token: string;
};
export namespace IHrmTrackerPendingInvitation {
  /**
   * Search criteria and pagination parameters for retrieving filtered and paginated pending invitations list.
   */
  export type IRequest = {
    /**
     * Filter invitations by status. Multiple statuses can be selected.
     *
     * @x-autobe-specification Filter pending invitations by invitation status. Supports multiple statuses: pending, accepted, expired, cancelled. Each status corresponds to hrm_tracker_pending_invitations.status column values.
     */
    status?: ("pending" | "accepted" | "expired" | "cancelled")[] | undefined;

    /**
     * Search invitations by email address (partial match).
     *
     * @x-autobe-specification Search invitations by email address using partial match (LIKE). Corresponds to hrm_tracker_pending_invitations.email column.
     */
    email?: string | undefined;

    /**
     * Filter invitations by invited_at date range. Supports ISO 8601 date strings.
     *
     * @x-autobe-specification Filter invitations by invited_at date range using ISO 8601 date-time strings. Corresponds to hrm_tracker_pending_invitations.invited_at column.
     */
    invited_at_range?:
      | {
          from?: (string & tags.Format<"date-time">) | undefined;
          to?: (string & tags.Format<"date-time">) | undefined;
        }
      | undefined;

    /**
     * Filter invitations by organization context.
     *
     * @x-autobe-specification Filter invitations by organization context. Must be one of the organizations the authenticated member belongs to. Maps to hrm_tracker_pending_invitations.organization_id column.
     */
    organization_id?: (string & tags.Format<"uuid">) | undefined;

    /**
     * Sort field. Supported fields: invited_at, email, status. Default: invited_at.
     *
     * @x-autobe-specification Select field to sort results. Supported fields: invited_at, email, status. Each corresponds to hrm_tracker_pending_invitations columns.
     */
    sort_by?: "invited_at" | "email" | "status" | undefined;

    /**
     * Sort order. 'asc' for ascending, 'desc' for descending. Default: desc.
     *
     * @x-autobe-specification Specify sort direction. 'asc' for ascending, 'desc' for descending. Applied to the field selected by sort_by parameter.
     */
    sort_order?: "asc" | "desc" | undefined;

    /**
     * Page number for pagination. Starts from 1. Default: 1.
     *
     * @x-autobe-specification Page number for pagination. Starts from 1. Used for offset-based pagination to navigate through large result sets.
     */
    page?: (number & tags.Type<"int32"> & tags.Minimum<1>) | undefined;

    /**
     * Number of items per page. Maximum: 100. Default: 20.
     *
     * @x-autobe-specification Number of items per page. Maximum: 100. Used for offset-based pagination to control result set size per page.
     */
    limit?:
      | (number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<100>)
      | undefined;
  };

  /**
   * Lightweight pending invitation summary for list displays, including essential details without large text fields or sensitive tokens.
   */
  export type ISummary = {
    /**
     * Unique identifier of the invitation
     *
     * @x-autobe-database-schema-property id
     * @x-autobe-specification Direct mapping from hrm_tracker_pending_invitations.id. UUID.
     */
    id: string & tags.Format<"uuid">;

    /**
     * Email address of the invited person
     *
     * @x-autobe-database-schema-property email
     * @x-autobe-specification Direct mapping from hrm_tracker_pending_invitations.email. Email of the invited person.
     */
    email: string;

    /**
     * Role name to assign to the invited employee, if any
     *
     * @x-autobe-database-schema-property role_name
     * @x-autobe-specification Direct mapping from hrm_tracker_pending_invitations.role_name. Optional role name.
     */
    role_name?: string | null | undefined;

    /**
     * Department name to assign to the invited employee, if any
     *
     * @x-autobe-database-schema-property department_name
     * @x-autobe-specification Direct mapping from hrm_tracker_pending_invitations.department_name. Optional department name.
     */
    department_name?: string | null | undefined;

    /**
     * Status of the invitation
     *
     * @x-autobe-database-schema-property status
     * @x-autobe-specification Direct mapping from hrm_tracker_pending_invitations.status. Status of the invitation.
     */
    status: "pending" | "accepted" | "expired" | "cancelled";

    /**
     * Timestamp when the invitation was sent
     *
     * @x-autobe-database-schema-property invited_at
     * @x-autobe-specification Direct mapping from hrm_tracker_pending_invitations.invited_at. Timestamp of invitation.
     */
    invited_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Timestamp when the invitation was resolved
     *
     * @x-autobe-database-schema-property resolved_at
     * @x-autobe-specification Direct mapping from hrm_tracker_pending_invitations.resolved_at. Timestamp of resolution.
     */
    resolved_at?: (string & tags.Format<"date-time">) | null | undefined;

    /**
     * Organization of the invitation
     *
     * @x-autobe-database-schema-property organization
     * @x-autobe-specification Join via organization_id. Returns IHrmTrackerOrganization.ISummary.
     */
    organization: IHrmTrackerOrganization.ISummary;
  };
}
