import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia, { tags } from "typia";
import { patchTodoListUserUsersUserIdSessions } from "../../../../../providers/patchTodoListUserUsersUserIdSessions";
import { UserAuth } from "../../../../../decorators/UserAuth";
import { UserPayload } from "../../../../../decorators/payload/UserPayload";
import { getTodoListUserUsersUserIdSessionsUserSessionId } from "../../../../../providers/getTodoListUserUsersUserIdSessionsUserSessionId";
import { deleteTodoListUserUsersUserIdSessionsUserSessionId } from "../../../../../providers/deleteTodoListUserUsersUserIdSessionsUserSessionId";

import { IPageITodoListUserSession } from "../../../../../api/structures/IPageITodoListUserSession";
import { ITodoListUserSession } from "../../../../../api/structures/ITodoListUserSession";

@Controller("/todoList/user/users/:userId/sessions")
export class TodolistUserUsersSessionsController {
  /**
   * List all sessions for a user (todo_list_user_sessions).
   *
   * Retrieve a filtered, paginated list of all session records for a specific
   * user account by privileged system access. This API is intended for audit or
   * investigation of user login activities in the todo list application.
   *
   * The session records contain metadata for each authentication session,
   * including client IP, referrer, connection URL, and lifecycle timestamps.
   * Only the system or internally authorized components are expected to use
   * this endpoint for reviewing authentication history, tracking potential
   * security issues, and managing session policy.
   *
   * Sensitive information such as password hashes are never returned, and all
   * business rules for data minimization and audit trail integrity, as
   * specified in the Prisma schema, are tightly enforced. Pagination is
   * supported for efficient navigation through large record sets. The related
   * user account is referenced by UUID in the path, and session records are
   * sorted by creation time by default.
   *
   * @param connection
   * @param userId Unique identifier (UUID) of the user whose session records
   *   are being listed.
   * @param body Search, filtering, sorting, and pagination criteria for session
   *   listing.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @UserAuth()
    user: UserPayload,
    @TypedParam("userId")
    userId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ITodoListUserSession.IRequest,
  ): Promise<IPageITodoListUserSession.ISummary> {
    try {
      return await patchTodoListUserUsersUserIdSessions({
        user,
        userId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Get details of a specific session for a user (todo_list_user_sessions).
   *
   * Retrieve full detail for a specific authentication session associated with
   * the indicated user. This API is intended for system or backend component
   * use, for security and audit review of user sessions in the todo list
   * service.
   *
   * Each session record provides contextual metadata about the authentication
   * event, including the originating IP, HTTP referrer, connection URL, and
   * full authentication lifecycle timestamps (creation and, if available,
   * expiration).
   *
   * Both the user's ID and the session's ID are required in the path. Only
   * privileged system-level logic may access this information; users cannot
   * inspect session records for themselves or others directly via API.
   * Sensitive attributes, such as credential hashes, are never returned; only
   * audit-appropriate information is exposed as defined in the Prisma schema.
   *
   * @param connection
   * @param userId Unique identifier (UUID) of the user who owns the session.
   * @param userSessionId Unique identifier (UUID) of the session to retrieve
   *   for the specified user.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":userSessionId")
  public async at(
    @UserAuth()
    user: UserPayload,
    @TypedParam("userId")
    userId: string & tags.Format<"uuid">,
    @TypedParam("userSessionId")
    userSessionId: string & tags.Format<"uuid">,
  ): Promise<ITodoListUserSession> {
    try {
      return await getTodoListUserUsersUserIdSessionsUserSessionId({
        user,
        userId,
        userSessionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete a user session record from the todo_list_user_sessions table.
   *
   * Delete a specific user session for a given user from the system.
   *
   * This operation is intended to allow users to log out of or forcibly
   * terminate sessions associated with their account, for example when logging
   * out from a device or after changing their password.
   *
   * The session record is permanently removed from the database. There is no
   * soft deletion or session recovery; this operation complies with strict
   * privacy and security rules for the Todo List application.
   *
   * The operation strictly enforces that only the owner can delete their own
   * session, ensuring there is no cross-account manipulation. Path parameters
   * userId and userSessionId are both required, and must be valid UUID format.
   * If the session does not exist or does not belong to the user, an error is
   * returned.
   *
   * Related operations include login (handled by the authentication service)
   * and session retrieval (admin auditing only, not user-facing).
   *
   * @param connection
   * @param userId Unique identifier (UUID) of the user who owns the session.
   * @param userSessionId Unique identifier (UUID) of the user session to be
   *   deleted.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":userSessionId")
  public async erase(
    @UserAuth()
    user: UserPayload,
    @TypedParam("userId")
    userId: string & tags.Format<"uuid">,
    @TypedParam("userSessionId")
    userSessionId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await deleteTodoListUserUsersUserIdSessionsUserSessionId({
        user,
        userId,
        userSessionId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
