import { TypedBody, TypedParam, TypedRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import typia, { tags } from "typia";

import { ICommunityPlatformPostVote } from "../../../../../api/structures/ICommunityPlatformPostVote";
import { MemberAuth } from "../../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../../decorators/payload/MemberPayload";
import { getCommunityPlatformMemberPostsPostIdVotesVoteId } from "../../../../../providers/getCommunityPlatformMemberPostsPostIdVotesVoteId";
import { patchCommunityPlatformMemberPostsPostIdVotes } from "../../../../../providers/patchCommunityPlatformMemberPostsPostIdVotes";
import { postCommunityPlatformMemberPostsPostIdVotes } from "../../../../../providers/postCommunityPlatformMemberPostsPostIdVotes";
import { putCommunityPlatformMemberPostsPostIdVotesVoteId } from "../../../../../providers/putCommunityPlatformMemberPostsPostIdVotesVoteId";

@Controller("/communityPlatform/member/posts/:postId/votes")
export class CommunityplatformMemberPostsVotesController {
  /**
   * Create or update a vote on a post.
   *
   * This operation allows authenticated members to express approval (upvote) or disapproval (downvote) on posts within communities they are subscribed to. Each member can cast only one vote per post, and subsequent calls to this endpoint will update the existing vote type rather than creating duplicate votes. Vote changes trigger real-time updates to both the post's visible score and the post author's karma score.
   *
   * Authentication is required via member session token. The requesting member must be subscribed to the community where the post resides, ensuring that only community participants can influence content ranking through voting. If the member is not subscribed to the community, the operation will be rejected with a 403 Forbidden error.
   *
   * Vote creation follows the business rules defined in the community_platform_post_votes table schema, which enforces a unique constraint on the combination of member_id and post_id. When a vote is successfully created or updated, the system immediately recalculates the post author's karma score based on the vote type difference.
   *
   * The response includes the complete vote record with all fields from the community_platform_post_votes table, allowing clients to verify the vote state and track any changes. Clients should handle idempotent behavior when the same vote type is submitted multiple times.
   *
   * This operation is fundamental to the platform's engagement system, enabling community members to signal content quality and influence content visibility through ranking algorithms.
   *
   * @param connection
   * @param postId ID of the post to vote on (UUID format)
   * @param body Vote type selection for the post
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Create or update a vote on a post.
   *
   * 1. Authentication: Require authenticated member session via bearer token.
   * 2. Validation:
   *    - Verify post exists and is not deleted
   *    - Verify member is subscribed to the post's community (community_platform_subscriptions.active = true)
   *    - Validate vote type is either 'upvote' or 'downvote'
   * 3. Business Logic:
   *    - Check for existing vote by member on post (community_platform_post_votes where member_id = current member and post_id = postId)
   *    - If exists and vote type differs:
   *      - Update existing vote type
   *      - Adjust karma: subtract old vote impact (+1/-1), add new vote impact
   *      - Update updated_at timestamp
   *    - If exists and vote type matches: return existing vote (idempotent)
   *    - If exists and new type null: soft delete vote (set deleted_at)
   *    - If not exists: create new vote with type
   *    - Update post author's karma score: +1 for upvote, -1 for downvote
   * 4. Database Operations:
   *    - Transaction: vote upsert + karma update
   *    - Use ON CONFLICT clause on (member_id, post_id) unique constraint
   *    - Insert/update community_platform_post_votes
   *    - Update community_platform_karmas.score where member_id = post.author_id
   * 5. Return created/updated vote with all fields.
   *
   * Error Handling:
   * - 404 if post not found or deleted
   * - 403 if member not subscribed to community
   * - 400 if vote type invalid
   * - 409 if constraint violation (handled by DB)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("postId")
    postId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ICommunityPlatformPostVote.ICreate,
  ): Promise<ICommunityPlatformPostVote> {
    try {
      return await postCommunityPlatformMemberPostsPostIdVotes({
        member,
        postId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update the authenticated member's vote on a specific post, with support for upvote, downvote, or vote removal.
   *
   * This operation allows members to express approval or disapproval of posts through voting. Members can cast upvotes to increase post scores and author karma, downvotes to decrease them, or remove existing votes. Each member can have only one vote per post, with the latest vote operation overwriting any previous vote. Vote changes trigger real-time updates to both the post's displayed vote score and the post author's karma score.
   *
   * The operation enforces business rules including single vote per user per post, real-time karma adjustments on vote changes, and vote type validation. When a vote is changed from upvote to downvote, the author's karma decreases by two points (removing +1 from upvote, applying -1 from downvote). When a vote is removed, karma adjusts accordingly based on the removed vote type (+1 for upvote removal, -1 for downvote removal).
   *
   * This API integrates with the community_platform_post_votes database table which tracks member votes on posts with upvote/downvote types. The operation requires authentication as a member with valid session token to authorize vote actions.
   *
   * Related operations include retrieving post details (GET /posts/{postId}) to see updated vote scores and viewing member profiles (GET /members/{memberId}) to see karma impacts. The operation ensures data consistency through transaction boundaries while maintaining real-time karma calculation requirements.
   *
   * @param connection
   * @param postId Identifier of the post to vote on
   * @param body Vote operation parameters specifying upvote, downvote, or vote removal
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Implement vote creation, update, or removal for a member on a specific post.
   *
   * 1. Authentication: Require valid member session token. Extract memberId from session.
   * 2. Validation: Verify post exists and is not deleted. Member must be authenticated (not guest).
   * 3. Request body parsing: Accept ICommunityPlatformPostVote.IUpdate with optional 'type' field ("up", "down", or null). Null indicates vote removal (soft delete).
   * 4. Database operations:
   *    - Check existing vote in community_platform_post_votes table using unique constraint on (member_id, post_id).
   *    - If vote exists and new type same as existing: no change needed.
   *    - If vote exists and new type differs: update 'type' field and 'updated_at'.
   *    - If vote exists and new type is null: set 'deleted_at' to current timestamp (soft delete).
   *    - If no vote exists and new type provided: insert new record with 'type', 'member_id', 'post_id'.
   *    - If no vote exists and new type is null: return error (cannot remove non-existent vote).
   * 5. Karma adjustments: Calculate karma impact:
   *    - Upvote: +1 to post author's karma
   *    - Downvote: -1 to post author's karma
   *    - Vote removal: reverse previous vote's karma impact
   *    - Vote change: apply combined adjustment (e.g., up→down: -2 total)
   *    - Update community_platform_karmas table accordingly, ensuring atomic operation.
   * 6. Post score update: Recalculate post vote score = count(upvotes) - count(downvotes) where deleted_at is null.
   *    - Update post display score or materialized view.
   * 7. Response: Return updated vote status including type, timestamps, and potentially new post score.
   * 8. Error handling: Handle cases where member is banned from community, post is deleted, or database constraints violated.
   * 9. Transaction: Wrap vote update, karma adjustment, and post score update in a single transaction for consistency.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async patchByPostid(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("postId")
    postId: string,
    @TypedBody()
    body: ICommunityPlatformPostVote.IUpdate,
  ): Promise<ICommunityPlatformPostVote> {
    try {
      return await patchCommunityPlatformMemberPostsPostIdVotes({
        member,
        postId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve detailed information about a specific vote on a post.
   *
   * This operation allows members to view their vote status on a particular post, including the vote type (upvote/downvote/null for removed), timestamps, and relationship information. Members can use this endpoint to check their current vote before deciding to change or remove it.
   *
   * The vote type field indicates the current voting status: 'up' for upvote (+1 to post score), 'down' for downvote (-1 to post score), or null for removed vote. Votes influence both the post's visibility score and the post author's karma score in real-time calculations.
   *
   * Authorization is required to access this endpoint, and members can only view their own votes unless they have moderator permissions for the post's community. Soft-deleted votes are typically not accessible through this endpoint.
   *
   * Related operations include PATCH /posts/{postId}/votes for creating/changing votes and DELETE /posts/{postId}/votes for removing votes.
   *
   * @param connection
   * @param postId The UUID identifier of the post that received the vote
   * @param voteId The UUID identifier of the vote record
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Query the community_platform_post_votes table with both postId and voteId parameters. First validate that the post exists by checking community_platform_posts table. Then retrieve the specific vote record. Ensure the authenticated member has permission to view this vote (members can only view their own votes). Authorization: Only the member who cast the vote can retrieve it, or community moderators/owners may need access for moderation purposes. Return 404 if vote not found or if the vote doesn't belong to the specified post. Include all vote fields: id, type, member_id, post_id, created_at, updated_at, deleted_at. Soft-deleted votes should return 404 unless the member has moderator permissions. Join with member and post tables for relationship validation.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":voteId")
  public async at(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("postId")
    postId: string & tags.Format<"uuid">,
    @TypedParam("voteId")
    voteId: string & tags.Format<"uuid">,
  ): Promise<ICommunityPlatformPostVote> {
    try {
      return await getCommunityPlatformMemberPostsPostIdVotesVoteId({
        member,
        postId,
        voteId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update an existing vote cast on a post.
   *
   * This operation allows members to change their vote on a post from upvote to downvote or vice versa, or to remove their vote entirely. The vote must belong to the authenticated member making the request.
   *
   * When a vote is updated, the system recalculates the post's vote score in real-time and adjusts the post author's karma score accordingly. If the vote type is changed from upvote to downvote, the post author's karma decreases by 2 points (losing +1 from upvote and gaining -1 from downvote). If changed from downvote to upvote, karma increases by 2 points. If the vote is removed (type set to null), the post author's karma is adjusted by removing the previous vote's contribution.
   *
   * Only the vote type field can be updated through this operation. The member_id and post_id fields remain immutable. Attempting to update a vote that does not exist or belongs to another member will result in a 404 Not Found error.
   *
   * Successful vote updates trigger immediate recalculation of both the post's visible vote score and the post author's karma score displayed on their profile.
   *
   * @param connection
   * @param postId UUID of the post being voted on
   * @param voteId UUID of the vote record to update
   * @param body New vote type information
   * @x-autobe-authorization-type null
   * @x-autobe-authorization-actor member
   * @x-autobe-specification Update an existing vote on a post. Validate that the authenticated user owns the vote being updated. Validate that the new vote type is either 'upvote' or 'downvote' (or null to remove vote). Update the vote record's type field and set updated_at timestamp. If vote type is null, treat as vote removal (soft delete). Ensure real-time karma calculation updates the post author's karma score based on vote change. Return the updated vote record with all current fields.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":voteId")
  public async putByPostidAndVoteid(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("postId")
    postId: string & tags.Format<"uuid">,
    @TypedParam("voteId")
    voteId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ICommunityPlatformPostVote.IUpdate,
  ): Promise<ICommunityPlatformPostVote> {
    try {
      return await putCommunityPlatformMemberPostsPostIdVotesVoteId({
        member,
        postId,
        voteId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
