import { Module } from "@nestjs/common";

import { AuthGuestController } from "./controllers/auth/guest/AuthGuestController";
import { AuthCustomerController } from "./controllers/auth/customer/AuthCustomerController";
import { AuthSellerController } from "./controllers/auth/seller/AuthSellerController";
import { AuthAdminController } from "./controllers/auth/admin/AuthAdminController";
import { ShoppingmallAdminShoppingmallsystemconfigurationsController } from "./controllers/shoppingMall/admin/shoppingMallSystemConfigurations/ShoppingmallAdminShoppingmallsystemconfigurationsController";
import { ShoppingmallShoppingmallcategoriesController } from "./controllers/shoppingMall/shoppingMallCategories/ShoppingmallShoppingmallcategoriesController";
import { ShoppingmallCustomerShoppingmallcategoriesController } from "./controllers/shoppingMall/customer/shoppingMallCategories/ShoppingmallCustomerShoppingmallcategoriesController";
import { ShoppingmallAdminShoppingmallcategoriesController } from "./controllers/shoppingMall/admin/shoppingMallCategories/ShoppingmallAdminShoppingmallcategoriesController";
import { ShoppingmallCustomerShoppingmallcategoriesShoppingmallcategoryhierarchiesController } from "./controllers/shoppingMall/customer/shoppingMallCategories/shoppingMallCategoryHierarchies/ShoppingmallCustomerShoppingmallcategoriesShoppingmallcategoryhierarchiesController";
import { ShoppingmallAdminShoppingmallcategoriesShoppingmallcategoryhierarchiesController } from "./controllers/shoppingMall/admin/shoppingMallCategories/shoppingMallCategoryHierarchies/ShoppingmallAdminShoppingmallcategoriesShoppingmallcategoryhierarchiesController";
import { ShoppingmallShoppingmallguestsController } from "./controllers/shoppingMall/shoppingMallGuests/ShoppingmallShoppingmallguestsController";
import { ShoppingmallGuestShoppingmallguestsController } from "./controllers/shoppingMall/guest/shoppingMallGuests/ShoppingmallGuestShoppingmallguestsController";
import { ShoppingmallAdminShoppingmallguestsShoppingmallguestsessionsController } from "./controllers/shoppingMall/admin/shoppingMallGuests/shoppingMallGuestSessions/ShoppingmallAdminShoppingmallguestsShoppingmallguestsessionsController";
import { ShoppingmallShoppingmallguestsShoppingmallguestsessionsController } from "./controllers/shoppingMall/shoppingMallGuests/shoppingMallGuestSessions/ShoppingmallShoppingmallguestsShoppingmallguestsessionsController";
import { ShoppingmallAdminShoppingmallcustomersController } from "./controllers/shoppingMall/admin/shoppingMallCustomers/ShoppingmallAdminShoppingmallcustomersController";
import { ShoppingmallCustomerShoppingmallcustomersController } from "./controllers/shoppingMall/customer/shoppingMallCustomers/ShoppingmallCustomerShoppingmallcustomersController";
import { ShoppingmallAdminShoppingmallcustomersShoppingmallcustomersessionsController } from "./controllers/shoppingMall/admin/shoppingMallCustomers/shoppingMallCustomerSessions/ShoppingmallAdminShoppingmallcustomersShoppingmallcustomersessionsController";
import { ShoppingmallCustomerShoppingmallcustomersShoppingmallcustomersessionsController } from "./controllers/shoppingMall/customer/shoppingMallCustomers/shoppingMallCustomerSessions/ShoppingmallCustomerShoppingmallcustomersShoppingmallcustomersessionsController";
import { ShoppingmallAdminShoppingmallsellersController } from "./controllers/shoppingMall/admin/shoppingMallSellers/ShoppingmallAdminShoppingmallsellersController";
import { ShoppingmallSellerShoppingmallsellersController } from "./controllers/shoppingMall/seller/shoppingMallSellers/ShoppingmallSellerShoppingmallsellersController";
import { ShoppingmallSellerShoppingmallsellersShoppingmallsellersessionsController } from "./controllers/shoppingMall/seller/shoppingMallSellers/shoppingMallSellerSessions/ShoppingmallSellerShoppingmallsellersShoppingmallsellersessionsController";
import { ShoppingmallAdminShoppingmalladminsController } from "./controllers/shoppingMall/admin/shoppingMallAdmins/ShoppingmallAdminShoppingmalladminsController";
import { ShoppingmallAdminShoppingmalladminsShoppingmalladminsessionsController } from "./controllers/shoppingMall/admin/shoppingMallAdmins/shoppingMallAdminSessions/ShoppingmallAdminShoppingmalladminsShoppingmalladminsessionsController";
import { ShoppingmallShoppingmallproductsController } from "./controllers/shoppingMall/shoppingMallProducts/ShoppingmallShoppingmallproductsController";
import { ShoppingmallSellerShoppingmallproductsController } from "./controllers/shoppingMall/seller/shoppingMallProducts/ShoppingmallSellerShoppingmallproductsController";
import { ShoppingmallAdminShoppingmallproductsController } from "./controllers/shoppingMall/admin/shoppingMallProducts/ShoppingmallAdminShoppingmallproductsController";
import { ShoppingmallCustomerShoppingmallproductsShoppingmallproductvariantsController } from "./controllers/shoppingMall/customer/shoppingMallProducts/shoppingMallProductVariants/ShoppingmallCustomerShoppingmallproductsShoppingmallproductvariantsController";
import { ShoppingmallSellerShoppingmallproductsShoppingmallproductvariantsController } from "./controllers/shoppingMall/seller/shoppingMallProducts/shoppingMallProductVariants/ShoppingmallSellerShoppingmallproductsShoppingmallproductvariantsController";
import { ShoppingmallAdminShoppingmallproductsShoppingmallproductvariantsController } from "./controllers/shoppingMall/admin/shoppingMallProducts/shoppingMallProductVariants/ShoppingmallAdminShoppingmallproductsShoppingmallproductvariantsController";
import { ShoppingmallAdminShoppingmallproductvariantsShoppingmallinventoriesController } from "./controllers/shoppingMall/admin/shoppingMallProductVariants/shoppingMallInventories/ShoppingmallAdminShoppingmallproductvariantsShoppingmallinventoriesController";
import { ShoppingmallSellerShoppingmallproductvariantsShoppingmallinventoriesController } from "./controllers/shoppingMall/seller/shoppingMallProductVariants/shoppingMallInventories/ShoppingmallSellerShoppingmallproductvariantsShoppingmallinventoriesController";
import { ShoppingmallShoppingmallproductvariantsShoppingmallinventoriesController } from "./controllers/shoppingMall/shoppingMallProductVariants/shoppingMallInventories/ShoppingmallShoppingmallproductvariantsShoppingmallinventoriesController";
import { ShoppingmallCustomerShoppingmallproductvariantsShoppingmallinventoriesController } from "./controllers/shoppingMall/customer/shoppingMallProductVariants/shoppingMallInventories/ShoppingmallCustomerShoppingmallproductvariantsShoppingmallinventoriesController";
import { ShoppingmallAdminShoppingmallproductsSnapshotsController } from "./controllers/shoppingMall/admin/shoppingMallProducts/snapshots/ShoppingmallAdminShoppingmallproductsSnapshotsController";
import { ShoppingmallCustomerShoppingmallcartsController } from "./controllers/shoppingMall/customer/shoppingMallCarts/ShoppingmallCustomerShoppingmallcartsController";
import { ShoppingmallCustomerShoppingmallcartsShoppingmallcartitemsController } from "./controllers/shoppingMall/customer/shoppingMallCarts/shoppingMallCartItems/ShoppingmallCustomerShoppingmallcartsShoppingmallcartitemsController";
import { ShoppingmallCustomerShoppingmallwishlistsController } from "./controllers/shoppingMall/customer/shoppingMallWishlists/ShoppingmallCustomerShoppingmallwishlistsController";
import { ShoppingmallCustomerShoppingmallwishlistsShoppingmallwishlistitemsController } from "./controllers/shoppingMall/customer/shoppingMallWishlists/shoppingMallWishlistItems/ShoppingmallCustomerShoppingmallwishlistsShoppingmallwishlistitemsController";
import { ShoppingmallCustomerOrdersController } from "./controllers/shoppingMall/customer/orders/ShoppingmallCustomerOrdersController";
import { ShoppingmallAdminOrdersController } from "./controllers/shoppingMall/admin/orders/ShoppingmallAdminOrdersController";
import { ShoppingmallAdminOrdersOrderitemsController } from "./controllers/shoppingMall/admin/orders/orderItems/ShoppingmallAdminOrdersOrderitemsController";
import { ShoppingmallCustomerOrdersOrderitemsController } from "./controllers/shoppingMall/customer/orders/orderItems/ShoppingmallCustomerOrdersOrderitemsController";
import { ShoppingmallAdminPaymentsController } from "./controllers/shoppingMall/admin/payments/ShoppingmallAdminPaymentsController";
import { ShoppingmallSellerPaymentsController } from "./controllers/shoppingMall/seller/payments/ShoppingmallSellerPaymentsController";
import { ShoppingmallCustomerShipmentsController } from "./controllers/shoppingMall/customer/shipments/ShoppingmallCustomerShipmentsController";
import { ShoppingmallSellerShipmentsController } from "./controllers/shoppingMall/seller/shipments/ShoppingmallSellerShipmentsController";
import { ShoppingmallAdminShipmentsController } from "./controllers/shoppingMall/admin/shipments/ShoppingmallAdminShipmentsController";
import { ShoppingmallAdminOrdercancellationsController } from "./controllers/shoppingMall/admin/orderCancellations/ShoppingmallAdminOrdercancellationsController";
import { ShoppingmallCustomerOrdercancellationsController } from "./controllers/shoppingMall/customer/orderCancellations/ShoppingmallCustomerOrdercancellationsController";
import { ShoppingmallCustomerRefundrequestsController } from "./controllers/shoppingMall/customer/refundRequests/ShoppingmallCustomerRefundrequestsController";
import { ShoppingmallAdminRefundrequestsController } from "./controllers/shoppingMall/admin/refundRequests/ShoppingmallAdminRefundrequestsController";
import { ShoppingmallSellerRefundrequestsController } from "./controllers/shoppingMall/seller/refundRequests/ShoppingmallSellerRefundrequestsController";
import { ShoppingmallCustomerCouponsController } from "./controllers/shoppingMall/customer/coupons/ShoppingmallCustomerCouponsController";
import { ShoppingmallAdminCouponsController } from "./controllers/shoppingMall/admin/coupons/ShoppingmallAdminCouponsController";
import { ShoppingmallAdminCouponusagesController } from "./controllers/shoppingMall/admin/couponUsages/ShoppingmallAdminCouponusagesController";
import { ShoppingmallCustomerMileagesController } from "./controllers/shoppingMall/customer/mileages/ShoppingmallCustomerMileagesController";
import { ShoppingmallAdminMileagesController } from "./controllers/shoppingMall/admin/mileages/ShoppingmallAdminMileagesController";
import { ShoppingmallAdminPointsController } from "./controllers/shoppingMall/admin/points/ShoppingmallAdminPointsController";
import { ShoppingmallCustomerPointsController } from "./controllers/shoppingMall/customer/points/ShoppingmallCustomerPointsController";
import { ShoppingmallShoppingmallproductreviewsController } from "./controllers/shoppingMall/shoppingMallProductReviews/ShoppingmallShoppingmallproductreviewsController";
import { ShoppingmallCustomerShoppingmallproductreviewsController } from "./controllers/shoppingMall/customer/shoppingMallProductReviews/ShoppingmallCustomerShoppingmallproductreviewsController";
import { ShoppingmallAdminShoppingmallproductreviewsController } from "./controllers/shoppingMall/admin/shoppingMallProductReviews/ShoppingmallAdminShoppingmallproductreviewsController";
import { ShoppingmallAdminShoppingmallproductreviewsShoppingmallreviewmoderationsController } from "./controllers/shoppingMall/admin/shoppingMallProductReviews/shoppingMallReviewModerations/ShoppingmallAdminShoppingmallproductreviewsShoppingmallreviewmoderationsController";
import { ShoppingmallAdminShoppingmallcustomerquestionsController } from "./controllers/shoppingMall/admin/shoppingMallCustomerQuestions/ShoppingmallAdminShoppingmallcustomerquestionsController";
import { ShoppingmallCustomerShoppingmallcustomerquestionsController } from "./controllers/shoppingMall/customer/shoppingMallCustomerQuestions/ShoppingmallCustomerShoppingmallcustomerquestionsController";
import { ShoppingmallCustomerShoppingmallcustomerquestionsShoppingmallquestionanswersController } from "./controllers/shoppingMall/customer/shoppingMallCustomerQuestions/shoppingMallQuestionAnswers/ShoppingmallCustomerShoppingmallcustomerquestionsShoppingmallquestionanswersController";
import { ShoppingmallSellerShoppingmallcustomerquestionsShoppingmallquestionanswersController } from "./controllers/shoppingMall/seller/shoppingMallCustomerQuestions/shoppingMallQuestionAnswers/ShoppingmallSellerShoppingmallcustomerquestionsShoppingmallquestionanswersController";
import { ShoppingmallCustomerShoppingmallsupportticketsController } from "./controllers/shoppingMall/customer/shoppingMallSupportTickets/ShoppingmallCustomerShoppingmallsupportticketsController";
import { ShoppingmallSellerShoppingmallsupportticketsController } from "./controllers/shoppingMall/seller/shoppingMallSupportTickets/ShoppingmallSellerShoppingmallsupportticketsController";
import { ShoppingmallAdminShoppingmallsupportticketsController } from "./controllers/shoppingMall/admin/shoppingMallSupportTickets/ShoppingmallAdminShoppingmallsupportticketsController";
import { ShoppingmallAdminShoppingmallrolesController } from "./controllers/shoppingMall/admin/shoppingMallRoles/ShoppingmallAdminShoppingmallrolesController";
import { ShoppingmallAdminShoppingmalluserrolesController } from "./controllers/shoppingMall/admin/shoppingMallUserRoles/ShoppingmallAdminShoppingmalluserrolesController";
import { ShoppingmallAdminShoppingmallpermissionsController } from "./controllers/shoppingMall/admin/shoppingMallPermissions/ShoppingmallAdminShoppingmallpermissionsController";
import { ShoppingmallAdminShoppingmalladminauditlogsController } from "./controllers/shoppingMall/admin/shoppingMallAdminAuditLogs/ShoppingmallAdminShoppingmalladminauditlogsController";
import { ShoppingmallMvshoppingmalldailysalesController } from "./controllers/shoppingMall/mvShoppingMallDailySales/ShoppingmallMvshoppingmalldailysalesController";
import { ShoppingmallMvshoppingmallinventorystatusController } from "./controllers/shoppingMall/mvShoppingMallInventoryStatus/ShoppingmallMvshoppingmallinventorystatusController";

@Module({
  controllers: [
    AuthGuestController,
    AuthCustomerController,
    AuthSellerController,
    AuthAdminController,
    ShoppingmallAdminShoppingmallsystemconfigurationsController,
    ShoppingmallShoppingmallcategoriesController,
    ShoppingmallCustomerShoppingmallcategoriesController,
    ShoppingmallAdminShoppingmallcategoriesController,
    ShoppingmallCustomerShoppingmallcategoriesShoppingmallcategoryhierarchiesController,
    ShoppingmallAdminShoppingmallcategoriesShoppingmallcategoryhierarchiesController,
    ShoppingmallShoppingmallguestsController,
    ShoppingmallGuestShoppingmallguestsController,
    ShoppingmallAdminShoppingmallguestsShoppingmallguestsessionsController,
    ShoppingmallShoppingmallguestsShoppingmallguestsessionsController,
    ShoppingmallAdminShoppingmallcustomersController,
    ShoppingmallCustomerShoppingmallcustomersController,
    ShoppingmallAdminShoppingmallcustomersShoppingmallcustomersessionsController,
    ShoppingmallCustomerShoppingmallcustomersShoppingmallcustomersessionsController,
    ShoppingmallAdminShoppingmallsellersController,
    ShoppingmallSellerShoppingmallsellersController,
    ShoppingmallSellerShoppingmallsellersShoppingmallsellersessionsController,
    ShoppingmallAdminShoppingmalladminsController,
    ShoppingmallAdminShoppingmalladminsShoppingmalladminsessionsController,
    ShoppingmallShoppingmallproductsController,
    ShoppingmallSellerShoppingmallproductsController,
    ShoppingmallAdminShoppingmallproductsController,
    ShoppingmallCustomerShoppingmallproductsShoppingmallproductvariantsController,
    ShoppingmallSellerShoppingmallproductsShoppingmallproductvariantsController,
    ShoppingmallAdminShoppingmallproductsShoppingmallproductvariantsController,
    ShoppingmallAdminShoppingmallproductvariantsShoppingmallinventoriesController,
    ShoppingmallSellerShoppingmallproductvariantsShoppingmallinventoriesController,
    ShoppingmallShoppingmallproductvariantsShoppingmallinventoriesController,
    ShoppingmallCustomerShoppingmallproductvariantsShoppingmallinventoriesController,
    ShoppingmallAdminShoppingmallproductsSnapshotsController,
    ShoppingmallCustomerShoppingmallcartsController,
    ShoppingmallCustomerShoppingmallcartsShoppingmallcartitemsController,
    ShoppingmallCustomerShoppingmallwishlistsController,
    ShoppingmallCustomerShoppingmallwishlistsShoppingmallwishlistitemsController,
    ShoppingmallCustomerOrdersController,
    ShoppingmallAdminOrdersController,
    ShoppingmallAdminOrdersOrderitemsController,
    ShoppingmallCustomerOrdersOrderitemsController,
    ShoppingmallAdminPaymentsController,
    ShoppingmallSellerPaymentsController,
    ShoppingmallCustomerShipmentsController,
    ShoppingmallSellerShipmentsController,
    ShoppingmallAdminShipmentsController,
    ShoppingmallAdminOrdercancellationsController,
    ShoppingmallCustomerOrdercancellationsController,
    ShoppingmallCustomerRefundrequestsController,
    ShoppingmallAdminRefundrequestsController,
    ShoppingmallSellerRefundrequestsController,
    ShoppingmallCustomerCouponsController,
    ShoppingmallAdminCouponsController,
    ShoppingmallAdminCouponusagesController,
    ShoppingmallCustomerMileagesController,
    ShoppingmallAdminMileagesController,
    ShoppingmallAdminPointsController,
    ShoppingmallCustomerPointsController,
    ShoppingmallShoppingmallproductreviewsController,
    ShoppingmallCustomerShoppingmallproductreviewsController,
    ShoppingmallAdminShoppingmallproductreviewsController,
    ShoppingmallAdminShoppingmallproductreviewsShoppingmallreviewmoderationsController,
    ShoppingmallAdminShoppingmallcustomerquestionsController,
    ShoppingmallCustomerShoppingmallcustomerquestionsController,
    ShoppingmallCustomerShoppingmallcustomerquestionsShoppingmallquestionanswersController,
    ShoppingmallSellerShoppingmallcustomerquestionsShoppingmallquestionanswersController,
    ShoppingmallCustomerShoppingmallsupportticketsController,
    ShoppingmallSellerShoppingmallsupportticketsController,
    ShoppingmallAdminShoppingmallsupportticketsController,
    ShoppingmallAdminShoppingmallrolesController,
    ShoppingmallAdminShoppingmalluserrolesController,
    ShoppingmallAdminShoppingmallpermissionsController,
    ShoppingmallAdminShoppingmalladminauditlogsController,
    ShoppingmallMvshoppingmalldailysalesController,
    ShoppingmallMvshoppingmallinventorystatusController,
  ],
})
export class MyModule {}
