import { HttpError, IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";

import { IDiscussionBoardContentModerationLog } from "../../../../structures/IDiscussionBoardContentModerationLog";
import { IPageIDiscussionBoardContentModerationLog } from "../../../../structures/IPageIDiscussionBoardContentModerationLog";

/**
 * Retrieve a filtered and paginated list of content moderation logs for administrative review and audit purposes.
 *
 * This operation provides comprehensive search capabilities for moderation activity tracking, allowing administrators to review content management actions performed across the platform. The search supports filtering by specific administrators, action types, target content types, time periods, and reason text content.
 *
 * Administrators can use this endpoint to investigate moderation patterns, track specific content management activities, and generate compliance reports. The response includes essential moderation log information with pagination support for efficient browsing of large result sets.
 *
 * This operation is essential for maintaining transparency and accountability in content moderation practices, providing administrators with the tools needed to monitor and review moderation activities across the discussion board platform.
 *
 * @param props.connection
 * @param props.body Search criteria and pagination parameters for moderation logs
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Query the discussion_board_content_moderation_logs table with advanced filtering capabilities. Support filtering by admin_id, action_type, target_content_type, date ranges (created_at), and text search in reason field. Implement pagination with configurable page sizes. Join with discussion_board_admins table to include administrator information in results. Apply text search using gin_trgm_ops index on reason field for efficient partial matching. Return results sorted by created_at descending for chronological review.
 * @path /discussionBoard/admin/content-moderation-logs
 * @accessor api.functional.discussionBoard.admin.content_moderation_logs.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search criteria and pagination parameters for moderation logs
     */
    body: IDiscussionBoardContentModerationLog.IRequest;
  };
  export type Body = IDiscussionBoardContentModerationLog.IRequest;
  export type Response = IPageIDiscussionBoardContentModerationLog.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/discussionBoard/admin/content-moderation-logs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/discussionBoard/admin/content-moderation-logs";
  export const random =
    (): IPageIDiscussionBoardContentModerationLog.ISummary =>
      typia.random<IPageIDiscussionBoardContentModerationLog.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve detailed information about a specific content moderation action logged in the system.
 *
 * This operation provides comprehensive audit trail information for individual moderation actions performed by administrators. Each log entry captures essential details including the moderator who performed the action, the type of moderation action taken, the specific content that was moderated, and the reason provided for the action.
 *
 * The response includes complete timestamp information showing when the moderation action was performed and when the log record was last updated. This audit trail serves as a critical accountability mechanism for content moderation activities on the platform.
 *
 * Administrators can use this operation to review specific moderation actions, investigate patterns of content management, and ensure compliance with moderation policies. The operation requires administrator-level access to protect sensitive moderation information from regular users.
 *
 * @param props.connection
 * @param props.logId Unique identifier of the content moderation log entry to retrieve
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor admin
 * @x-autobe-specification Retrieve a specific content moderation log entry by its unique ID. Query the discussion_board_content_moderation_logs table using the provided logId parameter. Include the related administrator information by joining with discussion_board_admins table to provide moderator details. Return the complete log entry with all fields including admin_id, action_type, target_content_type, target_content_id, reason, and timestamps. Validate that the log entry exists and return appropriate error if not found.
 * @path /discussionBoard/admin/content-moderation-logs/:logId
 * @accessor api.functional.discussionBoard.admin.content_moderation_logs.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier of the content moderation log entry to retrieve
     */
    logId: string & tags.Format<"uuid">;
  };
  export type Response = IDiscussionBoardContentModerationLog;

  export const METADATA = {
    method: "GET",
    path: "/discussionBoard/admin/content-moderation-logs/:logId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/discussionBoard/admin/content-moderation-logs/${encodeURIComponent(props.logId ?? "null")}`;
  export const random = (): IDiscussionBoardContentModerationLog =>
    typia.random<IDiscussionBoardContentModerationLog>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("logId")(() => typia.assert(props.logId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
