import {
  HttpError,
  IConnection,
  NestiaSimulator,
  PlainFetcher,
} from "@nestia/fetcher";
import typia, { tags } from "typia";

import { IEcommerceMallShipmentItem } from "../../../../structures/IEcommerceMallShipmentItem";

/**
 * Retrieve detailed information about a specific shipment item.
 *
 * Returns the complete shipment item record including its status, quantity shipped, and relationships to the parent shipment and order item. Customers can view tracking information for items in their orders. Sellers can view order items included in shipments they created. The response includes the shipment tracking details (carrier and tracking number) and the current status of the item in the shipment.
 *
 * The shipment item status reflects its current fulfillment state: pending (order placed but not shipped), shipped (in transit), delivered (customer confirmed or auto-delivered after 14 days), or cancelled (order cancelled before shipment). Status changes automatically when the parent shipment status changes.
 *
 * @param props.connection
 * @param props.shipmentItemId The unique identifier of the shipment item to retrieve.
 * @x-autobe-authorization-type null
 * @x-autobe-authorization-actor administrator
 * @x-autobe-specification Query ecommerce_mall_shipment_items table for the record matching the shipmentItemId UUID path parameter.
 *
 * Join with ecommerce_mall_shipments to include carrier and tracking_number fields.
 * Join with ecommerce_mall_order_items to include order item details (product name, variant options, quantity).
 * Join with ecommerce_mall_products via order_item to include product name and category information.
 * Join with ecommerce_mall_sellers via order_item to get seller information for the shipment.
 *
 * Access Control:
 * - If requesting customer: verify the order_item belongs to an order owned by the customer (check ecommerce_mall_orders customer_id matches authenticated user)
 * - If requesting seller: verify the order_item belongs to a product owned by the seller (check product seller_id matches authenticated user) or verify the shipment was created by the seller
 * - Return 403 Forbidden if access check fails
 *
 * Business Rules:
 * - Status must be one of: pending, shipped, delivered, cancelled
 * - quantity_shipped must be greater than 0 and cannot exceed original order quantity
 * - deleted_at must be null (active record)
 *
 * Return the complete shipment item entity with all fields. Include joined shipment data (carrier, tracking_number, status, shipped_at, delivered_at) and order item details (product name, variant options, original quantity).
 *
 * Error Handling:
 * - 404 Not Found if shipment item does not exist or has been soft deleted
 * - 403 Forbidden if requesting user lacks authorization to view this shipment item
 * @path /ecommerceMall/administrator/shipment-items/:shipmentItemId
 * @accessor api.functional.ecommerceMall.administrator.shipment_items.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * The unique identifier of the shipment item to retrieve.
     */
    shipmentItemId: string & tags.Format<"uuid">;
  };
  export type Response = IEcommerceMallShipmentItem;

  export const METADATA = {
    method: "GET",
    path: "/ecommerceMall/administrator/shipment-items/:shipmentItemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/ecommerceMall/administrator/shipment-items/${encodeURIComponent(props.shipmentItemId ?? "null")}`;
  export const random = (): IEcommerceMallShipmentItem =>
    typia.random<IEcommerceMallShipmentItem>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("shipmentItemId")(() => typia.assert(props.shipmentItemId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
