import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { IDiscussionBoardNotificationTemplate } from "../../../../../structures/IDiscussionBoardNotificationTemplate";

/**
 * Update a specific notification template for the discussion board system. This
 * operation modifies an existing notification template identified by its unique
 * templateId. The template defines the message content and structure for
 * system-generated notifications sent to users. Any changes to a template
 * affect all future notifications that use this template.
 *
 * The operation targets the discussion_board_notification_templates table in
 * the database schema, specifically updating the name, title, content, and
 * is_active fields. The templateId parameter corresponds to the unique
 * identifier field in this table. When updating a template, the system
 * validates that the new content is properly formatted, within character
 * limits, and does not contain invalid placeholders.
 *
 * Security considerations ensure that only authenticated users can update
 * notification templates, with additional access controls potentially applied
 * based on user roles. The update must preserve the template's existing
 * metadata such as creation time and version, only modifying the content
 * fields. The updated_at timestamp is automatically managed by the system.
 *
 * This operation is idempotent, meaning multiple identical requests will have
 * the same effect as a single request. Template updates are logged for audit
 * purposes to track changes over time.
 *
 * @param props.connection
 * @param props.templateId Unique identifier of the notification template to
 *   update (global scope)
 * @param props.body Updated content and configuration for the notification
 *   template
 * @path /discussionBoard/citizen/notifications/templates/:templateId
 * @accessor api.functional.discussionBoard.citizen.notifications.templates.update
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Unique identifier of the notification template to update (global
     * scope)
     */
    templateId: string;

    /** Updated content and configuration for the notification template */
    body: IDiscussionBoardNotificationTemplate.IUpdate;
  };
  export type Body = IDiscussionBoardNotificationTemplate.IUpdate;
  export type Response = IDiscussionBoardNotificationTemplate;

  export const METADATA = {
    method: "PUT",
    path: "/discussionBoard/citizen/notifications/templates/:templateId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/discussionBoard/citizen/notifications/templates/${encodeURIComponent(props.templateId ?? "null")}`;
  export const random = (): IDiscussionBoardNotificationTemplate =>
    typia.random<IDiscussionBoardNotificationTemplate>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("templateId")(() => typia.assert(props.templateId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Permanently delete a specific notification template from the system.
 *
 * This operation removes a notification template from the
 * discussion_board_notification_templates table in the database. The template
 * can be deleted by any authenticated citizen user if they are the original
 * creator of the template, or by a moderator with elevated privileges. This is
 * a hard delete operation that permanently removes the record and cannot be
 * undone.
 *
 * The operation validates that the template ID provided in the path parameter
 * corresponds to an existing notification template. If the requesting user is a
 * citizen, the system checks that the template was created by the same user
 * before allowing deletion. Moderator users can delete any template regardless
 * of ownership.
 *
 * Security considerations include preventing unauthorized deletion of system
 * templates and enforcing proper ownership verification.
 *
 * This operation is associated with the discussion_board_notification_templates
 * table and does not cascade to other tables since notification templates are
 * standalone definitional records.
 *
 * Related operations: GET /notifications/templates for listing templates, PUT
 * /notifications/templates/{templateId} for updating templates, POST
 * /notifications/templates for creating new templates.
 *
 * @param props.connection
 * @param props.templateId Unique identifier of the notification template to be
 *   deleted
 * @path /discussionBoard/citizen/notifications/templates/:templateId
 * @accessor api.functional.discussionBoard.citizen.notifications.templates.erase
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique identifier of the notification template to be deleted */
    templateId: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/discussionBoard/citizen/notifications/templates/:templateId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/discussionBoard/citizen/notifications/templates/${encodeURIComponent(props.templateId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("templateId")(() => typia.assert(props.templateId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
